### PR TITLE
FIX: missed changing unit of MISC to volts

### PR DESCRIPTION
**Pull request by dgwakeman**

### CODE REVIEW

**Comment by Eric89GXL** [comment]
I assume this is consistent with what Matti does in MNE-C?

**Comment by dgwakeman** [comment]
Yes, it was just a missed comment from @teonlamont 's contribution. (referred to here: #1932).

**Comment by agramfort** [comment]
why? isn't it an acquisition pb?

**Comment by dgwakeman** [comment]
Well, that is what acquisition will do, but the rename_channels refactor allows you to change a channel to a misc. Incorporated with that the code changes the units to the defaults @teonlamont selected. This just updates that so that the unit for misc is consistent with MNE-C conventions. As for the debate on changing units, the old code restricted this, but people wanted to open it up more to have more options.

**Comment by agramfort** [comment]
sorry I don't follow the situation you describe

**Comment by dgwakeman** [comment]
Sorry for my Proustian reply. This one is better delineated:

Yes, Neuromag MISC channels are in Volts.

@teonlamont added changes in #1932 to allow switching of channel types between many channel types some of which have different units. In that commit, MISC is erroneously set to be unit NONE. This commit fixes that.

You are correct that in acquisition (at least on Neuromag) this won't be a problem. However, if a user were to change for example a channel labelled as EMG to a MISC labelled channel #1932 would erroneously change the unit to NONE.

In the broader discussion of #1932 and the related issues, core developers preferred this arrangement to restricting changes to channels with the same unit only.

Clearer?

**Comment by agramfort** [comment]
Much clearer ;)

No objection then...

**Pull request merged**
