### PR TITLE
MRG: Fix dipole IO

### LINKED ISSUE #3244: Elekta xfit dipole file reader
@Eric89GXL it looks like the parsing of the xfit dipole file is prone to being botched likely due to how users decide to write out the `.dip` file (i.e. what fields to include). [Here](https://www.dropbox.com/s/hk3ez4512ml1168/All_157_RH.dip.txt?dl=0) is an e.g. dipole file; and the resulting `__dict__`

```
{'amplitude': array([  4.36000000e-08]),
 'gof': array([-5.8]),
 'name': None,
 'ori': array([[ 0.4587156 ,  0.16055046,  0.40825688]]),
 'pos': array([[ 0.0382,  0.0056,  0.0674]]),
 'times': array([ 0.363])}
```
`gof` and `amplitude` fields are off and I am not sure how the `ori` is being represented here.

### PR DESCRIPTION
**Pull request by Eric89GXL**
Moving toward fixing dipole text IO.

Closes #3244.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
@kambysese this should fix your Elekta dipole-reading problems.

Ready for review/merge from my end.

**Comment by Eric89GXL** [comment]
@agramfort you can review/merge this if you're happy

**Comment by Eric89GXL** [comment]
Oh wait, failures...

**Comment by agramfort** [comment]
thx @Eric89GXL

**Pull request merged**
