### PR TITLE
FIX: Safe not to have mayavi

### LINKED ISSUE #1741: FIX: mayavi imports tend to produce x server crashes on some mashines.
would be good to avoid trying mayavi imports by option

cc @fraimondo @mainakjas @agramfort

### PR DESCRIPTION
**Pull request by Eric89GXL**
Closes #1741.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
@fraimondo @dengemann can one of you see if this fixes report for you?

**Comment by Eric89GXL** [comment]
Ready for review/merge from my end

**Comment by agramfort** [comment]
I'll let @dengemann merge if he's happy

**Comment by dengemann** [comment]
Thanks @Eric89GXL 

cc @fraimondo

**Pull request merged**
