### PR TITLE
MAINT: Pin jsonschema to < 4 to avoid DeprecationWarning

### PR DESCRIPTION
**Pull request by hoechenberger**
See https://github.com/jupyter/nbformat/issues/232

### CODE REVIEW

**Review by agramfort — APPROVED** [review]
I think CI failure is unrelated

**Comment by hoechenberger** [comment]
CI error seems unrelated?

@agramfort @larsoner Could you have a look and merge if you're happy?

**Comment by larsoner** [comment]
FYI the preferred solution to me, already implemented in #9803 and #9800, is just to ignore the warning in conftest. It's not our problem and we know they'll probably fix it, so a simple ignore is less maintenance work for us here than a version pin we have to keep track of.

**Comment by hoechenberger** [comment]
Oh, ok, sounds like a reasonable approach too 😅

So … should this PR be reverted…?

**Comment by larsoner** [comment]
I'll fix it in #9803

**Pull request merged**
