### PR TITLE
MRG: Fix nonalphabetically sorted chan names for spatial_colors legend

### LINKED ISSUE #2694: BUG: something wrong with spatial_colors legend
Something wrong with the legend in files that should be fairly regular - no bad channels, all EEG ... but the legend colors seem completely random. (The line colors are fine!)

The tests look fine and another experiment of mine looks fine, it's only for some layouts.

unknown-34

I'll see if I can find what it's about, but I'm also attaching an evoked file that has the issue: [bad_example-ave.fif.gz](https://github.com/mne-tools/mne-python/files/59396/bad_example-ave.fif.gz)
@jaeilepp

### PR DESCRIPTION
**Pull request by jona-sassenhagen**
Works on my data, works on example, let's see what Travis says.

Closes #2694

### CODE REVIEW

**Comment by jasmainak** [comment]
can you squash the commits?

**Comment by jona-sassenhagen** [comment]
Can I do that over the web interface? I didn't bother to create a local branch.

**Comment by agramfort** [comment]
LGTM

+1 for merge if travis is happy

**Comment by jasmainak** [comment]
I don't know ... I don't use the web interface. Just fetch the commit locally and squash them:

```sh
git fetch upstream pull/2695/head:patch-5
git rebase -i HEAD~2
# change 'pick' -> 'squash' for second commit and edit the new commit message
git push -f origin patch-5
```

**Comment by Eric89GXL** [comment]
FYI you only need the first letter so to save time you can change `pick` to `s` :)

**Comment by jona-sassenhagen** [comment]
Okay I did that thing but I don't think it did what it was supposed to do ...

**Comment by jasmainak** [comment]
How did you fetch?

**Comment by jasmainak** [comment]
I do see only one commit now ...

**Comment by jona-sassenhagen** [comment]
Oh okay. Then it's good.

**Comment by jasmainak** [comment]
@jaeilepp is this fix okay?

**Comment by jaeilepp** [comment]
Yes. LGTM.

**Comment by agramfort** [comment]
merge when travis is green

**Comment by jona-sassenhagen** [comment]
Checks passed.

**Comment by Eric89GXL** [comment]
Thanks @jona-sassenhagen

**Comment by jasmainak** [comment]
thanks @jona-sassenhagen

**Pull request merged**
