### PR TITLE
ENH: Safer sys_info

### PR DESCRIPTION
**Pull request by larsoner**
One more to sneak into 1.0. Needs https://github.com/pyvista/pyvista/pull/2250 which will hopefully be merged soon.

### CODE REVIEW

**Comment by larsoner** [comment]
Okay, even without pyvista/pyvista#2250 I now get no segfaults even when I do something that causes one on `main` (setting DISPLAY to an invalid value):
```
$ mne sys_info
...
pyvista:          0.34.dev0 {OpenGL 4.5.0 NVIDIA 470.103.01 via NVIDIA GeForce GTX 650 Ti BOOST/PCIe/SSE2}
$ DISPLAY=:2 mne sys_info
...
pyvista:          0.34.dev0 {OpenGL could not be initialized}
```
This PR is actually even compatible with pyvista/pyvista#2250 , it just becomes redundant if they use it. So eventually we'll want to triage based on version once they release, which I've noted in the comments.

@hoechenberger feel free to merge if you're happy

**Comment by hoechenberger** [comment]
Amazing! @larsoner I can test this tomorrow before merging if you want?

**Comment by larsoner** [comment]
Sure, sounds like we should wait for Dipy to release this weekend / early next week so that our installers can use Python 3.10 anyway. So a tomorrow merge on this is no problem

**Comment by larsoner** [comment]
@hoechenberger we need this for #10391 -- any chance you could test and merge?

**Comment by hoechenberger** [comment]
Will have a look probably tomorrow!

**Comment by larsoner** [comment]
I have tested this on a few platforms -- including Linux where I used a bad DISPLAY that I know causes a segfault on `main` -- so I'll go ahead and merge this for 1.0

**Pull request merged**
