### PR TITLE
website theme updates

### LINKED ISSUE #10767: Changed color scheme?
Hello, I'm not sure if this was introduced upstream in our theme or we did that ourselves, but I don't really like the new colors here:

Screen Shot 2022-06-15 at 14 19 50

Aside from the reduced contrast compared to what we had before for headlines, now links and headlines have the same color, so I caught myself actually clicking on headlines a few times, believing that's some sort of hyperlink. I don't think this is a great choice of colors.

### PR DESCRIPTION
**Pull request by drammock**
WIP / do not merge. Working on consistency with upstream theme enhancements.

closes #10767

### CODE REVIEW

**Comment by drammock** [comment]
should wait for https://github.com/pydata/pydata-sphinx-theme/pull/836 before merging here.

**Comment by drammock** [comment]
Here are the major changes in this PR:

- [Homepage:](https://output.circle-artifacts.com/output/job/e555eda6-59bd-4824-9835-c2585a39710e/artifacts/0/dev/index.html) funder and supporting-institution logos are now responsive to light/dark mode (except ICM and Paris/Saclay CDS, couldn't find vector versions of those).
- tabbed interface (e.g., [here](https://output.circle-artifacts.com/output/job/e555eda6-59bd-4824-9835-c2585a39710e/artifacts/0/dev/install/installers.html)) has better colors (not faded out; consistent hover color).
- dropdowns (e.g., [on this page](https://output.circle-artifacts.com/output/job/e555eda6-59bd-4824-9835-c2585a39710e/artifacts/0/dev/install/check_installation.html)) now get proper styling if you specify a semantic color like `danger` or `info`
- sidebars can now be styled like admonitions, by simply adding a `sidebar` class to the admonition. There's a warning sidebar in [this section](https://output.circle-artifacts.com/output/job/e555eda6-59bd-4824-9835-c2585a39710e/artifacts/0/dev/install/updating.html#upgrading-to-the-development-version).

Still TODO:
- homepage quick links card has bad background color on dark theme.

**Comment by drammock** [comment]
OK, ready for review.

- [homepage](https://output.circle-artifacts.com/output/job/4f7af46c-6521-4873-bce3-113c98767217/artifacts/0/dev/index.html) (try toggling light/dark mode and watch the icons change!)
- [installers page](https://output.circle-artifacts.com/output/job/4f7af46c-6521-4873-bce3-113c98767217/artifacts/0/dev/install/installers.html) (better styling on the OS tabs)
- [check install page](https://output.circle-artifacts.com/output/job/4f7af46c-6521-4873-bce3-113c98767217/artifacts/0/dev/install/check_installation.html) (note the color styling on dropdowns)
- [updating page](https://output.circle-artifacts.com/output/job/4f7af46c-6521-4873-bce3-113c98767217/artifacts/0/dev/install/updating.html#upgrading-to-the-development-version) (note the admonition-styled sidebar)

**Comment by cbrnr** [comment]
Beautiful!

Re light/dark, the Uni Graz logo moves 1 pixel up when switching to dark mode. Or is this just me?

The dark icon for Discourse looks strangely yellow, is this how it should be?

**Comment by larsoner** [comment]
> Re light/dark, the Uni Graz logo moves 1 pixel up when switching to dark mode. Or is this just me?

It moves for me, too. Worth fixing if it's easy but if not I don't think it's a blocker. (My guess is that it's actually the size of one of the other logos -- BIDS maybe? -- changing the vertical centering, but who knows.)

+1 for merge and iterating more later

**Comment by cbrnr** [comment]
Yes, the BIDS logos seem to be different sizes. Definitely not a blocker though if it's too much work to fix now.

**Comment by drammock** [comment]
OK I'll merge, and I'll see about getting a vector version of BIDS logo to fix it in a later PR.

**Pull request merged**
