### PR TITLE
MNT: window and layout in GUI API

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR refactors `_QtWindow`:
* adds support for custom central layout
* adds `_window_create` to spawn a window 'without pyvista support' (instance of `_MNEMainWindow`)
* ~adds the option `theme_support` to opt-out from automatic theming~

and `_QtLayout`:
* adds support for grid layout

Here is a code snippet to try:

```py
from mne.viz.backends.renderer import _get_renderer

renderer = _get_renderer()
renderer.show()

window = renderer._window_create()
window.show()
```

Further consideration:
* With more refactoring it should be possible to use `_get_renderer()` to spawn `_MNEMainWindow` instead of using `_PyVistaRenderer`. This more important matter is about about having a GUI API which does not depends on `pyvista`.

It's an item of https://github.com/mne-tools/mne-python/pull/10565

### CODE REVIEW

**Comment by larsoner** [comment]
Sounds reasonable, let me know when to look!

**Comment by GuillaumeFavelier** [comment]
This is delayed until https://github.com/mne-tools/mne-python/pull/10565#issuecomment-1132687477 is resolved.

**Comment by larsoner** [comment]
Okay, let me know what PR to review whenever one of them is ready

**Comment by GuillaumeFavelier** [comment]
Assuming the CIs return green, this is ready for review @larsoner

**Comment by GuillaumeFavelier** [comment]
The failure on `Test Windows 3.9 pip` does not seem related:

```
================================== FAILURES ===================================
________________ test_spatio_temporal_cluster_adjacency[Numba] ________________
mne\stats\tests\test_cluster_level.py:576: in test_spatio_temporal_cluster_adjacency
    spatio_temporal_cluster_test([data1_2d, data2_2d],
<decorator-gen-336>:12: in spatio_temporal_cluster_test
    ???
mne\stats\cluster_level.py:1357: in spatio_temporal_cluster_test
    return permutation_cluster_test(
<decorator-gen-333>:12: in permutation_cluster_test
    ???
mne\stats\cluster_level.py:1123: in permutation_cluster_test
    return _permutation_cluster_test(
mne\stats\cluster_level.py:983: in _permutation_cluster_test
    H0 = parallel(
mne\utils\progressbar.py:157: in __exit__
    os.remove(self._mmap_fname)
E   PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\tmp_mne_progky0ehjn_'
--------------- generated xml file: D:\a\1\s\junit-results.xml ----------------
```

**Comment by larsoner** [comment]
That looks like a replication of https://github.com/mne-tools/mne-python/issues/10648 on CIs, the first time I've seen it! Agreed it's unrelated, though

**Pull request merged**
