### PR TITLE
Fix names for train/test arrays in plot_gat_matrix

### PR DESCRIPTION
**Pull request by mvdoc**
I was looking through the code for `plot_gat_matrix` and I saw this inconsistency in naming. Feel free to ignore this PR if you consider it too nitpicky ;)

### CODE REVIEW

**Comment by agramfort** [comment]
@kingjr ok for you?

if so please merge

**Comment by jasmainak** [comment]
LGTM

**Comment by agramfort** [comment]
@mvdoc please rebase to check that CIs are happy

**Comment by mvdoc** [comment]
@agramfort done, let's see :-)

**Comment by kingjr** [comment]
LGTM, Thanks @mvdoc

**Pull request merged**
