### PR TITLE
Reorg examples

### LINKED ISSUE #2099: ENH/DOC: more structure to and cleanup examples in the general section
- section on data io
- Unify reading and plotting examples,
e.g. read vs estimate copvariance
- MEG processing
- advanced processing
- forward / MRI stuff

### PR DESCRIPTION
**Pull request by agramfort**
big reorg... sorry...

EDIT by Eric89GXL:

Closes #2099.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
@agramfort also ignore CI feedback here, I killed a build or two to prevent clogging up the build bots

I will run `make flake` locally before merge

**Comment by Eric89GXL** [comment]
So now our only two root-level examples are:

plot_extract_events_from_raw.py
plot_from_raw_to_epochs_to_evoked.py

I think we should have a third, namely how to go from evoked to a SourceEstimate using forward calculation + inverse calculation. MNE is the name of the package after all :) WDYT?

**Comment by Eric89GXL** [comment]
Otherwise LGTM, thanks for tackling this

**Comment by Eric89GXL** [comment]
I added a `closes` tag for you

**Comment by agramfort** [comment]
>
> I think we should have a third, namely how to go from evoked to a
> SourceEstimate using forward calculation + inverse calculation. MNE is the
> name of the package after all :) WDYT?


done

**Comment by Eric89GXL** [comment]
Done at your end @agramfort? I think I'm happy. @dengemann do you have a minute to look? I found it easiest to look at the file view of the latest commit:

https://github.com/mne-tools/mne-python/tree/afa5df6e77499c8c707a13cbc0e951c77d07fe40/examples

**Comment by agramfort** [comment]
yes done

@dengemann is updating the mailmap

**Comment by Eric89GXL** [comment]
@agramfort I added a simple redirecting `index.html`, you should see it very briefly if you go to https://mne-tools.github.io.

**Comment by agramfort** [comment]
perfect

this reorg branch builds fine on my box

**Comment by Eric89GXL** [comment]
@dengemann want to have a quick look before I merge?

**Comment by dengemann** [comment]
Taking a look now.

**Comment by dengemann** [comment]
looks good on my box, merging.

**Comment by dengemann** [comment]
Thanks @agramfort

**Pull request merged**
