### PR TITLE
Just a test of PyQt, please ignore

### PR DESCRIPTION
**Pull request by hoechenberger**
See https://github.com/conda-forge/mne-feedstock/pull/22

### CODE REVIEW

**Comment by larsoner** [comment]
This will not work, `conda` calls it `pyqt` but `pip` calls it `pyqt5`. Locally I see:
```
$ pip install pyqt
ERROR: Could not find a version that satisfies the requirement pyqt (from versions: none)
ERROR: No matching distribution found for pyqt
$ pip install pyqt5
Requirement already satisfied: pyqt5 in /Users/larsoner/anaconda3/lib/python3.7/site-packages (5.13.0)
Requirement already satisfied: PyQt5_sip<13,>=4.19.14 in /Users/larsoner/anaconda3/lib/python3.7/site-packages (from pyqt5) (4.19.18)
```
And if you look at the [macOS](https://travis-ci.org/mne-tools/mne-python/jobs/636366905#L586-L587) or [Linux](https://travis-ci.org/mne-tools/mne-python/jobs/636366904#L687-L688) Travis logs you see it does not work (but note that the macOS travis config has a special line to call `pip install pyqt5 >= 5.10 so it [does do it eventually](https://travis-ci.org/mne-tools/mne-python/jobs/636366905#L602-L603).

**Comment by larsoner** [comment]
Pushed a commit to change it to `pyqt5`

**Comment by hoechenberger** [comment]
Hah, had forgotten about the difference in naming. Thanks for fixing this up, @larsoner

**Comment by larsoner** [comment]
Okay looks like things on Linux are already problematic

https://travis-ci.org/mne-tools/mne-python/jobs/636390545

**Comment by larsoner** [comment]
If you want to explore the CI rabbit hole, we could add `conda-forge` as a channel and see if we can do `pyqt>=5.10` in the `conda` list rather than the `pip` list. Or we can close and come back to this in another year :)

**Comment by hoechenberger** [comment]
I guess there's some weird interactions between `conda`- and `pip`-installed `PyQt` versions anyway, eh? Mmh.

**Comment by larsoner** [comment]
I think it's more deficiencies in `pyqt5` on PyPi, as we have to jump through hoops on CircleCI which uses just `pip` (no `conda`):

https://github.com/mne-tools/mne-python/blob/master/.circleci/config.yml#L62-L67

**Comment by larsoner** [comment]
(or more likely,  installing this package pulls in some system dependencies that are needed to run PyQt5 -- if we could isolate just those and install them, then it's likely we could install those packages in Travis and Circle and then more easily use the conda-forge updated version)

**Comment by hoechenberger** [comment]
Ok we could certainly try with pyqt from conda-forge then. I may look into this later tonight.

**Comment by larsoner** [comment]
Latest PyQt5 works on my Windows VM and in #7202 I figured out what package was actually needed to use PyQt5 from `pip`, so I'm optimistic that a rebase after that is merged might actually work here

**Comment by larsoner** [comment]
(If it does, then you should also update `doc/install/mne_python.rst` to get rid of the special PyQt5 instructions for macOS since they will no longer be necessary!)

**Comment by hoechenberger** [comment]
@larsoner rebased on `master` and force-pushed, let's see

**Comment by agramfort** [comment]
can we close https://github.com/mne-tools/mne-python/pull/7201 @hoechenberger ?

**Comment by hoechenberger** [comment]
I think I'll close for now and potentially re-open if I ever get back to working on this.

**Pull request closed without merging**
