### PR TITLE
fix icon link colors

### LINKED ISSUE #12285: Twitter logo in docs should not be colored
Twitter is the only colored icon on our docs website:

Screenshot 2023-12-08 at 23 05 51

It should be gray like all the other icons.

### PR DESCRIPTION
**Pull request by drammock**
closes #12285

### CODE REVIEW

**Review by agramfort — APPROVED** [review]

**Comment by drammock** [comment]
results:

Screenshot 2023-12-18 at 10-07-25 Computation times — MNE 1 7 0 dev45 ga27da3a6b documentation


Screenshot 2023-12-18 at 10-05-30 Computation times — MNE 1 7 0 dev45 ga27da3a6b documentation

**Comment by drammock** [comment]
windows pip-pre is failing on the `print config` step. Same failure today (after restarting) and last Friday. The error msg is not very informative:

```
"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\1f58f2bd-d074-4b82-af8b-1ca9aa287737.cmd""
##[error]Cmd.exe exited with code '-1073741819'.
```

anyone with a windows machine able to reproduce this with `mne sys_info -pd`?

**Comment by larsoner** [comment]
All PRs are failing that way. I should be able to look tomorrow

**Comment by larsoner** [comment]
Thanks @drammock !

**Pull request merged**
