### PR TITLE
MRG: Improve toolbar icon consistency

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
The goal of this PR is to improve the consistency of the toolbar icons.

With the current resolution (18dp) the amount of information contained in one icon is limited. So far, I did not manage to manually modify for example the movie icon [to add a floppy disk](https://github.com/mne-tools/mne-python/pull/7612#issuecomment-614687019) that we can notice.

This is what I suggest for the movie icon for now based on https://github.com/mne-tools/mne-python/pull/7612#issuecomment-615113999:

master | image
--- | ---
**PR** | image

This is still a work in progress. I plan to upscale the icons to 48dp and maybe give more space for the toolbar.

**ToDo**

- [x] Resize the new movie icon (suggested in https://github.com/mne-tools/mne-python/pull/7698#issuecomment-621258820)

**Ideas**

* Use vertical separator (suggested in https://github.com/mne-tools/mne-python/pull/7698#issuecomment-621262734)

**Known issue**

I had to move `mne.qrc` at the root directory to update `resources.py`

This is an item of #7162

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
Any suggestion is of course welcome @larsoner, @agramfort, @hoechenberger

**Comment by larsoner** [comment]
I can live without the floppy disk

**Comment by GuillaumeFavelier** [comment]
> hope you can see what I mean in this screenshot

Yes, it's all clear :+1: 

Feel free to share any comment related to those icons. I want to take care of that in this PR.

**Comment by hoechenberger** [comment]
> Feel free to share any comment related to those icons.

😍

is all I can say ;)

**Comment by hoechenberger** [comment]
Not sure if that makes sense in this PR, but I think adding a few vertical separators (or horizontal space?) between "associated" groups of icons could be a good idea too. Not so certain about the actual grouping yet, though!!

**Comment by GuillaumeFavelier** [comment]
It's as easy as using `addSeparator`. What would be the grouping?

1) screenshot, movie
2) visibility, play
3) auto-scale, restore
4) clear, help

**Comment by GuillaumeFavelier** [comment]
For horizontal spacing, I'll have to investigate

**Comment by hoechenberger** [comment]
> It's as easy as using `addSeparator`. What would be the grouping?
> 
> 1. screenshot, movie
> 2. visibility, play
> 3. auto-scale, restore
> 4. clear, help

I would need to think about that… and maybe do a mockup. Please don't consider this a blocker for this PR!

**Comment by GuillaumeFavelier** [comment]
I fixed the size of the movie icon.

And if the floppy disk is not required anymore I think I don't need to upscale the icons anymore.

I'll see what I can do for `mne.qrc` and this should be good to go.

**Comment by hoechenberger** [comment]
Thanks @GuillaumeFavelier

**Pull request merged**
