### PR TITLE
[MRG] fix for neuroone brain vision files

### LINKED ISSUE #5333: Support for reading brainvision exported from NeurOne Tesla amplifier
The Bittium NeurOne recording software is using some alternative spelling in their BrainVision export (.vhdr/.vmrk) files causing reading in MNE to fail, in order to enable reading of these I made some minimal changes to brainvision.py.
One could argue that the files should rather be fixed by Bittium - however reading via EEGLAB and fieldtrip work fine.
The changes are commented in the attached file, which I can push to git if desired.

Regards,
Kristoffer H. Madsen
Danish Research Centre for Magnetic Resonace
[brainvision.txt](https://github.com/mne-tools/mne-python/files/2185116/brainvision.txt)

### PR DESCRIPTION
**Pull request by agramfort**
fixes #5333

cc @Kstoffer can you check if I did not forget anything?

### CODE REVIEW

**Comment by Kstoffer** [comment]
Well that part of the code works fine, however another commit to include info['meas_date'] in the meantime broke the support as NeurOne always reports '00000000000000000000'.
changing line 479: 
if match: 
into:
if match and '00000000000000000000'.find(match[0])<0:
makes it work again.

The NeurOne export seems to be a bit of a mess.

Regards,
Kristoffer

**Comment by agramfort** [comment]
You need to provide us a small test file otherwise we cannot guarantee long term support. Can you share one?

**Comment by agramfort** [comment]
pushed @Kstoffer let me know what you think.

Sorry I had missed the data you had shared.

**Comment by agramfort** [comment]
all green @Kstoffer

**Comment by agramfort** [comment]
@Kstoffer ready to go from your end?

**Comment by Kstoffer** [comment]
Yes works great, thanks a lot.

**Comment by larsoner** [comment]
Thanks @agramfort

**Pull request merged**
