### PR TITLE
MRG, ENH: Move up to 3.8

### PR DESCRIPTION
**Pull request by larsoner**
Bumps up to 3.8 on CircleCI and Travis because the vtk9.0.0.rc3 wheels are available.

Let's see if the CIs are happy with it!

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
I'm working on a fix for the issue in `_Brain` with VTK9. I'll open the PR soon

**Comment by GuillaumeFavelier** [comment]
I believe https://github.com/mne-tools/mne-python/pull/7675 will help with that

**Comment by larsoner** [comment]
Full build complete without errors:

https://19654-1301584-gh.circle-artifacts.com/0/dev/index.html

I'll rebase, push-force and then once it comes back green I'll merge and we'll be testing 3.8 finally!

**Comment by agramfort** [comment]
great !

>

**Pull request merged**
