### PR TITLE
Fix eeglab.py, an error for read annotations in `RawEEGLab`

### PR DESCRIPTION
**Pull request by frostime**
In `io.eeglab.RawEEGLab`, read annotations should also pass argument `uint16_codec`.

#### Reference issue

This problem has been reported in the group, click link for details:

https://mne.discourse.group/t/bug-report-an-error-in-io-eeglab-and-solution-to-it/7173

#### What does this implement/fix?

Merely by passing the correct codec argument to function call.

#### Additional information

No

### CODE REVIEW

**Review by agramfort — APPROVED** [review]

**Comment by agramfort** [comment]
@frostime can you merge the upstream main branch here so the CI can be green and we could merge?

thanks a lot for taking the time @frostime

**Comment by frostime** [comment]
> @frostime can you merge the upstream main branch here so the CI can be green and we could merge?
> 
> thanks a lot for taking the time @frostime

Hello, I'm a bit confused cause I've sync to the main branch before launching this pr,  what do you mean by saying "merge the upstream main branch here"?

image

**Comment by frostime** [comment]
Oh no, I add new commits to re launch the ci, but it seems that there still some error.
image

Mr. @agramfort , if this pr bother you too much, I think you can merely close this pr, and make changes at your branch.

The only changes in this pr is merely add `uint16_codec` parameter to read_annotations

image

**Comment by larsoner** [comment]
@frostime can you update `doc/changes/latest.inc` using `:newcontrib:` and add a URL to `doc/changes/names.inc`? Or alternatively let us know what name/URL you prefer to use to get credit for your change and we can push a quick commit to do it then merge, thanks!

**Comment by frostime** [comment]
> @frostime can you update `doc/changes/latest.inc` using `:newcontrib:` and add a URL to `doc/changes/names.inc`? Or alternatively let us know what name/URL you prefer to use to get credit for your change and we can push a quick commit to do it then merge, thanks!

Hello, sorry that I'm not familiar with the `mne` dev pipeline and don't know what is `:newcontrib:`. 
It would be nice of you if you could help me to fill the required information, shown as follow:

- My names: Yiping Zuo
- My url: https://github.com/frostime

Appreciate your dedication, thanks! 👍

**Comment by drammock** [comment]
sorry @larsoner I enabled auto-merge without requesting changelog entry. @frostime I'll do the changelog in another PR.

**Pull request merged**
