### PR TITLE
[MRG] Add data loader functions for BESA files

### LINKED ISSUE #9238: Support BESA .mul file format
#### Describe the new feature or enhancement
There was a request on Discord from @sinthemaroy to support `.mul` format.  It's an ASCII format for channel data put out by BESA, described here: http://wiki.besa.de/index.php?title=ASCII_File_Format

@sinthemaroy unfortunately cannot share their data files for testing, so we'll need to work up a fake data file based on the published standard.

### PR DESCRIPTION
**Pull request by wmvanvliet**
Implementing file readers for BESA .avr and .mul files, which are simple text files containing evokeds as produces by the BESA analysis software. Needs testing.

closes #9238, #10908

Todo:
 - [x] Support for .avr files
 - [x] Support for .mul files
 - [x] Add entry to what's new (will do this after this PR is cleared for merge otherwise)

### CODE REVIEW

**Comment by wmvanvliet** [comment]
@massich This PR messes with your BESA `.elp` montage file loader. Could you have a look?

**Comment by larsoner** [comment]
@wmvanvliet IIRC @massich has moved on to other projects/domains so I would proceed without a review. I think we can trust that tests were implemented well enough that we can go based on what they tell us

**Comment by agramfort** [comment]
I would have just put the testing files in the mne-testing-data

**Comment by wmvanvliet** [comment]
They are only a few kb each.

**Pull request merged**
