### PR TITLE
ENH: Add automerge

### PR DESCRIPTION
**Pull request by larsoner**
It looks like we don't need to use [bulldozer](https://github.com/palantir/bulldozer) to get automerge. (@hoechenberger I did look into conda-forge -- they have [their own action](https://github.com/conda-forge/automerge-action) FYI). GitHub provides this natively, but we need to set up branch protection rules saying that status commits must pass -- and for this, we need better / more specific GH actions job names, which I've added here. Then I'll add branch protection rules (that can always be ignored by maintainers, as this is needed from time to time) and then there should be a button added to PRs that says "squash+merge once status checks pass" or so:

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request#enabling-auto-merge

### CODE REVIEW

**Comment by hoechenberger** [comment]
Nice!!

**Comment by larsoner** [comment]
Here is an example of the protected interface, before the statuses started popping up:

Screenshot from 2022-03-21 11-34-58

So you can see the ability to override is still there. And now with the statuses:

Screenshot from 2022-03-21 11-36-45

The names got a tiny bit longer and redundant, which I don't love -- but it's necessary for the branch protection rules. Also, GH actions supports restarting just failed jobs nowadays, so we might consider consolidating into a single "tests" config, or at least merging the most redundant ones (probably macos conda + linux conda or so) at some point.

**Comment by hoechenberger** [comment]
I don't like that I wouldn't be able to merge if a test fails … we've had longer-lasting issues with Circle in the past before, for example. Also I hope codecov is exempt from this too..?

Screen Shot 2022-03-21 at 16 54 01

**Comment by larsoner** [comment]
> I would disable this for Circle docs and linkcheck…

I would not disable for CircleCI. That is actually one of the ones that I have to push hotfixes for most frequently.

What we can do instead is move you into the correct permissions tier (probably admin?) to allow you to ignore the checks, like you see in my screenshots.

**Comment by larsoner** [comment]
@hoechenberger you should have the option to bypass now

**Comment by hoechenberger** [comment]
Merci!

**Pull request merged**
