### PR TITLE
MRG: Use latest version 0.23.0 of pyvista instead of master

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR updates the package requirements for the pyvista 3d backend.

### CODE REVIEW

**Comment by larsoner** [comment]
To save us some potential post-merge pain, can you push a commit with `[circle full]` in the message so we can make sure everything works before merging?

**Comment by GuillaumeFavelier** [comment]
I've bult the `doc` locally with `MNE_3D_BACKEND=pyvista make html_dev` but I can't reproduce [Circle issue](https://circleci.com/gh/mne-tools/mne-python/17254?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link):
```
...
generating gallery for auto_examples/connectivity... [ 55%] plot_mne_inverse_envelope_correlation.py
Makefile:44: recipe for target 'html_dev' failed
make: *** [html_dev] Terminated

Too long with no output (exceeded 10m0s): context deadline exceeded
```

**Comment by GuillaumeFavelier** [comment]
The merge with `master` didn't solve this one.

**Comment by GuillaumeFavelier** [comment]
[This time](https://circleci.com/gh/mne-tools/mne-python/17258?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) with:

```
...
generating gallery for auto_examples/connectivity... [ 22%] plot_mixed_source_space_connectivity.py
Makefile:44: recipe for target 'html_dev' failed
make: *** [html_dev] Terminated

Too long with no output (exceeded 10m0s): context deadline exceeded
```

**Comment by GuillaumeFavelier** [comment]
But Travis is happy now

**Comment by agramfort** [comment]
I've tried to restart the build.

@GuillaumeFavelier can you do a test of mprof on the example that fails?

**Comment by GuillaumeFavelier** [comment]
Circle displays the current script or the last script executed with success? Because I don't think `plot_mixed_source_space_connectivity.py` uses the pyvista 3d backend.

**Comment by GuillaumeFavelier** [comment]
Everything seems fine on the previous version.

Azure has a [http error](https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=4870&view=logs&j=20ec0733-a031-5a42-425a-ca7f9f76ad75&t=87d26a1d-3b73-59fb-0483-60acfaa9bf89&l=1025): `http.client.IncompleteRead: IncompleteRead(319488 bytes read)`

**Comment by GuillaumeFavelier** [comment]
Result available here: https://17262-1301584-gh.circle-artifacts.com/0/dev/index.html

**Comment by agramfort** [comment]
so we have a regression with pyvista 0.23 :(

>

**Comment by GuillaumeFavelier** [comment]
After investing some `[circle full]` time, my guess is that the regression is related to https://github.com/pyvista/pyvista/commit/5b5a09d70579a2f34ae2344f7596196dc0244703. At least, I can say that everything works fine until this one. This work introduces `auto_update=True` to the `BackgroundPlotter` and `QtInteractor`.

Let's go back on `pyvista==0.23.0` and try again with `auto_update=False`.

**Comment by GuillaumeFavelier** [comment]
The results are available: https://17307-1301584-gh.circle-artifacts.com/0/dev/index.html

AFAIK, https://github.com/pyvista/pyvista/pull/509#issue-354247887 helps for embedding a plotter as a qt widget, this is not something we're interested in here so keeping `auto_update=False` is fine by me.

I think this PR is ready for reviews now @agramfort, @larsoner

**Comment by agramfort** [comment]
Awesome Thx @GuillaumeFavelier

**Pull request merged**
