### PR TITLE
MRG, DOC: Clearer EEG doc

### PR DESCRIPTION
**Pull request by larsoner**
Document more clearly what these options mean.

### CODE REVIEW

**Comment by larsoner** [comment]
@christian-oreilly would this have saved you some pain?

https://18089-1301584-gh.circle-artifacts.com/0/dev/generated/mne.viz.plot_alignment.html#mne.viz.plot_alignment

**Comment by larsoner** [comment]
@drammock feel free to merge if you're happy with this, too

**Comment by larsoner** [comment]
(CI failures are spurious and unrelated)

**Comment by drammock** [comment]
tx @larsoner

**Pull request merged**
