### PR TITLE
Add Scanner Info & Layout for Macquarie Adult KIT MEG System

### PR DESCRIPTION
**Pull request by neurofractal**
Addresses Issue #5280 

1) I have updated the scanner information in mne.io.kit.constants

2) I have created new layout file for KIT system with 160 MEG channels. These changes have been tested with data from the scanner.

CC @paulsowman @monkeyman192

### CODE REVIEW

**Comment by paulsowman** [comment]
Any possibility of a 125 (child) channel layout?

**Comment by neurofractal** [comment]
@paulsowman yes that's the next job 👍

**Comment by paulsowman** [comment]
**@neurofractal** Sweet.

**Comment by agramfort** [comment]
You have line endings problems. Bad character is used. See Travis log

Can you also add a Whats new entry for the doc ? Thx

**Comment by agramfort** [comment]
i took over at https://github.com/mne-tools/mne-python/pull/5314/files
as you still had line endings pbs.

next time do not open a PR from your master branch as it prevents me from pushing directly to your branch to help you on your PR.

thanks

**Pull request closed without merging**
