### PR TITLE
Improve add_channels() docstrings

### LINKED ISSUE #11106: add_channels() documentation is difficult to understand
I just wanted to use `Raw.add_channels()`, so I looked at the API docs and even though I'm a developer, it actually took me a couple of seconds to even understand what **could** probably be meant, and still I think I'll have to take a look at the code to get a better understanding:

Screen Shot 2022-08-28 at 17 00 00

- What is `self`
- What is meant by, "Must contain the same type as the current object" (actually I'm still unsure, I'll probably have to look at the code to figure it out)
- "force the info objects ... to match the values in self". I have absolutely no clue what that means.
- Why does it say it can return Raw, Evoked, or Epochs – I was looking it up for Raw at https://mne.tools/stable/generated/mne.io.Raw.html#mne.io.Raw.add_channels, and I don't think my Raw is suddenly gonna get turned into an Epoch by this method, no?

I believe we're making bad use of the docdict here, avoiding redundancy but making the docs effectively useless because they're too weird and hard to understand.

Didn't we recently have a somewhat similar case where we ended up with a way to improve things?

### PR DESCRIPTION
**Pull request by hoechenberger**
Fixes #11106

### CODE REVIEW

**Comment by hoechenberger** [comment]
Docs for

- [Epochs](https://output.circle-artifacts.com/output/job/51cb8b78-e031-483c-be0a-38fb2f51b259/artifacts/0/dev/generated/mne.Epochs.html#mne.Epochs.add_channels)
- [Evoked](https://output.circle-artifacts.com/output/job/51cb8b78-e031-483c-be0a-38fb2f51b259/artifacts/0/dev/generated/mne.Evoked.html?highlight=add_channels#mne.Evoked.add_channels)
- [Raw](https://output.circle-artifacts.com/output/job/51cb8b78-e031-483c-be0a-38fb2f51b259/artifacts/0/dev/generated/mne.io.Raw.html?highlight=add_channels#mne.io.Raw.add_channels)
- [Spectrum](https://output.circle-artifacts.com/output/job/51cb8b78-e031-483c-be0a-38fb2f51b259/artifacts/0/dev/generated/mne.time_frequency.Spectrum.html?highlight=add_channels#mne.time_frequency.Spectrum.add_channels)

**Comment by drammock** [comment]
@hoechenberger and I just discussed this during office hours, and we're not happy with the current state of this PR --- it's better for users but extremely non-DRY.  We looked around for solutions; [this SO post](https://stackoverflow.com/q/55187122/1664024) describes our situation, but has no answers :(  However, it does offer a promising suggestion in one of the comments: use type hints to specify "returns same type as `self`".  Hopefully this will work (and not, e.g., say that it returns the `Mixin` class!) Curious what others think about this possible solution. Other ideas are welcome too.

**Comment by hoechenberger** [comment]
> use type hints to specify "returns same type as `self`". Hopefully this will work (and not, e.g., say that it returns the `Mixin` class!) Curious what others think about this possible solution

Yep, this works. It's a bit clumsy until [PEP 673](https://peps.python.org/pep-0673/) gets implemented with Python 3.11, but it's possible today:

```python
# typing-test.py
from typing import TypeVar

MixinT = TypeVar("MixinT", bound="Mixin")

class Mixin:
    def foo(
        self: MixinT
    ) -> MixinT:
        return self

class A(Mixin):
    pass


class B(A, Mixin):
    pass


a = A()
b = B()

reveal_type(a.foo())
reveal_type(b.foo())
```
Running this through `mypy typing-test.py` produces:
```
typing-test.py:22: note: Revealed type is "typing-test.A"
typing-test.py:23: note: Revealed type is "typing-test.B"
Success: no issues found in 1 source file
```
So this reveals to correct types!

**Comment by mmagnuski** [comment]
I like the changes how they are now, I'm not sure investing too much time in reducing the text overlap is really worth it.
You can always go back to saying "self" instead of mentioning correct object type. ;D

**Pull request closed without merging**
