### PR TITLE
Bit 17 - EDF

### PR DESCRIPTION
**Pull request by lennyvarghese**
Issue #2575.

### CODE REVIEW

**Comment by agramfort** [comment]
@teonlamont how does that sound for you?

**Comment by teonlamont** [comment]
it sounds fine. I was just remembering one of the research lab I was working with just got a 24-bit DIO card for triggering. Their stimulus channel would also benefit from a change to 2**24 - 1.
I am wondering how necessary it is to have mask values on this channel. 

I am ok with the 17th bit increase.

**Comment by agramfort** [comment]
if you think it will not break existing code please merge.

**Comment by agramfort** [comment]
ok @teonlamont merging then.

thanks @lennyvarghese

**Pull request merged**
