### PR TITLE
Remove appveyor

### PR DESCRIPTION
**Pull request by massich**
This is how it rends in my fork:
image

### CODE REVIEW

**Comment by cbrnr** [comment]
Do you really want to change this right now? The Azure jobs is always red in my PRs (and it seems also in this here). I'd wait until this is fixed.

**Comment by agramfort** [comment]
yes we need to be sure azure alternative is ok. I thought it was...

>

**Comment by massich** [comment]
For me it works on the PRs but it does weird stuff in master

**Comment by larsoner** [comment]
@massich can you rebase and try pushin a few empty commits with `[skip travis] [skip appveyor] [skip circle]'? (I don't think Azure has auto-cancellation, so pushing them all in a row should probably be okay.) I think now the download timeouts on Azure should hopefully be fixed, and seeing a few commits after rebase with green Azure checks would help gain confidence.

**Comment by massich** [comment]
I guess that this would also work in master. (I'll merge we can always revert)

**Pull request merged**
