### PR TITLE
BUG: Fix bug with nan handling

### PR DESCRIPTION
**Pull request by larsoner**
As an intellectual challenge I followed https://github.com/mne-tools/mne-python/issues/10996#issuecomment-1203239429 to its conclusion, but happy to use @mmagnuski's version instead if it works the same or better!

### CODE REVIEW

**Comment by mmagnuski** [comment]
+1, I first wanted to follow a similar path, but then incorrectly thought that the number of nans will be the same (summing along the last dimension) cause I didn't consider epochs. This is better. :)

**Review by drammock — APPROVED** [review]
I had started on my own attempt earlier this afternoon, but gave up after realizing (like @mmagnuski did) that my attempt wouldn't handle epochs cleanly.  Thanks for saving the day again @larsoner

**Comment by chapochn** [comment]
Regarding the epochs: in my understanding, when the input are epochs, there is no averaging happening anyway (even if the option average is non None): `if input is of type Epochs, then psds will be of shape (n_epochs, n_channels, n_freqs)` in https://mne.tools/dev/generated/mne.time_frequency.psd_welch.html.
Would be nice to add the possibility of averaging between epochs though.

**Comment by mmagnuski** [comment]
@chapochn The welch windows are averaged (this is what `average` argument controls, perhaps this could be clarified in the docs), to average epochs currently you have to average that dimension of the output psd array yourself.

**Comment by chapochn** [comment]
@mmagnuski "to average epochs currently you have to average that dimension of the output psd array yourself." 

Yes, that's what I was referring to - might be a useful to have the median_bias publicly available when doing the median averaging of epochs ourselves

**Pull request merged**
