### PR TITLE
[ENH, MRG] Add coregistration video and execute GUI in tutorial to show window & add show and block to GUIs

### PR DESCRIPTION
**Pull request by alexrockhill**
Fixes https://github.com/mne-tools/mne-python/issues/9451, fixes https://github.com/mne-tools/mne-python/issues/10801.

### CODE REVIEW

**Comment by alexrockhill** [comment]
Alright! A bit of the code is a tiny bit inelegant but that will be fixed with future PRs that slightly refactor the window classes so that they don't depend on the 3D renderer, harmonizing between the `coreg` & `brain` GUIs and the `ieeg_locate` GUI. For now, I think this is great, the video looks good and the GUI is scraped and appears in the docs, real progress I think https://output.circle-artifacts.com/output/job/754bf05f-35bd-4deb-8050-67f788191330/artifacts/0/dev/auto_tutorials/forward/20_source_alignment.html.

**Comment by agramfort** [comment]
@alexrockhill in the video you pick the fiducials too high. In this subject the LPA and RPA should be just just below the targus

**Comment by alexrockhill** [comment]
> @alexrockhill in the video you pick the fiducials too high. In this subject the LPA and RPA should be just just below the targus

Ok, I will reshoot picking as in here https://www.fieldtriptoolbox.org/faq/how_are_the_lpa_and_rpa_points_defined/

**Comment by alexrockhill** [comment]
Ok new video is up, looks good https://output.circle-artifacts.com/output/job/a249d7a8-3e0b-4508-9864-8bca3bc5fa25/artifacts/0/dev/auto_tutorials/forward/20_source_alignment.html#defining-the-headmri-trans-using-the-gui. I did notice that there was a reference to toggling head points that is defunct so I'll fix that.

**Comment by alexrockhill** [comment]
I noticed that the text instructions were out-of-date so this fixes those as well.

**Comment by agramfort** [comment]
nice !

2 nitpicks:
- you can use omit button after the first ICP fit to remove the outlier
point
- the scaling option is more if you have an individual digitization (aka
the head shape points)
but you don't have the MRI. You use then the dig points as proxy for the
head size etc.

**Comment by alexrockhill** [comment]
Ok, I'll give the video one more shot

**Comment by alexrockhill** [comment]
@agramfort, if you have time for one more look, sorry for the bad takes, you can playback at double speed and it's only two minutes 😄 https://youtu.be/ALV5qqMHLlQ

**Comment by cbrnr** [comment]
Maybe something for the text (I don't want you to redo the video again), but I have been wondering where the exact location of a fiducial marker actually is. Is it at some vertex? Or the center of mass inside the shape? Probably worth mentioning because that shape has a non-negligible shape.

**Comment by alexrockhill** [comment]
I was going off https://www.fieldtriptoolbox.org/faq/how_are_the_lpa_and_rpa_points_defined/ @cbrnr, we could link that in the tutorial

**Comment by alexrockhill** [comment]
I think it's the center of mass of the shape... does that help?

**Comment by alexrockhill** [comment]
@cbrnr, I added that info in the text

**Review by agramfort — COMMENTED** [review]
video is great !

are all the changes in this PR related? I see you touch stuff in GUI code and I want to know how deeply I need to review this

**Comment by alexrockhill** [comment]
If you could give it 5 minutes that would be really helpful. I abstracted the scraper to work for the `coreg` GUI as well so that it could be displayed inline and then I added `show` and `block` so that it wouldn't block the execution in the tutorial. Those are so that the code actually executes in the tutorial which I think is really important for maintenance. I added `show` and `block` to the `ieeg_locate` GUI while I was at it for symmetry. All of those are pretty minor changes, I'm not too worried about them breaking because they worked on the other GUI and I'm just harmonizing. Lastly, I fixed the wording suggesting that you could only launch `coreg` from the CLI which I think is a bit out-of-date per @hoechenberger 's issue.

**Comment by larsoner** [comment]
@agramfort is happy with the video, I'm happy with the code, and I don't see any unresolved comments so in it goes, thanks @alexrockhill !

**Pull request merged**
