### PR TITLE
Fix comment for FIFFV_RESP_CH constant

### LINKED ISSUE #8853: Confusion around "resp" channel type
In `channels.py`, it is claimed that the `resp` channel type is for certain response triggers:

https://github.com/mne-tools/mne-python/blob/19fb479de44865d5ce79ad5af539a06081fae0c5/mne/channels/channels.py#L704-L706

This seems to be supported by code treating BTi data:
https://github.com/mne-tools/mne-python/blob/19fb479de44865d5ce79ad5af539a06081fae0c5/mne/io/bti/bti.py#L1188-L1189

But the following comment in `constants.py` suggests it's a resp-iratory, not a resp-onse channel:
https://github.com/mne-tools/mne-python/blob/19fb479de44865d5ce79ad5af539a06081fae0c5/mne/io/constants.py#L177

Now … what gives?

x-ref https://github.com/mne-tools/mne-bids/issues/700

cc @agramfort

### PR DESCRIPTION
**Pull request by hoechenberger**
Fixes #8853

I searched the sources, and the only code that really uses FIFFV_RESP_CH is BTi I/O, where it's quite clear that it's a response channel (not a respiration monitoring channel)

### CODE REVIEW

**Review by agramfort — COMMENTED** [review]
should it also fixed elsewhere?

**Comment by hoechenberger** [comment]
> should it also fixed elsewhere?

Probably, yes:

https://github.com/mne-tools/mne-cpp/blob/c8e0124fd7630b5daff6477309a819d8b9dbfa90/libraries/fiff/c/fiff_types_mne-c.h#L234

https://github.com/mne-tools/fiff-constants/blob/5bd84d224de502bee66f70b7867b8f45b45264c1/DictionaryTypes.txt#L257

https://github.com/mne-tools/mne-matlab/blob/8f02bdeaf468c8df7a02adcd35656ca6f45f2d2f/matlab/fiff_define_constants.m#L167

Were the ones I've discovered so far

**Comment by hoechenberger** [comment]
FT is also not perfectly consistent here:

- "respiratory":    
    - https://github.com/fieldtrip/fieldtrip/blob/ddbfd3187299628b7b94b67c95b15d5cb76e96f4/fileio/ft_chantype.m#L236-L237
    - https://github.com/fieldtrip/fieldtrip/blob/ddbfd3187299628b7b94b67c95b15d5cb76e96f4/fileio/private/mne2grad.m#L217-L218
    - https://github.com/fieldtrip/fieldtrip/blob/ddbfd3187299628b7b94b67c95b15d5cb76e96f4/realtime/src/acquisition/neuromag/include/fiff_types.h#L151


- "event":
    - https://github.com/fieldtrip/fieldtrip/blob/ddbfd3187299628b7b94b67c95b15d5cb76e96f4/realtime/src/acquisition/neuromag/include/fiff_file.h#L584
    

cc @robertoostenveld

**Comment by hoechenberger** [comment]
@larsoner suggested that it might be our BTi code that's incorrect, not the comment -> channel type 602 would indeed be respiratory then: https://github.com/mne-tools/mne-python/issues/8853#issuecomment-776762418

**Comment by robertoostenveld** [comment]
Thanks for pinging me. So the FieldTrip MATLAB code (which is most relevant to me) has "respiratory" which is considered to be correct. One of the fif c-code header files that is included in FT suggests in a comment that it is "events" or responses. I won't touch that header file, since it stems (probably) from @LauriParkkonen and I am unlikely to recompile that code anyway (and if I were to recompile, it would not change a thing).

**Comment by agramfort** [comment]
it's more evidence now that RESP means actually respiration

>

**Comment by LauriParkkonen** [comment]
Yes, RESP refers to respiratory monitoring and that channel is supposed to contain an analog signal from a monitoring belt around the chest.

**Comment by hoechenberger** [comment]
Thanks for your feedback, this clarifies things!

**Pull request closed without merging**
