### PR TITLE
FIX toggling of html section

### PR DESCRIPTION
**Pull request by mainakjas**
cc @teonlamont

closes https://github.com/mne-tools/mne-python/issues/2212

### CODE REVIEW

**Comment by teonlamont** [comment]
if you do #1996, it will close all toggle-related issues in one pr :)

**Comment by agramfort** [comment]
merge if you're happy

**Comment by mainakjas** [comment]
I'm happy. I'm presuming @teonlamont is also happy. So merging.

**Comment by teonlamont** [comment]
thanks for the fix @mainakjas. as for these toggle buttons.... ;)

**Pull request merged**
