### PR TITLE
MRG: Add docstring checks

### LINKED ISSUE #1720: automatic docstring checking
we should have a way to automatically check docstrings based on function signatures. See:

https://github.com/jnothman/scikit-learn/blob/test_docstring_parameters/test_docstring_parameters.py

### PR DESCRIPTION
**Pull request by Eric89GXL**
Fixes many issues with our docs and docstrings. WIP because I needed to update our doc-building scripts but I can't check to make sure they actually work because Sphinx won't build the docs on my Windows laptop.

However, the substantive docstring fixes are done. @dengemann @mainakjas @agramfort please check to make sure you're happy with the changes I made, because some of the docstring errors could be dealt with in multiple ways.

Closes #1720. @agramfort if you're feeling bored, do you want to take over the doc building updates? I might not be able to get to it until next week. Basically I copied many changes over from the latest sklearn code.

### CODE REVIEW

**Comment by agramfort** [comment]
@Eric89GXL let me know when we can review.

**Comment by Eric89GXL** [comment]
Will do, I hope to get to it tomorrow or Tuesday.

**Comment by Eric89GXL** [comment]
Rebased and doc building works again. Ready for review/merge from my end. @dengemann @mainakjas @agramfort please be sure to check to make sure I didn't break your docstrings.

**Comment by agramfort** [comment]
merged by rebase after fixing a typo.

thanks heaps @Eric89GXL !

**Pull request merged**
