### PR TITLE
Fix tutorial deprecations

### PR DESCRIPTION
**Pull request by drammock**
- Fixes doc build errors arising from recent deprecations related to montage and epochs/evoked plotting functions.
- Fixes a bug in `plot_epochs_image` where an input dict was not deepcopied, and thus the global variable was getting modified.

### CODE REVIEW

**Comment by drammock** [comment]
cc @larsoner this should resolve the issues with https://circleci.com/gh/mne-tools/mne-python/14228

**Comment by larsoner** [comment]
Great thanks for the quick fix, feel free to merge once CircleCI comes back green.

**Comment by larsoner** [comment]
(And the rest of the CIs)

**Comment by larsoner** [comment]
Thanks @drammock !

**Pull request merged**
