### PR TITLE
Fix to filtering tutorial.

### PR DESCRIPTION
**Pull request by jaeilepp**
There was a small bug in the filtering tutorial http://mne-tools.github.io/dev/auto_tutorials/plot_background_filtering.html#baseline-problems-or-solutions.
See if you agree.

### CODE REVIEW

**Comment by jasmainak** [comment]
LGTM

**Comment by jasmainak** [comment]
@Eric89GXL should probably take a look before merging

**Comment by jaeilepp** [comment]
My PRs always seem to fail on circle for ``SUBJECTS_DIR`` not being set. I'm not sure why.

**Comment by Eric89GXL** [comment]
@jaeilepp it looks like this is very out of date, as the baseline stuff isn't even in there:

http://martinos.org/mne/dev/auto_tutorials/plot_background_filtering.html

Any idea why?

**Comment by jaeilepp** [comment]
The link is for stable, which was updated on 2. of July. And this tutorial section is quite recent. Right?

**Comment by jaeilepp** [comment]
No actually it is for dev, but it was updated in July. Seems like the updates on martinos aren't working. @agramfort

**Comment by Eric89GXL** [comment]
Circle failed here so I can't look at the result

**Comment by Eric89GXL** [comment]
Thanks @jaeilepp I looked at mne-tools.github.io and confirmed it's backward there

**Pull request merged**
