### PR TITLE
MRG, DOC: Deduplicate MNE manual pages

### PR DESCRIPTION
**Pull request by drammock**
This PR removes some of the redundancy in the `doc/manual` tree.

- References to MNE-Python functions were mostly moved into sidebars rather than integrated into the original manual text.
- The sections have been put into correct order in the TOC page.
- Text has been reflowed to fit a 79-char column (except for long `:math:` blocks or tables)
- some improvements to folder path formatting, e.g., using the rST `:file:` role instead of double backticks

### CODE REVIEW

**Comment by larsoner** [comment]
CircleCI complaints are legitimate. I fixed a few of them but there are more

**Comment by drammock** [comment]
Thanks for fixing the sidebars. Circle is happy so looks like I got all the crossrefs...  sorry i didn't test locally first (it takes forever on my laptop, and I don't have remote access to my UW machine at the moment because it changed subnets recently).

**Comment by jasmainak** [comment]
couple of comments
-- isn't the C API reference still being duplicated in the Manual?
-- what is the version of the manual here? It probably doesn't match the latest one, should we make a note of this?
-- the SSP was also part of the original manual? Is this part being duplicated still?

**Comment by drammock** [comment]
> couple of comments
> -- isn't the C API reference still being duplicated in the Manual?

it's *content* only exists on one page.  It is listed in the Manual TOC because chapter 1 of the manual had similar summary tables of the commands.  Do you think we should remove it from the manual TOC?

> -- what is the version of the manual here? It probably doesn't match the latest one, should we make a note of this?

we refer to it as "The web version of Matti Hämäläinen’s original MNE-C manual". I don't know how close it is to the most current version, doesn't really seem worth the effort to go through with a fine-toothed comb to figure it out.  What do you suggest for wording?

> -- the SSP was also part of the original manual? Is this part being duplicated still?

I think the standalone SSP page covers different material than what's in the manual (and its examples are all Python-specific).  But I'll double check.

**Comment by jasmainak** [comment]
>  Do you think we should remove it from the manual TOC?

I would say so, the TOC is too long to parse easily. We also have it here: https://15088-1301584-gh.circle-artifacts.com/0/dev/manual/c_reference.html#c-reference

> What do you suggest for wording?

I was going to suggest linking to the actual pdf of the latest version and nuke the web version (but that may make @agramfort sad)

**Comment by drammock** [comment]
> > Do you think we should remove it from the manual TOC?
> 
> I would say so, the TOC is too long to parse easily. We also have it here: https://15088-1301584-gh.circle-artifacts.com/0/dev/manual/c_reference.html#c-reference

OK will do

> 
> > What do you suggest for wording?
> 
> I was going to suggest linking to the actual pdf of the latest version and nuke the web version (but that may make @agramfort sad)

The PDF is behind a free-wall (users must log in with an account to even download it).  Until that policy changes I don't think we should take down the HTML version.

**Comment by drammock** [comment]
@jasmainak you were right about the SSP being duplicated.  I've fixed that now, and removed the C API from the manual TOC.

**Comment by jasmainak** [comment]
> The PDF is behind a free-wall (users must log in with an account to even download it). Until that policy changes I don't think we should take down the HTML version.

I think this must change. I will talk to @mshamalainen tomorrow

**Comment by drammock** [comment]
OK.  In the meantime I think we should still merge this when CIs come back green.  If we need to decommision the whole set of manual pages it will be a larger effort (due to all the crossrefs pointing there) and we should probably get buy-in from more of the community first.

**Comment by larsoner** [comment]
Thanks @drammock

**Comment by jasmainak** [comment]
So, just to finish the story @mshamalainen is totally fine with putting the manual on github. Let me know if you need my help there.

**Pull request merged**
