### PR TITLE
BUG: Fix bug with CSP rank

### LINKED ISSUE #9094: CSP error: LinAlgError : The leading minor of order 64 of B is not positive definite.
#### Describe the bug

This issue has been discussed on the Forum [here](https://mne.discourse.group/t/csp-error-linalgerror-the-leading-minor-of-order-64-of-b-is-not-positive-definite/2755/2) with the suggestion to open a bug report. 

I face the following error when running the CSP function using the EEG BCI dataset:

LinAlgError : The leading minor of order 64 of B is not positive definite. The factorization of B could not be completed and no eigenvalues or eigenvectors were computed.

#### Steps to reproduce

import numpy as np
from mne.decoding import CSP

loaded = np.load('preprocessingoutput.npz')
CSP(n_components=5, reg=1e-4).fit(loaded['x1'], loaded['y1'])

preprocessingoutput.npz and the preprocessing steps run on the EEG data are provided [here](https://github.com/FriederikeScholten/CSP-error-LinAlgError.git). 

#### Expected results
running CSP analysis. 

#### Actual results
LinAlgError : The leading minor of order 64 of B is not positive definite. The factorization of B could not be completed and no eigenvalues or eigenvectors were computed.

#### Additional information
mne.sys_info()
Platform:      Windows-10-10.0.19041-SP0
Python:        3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]
Executable:    C:\Users\????\Anaconda3\python.exe
CPU:           Intel64 Family 6 Model 142 Stepping 10, GenuineIntel: 8 cores
Memory:        7.9 GB

mne:           0.22.0
numpy:         1.18.5 {blas=mkl_rt, lapack=mkl_rt}
scipy:         1.5.4
matplotlib:    3.3.3 {backend=module://ipykernel.pylab.backend_inline}

sklearn:       0.23.2
numba:         0.50.1
nibabel:       Not found
nilearn:       Not found
dipy:          Not found
cupy:          Not found
pandas:        1.0.5
mayavi:        Not found
pyvista:       Not found
vtk:           Not found

### PR DESCRIPTION
**Pull request by larsoner**
Closes #9094

WIP because I haven't thoroughly tested or anything. But at least modifying the example things work out of the box. The "trick" is to use `_smart_eigh` to figure out the correct subspace, do the `eigh(a, b)` in that subspace, and project back the same way we do with covariances. (Now you shouldn't even have to supply `rank` because it'll compute it from the `cov` for you if you don't!)

This really only works with a single channel type at the moment -- to properly support multiple channel types people should pass an `info` I think. So the TODO list is roughly:

- [x] Make tests more thorough
- [x] Make sure everything is green
- [x] Add a test using MEG+EEG to make sure it works
- [x] ~~Add `info` support to make multiple channel types support robust~~
- [x] ~~Add an example using MEG+EEG~~

### CODE REVIEW

**Comment by larsoner** [comment]
@drammock realized we should get this in to 1.7 as well. Ready for review/merge from my end!

**Comment by larsoner** [comment]
Argh https://physionet.org/ is down but example renders okay locally

| main | PR |
| -- | -- |
| image | image |
| image | image |

**Comment by larsoner** [comment]
Related https://github.com/MIT-LCP/physionet/issues/154

**Comment by cbrnr** [comment]
LGTM, just one question: does this also resolve the issue with channel types? I remember someone reported that computing the rank on EEG-only data suddenly created a rank for MEG channels, but unfortunately I cannot find that issue (or forum question).

**Review by cbrnr — APPROVED** [review]
LGTM!

**Comment by ivopascal** [comment]
> LGTM, just one question: does this also resolve the issue with channel types? I remember someone reported that computing the rank on EEG-only data suddenly created a rank for MEG channels, but unfortunately I cannot find that issue (or forum question).

I think this refers to my problem, though it created a rank for MAG instead of MEG. It's discussed here https://github.com/mne-tools/mne-python/issues/9094#issuecomment-1954187464

A MWE is here: https://colab.research.google.com/drive/1LBq8Sg-30Cnlj9sYLPtEcsPIyBtsvxF8?usp=sharing#scrollTo=_hS__cmSGVIU

The logger still indicates MAG channels which don't exist, but it's not causing any real problems anymore.
`Setting small MAG eigenvalues to zero (without PCA)`

**Comment by larsoner** [comment]
Okay pushed a commit to fix that `"mag"` business as well, the logging in the changed example (if you enable it) looks like:
```
Computing rank from data with rank=None
    Using tolerance 7e-05 (2.2e-16 eps * 64 dim * 4.9e+09  max singular value)
    Estimated rank (data): 63
    data: rank 63 computed from 64 data channels with 0 projectors
    Setting small data eigenvalues to zero (without PCA)
Reducing data rank from 64 -> 63
Estimating class=0 covariance using EMPIRICAL
Done.
Estimating class=1 covariance using EMPIRICAL
Done.
```

**Comment by cbrnr** [comment]
Thanks @larsoner!

**Comment by mscheltienne** [comment]
Seems like this PR introduces a bug, reported here: https://mne.discourse.group/t/the-api-reference-of-csp-needs-updata/9018/2

**Pull request merged**
