### PR TITLE
MRG: Refactor OFF_SCREEN variable

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR prevents setting `pyvista.OFF_SCREEN` globally (*i.e.* in tests, ... etc) by managing a renderer `MNE_3D_OFF_SCREEN` variable instead.

Also, before #7266, the [tests were done offscreen by default](https://github.com/mne-tools/mne-python/pull/7266/files#diff-7d015438f1f32b2f4c28f713c2e3e7b1L130) with `_use_test_3d_backend()` so this PR fixes this.

This variable is still set globally in `_testing_context()` (this one restores the original value) and in the `doc` which is fine by me.

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
What do you think @larsoner , @agramfort ?

**Comment by agramfort** [comment]
@larsoner let us know what you think. I don't fully grasp the consequences of this but if it works and CIs are green it cannot be too bad :)

**Comment by GuillaumeFavelier** [comment]
Actually it's fine to set it globally but we just have to remember to set the original value. My previous changes brought confusion/redundancy of two variables doing the same thing.

**Comment by GuillaumeFavelier** [comment]
Makes me think that we can use a `contextmanager` for that.

**Comment by agramfort** [comment]
I trust your judgement here.

>

**Comment by GuillaumeFavelier** [comment]
I would say it's good enough now. We can always make it nicer later.

**Comment by agramfort** [comment]
@larsoner merge if you're happy

**Comment by larsoner** [comment]
(but we can do that in another PR, since it's not a problem with these changes specifically)

**Comment by larsoner** [comment]
Thanks @GuillaumeFavelier

**Pull request merged**
