### PR TITLE
FIX: blink annotations eyetracking/pupilometry

### LINKED ISSUE #12408: raw.crop doesn't adjust onset of annotations for eyetracking data leading to interpolation errors
### Description of the problem

specifically for eyetracking data (not sure about other types), the `raw.crop` method will trim the signal down appropriately, but no adjustment is made to the onset time of any annotations that remain in the data. this is particularly problematic when you use `mne.preprocessing.eyetracking.interpolate_blinks` where it will just interpolate over random segments of the signal

i am not sure if this is an intended behaviour as I think, in the past, the `.crop` function has adjusted the onset time of events (before annotations were used). If i'm wrong, please send me away!

### Steps to reproduce

```Python
import mne
from mne.datasets.eyelink import data_path
mne.viz.set_browser_backend('qt')

dpath = data_path() / "eeg-et" / "sub-01_task-plr_eyetrack.asc"
raw = mne.io.read_raw_eyelink(dpath, create_annotations = ['blinks'])
raw.plot(scalings = dict(eyegaze = 1e3))
raw = raw.crop(tmin = 4)
raw = mne.preprocessing.eyetracking.interpolate_blinks(raw, buffer = 0.15)
raw.plot(scalings = dict(eyegaze = 1e3)) #can see interpolation happens exactly 4s after the actual blink period
```

### Link to data

_No response_

### Expected results

it should interpolate the blinks (removing blink artefact)

### Actual results

it interpolates exactly Xs after the blink, where X is the tmin applied in the `raw.crop` call

### Additional information

Platform             macOS-14.2.1-arm64-arm-64bit
Python               3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:37:07) [Clang 15.0.7 ]
Executable           /Users/sammichekroud/anaconda3/envs/mne/bin/python
CPU                  arm (8 cores)
Memory               16.0 GB

Core
├☒ mne               1.6.0 (outdated, release 1.6.1 is available!)
├☑ numpy             1.26.2 (OpenBLAS 0.3.25 with 8 threads)
├☑ scipy             1.11.4
├☑ matplotlib        3.8.2 (backend=Qt5Agg)
├☑ pooch             1.8.0
└☑ jinja2            3.1.2

Numerical (optional)
├☑ sklearn           1.3.2
├☑ numba             0.58.1
├☑ nibabel           5.2.0
├☑ nilearn           0.10.2
├☑ dipy              1.7.0
├☑ openmeeg          2.5.7
├☑ pandas            2.1.4
└☐ unavailable       cupy

Visualization (optional)
├☑ pyvista           0.43.1 (OpenGL 4.1 Metal - 88 via Apple M2)
├☑ pyvistaqt         0.11.0
├☑ vtk               9.2.6
├☑ qtpy              2.4.1 (PyQt5=5.15.2)
├☑ pyqtgraph         0.13.3
├☑ mne-qt-browser    0.6.1
├☑ ipywidgets        8.1.1
├☑ trame_client      2.14.1
├☑ trame_server      2.13.1
├☑ trame_vtk         2.6.3
├☑ trame_vuetify     2.3.1
└☐ unavailable       ipympl

Ecosystem (optional)
└☐ unavailable       mne-bids, mne-nirs, mne-features, mne-connectivity, mne-icalabel, mne-bids-pipeline

### PR DESCRIPTION
**Pull request by schekroud**
#### Reference issue
Fixes #12408

#### What does this implement/fix?
properly adjusts blink onsets/offsets to account for the start time of the signal. This allows you to crop the signal and still have an accurate description of blink onsets

### CODE REVIEW

**Comment by schekroud** [comment]
@scott-huberty @larsoner sorry if i have completely screwed up how you guys normally do this - i closed the previous PR (i dont think i could edit the code once the PR was made) as i noticed it didn't import the annotations function needed (i incorrectly assumed it would be there by default, but then tested and found i was wrong).

This should work!

Again, sorry if i have messed up the normal workflow 😆

**Comment by scott-huberty** [comment]
No worries @schekroud there can be a learning curve for PR's. Have you read the [contributing guide](https://mne.tools/dev/development/contributing.html)? I still use it from time to time to remind myself. 

One comment (@larsoner can correct me if it isn't a big deal in this case), usually it's best to open a PR from a _development_ branch (not your main branch). This should be covered in the contributing guide (let us know if it isn't).

**Comment by scott-huberty** [comment]
I just took a closer look at this PR. It looks like most of the failing tests are unrelated, and I think all of them should have been fixed by recently merged PR's (i.e. #12417 ).

@schekroud if you do want to work on this PR from a development branch here is what I would do:

<details>
  <summary>git commands</summary>

(Assuming you are in the mne-python github respoitory directory, and on your main branch):

```
# checkout new branch starting from commit just BEFORE your commits for this PR
git checkout -b fix_interpolate_blinks d8ea2f5e60174d61301dbefbed9c76c9adc01ec9

# bring in the commits from this PR (that are currently on your main branch)
git rebase main fix_interpoate_blinks

# add a link to the mne-python github repo, we'll call it "upstream"
git remote add upstream https://github.com/mne-tools/mne-python.git

# bring in the latest changes that have been merged into mne-python
git fetch upstream main
git merge upstream/main --ff-only

# push your new local development branch to your remote fork
 git push --set-upstream origin fix_interpoate_blinks
```

Then you could open another PR and close this one.

## resetting your main branch to be in line with mne-pythons main branch

if you create a new branch with the changes from this PR, you'll want to reset your main branch: 

```
git checkout main

git reset --hard upstream/main
```

</details>

Either way (you create a new dev branch or just continue this PR from your main branch), There a couple things to do.

1. add a new `rst` file to `doc/changes/devel` that describe the changes made by this PR. See https://mne.tools/dev/development/contributing.html#describe-your-changes-in-the-changelog
2. @larsoner should we amend `test_interpolate_blinks` to include a test with a cropped raw object?

**Comment by scott-huberty** [comment]
Hi @schekroud do you still have time to work on this? I think you just need [to merge in the updates to mne ](https://mne.tools/dev/development/contributing.html) since your last commit, and add an entry to the changelog (see point 1 in my previous message). Let me know if you need any support from us!

**Comment by mscheltienne** [comment]
I merged main. A test should be added to cover the previous failure.

**Pull request closed without merging**
