### PR TITLE
allow ch_type change without ch_name change

### PR DESCRIPTION
**Pull request by agramfort**
with this fix now you can do this to change type of all channels:

```
mne.rename_channels(evoked.info, dict((c, (c, 'seeg')) for c in evoked.ch_names))
```

cc @aestrivex

### CODE REVIEW

**Comment by dengemann** [comment]
LGTM!

**Comment by Eric89GXL** [comment]
LGTM, thanks

**Comment by dgwakeman** [comment]
@agramfort Did this remove the check for giving channels the same name? If so why?

**Comment by agramfort** [comment]
yes it did. Otherwise you could not change the type of a channel without
changing also it's name

**Comment by dgwakeman** [comment]
what about something like?

other_chs = deepcopy(ch_names)
other_chs.remove(ch_name)
new_name in other_chs:
 raise ValueError('The new name ({new}) already exists. Choose a '
 'unique name'.format(new=new_name))

**Comment by agramfort** [comment]
please feel free to make my example for @aestrivex work with what you suggest

**Comment by aestrivex** [comment]
@dgwakeman that would work just fine as well, it probably isn't necessary to do a deepcopy to get that behavior.

**Pull request merged**
