### PR TITLE
FIX: Fix report

### PR DESCRIPTION
**Pull request by Eric89GXL**
Minor fix for report so it does what it says it will do (cc @mainakjas). Waiting to see if Travis is happy about it...

### CODE REVIEW

**Comment by agramfort** [comment]
Lgtm

**Comment by dengemann** [comment]
LGTM

**Comment by Eric89GXL** [comment]
Thanks for the quick reviews, @mainakjas feel free to take a look and correct if I was mistaken

**Comment by mainakjas** [comment]
looks fine. Thanks @Eric89GXL !

**Pull request merged**
