### PR TITLE
MRG +1: Use faulthandler

### PR DESCRIPTION
**Pull request by Eric89GXL**
Should hopefully help with #3948 and any other segfaults we get.

Simply doing `pip install nose-faulthandler` [enables it by default](https://pypi.python.org/pypi/nose-faulthandler):
```
nose.plugins.faulthandler: INFO: Activating faulthandler module.
```
Should be ready for merge assuming Travis and AppVeyor agree.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
@christianbrodbeck do you have time for a quick look? If you can give your +1 then I'll go ahead and merge once the CIs are happy, and you can rebase your PR

**Comment by Eric89GXL** [comment]
Somehow there is now a bug in `master` for 3.5. Fixing it in this PR, too.

**Comment by christianbrodbeck** [comment]
Looks good

**Comment by agramfort** [comment]
thx @Eric89GXL

**Pull request merged**
