### PR TITLE
[WIP/ENH] Enable working with the full MNE solution

### PR DESCRIPTION
**Pull request by wmvanvliet**
By default, only the magnitude of the dipoles are returned by the `apply_inverse_*` family of methods. This PR adds a new value for the `pick_ori` parameter: `'full'`.

This results in a `FullSourceEstimate` object, which inherits from `SourceEstimate`. The main differense is a new dimension for the `stc.data` array. It is now `#dipoles x 3 x #samples`, containing the MNE solution in the XYZ (fixed orientation) directions. All the functions of `SourceEstimate` have been properly overloaded and also work for the new `FullSourceEstimate` object. This includes a suitable plotting and save function.

At any time, the user can transform the `FullSourceEstimate` object into a regular `SourceEstimate` object by calling either the `.magnitude` or `.normal` function.

snapshot

TODO:
- [ ] Make existing unit tests pass
- [ ] Add more unit tests
- [ ] Write tutorial on this

### CODE REVIEW

**Comment by Eric89GXL** [comment]
@wmvanvliet any time to work on this in the coming month or two? It looks like it could be a useful addition.

**Comment by wmvanvliet** [comment]
this is basically done. The only reason this is flagged as WIP is that it doesn't have 100% unit testing coverage yet. Give it a go if you are curious :)

I will continue working on this (it is part of my next paper) in the upcoming months.

**Comment by Eric89GXL** [comment]
Great. I think that @SherazKhan had some code to do something similar. It might be worth trying to work that in if possible. I'll bother him about it :)

In the meantime, can you get the coverage up, or is it a pain?

**Comment by wmvanvliet** [comment]
Yes and yes. The problem is that this change has quite a large impact on many functions. For one, the `SourceEstimate` has a lot of functionality, a lot of which needs to be tweaked a little to properly work when the `.data` attribute has an extra dimension. This also means the unit tests for this functionality need to be expanded. Furthermore, one of the more useful things you can do when working with the source directions is that applying the forward model to get sensor signals "just works (tm)". So the simulation code has to be updated as well to operate on a `FullSourceEstimate` object. And this requires even more unit tests. It's a big PR.

**Comment by agramfort** [comment]
I think we should agree on the plan here before investing too much time on
refactoring.

**Comment by wmvanvliet** [comment]
> I think we should agree on the plan here

Sounds good!

The plan for the API thus far has been to make working with source directions as easy as just flipping the `pick_ori` flag and continuing like usual.

Here are some implementation challenges I encountered trying to implement the desired API functionality:

 - The result is now an `(n_vertices, 3, n_samples)` matrix. It can be stored in a regular `SourceEstimate` object by reshaping it as a `(3*n_vertices, n_samples)` matrix, but some functionality (plotting, saving, ROI checking) will break. In the end, I found it easier to subclass the `SourceEstimate` object, which has the added bonus that we can easily check in the code whether a source solution has directions with `isinstance`.
 - Re-implementing the methods of `SourceEstimate` in the `FullSourceEstimate` class was causing a huge amount of copy/pasting. Therefore, I opted to make the methods in `SourceEstimate` a bit more generic where possible to deal with the `(n_vertices, n_samples)` versus `(n_verices, 3, n_samples)` case. For example, to compute the mean across time I changed `mean(data, axis=1)` into `mean(data, axis=-1)`. This way, a lot of methods could simply be re-used.
 - The `save` functionality is tricky. Right now I save a `FullSourceEstimate` in a modified version of the `.stc` format. Reading the file will check whether the filename ends in `-full-lh.stc` or `-full-rh.stc`, which indicates that directionality information is present. Maybe we should just save as HDF.
 - The `apply_forward` and `apply_forward_raw` functions are currently extremely picky on how the source estimate was constructed. When given a `FullSourceEstimate` object, these function can be a lot less picky. Should we address this in this PR or make a subsequent PR?
 - The simulation code for modeling a dipole with a certain direction currently creates a custom source space with the vertex normal pointing in the desired direction. This could be made simpler by making it create a `FullSourceEstimate` object instead. This should probably go into a subsequent PR.

**Comment by Eric89GXL** [comment]
> In the end, I found it easier to subclass the SourceEstimate object, which has the added bonus that we can easily check in the code whether a source solution has directions with isinstance.

Shouldn't you subclass `BaseSourceEstimate`? Otherwise `isinstance(x, SourceEstimate)` will pass even for yours, despite not all functions/attributes working the same way.

> Re-implementing the methods of SourceEstimate in the FullSourceEstimate class was causing a huge amount of copy/pasting

Maybe what we really need, then, is a `BaseSurfaceSourceEstimate` class that subclasses `BaseSourceEstimate` but has any of the methods that apply to both `FullSourceEstimate` and `SourceEstimate`.

> Maybe we should just save as HDF.

+1 it will be much easier.

> The apply_forward and apply_forward_raw functions are currently extremely picky on how the source estimate was constructed

Let's just raise `ValueError` for now in those, and subsequent PR to fix them. It will reduce review burden.

> This could be made simpler by making it create a FullSourceEstimate object instead. This should probably go into a subsequent PR.

Yes, separate PR is better.

One other thing to keep in mind is that eventually we might want e.g. time-frequency SourceEstimates, so whatever structures we come up with (at the very least for saving) we should try to make future compatible if possible.

**Comment by agramfort** [comment]
ok it seems you have a clear plan. Let's just start with a small PR.

What I propose is to create a VectorSourceEstimate (as we store a vector
field over time) and a common _BaseSurfaceSourceEstimate so that
SourceEstimate inherits from _BaseSurfaceSourceEstimate

it should make the diff minimal and we could simply doc

stc = vector_stc.norm()

to recover the classical stc object.

how does this sound?

we can make the rest in a subsequent PR

**Comment by Eric89GXL** [comment]
+1 from me

**Comment by wmvanvliet** [comment]
closing in favor of #3842

**Pull request closed without merging**
