### PR TITLE
Fixing time decoding docstring

### PR DESCRIPTION
**Pull request by choldgraf**
Fixing the GeneralizationAcrossTime docstring so that the correct default classifier is listed.

### CODE REVIEW

**Comment by agramfort** [comment]
Thanks

**Comment by kingjr** [comment]
Has this been merged? It wasn't rebased when I added https://github.com/mne-tools/mne-python/pull/2066

**Comment by choldgraf** [comment]
Ummm I think it was, right @agramfort? Just a one-liner change. Did these changes get undone in a separate commit?

**Comment by kingjr** [comment]
I can add it in #2066 if necessary. I'll wait for Alex's response

**Comment by kingjr** [comment]
I changed it back in #2066

**Pull request merged**
