### PR TITLE
BUG: issue 3930- mne cmd line tools no longer needed

### PR DESCRIPTION
**Pull request by bloyl**
Fix for issue 3930
no need to check for mne cmd line tools

### CODE REVIEW

**Comment by christianbrodbeck** [comment]
I think you could actually remove the `requires_mne` argument from `_prepare_env`, it's not called with `True` anywhere.

**Comment by bloyl** [comment]
I can certainly do that.

My only hesitation is that the check is pretty innocuous and i didn't want to change the API, even of a hidden method, in the off chance that some code imported it directly.

**Comment by Eric89GXL** [comment]
> My only hesitation is that the check is pretty innocuous and i didn't want to change the API, even of a hidden method, in the off chance that some code imported it directly.

It is private so we need only concern ourselves with internal consistency. Let's try a `git grep` (which @christianbrodbeck probably did already) and remove it if it seems okay.

**Comment by bloyl** [comment]
Done.

**Comment by agramfort** [comment]
LGTM

+1 for merge if CIs are happy

**Comment by Eric89GXL** [comment]
Thanks @bloyl

**Pull request merged**
