### PR TITLE
TST: Build the doc on Circle with offscreen=False

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR tests how Circle reacts when `OFF_SCREEN=False`.

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
Apparently there is an issue installing `PyQt5 5.14.1` on macOS, I'll try to reproduce on master.

I encountered the same on https://github.com/mne-tools/mne-python/pull/7153 and it was completely fine on https://github.com/mne-tools/mne-python/pull/7175 when using `PyQt5 5.14.0`.

**Comment by GuillaumeFavelier** [comment]
Except the latest issue with Travis, the good news is that [Circle came back happy](https://circleci.com/gh/mne-tools/mne-python/17388?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).

Results available: https://17388-1301584-gh.circle-artifacts.com/0/dev/index.html

**Comment by GuillaumeFavelier** [comment]
I launched another build now that is #7176 is merged.

**Comment by larsoner** [comment]
And this PR is necessary to get the sliders visible in examples in #7153 ?

**Comment by GuillaumeFavelier** [comment]
I would say that it's the simplest way. This PR checks that there is no regression with this modification.

**Comment by larsoner** [comment]
Is it good to go? Still marked as draft

**Comment by GuillaumeFavelier** [comment]
Once the CIs come back happy, I'll make it ready.

**Comment by agramfort** [comment]
works ! thx @GuillaumeFavelier

**Pull request merged**
