### PR TITLE
[MRG+1] Remove minor ticks from tfr plot.

### PR DESCRIPTION
**Pull request by jaeilepp**
Closes https://github.com/mne-tools/mne-python/issues/4060

### CODE REVIEW

**Comment by Eric89GXL** [comment]
LGTM +1 for merge

**Comment by agramfort** [comment]
how does the figure look like now?

**Comment by jaeilepp** [comment]
Like this:
figure_1

**Comment by mmagnuski** [comment]
Looks good, thanks for the fix @jaeilepp !

**Comment by Eric89GXL** [comment]
@mmagnuski I take that as a +1

Thanks @jaeilepp

**Pull request merged**
