### PR TITLE
DOC: convert references in plot_parcellation to use footcite

### LINKED ISSUE #8911: use bibtex in plot_parcellation.py
convert references in `examples/visualization/plot_parcellation.py` to use footcite / footbibliography

### PR DESCRIPTION
**Pull request by NicolasGensollen**
Fixes #8911

### CODE REVIEW

**Comment by agramfort** [comment]
@NicolasGensollen you have CI issues. I fear you need to update the .bib file too.

**Comment by NicolasGensollen** [comment]
>@NicolasGensollen you have CI issues. I fear you need to update the .bib file too.

@agramfort I'm not sure what's causing them yet. I don't think I have to update the .bib file since the two refs of `plot_parcellation` are already there:

https://github.com/mne-tools/mne-python/blob/6cfd3040aed69d9970c618b782e6126ed56adb65/doc/references.bib#L419-L428

and:

https://github.com/mne-tools/mne-python/blob/6cfd3040aed69d9970c618b782e6126ed56adb65/doc/references.bib#L789-L797

**Comment by agramfort** [comment]
I am restarting the build to try

>

**Comment by drammock** [comment]
@NicolasGensollen thanks for fixing this!  FYI, we are saving a lot of "easy" issues like this for our New Developer Code Sprint next week.  There are still plenty to go around so no problem with us merging this one, but in case you were planning to tackle several more like this in the coming days, please wait until after the code sprint.

**Comment by NicolasGensollen** [comment]
>FYI, we are saving a lot of "easy" issues like this for our New Developer Code Sprint next week.

@drammock thanks for the heads up. :+1: 
This was just the occasion to start playing with MNE.
Feel free to close if you want to save it for the sprint.

**Comment by drammock** [comment]
No sense closing a perfectly good pull request!  We have plenty of other easy issues for them to tackle.  Once we get our CI build problem sorted out I'll merge this.

**Review by drammock — APPROVED** [review]

**Comment by drammock** [comment]
CI error is this (lines 1017-1032 [here](https://app.circleci.com/pipelines/github/mne-tools/mne-python/6742/workflows/b318c113-8df1-4af6-9fb7-a198a9ba538a/jobs/25733)):

```
  gcc: tvtk/src/array_ext.c
  In file included from /home/circleci/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:1944,
                   from /home/circleci/.local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                   from /home/circleci/.local/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                   from tvtk/src/array_ext.c:223:
  /home/circleci/.local/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it with " \
    ^~~~~~~
  gcc -pthread -shared build/temp.linux-x86_64-3.8/tvtk/src/array_ext.o -L/usr/local/lib -o build/lib.linux-x86_64-3.8/tvtk/array_ext.cpython-38-x86_64-linux-gnu.so
  running gen_docs
  qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
  This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
  
  Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
  
  Fatal Python error: Aborted
```

The "could not load plugin xcb" feels like a familiar error...  some searching suggests that reinstalling `libxcb` (or `libxcb-xinerama0`) fixes this for some people, but there seem to be a variety of causes and solutions. may need to re-run on Circle with `export QT_DEBUG_PLUGINS=1` to solve?

**Comment by larsoner** [comment]
That should have been fixed by https://github.com/mne-tools/mne-python/pull/9024 so I pushed a merge with upstream/main to see if it fixes things

**Comment by larsoner** [comment]
Thanks @NicolasGensollen !

**Pull request merged**
