### PR TITLE
FIX: public API for joint plot in viz (following common patterns)

### PR DESCRIPTION
**Pull request by dengemann**
it should have been like that in the first place, no deprecation needed.

### CODE REVIEW

**Comment by dengemann** [comment]
not done yet, don't merge.

**Comment by jona-sassenhagen** [comment]
Fine with me. I forgot why I initially used the other name.

**Comment by agramfort** [comment]
why was this necessary?

**Comment by dengemann** [comment]
> why was this necessary?

because we expose our viz methods as public functions and we wrote this somewhere in a paper. I would ask the other way round: why would you want to break consistency here?

**Comment by agramfort** [comment]
>
> because we expose our viz methods as public functions and we wrote this
> somewhere in a paper. I would ask the other way round: why would you want
> to break consistency here?
>
I am thinking that their should be "one way to do things" but let's avoid a
massive PR just for this.

**Comment by dengemann** [comment]
yes and we have always done it this way.

**Comment by dengemann** [comment]
@agramfort you finally agreed that this is good to go, right? Anyone else? I'll merge in a while if no one objects.

**Comment by teonlamont** [comment]
just echoing what @dengemann mentioned, our viz module has all of the plotting functions where you can supply it the proper object and it does the plotting. we then have these functions inherited as methods to their respective modules. it's been that way for a while. LGTM @dengemann

**Pull request merged**
