### PR TITLE
MxNE and irMxNE with BCD

### PR DESCRIPTION
**Pull request by joewalter**

### CODE REVIEW

**Comment by adykstra** [comment]
Hi @joewalter ,

Where's this at?  From reading @agramfort's comments it looks nearly ready.  I am about to start analyzing data from a new study and would love to have this available rather than continuing to use my original iterative MxNE hack.  Anything I can do to help?

Andy

**Comment by agramfort** [comment]
I am on it. I'll finish it.

**Comment by adykstra** [comment]
Fantastic!  Thanks.

**Comment by agramfort** [comment]
closing in favor of #1785

**Pull request closed without merging**
