### PR TITLE
MNT: Revert to mayavi as 3d backend for building the documentation

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR follows https://github.com/mne-tools/mne-python/issues/7228#issuecomment-595666636 and reverts Circle's config to use `mayavi` to build the documentation until https://github.com/mne-tools/mne-python/issues/7228 is fixed at least.

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
`time_viewer=True` needs to be reverted in `plot_visualize_stc.py`

**Comment by agramfort** [comment]
time_viewer viewer auto to keep the feature when we move back to
pyvista hopefully before the release in 2 weeks...

**Comment by GuillaumeFavelier** [comment]
To get it back, it mostly depends on:
* https://github.com/mne-tools/mne-python/issues/7228
* https://github.com/mne-tools/mne-python/pull/7060
* https://github.com/mne-tools/mne-python/pull/7380

**Comment by agramfort** [comment]
to me https://github.com/mne-tools/mne-python/pull/7380 is the blocker. I
can live with the two others as WIP

>

**Comment by GuillaumeFavelier** [comment]
But bringing `time_viewer='auto'` is not compatible with letting `mayavi` as default 3d backend.

**Pull request closed without merging**
