### PR TITLE
WIP: Use environment.yml on CircleCI

### PR DESCRIPTION
**Pull request by larsoner**
I've tried this before but I can't remember if I did it with the latest `environment.yml`. Let's see if it works.

### CODE REVIEW

**Comment by larsoner** [comment]
The problem is that newer VTK (7.1 that we use now) requires a MESA version not available on Trusty 14.04 that CircleCI 1.0 uses. In theory if we get a usable Docker image with 16.04 on it, we could migrate to CircleCI 2.0 (which this PR gets going). I'll play with Docker a bit to see if I can get it working.

**Comment by larsoner** [comment]
So far so good!

https://7398-1301584-gh.circle-artifacts.com/0/home/circleci/project/doc/_build/html/auto_tutorials/plot_mne_dspm_source_localization.html

Going to try a `full` run. @agramfort if it succeeds, okay to merge this and iterate in `master` as necessary to get the uploads working properly?

**Comment by larsoner** [comment]
Looks like we are good to go!

https://7410-1301584-gh.circle-artifacts.com/0/HTML/html/index.html

**Comment by massich** [comment]
LGTM

**Comment by larsoner** [comment]
Docs successfully updated, hooray!

https://github.com/mne-tools/mne-tools.github.io/commit/0dbde5447594699b43948c181cabaf33d71af1c8

**Pull request closed without merging**
