### PR TITLE
MRG: Build relevant examples

### LINKED ISSUE #3357: ENH: Auto-build examples or tutorials that are modified
Fun project for someone if they get bored. CircleCI currently builds full docs `html_dev` on `master` and `html_dev-noplot` on PRs. But really on PRs it should build `PATTERN=... make html_dev-pattern` when the PR touches an example or tutorial. So some enterprising person could inspect the `diff` and figure out if any of the files live in `examples/` or `tutorials/` and call the pattern version.

@jaeilepp fancy a challenge? :)

### PR DESCRIPTION
**Pull request by Eric89GXL**
Closes #3357.

Today is Sunday right @agramfort? :)

### CODE REVIEW

**Comment by Eric89GXL** [comment]
From the first commit, which only touched `circle.yml` we get the `html_dev-noplot`:

https://1413-1301584-gh.circle-artifacts.com/0//home/ubuntu/mne-python/doc/_build/html/auto_tutorials/plot_visualize_raw.html

And from the second commit, which touched a couple of tutorials, we get the following run:
```
BUILD_DEV_HTML=1 sphinx-build -D plot_gallery=1 -D sphinx_gallery_conf.filename_pattern=\(plot_visualize_raw.py\|plot_background_filtering.py\) -b html -d _build/doctrees   . _build/html
```
Which produces:

https://1414-1301584-gh.circle-artifacts.com/0//home/ubuntu/mne-python/doc/_build/html/auto_tutorials/plot_background_filtering.html

https://1414-1301584-gh.circle-artifacts.com/0//home/ubuntu/mne-python/doc/_build/html/auto_tutorials/plot_visualize_raw.html

I like it, but I don't think we can merge this until the caching problem is solved. This build took an hour and 11 minutes, 57 minutes of which was downloading data (!).

**Comment by agramfort** [comment]
LGTM

thx @Eric89GXL

**Comment by Eric89GXL** [comment]
Okay I'm going to rebase, hopefully it picks up the cache and takes less time now.

**Comment by Eric89GXL** [comment]
@jaeilepp looks like we still get:

```
restoring cache v5/os:linux/mne-tools/mne-python/dependency/pull/3365/1413/TvoMGrNbQpVtayCqXueI7A__.tar.gz
restoring home/ubuntu/.m2, home/ubuntu/.ivy2, home/ubuntu/.go_workspace, home/ubuntu/.gradle, home/ubuntu/miniconda, home/ubuntu/mne-tools.github.io
```
After this finishes successfully, I'll try pushing another commit. Maybe it needs a couple of tries to save properly.

**Comment by Eric89GXL** [comment]
Still appears to have failed:
```
restoring cache v5/os:linux/mne-tools/mne-python/dependency/pull/3365/1413/TvoMGrNbQpVtayCqXueI7A__.tar.gz
restoring home/ubuntu/.m2, home/ubuntu/.ivy2, home/ubuntu/.go_workspace, home/ubuntu/.gradle, home/ubuntu/miniconda, home/ubuntu/mne-tools.github.io
```
I don't understand why it would get the other directories. That's weird.

**Comment by jaeilepp** [comment]
Yeah I'm trying to debug this by running minimal builds on my branch. Let's see if I can find something.

**Comment by jaeilepp** [comment]
I'm wondering if our cache is just stuck in some weird state and it would fix itself if we just clear it once. I can't think of anything else right now.

**Comment by Eric89GXL** [comment]
Might as well try it

**Comment by jaeilepp** [comment]
Done. Build without cache running now.

**Comment by Eric89GXL** [comment]
Well the `save cache` step looks like it saved the directories. We'll have to see how it does on the next build.

**Comment by Eric89GXL** [comment]
Argh, still only restored the ones from before:

https://circleci.com/gh/mne-tools/mne-python/1432

**Comment by Eric89GXL** [comment]
I opened a forum topic:

https://discuss.circleci.com/t/cache-not-restoring-properly/4896

**Comment by jaeilepp** [comment]
> Argh, still only restored the ones from before:

I think how it works is that it uses the previous cache from the same branch. Only for new branches it uses the master's cache. I'll try with a new branch and see how it looks.

**Comment by jaeilepp** [comment]
And looks like for PRs it is using the master of the fork, so basically we'll see if clearing the cache worked when we merge something.

**Comment by jaeilepp** [comment]
So the problem with this _might_ be that every PR is using the cache of the user instead of upstream master. In that case, I think this would be reasonable if we could somehow only download the data that is being used.

**Comment by Eric89GXL** [comment]
Actually, in that case, we just won't auto-download anything. Each example when it runs will trigger a download if necessary. Let's try it.

**Comment by jaeilepp** [comment]
But the caching happens before the testing. So if we download at testing stage nothing gets cached. So at least for the master, the downloads should stay.

**Comment by Eric89GXL** [comment]
> So if we download at testing stage nothing gets cached. So at least for the master, the downloads should stay.

Yeah -- check the commit I pushed, this is what happens. For `master` builds it downloads during the first phase as before. For other builds, it does some (weak) introspection to see if it should get the `sample` dataset at least. In theory we could expand it to other datasets but this should get 90% of use cases hopefully.

**Comment by Eric89GXL** [comment]
Hooray, it worked!

https://circleci.com/gh/mne-tools/mne-python/1446#artifacts

@jaeilepp feel free to merge if you're happy.

**Comment by Eric89GXL** [comment]
(I killed the Travis build manually since the last commit only changed Circle, look one commit back to see Travis passing)

**Comment by agramfort** [comment]
thx @Eric89GXL

**Pull request merged**
