### PR TITLE
fix vline when scrolling in epochs browser

### PR DESCRIPTION
**Pull request by drammock**
this is item 4 from #8761

### CODE REVIEW

**Comment by jasmainak** [comment]
Thanks @drammock for giving a stab at this. When I tried to make a green vertical line by left clicking, this happened:

image

here's how I got to epochs:

```py
import os
import mne

sample_data_folder = mne.datasets.sample.data_path()
sample_data_raw_file = os.path.join(sample_data_folder, 'MEG', 'sample',
                                    'sample_audvis_raw.fif')
raw = mne.io.read_raw_fif(sample_data_raw_file, verbose=False).crop(tmax=120)

events = mne.find_events(raw, stim_channel='STI 014')
event_dict = {'auditory/left': 1, 'auditory/right': 2, 'visual/left': 3,
              'visual/right': 4, 'face': 5, 'button': 32}
epochs = mne.Epochs(raw, events, tmin=-0.2, tmax=0.5, event_id=event_dict,
                    preload=True)
```

**Comment by drammock** [comment]
are you using the macos backend for MPL?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by jasmainak** [comment]
so I had started using 

```sh
$ ipython --matplotlib
```

what I thought was the recommendation but I just checked and it seems the recommendation is:


```sh
$ ipython --matplotlib=qt
```

and with this, it works!

**Comment by jasmainak** [comment]
Actually no, it doesn't work on that backend either. I spoke too soon. It depends where you click. Should I try another backend?

**Comment by agramfort** [comment]
I replicate the problem on my machine.

**Comment by larsoner** [comment]
I cannot replicate on my MacOSX backend, but I do get this:
```
(base) $ MPLBACKEND=MacOSX python -ui rep.py 
Traceback (most recent call last):
  File "/Users/larsoner/opt/miniconda3/lib/python3.8/site-packages/matplotlib/cbook/__init__.py", line 224, in process
    func(*args, **kwargs)
  File "/Users/larsoner/python/mne-python/mne/viz/_figure.py", line 563, in _resize
    old_width, old_height = self.mne.fig_size_px
```
And interaction with this backend is pretty bad. I recommend people use Qt5Agg on macOS, the experience will probably be better.

We should still fix this, but I wish the default backend on macOS was Qt5Agg so we didn't have to keep working around the MacOSX backend flaws in our code :(

**Comment by drammock** [comment]
> I wish the default backend on macOS was Qt5Agg so we didn't have to keep working around the MacOSX backend flaws in our code :(

Another alternative is that one of you folks who has a mac laptop can do all the 2D viz work (or ship a mac laptop to me) :)

**Pull request closed without merging**
