### PR TITLE
MRG: Raw PSD respects annotations

### PR DESCRIPTION
**Pull request by Eric89GXL**
This makes `raw.plot_psd()` respect / ignore annotations by default. Ready for review/merge from my end.

cc @wronk 

@mmagnuski you might be interested, too, since you have some PSD-related PR going IIRC.

### CODE REVIEW

**Comment by dengemann** [comment]
Nice! Finally!

**Comment by wronk** [comment]
Thanks @Eric89GXL, LGTM other than Travis whining about VTK. I'll have time to test this next week, but no need to wait from a merge standpoint if everyone else is happy

**Comment by wronk** [comment]
Downloaded the PR and it seems to be working as intended -- the PSD shifts depending on if I include annotations or not in raw objects.

**Comment by agramfort** [comment]
travis is red !

**Comment by Eric89GXL** [comment]
One flake error and two false positives (timeout, weird semi-common generator error). Flake error has been fixed.

**Comment by agramfort** [comment]
thx @Eric89GXL  !

@wronk you can now give it a try between two barbecues in your camping trip :)

**Comment by wronk** [comment]
Took me until today because, like this PR, the BBQs merged.

**Comment by wronk** [comment]
The effect from annotation filtering issues doesn't seem that big. Turns out SSP has a bigger effect (even though the same projection vectors were used for all runs). I'm guessing that the SSP projection had a more pronounced effect for motor runs since that's the data from which they were calculated. Therefore, the motor data ended up with lower variance/broadband power and led to bias during classification.

**Comment by wronk** [comment]
Raw data: 



Raw + filtering + SSP; W/out annotation correction:


Raw + filtering; W/out annotation correction:


Raw + filtering; WITH annotation correction:

**Comment by agramfort** [comment]
you had some subjects with much stronger differences between rest and task.
Can you show one of those?

**Comment by Eric89GXL** [comment]
Also, you could consider computing your EOG/ECG projections from the concatenated raw data instead of just one of the runs.

**Comment by wronk** [comment]
Raw data: 



Raw + filtering + SSP; W/out annotation correction:



Raw + filtering; W/out annotation correction:



Raw + filtering; WITH annotation correction:

**Comment by wronk** [comment]
@Eric89GXL, that might be a good way around the SSP part of the issue. The rest must somehow be related to filtering (even though I'm doing the same pipeline for all runs)

**Comment by agramfort** [comment]
you should not have such differences between rest and task
if you did properly your data cleaning.

my 2c

**Comment by Eric89GXL** [comment]
Filtering might create problems at the annotations by spreading the artifacts, can you check?

**Comment by Eric89GXL** [comment]
Basically try just SSP or just filtering to see which one causes the shift.

**Comment by wronk** [comment]
Upon more inspection, appears that `hcp.preprocessing.apply_ref_correction` is the culprit. I'll post more comparisons tomorrow

**Comment by wronk** [comment]
@Eric89GXL, looks like just SSP or just BP filtering doesn't seem to have a major effect in terms of changing the PSD across runs (at least at a very high-level view of averaging across all sensors of an entire run). I count about 6 out of 20 where SSP alone seemed to introduce a very mild but noticeable change in the PSD from the raw data, so it doesn't seem like BP filtering without accounting for annotations (at least w/ reasonable params: 0.1 Hz - 55 Hz) is causing any large scale problems. However, changing those corner frequencies or having more severe artifacts could change the outcome.

`hcp.preprocessing.apply_ref_correction` is certainly changing PSDs, and looks to be the problem for my classification (but I'll need to rerun everything to make sure). 7 of 20 PSDs were moderately changed and 3 more were pretty severely altered. For all those changed, `apply_ref_correction` seemed to boost power in the resting state runs.

**Pull request merged**
