### PR TITLE
Fix to sklearn imports.

### PR DESCRIPTION
**Pull request by jaeilepp**
I think there is something wrong with how sklearn handles deprecations. I couldn't find a better way to make it work on every platform.

EDIT: In the end, I think my setup was somehow wrong. Now it is cleaner than in the beginning.

### CODE REVIEW

**Comment by agramfort** [comment]
thanks a lot @jaeilepp 

let us know when travis is happy

**Comment by agramfort** [comment]
travis complains

**Comment by jaeilepp** [comment]
I'm not sure how we fixed the flake errors we get [here](https://travis-ci.org/mne-tools/mne-python/jobs/176691773). @Eric89GXL any idea?

**Comment by Eric89GXL** [comment]
That shouldn't really happen because `setup.cfg` has been set up in latest `master` to ignore 305. Try rebasing

**Comment by Eric89GXL** [comment]
Oh, maint/0.12. You need to add to `setup.cfg`, might as well do it here

**Comment by Eric89GXL** [comment]
...but we should be careful when merging this, it is going to overwrite our `stable` docs.

**Comment by jaeilepp** [comment]
I actually disabled the update of docs in an earlier push https://github.com/mne-tools/mne-python/blob/maint/0.12/circle.yml.

**Comment by jaeilepp** [comment]
Seems that the warnings for str.format are also disabled. Maybe the format fixes should be done on master too. My understanding is that ``'{}'.format('smth')`` does not work on python 3.0. Not sure if anyone is using it...

**Comment by Eric89GXL** [comment]
That works fine on Py3k, but doesn't work on 2.6. Maybe that's what you're thinking of? In which case it's fine because we have dropped support for 2.6

**Comment by Eric89GXL** [comment]
https://travis-ci.org/mne-tools/mne-python/jobs/176711910#L2748

We need to change the decorator to `except Exception` instead of `except ImportError`

**Comment by jaeilepp** [comment]
Travis now passes. I don't understand the problem with appveyor.

**Comment by agramfort** [comment]
ok that's good enough for me

thx @jaeilepp

**Pull request merged**
