### PR TITLE
change toggle from 'h' to 't'

### PR DESCRIPTION
**Pull request by mainakjas**
cc @teonlamont

### CODE REVIEW

**Comment by mainakjas** [comment]
thanks @mainakjas :D

**Comment by teonlamont** [comment]
you got rid of the 'h' entirely??

**Comment by mainakjas** [comment]
I just changed the keyboard shortcut from 'h' to 't'. Rest is all the same

**Comment by teonlamont** [comment]
so I can still hide all the plots with 'h'. if so, why isn't it in the `whats_new` anymore?

**Comment by mainakjas** [comment]
no you can't do that.

**Comment by teonlamont** [comment]
why...?

**Pull request merged**
