### PR TITLE
Removed ellipsis in combination with time mask.

### PR DESCRIPTION
**Pull request by jaeilepp**

### CODE REVIEW

**Comment by dengemann** [comment]
Looks good. We should actually see which numpy version is protesting to the previous syntax.

**Comment by jaeilepp** [comment]
There are quite a few of test failures, but I suppose it is safe to merge?

**Comment by dengemann** [comment]
> There are quite a few of test failures, but I suppose it is safe to merge?

let's not assume that ... having a look.

**Comment by dengemann** [comment]
seems unrelated, we only changed testing code here, right?

**Comment by jaeilepp** [comment]
Actually the changes are in ``tfr.py`` and ``psd.py``, but the equivalent changes passed on master. This maint branch just doesn't have the same fixes in place.

**Comment by Eric89GXL** [comment]
Looks okay to me, failures are unrelated

**Comment by agramfort** [comment]
@jaeilepp can you backport, tag a maintenance release, and update the debian package?

thx

**Pull request merged**
