### PR TITLE
FIX : #5906 epochs plot index error

### LINKED ISSUE #5906: IndexError in epochs.plot() when first epoch of next page is marked as bad and there is a bad channel
#### Description:
An IndexError occurs when the first epoch of the next page (i.e. epoch nr 21 when n_epochs=20) is marked as bad and there is a bad channel. It would be fixed by changing:

 _if bad_idx < start_idx or bad_idx __>__ end_idx:_  _(line 1275 of /mne/viz/epochs.py)_
to:
 _if bad_idx < start_idx or bad_idx __>=__ end_idx:_

However, I'm surprised that this didn't show up before (since the commit that introduced this line is from 2015), therefore I'm asking here before submitting the pull request. Should I go ahead?

#### Steps to reproduce:
import mne
import os.path as op

data_path = mne.datasets.sample.data_path()
raw = mne.io.read_raw_fif(op.join(data_path, 'MEG/sample/sample_audvis_raw.fif'))
events = mne.find_events(raw, stim_channel='STI 014')
event_id = {'Auditory/Left': 1, 'Auditory/Right': 2}
epochs = mne.Epochs(raw, events, event_id, tmin=-0.1, tmax=1, baseline=(None, 0), preload=True)
epochs.plot(block=True)

-> mark one channel as bad
-> press right arrow to go to next page
-> mark the first epoch of the new page as bad
-> press left arrow to go to the previous page

#### Expected results
No error

#### Actual results
_IndexError: index 20 is out of bounds for axis 0 with size 20_

#### Additional information
Platform:      Linux-4.15.0-45-generic-x86_64-with-debian-buster-sid
Python:        3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51)  [GCC 7.2.0]
Executable:    /home/eze/soft/anaconda3/envs/mne3/bin/python
CPU:           x86_64: 8 cores
Memory:        15.6 GB
mne:           0.18.dev0
numpy:         1.15.0 {blas=mkl_rt, lapack=mkl_rt}
scipy:         1.1.0
matplotlib:    2.2.2 {backend=Qt5Agg}
sklearn:       0.19.1
nibabel:       2.3.0
mayavi:        4.7.0.dev0 {qt_api=pyqt5, PyQt5=5.9.2}
cupy:          Not found
pandas:        0.23.3
dipy:          Not found

### PR DESCRIPTION
**Pull request by agramfort**
closes #5906

### CODE REVIEW

**Comment by larsoner** [comment]
CircleCI is unrelated and I'll need to fix it

**Comment by larsoner** [comment]
Same with the Travis pip run

**Comment by larsoner** [comment]
AppVeyor was a download timeout error.

Is it worth adding a test to the epoch plotting tests?

**Comment by agramfort** [comment]
no strong feeling here.

>

**Comment by larsoner** [comment]
Thanks @agramfort

**Pull request merged**
