### PR TITLE
Fix html table scrolling again

### PR DESCRIPTION
**Pull request by drammock**
The prior fix in #8977 seems to have been short-lived.  Locally for me with latest docutils (0.17) this now works again (pretty-printing dataframes in our tutorials once again creates a horizontal scrollbar).  Let's see if CircleCI behaves the same way.

Also removes from website template cruft that is no longer needed due to theme updates.

### CODE REVIEW

**Comment by agramfort** [comment]
can you share a rendered page with the fix? thx

>

**Comment by drammock** [comment]
@larsoner it seems like CircleCI is no longer auto-executing the tutorials that are edited in a PR?  The artifact for this PR (https://26834-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/epochs/plot_40_autogenerate_metadata.html) doesn't have any cell output.

**Comment by larsoner** [comment]
Should be fixed now, I reduced the regression when refactoring CircleCI yesterday

**Comment by larsoner** [comment]
https://26839-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/epochs/plot_40_autogenerate_metadata.html

**Comment by drammock** [comment]
Thanks @larsoner!  Looks like the horizontal scrolling is working again.  Ready for review/merge on my end.

**Review by larsoner — APPROVED** [review]

**Comment by larsoner** [comment]
Thanks @drammock

**Pull request merged**
