### PR TITLE
[ENH, MRG] Add maximum intensity projection button to ieeg locate gui 

### PR DESCRIPTION
**Pull request by alexrockhill**
Fixes https://github.com/mne-tools/mne-python/issues/10180.

I'm not sure I would use it, but it looks really cool and apparently Barry would like to use it so I have no problem adding it.

### CODE REVIEW

**Comment by agramfort** [comment]
can you share a screen shot?

**Comment by alexrockhill** [comment]
Ah yeah, right after I went to bed, I thought I should have done this

```
import os.path as op

import numpy as np
import matplotlib.pyplot as plt

import nibabel as nib
import nilearn.plotting
from dipy.align import resample

import mne
from mne.datasets import fetch_fsaverage

# paths to mne datasets: sample sEEG and FreeSurfer's fsaverage subject,
# which is in MNI space
misc_path = mne.datasets.misc.data_path()
sample_path = mne.datasets.sample.data_path()
subjects_dir = op.join(sample_path, 'subjects')

# use mne-python's fsaverage data
fetch_fsaverage(subjects_dir=subjects_dir, verbose=True)  # downloads if needed

# GUI requires pyvista backend
mne.viz.set_3d_backend('pyvistaqt')

T1 = nib.load(op.join(misc_path, 'seeg', 'sample_seeg', 'mri', 'T1.mgz'))
CT_orig = nib.load(op.join(misc_path, 'seeg', 'sample_seeg_CT.mgz'))
reg_affine = np.array([
    [0.99270756, -0.03243313, 0.11610254, -133.094156],
    [0.04374389, 0.99439665, -0.09623816, -97.58320673],
    [-0.11233068, 0.10061512, 0.98856381, -84.45551601],
    [0., 0., 0., 1.]])
CT_aligned = mne.transforms.apply_volume_registration(CT_orig, T1, reg_affine)
subj_trans = mne.coreg.estimate_head_mri_t(
    'sample_seeg', op.join(misc_path, 'seeg'))
raw = mne.io.read_raw(op.join(misc_path, 'seeg', 'sample_seeg_ieeg.fif'))

gui = mne.gui.locate_ieeg(raw.info, subj_trans, CT_aligned,
                          subject='sample_seeg',
                          subjects_dir=op.join(misc_path, 'seeg'))
```
Screen Shot 2022-01-07 at 8 48 35 AM

**Review by larsoner — APPROVED** [review]
LGTM +1 for merge

**Review by drammock — APPROVED** [review]

**Comment by drammock** [comment]
merge conflict in changelog, otherwise this is ready to go @alexrockhill

**Review by agramfort — APPROVED** [review]

**Comment by agramfort** [comment]
thx @alexrockhill

**Pull request merged**
