### PR TITLE
ENH: Use setuptools_scm to set the version

### LINKED ISSUE #11466: MAINT: Switch to setuptools_scm
See for example

https://github.com/LABSN/tdtpy/pull/20

It basically does the `.dev` and versions for us automatically based on tags.

I think we *do* want to write `_version.py` in order to avoid people needing `setuptools_scm` (and new-ish setuptools or whatever) for our released versions. This is how `tdtpy` does it above. But I haven't totally thought it through...

We could maybe also transition to a `pyproject.toml` while we're at it.

### PR DESCRIPTION
**Pull request by larsoner**
This should allow us to follow our versioning rules just based on tagging correctly. Based on it locally naming this `1.4.0.dev64+g940dd1e2ba` I think it's working

Closes #11466

### CODE REVIEW

**Comment by larsoner** [comment]
Notebook failure is unrelated / #10946. It seems to be working in CIs, e.g. [here](https://app.circleci.com/pipelines/github/mne-tools/mne-python/18121/workflows/5cfd66b4-99c6-47e6-a29a-a7b0be69d030/jobs/52780?invite=true#step-117-17):
```
mne:                 1.4.0.dev68+g2cecb01b9
```
Ready for review/merge from my end

**Review by hoechenberger — APPROVED** [review]

**Comment by hoechenberger** [comment]
Interesting, it seems I cannot merge unless everything is green (no override). Lack of permissions, I suppose 😕

**Comment by larsoner** [comment]
I've restarted the problematic CI and am making for merge when green

**Review by agramfort — APPROVED** [review]
sounds like the right thing to do

thx @larsoner

**Pull request merged**
