### PR TITLE
WIP: FreeSurfer env

### PR DESCRIPTION
**Pull request by christianbrodbeck**
@larsoner I am trying to source `SetUpFreeSurfer.sh` before running the FreeSurfer command, but can't get it to update `env`; do you know how to do that?

CC @agramfort

### CODE REVIEW

**Comment by larsoner** [comment]
> but can't get it to update env; do you know how to do that?

We did this for PySurfer for a while with:

https://github.com/nipy/PySurfer/pull/132
https://github.com/nipy/PySurfer/pull/149

At some point but it ended up being fragile (it broke things on OSX, Linux, or both, can't remember offhand).

Are you on OSX? If so this workaround (what we do now in PySurfer) might be sufficient:

https://github.com/nipy/PySurfer/blob/master/surfer/io.py#L184

**Comment by christianbrodbeck** [comment]
Hm, the error I get is below, also after I add the following to _prepare_env:

```
        ld_path = op.join(fs_home, 'lib', 'gcc', 'lib')
        if 'DYLD_LIBRARY_PATH' in env:
            env['DYLD_LIBRARY_PATH'] = ld_path + ':' + env['DYLD_LIBRARY_PATH']
        else:
            env['DYLD_LIBRARY_PATH'] = ld_path
```

```
In [2]: mne.bem.make_watershed_bem('fsaverage', '.', overwrite=True)

Running mri_watershed for BEM segmentation with the following parameters:

SUBJECTS_DIR = .
SUBJECT = fsaverage
Results dir = ./fsaverage/bem/watershed

Running subprocess: mri_watershed -useSRAS -surf ./fsaverage/bem/watershed/fsaverage ./fsaverage/mri/T1.mgz ./fsaverage/bem/watershed/ws

Mode:          use surfaceRAS to save surface vertex positions
Mode:          Saving out BEM surfaces

*********************************************************
The input file is ./fsaverage/mri/T1.mgz
The output file is ./fsaverage/bem/watershed/ws
dyld: lazy symbol binding failed: Symbol not found: ___emutls_get_address
  Referenced from: /Applications/freesurfer/bin/../lib/gcc/lib/libgomp.1.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ___emutls_get_address
  Referenced from: /Applications/freesurfer/bin/../lib/gcc/lib/libgomp.1.dylib
  Expected in: /usr/lib/libSystem.B.dylib

(u'', u'')
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
<ipython-input-2-5182d048f8c8> in <module>()
----> 1 mne.bem.make_watershed_bem('fsaverage', '.', overwrite=True)

/Users/christian/Code/mne-python/mne/bem.py in make_watershed_bem(subject, subjects_dir, overwrite, volume, atlas, gcaatlas, preflood, show, verbose)

/Users/christian/Code/mne-python/mne/utils.pyc in verbose(function, *args, **kwargs)
    726         with use_log_level(verbose_level):
    727             return function(*args, **kwargs)
--> 728     return function(*args, **kwargs)
    729 
    730 

/Users/christian/Code/mne-python/mne/bem.py in make_watershed_bem(subject, subjects_dir, overwrite, volume, atlas, gcaatlas, preflood, show, verbose)
   1107                 'Results dir = %s\n' % (subjects_dir, subject, ws_dir))
   1108     os.makedirs(op.join(ws_dir, 'ws'))
-> 1109     run_subprocess(cmd, env=env)
   1110 
   1111     if op.isfile(T1_mgz):

/Users/christian/Code/mne-python/mne/utils.pyc in run_subprocess(command, verbose, *args, **kwargs)

/Users/christian/Code/mne-python/mne/utils.pyc in verbose(function, *args, **kwargs)
    726         with use_log_level(verbose_level):
    727             return function(*args, **kwargs)
--> 728     return function(*args, **kwargs)
    729 
    730 

/Users/christian/Code/mne-python/mne/utils.pyc in run_subprocess(command, verbose, *args, **kwargs)
   1217         err_fun = subprocess.CalledProcessError.__init__
   1218         if 'output' in _get_args(err_fun):
-> 1219             raise subprocess.CalledProcessError(p.returncode, command, output)
   1220         else:
   1221             raise subprocess.CalledProcessError(p.returncode, command)

CalledProcessError: Command '['mri_watershed', '-useSRAS', '-surf', './fsaverage/bem/watershed/fsaverage', './fsaverage/mri/T1.mgz', './fsaverage/bem/watershed/ws']' returned non-zero exit status -6
```

**Comment by larsoner** [comment]
IIRC that looks a lot like the errors I got with PySurfer on OSX without the fix there. Maybe the `DYLD_LIBRARY_PATH` needs to be prepended instead of appended...

Do the PySurfer tests pass for you?

**Comment by larsoner** [comment]
And to be clear, you have already sourced the Freesurfer setup script in a terminal (and the command works in the terminal) before running this Python script?

**Comment by christianbrodbeck** [comment]
> And to be clear, you have already sourced the Freesurfer setup script in a terminal (and the command works in the terminal) before running this Python script?

Ah no, if I do that then the command works :) , the point of this was to try to add it in the Python wrapper. If that is not doable then I guess we should raise a better error requesting the user to quite Python, source the setup script, and retry?

**Comment by larsoner** [comment]
I'd just improve the error message. But if you want to follow the trail of PRs/issues I linked to and try to make that solution work properly to avoid this extra step, that's fine by me

**Comment by larsoner** [comment]
@christianbrodbeck okay to close this one, then?

**Pull request closed without merging**
