### PR TITLE
ENH: check coreg output subject name

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR prompts a dialog when the name of the subject chosen to save the scaled anatomy already exists.

It's still work in progress. I ran into issues because the dialog does not start from the main thread.

It's an item of #8833

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
> I ran into issues because the dialog does not start from the main thread.

The dialog must be created on the main thread and the request to show must be made indirectly with a signal. I had to do some Qt gymnastics to support this. It's the idea behind the convenience class `_QtDialogCommunicator`.

**Comment by GuillaumeFavelier** [comment]
An idea for another PR would be to organize all the dialogs in `_configure_dialogs` and reuse them instead of creating a new instance each time.

**Comment by GuillaumeFavelier** [comment]
This is ready for review @larsoner, @agramfort

**Comment by larsoner** [comment]
It seems like it's mostly there, but I did find a few bugs by testing the code on some simple cases.

# Discard

Unrelated to this PR, but something we should fix, is another bug related to the `Discard` business. On my Ubuntu Linux system running Gnome-shell, I get:
```
Traceback (most recent call last):
  File "/home/larsoner/python/mne-python/mne/viz/backends/_qt.py", line 67, in func
    callback(button_name)
  File "/home/larsoner/python/mne-python/mne/gui/_coreg.py", line 1799, in _close_dialog_callback
    assert button_name == "Discard"
AssertionError
```
In my case it's `"Close without Saving"`, but I really think we should stop trying to find every variant of "discard"-like things that the given OS / UI can decide to put as the "discard" text. It seems fragile, and I don't think it adds much value.

# Incorrect prompt on exit

First bug, I don't have any MRI fiducials for `sample`. if I do this:
```
$ mne coreg -s sample -d subjects --fif MEG/sample/sample_audvis_raw.fif --trans MEG/sample/sample_audvis_raw-trans.fif 
```
then lock fids, change to uniform scale mode, set to 99, put subject name as "test", then click the X to exit, I get a prompt to save the scaled subject anatomy (good!). But if I click "Save":

1. It saves the MRI fiducials, even though I wasn't prompted about it (probably no prompt because I did not modify the MNI-pos fiducials, which is good, but it's bad that it wrote it out anyway):

   Screenshot from 2022-02-23 13-15-00

    This seems like a bug that we should fix before 1.0

2. During this save operation, the UI is totally frozen. That's okay, but if we could change the mouse pointer to be a "busy" one while hovering over the Qt window, that's at least a minimal sign to the user that they shouldn't expect any of their inputs to work. Someday maybe we can add a progress bar with UI updates -- let's add a progressbar to the TODO. Hopefully the "busy" cursor is easy and doable here, but if not, add that to the TODO as well.

# Enhancement

When the user enters text into the "Save scaled anatomy" text entry box, it should be easy enough to check to see if the text that they entered is in the `set(subjects)` in the given `subjects_dir` (this check should take < 1 ms, so with every key stroke should be fine). If it is, you could modify the save button to indicate this. I'm not sure if there is a standard way to do this, but even something like `button.setStyleSheet("border:2px solid #ff0000;")` might be enough to indicate to the user that they have typed in a "taken" subject name, which could save them from needing to click to find out via the prompt. Then, the prompt is really there just to make sure they're certain that they want to overwrite.

# Bug

Remove `subjects/sample/bem/sample-fiducials.fif` if it exists. Run the command line above from "Incorrect prompt on exit". Click "Lock" to accept the MNI fids. Scale mode to uniform. Enter 90. Enter "test" as the subject name. (It should already exist from trying the "Incorrect prompt on exit" before. If it doesn't just save it, and restart this process.) Clicking "Save scaled anatomy" correctly prompts for overwrite, but "Cancel" and "No" are both provided, even though in this case (when not in "Exiting" mode) they do the same thing in principle, right? So it seems like "Cancel" is not needed here. When exiting, you *do* need both, because "no" means "discard the edits and exit" while "cancel" just means "cancel the save and cancel the exit, return me to the UI without doing anything".

Another bug here is that, even if I click "No", the MRI fiducials are written to disk again.

**Comment by GuillaumeFavelier** [comment]
> It saves the MRI fiducials

The function `_save_subject()` was always saving fiducials. I think it was needed before but now that we have a dialog to handle that, I can remove it. 

> Clicking "Save scaled anatomy" correctly prompts for overwrite, but "Cancel" and "No" are both provided, even though in this case (when not in "Exiting" mode) they do the same thing in principle, right?

To be exact, the function `_save_subject()` also handles BEM computation. I'll rework the scenario for "No" and remove "Cancel".

**Comment by GuillaumeFavelier** [comment]
I'll update once https://github.com/mne-tools/mne-python/pull/10397 is merged

**Comment by GuillaumeFavelier** [comment]
I removed some unused traits, fixed a bug with cursor and implemented [your suggestions](https://github.com/mne-tools/mne-python/pull/10378#issuecomment-1049085806) @larsoner 

I also spent some time trying to fix the issue with `Test Notebook` but I did not find anything so far.
When I tested using `pyvista-wheels` on a remote server, I ran into errors with GLIBC.

**Comment by larsoner** [comment]
It works much better!

> fixed a bug with cursor and implemented your suggestions @larsoner

For me the spinning cursor works/appears if my mouse is over the main window, but not if it's over the modal dialog save/close/discard dialog, or over the overwrite dialog (if that's also opened, in this case it is -- I have already clicked "yes" to overwrite here):


https://user-images.githubusercontent.com/2365790/156604565-761c4d91-54df-4a24-8546-1656f513fab9.mp4



This is not a deal breaker, but if you can find a quick fix for this then that's even better! If you don't feel like looking now or it turns out not to be easy, though, feel free to add it to the `coreg` TODO list for future work.

One thing that might be good to fix is that, if the subject name already exists (here, `test`), and you scale, click exit, get a dialog to save, say yes, then get a dialog to overwrite, and say no, this shouldn't exit but rather be the same as saying cancel. That way there is no risk of lost work. In other words, this is wrong/dangerous (`'test'` already exists for me starting this):

https://user-images.githubusercontent.com/2365790/156605739-5469f607-f8c5-475c-a41d-1155f536acf4.mp4

I know "cancel" was an option on that second dialog, but I have a feeling users will readily click "no" here. So the first (close) dialog should only actually close / accept the close event if all subsequent dialogs that are spawned successfully save. Or maybe better, that second dialog needs to say "Close without saving" rather than "No", since "No" does not make it clear that this really ends up being a "Discard"-like operation.

**Comment by GuillaumeFavelier** [comment]
I replaced "No" by "Discard" :sweat_smile: 

image

And I hope the issue with the cursor is solved as well

**Comment by larsoner** [comment]
> And I hope the issue with the cursor is solved as well

It's not, this is after clicking "yes" to save, see how the cursor stays an arrow on the modal dialog even though now it should be spinning there, too:


https://user-images.githubusercontent.com/2365790/156773696-944f9c4a-6904-403b-bc1a-992684c27839.mp4

I pushed a little commit to set/unset the cursor for the dialog itself during the `callback`. It fixes this behavior above for me @GuillaumeFavelier :


https://user-images.githubusercontent.com/2365790/156774207-2226ed5f-5ed0-41f2-9ece-5b7cf6e36c63.mp4

I can't figure out how to get the spinning cursor to show even on the window decorations, but this is probably good enough. (Maybe QApplication.setOverrideCursor, but this seems like overkill!) Let me know if you're happy with this and I'll merge!

**Comment by GuillaumeFavelier** [comment]
So it needs to be set for each widget even though I set the parent of the dialog to be the window? Alright, I'm okay with a `WaitCursor` to wait until the end of the callback :+1: 

> Let me know if you're happy with this and I'll merge!

BTW @larsoner, I opened https://github.com/mne-tools/mne-python/pull/10411 to deal with `Test Notebook`. It does not seem to finish in here.

**Comment by larsoner** [comment]
Thanks @GuillaumeFavelier !

**Pull request merged**
