### PR TITLE
MRG sklearn .18 n_splits

### LINKED ISSUE #3578: BUG: Breakages in time_gen with latest numpy and sklearn
First one probably needs to be `np.maximum` instead of `np.max`:
```
  File "/home/larsoner/custombuilds/mne-python/mne/decoding/csp.py", line 604, in _ajd_pham
    tmp2 = (tmp * g12 - g21) / np.max(omega - 1, 1e-9)
  File "/home/larsoner/.local/lib/python2.7/site-packages/numpy-1.12.0.dev0+b91e8d8-py2.7-linux-x86_64.egg/numpy/core/fromnumeric.py", line 2249, in amax
    return amax(axis=axis, out=out, **kwargs)
  File "/home/larsoner/.local/lib/python2.7/site-packages/numpy-1.12.0.dev0+b91e8d8-py2.7-linux-x86_64.egg/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
TypeError: 'float' object cannot be interpreted as an index
```
Second one must be due to sklearn change:
```
  File "/home/larsoner/custombuilds/mne-python/mne/decoding/base.py", line 670, in _set_cv
    cv = XFold(n_folds=cv)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
```
@kingjr do you have time to look?

### PR DESCRIPTION
**Pull request by kingjr**
attempt to close #3578 & #3579

### CODE REVIEW

**Comment by kingjr** [comment]
@agramfort @Eric89GXL ready for review.

**Comment by agramfort** [comment]
is that it? I fixed more in 

https://github.com/mne-tools/mne-python/pull/3579

**Comment by kingjr** [comment]
Well but yours didn't pass did it? :]

**Comment by kingjr** [comment]
Yes I think that's it, we're currently relying on sklearn.cross_validation, which is backward compatible until sklearn .20; we'll have to make hard choices then: i.e. ask the user to get sklearn > .18 or hard copy old cross_validation objects in mne.

**Comment by Eric89GXL** [comment]
Can't we inspect the arguments and triage?

**Comment by kingjr** [comment]
> Can't we inspect the arguments and triage?

To me it's a sklearn bleeding edge issue; they decided to change their API, we shouldn't put too much into supporting it.

**Comment by Eric89GXL** [comment]
> they decided to change their API, we shouldn't put too much into supporting it.

But they have clear deprecation messages, right? This means we should use the new API if possible (by inspecting args) and fall back to the old way if necessary. This avoids warnings in the meantime. See e.g. #3582. I can take care of it if necessary

**Comment by kingjr** [comment]
That's what we do in the script. The bug came from a change of API in their
dev version.

For the examples I don't think we should create an if condition to handle
sklearn version. Just push until .20 and then update the examples with the
new API.

**Comment by Eric89GXL** [comment]
Sure for the examples. But I'm talking about our internal code -- the warnings (and error) in #3582 appear when running tests. We'll need to support 0.20+ and 0.18- eventually, so might as well do it now.

**Comment by Eric89GXL** [comment]
For the warning in #3582 it works but emits a warning. I think we need to do the same thing, i.e. triage based on sklearn version what arguments/calls to make.

**Comment by kingjr** [comment]
@Eric89GXL ok, I'll take a look. Ok to merge this one?

**Comment by Eric89GXL** [comment]
Yeah thanks @kingjr

**Pull request merged**
