### PR TITLE
[MRG] FIX #8486, Evoked and Epochs don't get split

### PR DESCRIPTION
**Pull request by hoechenberger**
This should fix the error on Circle

### CODE REVIEW

**Review by agramfort — APPROVED** [review]

**Comment by hoechenberger** [comment]
One Travis run times out, but the other one is genuinely failing. I'm not sure what's happening, I cannot reproduce. It appears there's a side-effect somewhere, altering `raw_fname`??

**Comment by hoechenberger** [comment]
@larsoner any idea?

**Comment by larsoner** [comment]
https://github.com/mne-tools/mne-python/blob/master/mne/tests/test_report.py#L499

is missing the `@testing.requires_testing_data` decorator

**Comment by hoechenberger** [comment]
D'oh!

**Comment by larsoner** [comment]
Thanks @hoechenberger 

In the future when there is an error on CircleCI, it's good practice to make some minor change to the example in the PR that is supposed to fix it. That way in the PR we can see that the example runs without issue. (CircleCI for PRs only builds changed examples by default.)

**Comment by hoechenberger** [comment]
Got it!

**Pull request merged**
