### PR TITLE
removed requirement for curv.*h files to create Brain object

### LINKED ISSUE #11703: Creation of Brain object should not require curv.*h file
### Description of the problem

Plotting a pial brain surface should only require the pial surface files. This is evident in the [mne freesurfer examples](https://mne.tools/stable/auto_tutorials/forward/50_background_freesurfer_mne.html#using-freesurfer-s-surface-reconstructions)

 Currently the initialization for the Brain object returns an error if missing a "curve.*h" file. 

### Steps to reproduce

```Python
f = Brain(subject, subjects_dir=subjects_dir, cortex='low_contrast', alpha=0.5,
         background='grey', surf='pial')
```

### Link to data

_No response_

### Expected results

A plot of a brain

### Actual results

  File "C:\Users\ae166\git\SentenceRep_analysis\ieeg\viz\mri.py", line 312, in _
    f = Brain(sub, subjects_dir=subj_dir, cortex='low_contrast', alpha=0.5,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ae166\.conda\envs\ieeg\Lib\site-packages\mne\viz\_brain\_brain.py", line 425, in __init__
    geo.load_curvature()
  File "C:\Users\ae166\.conda\envs\ieeg\Lib\site-packages\mne\viz\_brain\surface.py", line 179, in load_curvature
    self.curv = read_curvature(curv_path, binary=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ae166\.conda\envs\ieeg\Lib\site-packages\mne\surface.py", line 815, in read_curvature
    with open(filepath, "rb") as fobj:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ae166\\Box\\ECoG_Recon\\D28\\surf\\lh.curv

### Additional information

Platform             Windows-10-10.0.19044-SP0
Python               3.11.3 | packaged by Anaconda, Inc. | (main, Apr 19 2023, 23:46:34) [MSC v.1916 64 bit (AMD64)]
Executable           C:\Users\ae166\.conda\envs\ieeg\python.exe
CPU                  Intel64 Family 6 Model 158 Stepping 9, GenuineIntel (8 cores)
Memory               63.9 GB
Core
├☑ mne               1.4.0
├☑ numpy             1.24.3 (MKL 2023.1-Product with 4 threads)
├☑ scipy             1.10.1
├☑ matplotlib        3.7.1 (backend=TkAgg)
├☑ pooch             1.7.0
└☑ jinja2            3.1.2
Numerical (optional)
├☑ sklearn           1.2.2
├☑ numba             0.57.0
├☑ nibabel           5.1.0
├☑ dipy              1.7.0
├☑ pandas            2.0.1
└☐ unavailable       nilearn, openmeeg, cupy
Visualization (optional)
├☑ pyvista           0.39.1 (OpenGL 4.5.0 - Build 30.0.101.1692 via Intel(R) HD Graphics 630)
├☑ pyvistaqt         0.10.0
├☑ vtk               9.2.6
├☑ qtpy              2.3.1 (PyQt5=5.15.2)
└☐ unavailable       ipyvtklink, ipympl, pyqtgraph, mne-qt-browser
Ecosystem (optional)
├☑ mne-bids          0.12
└☐ unavailable       mne-nirs, mne-features, mne-connectivity, mne-icalabel, mne-bids-pipeline

### PR DESCRIPTION
**Pull request by Aaronearlerichardson**
#### Reference issue
Fixes #11703

#### What does this implement/fix?
Makes curv.*h files optional for creating Brain objects

### CODE REVIEW

**Comment by larsoner** [comment]
Makes sense to me! Can you add this change to doc/changes/latest.inc using `:newcontrib:` and add your name to doc/changes/names.inc?

**Comment by hoechenberger** [comment]
What is the status of this? 🙃

**Comment by Aaronearlerichardson** [comment]
I added the requested changes, and am waiting for someone to merge it I think?

**Comment by hoechenberger** [comment]
@larsoner Could you please take a look? 😄

**Comment by larsoner** [comment]
Nice! I think the one last thing missing now is a regression test. I would add it to `mne/viz/_brain/tests/` somewhere. We might already have tests that make a `tmp_path` copy of a subject -- you could modify one to remove the `lh.curv` for example after it's `shutil.copytree`d to the temp dir, and that should cover the new lines (the curv should be missing when the brain is plotted).

If it's not clear how to do it let me know and I can push a quick commit

**Review by hoechenberger — APPROVED** [review]

**Comment by larsoner** [comment]
Pushed a tiny test and marked for merge when green, thanks in advance Aaronearlerichardson !

**Pull request merged**
