### PR TITLE
[MRG] Update spm dataset to include dig montage.

### PR DESCRIPTION
**Pull request by jaeilepp**
Follow up to https://github.com/mne-tools/mne-python/pull/4444.

I removed the small raw file and replaced it with a dig montage.

### CODE REVIEW

**Comment by agramfort** [comment]
you will need to update some example files no?

**Comment by jaeilepp** [comment]
Well, this file is not really used anywhere in the examples. It's basically just for being able to use it with coregistration. Perhaps there's a place to mention it somewhere...

**Comment by agramfort** [comment]
ok fair enough

please merge

**Comment by agramfort** [comment]
thx @jaeilepp

**Pull request merged**
