### PR TITLE
[WIP] run_meg_tutorial in python

### PR DESCRIPTION
**Pull request by jaeilepp**
This is a python script converted from the C-version. It takes a bit longer to compute than the C-version. Especially the source_spaces portion. Is there a way to speed it up?
Also, I'm not sure if it is necessary to save all the files to hard drive. Is tutorials folder the right place for the scripts? Comments?

### CODE REVIEW

**Comment by jaeilepp** [comment]
Shell script for comparison: https://github.com/mne-tools/mne-scripts/blob/master/sample-data/run_meg_tutorial.sh

**Comment by agramfort** [comment]
I would put this script in mne-scripts. It's not really a tutorial as it's not documented and probably too much for one file in terms of content.

wdyt?

**Comment by jaeilepp** [comment]
You mean the different repo?

**Comment by agramfort** [comment]
yes.

**Comment by jaeilepp** [comment]
Okay, closing this.

**Pull request closed without merging**
