### PR TITLE
FIX: Bump tempita

### PR DESCRIPTION
**Pull request by Eric89GXL**
This bumps our tempita version to the latest one I could find, which is used by Cython (?).

@yarikoptic can you see if this helps with #3657?

### CODE REVIEW

**Comment by agramfort** [comment]
travis is not happy :(

**Comment by Eric89GXL** [comment]
@yarikoptic this should be working now if you have time to try it

**Comment by agramfort** [comment]
@yarikoptic can you check if tests on master pass?

**Comment by yarikoptic** [comment]
@agramfort I think it does!
```
python-mne_0.13+git8-gcb8707f+dfsg-1~nd70+1_amd64.build FAILED  1:31.42 real, 40.30 user, 17.94 sys, 2128472 out
python-mne_0.13+git8-gcb8707f+dfsg-1~nd80+1_amd64.build OK      6:47.90 real, 327.24 user, 28.88 sys, 3584264 out
python-mne_0.13+git8-gcb8707f+dfsg-1~nd90+1_amd64.build OK      8:47.24 real, 441.34 user, 34.38 sys, 4517712 out
python-mne_0.13+git8-gcb8707f+dfsg-1~nd+1_amd64.build   OK      7:56.35 real, 413.47 user, 27.18 sys, 4556416 out
python-mne_0.13+git8-gcb8707f+dfsg-1~nd12.04+1_amd64.build      FAILED  1:07.86 real, 25.36 user, 13.95 sys, 1750944 out
python-mne_0.13+git8-gcb8707f+dfsg-1~nd14.04+1_amd64.build      OK      6:04.05 real, 313.46 user, 21.07 sys, 3387680 out
python-mne_0.13+git8-gcb8707f+dfsg-1~nd15.04+1_amd64.build      OK      6:14.00 real, 316.48 user, 22.58 sys, 3517480 out
python-mne_0.13+git8-gcb8707f+dfsg-1~nd15.10+1_amd64.build      OK      6:22.35 real, 320.67 user, 24.78 sys, 3687736 out
python-mne_0.13+git8-gcb8707f+dfsg-1~nd16.04+1_amd64.build      OK      8:18.03 real, 433.04 user, 26.96 sys, 4333840 out
python-mne_0.13+git8-gcb8707f+dfsg-1~nd16.10+1_amd64.build      OK      8:03.70 real, 411.92 user, 27.97 sys, 4414720 out
```
there is a problem with default debian unstable atm due to some dependencies needing update (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=844714) so I will see how to go about it... otherwise -- uploading to neurodebian for now

**Comment by agramfort** [comment]
:beers: !

thx heaps

**Pull request merged**
