### PR TITLE
Fix scrollbar patch limits in epochs plotter

### PR DESCRIPTION
**Pull request by jasmainak**
cc @jaeilepp 

Closes https://github.com/mne-tools/mne-python/issues/2324

Got stung by it one too many times. In my opinion, the plotting is also nicer this way.

### CODE REVIEW

**Comment by agramfort** [comment]
@jaeilepp merge if you're ok

**Comment by jasmainak** [comment]
@Eric89GXL any opinion?

**Comment by Eric89GXL** [comment]
Looks reasonable to me. FYI an alternative single-command would be `np.clip` instead of `min(max())`, but min(max()) might actually be a little bit faster since they're builtins.

**Comment by agramfort** [comment]
works great

merged by rebase.

thx @jasmainak

**Pull request closed without merging**
