### PR TITLE
MRG: More links

### PR DESCRIPTION
**Pull request by larsoner**
This adds more links in the docs dropdown, and changes the placement.

### CODE REVIEW

**Comment by agramfort** [comment]
this is still a PR although it seems to have been commited to web site.

We have a process problem :)

**Comment by larsoner** [comment]
Yeah I thought you were on board with adding old versions, and doing so required some direct commits to `mne-tools.github.io`. Sorry about the hassle there.

But in the meantime, the core functionality seems to work properly I think (multiple versions and the like), so we can move on (backward) to deciding if the style/implementation is right. This is what these changes would do:

https://6243-1301584-gh.circle-artifacts.com/0/tmp/circle-artifacts.L1tjoOn/html/index.html

**Comment by agramfort** [comment]
we should prevent PRs to push to mne-tools website. only master should be allowed

**Comment by larsoner** [comment]
Yes only `master` and `maint/0.15` push to the website. The reason the dropdowns exist currently is that I did some pushes to `master` last night in prep for release during reorganization

**Comment by larsoner** [comment]
... so this PR is to tweak the visual and add `0.13`/`0.12`/`0.11` to what is already in `master`

**Comment by agramfort** [comment]
ok ok

we might need to trim down the size of the website repo and it's getting
really big (more than 1GB of stufff)

can we safely squash? won't break circle?

A

**Comment by larsoner** [comment]
yes I think we can safely squash now, in theory by putting 11/12/13/14 in folders it should capture the docs from those versions

CircleCI should be fine, now it cleans up old files before adding new ones anyway

**Comment by agramfort** [comment]
merge when it's green

thx @larsoner

**Comment by larsoner** [comment]
It's only red because I killed Travis and AppVeyor, as this only touches templates that `CircleCI` deals with :)

**Pull request merged**
