### PR TITLE
FIX: dock file button

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR fixes the dock file buttons. They were always a bit different than the rest of the API because they actually are a `_QtWidgetList` of a text widget and a standard button. This PR makes it so that they are only buttons now. The text fields are processed separately with `_dock_add_text()`.

The coreg app is also updated, the text fields are getting usable. Similarly to 'Save scaled anatomy', they provide a visual cue when the path is not correct, *i.e.* their border becomes red.

It's still work in progress, I have to add more checks.

### CODE REVIEW

**Comment by agramfort** [comment]
@GuillaumeFavelier can you share a screenshot?

**Comment by agramfort** [comment]
looks good

**Comment by GuillaumeFavelier** [comment]
I added a file picker to the `notebook` 3d backend. It's inspired from https://gist.github.com/elkhadiy/284900b3ea8a13ed7b777ab93a691719 and, from my usage, it works quite well:

https://user-images.githubusercontent.com/18143289/158833880-75130cc8-0b4e-43a6-ab2c-0f4d43825b14.mp4

But unfortunately I discovered an issue preventing the app to load the `trans` file. I'll continue to investigate.

**Comment by agramfort** [comment]
looks neat !

tell us when it's not anymore WIP at your end.

**Comment by GuillaumeFavelier** [comment]
It's fixed now. The variable used to lock plotting was not shared to the parameter thread:

https://user-images.githubusercontent.com/18143289/159019962-1f6b1b19-d5a1-4307-a8a5-10630d0d9d27.mp4

**Comment by GuillaumeFavelier** [comment]
This is ready for review from my end @agramfort, @larsoner

**Comment by GuillaumeFavelier** [comment]
I still have to work on 2 things:
- bug with `subjects_dir`
- allow to create a new file

**Comment by GuillaumeFavelier** [comment]
After d1077d6417e6639a9fb859e2f9893f6c9801e8de, this is the new face of the file picker:

image

**Comment by agramfort** [comment]
looks great ! good to go from your end then?

**Comment by GuillaumeFavelier** [comment]
> good to go from your end then?

It's indeed ready from my end @agramfort :ok_hand:

**Comment by agramfort** [comment]
@GuillaumeFavelier you have some CIs red? can you investigate? see if this is unique to this PR? maybe merge main?

**Comment by agramfort** [comment]
still failing :'(

**Comment by GuillaumeFavelier** [comment]
I don't understand why it happens in here, AFAIK the failing test is not directly related to the changes. I updated https://github.com/mne-tools/mne-python/pull/10430 hoping to reproduce.

**Review by agramfort — APPROVED** [review]

**Comment by agramfort** [comment]
thx @GuillaumeFavelier

**Pull request merged**
