### PR TITLE
MRG: whats new test

### LINKED ISSUE #2138: Whats New feature
Idea for What's new page. Add link to the function page for each new feature. e.g.

Add SourceSpaces.save_as_volume method by Alan Leggitt 
 would link here
http://martinos.org/mne/stable/generated/mne.SourceSpaces.html

Note, curiously, this is a bad example as the SourceSpaces does not describe a function titled save_as_volume

### PR DESCRIPTION
**Pull request by dgwakeman**
This is a copy of the sklearn pattern for the what's new page (note just one example to test first). I'm not sure if it will work or the best way to test. Comments, thoughts welcome.

closes #2138

### CODE REVIEW

**Comment by dengemann** [comment]
@dgwakeman go in ./doc/ and check out the make commands, you can build the docs to test it.

**Comment by Eric89GXL** [comment]
I'd do as @dengemann suggested, specifically the `make html_dev-noplot` command and look at the result in the `build` dir

**Comment by dgwakeman** [comment]
Sorry for the dummy questions. In doc all I see is:
ls -1
build_doc
Makefile
source
sphinxext
upload_html.sh
utils

when I run ./build_doc I get:
make: Nothing to be done for `html'.

There isn't a lot of documentation here. There is nothing named what @Eric89GXL described
Sorry

**Comment by dengemann** [comment]
@dgwakeman run ```cat Makefile``` to see the make commands listed

2015-06-23 18:06 GMT+02:00 dgwakeman <notifications@github.com>:

**Comment by dgwakeman** [comment]
I opened that but it is not intelligible to me. The command make isn't mentioned once in there (checked via grep). It's not clear to me what language this is even written in. There is no shebang. Again I am sorry for the noise.

**Comment by dengemann** [comment]
https://en.wikipedia.org/wiki/Makefile

2015-06-23 18:17 GMT+02:00 dgwakeman <notifications@github.com>:

**Comment by Eric89GXL** [comment]
You should be able to do `make html_dev-noplot` from the command line while in the `doc` dir. `make` is a program that knows how to interpret a `Makefile` to do certain commandns.

**Comment by dgwakeman** [comment]
Ok, worked that out. I haven't been able to get the links to work. I'll document what I've found so far here. Maybe someone who knows about sphinx can pick this up or give me a hint to help along. 

sklearn uses :func:`<path relative to sklearn separated by ".">.<function_name>`
Unfortunately, this uses some kind of magic remapping under the hood. I believe this is related to the following file: https://github.com/scikit-learn/scikit-learn/blob/master/doc/modules/classes.rst

Note: we don't have modules/classes.rst
Confusingly this uses :mod:, which is also not documented in sphinx (at least in a searchable way).

One other minor discovery was that sklearn uses a different default of sphinx in its doc/conf.py file:
# If true, '()' will be appended to :func: etc. cross-reference text.
add_function_parentheses = False

**Comment by dgwakeman** [comment]
ok @dengemann, I figured out how to create the links. For some reason, I haven't figured out why we need to cite them slightly differently than sklearn. The new problem is a lot of the documentation doesn't exist. For example, f_mway_rm hasn't been created. Is there a way to generate this?

fyi: this works
`:func:`mne.read_label`

**Comment by agramfort** [comment]
does the function you want to link to appears in the python_reference.rst
file?

**Comment by dgwakeman** [comment]
yes, under the statistics module. Does this file have to be processed by `make` in a way that `make html_dev-noplot` wouldn't?

**Comment by agramfort** [comment]
make html_dev-noplot should do it... maybe it's broken...

**Comment by dgwakeman** [comment]
Well, it seems like it is a series of functions. I noticed the following in the make output:

```
WARNING: [autosummary] failed to import 'mne.Dipole': no module named mne.Dipole
WARNING: [autosummary] failed to import 'mne.MixedSourceEstimate': no module named mne.MixedSourceEstimate
WARNING: [autosummary] failed to import 'mne.SourceSpaces': no module named mne.SourceSpaces
WARNING: [autosummary] failed to import 'mne.beamformer.rap_music': no module named mne.beamformer.rap_music
WARNING: [autosummary] failed to import 'mne.bem.make_watershed_bem': no module named mne.bem.make_watershed_bem
WARNING: [autosummary] failed to import 'mne.channels.find_layout': no module named mne.channels.find_layout
WARNING: [autosummary] failed to import 'mne.channels.generate_2d_layout': no module named mne.channels.generate_2d_layout
WARNING: [autosummary] failed to import 'mne.channels.make_eeg_layout': no module named mne.channels.make_eeg_layout
WARNING: [autosummary] failed to import 'mne.channels.make_grid_layout': no module named mne.channels.make_grid_layout
WARNING: [autosummary] failed to import 'mne.channels.read_layout': no module named mne.channels.read_layout
WARNING: [autosummary] failed to import 'mne.channels.read_montage': no module named mne.channels.read_montage
WARNING: [autosummary] failed to import 'mne.combine_evoked': no module named mne.combine_evoked
WARNING: [autosummary] failed to import 'mne.decoding.GeneralizationAcrossTime': no module named mne.decoding.GeneralizationAcrossTime
WARNING: [autosummary] failed to import 'mne.epochs.concatenate_epochs': no module named mne.epochs.concatenate_epochs
WARNING: [autosummary] failed to import 'mne.fit_dipole': no module named mne.fit_dipole
WARNING: [autosummary] failed to import 'mne.get_volume_labels_from_aseg': no module named mne.get_volume_labels_from_aseg
WARNING: [autosummary] failed to import 'mne.grand_average': no module named mne.grand_average
WARNING: [autosummary] failed to import 'mne.io.RawFIF': no module named mne.io.RawFIF
WARNING: [autosummary] failed to import 'mne.io.add_reference_channels': no module named mne.io.add_reference_channels
WARNING: [autosummary] failed to import 'mne.io.read_raw_fif': no module named mne.io.read_raw_fif
WARNING: [autosummary] failed to import 'mne.io.set_bipolar_reference': no module named mne.io.set_bipolar_reference
WARNING: [autosummary] failed to import 'mne.make_ad_hoc_cov': no module named mne.make_ad_hoc_cov
WARNING: [autosummary] failed to import 'mne.make_sphere_model': no module named mne.make_sphere_model
WARNING: [autosummary] failed to import 'mne.minimum_norm.estimate_snr': no module named mne.minimum_norm.estimate_snr
WARNING: [autosummary] failed to import 'mne.read_dipole': no module named mne.read_dipole
WARNING: [autosummary] failed to import 'mne.read_dipole': no module named mne.read_dipole
WARNING: [autosummary] failed to import 'mne.read_epochs_kit': no module named mne.read_epochs_kit
WARNING: [autosummary] failed to import 'mne.stats.f_mway_rm': no module named mne.stats.f_mway_rm
WARNING: [autosummary] failed to import 'mne.time_frequency.AverageTFR': no module named mne.time_frequency.AverageTFR
WARNING: [autosummary] failed to import 'mne.time_frequency.cwt_morlet': no module named mne.time_frequency.cwt_morlet
WARNING: [autosummary] failed to import 'mne.time_frequency.fit_iir_model_raw': no module named mne.time_frequency.fit_iir_model_raw
WARNING: [autosummary] failed to import 'mne.time_frequency.read_tfrs': no module named mne.time_frequency.read_tfrs
WARNING: [autosummary] failed to import 'mne.time_frequency.tfr_multitaper': no module named mne.time_frequency.tfr_multitaper
WARNING: [autosummary] failed to import 'mne.time_frequency.tfr_stockwell': no module named mne.time_frequency.tfr_stockwell
WARNING: [autosummary] failed to import 'mne.time_frequency.write_tfrs': no module named mne.time_frequency.write_tfrs
WARNING: [autosummary] failed to import 'mne.viz.ClickableImage': no module named mne.viz.ClickableImage
WARNING: [autosummary] failed to import 'mne.viz.add_background_image': no module named mne.viz.add_background_image
WARNING: [autosummary] failed to import 'mne.viz.plot_dipole_amplitudes': no module named mne.viz.plot_dipole_amplitudes
WARNING: [autosummary] failed to import 'mne.viz.plot_dipole_locations': no module named mne.viz.plot_dipole_locations
WARNING: [autosummary] failed to import 'mne.viz.plot_evoked_white': no module named mne.viz.plot_evoked_white
WARNING: [autosummary] failed to import 'mne.viz.plot_montage': no module named mne.viz.plot_montage
WARNING: [autosummary] failed to import 'mne.viz.plot_raw_psd': no module named mne.viz.plot_raw_psd
WARNING: [autosummary] failed to import 'mne.viz.plot_snr_estimate': no module named mne.viz.plot_snr_estimate
```

**Comment by Eric89GXL** [comment]
Most of those are fairly new functions. Did you install with `python setup.py develop`, or something else? I wonder if it is importing some old version of `mne-python` when building docs for some reason.

**Comment by dgwakeman** [comment]
@Eric89GXL, Thank You! You figured it out. I hadn't "installed" at all. I was just running on a fresh downloaded version of mne-dev, but hadn't run setup.py. I guess the script must have searched and found the stable version installed at Martinos: even though I hadn't imported it or anything. 

If I can find out how to turn off that search and only allow it to work on the current version (and return an error if setup.py hasn't been run: or maybe just have it call it), I will, but as a different PR. Ok, I will put this in a new PR, because I am now well behind Master and rebasing is scary.

**Comment by agramfort** [comment]
just run python setup.py develop --user and you will use your local version.

tell us when done here.

**Comment by dgwakeman** [comment]
Ok, this is good to go. @jaeilepp, please check that I cited the correct function. Thanks

**Comment by dgwakeman** [comment]
screenshot

**Comment by agramfort** [comment]
cool !

**Comment by jaeilepp** [comment]
Yeah, looks good.

**Comment by Eric89GXL** [comment]
Thanks @dgwakeman, this will be nice to have!

**Pull request merged**
