### PR TITLE
TST: Check Circle

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR follows https://github.com/mne-tools/mne-python/pull/7574#issuecomment-612106164 and tries to reproduce the warnings.

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
Okay so I'm able to reproduce on `master` but I swim in very dark waters here. From what I can decipher, `STIM channel` and `hpi` are not registered in a certain glossary.

**Comment by GuillaumeFavelier** [comment]
I suppose those two terms should be added in `doc/glossary.rst`

**Comment by GuillaumeFavelier** [comment]
Actually `stim channel` already exists so it could be an issue with case-sensitive stuff.

**Comment by larsoner** [comment]
Yes we build with `--pre` releases of Sphinx nowadays to catch these bugs early

**Comment by larsoner** [comment]
Thanks @GuillaumeFavelier

**Pull request merged**
