### PR TITLE
BUG: Fix add_figure for MNEQtBrowser

### PR DESCRIPTION
**Pull request by larsoner**
Closes https://github.com/mne-tools/mne-qt-browser/issues/77

Locally:
```
import mne
raw = mne.io.read_raw_fif(mne.datasets.sample.data_path() / 'MEG' / 'sample' / 'sample_audvis_raw.fif')
report = mne.Report()
report.add_figure(raw.plot(), title='Raw plot')
report.save('test.html', overwrite=True)
```

Now produces:

Screenshot from 2022-04-01 16-00-37

Note I cut out the statusbar and toolbar to at least move toward what @cbrnr was looking for.

For the overview bar, I think we should do that separately, if at all. It probably adds enough information in some examples (e.g., annot/event timing) that we want to keep it. If someone's motivated, it's easy enough to implement custom code-block parsing that would allow us to move to a "scrape only if a `# sphinx_gallery_include_overview_bar` comment present" functionality where the overview bar is turned off during scraping unless this opt-in comment is included in a given code block. Finding the right places to include it might be a lot of work, but it's one way to go if someone is motivated at some point.

### CODE REVIEW

**Comment by larsoner** [comment]
Okay looks like CircleCI is happy now at least

https://output.circle-artifacts.com/output/job/80b97536-080f-47d0-9142-900810bccee9/artifacts/0/dev/auto_tutorials/intro/70_report.html#adding-custom-figures

**Comment by cbrnr** [comment]
This is better than before. I'd use a light theme by default though, at least for our docs. I'm OK with dealing with the overview bar separately (but I still think it should be off by default in our docs).

**Comment by larsoner** [comment]
Circle CI should already use light (see Circle link for example), the dark one came from my machine

**Review by agramfort — APPROVED** [review]

**Comment by agramfort** [comment]
Thx @larsoner

**Pull request merged**
