### PR TITLE
MRG: Add smoothing controller to TimeViewer for the notebook backend

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR adds a controller to the `notebook` backend to set the number of smoothing steps when `time_viewer=True`.

**Issue**

The rendering cell is broken because of the text given by `logger` I think (the name of the backend and the number of iterations for smoothing).

image

image

It's part of #7162.

### CODE REVIEW

**Comment by larsoner** [comment]
I would just wrap [this call](https://github.com/mne-tools/mne-python/blob/master/mne/viz/_brain/_brain.py#L1009) in `with mne.use_log_level(False):` to always suppress these messages. They aren't really useful now that our morphing is fairly fast

**Comment by GuillaumeFavelier** [comment]
Your advice helped, now the messages about the number of iterations have stopped popping up.
If the first element of the rendered cell is not text, it works as expected, otherwise the cell is not flat and sliding is needed. This behaviour is totally normal.

**Comment by GuillaumeFavelier** [comment]
I can cherry-pick 1355296c69e8b54ccbeacd12deb3770296d85241 here if needed?

**Comment by larsoner** [comment]
Go ahead and I'll merge so it gets into master

**Comment by larsoner** [comment]
Thanks @GuillaumeFavelier

**Pull request merged**
