### PR TITLE
ENH: Colorbar width

### PR DESCRIPTION
**Pull request by Eric89GXL**
Taking over #1920 so @mainakjas can use it. @dengemann can you take a look and see if it's what you wanted?

### CODE REVIEW

**Comment by Eric89GXL** [comment]
@mainakjas can you make sure this has what you need?

**Comment by mainakjas** [comment]
Hold on, let me pull and see

**Comment by mainakjas** [comment]
@Eric89GXL works fine! maybe a little space below the title. I have to run now, feel free to merge when you are satisfied.

**Comment by Eric89GXL** [comment]
I agree about the title spacing, but I'll leave that for a future PR :)

**Comment by dengemann** [comment]
Having a look in a few minutes, once back on keyboard

**Comment by dengemann** [comment]
Thanks @Eric89GXL @cmoutard !!

**Comment by Eric89GXL** [comment]
Sweet thanks, now you can move on to docs, right? :)

**Comment by dengemann** [comment]
> Sweet thanks, now you can move on to docs, right? :)

Now I'm going out for dinner + drinks. Weekends tend to be busy in Paris ;)

**Comment by Eric89GXL** [comment]
Without your laptop to do mne-python coding? You must be hanging out with the wrong crowd.

**Comment by dengemann** [comment]
> Without your laptop to do mne-python coding? You must be hanging out with the wrong crowd.

;)

**Comment by mainakjas** [comment]
Thanks @Eric89GXL :)

**Comment by mainakjas** [comment]
and also @cmoutard !

**Pull request merged**
