### PR TITLE
Remove `jinja2` and `pooch` from `sys_info`

### LINKED ISSUE #12387: Consider removing jinja2 from `mne.sys_info()`
We've had many discussions on how we should handle dependencies, but given that we currently only include absolutely essential packages as core dependencies, I was wondering why we include `jinja2`. In my opinion, it would be better (more consistent) to make it an optional dependency. In addition, it is only imported in one location (`mne/html_templates/_templates.py`), and even there it is a nested import.

### PR DESCRIPTION
**Pull request by cbrnr**
Fixes #12387.

### CODE REVIEW

**Review by hoechenberger — APPROVED** [review]

**Review by larsoner — COMMENTED** [review]
Works for me. I think in principle maybe we could want all core dep versions listed somewhere, but in practice over the many years we've had this I don't think these have ever been useful to have reported. So I'm okay with removing them in favor of trimming things down a bit. But @drammock you had suggested possibly moving them rather than removing them so I'll let you look before merge

**Comment by larsoner** [comment]
> Of course, we already have a dependencies="developer" option, where we could also move these packages to.

Works for me and might satisfy @drammock's desire to keep them somewhere (he had suggested `misc` I think but maybe lumping under `developer` is good enough)

**Review by cbrnr — COMMENTED** [review]
I added the other required packages to a new section called "Infrastructure". Well, all but `lazy_loader`, which doesn't have a version attribute.

**Comment by drammock** [comment]
pushed a commit to hopefully fix Circle, which seems to have been broken by docdict changes in #12195 

cc @withmywoessner; see [43094a7](https://github.com/mne-tools/mne-python/pull/12411/commits/43094a75599218ec20dfdfe19bde5ed1ee03cdce); I think the only *necessary* changes were the ones relating to blank lines, but I took the opportunity to clean up the formatting a bit too

**Review by drammock — APPROVED** [review]

**Comment by drammock** [comment]
reported the missing lazy_loader version upstream: https://github.com/scientific-python/lazy_loader/issues/96

**Comment by drammock** [comment]
pip-pre failure is being tracked in #12413

**Pull request merged**
