### PR TITLE
ENH add gantry angle IO to FIFF consts and meas_info

### PR DESCRIPTION
**Pull request by cjayb**
Elekta's official `fiff_support` libs have included (amongst others) a tag for gantry position.

```c
#define FIFF_GANTRY_ANGLE          282    /* Tilt angle of the gantry in degrees. */
```

Presumably this is included in all subsequent DACQ versions, so practically all VectorView __and__ Triux files will have this tag set. Notably, `sample` doesn't ;)

For this PR I simply followed the tag `line_freq` down the code in `meas_info.py`, and added a new key `gantry_angle` everywhere.

BTW, it's useful to know the angle when diagnosing far-away noise sources and EAS (some directions are better compensated than others).

### CODE REVIEW

**Comment by larsoner** [comment]
Can you add a simple test? You can e.g. load or create from scratch an info, modify the `gantry_angle`, save it to disk (using `_TempDir`), load it, and verify it's properly loaded.

**Comment by cjayb** [comment]
Sure, will do

**Comment by agramfort** [comment]
does it get printed in the __repr__ ? if not it should. thx @cjayb

**Comment by larsoner** [comment]
> does it get printed in the repr ?

[It does automatically](https://github.com/mne-tools/mne-python/blob/master/mne/io/meas_info.py#L416)
```
gantry_angle : float | 0.1
```
I'll fix the merge conflict and merge (Travis failure is OSX), thanks @cjayb

**Pull request merged**
