### PR TITLE
MRG: Add links for parameters

### PR DESCRIPTION
**Pull request by larsoner**
WIP because it requires https://github.com/numpy/numpydoc/pull/197, thus the weird `pip` install for now for CircleCI. Want to make sure it works before getting the NumpyDoc PR merged.

### CODE REVIEW

**Comment by agramfort** [comment]
can you give a link to a rendered doc to understand what this brings?

**Comment by larsoner** [comment]
Look at these wonderful parameter lists

https://10865-1301584-gh.circle-artifacts.com/0/dev/generated/mne.viz.plot_topomap.html

**Comment by agramfort** [comment]
wunderbar !

**Comment by larsoner** [comment]
Since this touches a lot of files and fixes a bunch of docstring errors, I'd like to merge this one. The only downside is that there will be some cruft in the `conf.py` until the `numpydoc` PR gets merged. If it never does, we can just delete the `xref` stuff from `conf.py`.

**Comment by agramfort** [comment]
you have my blessing. But does it mean it will get harder for people to build the doc?
do we have now install something more?

**Comment by larsoner** [comment]
No. Eventually, once the `numpydoc` PR is merged, this will take effect for us. If someone has an old numpydoc, it will still build, just without the links.

**Comment by agramfort** [comment]
awesome !

>

**Pull request merged**
