### PR TITLE
MRG: Fix sign flip

### LINKED ISSUE #2997: Right singular vector in "label_sign_flip"
In line 1082-1085 of mne/label.py

1082:  _, _, Vh = linalg.svd(ori, full_matrices=False)
1083: 
1084: # Comparing to the direction of the first right singular vector
1085: flip = np.sign(np.dot(ori, Vh[:, 0] if len(vertno_sel) > 3 else Vh[0]))

If I am following correctly,  "ori" is a [n_dipoles, 3] vector.  According to "numpy.linalg.svd", the right singular vectors are the rows rather than columns of "Vh".  So should line 1085 be

flip = np.sign(np.dot(ori, Vh[0])) ?

Thanks.

### PR DESCRIPTION
**Pull request by Eric89GXL**
Ready for review/merge from my end.

Closes #2997.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
@natalieklein here's what I came up with

**Comment by Eric89GXL** [comment]
@agramfort I guess this code has been there since 2011

https://github.com/mne-tools/mne-python/commit/11ca75b38a22b7dfa2d48886401b61b2d2af6162

**Comment by dengemann** [comment]
@Eric89GXL ouch ... what was the consequence? Wrong sign?

**Comment by Eric89GXL** [comment]
Sometimes the sign flip vector was sub-optimal, yeah

**Comment by natalieklein** [comment]
Thanks!

**Comment by Eric89GXL** [comment]
@natalieklein thanks for helping isolate the bug and the proper fix

**Comment by natalieklein** [comment]
@YingYang actually found the problem :)

**Comment by Eric89GXL** [comment]
Ahh you're right -- thanks @YingYang!

**Comment by agramfort** [comment]
thanks guys

nice team work :)

sorry for my bug in 2011...

**Comment by natalieklein** [comment]
I mentioned this bug to a colleague, so he switched his MNE Python to the dev version to get the fixed code and reran some analysis he was doing, and it had a fairly large impact and he wanted me to share.

He extracted 333 cortical ROIs, computed an average resting-state time course using "mean_flip" (which calls label_sign_flip), then computed the correlations between ROI time courses. He took the raw values of the correlations before the bug fix (axis label "Uncorrected") and plotted them against the new values with the bug fix (axis label "Corrected"). This is one subject but others look similar. The point being that this change seems to have a large effect on some of the ROIs.

[MEG_CORRS_Corrected_vs_Uncorrected.pdf](https://github.com/mne-tools/mne-python/files/197756/MEG_CORRS_Corrected_vs_Uncorrected.pdf)

**Comment by Eric89GXL** [comment]
Since the + or - in the sign flips are arbitrarily determined by the SVD, it might be better to plot the absolute value of the correlation in both cases.

To further quantify the effect, you could take a histogram of the difference in absolute value of the original and corrected R values. It looks like there would (thankfully) be a big peak around 0, but still some hanging out toward the tail (near 0.9). But this can more or less be inferred from your plot already -- as you say, for some (probably small proportion) of ROIs it can matter.

I wonder how these differences would compare to, say, not doing the sign flip at all? I'd assume the "corrected vs uncorrected" would be more similar than "corrected vs no-flip". If someone gets bored they could try it, and we could compare the histograms of the differences in absolute value.

**Comment by natalieklein** [comment]
Yes, thank you for pointing that out. Here he plotted a histogram of abs(corr(uncorrected)) - abs(corr(corrected)). Maybe we can try to look at no flip as well.
meg_corrs_hist_abs diff

**Comment by Eric89GXL** [comment]
Nice -- good to know they're centered around zero and most (but not all!) are between -0.2 and 0.2. Thanks for all this info

**Pull request merged**
