### PR TITLE
MRG: Fix interpolation truncation

### LINKED ISSUE #4377: MEG Interpolation
Dear MNE-community,

I am currently trying to interpolate some bad MEG channels with MNE.
Unfortunately there seems to occur an exception, such that the resulting
channels hold only zeros. Even when I try to interpolate only one
channel I get from '_field_interpolation.py:80' the log
'Truncate at 0 missing 0.0001'
As I understand it, this happens because the eigenvalues are all too
small. My data contains of 248 channels measured at ~291000 time steps.

I am currently stuck there, with no idea remaining. Can you give me a
hint what else I could try to get at least some interpolation for my bad
channels?

As suggested, I attached a minimal example.

[interpol.zip](https://github.com/mne-tools/mne-python/files/1136430/interpol.zip)

Thanks in advance, Christoph

### PR DESCRIPTION
**Pull request by larsoner**
I'm not actually sure if we want to do +1 here (which means "missing less than 0.0001") or do `max(old_val, 1)`, which means "missing at least 0.0001 but keeping at least one component". The former seemed nicer to me but is a bit bigger of a change.

Closes #4377.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
Travis failure suggests that changing the criteria to "missing less than 0.0001" changes the mapping, so maybe we should use "missing at least 0.0001 but always keeping at least one component"...?

**Comment by Chrisinger** [comment]
In both your solutions, you are setting the index of the component to be taken.
Instead of adding 1, I would suggest to take the best component (the one with the highest value).
I do not know the details of truncation, but the parameter 0.0001 seems to be arbitrarily set - could it help to add this parameter to the interpolation function?

**Comment by Eric89GXL** [comment]
> In both your solutions, you are setting the index of the component to be used.

No, it is the index of the first component not to be used, i.e. `components[:limit]`. In other words, all components that precede this limit are used.

> the parameter 0.0001 seems to be arbitrarily set - could it help to add this parameter to the interpolation function?

The idea is that during the pseudoinverse step, if whitening has been done properly, such components are unlikely to be meaningful. We could add this as a parameter but I don't think it should really be necessary (YAGNI) if we choose either direction proposed above.

**Comment by Chrisinger** [comment]
Oh, sorry, then I misunderstood your code. But what does it tell me, when none of my 247 channels are meaningful when interpolation channel number 248? Maybe, my measurement is just too long with 290000 time steps?
I do not see, why the same issue appear in the short example of few seconds.
If you chose between your two solutions, i suggest taking max(old_val, 1) instead of always adding 1 - especially because it is not clear, that there always are k+1 channels available.

**Comment by Eric89GXL** [comment]
> But what does it tell me, when none of my 247 channels are meaningful
when interpolation channel number 248? Maybe, my measurement is just too
long with 290000 time steps?

That's not quite what it implies. It's that one component (loosely
speaking) accounts for 99.99% of the variance. This isn't so surprising
given the extremely limited number of channels in the example, which IIRC
was 4 (on mobile so can't easily cross check). Do you also see this when
using all channels? If so can you share those data, too? You can crop to a
short time window (e.g., 1 second).

But this also makes me realize we should include and not use max --
thinking of the case where the first two components each account for
49.999% of the variance (and the remaining N-2 components are noise) you'd
want to include two components, not just one.

I do not see, why the same issue appear in the short example of few seconds.

This operation is purely spatial, so the number of time points doesn't
matter.

If you chose between your two solutions, i suggest taking max(old_val, 1)
instead of always adding 1 - especially because it is not clear, that there
always are k+1 channels available.

I think this won't be an issue given how these variables and conditionals
are constructed, but I'll keep this in mind.

**Comment by Eric89GXL** [comment]
Okay in the course of correcting the tests I became convinced the +1 is the correct way -- the EEG map (which used 6 electrodes w/avg ref) had cumulative normalized singular values:
```
[ 0.53143108  0.76656957  0.91056205  0.96350951  1.          1.        ]
```
Clearly in this instance you'd want to keep 5 components, otherwise you're off by ~4% (~0.04). Previously we were only keeping 4.

Ready for review/merge from my end.

**Comment by Chrisinger** [comment]
Thank you very much. 
This works fine at the test set. I will test the implementation on my real data and let you know if it also works.

**Comment by larsoner** [comment]
@agramfort don't forget this one while you're poking around :)

**Comment by agramfort** [comment]
merge when green. Thx @larsoner

**Comment by Chrisinger** [comment]
Just checked it with my data. It works! :) Thanks again!

**Pull request merged**
