### PR TITLE
[MRG??][ENH] Change pre-Unix-zero-time to time stamp minutes, not seconds

### PR DESCRIPTION
**Pull request by alexrockhill**
Here is my idea to fix https://github.com/bids-standard/bids-specification/issues/360, https://github.com/mne-tools/mne-python/pull/7016 and https://github.com/mne-tools/mne-bids/pull/280 until 2038: Any timestamp from before Unix time 0 (1970 Jan 1) will be interpreted as representing minutes instead of seconds back from Unix time 0.

The pros of this change will be that dates can be represented well before 1900 with minute-level resolution so you don't lose features like when in the day the scan was collected that are most often thrown away but for experimental debugging in my personal experience can be quite useful (there's a long story I told @jasmainak about NPR being picked up in our EEG until we put a Faraday cage up which would be depended on when they were on or off air). Existing and new data will be completely unaffected so long as their dates are before Unix time zero (we could move the date backward as well, < unix 0 is just the most parsimonious). Most importantly, dates will easily be able to go back far enough for BIDS specs (to the year -2114 Unix time).

The major con is that EEG data from before 1970 would be interpreted incorrectly. As stated previously, if data this old exists and wants to be read into MNE, we could move the convert to minutes date back to 1925. As maybe should be obvious, this won't cause any necessary changes in FIF or recording equipment as it is well past 1970 and therefore any timestamp generated now would be unaffected.

### CODE REVIEW

**Comment by jasmainak** [comment]
I think this is making things a bit too complicated than it needs to be. It will be burden on future contributors. We have made special provisions in `meas_date` in the past but I would say YAGNI in this case. Maybe @larsoner or @agramfort can weigh in if you need second opinion.

**Comment by larsoner** [comment]
I agree it makes things a bit complicated. It's a potential solution but I'd rather prefer some of the others that have been discussed first

**Comment by agramfort** [comment]
to me this is not the right fix

**Comment by alexrockhill** [comment]
No problem, just a suggestion. Any ideas about what to do about datasets spanning more than 24 years? Or is that not an issue that is likely to come up?

**Comment by agramfort** [comment]
unlikely to happen

>

**Pull request closed without merging**
