### PR TITLE
MRG, DOC: update tutorial: epochs to pandas DataFrame

### PR DESCRIPTION
**Pull request by drammock**
~~WIP;~~ requires #7206

### CODE REVIEW

**Comment by drammock** [comment]
@larsoner @rob-luke I'm seeing a Travis failure here for nirx / `scalp_coupling_index` on a PR that only changes tutorials / docs. 

@agramfort @dengemann since Travis fail is unrelated, this should be ready for review.

**Comment by drammock** [comment]
Here's the rendered tutorial link: https://17982-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/epochs/plot_40_epochs_to_data_frame.html#sphx-glr-auto-tutorials-epochs-plot-40-epochs-to-data-frame-py

**Comment by rob-luke** [comment]
Yep that's due to a bad test that I added. I thought this might happen and listed the issue here...  

https://github.com/mne-tools/mne-python/blob/master/mne/preprocessing/tests/test_scalp_coupling_index.py#L53

I will remove this test in another PR.

**Comment by agramfort** [comment]
looks great https://17982-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/epochs/plot_40_epochs_to_data_frame.html#sphx-glr-auto-tutorials-epochs-plot-40-epochs-to-data-frame-py

**Comment by larsoner** [comment]
This will fix one of the three failures in `master`, can you see if you can add fixes for the other two here, too?

https://circleci.com/gh/mne-tools/mne-python/17989

**Comment by drammock** [comment]
@larsoner The tutorial build issues are fixed.  [The Azure failures for full-pip](https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=5520&view=logs&j=20ec0733-a031-5a42-425a-ca7f9f76ad75&t=907150ea-d0b2-5422-b4c8-a9ac9452f813&l=170) are all about `TraitTuple` deprecation, which is being dealt with in #7322.  Just waiting on Travis.

**Comment by larsoner** [comment]
I'll get this in to hopefully get back to green, thanks @drammock

**Pull request merged**
