### PR TITLE
FIX: Allow one-sample epochs

### LINKED ISSUE #2434: EpochsArray constructor is broken if len(times) == 1
This is useful for EEG/MEG measures which reduce the time dimension in each trial. It used to work with the last release. Tried to find a fix but it seems to be deeper than I assumed.

cc @Eric89GXL @agramfort

### PR DESCRIPTION
**Pull request by Eric89GXL**
cc @dengemann

Closes #2435
Closes #2434

~~Can you make a minimal example for the other error you were getting having to do with `event_id` being an integer?~~

### CODE REVIEW

**Comment by Eric89GXL** [comment]
BTW @fraimondo sorry I took this over, I didn't realize you had pushed to @dengemann's PR almost the same fixes until after I had already made this. I think this solution should work a little bit better, see if you agree.

**Comment by fraimondo** [comment]
Same fix for single times, fix for that ugly event_id thing, better test... I think this is the one to use!

**Comment by dengemann** [comment]
@Eric89GXL looks clean. @fraimondo are we ok with this?

**Comment by fraimondo** [comment]
I’m happy

**Comment by dengemann** [comment]
Thanks @Eric89GXL @fraimondo -- nice team play. Next time let's coordinate better and use 1 branch.

**Pull request merged**
