### PR TITLE
ENH: Allow printing of valid keys

### LINKED ISSUE #2817: Is there a list of mne config options?
`mne.set_config()` or `get_config` doesn't tell you what the possible keys are. I know you can set CUDA there and some file dirs, but is there an overview somewhere?

### PR DESCRIPTION
**Pull request by Eric89GXL**
Closes #2817.

### CODE REVIEW

**Comment by agramfort** [comment]
Lgtm

**Comment by dengemann** [comment]
Yep.

**Comment by Eric89GXL** [comment]
Cool, will merge once the CIs are happy

**Comment by jona-sassenhagen** [comment]
Thanks Eric!

**Pull request merged**
