### PR TITLE
MRG, ENH: Speed up NIRx read without preload

### LINKED ISSUE #7744: Writing NIRS files to FIF is surprisingly slow
#### Describe the bug

I am reading NIRX NIRS files and writing them to fif files. This process takes longer than I expected.

It may be that this is how long writing takes. But I want to make sure there is nothing wrong with how we have written the `read_raw_nirx` function that is causing a slowdown.

Or perhaps fif is not the correct format I should be using? I selected fif as I know that it should work as its being tested [here](https://github.com/mne-tools/mne-python/blob/d0dc8f3d51cfd0db8bcec8f1adee98050152d2df/mne/io/tests/test_raw.py#L129) (called [here](https://github.com/mne-tools/mne-python/blob/master/mne/io/nirx/tests/test_nirx.py#L231)).

#### Steps to reproduce
```python
import os
import time
import mne

fnirs_data_folder = mne.datasets.fnirs_motor.data_path()
fnirs_raw_dir = os.path.join(fnirs_data_folder, 'Participant-1')
raw_intensity = mne.io.read_raw_nirx(fnirs_raw_dir, verbose=True, preload=False)

t = time.time()
raw_intensity.save("test_raw.fif")
print(time.time() - t)
```

On my PC this takes almost 2 minutes.

#### Expected results

I don't have an exact time I would expect this to take, but two minutes to process a 5 MB file seemed slow.

#### Actual results

About 2 mins.

#### Additional information
```
Platform:      Darwin-19.3.0-x86_64-i386-64bit
Python:        3.7.3 (default, Dec 13 2019, 19:58:14)  [Clang 11.0.0 (clang-1100.0.33.17)]
Executable:    /Library/Developer/CommandLineTools/usr/bin/python3
CPU:           i386: 16 cores
Memory:        32.0 GB
mne:           0.21.dev0
numpy:         1.18.2 {blas=openblas, lapack=openblas}
scipy:         1.4.1
matplotlib:    3.2.1 {backend=module://backend_interagg}
sklearn:       0.22.2.post1
numba:         0.48.0
nibabel:       3.0.2
cupy:          Not found
pandas:        1.0.3
dipy:          1.1.1
mayavi:        4.7.1
pyvista:       0.24.1
vtk:           8.1.2
PyQt5:         5.14.1
```

### PR DESCRIPTION
**Pull request by larsoner**
Closes #7744

@rob-luke this code only takes 1 sec now, no idea how long it takes on `master` because I lost patience waiting after 30 seconds or so:
```Python
import time
import mne
fnirs_data_folder = mne.datasets.fnirs_motor.data_path()
fnirs_raw_dir = fnirs_data_folder + '/Participant-1'
raw = mne.io.read_raw_nirx(fnirs_raw_dir)
t0 = time.time()
raw.save('/dev/null', verbose='error')
print(time.time() - t0)
```

### CODE REVIEW

**Comment by kylemath** [comment]
This change is helpful for us and we will add to our import function too (our data files for different blocks sometimes have different sized headers)

**Comment by rob-luke** [comment]
Thanks @larsoner, I appreciate you fixing this.

**Comment by larsoner** [comment]
Okay, in it goes, thanks for looking @kylemath @rob-luke . In the future feel free to click the green "Review changes" in the upper right of the files-changed page and "Approve" or add some comments and "Request changes" etc., too, if you want. It's always good to get extra eyes (and know that there have been extra eyes) on any code changes...

**Comment by rob-luke** [comment]
> feel free to click the green "Review changes" in the upper right

Thanks, will do in the future.

**Pull request merged**
