### PR TITLE
FIX: Add numbers for dipoles

### PR DESCRIPTION
**Pull request by larsoner**
Takeover of #4431.

Ready for review/merge from my end.

### CODE REVIEW

**Comment by larsoner** [comment]
No, in ICA the numbering now starts from 0 for the channel names

Updated example

https://5853-1301584-gh.circle-artifacts.com/0/tmp/circle-artifacts.klQas8D/html/auto_examples/inverse/plot_mixed_norm_inverse.html

**Comment by dengemann** [comment]
Dipole 51? ... I think a bracket is missing in the code :)

**Comment by larsoner** [comment]
I'm not sure what you mean, can you clarify what you want changed?

I modified @agramfort's suggestion of doing `Dipole 1 / 7` slightly [to be](https://5853-1301584-gh.circle-artifacts.com/0/tmp/circle-artifacts.klQas8D/html/auto_examples/inverse/plot_mixed_norm_inverse.html) `Dipole #1 / 7` style, in this case it's 51 ([index 50](https://mne-tools.github.io/dev/auto_examples/inverse/plot_mixed_norm_inverse.html#sphx-glr-auto-examples-inverse-plot-mixed-norm-inverse-py)).

**Comment by dengemann** [comment]
Wasn't it 6 before? Did the example change?

**Comment by larsoner** [comment]
I have links in my last comment that are before/after this PR. If it changed 6->50 it's not from this PR so let's discuss separately -- any changes you want here?

**Comment by dengemann** [comment]
Ok so if it is 50 on master these changes are ok.

**Comment by agramfort** [comment]
thx @larsoner

**Pull request merged**
