### PR TITLE
SourceMorph (GSoC 2018 - The End)

### PR DESCRIPTION
**Pull request by TommyClausner**
# Summary GSoC 2018 with MNE-Python

This pull request contains all the work done related to [this](https://summerofcode.withgoogle.com/projects/#5999365848563712) project.

### What we wanted

The goal of my this year's GSoC project, was to "implementing necessary tools for group level analyses based on volumetric data". More detailed, a functionality for volumetric morphing, as well the creation of pseudo MRIs was targeted.

### What we achieved

The respective functionality was implemented in form of a new class ``SourceMorph`` that was added to the MNE ecosystem. This class is able to perform the requested operation on volumetric morphing. The resulting API to perform a volumetric morph looks like this:

```
# setup a new instance of SourceMorph
morpher = mne.SourceMorph(subject_from='Marry', subject_to='Ben', 
                          subjects_dir='~/subjects', src=src)

# morph Marry's data into Ben's brain space
stc_ben = morpher(stc_marry)
```

### What we didn't achieved
The sub-target of creating pseudo-individual MRI volumes was dropped in favor of a major API change to MNE's pre-existing morphing functionality for surfaces. Furthermore there was no time left to reach the bonus goal of engaging in plotting

### What we however achieved in return
``SourceMorph`` is not only able to morph volumetric data, but also surface based data. To achieve this, existing functions were integrated into the class functionality, such that the user does not experience any difference in the usage no matter if surface or volume based data was provided.

Well, of course the user experiences *any* difference, due to the fact that both methods (volume vs. surface) require different parameter settings. In essence however ``SourceMorph`` can be applied with it's default paramters in the exact same fashion:

```
morpher = mne.SourceMorph(src=src)
```

This is due to the fact, that by default ``subject_to='fsaverage'`` and ``subject_from`` can be inferred from ``src`` - the source space. Since MNE works with [FreeSurfer](https://surfer.nmr.mgh.harvard.edu/), either the respective volumetric MRI representation or the reconstructed surface - stored in ``subjects_dir`` that is set in the environment - will be used to compute the morph.

Another nice little detail about ``SourceMorph`` is that it can output source estimate data as volumetric data in NIfTI format.

```
# direct morph to volume
morpher = mne.SourceMorph(src=src)
nifti_fsaverage = morpher(stc_marry, as_volume=True)

# staged output
morpher = mne.SourceMorph(src=src)
stc_fsaverage = morpher(stc_ben)
nifti_fsaverage = morpher.as_volume(stc_fsaverage)
```

Furthermore ``SourceMorph`` can be stored...
```
morpher.save('Marrys_morph_to_fsaverage.h5')
```
... and read from disk.
```
morpher = mne.read_source_morph('Marrys_morph_to_fsaverage.h5')
```

Therefore the function ``read_source_morph`` was added as well.

### Integration with previous API
Beside adding the new functionality, previous functions were deprecated and wrappers were used for the deprecation cycle. All related existing examples / tutorials / tests / functions that made use of previous morphing API were adjusted.

The user will from now on receive a deprecation warning on attempting to use old functionality and will be guided towards the new.

### Examples and Tutorials
To explain the new functionality as good as possible and make the change for the user smoothly, 2 examples and 3 tutorials were added:

- an example demonstrating the functionality with [volumes](https://9010-1301584-gh.circle-artifacts.com/0/html/auto_examples/inverse/plot_morph_volume_stc.html)
- an example demonstrating the functionality with [surfaces](https://9010-1301584-gh.circle-artifacts.com/0/html/auto_examples/inverse/plot_morph_surface_stc.html)
- a tutorial explaining [morphing](https://9010-1301584-gh.circle-artifacts.com/0/html/auto_tutorials/plot_morph_stc.html) more generally
- a tutorial explaining [source estimation](https://9010-1301584-gh.circle-artifacts.com/0/html/auto_tutorials/plot_object_source_estimate.html) objects
- a tutorial explaining [FreeSurfer](https://9010-1301584-gh.circle-artifacts.com/0/html/auto_tutorials/plot_background_freesurfer.html) integration with MNE

### Why merged into here and not the master branch?
Restructuring the whole morphing API of the entire MNE ecosystem required not only to change a lot of files and dig through the deepness of the software package; but also would be ideally such, that the new API is entirely designed to function in a reasonable way.

Since it was not fully clear yet, if and why and why not some major API aspects are finally desirable, we agreed upon to merge the files into this branch.

This way a refinement - necessary for such a major API change - can be done without the pressure of a deadline just waiting to be missed ;)

### Conclusion
We achieved our major goal of implementing the required morphing functionality. Missed goals (MRI creator and plotting functionality) were replaced by creating a coherent API for the entire source estimate morph functionality in MNE. To my opinion that's a very good trade and I think the new class - even as implemented "as is" at the moment - will add a major benefit.

Furthermore committed files pass all continuous integration checks and thus the new class would theoretically be ready to use :)

### CODE REVIEW

**Comment by larsoner** [comment]
The commit history here is weird, it includes changes having to do with COLORS

**Comment by TommyClausner** [comment]
Hey @larsoner I guess with a little bit of luck, this could have been the last commit...

Would you mind merging it latest at ~ 16:00 so that I have some time left (2h), to adjust the description of the PR, that the links actually link to the built examples / tutorials and not just the artifacts(?) - and also I don't want to submit the final thingy last minute, because even though it's Google's servers, you never know ;)

**Comment by larsoner** [comment]
It looks like the problem is that you have a commit at the top which is from a different PR. One option is to fix this by cherry-picking your commits (leaving out the beamformer one), which you can see the results of [here](https://github.com/mne-tools/mne-python/compare/master...larsoner:sourcemorph?expand=1). Okay with you if I force push that branch here? You'll need to check the "allow edits from maintainers" box or add me as a collaborator on your fork.

And yes we should merge ASAP and definitely today. 16:00 what time zone?

**Comment by TommyClausner** [comment]
Guess the conflict was from having two weird commits that were excluding each other... have no idea how this happened and it took me a while to figure out and later I went the lazy way, rebased and replaced the files (which had to lead to confusion of course, because I didn't spot all differences in the first place)... anyway:

I'm ready to merge, the box is ticked and the tests are passed :)

16:00 CEST btw (in 45min)

**Comment by TommyClausner** [comment]
(or do you insist on new PR?)

**Comment by larsoner** [comment]
We can fix it later with `push --force`. Thanks @TommyClausner !

**Comment by TommyClausner** [comment]
Hey thanks a lot in return !!

**Pull request merged**
