### PR TITLE
ENH: add figure title to morphed MxNE in example

### PR DESCRIPTION
**Pull request by adykstra**

### CODE REVIEW

**Comment by Eric89GXL** [comment]
LGTM. I killed all CIs except the [relevant](https://travis-ci.org/mne-tools/mne-python/jobs/242862470) [ones](https://4782-1301584-gh.circle-artifacts.com/0/tmp/circle-artifacts.ovUTLrE/html/auto_examples/inverse/plot_mixed_norm_inverse.html).

If you feel like making one more change, it's probably better to separate the original-subject and morphed-subject plots into to different sphinx-gallery sections so that the plots are grouped more clearly.

**Comment by agramfort** [comment]
@adykstra long time no see :) Glad to have you back !

are you done here? if so +1 for merge

**Comment by adykstra** [comment]
@Eric89GXL , where/how is that specified?

**Comment by Eric89GXL** [comment]
You'd just need to create a new section like
```
###############################################################################
 # View on a destination subject using morphing
```

**Comment by Eric89GXL** [comment]
... and put the plot commands after that heading

**Comment by adykstra** [comment]
Need the

`###############################################################################` 
`#comment` 

be immediately prior to the plotting function? Or can it also be placed before the actual morphing?

**Comment by Eric89GXL** [comment]
It can be before the morphing. The `####` separate sections (where plots are grouped).

**Comment by Eric89GXL** [comment]
Much better :)

https://4783-1301584-gh.circle-artifacts.com/0/tmp/circle-artifacts.cipiYTp/html/auto_examples/inverse/plot_mixed_norm_inverse.html

**Comment by Eric89GXL** [comment]
Ready to go from your end @adykstra ?

**Comment by adykstra** [comment]
Yep.

**Comment by Eric89GXL** [comment]
Thanks @adykstra

**Pull request merged**
