### PR TITLE
[MRG] ENH Ref

### PR DESCRIPTION
**Pull request by teonlamont**
Add functions to the reference

### CODE REVIEW

**Comment by Eric89GXL** [comment]
LGTM, did you check to see if they render properly when building doc? You can do it with `make html_dev-noplot` to do it quickly.

**Comment by teonlamont** [comment]
yay, docs finally build for me and not break.

problem: the docs doesn't fully build the API Reference, is that supposed to happen?
also, `linear_regression_raw` isn't imported with the stats module, I'm guessing this is an oversight?

**Comment by Eric89GXL** [comment]
How do you mean it's not completely built? It looks complete to me.

That last part sounds like an oversight.

**Comment by Eric89GXL** [comment]
I just built your branch and everything looks okay over here...

**Comment by teonlamont** [comment]
modulo the css, etc. here's how the `python_reference.html`, which is sparse compared to the website's version: https://www.dropbox.com/s/2zd9dsdb8haj7d7/python_reference.html?dl=0

**Comment by Eric89GXL** [comment]
I don't have that problem, my build looks like the website, e.g. the `minimum_norm` section is appropriately populated. I wonder if you have some out-of-date package.

**Comment by Eric89GXL** [comment]
It might be worth posting the version numbers of various packages like `sphinx`, `sphinx-gallery`, etc. as well as (you) looking at your doc-building logs for abnormalities

**Pull request merged**
