### PR TITLE
MRG: In Report, allow to add multiple figure or image elements to the same content block ("section")

### PR DESCRIPTION
**Pull request by hoechenberger**
This allows for the following:

```python
# %%
import matplotlib.pyplot as plt
import mne


r = mne.Report(title='Test')

captions = ['Cap 1', 'Cap 2']
titles = ['Title 1', 'Title 2']
tags = ['tag1', 'tag2']

for title, caption, tag in zip(titles, captions, tags):
    fig, ax = plt.subplots()
    ax.plot([1, 2, 3])
    r.add_figure(fig=fig, title=title, caption=caption,
                 section='Common Section', tags=tag)

r.save('/tmp/test.html', overwrite=True)
```

Which then produces:

Screen Shot 2022-06-01 at 15 14 15

Each figure can now be individually collapsed. Previously, such "grouping" was only possible by means of a slider, which would sometimes make it hard to discover content.

The "parent" section inherits all tags of its children.

This is also a serious refactoring, as you can see by looking at the number of changed lines … The idea was to avoid having to pass around DOM IDs and rendered HTML content so much. Previously, the `_render_*()` methods would return HTML content, and the calling method would then have to add the content to the report. Now, most `_render_*()` methods have been renamed to `_add_*()`, and add the content themselves. This reduces flexibility a bit, but we never made use of it anyway. The only exception is BEM rendering, where we need to group 2 sliders in a row. For this reason, `_render_slider()` remains.

This code lays a foundation for eventually allowing us to add a `section` kwarg to **all** `add_*()` methods, should we wish to do so.

I've also taken the opportunity to make use of inheritance in our Jinja templates, and get rid of a few we don't need anymore.

### CODE REVIEW

**Comment by hoechenberger** [comment]
Rendered tutorial looks good:
https://output.circle-artifacts.com/output/job/b4a85fd7-6e60-4b0f-a3b1-9241ae45e9ef/artifacts/0/dev/auto_tutorials/intro/70_report.html#sphx-glr-auto-tutorials-intro-70-report-py

Here's a demo of the new feature:
https://output.circle-artifacts.com/output/job/b4a85fd7-6e60-4b0f-a3b1-9241ae45e9ef/artifacts/0/dev/auto_tutorials/intro/70_report.html#adding-custom-figures

**Review by agramfort — APPROVED** [review]
rendered output looks great !

and you deleted more lines than you added 👏

**Comment by hoechenberger** [comment]
> and you deleted more lines than you added 👏

Aaaand many of the added lines are just because I've decided to spread out method parameters across lines (one per line), otherwise the diff would've been even more in favor of removal ;)

**Comment by hoechenberger** [comment]
Since this one doesn't really change behavior, and is mostly a refactoring plus a small feature addition, I'm going a head with merging now

**Comment by agramfort** [comment]
🙏 👏 @hoechenberger

**Pull request merged**
