### PR TITLE
ENH/API: find evoked peak

### LINKED ISSUE #979: ENH/API: peak detection
I was thinking about a peak detection API for evokeds / single trials / stcs.

where you could basically, conveniently do sth. like:

`vertex, latency = stc.find_peak(tmin=0.09, tmax=0.14)`

or 

`channel, latency = evoked.find_peak(tmin=0.09, tmax=0.14)`

Any thoughts, praise, objections?

### PR DESCRIPTION
**Pull request by dengemann**
Addresses and closes #979.

### CODE REVIEW

**Comment by mainakjas** [comment]
I'm just wondering how the peak detection is done here. Is it a simple `np.max`? Maybe we should switch to something more sophisticated like this: http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.signal.find_peaks_cwt.html ?

**Comment by dengemann** [comment]
> I'm just wondering how the peak detection is done here. Is it a simple np.max? 

yes

>  more sophisticated like this: http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.signal.find_peaks_cwt.html ?

+1

**Comment by agramfort** [comment]
why not but first please test on data how well it works out of the box

**Comment by dengemann** [comment]
The question is in particular whether it outperforms what we have if SNR is
low, e.g. single trial data or only few trials of data.

2015-03-26 21:34 GMT+01:00 Alexandre Gramfort <notifications@github.com>:

**Comment by Anevar** [comment]
It could be interesting if both valleys and peak detection are possible like in this one: 
http://demotu.github.io/posts/detect-peaks-in-data.html

**Pull request merged**
