### PR TITLE
WIP _validate_type(info, "info")

### PR DESCRIPTION
**Pull request by jona-sassenhagen**
see #5259

### CODE REVIEW

**Comment by agramfort** [comment]
@larsoner shall we merge with red travis?

**Comment by larsoner** [comment]
Yes as long as the failure is on one run with `test_cov.py` timeout

**Comment by jona-sassenhagen** [comment]
It is.

I just restarted the test.

**Comment by larsoner** [comment]
Thanks @jona-sassenhagen

**Pull request merged**
