### PR TITLE
Warn on missing header in BrainVision files

### LINKED ISSUE #9999: can't read new brainvision markers?
When reading a brainvision file (available [here](https://osf.io/5qbr3/?show=revision), after extracting 
- `EEG_data/EEG_excluded.zip/vic0001.vhdr` 
- `EEG_data/hdr_mrk_files/vic0001.vmrk` 
- `EEG_data/hdr_mrk_files/vic0001.vhdr`
)

The following command
```python
raw = mne.io.read_raw_brainvision('vic0001.vhdr')
```

leads to
```
ValueError: MNE-Python currently only supports marker versions 1.0 and 2.0, got unparsable '[Marker Infos]'. 
Contact MNE-Python developers for support.
```

I am thus contacting MNE-Python developers for support :]

### PR DESCRIPTION
**Pull request by cbrnr**
Fixes #9999.

### CODE REVIEW

**Review by hoechenberger — APPROVED** [review]

**Comment by hoechenberger** [comment]
LGTM

**Review by sappelhoff — APPROVED** [review]
LGTM :-)

**Comment by cbrnr** [comment]
All green on my first try!

**Comment by hoechenberger** [comment]
> All green on my first try!

Amazing! 🥇

**Pull request merged**
