### PR TITLE
MAINT: Refactor for mne-qt-browser

### PR DESCRIPTION
**Pull request by larsoner**
Along with https://github.com/mne-tools/mne-qt-browser/pull/66, before:

Screen Shot 2022-03-04 at 2 00 45 PM

After:

Screen Shot 2022-03-04 at 2 01 00 PM

### CODE REVIEW

**Comment by larsoner** [comment]
@agramfort @hoechenberger @GuillaumeFavelier feel free to have a quick look, if we merge this and https://github.com/mne-tools/mne-qt-browser/pull/66 we can get `qdarkstyle` support for mne-qt-browser easily I think

**Comment by hoechenberger** [comment]
@larsoner Probably okay for Linux and Windows, but doesn't look "native" at all on the Mac. There, Qt has built-in dark mode support for many widgets; however, this seems to be overridden by `mne-qt-browser` somehow:
Screen Shot 2022-03-05 at 18 30 28

What I'm saying is:
Yes, the change you propose makes things slightly better, but is nothing we'd want to keep in the long term for macOS. 

Similar issue with `Brain`.

Positive example, except for the status bar: `CoregistrationUI`
Screen Shot 2022-03-05 at 18 33 25

This is how it's supposed to look.

Our `qdarkstyle` themes look like an awful paint job 😅

But like I said, it's already making things slightly better, so why not.

**Comment by larsoner** [comment]
> @larsoner Probably okay for Linux and Windows, but doesn't look "native" at all on the Mac. There, Qt has built-in dark mode support for many widgets; however, this seems to be overridden by mne-qt-browser somehow for status- and toolbar. So this is a screenshot I took with my system in Dark Mode, and without using your branch:


Are you sure you're on this branch of MNE-Python *and* this branch of mne-qt-browser? https://github.com/mne-tools/mne-qt-browser/pull/66

To me what you have is what mine looked like without https://github.com/mne-tools/mne-qt-browser/pull/66

**Comment by larsoner** [comment]
... in any case, for mne-qt-browser to look any different, this PR does nothing. It just makes https://github.com/mne-tools/mne-qt-browser/pull/66 (which changes the mne-qt-browser behavior) easier/cleaner. So I'll go ahead and merge this.

BTW, this just makes mne-qt-browser behave like Brain. I think we should make `mne coreg` behave like Brain, as well. Then, if there are problems with that, we should address them ideally in `qdarkstyle` or, if not, then with some custom stylesheet here in MNE-Python.

**Comment by hoechenberger** [comment]
@larsoner Agreed! Thanks for the work!

**Comment by GuillaumeFavelier** [comment]
> I think we should make mne coreg behave like Brain

I updated #8833 with:

> - [ ] add support for (qdarkstyle) dark theme

**Pull request merged**
