### PR TITLE
ENH: (WIP) MVAR connectivity and example

### PR DESCRIPTION
**Pull request by kazemakase**

### CODE REVIEW

**Comment by Eric89GXL** [comment]
@kazemakase this one is over a year old now, do you plan to come back to it? If not we can close it and resurrect it if someone is interested.

**Comment by Eric89GXL** [comment]
Closing due to non-response, but feel free to reopen if you find time to work on it.

**Comment by kazemakase** [comment]
Sorry for not responding. I've been on vacation during the last weeks.

Let's resurrect this if someone becomes interested. Meanwhile we work on improving scot :)

**Comment by kingjr** [comment]
Where are we on this? It'd be great to have it merged at some point :)

**Comment by agramfort** [comment]
I/we never took the time to poperly review.

to make this happen fast -> mne-sandbox?

**Comment by mbillingr** [comment]
I guess by now the PR is quite behind the current master...

**Comment by kingjr** [comment]
> to make this happen fast -> mne-sandbox?

+1; I'm happy to help review, I'm trying to understand the implementation of "effective" connectivity measures.

> I guess by now the PR is quite behind the current master... Also, scot has progressed in the meanwhile.

I guess yes. Do you think there's still a chance to integrate the two libraries in the near future?

**Comment by mbillingr** [comment]
> I guess yes. Do you think there's still a chance to integrate the two libraries in the near future?

I tried to rebase the PR to current master but there is a problem with `viz.py` where I added some functions. Apparently it was removed and there is a new `viz` subpackage. Can someone explain how the new visualization stuff is organized so I can adapt the code?

Once the rebase was successful we could consider to update to the current version of scot, where we recently changed the data orientation to match that of MNE. This should allow us to get rid of some glue code.

If this works smoothly I see a good chance to do that in the near future, although I currently have a busy time changing jobs :)

**Comment by agramfort** [comment]
>
> I tried to rebase the PR to current master but there is a problem with
> viz.py where I added some functions. Apparently it was removed and there
> is a new viz subpackage. Can someone explain how the new visualization
> stuff is organized so I can adapt the code?
>
put it in a new file if you don't need to reuse a lot of code from an
existing viz file.


> Once the rebase was successful we could consider to update to the current
> version of scot, where we recently changed the data orientation to match
> that of MNE. This should allow us to get rid of some glue code.
>
> If this works smoothly I see a good chance to do that in the near future,
> although I currently have a busy time changing jobs :)
>

going where?

**Comment by mbillingr** [comment]
Ok, I think I'll be able to pull that rebase off in the next view days.

> going where?

Back to Austria, joining a hearing implant company in Innsbruck.

**Comment by mbillingr** [comment]
Hey, this worked remarkably well! Everything is still working on top of the current master.

It seems that this PR is no longer updated because it is closed.
Do you want me to create a new PR or is it possible to reopen this one?
(Note that I squashed all 46 commits to make rebasing easier.)

**Comment by Eric89GXL** [comment]
It looks like you'll need to reopen -- force-push makes it impossible to reopen a PR on the GitHub interface (but it is fine to force push on an already-open PR), not sure why.

**Comment by Eric89GXL** [comment]
Oh actually, please open the PR into mne-sandbox instead of mne-python

**Comment by Eric89GXL** [comment]
https://github.com/mne-tools/mne-sandbox

It's where we're going to put code for people to use until we settle on API, use cases, best practices, etc.

**Comment by mbillingr** [comment]
That sounds practical :)

Btw, is it possible to rebase without force pushing (unless it's a fast-forward)?

**Comment by mbillingr** [comment]
Uhm, how do I actually create a PR from a mne-tools fork into mne-sandbox?

**Comment by Eric89GXL** [comment]
You can't -- you'll need to fork and clone the `mne-sandbox` repo and make your changes there. Hopefully it's only to a single file, which would make it easy...?

**Comment by Eric89GXL** [comment]
And no, you have to force push after rebase because it rewrites history

**Comment by mbillingr** [comment]
Nah, it's a whole bunch of files, which makes it not so easy... but it's doable.

There are also a few changes to existing MNE files that do not exist in mne-sandbox. How do I deal with that?

**Comment by Eric89GXL** [comment]
If you e.g. made some functions take optional arguments or did refactoring, you have two choices I think:

1. Make the changes in mne-python, with appropriate unit tests for any new parameters. This should only really be done if those changes make things more general or usable in a way that would help even if MVAR (in principle) would never land in mne-python.

2. Make a local copy of the modified mne-python functions in your new file in mne-sandbox. For example, if you needed to change how `pick_info` worked, you'd make a copy of it in `mne-sandbox/mne_sandbox/connectivity/mvar.py` (new file you've made with your code added to it) and modify it there.

Make sense?

**Comment by mbillingr** [comment]
Ok, I think I'll go for option 2 now.
Thanks for the help!

**Comment by Eric89GXL** [comment]
No problem -- looking forward to the PR

**Pull request closed without merging**
