### PR TITLE
[MRG] Fix add_bem_to_section

### PR DESCRIPTION
**Pull request by teonlamont**
Because of the comment addition, the add_bem_to_section was silently
broken

### CODE REVIEW

**Comment by teonlamont** [comment]
I don't know how backporting works, but this seems appropriate

**Comment by mainakjas** [comment]
can you add a test?

**Comment by teonlamont** [comment]
I don't know what the test would be. It was because three arguments were returned but only two variable names were given

**Comment by agramfort** [comment]
done with backport

thx @teonlamont

**Comment by mainakjas** [comment]
@teonlamont for the backport you need to push / make a pr to the maint/0.9 branch: https://github.com/mne-tools/mne-python/tree/maint/0.9

**Pull request merged**
