### PR TITLE
Drop channel selection from LCMV example

### PR DESCRIPTION
**Pull request by britta-wstnr**
see https://github.com/mne-tools/mne-python/issues/4875

I dropped the channel selection and used the data from both left and right auditory stimulation.
Source space activity is plotted based on peak latency in the sensor level data.

cc @kingjr @agramfort @dengemann and @sarangnemo

### CODE REVIEW

**Comment by larsoner** [comment]
Output looks fine:

https://6811-1301584-gh.circle-artifacts.com/0/tmp/circle-artifacts.JaQpa1T/html/auto_examples/inverse/plot_lcmv_beamformer_volume.html

But @britta-wstnr would you be up for:

1. separating some sections with full-line `#######################` separators so that plots come up in different sections. See for example how it's done [here](https://mne-tools.github.io/dev/auto_tutorials/plot_background_statistics.html).

2. adding `# sphinx_gallery_thumbnail_number = 3` to make the fourth image the one that gets shown on the [example page](https://6811-1301584-gh.circle-artifacts.com/0/tmp/circle-artifacts.JaQpa1T/html/auto_examples/index.html#inverse-problem-and-source-analysis)

**Comment by sarangnemo** [comment]
Beautiful bilateral beamformer result! ;-)

**Comment by britta-wstnr** [comment]
@larsoner Done, also added some one-line descriptions.

**Comment by mmagnuski** [comment]
Link to the example:
https://6817-1301584-gh.circle-artifacts.com/0/tmp/circle-artifacts.y7uqUDm/html/auto_examples/inverse/plot_lcmv_beamformer_volume.html

**Comment by agramfort** [comment]
thanks a lot @britta-wstnr

**Pull request merged**
