### PR TITLE
MRG, ENH: make subplots_adjust work with {raw,epochs}.plot() and ica.plot_sources()

### LINKED ISSUE #6647: BUG, VIZ: can't use `fig.subplots_adjust` on `raw.plot` figure
well, you can, but it looks awful:

sphx_glr_plot_55_setting_eeg_reference_001

Note especially the `Help` button and the extra-wide channel and time scrollbars. This resulted from:
```
eeg_picks = mne.pick_types(raw.info, meg=False, eeg=True)
fig = raw.plot(proj=False, order=eeg_picks, n_channels=len(eeg_picks))
fig.subplots_adjust(top=0.94)
fig.suptitle('No reference', size='xx-large', weight='bold')
```
Possible solutions include:

- leaving enough room for a title at the top edge by default (and possibly putting the title on the plot instead of / in addition to in the window titlebar)
- debugging to figure out why it gets so messed up currently, and fixing it so that `subplots_adjust` works more or less normally

### PR DESCRIPTION
**Pull request by drammock**
closes #6647 

- [x] raw
- [x] epochs
- [x] ICA

### CODE REVIEW

**Comment by drammock** [comment]
Here's an example of `subplots_adjust` working on a `raw.plot()` figure: https://14722-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/preprocessing/plot_15_handling_bad_channels.html#interpolation-in-mne-python

**Comment by cbrnr** [comment]
Any chance you can also implement a zen mode (i.e. get rid of the buttons and the timeline overview)?

**Comment by drammock** [comment]
Yes, but I'd like to do that in a separate PR.

**Comment by drammock** [comment]
CIs are happy except for Circle (complaining about dipy link, see #6671). Ready for review and merge. Someone with a hi-dpi screen (@larsoner?) should try generating and resizing the `raw.plot()` window to make sure everything looks normal.

**Comment by larsoner** [comment]
@cbrnr also feel free to try. I'll give it a shot tomorrow

**Comment by cbrnr** [comment]
I tried `raw.plot` on my hidpi screen and it works perfectly! +1 for merge (maybe @larsoner can you test this for epochs and/or ICA?).

**Comment by larsoner** [comment]
On my HiDPI macOS screen things do not look correct. The following code:
```
import mne
path = mne.datasets.sample.data_path()
raw = mne.io.read_raw_fif(path + '/MEG/sample/sample_audvis_raw.fif')
raw.plot()
events = mne.find_events(raw)
epochs = mne.Epochs(raw, events)
epochs.plot()
```
Shows this (just the `raw` plot here but `epochs` has the same spacing issues) on `master`, which has no overlap between elements (correct):

Screen Shot 2019-08-19 at 10 37 16

But on this PR it looks like:

Screen Shot 2019-08-19 at 10 37 34

I am not sure why I have these overlap problems but @cbrnr did not (unless you missed them?).

**Comment by larsoner** [comment]
If you want to test on a non-HiDPI screen as long as you're on the Qt5Agg backend you can do (here on my Linux non-HiDPI machine):
```
QT_SCALE_FACTOR=2 python -ui ~/Desktop/plot.py
```
I get on `master`:

Screenshot from 2019-08-19 10-46-51

But on this PR:

Screenshot from 2019-08-19 10-47-05

**Comment by drammock** [comment]
thanks, I think I know what's wrong. Will fix today.

**Comment by drammock** [comment]
@larsoner @cbrnr  the changes just pushed work locally (show correct button alignment / no overlap) when testing with `QT_SCALE_FACTOR=2` (or 3 or 4).  Please double-check, but assuming it's good (and the CIs are happy) this should be ready for merge.

**Comment by drammock** [comment]
Still looks OK on Circle...

https://14746-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/preprocessing/plot_15_handling_bad_channels.html#interpolation-in-mne-python

**Comment by larsoner** [comment]
The gaps at the top and bottom seem incorrect. `master`:

Screen Shot 2019-08-19 at 20 39 17

This PR:

Screen Shot 2019-08-19 at 20 39 34

**Comment by larsoner** [comment]
(and left and right actually, all off by what appears to be a factor of 2)

**Comment by cbrnr** [comment]
@larsoner I tested with the `osx` backend, which didn't have these issues. I can confirm the problems with the `qt5` backend though. Even with the latest change, `osx` looks fine but `qt5` has large borders on the top, left, and bottom just like in your screenshot.

**Comment by larsoner** [comment]
Actually it appears on my Linux machine, too. Seems to be that the spacing at the edges is not fixed through window resizing. In other words, it should be some set number of pixels, but ends up being proportional to the window size. For example here is my window shrunk to be small:

Screenshot from 2019-08-20 09-16-46

Then once I make resize it to be large:

Screenshot from 2019-08-20 09-18-09

**Comment by drammock** [comment]
I see what @larsoner sees. I thought of a fix last night but didn't have time to implement it then. Will do today.

**Comment by drammock** [comment]
OK, I think I've finally got it.

### Fullscreen:

fullscreen_regularDPI

### Halfscreen:

halfscreen_regularDPI

### Quarterscreen:

quarterscreen_regularDPI

### Fullscreen hiDPI (simulated)

fullscreen_hiDPI

### Halfscreen hiDPI (simulated)

halfscreen_hiDPI

### Quarterscreen hiDPI (simulated)

quarterscreen_hiDPI

Also, effects of `subplots_adjust()` are persistent, with two caveats:

1. if not using ipython / not in `plt.ion()` mode, `fig.subplots_adjust()` requires a `fig.canvas.draw()` or `plt.draw()` for its effects to be visible.  This is normal MPL behavior.

2. The persistent effects of `subplots_adjust` are dependent on the window size at the time --- if user sets `top=0.9`, and the figure size at the time is 10 inches high, then the top margin will persist as **1 inch** through subsequent window resizes (i.e., it will not persist as 10% of figure height). I think in theory it would be possible to maintain user-modified margins as relative and user-untouched margins as a fixed number of inches/pixels, but it seems like more work than it's worth and YAGNI, since my use case is "change margins once so I can add titles to these figures in the docs".

**Comment by cbrnr** [comment]
Unfortunately now it doesn't work for me - but only if I'm on a scaled resolution *and* using the `osx` backend (`qt5` works fine). After resizing the window (`subplots_adjust` works fine), the margins are wrong:

```
import mne
path = mne.datasets.sample.data_path()
raw = mne.io.read_raw_fif(path + '/MEG/sample/sample_audvis_raw.fif')
raw.plot()
```

Initially, this looks fine:
Screen Shot 2019-08-21 at 08 52 57

After manually resizing the window:
Screen Shot 2019-08-21 at 08 53 46

**Comment by larsoner** [comment]
I also see this when running with `MPLBACKEND=macosx`. This is almost certainly a `matplotlib` bug in that backend (it tends to be buggy IIRC). That backend is also just about unusable for me it's so slow. I wonder if we should really support it.

@drammock is there something I could try adding as a resize event handler (for the macosx backend only) that might force it to update the params?

**Comment by drammock** [comment]
I'm really not sure what to do here. I can't tell from the screenshots whether resizing is not happening at all, or if it's happening but not to the correct degree.

**Comment by cbrnr** [comment]
Let's not drop `osx` support. This is still the default backend and I don't find it slower than `qt5` (what's really slowing my Mac down to a point where it's almost unusable is scaled resolution aka HiDPI, but that's another story).

**Comment by drammock** [comment]
I have arranged access to a Mac for next week so I'll try to debug on Monday. I tried today on KC's Mac desktop but could not reproduce (his resolution may not be high enough? It is an "Apple Cinema display" 2560 x 1440)

**Comment by larsoner** [comment]
The Qt5Agg backend is fine, did you do it with `MPLBACKEND=MacOSX python -ui test.py` or so?

**Comment by drammock** [comment]
I tested only with the default backed but had to run to a meeting before I could verify whether it was defaulting to qt or macosx. Will continue testing tomorrow.

**Comment by cbrnr** [comment]
@drammock you need to set a scaled resolution, it works with the native resolution. I'm not sure this works with 2560x1440, but try setting it to a scaled (lower) resolution. I have a 4K display and select the second resolution to the right in the Displays settings page.

**Comment by drammock** [comment]
I'm really struggling to reproduce this. Screenshot:

Screen Shot 2019-08-24 at 1 04 57 PM

**Comment by drammock** [comment]
running in a plain python terminal instead of ipython, I am simply unable to resize the window so I can't actually test it (mouse cursor never turns to double-headed arrow, can drag titlebar to move the window but the titlebar never gets system focus --- note the grayed out close/minimize buttons even though the window is on top)

Screen Shot 2019-08-24 at 1 16 16 PM

**Comment by drammock** [comment]
Running as a script I also get expected behavior:

Screen Shot 2019-08-24 at 1 28 19 PM

**Comment by drammock** [comment]
Here are the test system details:
```
(mnedev) D-10-19-149-242:~ labshared$ python -c 'import mne; mne.sys_info()'
Platform:      Darwin-17.4.0-x86_64-i386-64bit
Python:        3.7.4 (default, Aug 13 2019, 15:17:50)  [Clang 4.0.1 (tags/RELEASE_401/final)]
Executable:    /Users/labshared/miniconda3/envs/mnedev/bin/python
CPU:           i386: 12 cores
Memory:        16.0 GB

mne:           0.19.dev0
numpy:         1.16.4 {blas=mkl_rt, lapack=mkl_rt}
scipy:         1.3.1
matplotlib:    3.1.0 {backend=MacOSX}

sklearn:       0.21.2
numba:         0.45.1
nibabel:       2.5.0
cupy:          Not found
pandas:        0.25.0
dipy:          1.0.0
mayavi:        4.7.1 {qt_api=pyqt5, PyQt5=5.9.2}
pyvista:       0.22.1
vtk:           8.1.2
```

**Comment by drammock** [comment]
Same results at 2048x1152 resolution:

Screen Shot 2019-08-24 at 1 39 43 PM

...and at 1280x720:

Screen Shot 2019-08-24 at 1 44 10 PM

**Comment by drammock** [comment]
for completeness here are the Qt5Agg screenshots on the same system. Default scaling:

Screen Shot 2019-08-24 at 1 53 07 PM

With `QT_SCALE_FACTOR=2`:

Screen Shot 2019-08-24 at 1 56 20 PM

**Comment by cbrnr** [comment]
I think your monitor might not be recognized as a retina/HiDPI screen because its native resolution is too low. To reproduce the problem, you need to have a screen that macOS recognized as retina/HiDPI capable. Here's what my display preferences window looks like - notice the five presets for different scaling factors:

Screen Shot 2019-08-26 at 09 17 49

I think this is only shown if the monitor is at least 4K, and these settings seem to influence how scaling is performed. In your case, I think macOS performs regular non-HiDPI scaling, and therefore you don't see the problem. I can simulate this even on my HiDPI screen by alt-clicking on the "Scaled" radio button and selecting a resolution that says "(low resolution)":

Screen Shot 2019-08-26 at 09 19 37

Now this is exactly the same 3360 x 1890 resolution I normally use, but in low resolution mode (aka non-HiDPI) I don't see the issue with overlapping elements either.

**Comment by cbrnr** [comment]
PS: What this means is that this issue occurs on MacBooks with retina displays (so basically all of them) with the default `osx` backend (so no external display required). This is even worse, because there is no way to select the native (full) resolution for internal displays (because for whatever reason, even the maximum resolution is a scaled one).

**Comment by cbrnr** [comment]
PPS: Here's the code snippet I used (copied from your screenshots):

```
import os
import matplotlib.pyplot as plt
import mne


plt.get_backend()
sample_data_folder = mne.datasets.sample.data_path()
sample_data_raw_file = os.path.join(sample_data_folder, 'MEG', 'sample',
                                    'sample_audvis_raw.fif')
raw = mne.io.read_raw_fif(sample_data_raw_file)
raw.crop(0, 60).load_data()
fig = raw.plot()  # works
fig.subplots_adjust(top=0.9)  # works
# now resize the window - destroys figure layout
```

**Comment by cbrnr** [comment]
Nice! I can confirm that this now works with all combinations of `osx`/`qt5` backends and retina/non-retina resolutions for me.

If the LGTM warnings are fixed (by e.g. using tuples instead of lists), +1 for merge!

**Comment by agramfort** [comment]
Lets merge then

**Comment by cbrnr** [comment]
Thanks @drammock!

**Comment by larsoner** [comment]
BTW @drammock if you ever need to debug HiDPI on macOS on a non-HiDPI display, you can enable (usually ugly) HiDPI resolutions typically hidden from the user with something like:
```Console
$ sudo defaults write /Library/Preferences/com.apple.windowserver.plist DisplayResolutionEnabled -bool true
```
It's also possible clicking the "scaled" button while holding Alt/Option might do it (or be necessary).

I did something like this a couple of years ago when I only had access to a non-HiDPI macOS display and it worked. So hopefully next time you won't need to borrow @ktavabi's machine but any macOS one (where the owner doesn't mind some option tweaking) should work :)

**Pull request merged**
