### PR TITLE
MRG, DOC: Integrate manual parts

### PR DESCRIPTION
**Pull request by larsoner**
Okay @drammock I got a good start on integrating the `manual` parts. Can you look into the last few points, and also do a general cleanup according to whatever you think helps the organization the most?

- [x] Remove all `c_legacy` prefixes by going through the files, modernizing them, and updating refs
- [x] Move `manual/` stuff to `overview/algorithms/`
- [x] Make the simple ICA manual file a brief `discussions` tutorial
- [x] Remove MNE-C docs
- [x] Incorporate `sample_dataset.rst` information directly into `datasets_index.rst`
- [x] Incorporate what is in this PR `ssp-api.rst` content into a tutorial (and/or what in this PR is `ssp.rst`) and remove the `ssp-api.rst` file
- [x] Upload PDF of MNE-C manual (probably directly to `mne-tools.github.io` repo somewhere?) and update the currently broken link in `doc/links.inc`

Don't look at the `diff` too much, it's insane. Better to just browse the result and iterate.

I would like to get this into 0.19 if possible. Do you think it's reasonable for you to get the rest done early next week? If not I can try to spend more time on it.

### CODE REVIEW

**Comment by drammock** [comment]
@larsoner I can prioritize this for Monday

**Comment by drammock** [comment]
@larsoner I think we should punt on integrating the cookbook at this point. It will be a fair amount of work that I don't think can be done well in time for the 0.19 release.

See also mne-tools/mne-tools.github.io#17

**Comment by larsoner** [comment]
So then do you think this is good enough as is for 0.19?

**Comment by drammock** [comment]
I think it's good enough that if you want to merge today, you could.  If it can wait one more day I would spend a little time tomorrow smoothing out the `migrating` page and maybe tweaking the `overview` page a tiny bit.

**Comment by larsoner** [comment]
I'm fine to wait another day

**Comment by larsoner** [comment]
@drammock marked as WIP, feel free to set to MRG once you're happy and I'll take another look, and then if we can get another +1 we should be good for 0.19.

**Comment by larsoner** [comment]
I pushed a PEP8 fix right after yours @drammock

**Comment by drammock** [comment]
@larsoner I just noticed that [the MNE-MATLAB docs got inserted into the MNE-C install pages](https://15387-1301584-gh.circle-artifacts.com/0/dev/install/mne_c.html#mne-matlab-documentation), was that intentional?

**Comment by jasmainak** [comment]
@larsoner @drammock there used to be a [page about IO](https://mne.tools/stable/manual/io.html), has that been nuked now? I can find it through the search bar but not through any weblinks.

**Comment by drammock** [comment]
@jasmainak the page still exists (as you found by searching) but is not very discoverable. This is a known issue; it's true of everything in `doc/overview/algorithms` at the moment. In a subsequent PR we'll clean those up and make them easier to find, and also integrate the "cookbook" page into the rest of the docs (possibly as a tutorial, or divvy up its content into several tutorials). I'll be opening some doc TODO issues today in prep for the sprint; this will be one of them.

**Comment by drammock** [comment]
merging as we have approvals from @larsoner and @agramfort and me.

**Pull request merged**
