### PR TITLE
WIP: unify cov code for raw

### PR DESCRIPTION
**Pull request by dengemann**
Will produce worse memory behavior as it is implemented now. Not too bad, but not beautiful either. Let's see what we can do here.

cc @agramfort @Eric89GXL

### CODE REVIEW

**Comment by dengemann** [comment]
Closes #1729 .

**Comment by agramfort** [comment]
travis complains. Let me know when you're happy here.

**Comment by dengemann** [comment]
@agramfort the failing test is difficult to understand. It's basically telling us that the raw cov computed here is not identical to the raw cov computed in C. If you compare the numbers of samples used the two versions slightly differ by 5 samples or so. Probably the fixed events approach leaves out some data, althought I'd be surprised to see that 5 samples already make this tests fail. Any ideas?

**Comment by dengemann** [comment]
@agramfort maybe we want to remove the test against the precomputed C result?

**Comment by Eric89GXL** [comment]
When I looked at the code earlier, I actually suspected that the fixed length events approach would cause samples to be missed. This is sloppy, and probably the source of the mismatch -- we should fix it. It might make more sense to allow the computation function to take not just an `Epochs` instance, but alternatively just a `numpy` array -- or even better, anything that can be iterated to pull out epochs. That way you could make a generator to pull in the segments of raw data one at a time as necessary and thus fix the memory consumption increase that this also causes.

**Comment by agramfort** [comment]
+1 for fixing fixed events approach

**Comment by agramfort** [comment]
closing this. It's not worth it.

**Pull request closed without merging**
