### PR TITLE
MRG, FIX: allow explicit non-data picks

### LINKED ISSUE #7631: 'No data channels found' with plot_psd() on misc channels
**Issue:**
Error of "No Data channels found" when attempting to **plot_psd()** on **misc** channels in a dataset which contains only **misc** channels. The dataset is created from raw numpy EEG data derived from a custom made device.

**Platform**
```
Platform:      Darwin-19.3.0-x86_64-i386-64bit
Python:        3.7.7 (default, Mar 10 2020, 15:43:33)  [Clang 11.0.0 (clang-1100.0.33.17)]
mne:           0.21.dev0
numpy:         1.18.2 {blas=openblas, lapack=openblas}
scipy:         1.4.1
matplotlib:    3.2.1 {backend=MacOSX}
```

**Steps:**
Create mne object from raw data
```
mne_data = create_mne_object(channels, data, samp_freq)
print(mne_data)
print(mne_data.info)
```

The output is shown below. 
```
<RawArray | 2 x 1024 (4.1 s), ~25 kB, data loaded>
<Info | 7 non-empty values
 bads: []
 ch_names: CH1, CH2
 chs: 2 MISC
 custom_ref_applied: False
 highpass: 0.0 Hz
 lowpass: 125.0 Hz
 meas_date: unspecified
 nchan: 2
 projs: []
 sfreq: 250.0 Hz
>
```
Time-domain data does plot correctly. However, when attempting to plot psd:
```
picks = mne.pick_types(mne_data.info, misc=True)
print(picks)
spect = mne_data.plot_psd(picks=picks)
```
Output:
```
[0 1]
RuntimeError: No data channels found
```

**Summary**
This issue seems similar to the bug [here](https://github.com/mne-tools/mne-python/issues/7154). Is there a workaround at this point? I have tried passing **picks=None** without success.

### PR DESCRIPTION
**Pull request by drammock**
closes #7631 

New test fails on master and passes on this PR

### CODE REVIEW

**Comment by drammock** [comment]
cc @gpeyton

**Comment by drammock** [comment]
still waiting for Travis, but other CIs are all green; this should be ready for review.

**Comment by larsoner** [comment]
LGTM +1 for merge after `latest.inc` update

**Comment by gpeyton** [comment]
thanks @drammock

**Pull request merged**
