### PR TITLE
[WIP] Test if Matplotlib warns (and Travis breaks)

### PR DESCRIPTION
**Pull request by massich**
Playground to see, why I'm getting red travis everywhere.

I get this error in Travis [see this example](https://travis-ci.org/mne-tools/mne-python/jobs/430591326#L2604)

```sh
        if manager is not None:
            try:
                manager.show()
                return
            except NonGuiException:
                pass
        if warn:
            warnings.warn('Matplotlib is currently using %s, which is a '
                          'non-GUI backend, so cannot show the figure.'
>                         % get_backend())
E           UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
```

but when I run it locally it does not break:
```sh
~/code/mne-python agramfort-eeglab_annot_to_event*
(mne) ❯ export MPLBACKEND="agg"                                 

~/code/mne-python agramfort-eeglab_annot_to_event*
(mne) ❯ pytest mne/commands/tests/test_commands.py -k browse_raw
Test session starts (platform: linux, Python 3.6.6, pytest 3.6.3, pytest-sugar 0.9.1)
rootdir: /home/sik/code/mne-python, inifile: setup.cfg
plugins: smother-0.2, sugar-0.9.1, pudb-0.6, ipdb-0.1, faulthandler-1.5.0, cov-2.5.1

 mne/commands/tests/test_commands.py ✓                                          100% ██████████
================================== slowest 20 test durations ==================================
1.01s call     mne/commands/tests/test_commands.py::test_browse_raw
0.00s setup    mne/commands/tests/test_commands.py::test_browse_raw
0.00s teardown mne/commands/tests/test_commands.py::test_browse_raw

Results (2.39s):
       1 passed
      14 deselected

```

### CODE REVIEW

**Comment by larsoner** [comment]
@massich when opening PRs could you set the description properly? That way the GitHub notification emails make it clear what it's about so I don't have to navigate here, see that the description is the template, then look at the code diff to see what it's about...

**Comment by larsoner** [comment]
... and then there is no diff to look at so it's nothing, and I'm more confused.

**Comment by massich** [comment]
@larsoner sorry, I'll try to be more careful. Do you get the template in the email if we write the info as a comment?

**Comment by larsoner** [comment]
> Do you get the template in the email if we write the info as a comment?

I'm not sure what you mean. I'm not sure how you have been opening PRs but lately I keep getting emails with content like:
```
[mne-tools/mne-python] [WIP] Test if Matplotlib warns (and Travis breaks) (#5535)
from: | Joan Massich <notifications@github.com>

Thanks for contributing a pull request! Please make sure you have read the
contribution guidelines
before submitting.

Please be aware that we are a loose team of volunteers so patience is
necessary. Assistance handling other issues is very welcome. We value
all user contributions, no matter how minor they are. If we are slow to
review, either the pull request needs some benchmarking, tinkering,
convincing, etc. or more likely the reviewers are simply busy. In either
case, we ask for your understanding during the review process.

Again, thanks for contributing!

Reference issue
Example: Fixes #1234.

What does this implement/fix?
Explain your changes.

Additional information
Any additional information you think is important.

You can view, comment on, or merge this pull request online at:
  https://github.com/mne-tools/mne-python/pull/5535

Commit Summary
Test if Matplotlib warns (and Travis breaks)
File Changes
Patch Links:
https://github.com/mne-tools/mne-python/pull/5535.patch
https://github.com/mne-tools/mne-python/pull/5535.diff
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
```

**Comment by larsoner** [comment]
Superseded by #5537

**Comment by massich** [comment]
Thx!!

**Pull request closed without merging**
