### PR TITLE
MAINT: Simplify SphinxWindows, use stable intersphinx URLs

### PR DESCRIPTION
**Pull request by larsoner**

### CODE REVIEW

**Comment by larsoner** [comment]
This one is pretty straightforward and contains (hopefully) a fix for the NumPy intersphinx bug by using the `stable` docs rather than their `devdocs`, which I think makes more sense anyway.

**Comment by larsoner** [comment]
@drammock have you ever seen this SG error before?

https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=23363&view=logs&jobId=c04f1cb7-a28e-5e8a-4074-704b3a6c72b1&j=c04f1cb7-a28e-5e8a-4074-704b3a6c72b1&t=f7dd0e15-8953-5b2b-e55e-55ccfc7ae79a

It's a mystery to me. Also it's weird that it's just now happening.

Perhaps another good reason to use a released pydata-sphinx-theme if we can, it would avoid stuff like this!

**Comment by drammock** [comment]
> have you ever seen this SG error before?

That link doesn't work for me, it says "an unexpected error has occurred" and reloading doesn't help. What was the SG error?

**Comment by larsoner** [comment]
Some decoding error on windows that was fixed by the PYTHONUTF env var. If you want to see it you can open a quick PR removing that and it should show the error again

**Comment by drammock** [comment]
FWIW we hit this in pydata-sphinx-theme too. In that case it was the existence of emoji in our README that caused the trouble with the Windows CIs (during the `pip install -e .` step; apparently the README is added to the installation metadata in some way). The solution there was setting the shell to BASH (not PowerShell) *and* using the `PYTHONUTF8` env var, as you did here. Various attempts to change the codepage in PowerShell didn't work.

**Pull request merged**
