### PR TITLE
Slightly rework `mne.sys_info()`

### LINKED ISSUE #11543: Do not list not installed packages in `mne.sys_info()`
We would like to see the output of `mne.sys_info()` in issue reports, but this list is very long – even when many packages are not installed it looks like this:

```
Platform:         macOS-13.2.1-arm64-arm-64bit
Python:           3.10.10 (v3.10.10:aad5f6a891, Feb  7 2023, 08:47:40) [Clang 13.0.0 (clang-1300.0.29.30)]
Executable:       /Users/clemens/.local/pipx/venvs/ipython/bin/python
CPU:              arm: 12 cores
Memory:           32.0 GB

mne:              1.4.dev0
numpy:            1.24.2 {OpenBLAS 0.3.21 with 12 threads}
scipy:            1.10.1
matplotlib:       3.7.0 {backend=MacOSX}

sklearn:          Not found
numba:            Not found
nibabel:          Not found
nilearn:          Not found
dipy:             Not found
openmeeg:         Not found
cupy:             Not found
pandas:           Not found
pyvista:          Not found
pyvistaqt:        Not found
ipyvtklink:       Not found
vtk:              Not found
qtpy:             Not found
ipympl:           Not found
pyqtgraph:        Not found
pooch:            v1.7.0

mne_bids:         Not found
mne_nirs:         Not found
mne_features:     Not found
mne_qt_browser:   Not found
mne_connectivity: Not found
mne_icalabel:     Not found
```

I propose to exclude packages that are not installed, so the list would be much shorter:

```
Platform:         macOS-13.2.1-arm64-arm-64bit
Python:           3.10.10 (v3.10.10:aad5f6a891, Feb  7 2023, 08:47:40) [Clang 13.0.0 (clang-1300.0.29.30)]
Executable:       /Users/clemens/.local/pipx/venvs/ipython/bin/python
CPU:              arm: 12 cores
Memory:           32.0 GB

mne:              1.4.dev0
numpy:            1.24.2 {OpenBLAS 0.3.21 with 12 threads}
scipy:            1.10.1
matplotlib:       3.7.0 {backend=MacOSX}

pooch:            v1.7.0
```

### PR DESCRIPTION
**Pull request by cbrnr**
Fixes #11543, supersedes #11544.

### CODE REVIEW

**Comment by larsoner** [comment]
> But feel free to ...

I'm also happy to push a quick commit for some of this stuff if you want a break from this stuff :)

**Comment by cbrnr** [comment]
@larsoner yes, please go ahead! I didn't include the headers this time to keep the output shorter.

**Comment by larsoner** [comment]
Okay updated by iterating with @drammock during what we errantly thought were office hours trying various headers/left items etc., WDYT @cbrnr ?
```
$ mne sys_info
Platform:         Linux-5.19.0-35-generic-x86_64-with-glibc2.36
Python:           3.10.7 (main, Nov 24 2022, 19:45:47) [GCC 12.2.0]
Executable:       /home/larsoner/.local/bin/python
CPU:              x86_64 (8 cores)
Memory:           62.8 GB

Core
├☑ mne:              1.4.0.dev76+gbc47d98992
├☑ numpy:            1.25.0.dev0+364.g341afc9000 (OpenBLAS 0.3.21.dev with 1 thread)
├☑ scipy:            1.11.0.dev0+1286.bd120df
├☑ matplotlib:       3.8.0.dev425+g3aa5386c38 (backend=QtAgg)
├☑ pooch:            1.5.2
└☑ jinja2:           3.1.2

Numerical (optional)
├☑ sklearn:          1.3.dev0
├☑ numba:            0.57.0dev0+952.g1304e64d0
├☑ nibabel:          5.1.0.dev3+g7327927f
├☑ nilearn:          0.10.1.dev
├☑ dipy:             1.6.0dev0
├☑ openmeeg:         2.6.0.dev1
├☑ pandas:           1.6.0.dev0+206.g4baeede019
└☐ unavailable:      cupy

Visualization (optional)
├☑ pyvista:          0.39.dev0 (OpenGL 4.5.0 NVIDIA 470.161.03 via NVIDIA GeForce GTX 650 Ti BOOST/PCIe/SSE2)
├☑ pyvistaqt:        0.10.dev0
├☑ ipyvtklink:       0.2.2
├☑ vtk:              9.2.5
├☑ qtpy:             2.4.0.dev0 (PyQt6=6.4.0)
├☑ ipympl:           0.9.2
├☑ pyqtgraph:        0.12.4
└☐ unavailable:      mne-qt-browser

Ecosystem (optional)
├☑ mne_bids:         0.13.dev0
├☑ mne_nirs:         0.5.dev0
├☑ mne_connectivity: 0.6.0dev0
└☐ unavailable:      mne_features, mne_icalabel
```
The checkboxes are a bit small on GitHub but decent in a terminal:

Screenshot from 2023-03-17 13-28-37

But if those are too small we could use filled squares:
```
Core
├▣ mne:              1.4.0.dev76+gbc47d98992
├▣ numpy:            1.25.0.dev0+364.g341afc9000 (OpenBLAS 0.3.21.dev with 1 thread)
├▣ scipy:            1.11.0.dev0+1286.bd120df
├▣ matplotlib:       3.8.0.dev425+g3aa5386c38 (backend=QtAgg)
├▣ pooch:            1.5.2
└▣ jinja2:           3.1.2

Numerical (optional)
├▣ sklearn:          1.3.dev0
├▣ numba:            0.57.0dev0+952.g1304e64d0
├▣ nibabel:          5.1.0.dev3+g7327927f
├▣ nilearn:          0.10.1.dev
├▣ dipy:             1.6.0dev0
├▣ openmeeg:         2.6.0.dev1
├▣ pandas:           1.6.0.dev0+206.g4baeede019
└▢ unavailable:      cupy
```
Screenshot from 2023-03-17 13-30-22

**Comment by cbrnr** [comment]
Looks great! I like the checkboxes better than the filled ones, but I let you decide. Thank you!

**Comment by larsoner** [comment]
Okay back to boxes -- @drammock feel free to mark for merge if you're happy

**Comment by hoechenberger** [comment]
Great work! Can we remove the colons after the package names? I don't think they're needed since we use a tabular alignment.

**Comment by agramfort** [comment]
a few comments on this one.

It runs on my laptop but it took about a minute to print.

Also I get this

```
❯ mne sys_info
Platform:         macOS-13.2.1-arm64-arm-64bit
Python:           3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:25:29) [Clang 14.0.6 ]
Executable:       /Users/agramfort/miniconda3/envs/mne/bin/python3.10
CPU:              arm (10 cores)
Memory:           32.0 GB

Core
├☑ mne:              1.4.dev0
├☑ numpy:            1.23.5 (OpenBLAS 0.3.21 with 10 threads)
├☑ scipy:            1.10.0
├☑ matplotlib:       3.7.0 (backend=MacOSX)
├☑ pooch:            1.6.0
└☑ jinja2:           3.1.2

Numerical (optional)
├☑ sklearn:          1.2.0
├☑ numba:            0.56.4
├☑ nibabel:          5.0.0
├☑ nilearn:          0.10.0
├☑ dipy:             1.5.0
├☑ openmeeg:         2.5.5
├☑ pandas:           1.5.3
└☐ unavailable:      cupy

Visualization (optional)
├☑ pyvista:          0.37.0 (OpenGL 4.1 Metal - 83 via Apple M1 Pro)
├☑ pyvistaqt:        0.9.0
├☑ ipyvtklink:       0.2.2
├☑ vtk:              9.2.5
├☑ qtpy:             2.3.0 (PyQt5=5.15.6)
├☑ ipympl:           0.9.2
├☑ pyqtgraph:        0.13.1
└☐ unavailable:      mne-qt-browser

Ecosystem (optional)
├☑ mne_bids:         0.13.dev0
├☑ mne_nirs:         0.6.dev0
└☐ unavailable:      mne_features, mne_connectivity, mne_icalabel
❯ which mne
/Users/agramfort/miniconda3/envs/mne/bin/mne
❯ mne browse_raw ~/mne_data/MNE-sample-data/MEG/sample/sample_audvis_raw.fif
❯ conda list | grep mne-qt
mne-qt-browser            0.4.0           py310hbe9552e_0    conda-forge
```

you can see that mne-qt-browser is installed and works but the new `mne sys_info` does not detect this. To me it's a bug...

**Pull request merged**
