### PR TITLE
MRG: new color scheme for docs

### PR DESCRIPTION
**Pull request by drammock**
@Eric89GXL @agramfort as requested, an updated color scheme for the docs (and a single-character typo fix).  LMK what you think.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
The biggest changes I notice are (1) top bar slightly different, (2) `.. note::` a bit different:

https://circle-artifacts.com/gh/mne-tools/mne-python/824/artifacts/0/home/ubuntu/mne-python/doc/_build/html/getting_started.html

(3) unification of colors of `.. note::` and Tutorials boxes:

https://circle-artifacts.com/gh/mne-tools/mne-python/824/artifacts/0/home/ubuntu/mne-python/doc/_build/html/tutorials.html

(4) unified `.. warning::`:

https://circle-artifacts.com/gh/mne-tools/mne-python/824/artifacts/0/home/ubuntu/mne-python/doc/_build/html/generated/mne.preprocessing.maxwell_filter.html#mne.preprocessing.maxwell_filter

Anything else that we should look at?

LGTM, +1 for merge from my end.

**Comment by drammock** [comment]
The background color for code samples has also changed.  Also the download boxes at the bottom of [this page](https://circle-artifacts.com/gh/mne-tools/mne-python/824/artifacts/0/home/ubuntu/mne-python/doc/_build/html/auto_tutorials/plot_python_intro.html).  I'm pushing 1 more commit though because I noticed one change that I forgot to make. After build, it will show up in the highlighting around function signatures, e.g., [here](https://circle-artifacts.com/gh/mne-tools/mne-python/824/artifacts/0/home/ubuntu/mne-python/doc/_build/html/generated/mne.preprocessing.maxwell_filter.html#mne.preprocessing.maxwell_filter)

**Comment by Eric89GXL** [comment]
Unification of the yellows I take it?

https://circle-artifacts.com/gh/mne-tools/mne-python/825/artifacts/0/home/ubuntu/mne-python/doc/_build/html/generated/mne.preprocessing.maxwell_filter.html#mne.preprocessing.maxwell_filter

**Comment by drammock** [comment]
yes, unification of the yellows, plus setting the function names to inherit their color when they have a yellow background.  Side by side: [before](https://circle-artifacts.com/gh/mne-tools/mne-python/824/artifacts/0/home/ubuntu/mne-python/doc/_build/html/generated/mne.preprocessing.maxwell_filter.html#mne.preprocessing.maxwell_filter), [after](https://circle-artifacts.com/gh/mne-tools/mne-python/825/artifacts/0/home/ubuntu/mne-python/doc/_build/html/generated/mne.preprocessing.maxwell_filter.html#mne.preprocessing.maxwell_filter)

**Comment by agramfort** [comment]
I find the red for warnings a bit aggressive. Can we soften it?

**Comment by agramfort** [comment]
an you make it a lighter red eg rgb(255,98,89) or something like this?

PS : I did not test just picked a color on my color app :)

**Comment by agramfort** [comment]
Yellow is great

Red on warning is the aggressive color

**Comment by drammock** [comment]
@agramfort are you happy with [the red color here](https://circle-artifacts.com/gh/mne-tools/mne-python/828/artifacts/0/home/ubuntu/mne-python/doc/_build/html/auto_tutorials/plot_artifacts_correction_maxwell_filtering.html)?  Also FYI, the long filenames at the bottom of that page was the reason for expanding the download box width.

**Comment by agramfort** [comment]
looks great 

thx @drammock !

**Comment by jona-sassenhagen** [comment]
Tutorials look great IMO. Is there a link with the current master with pics?

**Comment by Eric89GXL** [comment]
[This] (http://mne-tools.github.io/dev/tutorials.html) should auto-update with each new merge to `master`

**Comment by jona-sassenhagen** [comment]
Ah great. @Eric89GXL , how about fixing the ylims on the Maxwell example plot?

**Comment by jona-sassenhagen** [comment]
I mean, set them all to the same value to make the plot visually clearer.

**Comment by Eric89GXL** [comment]
+1 feel free to add to one of your PRs if you can

**Comment by jona-sassenhagen** [comment]
Will add to the evoked one, assuming I can remember what units MEG is in ...

**Pull request merged**
