### PR TITLE
[WIP] fix component inds used in plot_properties in ica tutorial

### PR DESCRIPTION
**Pull request by mmagnuski**
I checked circle artifacts to see how plot_properties looks in the tutorial - and the component ind's were bad (it seems I have corrected them the wrong way in the plot_properties PR). This little PR fixes the components inds so that tutorial is no longer confusing :)

### CODE REVIEW

**Comment by mmagnuski** [comment]
That's weird, I re-checked on my computer and it seems that the old numbers should have been ok.
So there is difference between circle artifacts and my computer. Is this possible given that I set the seed in the tutorial?
(the current circle doesn't have plots, so I am comparing to circle for the merge of plor_properties)

**Comment by jaeilepp** [comment]
I'm not sure which build you are looking at, but at the latest successful [build](https://1408-1301584-gh.circle-artifacts.com/0//home/ubuntu/mne-python/doc/_build/html/auto_tutorials/plot_artifacts_correction_ica.html) the ids seem correct

**Comment by jaeilepp** [comment]
No wait, you're right. The cardiac components are wrong.

**Comment by jaeilepp** [comment]
Maybe you should resort to using ``ica.find_bads_ecg`` instead and get rid of ic numbers in the narrative. Perhaps the random number generator works differently on different platforms.

**Comment by agramfort** [comment]
@mmagnuski you're facing numerical differences between systems. We've seen it many times in ICA.

+1 for using fing_bads_ecg

**Comment by mmagnuski** [comment]
Ok, I'll try fixing this. I will need to change the storytelling a little, but will use automatic methods.

**Comment by mmagnuski** [comment]
(I'll just close this and start over in a different PR)

**Pull request closed without merging**
