### PR TITLE
Refactor mne/channels Code

### PR DESCRIPTION
**Pull request by massich**
This PR refactors the code no tests involved.

### CODE REVIEW

**Comment by massich** [comment]
I get into something quite weird. I cannot import mne. But if I do `from mne import channels` and then do `import mne` it works like a charm.

```sh

Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import mne
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-d70f97b8aea9> in <module>
----> 1 import mne

~/code/mne-python/mne/__init__.py in <module>
     23                     get_config, get_config_path, set_cache_dir,
     24                     set_memmap_min_size, grand_average, sys_info, open_docs)
---> 25 from .io.pick import (pick_types, pick_channels,
     26                       pick_channels_regexp, pick_channels_forward,
     27                       pick_types_forward, pick_channels_cov,

~/code/mne-python/mne/io/__init__.py in <module>
      7 
      8 from .open import fiff_open, show_fiff, _fiff_get_fid
----> 9 from .meas_info import (read_fiducials, write_fiducials, read_info, write_info,
     10                         _empty_info, _merge_info, _force_update_info, Info,
     11                         anonymize_info, _stamp_to_dt)

~/code/mne-python/mne/io/meas_info.py in <module>
     30 from ..transforms import invert_transform
     31 from ..utils import logger, verbose, warn, object_diff, _validate_type
---> 32 from ..channels._digitization.base import _format_dig_points
     33 from .compensator import get_current_comp
     34 

~/code/mne-python/mne/channels/__init__.py in <module>
      4 """
      5 
----> 6 from .layout import (Layout, make_eeg_layout, make_grid_layout, read_layout,
      7                      find_layout, generate_2d_layout)
      8 from .montage import (read_montage, read_dig_montage, Montage, DigMontage,

~/code/mne-python/mne/channels/layout.py in <module>
     17 
     18 from ..transforms import _pol_to_cart, _cart_to_sph
---> 19 from ..bem import fit_sphere_to_headshape
     20 from ..io.pick import pick_types, _picks_to_idx
     21 from ..io.constants import FIFF

~/code/mne-python/mne/bem.py in <module>
     24 from .io.tree import dir_tree_find
     25 from .io.open import fiff_open
---> 26 from .surface import (read_surface, write_surface, complete_surface_info,
     27                       _compute_nearest, _get_ico_surface, read_tri,
     28                       _fast_cross_nd_sum, _get_solids)

~/code/mne-python/mne/surface.py in <module>
     24 from .io.write import (write_int, start_file, end_block, start_block, end_file,
     25                        write_string, write_float_sparse_rcs)
---> 26 from .channels.channels import _get_meg_system
     27 from .parallel import parallel_func
     28 from .transforms import (transform_surface_to, _pol_to_cart, _cart_to_sph,

~/code/mne-python/mne/channels/channels.py in <module>
     18 from ..io.compensator import get_current_comp
     19 from ..io.constants import FIFF
---> 20 from ..io.meas_info import anonymize_info, Info
     21 from ..io.pick import (channel_type, pick_info, pick_types, _picks_by_type,
     22                        _check_excludes_includes, _contains_ch_type,

ImportError: cannot import name 'anonymize_info'

In [7]: from mne import channels

In [8]: import mne

In [9]: mne.__version__
Out[9]: '0.19.dev0'

In [10]: 
```

**Comment by larsoner** [comment]
Sounds like a circular import problem

**Comment by larsoner** [comment]
@massich do we still need this?

**Comment by agramfort** [comment]
no. We can start over now. When we have time...

**Pull request closed without merging**
