### PR TITLE
ENH: multiple colors for ica.plot_sources(evokeds)

### PR DESCRIPTION
**Pull request by marsipu**
#### Reference issue
For #9417

#### What does this implement/fix?
This is supposed to make the differentiation of multiple ICA-components displayed for evokeds easier by displaying them in different colors.

#### Questions
**Are there more ICA-Categories than EOG/ECG which would be displayed simultaneously to consider?**
In this draft I accounted for different categories by assigning a different colormap for each one.

### CODE REVIEW

**Comment by hoechenberger** [comment]
I would differentiate categories by line style and components by color

**Comment by marsipu** [comment]
> Good start! I would differentiate categories by line style and components by color 💪
Thank you for the idea. How big is the possible number of different categories I should account for?

**Comment by hoechenberger** [comment]
So far I've only seen two in real life (ECG and EOG), not sure if we even support anything else right now? 😅

**Comment by hoechenberger** [comment]
Thanks @marsipu! Can you touch one of the ICA tutorials so we can actually see the effects in the generated report?

https://mne.tools/stable/auto_tutorials/preprocessing/40_artifact_correction_ica.html?highlight=ica#using-a-simulated-channel-to-select-ica-components might be a good place!

By "touching" I really mean, simply changing a tiny little thing, e.g. improving phrasing somewhere, to enforce re-rendering of the tutorial

**Comment by marsipu** [comment]
Where do I find the generated report?

**Comment by drammock** [comment]
Screenshot_2021-06-10 ENH multiple colors for ica plot_sources(evokeds) by marsipu · Pull Request #9444 · mne-tools mne-pyt

**Comment by marsipu** [comment]
Thank you! I also created this [gist](https://gist.github.com/marsipu/212d764a18c205cfa69fba49b5e6a418) to test multiple component-categories.

**Comment by hoechenberger** [comment]
It's working!

https://29347-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/preprocessing/40_artifact_correction_ica.html#using-a-simulated-channel-to-select-ica-components


I'm not a big fan of the color map though, can we try to see what it looks like e.g. with `tab10`?

**Review by agramfort — APPROVED** [review]

**Comment by agramfort** [comment]
anyone feel free to MRG if happy. thx @marsipu

**Comment by drammock** [comment]
> I'm not a big fan of the color map though, can we try to see what it looks like e.g. with `tab10`?

I tend to agree with @hoechenberger here, that we should stick with MPL default color choices (which in this case means `tab10`) unless we have a good reason not to.  I also found the gist example a little... overwhelming; it seemed to me difficult to keep track of which ones were ECG and which were EOG, etc.  I think that particular visualization would be better if *color* (rather than linestyle) were held fixed within a component type (so, ECG component 1 is blue solid, ECG 2 is blue dashed; EOG1 is orange solid, EOG2 is orange dashed; etc).  However, I acknowledge that this is a nitpick verging on bikeshedding, especially since I don't think it's all that common to view multiple component types at once (?).  So in that light maybe it is better to hold linestyle fixed (= all solid) and vary color, since the most common use case is to show 1-3 components of the same kind (EOG, ECG, etc) and nothing else.  But having talked myself out of that suggestion, I still think `tab10` is a better choice than `rainbow`.

**Comment by marsipu** [comment]
@drammock thank you for the feedback. I agree that especially the example from the gist doesn't proof the point of differentiating the components more easily. I also think that showing multiple component-types together is probably more rare than multiple components from the same type. At the moment, I just use the 4 named matplotlib linestyles, so displaying more than 4 different components with the same color but different linestyles would then lead to the original problem that components could not be differentiated (these could of course expanded with custom linestyles, but that would maybe not help much in terms of differentiation). So as you suggest I would keep it the way it is currently implemented and change the colormap to `tab10` (for `excluded_components>10` this would result in equal colors again, but so many excluded components are probably unlikely, right?).

**Comment by marsipu** [comment]
grafik

**Comment by hoechenberger** [comment]
This looks fantastic!

**Comment by drammock** [comment]
in it goes!  Thanks @marsipu

**Comment by marsipu** [comment]
Thank you:). Somehow #9417 wasn't closed

**Comment by hoechenberger** [comment]
Thanks @marsipu

**Pull request merged**
