### PR TITLE
chore: Included githubactions in the dependabot config

### PR DESCRIPTION
**Pull request by naveensrinivasan**
This should help with keeping the GitHub actions updated on new releases. This will also help with keeping it secure.

Dependabot helps in keeping the supply chain secure https://docs.github.com/en/code-security/dependabot

GitHub actions up to date https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

https://github.com/ossf/scorecard/blob/main/docs/checks.md#dependency-update-tool
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>

### CODE REVIEW

**Comment by hoechenberger** [comment]
I like and appreciate dependabot, but why do we need it for GH actions? And if we start using it anyway, why use it for GH actions only?

**Comment by larsoner** [comment]
> why do we need it for GH actions?

From a quick look at the URLs in the description I think it's a security thing

> why use it for GH actions only?

For this I think it's essentially because GH actions uses versioned things that you can "install" (`uses:`, really). Azure and CircleCI don't really have such mechanisms -- they update their machine images with updates directly. At least that's my understanding, but in the meantime this is at least some progress so I'll go ahead and merge!

Thanks @naveensrinivasan !

**Comment by hoechenberger** [comment]
> From a quick look at the URLs in the description I think it's a security thing

Yes, it's essential eg in JavaScript projects. 

But it can also scan requirements.txt files and that's why I'm asking why limit it to GHA :)

**Comment by cbrnr** [comment]
> But it can also scan requirements.txt files and that's why I'm asking why limit it to GHA :)

Aren't we already testing with the latest package dependencies anyway (in some CI job)? And wouldn't that require pinning all dependencies to specific versions, so that Dependabot can update?

**Pull request merged**
