### PR TITLE
MRG, MAINT: Remove PySurfer from CircleCI

### PR DESCRIPTION
**Pull request by larsoner**
@GuillaumeFavelier this should work at this point, right? CircleCI should maybe give us the answer.

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
> this should work at this point, right?

In theory yes, I'l still interested by the results

**Comment by GuillaumeFavelier** [comment]
This made me realize that `plot_parcellation.py` uses `PySurfer` explicity:

https://17778-1301584-gh.circle-artifacts.com/0/dev/auto_examples/visualization/plot_parcellation.html#sphx-glr-auto-examples-visualization-plot-parcellation-py

But why Circle was happy?

**Comment by larsoner** [comment]
Ahh there is still `pip install -r requirements.txt` which has PySurfer in there.

**Comment by GuillaumeFavelier** [comment]
It seems like refactor is needed for `plot_parcellation.py` and `plot_vector_source_estimates` (work in progress in https://github.com/mne-tools/mne-python/pull/7060)

**Comment by larsoner** [comment]
For `plot_parcellation` we can probably just change it to iterate over the labels and do `brain.add_label` for each one. I'll close for now but I'll add to your TODO list to do this once vector source estimates are taken care of

**Pull request closed without merging**
