### PR TITLE
ENH: fix layout guessing / ch names for plot proj topomap

### PR DESCRIPTION
**Pull request by dengemann**
This addresses the recent issue reported by Luke. Viz tests pass over here.

### CODE REVIEW

**Comment by jingjiangpsy** [comment]
Hello,

I came across this same problem like below. Is it really fixed?

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 81, in execfile
    builtins.execfile(filename, *where)
  File "/nobackup/nietzsche2/Eye_MEG/eyegazemeg/python/plot_artifacts_correction_ssp.py", line 52, in <module>
    mne.viz.plot_projs_topomap(ecg_projs)
  File "/afs/cbs.mpg.de/software/pythonlib/mne-python/0.12.0/lib/python2.7/site-packages/mne-0.12.0-py2.7.egg/mne/viz/topomap.py", line 243, in plot_projs_topomap
    % proj['desc'])
RuntimeError: Cannot find a proper layout for projection ECG-planar--0.200-0.400-PCA-01

**Comment by agramfort** [comment]
you're using 0.12

did you try running the current dev version?

**Comment by DominiqueMakowski** [comment]
Hi,

Unfortunately, I coudn't manage to plot the projs either...

```python
Traceback (most recent call last):
  File "<ipython-input-29-da88c79242b6>", line 1, in <module>
    mne.viz.plot_projs_topomap(eog_projs)

  File "C:\Users\DomM\Desktop\WinPython-64bit-3.5.2.2\python-3.5.2.amd64\lib\site-packages\mne\viz\topomap.py", line 259, in plot_projs_topomap
    % proj['desc'])

RuntimeError: Cannot find a proper layout for projection EOG-eeg--0.200-0.200-PCA-01
```

I'm using the 0.13 version.

Thank you !

**Comment by agramfort** [comment]
did you try to pass a layout to mne.viz.plot_projs_topomap ?

**Comment by DominiqueMakowski** [comment]
Ok it works I feel dumb now 😆 

Anyway as I didn't see the solution on the internet I'll put there the code I used for others

```python
mne.viz.plot_projs_topomap(eog_projs, layout=mne.channels.find_layout(raw.info))
```

Thank you for your quick answer!

**Comment by Eric89GXL** [comment]
Should we make `layout` also take `info` to save people a step?

**Comment by agramfort** [comment]
I don't feel a burning need...

**Pull request merged**
