### PR TITLE
MRG: Fix overlap between subplot titles and x-axis tick labels in viz.plot_*_psd()

### PR DESCRIPTION
**Pull request by hoechenberger**
This was brought up by @larsoner in https://github.com/mne-tools/mne-python/pull/9842#discussion_r729014409

MWE:
```python
# %%
from pathlib import Path
import mne


sample_dir = Path(mne.datasets.sample.data_path())
sample_fname = sample_dir / 'MEG' / 'sample' / 'sample_audvis_raw.fif'

raw = mne.io.read_raw_fif(sample_fname)
raw.crop(tmax=60)

events = mne.find_events(raw, stim_channel='STI 014')
event_id = {'auditory/left': 1, 'auditory/right': 2, 'visual/left': 3,
            'visual/right': 4, 'face': 5, 'buttonpress': 32}

epochs = mne.Epochs(raw, events=events, event_id=event_id,
                    tmin=-0.2, tmax=0.5, baseline=(None, 0),
                    preload=True)

fig = epochs.plot_psd()
```

On `main`:
main

This PR:
pr

### CODE REVIEW

**Comment by hoechenberger** [comment]
@drammock 
With the `tight_layout()` all, the figure looks better.
But I get this good old warning:
```
E   UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
3175
```
Is there a way to avoid (or just swallow) it? Is it **safe** to ignore it?

**Comment by hoechenberger** [comment]
Thanks @agramfort!

But I'm also wondering if maybe I should simply make `mne.viz.tight_layout()` simply consume and hide this warning…

**Comment by drammock** [comment]
IMO it's useful for us to know when we're using tight layout on axes that don't respect it. So I would not swallow the warning. ( I also agree that subplots_adjust is preferable here)

**Comment by hoechenberger** [comment]
Alright, thank you!

**Comment by hoechenberger** [comment]
Seems to render fine:
https://36071-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/intro/10_overview.html#loading-data

https://36071-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/epochs/20_visualize_epochs.html#plotting-the-power-spectrum-of-epochs

**Pull request merged**
