### PR TITLE
CI: Test circle

### PR DESCRIPTION
**Pull request by larsoner**
CicleCI is failing on `main`, let's see what the actual error is.

### CODE REVIEW

**Comment by larsoner** [comment]
Failure replicated!

@GuillaumeFavelier can you replicate? I suspect this might be due to #10430

**Comment by GuillaumeFavelier** [comment]
> can you replicate?

Yes I can replicate on this PR. I'm on it :+1:

**Comment by larsoner** [comment]
One possibility is that the `Brain` is never properly/completely `__init__`ed, because I had to add the `getattr` for `_cleaned`, but this is set in `__init__` I think.

**Comment by larsoner** [comment]
(and then the example fails, and during cleanup it does the GC check, which fails because cleanup was never attempted)

**Comment by GuillaumeFavelier** [comment]
This happens because we use `partial` in `mne/viz/backends/_qt.py`. I chose `partial` to patch the `NotImplementedError` in `Brain.__hash__()`, I'll have to find something else.

**Comment by larsoner** [comment]
>  I chose partial to patch the NotImplementedError in Brain.__hash__(), I'll have to find something else.

It would probably work to just have `Brain.__hash__` return `id(self)`. As long as we really do clean everything up so Qt doesn't try to call the method again, it hopefully wouldn't lead to segfaults :)

**Comment by GuillaumeFavelier** [comment]
> It would probably work to just have `Brain.__hash__` return `id(self)`

If you do not mind, I can try in this PR.

>  it hopefully wouldn't lead to segfaults

If it is the case, it is a sign that `cleaning` is not thorough anyway

**Comment by larsoner** [comment]
... actually, even better would be to just set `self._hash = time.time_ns()` during `__init__.py`, and have `__hash__` return this value. There is no way in practice that we will instantiate two `brain` objects at the same time, right? :)

But really I don't think it's going to matter much, we just have to find a way to placate `pyside2`. Do you know offhand, does it hash the `self` of any bound method for some reason? I searched a tiny bit and didn't find anything.

> If you do not mind, I can try in this PR.

Yes, please test locally then push here, and I'll merge if CIs are green.

**Comment by larsoner** [comment]
... please push with `[circle front]` or touch an example that uses Brain, though!

**Comment by larsoner** [comment]
Thanks for the quick fix @GuillaumeFavelier !

**Pull request merged**
