### PR TITLE
FIX: set_annotations when meas_date is prior to 1970

### LINKED ISSUE #6621: [BUG] set_annotations fails for data with a meas_date prior to 1970
Try reading this [example_file](https://drive.google.com/file/d/1vZCW3wUQ_0gemac_NFO9LtYVlG70rt-R/view?usp=sharing) (800MB) and check out `raw.info['meas_date']` --> it will be negative.

That's because the data has been anonymized (cc @agramfort ) to some time prior 1970.

That's an issue, because we represent `raw.info['meas_date']` in unix time, which is 0 at 1970, and thus negative for all prior years (strictly speaking, it's even undefined)

A negative `meas_date` will raise an error when we make an annotation object from scratch and try to set it with `raw.set_annotations()`.

That is because of this code:

in `set_annotations`: https://github.com/mne-tools/mne-python/blob/368a490f9d7a298050ee04c2aa7882629c9fab21/mne/io/base.py#L792

--> `time_of_first_sample` will be negative if `meas_date` is negative

then later we do: https://github.com/mne-tools/mne-python/blob/368a490f9d7a298050ee04c2aa7882629c9fab21/mne/io/base.py#L798-L801

i.e., pass a negative `tmin` to the `crop` function, which then raises an error: https://github.com/mne-tools/mne-python/blob/368a490f9d7a298050ee04c2aa7882629c9fab21/mne/annotations.py#L363-L364

cc @massich

### PR DESCRIPTION
**Pull request by massich**
fixes #6621

### CODE REVIEW

**Comment by sappelhoff** [comment]
Thanks @massich

**Comment by larsoner** [comment]
@massich it looks like this broke CircleCI, can you look?

https://circleci.com/gh/mne-tools/mne-python/14565

**Comment by sappelhoff** [comment]
I feel very guilty, but when I merged, CIs were green :)

**Comment by larsoner** [comment]
@sappelhoff don't worry about it :) Some of the effective "tests" only run after merge because that's when CircleCI rebuilds the doc with all examples.

**Comment by massich** [comment]
@larsoner sure I'm on it.

**Pull request merged**
