### PR TITLE
add urls to limo fetcher

### PR DESCRIPTION
**Pull request by JoseAlanis**
Hey guys, 

I'm adding the remaining URLs to the limo fetcher to provide support for the whole LIMO dataset.
In the original PR we only allowed the download of two subjects.

Best,
José

### CODE REVIEW

**Comment by JoseAlanis** [comment]
ping @dengemann

**Comment by dengemann** [comment]
Two things. Do we have a way of downloading them all in one command? Can you make a small check that throws an informative error if the user asks for impossible subjects?

**Comment by JoseAlanis** [comment]
No, but one could just put them in a list outside the function with something like
 ``limo_epochs = [limo.load_data(subject=subject) for subject in list(range(1, 'some_int'))]``.

And yes, we already habe a validity check for subjects inside the function. Subject must be an int in range 1 to 18, otherwise the fetcher will throw an error.

**Comment by agramfort** [comment]
really cool !

+1 for MRG

**Comment by dengemann** [comment]
thx for the fix!

**Comment by agramfort** [comment]
@dengemann can you please squash when merging? this issue was reported on your previous merge or a PR? thanks

**Comment by dengemann** [comment]
Is this a new rule?

**Comment by agramfort** [comment]
>
> Is this a new rule?
>

it depends what you call new? maybe 2 years... :)

**Comment by dengemann** [comment]
Well at least it was not there from the beginning ;-) Ok I'll pay more attention in the future.

**Pull request merged**
