### PR TITLE
MNT: Reduce number of calls to _update

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
1) This PR reduces the amount of renderer updates. I modified the two main entry points: `__init__()` and `setup_time_viewer()`.
For now I use a context manager but if big chunks of code need to be nested maybe `enable/disable` functions are better, not sure.
I'm still trying to download 0.119 locally so testing is delayed but in the example that I use regularly, it went from 16 to 1.

2) I'll see how to reduce the amount of overlay updates next.
3) I'll also investigate why the window is so slow to setup (suggested in https://github.com/mne-tools/mne-python/pull/9407#issuecomment-844199125)

Closes https://github.com/mne-tools/mne-python/issues/8986

### CODE REVIEW

**Comment by larsoner** [comment]
Notebook test is failing, seems related. 

In any case, this is the slowest `_brain` test on macOS run on this PR:
```
9.10s call     mne/viz/_brain/tests/test_brain.py::test_brain_init[pyvista]
```
and on `main` it's:
```
9.36s call     mne/viz/_brain/tests/test_brain.py::test_brain_init[pyvista]
```
So not a huge difference. Do you notice any timing difference locally @GuillaumeFavelier ? It might be the case that calling `._update()` multiple times does not have much effect on performance if VTK is smart about not bothering to re-render until actually needed. For example I just replaced a single call to `_update` in `set_time_point` to be:
```
        print('up')
        for _ in range(1000):
            self._renderer._update()
```
and I see "up" printed a bunch and get the same FPS in both cases -- it's low on my laptop, like 3, so if it's actually re-rendering each time it seems like it should drop to updating less than once a minute. So I'm not sure this will gain us too much?

On the other hand, if setting the camera forces a re-render somehow at the PyVista end (by doing a .Render call directly rather than plotter.update() maybe?) -- which seems possible since sometimes the brains switch views? Might also be worth checking the logic in their update method to understand things if you haven't already (I had a quick look and don't fully understand the logic):

https://github.com/pyvista/pyvista/blob/master/pyvista/plotting/plotting.py#L986-L1012

**Comment by GuillaumeFavelier** [comment]
Locally, the average of 10 calls for `test_brain_init`:

main | PR
--|--
7.79s | 7.71s

The impact is limited to say the least.

I won't lie, this `update` method is quite a mystery for me. I just assumed that in the case of `BackgroundPlotter` it was equivalent to calling `render()` since `force_redraw=True`. I will verify this.

**Comment by larsoner** [comment]
VTK might also be smart enough internally to figure out if anything in the scene has changed, so even if you `force_render` it might not actually do it. Not sure...

In any case, worth looking into!

**Comment by GuillaumeFavelier** [comment]
Because of the inheritance of `BackgroundPlotter`, this `udpate()` is the not the one we think...

```
In [9]: brain._renderer.plotter.update?
Docstring:
update(self)
update(self, QRect)
update(self, QRegion)
update(self, int, int, int, int)
Type:      builtin_function_or_method
```

It is probably a Qt or VTK function :sweat_smile:

**Comment by GuillaumeFavelier** [comment]
Sice this is clarified, I'll revert and I'll switch to the second part of the PR namely minimizing the number overlay updates.

There is not much I can do for the first part except maybe minimize the number of calls to `processEvents` and I doubt the effect will be so important.

**Comment by larsoner** [comment]
One thing I've noticed is slow is loading the window in the first place. I would start by making a script that just loads and closes maybe 10 times, `@profile` some functions, and `kernprof -lv python whatever.py` it and see what's actually eating all the time.

**Comment by GuillaumeFavelier** [comment]
The latest commit 8067b94 drastically improves the caching system of overlays:
* new partial update code to avoid iterating over all the overlays (basically, the cost of `set_time_point()` has decreased)
* no unnecessary full updates during overlay removal (this happened before in picking routines)
* the cache is updated only during full update or when a new overlay is added
I also updated the tests.

I think it can be improved further but a complexity analysis would probably be necessary to evaluate.

**Comment by GuillaumeFavelier** [comment]
So far, using `line_profiler` on `_plot_stc()`:
- `30%` by `brain = Brain()`
  - `60%` by `geo.load_geometry()`
  - `20%` by `self._setup_canonical_rotation()`
- `30%` by `brain.add_data()`
- `40%` by `brain.setup_time_viewer()`
  - `60%` by `self._configure_dock()`
    - `98%` by `self._configure_dock_trace_widget()`
      - `99%` by `_set_annot('None')`
  - `30%` by `self._renderer.show()`

**Comment by GuillaumeFavelier** [comment]
Yes, you are right it takes all the time

**Comment by GuillaumeFavelier** [comment]
So far, using `line_profiler` on `_plot_stc(show_traces=False)`:

- `42%` by `brain = Brain()`
- `40%` by `brain.add_data()`
- `12%` by `brain.setup_time_viewer()`

<details>
<summary>Script</summary>

```py
import os
import mne
from mne.datasets import sample

data_path = sample.data_path()
sample_dir = os.path.join(data_path, 'MEG', 'sample')
subjects_dir = os.path.join(data_path, 'subjects')
fname_stc = os.path.join(sample_dir, 'sample_audvis-meg')
stc = mne.read_source_estimate(fname_stc, subject='sample')
initial_time = 0.096

for i in range(10):
    brain = stc.plot(
        subjects_dir=subjects_dir, initial_time=initial_time,
        clim=dict(kind='value', lims=[3, 6, 9]),
        size=600,
        hemi='rh',
        show_traces=False,
        views=['lat', 'med'],
    )
    brain.close()
```

</details>

**Comment by GuillaumeFavelier** [comment]
So far, using `line_profiler` on `_plot_stc(time_viewer=False, show_traces=False)`:

- `45%` by `brain = Brain()`
- `45%` by `brain.add_data()`

<details>
<summary>Script</summary>

```py
import os
import mne
from mne.datasets import sample

data_path = sample.data_path()
sample_dir = os.path.join(data_path, 'MEG', 'sample')
subjects_dir = os.path.join(data_path, 'subjects')
fname_stc = os.path.join(sample_dir, 'sample_audvis-meg')
stc = mne.read_source_estimate(fname_stc, subject='sample')
initial_time = 0.096

for i in range(10):
    brain = stc.plot(
        subjects_dir=subjects_dir, initial_time=initial_time,
        clim=dict(kind='value', lims=[3, 6, 9]),
        size=600,
        hemi='rh',
        time_viewer=False,
        show_traces=False,
        views=['lat', 'med'],
    )
    brain.close()
```

</details>

**Comment by GuillaumeFavelier** [comment]
After 0a31936, the average of 3 x 10 runs:

master | PR
--|--
22.6s | 19.3s

**Comment by GuillaumeFavelier** [comment]
Same observation as https://github.com/mne-tools/mne-python/pull/9407#issuecomment-845193301, interfacing with `matplotlib` seems costly. I tried to keep updates minimal at least at init but now the path forward becomes blurry.

What I can say is that any significant improvement to `load_geometry()`, `_hemi_morph()` or `vertex_to_mni()` should benefit `Brain`'s loading time.

**Comment by GuillaumeFavelier** [comment]
This PR is ready for reviews on my end @larsoner

**Comment by larsoner** [comment]
`main` I get 20.0, this branch I get 17.9, with my commit (speeding up `vertex_to_mni`) I get 16.9 sec. I say we merge this and tackle the morphing separately. I'll fix the MFF problem on `main` first, then restart CIs, then let's merge!

**Comment by larsoner** [comment]
@GuillaumeFavelier I pushed a commit that uses `reset_camera=False` and `update=False` to avoid some costly `camera.reset()` and `process_events` calls, can you take a look and re-benchmark at your end? Once CIs come back green if you're happy with my changes and resulting benchmark options, feel free to merge

**Comment by larsoner** [comment]
(my changes optimize `load_geometry()`, `_hemi_morph()`, and `vertex_to_mni()` to the extent I found possible BTW)

**Comment by GuillaumeFavelier** [comment]
After 0a31936, the average of 3 x 10 runs:

master | PR
--|--
22.6s | 15s 

It feels way better in my opinion so I am happy with those changes :)

The failure of `compat / minimal / py3.7` seems legit though.

**Comment by GuillaumeFavelier** [comment]
Probably `test_scale_mri` and `test_volume_source_space` could use `requires_nibabel`

**Comment by larsoner** [comment]
Thanks @GuillaumeFavelier !

**Comment by larsoner** [comment]
A couple of nice things testing-wise, on another PR that ran recently we had:
```
515.01s total  mne/viz/_brain/tests/
...
25.19s call     mne/viz/_brain/tests/test_brain.py::test_brain_traces[pyvista-mixed-split]
```
and on the last run for this PR it was:
```
426.48s total  mne/viz/_brain/tests/
...
17.86s call     mne/viz/_brain/tests/test_brain.py::test_brain_traces[pyvista-mixed-split]
```

**Pull request merged**
