### PR TITLE
MRG: Fix epochs type in reference

### PR DESCRIPTION
**Pull request by jona-sassenhagen**
3 lines!!

### CODE REVIEW

**Comment by agramfort** [comment]
travis is not happy :(

**Comment by jona-sassenhagen** [comment]
@agramfort Merge or should I add a test?

**Comment by agramfort** [comment]
thanks @jona-sassenhagen

**Comment by jona-sassenhagen** [comment]
There are three or so other cases like ```isinstance(inst, Epochs)```. I can make a PR for that later.

**Pull request merged**
