### PR TITLE
MRG, BUG: Avoid referencing all data

### LINKED ISSUE #6454: BUG: ecog re-reference applied to non-data channels
I'm trying my hand applying mne to some ecog data and noticed a weird-ish bug using `.set_eeg_reference` which perhaps I had no business using to begin with. I set a custom reference using 
```
good_inds = mne.pick_types(raw.info, ecog=True)
goodchs = [raw.ch_names[g] for g in good_inds]
raw.set_eeg_reference(ref_channels=goodchs)
```
I noticed after doing this that while the reference was successful, my trigger channel had some weird changes to it which suggests that the reference is being applied to non-data channels as well.

This seems to happen in the [_apply_reference](https://github.com/mne-tools/mne-python/blob/569924b3ddcca4245725930ebca243ef213b31ee/mne/io/reference.py#L98) function which searches for eeg channels to apply the reference to and comes up with an empty list. Then in L136 the pick_channels takes the empty list and returns ALL channels instead of none of them. 

Moral of the story: I expected the reference to apply only to the ecog channels but instead it was applied to all channels. I can see a couple of solutions to this. 
1. An error at the beginning of set_eeg_reference if there are no EEG channels. Is there an ECoG reference function I'm unaware of? Should I just be doing this by hand?
2. A more general function `set_reference()` which handles EEG as well as ECoG data more flexibly. Perhaps defaulting to common average reference for ecog grids and bipolar references for seeg electrodes as suggested in #5081

### PR DESCRIPTION
**Pull request by larsoner**
Closes #6454.

@kdoelling1919 can you confirm this at least prevents the dangerous behavior you observed?

### CODE REVIEW

**Comment by agramfort** [comment]
@kdoelling1919 shall we wait for your feedback here?

**Comment by kdoelling1919** [comment]
I can confirm that this does what is intended on my end: itputs up an error rather than re-referencing all channels. I would prefer it to re-reference just the ecog channels though. I could implement that change sometime this week if you agree.

**Comment by larsoner** [comment]
If we expect EEG/ECoG/sEEG to never exist in the same dataset, we can just change the `pick_types` calls to have `seeg=True, ecog=True` in them.

The safer route would be to add a `ch_type='auto'` arg to `set_eeg_reference`, that you can then set to `'eeg'`, `'seeg'` or `'ecog'`. The default `auto` would search to see if `eeg`, then `seeg`, then `ecog` are present and adds a ref to whichever it finds first (erroring if it finds none). This API would "just work" for you with no new `kwargs`, but also be safe to use if there are ever multiple EEG-like chs present.

**Comment by agramfort** [comment]
+1 for ch_type='auto'

maybe in another PR?

**Comment by larsoner** [comment]
Yeah another PR would be better

**Comment by agramfort** [comment]
thx @larsoner and @kdoelling1919 for the bug report

**Pull request merged**
