### PR TITLE
Use latest version 0.23.1 of pyvista instead of master

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR updates the package requirements for the pyvista 3d backend.

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
Azure strikes back.

**Comment by GuillaumeFavelier** [comment]
Anyway, because we use the `interactor` directly in:

https://github.com/mne-tools/mne-python/blob/master/mne/viz/_brain/_timeviewer.py#L213

It's not possible to use `0.23.1`. I'll tag the next release.

**Comment by GuillaumeFavelier** [comment]
Following my concerns on https://github.com/pyvista/pyvista/pull/603#issuecomment-586140576 I think is top priority now.

**Comment by GuillaumeFavelier** [comment]
Of course, I plan to inform the users of `_TimeViewer` that `pyvista 0.23.1` is now the recommended version. Overall, I think it's a better practice to avoid using `master` and ensure stability.

**Comment by GuillaumeFavelier** [comment]
@larsoner  the issues on Circle are not related and the figures are duplicated as reported in https://github.com/mne-tools/mne-python/issues/7228

Example: https://17989-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/source-modeling/plot_visualize_stc.html#sphx-glr-auto-tutorials-source-modeling-plot-visualize-stc-py

**Comment by larsoner** [comment]
Agreed we should not use `master` if possible. PyVista releases fairly frequently so hopefully we don't have to wait too long to merge your future PRs that use new features.

**Comment by larsoner** [comment]
I noticed during some testing that it took a long time (e.g., at least 10 sec) for a PyVista window to appear at one point. And now I'm noticing some very long test times for the PyVista runs:

https://travis-ci.org/mne-tools/mne-python/jobs/650898534?utm_medium=notification&utm_source=github_status

I think that this is because 0.23.1 has depth peeling enabled by default, which means that 1) rendering is slower, and 2) even opening a window calls `check_depth_peeling` which is slow. On my laptop when I ctrl-C'ed during the slow startup it was checking depth peeling I think.

So I think we might want to revert this until they release their next version that has https://github.com/pyvista/pyvista/pull/618 incorporated.

I'll try opening a PR to revert this change, and if it runs significantly faster I'll merge. I think this is part of what is breaking things like https://travis-ci.org/mne-tools/mne-python/jobs/650898535?utm_medium=notification&utm_source=github_status hitting a timeout

**Pull request merged**
