### PR TITLE
[MRG+2] Add save method for EpochsTFR.

### PR DESCRIPTION
**Pull request by jaeilepp**
Closes https://github.com/mne-tools/mne-python/issues/3810

### CODE REVIEW

**Comment by agramfort** [comment]
LGTM

don't forget to update what's new

**Comment by jona-sassenhagen** [comment]
Thanks @jaeilepp !

**Comment by Eric89GXL** [comment]
+1 for merge from me, as well (just please update whats_new as @agramfort suggests)

**Comment by jaeilepp** [comment]
> just please update whats_new as @agramfort suggests

It's been done already. See if it's good enough.

**Comment by agramfort** [comment]
thx @jaeilepp

**Pull request merged**
