### PR TITLE
MRG: Add Epochs metadata to Report

### PR DESCRIPTION
**Pull request by hoechenberger**
This PR adds support for Epochs metadata to `mne.Report`.

- Table can be sorted in ascending/descending order based on any column
- Table can be filtered with free-form text input
- Alternative "card" view provides a "long" format and is great on devices with a smaller screen
- Invidiual columns can be hidden or shown
- Individual rows can be copied to the clipboard
- <strike>The first column (epoch number) is frozen while scrolling right</strike>
- CSV export

https://user-images.githubusercontent.com/2046265/147859070-2c952e07-5eef-42f3-bf48-c5f007a869e8.mov

I'm using [bootstrap-table](https://bootstrap-table.com) which is very much alive and actively maintained.

HTML Tables are generated via Pandas and post-hoc modified to make them work with `bootstrap-tables`.

Icons are provided via [bootstrap-icons](https://icons.getbootstrap.com). I created a small script that takes as input an original `bootstrap-icons` CSS and font and embeds the `base64`-encoded font in the CSS. This makes embedding into the report easier and saves space (we're only shipping a single font instead of multiple fonts and SVGs, as are included in the full `bootstrap-icons` distribution).

When activating the search box, global keyboard shortcuts (`T` for showing / hiding all content) are disabled; when leaving the box, keyboard shortcuts are enabled again.

cc @cbrnr @drammock @wmvanvliet @larsoner

### CODE REVIEW

**Comment by hoechenberger** [comment]
Rendered tutorial: https://40096-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/intro/70_report.html#adding-epochs

**Comment by hoechenberger** [comment]
CI error seems to be unrelated.

**Comment by agramfort** [comment]
@GuillaumeFavelier for the CI issue it seems related to pyvista : https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=17372&view=logs&j=305851a9-a7bb-55db-0042-7e2b6f48aa1c&t=77eb5bf7-3205-5b54-06c6-183c8195d846

can you have a look? 🙏

**Comment by agramfort** [comment]
a not so critical UI glitch when the browser window is large enough:

Screenshot 2022-01-02 at 11 09 14

**Comment by hoechenberger** [comment]
> a not so critical UI glitch when the browser window is large enough:

Ouch, this is ugly, I will have to look into this

**Comment by hoechenberger** [comment]
@agramfort I cannot seem to reproduce this, which browser is this and what screen resolution / browser window size? Do you need to perform some interactions first for this problem to occur? Thanks

**Comment by agramfort** [comment]
it's with safari on my MBP 16"

**Comment by hoechenberger** [comment]
> it's with safari on my MBP 16"

Thanks! And it happens right after viewing the report? Not interactions (scrolling etc)?

**Comment by agramfort** [comment]
yes no interaction needed

**Comment by agramfort** [comment]
pb disappears when I reduce the width of the window

**Comment by hoechenberger** [comment]
@agramfort I've pushed a (temporary?) change to disable the fixed `Epochs #` column – I think the problem is related to that. Can you please give it another shot and see if this fixes the issue for you?

For reference, this seems to be an upstream bug, which I can reproduce using the MWE provided here:
https://live.bootstrap-table.com/example/extensions/fixed-columns.html

**Comment by agramfort** [comment]
indeed problem solved !

**Comment by hoechenberger** [comment]
@agramfort Thanks!

I've removed everything related to freezing the columns now. This feature can added again later if the problem gets resolved upstream.

Otherwise, this is all good to merge from my end.

**Comment by hoechenberger** [comment]
I've created an upstream bug report: https://github.com/wenzhixin/bootstrap-table/issues/6014

**Review by agramfort — APPROVED** [review]
LGTM

🙏 @hoechenberger

**Comment by agramfort** [comment]
thx @hoechenberger

**Pull request merged**
