### PR TITLE
Fix couple of PEP8 errors.

### PR DESCRIPTION
**Pull request by ktavabi**
#### What does this implement/fix?
Couple minor PEP8 errors.

### CODE REVIEW

**Comment by agramfort** [comment]
pep8 is checked by our CI so technically it should be already fine...

**Comment by larsoner** [comment]
I see these in my local editor, too, though the automated checkers don't see them. Must not be strict enough!

**Comment by agramfort** [comment]
@ktavabi can you rebase to make CIs green?

**Comment by larsoner** [comment]
I restarted the CIs

**Comment by larsoner** [comment]
Thanks @ktavabi

**Pull request merged**
