### PR TITLE
[MRG] Adjust sEEG plotting

### LINKED ISSUE #4912: Improve sEEG visualization when plotting
The following code moocs a raw object to contain `sEEG` data, plots it and generate the figure below:

```py
def get_seeg_dummy_data(n_seeg_channels=5):
    from mne.datasets.testing import data_path
    from mne.io import read_raw_fif
    import os.path as op

    data_dir = op.join(data_path(download=False), 'MEG', 'sample')
    fif_fname = op.join(data_dir, 'sample_audvis_trunc_raw.fif')
    raw = read_raw_fif(fif_fname, verbose=0)
    seeg_channels = dict(zip(raw.ch_names[-n_seeg_channels:],['seeg']*n_seeg_channels))
    raw.info['projs'] = []
    raw.set_channel_types(seeg_channels)

    return raw

xx = get_seeg_dummy_data()
xx.plot()
```
image

On it, the scale and the legend color of the signals seem off.

cc: @mathurinm, @makkostya, @annesodub

### PR DESCRIPTION
**Pull request by massich**
fixes #4912

### CODE REVIEW

**Comment by makkostya** [comment]
I took your code with fixed color and I adjusted the scale which also was in the issue. Now it looks like this:
example

How can I submit the changes?

**Comment by massich** [comment]
Thx @makkostya. Looks great!

You can bring your changes in 3 different manners (that I can think of) :
1 - Submit a PR yourself to mne-python and I'll close this one. 
2 - Submit a PR to my fork (preferably to my `color` branch )
3 - I give you rights to my fork and you can directly push to the branch.

**Comment by makkostya** [comment]
2 is ok for me

**Comment by massich** [comment]
This PR is ready for review. cc: @agramfort, @mathurinm

**Comment by agramfort** [comment]
travis is not happy

**Comment by massich** [comment]
Hopefully it will, now !

**Comment by agramfort** [comment]
thx @makkostya and @massich !

**Pull request merged**
