### PR TITLE
MRG: Expose drop log

### PR DESCRIPTION
**Pull request by larsoner**
When getting `None` as proj because all epochs are rejected, it's nice to have the option to see why (and pass the result to `plot_drop_log`).

### CODE REVIEW

**Comment by agramfort** [comment]
don't forget the versionadded + what's new udpate

**Comment by larsoner** [comment]
Yes I'm planning on this being 0.16, waiting for release

**Comment by larsoner** [comment]
Okay I added 0.15 because we're in a holding pattern anyway

**Comment by agramfort** [comment]
thx @larsoner

**Pull request merged**
