### PR TITLE
WIP:  FAQ

### PR DESCRIPTION
**Pull request by christianbrodbeck**
WIP to add a FAQ to the documentation, following up on https://github.com/mne-tools/mne-python/issues/1495 and https://github.com/mne-tools/mne-python/issues/1637. 
CC @agramfort @dengemann 

Is it possible to build the docs with Anaconda? I get 

```
$ make html
...
plotting plot_bem_contour_mri.py
//anaconda/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core.py:16674: ImportWarning: Not importing directory '//anaconda/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/locale': missing __init__.py
  import locale
This program needs access to the screen.
Please run with a Framework build of python, and only when you are
logged in on the main display of your Mac.
make: *** [html] Error 1
```

### CODE REVIEW

**Comment by Eric89GXL** [comment]
Cov PR is merged, so this could be resumed. @christianbrodbeck do you have time to work on it and get it merged? Or @dengemann did you want to open a PR into his branch to add your covariance info? Maybe a stub is sufficient for now so this PR doesn't have to sit idle.

**Comment by christianbrodbeck** [comment]
@Eric89GXL @dengemann I don't understand the new methods well enough to write about them, but if you want to provide me with the content I will integrate it (you're of course also welcome to take over the PR)

**Comment by dengemann** [comment]
Hello folks. I'm taking over. I just can't do it now. See my comments on #1728 btw.

**Comment by Eric89GXL** [comment]
@dengemann now that you're done defending I assume you have time to take this over? :)

**Comment by Eric89GXL** [comment]
ping @dengemann do you have time in the next few days to take this over and finish it (with #1637 and #1728 and parts of #1495)?

**Comment by dengemann** [comment]
@Eric89GXL I might have time for this yes. I'm a bit reluctant, because it seems the full list of recommendations is not yet complete. But maybe incremental is better than nothing.

**Comment by Eric89GXL** [comment]
yeah i think so, users just need help getting going, we can always revise later

**Comment by Eric89GXL** [comment]
@dengemann has taken over, closing

**Pull request closed without merging**
