### PR TITLE
Allow toggling of DC removal in Raw.plot

### PR DESCRIPTION
**Pull request by cbrnr**
This PR adds the option to change the value of `remove_dc` in `mne.io.Raw.plot` so users can change this on the fly by pressing the 'd' key.

### CODE REVIEW

**Comment by agramfort** [comment]
works for me. you should be able to update a test

**Comment by cbrnr** [comment]
You mean add the 'd' key to these lines:

https://github.com/mne-tools/mne-python/blob/1532f98616ec875a2414b2631b0b8f7bc5e4b693/mne/viz/tests/test_raw.py#L185-L192

To which `for`-loop should I add it? And is this test sufficient (if nothing happens upon a keypress this test also works, e.g. by supplying a key which is not mapped)?

**Comment by agramfort** [comment]
yes

>

**Comment by cbrnr** [comment]
OK, but do I add the new 'd' key to the first, the second, or both for-loops?

**Comment by larsoner** [comment]
If you coudl add a comment that the first loop is over ` group_by='original'` and the second over `group_by='selection'` it will help the next dev understand why there are two (I had to look a bit to figure it out). So let's add to both

**Comment by cbrnr** [comment]
Done and ready.

**Comment by cbrnr** [comment]
AppVeyor and Azure have failed due to timeouts, but I can't restart these jobs.

**Comment by larsoner** [comment]
You need to sign up for an Azure account and tell me which email you used

**Comment by larsoner** [comment]
Thanks @cbrnr

**Pull request merged**
