### PR TITLE
MRG: Better warning for PyCUDA failure

### PR DESCRIPTION
**Pull request by Eric89GXL**
@kambysese can you see what error message you get for PyCUDA on this branch? Hopefully we can work through it here and improve the CUDA docs.

### CODE REVIEW

**Comment by kambysese** [comment]
No change in error message, is it odd that `_mnefun` is being referenced?

> Device does not appear to support 64-bit FFTs, CUDA not enabled:
> 
> CUDA not used, CUDA could not be initialized, falling back to n_jobs=1
> /home/ktavabi/Projects/mnefun/mnefun/_mnefun.py:1707: RuntimeWarning: Device does not appear to support 64-bit FFTs, CUDA not enabled:
> 
>   fir_window=fir_window)

**Comment by Eric89GXL** [comment]
@kambysese if you look closely that error message is different from what you reported before, look at the wording. It's supposed to give the error message emitted by PyCUDA, which apparently is an empty string. I'll have to modify it to give a more complete traceback, then. In the meantime, you could try running some PyCUDA tests -- you can try looking at their docs to see how to do it. They presumably give some way to validate the install.

**Comment by kambysese** [comment]
My confusion was if this is a CUDA or PyCuda related issue, and that change did me no good. FYI tests for pycuda under Anaconda don't seem to be as straightforward as [this](https://wiki.tiker.net/PyCuda/Installation/Linux). 
As I said, last system update fukcd my CUDA installation sideways. Trying `apt-get install pycuda` made situation worse by introducing broken held packages; by a stroke of luck `aptitute install cuda` managed to put things in order. `deviceQuery` returns working 7.5 CUDA drivers with Nvidia driver 352.63 on Ubuntu 14.04.  `aptitute` had several complaints about the 340 Nvidia driver.
I also upgraded to most recent version of pycuda via `pip`. In hindsight the message _CUDA not enabled_ is identifying actual problem in both versions of the RT warning. looking forward to next round of updates!

**Comment by Eric89GXL** [comment]
@kambysese can you try it now? I made it so it should print something more like this:
```
Device does not appear to support 64-bit FFTs, CUDA not enabled:
>   File "/home/larsoner/custombuilds/scikit-cuda/skcuda/cufft.py", line 111, in cufftCheckStatus
>     raise cufftExceptions[status]
> 
> cufftInvalidValue
```

**Comment by Eric89GXL** [comment]
Ready for review/merge from my end

**Comment by kambysese** [comment]
The message I get is "RuntimeWarning: module pycuda not found, CUDA not enabled fir_windows=fir_windows" followed by more information "...CUDA could not be initialized, falling back to n_jobs=1". I am pretty sure this has to do with PyCuda somehow being hidden from python env in the pycharm IDE when unattached to a shell environment. Otherwise diffs LGTM.

**Comment by Eric89GXL** [comment]
Can you paste the full traceback?

**Comment by kambysese** [comment]
There is no traceback just RT warning and program continues.

------------------------------------------------------------
Kambiz Tavabi PhD
Institute for Learning & Brain Sciences
1715 Columbia Road N
Portage Bay Building
Box 357988
University of Washington
Seattle, WA 98195-7988
Tel: 206-685-6173
------------------------------------------------------------

**Comment by Eric89GXL** [comment]
I mean full warning. You said "followed by more information", do you mean it wasn't part of the warning? It should have had some lines prefixed by `>` at the very least.

**Comment by kambysese** [comment]
The warning:

> ...Projects/mnefun/mnefun/_mnefun.py:1707: RuntimeWarning: module pycuda not found, CUDA not enabled fir_window=fir_window)

The logger information:

> module pycuda not found, CUDA not enabled
> CUDA not used, CUDA could not be initialized, falling back to n_jobs=1

I am on your `cuda-err` branch commit ead7a26 and current upstream of mnefun commit 14fd478.

**Comment by Eric89GXL** [comment]
So your system is now broken in a different / worse way... before you had failures of "Device does not appear to support 64-bit FFTs, CUDA not enabled" which means PyCUDA and scikits-cuda could be imported but not used properly, but now you get the error "module pycuda not found" which means you can't even do `import pycuda.autoinit`.

**Comment by kambysese** [comment]
Not exactly. System is fixed now, from above (edited):

> last system update broke CUDA installation. Tried `apt-get install pycuda` based on RunTime Warning and ran into broken packages issues. Tried `aptitute install cuda` which managed to put things in order. Running CUDA `deviceQuery` returned working 7.5 CUDA drivers with Nvidia driver 352.63. Of note aptitute had several complaints about the 340 Nvidia driver. I also upgraded to most recent version of pycuda via `pip`.

At present I think this warning is a fluke related to python IDE running detached from active shell console i.e., python doesn't have access to environment variables and (my guess is) PATH var(s) are not being properly set up. I opened an issue with JetBrains to see if they can provide any more info.

**Comment by Eric89GXL** [comment]
@agramfort this one should be good to go

**Pull request merged**
