### PR TITLE
MRG, ENH: Return flats with find_bad_channels_maxwell

### PR DESCRIPTION
**Pull request by larsoner**
@hoechenberger feel free to try.

Should be in 0.20 to make it within-cycle API change.

### CODE REVIEW

**Comment by agramfort** [comment]
to me flats are part of bads so it's weird to return 2 items one being called bads and the other one flats.

**Comment by larsoner** [comment]
I think it's useful to have them split and it's super easy for users to do `bads + flats` (we do this in the example) so I don't see harm in splitting them. However, combining them makes it so that you can't for example keep track as easily how often a given channel was bad vs flat in a large dataset without parsing logs (which is annoying to do)

**Comment by hoechenberger** [comment]
> I think it's useful to have them split and it's super easy for users to do `bads + flats` (we do this in the example) so I don't see harm in splitting them.

I generally agree, because at a certain level, they are conceptually different things:
`flats` is for _lack of variability_, while `bads` is for _too much variability_.

But I'm not happy with the nomenclature. To me, a "bad" channel is one that's problematic and should be removed before conducting further analysis. This is also how this term is used in MNE: we only have `.info['bads']`, but no `.info['flats']`. (Which I think is good) Not, typically, we need to remove both channels that are producing noise only, and those that produce pretty much no signal at all (i.e. are flat).

Maybe the return values of `find_bad_channels_maxwell` shouldn't be called `bads, flats`, but sth like `fluctuating_chs, flat_chs` instead?

**Comment by larsoner** [comment]
How about `outliers`, `flats`?

**Comment by larsoner** [comment]
Or `noisy`, `flat`?

**Comment by hoechenberger** [comment]
I thougt about `noise, flat` first, but we'd need to use plural forms to be consistent with the "MNE naming scheme", and `noisies, flats` sounds a bit weird I believe… `outliers, flats` could work... 
How about `noisy_chs, flat_chs`..?

**Comment by hoechenberger** [comment]
`irregulars, flats`? `deviants, flats`?

**Comment by hoechenberger** [comment]
`eccentrics, flats` :D

**Comment by drammock** [comment]
+1 for `noisy_chs`, `flat_chs`

**Comment by larsoner** [comment]
Pushed commit with `noisy_chs, flat_chs`

**Comment by hoechenberger** [comment]
@larsoner LGTM!

**Comment by hoechenberger** [comment]
Hehe, great timing @agramfort!

**Comment by hoechenberger** [comment]
Seems Travis is having big trouble these days, currently cannot even access the test results. I believe the macOS Test simply timed out, though...

**Comment by agramfort** [comment]
they are under maintenance

>

**Comment by hoechenberger** [comment]
Let's wait until this afternoon and see if they get things sorted out… Otherwise I'd be inclined to just merge: I remember seeing that only the macOS test hadn't started yesterday, and the others had successfully finished.

**Comment by drammock** [comment]
Yesterday I restarted the Travis macos test twice for this PR, after 2 timeouts. +1 for merging without it.

**Comment by agramfort** [comment]
fair enough. thanks @larsoner !

**Pull request merged**
