### PR TITLE
WIP: Move NIRS tests to appropriate directory

### PR DESCRIPTION
**Pull request by rob-luke**
#### What does this implement/fix?
A few months back someone (@cbrnr?) pointed out that the NIRS tests were not located with their code files and suggested we move them. I finally got around to it.

#### Additional information
Happy to leave as is too.

### CODE REVIEW

**Comment by cbrnr** [comment]
Any idea what's up with the failing Travis job?

**Comment by larsoner** [comment]
https://github.com/numpy/numpy/issues/17761 workaround in https://github.com/mne-tools/mne-python/pull/8495

**Comment by rob-luke** [comment]
Rebased, lets see if that fixes it.

**Comment by cbrnr** [comment]
Thanks @rob-luke!

**Pull request merged**
