### PR TITLE
Allow plotting Cz

### LINKED ISSUE #4649: BUG: Plotting Cz fails
With my current setup, plotting a sensor at 0, 0, 0 (e.g., Cz) fails because Numpy returns `False` for an array of all-zeros.

```
~/tools/mne-python/mne/viz/topomap.py in _prepare_topomap(pos, ax)
   1972     _hide_frame(ax)
   1973     if any([not pos_y.any(), not pos_x.any()]):
-> 1974         raise RuntimeError('No position information found, cannot compute '
   1975                            'geometries for topomap.')
   1976     return pos_x, pos_y

RuntimeError: No position information found, cannot compute geometries for topomap.
```

I'll try to take care of it.

### PR DESCRIPTION
**Pull request by jona-sassenhagen**
See #4649

@larsoner , I've picked a hopefully less invasive way of going about it.

Still, eventually missing channel positions should become NaNs.

Closes #4649

### CODE REVIEW

**Comment by jona-sassenhagen** [comment]
@larsoner no test required?

**Comment by agramfort** [comment]
test?

**Comment by jona-sassenhagen** [comment]
Are you saying we need a test, or that we don't need a test?

**Comment by agramfort** [comment]
we need a test ideally... if not tell me why It's not needed :)

**Comment by jona-sassenhagen** [comment]
Oh sure, I'll do a test.

**Comment by larsoner** [comment]
Thanks @jona-sassenhagen

**Comment by jona-sassenhagen** [comment]
Thanks guys.

**Pull request merged**
