### PR TITLE
DOC: updated the migrating.rst 

### PR DESCRIPTION
**Pull request by apoorva6262**
I made a new branch and deleted the earlier one as I was having some conflict issues. I have made the edits to the migrating.rst file that @larsoner mentioned regarding deleting the filter cell. (There were two filter cells with the same content, I took out one).  The table should look fine now.

### CODE REVIEW

**Comment by drammock** [comment]
it looks like the changes from #9158 didn't make it in here (I only see one commit and it doesn't modify the table)

**Comment by drammock** [comment]
OK, I've cherry-picked those changes and removed the duplicate row.

**Review by drammock — APPROVED** [review]

**Comment by apoorva6262** [comment]
Thank you so much.

**Comment by drammock** [comment]
The relevant CIs are happy; merging.  Thanks @apoorva6262!

**Pull request merged**
