### PR TITLE
[WIP] Enhancement of iEEG datasets with a real-clinical seizure Ecog dataset

### PR DESCRIPTION
**Pull request by adam2392**
#### Reference issue
Addresses part of #9060 

In collaboration with @alexrockhill 

#### What does this implement/fix?
Implements a `mne.datasets.epilepsy` dataset directory for housing "clinically" relevant datasets. In this case, there is a subject ECoG that has a seizure midway. Adds `sub-pt01` from https://openneuro.org/datasets/ds003029.

Once this is added, then we can provide the dataset to @larsoner who can upload to OSF. Then a tutorial can be rendered showing e.g. the gamma band power during seizure onset.

#### Next Steps
In a next PR, we intend on demonstrating how to compute a linear dynamical system from this dataset.

#### Additional information
Waiting to add also a tutorial.

### CODE REVIEW

**Comment by alexrockhill** [comment]
If these were in `fif`, then the tutorial would be simplified as far as reading in channel locations etc. ...

**Comment by larsoner** [comment]
Yes also but I think there is value in going from the native format. People who collect the data will have to figure out how to manipulate their data, and it's nice to have the example show that part a bit.

**Comment by alexrockhill** [comment]
Like cross-reference how to load in brainvision files ;) I guess I'll write it keeping it in brainvision

It's just not very high-level because `mne-bids` isn't a dependency. Is that okay to add to have `mne-bids` parse the channel locations for you or no?

**Comment by larsoner** [comment]
> It's just not very high-level because mne-bids isn't a dependency.

I think it's okay to add it as a dependency just needed for the example (i.e., not a dependency for MNE-Python in environment.yml or requirements.txt) if it simplifies things. We just add it to `requirements_doc.txt` and I think CircleCI should even deal with it properly.

**Comment by adam2392** [comment]
@larsoner is the storage of this dataset as is what you need from us? https://www.dropbox.com/sh/bsufh5npukzqe59/AAC4G3RilD-sSA3jH1SL_qhpa?dl=0

Should I delete everything except the compressed file? Should I rename anything accordingly?

**Comment by larsoner** [comment]
I can upload `MNE-Clinical.zip` (probably after putting it in a `MNE-Clinical-data` dir and recompressing as `.tar.gz`) to OSF if that's what you need for the example

**Comment by adam2392** [comment]
> I can upload `MNE-Clinical.zip` (probably after putting it in a `MNE-Clinical-data` dir and recompressing as `.tar.gz`) to OSF if that's what you need for the example

I think this is almost ready: https://www.dropbox.com/sh/bsufh5npukzqe59/AAC4G3RilD-sSA3jH1SL_qhpa?dl=0

@alexrockhill working on some issues related to our alignment (these electrode coordinates might be crap :/) in https://github.com/mne-tools/mne-python/pull/9087, and afterwards we can upload.

That PR can be the main one to merge.

**Comment by alexrockhill** [comment]
Is this good to go then?

**Comment by adam2392** [comment]
@larsoner i just subbed in the final changes in the epilepsy dataset. Are you able to upload to osf now? 

Did you want us to rename this to like epilepsy-seizure? 

We were thinking we can add additional epilepsy datasets through openneuro in the future.

**Comment by larsoner** [comment]
URL: https://osf.io/z4epq/download?revision=1
MD5: ffb139174afa0f71ec98adbbb1729dea

**Comment by larsoner** [comment]
(renamed `MNE-epilepsy-ecog-data`)

**Comment by larsoner** [comment]
Closing in favor of #9087 where we'll update the paths, etc.

**Pull request closed without merging**
