### PR TITLE
MRG: Convert CTF STL

### PR DESCRIPTION
**Pull request by larsoner**
@agramfort I have no idea what CTF systems are like, so it would be good if there were some CTF person who could check. Or even better, if there is a CTF + MRI where the head is known to be against the helmet, we could actually use `plot_alignment` to check that the head is up against the helmet.

The STL file was in a weird orientation with no reference to sensor positions so [I had to manually correct for it](https://gist.github.com/larsoner/866ef22e15b6a8d09d7f7cdc32e756eb) basically by trying to get the sensors to be a uniform distance from the interior of the helmet. Resulting output:

EDIT: Updated

screenshot from 2018-10-10 11-59-02

### CODE REVIEW

**Comment by agramfort** [comment]
looks pretty good.

did you try with SPM CTF data?

**Comment by larsoner** [comment]
No, not at a good computer for that currently. I can look next week unless you beat me to it.

**Comment by larsoner** [comment]
This snippet:
```
import mne
from mayavi import mlab
data_path = mne.datasets.spm_face.data_path()
subjects_dir = data_path + '/subjects'
raw_fname = data_path + '/MEG/spm/SPM_CTF_MEG_example_faces%d_3D.ds'
raw = mne.io.read_raw_ctf(raw_fname % 1)  # Take first run
trans = data_path + '/MEG/spm/SPM_CTF_MEG_example_faces1_3D_raw-trans.fif'
bem = mne.read_bem_solution(
    data_path + '/subjects/spm/bem/spm-5120-5120-5120-bem-sol.fif')
mne.viz.plot_alignment(raw.info, subject='spm', subjects_dir=subjects_dir,
                       meg=['sensors', 'helmet'], bem=bem, trans=trans)
mlab.view(135, 90)
```
Yielded:

snapshot

So I adjusted my translation a bit to make the head centered front-to-back and about the same distance to the top (not necessarily correct!) and now we get:

snapshot2


It would be nice if we could get some CTF user to record three 1-sec datasets with head to the front, then back, then top...

**Comment by larsoner** [comment]
Okay I've added clipping in the `gist`, now for the code snippet above I get something nicer:

screenshot from 2018-10-10 11-59-02

We still don't know if this is 100% correct (could be off by some rotation or some mm) but it's probably good enough. Updated `plot_sensors.py` [here](https://9708-1301584-gh.circle-artifacts.com/0/html/auto_examples/visualization/plot_meg_sensors.html).

Ready for review/merge from my end.

**Comment by agramfort** [comment]
LGTM

thanks heaps @larsoner

**Pull request merged**
