### PR TITLE
MRG: Add decorator for MKL errors in tests

### PR DESCRIPTION
**Pull request by Eric89GXL**
@kingjr recently hit the dreaded MKL bug. The next time it happens, this can allow us to avoid holding up a PR.

### CODE REVIEW

**Comment by agramfort** [comment]
appveyor is not happy

**Comment by Eric89GXL** [comment]
Perfect, Travis actually failed with an MKL error, so I can use it now :)

**Comment by agramfort** [comment]
CIs are not happy

**Comment by agramfort** [comment]
ping us when CIs are back

**Comment by Eric89GXL** [comment]
They're back :)

**Pull request merged**
