### PR TITLE
MRG Update README.rst

### LINKED ISSUE #3092: Misleading install instructions
The website reads:

>If you don't have git installed, you can download a zip or tarball of the latest code: >https://github.com/mne-tools/mne-python/archives/master

But when you click on that link, it currently reads:
>There aren’t any uploads for this repository.

Perhaps that link should be changed to link to https://github.com/mne-tools/mne-python/archive/master.zip instead?

### PR DESCRIPTION
**Pull request by jona-sassenhagen**
closes #3092

### CODE REVIEW

**Comment by Eric89GXL** [comment]
Now that I think about it, it's a bit non-DRY to have these instructions and very similar ones in `getting_started.rst` (or now really `install_python.rst`). @agramfort WDYT about getting rid of the installation instructions in the README.rst and pointing people clearly to the installation instructions on the website instead?

**Comment by agramfort** [comment]
I like the readme as it's what you have if you just get the sources. It's
also what is used to make:

https://pypi.python.org/pypi/mne/0.11.0

**Comment by jona-sassenhagen** [comment]
@Eric89GXL maybe a major overhaul will be in order later, but for now, I think it's important to no longer have the misleading line on the very first page :)

**Comment by Eric89GXL** [comment]
Okay fine :)

**Comment by jona-sassenhagen** [comment]
MRG from my end unless you guys want to see anything else done.

**Comment by jona-sassenhagen** [comment]
Should there be an Anaconda/Enthought recommendation following the list of required python packages (Scipy, MPL etc)?

**Comment by Eric89GXL** [comment]
No, people should really use the manual to figure out installation. If you want, you could give a link to the "getting_started.html" page.

**Comment by Eric89GXL** [comment]
Thanks @jona-sassenhagen

**Pull request merged**
