### PR TITLE
Duration must also be in seconds for loading EEGLAB files

### PR DESCRIPTION
**Pull request by cbrnr**
EEGLAB stores event durations in samples, so we need to convert that to seconds.

### CODE REVIEW

**Comment by agramfort** [comment]
Is it always in samples ? Can you update a test?

**Comment by cbrnr** [comment]
I didn't find this documented anywhere, but I'd imagine that since onsets are in samples, durations should also be in samples. I'll update a test though.

**Comment by cbrnr** [comment]
I don't think we have a file with annotation durations not equal to zero... Any suggestions?

**Comment by larsoner** [comment]
Create one manually in EEGLAB, export, see if MNE reads it correctly. Either way, add values to the fake `.set` MAT files we construct in our EEGLAB tests somewhere that are the same as what `EEGLAB` gives (in samples or time in sec) then add a test that we read it properly (after any necessary fixes)

**Comment by cbrnr** [comment]
I created a new EEGLAB .set file from the existing `test_raw_onefile.set` using the EEGLAB GUI. I cropped it to 25s to make it smaller, which reduced the number of events to 16. Then I added an event duration of exactly 1 second to each of the 16 events, and this is what I test.

Can someone add the new file to the mne-testing-data repo? Cloning is so slow for me that I gave up after a while. I can send the file via email. Or maybe someone with push access can use the GitHub website functionality to add new files without cloning?

**Comment by cbrnr** [comment]
Yes, you have to update the hash. I'm not sure if version 0.61 is the correct one, because there is already a release for 0.61, but `version.txt` still contained 0.60. Maybe the version has to be changed to 0.62.

**Comment by agramfort** [comment]
@jona-sassenhagen can you have a look ? Thx

**Comment by massich** [comment]
@cbrnr 	I'm syncing the versions, etc I'll push in your PR

**Comment by jona-sassenhagen** [comment]
LGTM - although I could imagine a shorter test file would be preferable.

**Comment by massich** [comment]
This should make the CIs green. cc: @cbrnr

**Comment by cbrnr** [comment]
I could shorten the file even more, but then we'd have to go through updating the whole testing data repo again 😝...

**Comment by cbrnr** [comment]
Something's wrong with the new Azure CI... @larsoner can you take a look?

**Comment by massich** [comment]
@cbrnr, @jona-sassenhagen if we want to change the file, now is the time. Make the PR and I'll update it, it would take me no time. Just the time the CIs run.

**Comment by massich** [comment]
@cbrnr the failure seems like a carrera problem. One of the windows builds wants to delete a file, while its still open by the other build.

Restarting the single build would make it green, but I couldn't restart it. In this case if you don't want to update the test file, you could merge it with the failure. The rest is green.

**Comment by massich** [comment]
@larsoner can we get rights to restart jobs? Thx

**Comment by cbrnr** [comment]
Cropping the file more would take me some time because I'm currently on a machine that doesn't have MATLAB (and therefore EEGLAB). @jona-sassenhagen?

**Comment by jona-sassenhagen** [comment]
I‘m on a train ... maybe I’m too anal here, is the file even that big?

**Comment by cbrnr** [comment]
The file is 0.5MB right now (because I've already cropped it).

**Comment by jona-sassenhagen** [comment]
Well cutting it to one channel and 2 seconds might in the long run save actual bandwidth and compute, right?

**Comment by larsoner** [comment]
>  can we get rights to restart jobs? Thx

Sign up for an Azure account and send me the email address you used

**Comment by cbrnr** [comment]
OK, I'll let you know when I'm done (might take a couple of days though).

**Comment by cbrnr** [comment]
Done, the test file is now 55kB. @massich could you please update the testing data repo so that the test will pass?

**Comment by jona-sassenhagen** [comment]
[Great, now I feel like Steve Jobs](https://www.folklore.org/StoryView.py?story=Saving_Lives.txt)

**Comment by larsoner** [comment]
Now you'll need to update `datasets/utils.py` to tell it to get version to `0.63` and update to the new hash

**Comment by cbrnr** [comment]
@massich could you update that please?

**Comment by massich** [comment]
Done

**Comment by massich** [comment]
Now everything should be green. And you can merge :)

**Comment by larsoner** [comment]
Thanks @cbrnr

**Comment by cbrnr** [comment]
Thanks @massich and everyone involved!

**Comment by jona-sassenhagen** [comment]
Thanks @cbrnr and @massich !

**Pull request merged**
