### PR TITLE
Remove need for `Union` and `Optional` type annotations in Python 3.9

### PR DESCRIPTION
**Pull request by hoechenberger**
Makes the existing annotations much cleaner and more readable.

### CODE REVIEW

**Review by cbrnr — APPROVED** [review]

**Comment by mscheltienne** [comment]
I think there is a ruff rule which does that? Maybe an UP one?

**Comment by hoechenberger** [comment]
Could be
But doesn't matter now that I changed it manually 😆

**Comment by cbrnr** [comment]
What's up with the pip pre Windows error?

**Comment by hoechenberger** [comment]
I just hope it's unrelated 🥸

**Comment by larsoner** [comment]
Marking for merge-when-green, thanks in advance @hoechenberger !

**Pull request merged**
