### PR TITLE
MRG: Add eLORETA

### LINKED ISSUE #4963: ENH: Add eLORETA
We have sLORETA but it would be nice to have eLORETA, too, see:

https://www.biorxiv.org/content/early/2018/02/22/269753

Anybody feel like digging into the math for this one?

### PR DESCRIPTION
**Pull request by larsoner**
Closes #4963.

Also includes some fixes/unifications for 3 plotting I hit while testing.

Todo:

- [x] add tests
- [x] deal with loose in docs or fix code
- [x] update `whats_new.rst`

### CODE REVIEW

**Comment by larsoner** [comment]
Updated API, hopefully sufficiently explains the options for using eLORETA:

https://7291-1301584-gh.circle-artifacts.com/0/tmp/circle-artifacts.bA2s3jk/html/generated/mne.minimum_norm.apply_inverse.html

Updated examples:

https://7291-1301584-gh.circle-artifacts.com/0/tmp/circle-artifacts.bA2s3jk/html/auto_tutorials/plot_mne_dspm_source_localization.html

https://7291-1301584-gh.circle-artifacts.com/0/tmp/circle-artifacts.bA2s3jk/html/auto_tutorials/plot_mne_solutions.html

Ready for review/merge from my end.

**Comment by jona-sassenhagen** [comment]
The 3d in-plot labels are broken on circle, correct?

**Comment by larsoner** [comment]
Yes, this is already happening on CircleCI independent of this PR and will be fixed when we fix #5015

**Comment by larsoner** [comment]
Slightly more readable versions after rebase, text sizes should be fixed by #5012:

https://7432-1301584-gh.circle-artifacts.com/0/HTML/html/auto_tutorials/plot_mne_dspm_source_localization.html

https://7432-1301584-gh.circle-artifacts.com/0/HTML/html/auto_tutorials/plot_mne_solutions.html

**Comment by agramfort** [comment]
@larsoner you need to rebase.

**Comment by larsoner** [comment]
Tests were passing and it's still reviewable in the meantime, nice try :)

>

**Comment by larsoner** [comment]
Rebased, rendered [updated example](https://7671-1301584-gh.circle-artifacts.com/0/html/auto_tutorials/plot_mne_dspm_source_localization.html) and [new example](https://7671-1301584-gh.circle-artifacts.com/0/html/auto_tutorials/plot_mne_solutions.html).

**Comment by larsoner** [comment]
CIs are happy, good to go for you @agramfort ?

**Comment by agramfort** [comment]
thanks @larsoner !

**Pull request merged**
