### PR TITLE
[MRG] Mention that bad channels are excluded for average reference

### PR DESCRIPTION
**Pull request by cbrnr**
I thought we could be a bit more verbose here...

### CODE REVIEW

**Comment by cbrnr** [comment]
Is `info['bads']` clear or should I write `raw.info['bads']` instead?

**Comment by larsoner** [comment]
info['bads'] is fine

**Comment by cbrnr** [comment]
Looking good, ready to merge.

**Comment by larsoner** [comment]
Thanks @cbrnr

**Pull request merged**
