### PR TITLE
WIP: refactoring of doc (switch to sphinx gallery)

### PR DESCRIPTION
**Pull request by agramfort**
so you know what I am up to...

### CODE REVIEW

**Comment by Eric89GXL** [comment]
SO MUCH RED

**Comment by agramfort** [comment]
pushed. Here is how it looks like now:

screen shot 2015-07-13 at 15 44 56

**Comment by agramfort** [comment]
what's broken now is mayavi support

**Comment by agramfort** [comment]
I am on it

**Comment by Eric89GXL** [comment]
I think we should update our logo to use a modern font. I'm partial to `OpenSans`. We can also use an image for the repo name in the upper-right like I did for `VisPy`, I think it's a nice touch. @agramfort I'm sure you don't mind making things prettier, right? :)

**Comment by Eric89GXL** [comment]
And the changes already look good

**Comment by agramfort** [comment]
don't try to read the diff. Just try to build the doc.

I am based on

https://github.com/sphinx-gallery/sphinx-gallery/pull/36

I'm about to add mayavi support to it

**Comment by Eric89GXL** [comment]
The diff actually isn't so bad, all the relevant changes are at the top, all the removes are at the bottom. Let me know when I should give it a build over here.

**Comment by agramfort** [comment]
use this branch to support mayavi

https://github.com/sphinx-gallery/sphinx-gallery/pull/42

**Comment by Eric89GXL** [comment]
Doc building seems slower now. Still okay, but slower.

**Comment by agramfort** [comment]
really?

**Comment by Eric89GXL** [comment]
Yeah it is slower on my system. Also `make html_dev-noplot` no longer works because `sphinx-gallery` assumes `doc/auto_examples/searchindex` exists and it does not.

**Comment by Eric89GXL** [comment]
(but I think that's an easy fix)

**Comment by Eric89GXL** [comment]
can you give me push access to your `sphinx-gallery` repo? I need to push at least one change

**Comment by agramfort** [comment]
I will review tomorrow morning

**Comment by agramfort** [comment]
Done

**Comment by Eric89GXL** [comment]
Why did you comment out the flow diagram, because we don't need to regenerate it very often?

**Comment by agramfort** [comment]
yes. And again someone could not build the doc because of pygraphviz...

**Comment by Eric89GXL** [comment]
I am going to work on this on and off over the next two days. If anyone else plans to work on it please make a note of it on `gitter` or here so we don't make conflicts @teonlamont @mainakjas @dengemann @agramfort

**Comment by Eric89GXL** [comment]
I am done editing for now, made some good progress on the cookbook. What do people think about merging this now, and iterating in `master`? +1 from my end, I think it will make things a bit easier.

**Comment by agramfort** [comment]
as discussed please revert the logo change, rebase and merge. We'll iterate
on master from now on.

thanks !

**Comment by Eric89GXL** [comment]
Will do shortly

**Pull request closed without merging**
