### PR TITLE
added functions to make random mne data objs

### PR DESCRIPTION
**Pull request by choldgraf**
This is a quick PR to add some helper functions for creating random data for testing etc. If it's not worth pulling then no worries, I've just found them useful for saving a few lines when quickly testing/debugging. Not sure if this is the kind of the thing we'd need to add tests for, but I'm happy to do so if people think the code is worth pulling.

### CODE REVIEW

**Comment by jasmainak** [comment]
Can you actually identify tests which might benefit from it? Go ahead and make the changes so we can see if it's actually helpful. The aim should be to save some lines (=more red lines) with this :)

**Comment by choldgraf** [comment]
Hmm, I'm looking through the test_epochs.py code, which I think is the place that a function like this might be most useful. There aren't a ton of places where EpochsArray is used with random data or zeros, which is the case where these kinds of functions might be useful. I forgot there were updates to the create_info function that makes it a bit easier to quickly generate info objects.

Basically it could be useful whenever people manually create "data" along with a custom info object and use EpochsArray to generate an epochs object. In test_epochs, that happens in lines 257, 1090, 1799, 1846, 1947.

But looking at the code, it's not really that clunky already, so maybe this is unnecessary.

**Comment by agramfort** [comment]
> maybe this is unnecessary.

my feeling ...

**Comment by choldgraf** [comment]
mmk, unless anybody dives in an proclaims their love for mne random object
functions, then I won't take this PR any further...

**Comment by jasmainak** [comment]
yeah, let's close ...

**Pull request closed without merging**
