### PR TITLE
[WIP] Real-time OpenBCI server

### PR DESCRIPTION
**Pull request by teonbrooks**
**this is very wip. Not ready for any review.**

Contributors are welcome. @trachelr, I created this branch so we could easily collaborate on this addition.

### CODE REVIEW

**Comment by trachelr** [comment]
Good one! I’m glad this branch is created… I’m on it during the weekend.
We finally managed to record good data at meiso (inside the cocon!!)
I’ll send you some figure, we observed very interesting heart rate patterns… 
Covariation with the band power feature is currently under investigation!
Good day!

**Comment by jasmainak** [comment]
@teonlamont : The real-time stuff needs some serious refactoring. There is tons of code duplication going on. Maybe we could have a `BaseClient` which implements some of the methods and the other clients inherit from them. Just throwing ideas

**Comment by trachelr** [comment]
@jasmainak +1, in particular the callback stuff could be shared.
Do you think we can use the function ‘start_streaming‘ from open_bci_v3 with a callback function?

**Comment by jasmainak** [comment]
Ah, I'm not sure about that. I'll have to play around with `OpenBCI` a bit. But also, I meant sharing `FieldTripClient` and `OpenBCIClient`. I see Teon has copied most of the code from there -- so this could definitely be refactored and improved.

**Comment by trachelr** [comment]
We did the copy/paste on purpose... as @teonlamont said it's very WIP
I'll be at la paillasse tomorrow afternoon for playing with an openBCI.
Join me if you have free time, I'll be glad to show you what we're doing in there!

**Comment by jasmainak** [comment]
is there a way to add tests here? I might be able to help you refactor if you can add tests.

**Comment by teonlamont** [comment]
there's a merge in here (c0c090a) that's no good for the history....I can try to fix it.

**Comment by trachelr** [comment]
@teonlamont oups... sorry!
you can go back to this commit.
It didn't change much before the last commit.
what do you suggest to fix that?

**Comment by teonlamont** [comment]
no worries, I fixed it, it just required a rebase to clear it up :)

**Comment by trachelr** [comment]
During the brain hack Paris, I discussed with robert about the redundancy between this PR and a recent openbci2ft driver in the field trip buffer... He told me that the python code provided by openbci looked quite messy for him, and would probably be less efficient that an implementation in C code. Therefore he decided to recode the driver himself and I did a pretty good job!
@agramfort what do you think about this PR. Should we try to enhance the python code (cf mne/externals/OpenBCI.py) and get rid of the field trip buffer dependency or keep the openbci2ft implementation and use it like that?

**Comment by agramfort** [comment]
no opinion. I don't understand the implications as I don't use this code myself

**Comment by teonlamont** [comment]
I think that the `openbci2ft` and the fieldtrip buffer would be the best option.

**Comment by trachelr** [comment]
+1 no need to reinvent the wheel.

**Comment by Eric89GXL** [comment]
@teonbrooks I'm moving this to 0.13, feel free to get it in for 0.12 if you have time

**Comment by Eric89GXL** [comment]
@teonbrooks should we close this, then?

**Comment by teonbrooks** [comment]
I'll close this for now.

**Pull request closed without merging**
