### PR TITLE
VIZ, FIX: make annotations immediately visible when scrolling via click on scrollbar

### LINKED ISSUE #8893: Clicking in overview bar does not draw annotations in raw.plot
If plotting a `Raw` object with annotations, these are not drawn in the main window when navigating through the data by clicking on the little overview bar. It's probably just an `update()` call that's missing. For a MWE, the example in from #8686 can be used. @drammock do you have time to look?

### PR DESCRIPTION
**Pull request by drammock**
closes #8893

### CODE REVIEW

**Review by larsoner — APPROVED** [review]
The elusive one-line fix!

**Comment by cbrnr** [comment]
I assume the failing tests are unrelated? Some of them are `raw.plot` tests though. Otherwise LGTM (tested and it works)!

**Review by cbrnr — APPROVED** [review]

**Comment by larsoner** [comment]
> I assume the failing tests are unrelated?

Yeah they are failing on every PR, and I checked that at least the number of failures is the same here as in other PRs for the linux pip build

**Comment by larsoner** [comment]
Thanks @drammock

**Comment by cbrnr** [comment]
Thanks @drammock - could you backport this PR?

**Pull request merged**
