### PR TITLE
Add fNIRS support to coregistration gui

### PR DESCRIPTION
**Pull request by rob-luke**
#### Reference issue
Replaces #10081 as I struggled with the git merge.

Conversation started over in https://github.com/mne-tools/mne-nirs/issues/419 and specifically this comment from @larsoner https://github.com/mne-tools/mne-nirs/issues/419#issuecomment-985239162 

However, when I ran the coreg guy with fNIRS data no sensors were displayed.

#### What does this implement/fix?
Enables plotting of fNIRS sources and detectors in the coreg gui

### CODE REVIEW

**Comment by rob-luke** [comment]
@larsoner @GuillaumeFavelier @agramfort this is ready for review

**Comment by agramfort** [comment]
diff looks simple and clean. I'll let @GuillaumeFavelier approve first

**Review by GuillaumeFavelier — APPROVED** [review]
LGTM as the follow-up PR of #10081

**Comment by agramfort** [comment]
merge if happy

>

**Comment by GuillaumeFavelier** [comment]
Thank you @rob-luke !

**Pull request merged**
