### PR TITLE
[MRG] Fix raw.plot_psd reject_by_annotation=False

### LINKED ISSUE #4784: raw.plot_psd(reject_by_annotation=False) crashes
When I run `raw.plot_psd(reject_by_annotation=False)` on a `raw` object containing annotations, I get the following error:

```
/usr/local/lib/python3.6/site-packages/mne/io/base.py in get_data(self, picks, start, stop, reject_by_annotation, return_times)
    890             data, times = self[picks, start:stop]
    891             return (data, times) if return_times else data
--> 892         if reject_by_annotation.lower() not in ['omit', 'nan']:
    893             raise ValueError("reject_by_annotation must be None, 'omit' or "
    894                              "'NaN'. Got %s." % reject_by_annotation)

AttributeError: 'bool' object has no attribute 'lower'
```

The problem is [here](https://github.com/mne-tools/mne-python/blob/master/mne/time_frequency/psd.py#L55):

    rba = 'NaN' if reject_by_annotation else reject_by_annotation

If `reject_by_annotation` is `False`, it remains `False`, but afterwards the string method is called on this `bool` object and fails.

### PR DESCRIPTION
**Pull request by cbrnr**
Fix #4784

### CODE REVIEW

**Comment by agramfort** [comment]
@cbrnr you need to fix conflict on what's new.

any chance to modify one of our tests?

**Comment by mmagnuski** [comment]
test would be good, other than that I'm also :+1:

**Comment by cbrnr** [comment]
I've added a smoke test, I think this should be sufficient without further checks.

**Comment by larsoner** [comment]
Thanks @cbrnr

**Pull request merged**
