### PR TITLE
fix trace offsets in butterfly mode

### LINKED ISSUE #10083: Vertical placement of channel traces seems off in raw butterfly plot
MWE:
```python
# %%
from pathlib import Path
import mne
import numpy as np


sample_dir = Path(mne.datasets.sample.data_path())
sample_fname = sample_dir / 'MEG' / 'sample' / 'sample_audvis_raw.fif'
raw = mne.io.read_raw_fif(sample_fname, preload=True)

# %%

fig = (
    raw.copy()
       .pick_types(eeg=True, eog=True, stim=True)
       .plot(butterfly=True, show_scrollbars=False, start=0,
             duration=1, show=False)
)
```
output

It appears as if the stim channel has a lot of signals, and the EOG channel were flat.

However, the following code reveals that this ain't so:
```python
# %%
fig = (
    raw.copy()
       .pick_types(stim=True)
       .plot(butterfly=True, show_scrollbars=False, start=0,
             duration=1, show=False)
)
```
output

```python
# %%
fig = (
    raw.copy()
       .pick_types(eog=True)
       .plot(butterfly=True, show_scrollbars=False, start=0,
             duration=1, show=False)
)
```
output

cc @drammock

### PR DESCRIPTION
**Pull request by drammock**
closes #10083

### CODE REVIEW

**Review by hoechenberger — APPROVED** [review]
Perfect, this works for me!

Can you add a changelog entry please?

**Review by larsoner — APPROVED** [review]
LGTM +1 for merge, whoever sees green first feel free to click the button

**Comment by larsoner** [comment]
@drammock it looks like this [broke circleci](https://app.circleci.com/pipelines/github/mne-tools/mne-python/11824/workflows/0dccbe06-081a-4391-bab2-6d893dd58104/jobs/39386):
```
Traceback (most recent call last):
  File "/home/circleci/project/tutorials/epochs/20_visualize_epochs.py", line 79, in <module>
    epochs['face'].plot(events=catch_trials_and_buttonpresses, event_id=event_dict,
  File "/home/circleci/project/mne/epochs.py", line 1136, in plot
    return plot_epochs(self, picks=picks, scalings=scalings,
  File "/home/circleci/project/mne/viz/epochs.py", line 915, in plot_epochs
    fig._draw_traces()
  File "/home/circleci/project/mne/viz/_mpl_figure.py", line 1721, in _draw_traces
    offsets = self.mne.trace_offsets[offset_ixs]
IndexError: index 364 is out of bounds for axis 0 with size 364
```

**Comment by drammock** [comment]
on it.

**Pull request merged**
