### PR TITLE
MRG: Add time player for the notebook backend

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR adds a "player" controller for the time slider with play, pause, stop and rewind. It also reorders the controllers for a cleaner UI.

image

It's part of #7162

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
I noticed incompatibilities between the orientation controller and the general camera settings. I will take care of that in another PR.

**Comment by agramfort** [comment]
works like a charm on my machine

**Comment by GuillaumeFavelier** [comment]
The warnings on Circle don't seem related to this PR:

<details>

```
/home/circleci/project/mne/cov.py:docstring of mne.Covariance.clear:: WARNING: py:class reference target not found: None.  Remove all items from D.

/home/circleci/project/mne/cov.py:docstring of mne.Covariance.items:: WARNING: py:class reference target not found: a set-like object providing a view on D's items

/home/circleci/project/mne/cov.py:docstring of mne.Covariance.keys:: WARNING: py:class reference target not found: a set-like object providing a view on D's keys

/home/circleci/project/mne/cov.py:docstring of mne.Covariance.pop:: WARNING: py:class reference target not found: v, remove specified key and return the corresponding value.

/home/circleci/project/mne/cov.py:docstring of mne.Covariance.update:: WARNING: py:class reference target not found: None.  Update D from dict/iterable E and F.

/home/circleci/project/mne/cov.py:docstring of mne.Covariance.values:: WARNING: py:class reference target not found: an object providing a view on D's values

/home/circleci/project/mne/forward/forward.py:docstring of mne.Forward.clear:: WARNING: py:class reference target not found: None.  Remove all items from D.

/home/circleci/project/mne/forward/forward.py:docstring of mne.Forward.items:: WARNING: py:class reference target not found: a set-like object providing a view on D's items

/home/circleci/project/mne/forward/forward.py:docstring of mne.Forward.keys:: WARNING: py:class reference target not found: a set-like object providing a view on D's keys

/home/circleci/project/mne/forward/forward.py:docstring of mne.Forward.pop:: WARNING: py:class reference target not found: v, remove specified key and return the corresponding value.

/home/circleci/project/mne/forward/forward.py:docstring of mne.Forward.update:: WARNING: py:class reference target not found: None.  Update D from dict/iterable E and F.

/home/circleci/project/mne/forward/forward.py:docstring of mne.Forward.values:: WARNING: py:class reference target not found: an object providing a view on D's values

/home/circleci/project/mne/io/meas_info.py:docstring of mne.Info.clear:: WARNING: py:class reference target not found: None.  Remove all items from D.

/home/circleci/project/mne/io/meas_info.py:docstring of mne.Info.items:: WARNING: py:class reference target not found: a set-like object providing a view on D's items

/home/circleci/project/mne/io/meas_info.py:docstring of mne.Info.keys:: WARNING: py:class reference target not found: a set-like object providing a view on D's keys

/home/circleci/project/mne/io/meas_info.py:docstring of mne.Info.pop:: WARNING: py:class reference target not found: v, remove specified key and return the corresponding value.

/home/circleci/project/mne/io/meas_info.py:docstring of mne.Info.update:: WARNING: py:class reference target not found: None.  Update D from dict/iterable E and F.

/home/circleci/project/mne/io/meas_info.py:docstring of mne.Info.values:: WARNING: py:class reference target not found: an object providing a view on D's values

/home/circleci/project/mne/io/proj.py:docstring of mne.Projection.clear:: WARNING: py:class reference target not found: None.  Remove all items from D.

/home/circleci/project/mne/io/proj.py:docstring of mne.Projection.copy:: WARNING: py:class reference target not found: a shallow copy of D

/home/circleci/project/mne/io/proj.py:docstring of mne.Projection.items:: WARNING: py:class reference target not found: a set-like object providing a view on D's items

/home/circleci/project/mne/io/proj.py:docstring of mne.Projection.keys:: WARNING: py:class reference target not found: a set-like object providing a view on D's keys

/home/circleci/project/mne/io/proj.py:docstring of mne.Projection.pop:: WARNING: py:class reference target not found: v, remove specified key and return the corresponding value.

/home/circleci/project/mne/io/proj.py:docstring of mne.Projection.update:: WARNING: py:class reference target not found: None.  Update D from dict/iterable E and F.

/home/circleci/project/mne/io/proj.py:docstring of mne.Projection.values:: WARNING: py:class reference target not found: an object providing a view on D's values

/home/circleci/project/mne/beamformer/_compute_beamformer.py:docstring of mne.beamformer.Beamformer.clear:: WARNING: py:class reference target not found: None.  Remove all items from D.

/home/circleci/project/mne/beamformer/_compute_beamformer.py:docstring of mne.beamformer.Beamformer.items:: WARNING: py:class reference target not found: a set-like object providing a view on D's items

/home/circleci/project/mne/beamformer/_compute_beamformer.py:docstring of mne.beamformer.Beamformer.keys:: WARNING: py:class reference target not found: a set-like object providing a view on D's keys

/home/circleci/project/mne/beamformer/_compute_beamformer.py:docstring of mne.beamformer.Beamformer.pop:: WARNING: py:class reference target not found: v, remove specified key and return the corresponding value.

/home/circleci/project/mne/beamformer/_compute_beamformer.py:docstring of mne.beamformer.Beamformer.update:: WARNING: py:class reference target not found: None.  Update D from dict/iterable E and F.

/home/circleci/project/mne/beamformer/_compute_beamformer.py:docstring of mne.beamformer.Beamformer.values:: WARNING: py:class reference target not found: an object providing a view on D's values

/home/circleci/project/mne/bem.py:docstring of mne.bem.ConductorModel.clear:: WARNING: py:class reference target not found: None.  Remove all items from D.

/home/circleci/project/mne/bem.py:docstring of mne.bem.ConductorModel.items:: WARNING: py:class reference target not found: a set-like object providing a view on D's items

/home/circleci/project/mne/bem.py:docstring of mne.bem.ConductorModel.keys:: WARNING: py:class reference target not found: a set-like object providing a view on D's keys

/home/circleci/project/mne/bem.py:docstring of mne.bem.ConductorModel.pop:: WARNING: py:class reference target not found: v, remove specified key and return the corresponding value.

/home/circleci/project/mne/bem.py:docstring of mne.bem.ConductorModel.update:: WARNING: py:class reference target not found: None.  Update D from dict/iterable E and F.

/home/circleci/project/mne/bem.py:docstring of mne.bem.ConductorModel.values:: WARNING: py:class reference target not found: an object providing a view on D's values

/home/circleci/project/mne/minimum_norm/inverse.py:docstring of mne.minimum_norm.InverseOperator.clear:: WARNING: py:class reference target not found: None.  Remove all items from D.

/home/circleci/project/mne/minimum_norm/inverse.py:docstring of mne.minimum_norm.InverseOperator.items:: WARNING: py:class reference target not found: a set-like object providing a view on D's items

/home/circleci/project/mne/minimum_norm/inverse.py:docstring of mne.minimum_norm.InverseOperator.keys:: WARNING: py:class reference target not found: a set-like object providing a view on D's keys

/home/circleci/project/mne/minimum_norm/inverse.py:docstring of mne.minimum_norm.InverseOperator.pop:: WARNING: py:class reference target not found: v, remove specified key and return the corresponding value.

/home/circleci/project/mne/minimum_norm/inverse.py:docstring of mne.minimum_norm.InverseOperator.update:: WARNING: py:class reference target not found: None.  Update D from dict/iterable E and F.

/home/circleci/project/mne/minimum_norm/inverse.py:docstring of mne.minimum_norm.InverseOperator.values:: WARNING: py:class reference target not found: an object providing a view on D's values

/home/circleci/project/mne/transforms.py:docstring of mne.transforms.Transform.clear:: WARNING: py:class reference target not found: None.  Remove all items from D.

/home/circleci/project/mne/transforms.py:docstring of mne.transforms.Transform.items:: WARNING: py:class reference target not found: a set-like object providing a view on D's items

/home/circleci/project/mne/transforms.py:docstring of mne.transforms.Transform.keys:: WARNING: py:class reference target not found: a set-like object providing a view on D's keys

/home/circleci/project/mne/transforms.py:docstring of mne.transforms.Transform.pop:: WARNING: py:class reference target not found: v, remove specified key and return the corresponding value.

/home/circleci/project/mne/transforms.py:docstring of mne.transforms.Transform.update:: WARNING: py:class reference target not found: None.  Update D from dict/iterable E and F.

/home/circleci/project/mne/transforms.py:docstring of mne.transforms.Transform.values:: WARNING: py:class reference target not found: an object providing a view on D's values
```


</details>

**Comment by larsoner** [comment]
I'll look into CircleCI

**Comment by GuillaumeFavelier** [comment]
I think this is ready to go now.

**Comment by agramfort** [comment]
works great !

to discuss (in a next PR if you want) is if it's wiser to specify time in ms and not in time index in the slider.

I would personally prefer to show time in ms

**Comment by larsoner** [comment]
> I would personally prefer to show time in ms

One problem is that a lot of times (cluster summary, custom STCs) milliseconds are not the units and don't really make sense. Time index is at least agnostic to this problem. In theory the `time_label` should be used because then the user has some control over how it gets labeled. Internally the code can use indices, and just make sure the slider gets labeled by the `time_label`-formatted value for example.

**Comment by agramfort** [comment]
ok fair enough. Let's postpone such discussion / improvements

+1 for merge

>

**Comment by larsoner** [comment]
Works great!

**Pull request merged**
