### PR TITLE
MRG, MNT: Migrate to nbclient for notebook testing

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
Checks that the CIs are green on Azure for the notebook 3d backend.

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
Now there is a warning on Azure for notebook testing:

```
FutureWarning: Method cleanup(connection_file=True) is deprecated, use cleanup_resources(restart=False).
```

**Comment by GuillaumeFavelier** [comment]
This is probably because of the new version of `jupyter_client`:

image

**Comment by GuillaumeFavelier** [comment]
Bumping `nbconvert` solved the warning but now `pytest-notebook` is [not ready for the change](https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=7866&view=logs&j=1d294aa9-8c9e-52da-e2cc-28ca059e1c9b&t=520de7d9-efc8-52cf-0de1-994cbfe115fe&l=63):

```
AttributeError: 'ExecuteCoveragePreprocessor' object has no attribute 'setup_preprocessor'
```

**Comment by GuillaumeFavelier** [comment]
Think it's fine since `nbconvert 6.0.0` is not officially released yet. We could probably ignore for now and report the change on [pytest-notebook](https://github.com/chrisjsewell/pytest-notebook) ?

**Comment by GuillaumeFavelier** [comment]
This is trickier than it seems. There is an API change in `nbconvert 6.0.0` leading to some part of the code to be split in `nbclient`.

**Comment by GuillaumeFavelier** [comment]
As we do not gather coverage informations from this notebook, I could consider migrating to `nbclient` instead.

**Comment by GuillaumeFavelier** [comment]
I reported the `FutureWarning` in https://github.com/jupyter/nbclient/issues/89.

For now, we can just pin `jupyter_client<6.1.5`.

**Comment by GuillaumeFavelier** [comment]
What do you think @agramfort, @larsoner ?

**Comment by agramfort** [comment]
I am confused. Why removing pytest-notebook?

**Comment by GuillaumeFavelier** [comment]
We don't use the coverage information and it's not ready yet for `nbconvert 6.0.0`.

**Comment by larsoner** [comment]
What do you mean we don't use it? It should be reported like all other runs (other than style)

**Comment by GuillaumeFavelier** [comment]
>  It should be reported like all other runs

I was not aware of that

**Comment by agramfort** [comment]
coverage report or execution? I can live without coverage but the notebook
definitely needs to be
executed by pytest

>

**Comment by GuillaumeFavelier** [comment]
`nbclient` executes the notebook `test.ipynb` in the `test_notebook_3d_backend()` function of the `test_notebook.py` file.

I'm now completely lost for coverage.

**Comment by agramfort** [comment]
if test.ipynb runs on CIs than I am happy

>

**Comment by larsoner** [comment]
> nbclient executes the notebook test.ipynb in the test_notebook_3d_backend() function of the test_notebook.py file.
>
> I'm now completely lost for coverage.

As long as it does this in the same Python process, I think `coverage` should work. And based on the coverage numbers for the notebook backend, it should be working.

https://codecov.io/gh/mne-tools/mne-python/src/master/mne/viz/backends/_notebook.py

**Comment by larsoner** [comment]
Closing in favor of #7943

**Pull request closed without merging**
