### PR TITLE
MRG+1, MINOR fix float xtick labels in plot_compare_evoked

### LINKED ISSUE #4948: Rounding bug in axis labels? Perhaps MPL?
As of recently, something is weirding up some of the axis labels - rounding messes with the formatting. It's not an MNE issue per se- maybe a matplotlib update? Anyone got an idea?

Before:
unknown-116
Now:
unknown-117

### PR DESCRIPTION
**Pull request by jona-sassenhagen**
I don't know why I originally put that line there?

Can we test what it outputs to the screen? I can't think of a test.

closes #4948

### CODE REVIEW

**Comment by larsoner** [comment]
This one would be a bit tricky to test, probably not worth it.

**Comment by jona-sassenhagen** [comment]
Is there a way I could check CircleCi outputs? I guess it won't re-render cause I didn't touch the files.

**Comment by larsoner** [comment]
I would just touch the files of interest in some way. There is always some typo or bad wording to fix.

**Comment by jona-sassenhagen** [comment]
https://7027-1301584-gh.circle-artifacts.com/0/tmp/circle-artifacts.dmjqMEA/html/auto_tutorials/plot_visualize_evoked.html

https://7027-1301584-gh.circle-artifacts.com/0/tmp/circle-artifacts.dmjqMEA/html/auto_examples/visualization/plot_roi_erpimage_by_rt.html

https://7027-1301584-gh.circle-artifacts.com/0/tmp/circle-artifacts.dmjqMEA/html/auto_examples/visualization/plot_channel_epochs_image.html

Renders look good. Good for merge on my end.

**Comment by larsoner** [comment]
@mmagnuski feel free to merge if you and Travis are happy

**Comment by larsoner** [comment]
Thanks @jona-sassenhagen

**Comment by jona-sassenhagen** [comment]
Thanks!

**Pull request merged**
