### PR TITLE
FIX: workaround MNE-C byteswapping bug

### PR DESCRIPTION
**Pull request by mluessi**
Workaround for #1823, so we can read raw files processed with MNE-C versions that had the byte swapping bug. 

Not sure what the best way is to test this..

### CODE REVIEW

**Comment by Eric89GXL** [comment]
LGTM. I'm not sure it's worth increasing test repo size to catch these lines, so I'm fine as-is assuming you tested the fix

**Comment by dengemann** [comment]
I agree with Eric, if this resolves the issue it's good to go!!

**Comment by agramfort** [comment]
thanks @mluessi !

**Comment by mluessi** [comment]
I had tested it by comparing the matrix from `test_raw.fif` and `sef_raw_sss.fif`. I also just tested the fix @mshamalainen implemented, works as well :)

**Pull request merged**
