### PR TITLE
MNT: GUI API

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR follows #10250 and refactors the GUI API, improve testing and overall consistency.

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
In another PR, I will add support for keyword-only argument by using the 'single star' syntax to indicate the end of positional parameters.

**Comment by GuillaumeFavelier** [comment]
This is ready for review @larsoner, @hoechenberger

**Review by hoechenberger — APPROVED** [review]
This is not changing the API per se, just passing all parameters by name now, right? 

In any case, looks good and much cleaner to me now! And is a required work when planning to switch to kw-only arguments anyway! 👍

**Comment by hoechenberger** [comment]
I'll let @larsoner merge if he's happy

**Comment by larsoner** [comment]
Thanks @GuillaumeFavelier !

**Pull request merged**
