### PR TITLE
Update institutions.png

### PR DESCRIPTION
**Pull request by britta-wstnr**
As discussed, update the logo banner with the Aarhus University logo.
@agramfort , cc @sarangnemo

### CODE REVIEW

**Comment by agramfort** [comment]
@britta-wstnr can you squeeze things a bit so the width of the image in pixels does not change?

I assume it will create css problem otherwise. @larsoner ?

**Comment by larsoner** [comment]
The CSS has it auto-scale to fit (at most) the width, so it should be okay. However, we now have so many that it might be worth going (back) to having two rows so that the scaling doesn't hit so early.

**Comment by agramfort** [comment]
still looks ok to me: https://7118-1301584-gh.circle-artifacts.com/0/tmp/circle-artifacts.RgIIFsF/html/index.html

@larsoner ok to merge?

**Comment by larsoner** [comment]
Sure, we can always make it 2 rows later

**Pull request merged**
