### PR TITLE
MRG: Less memory

### PR DESCRIPTION
**Pull request by Eric89GXL**
WIP to drop memory usage.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
So far I've gotten `plot_epochs_spectra.py`:

before

after

**Comment by Eric89GXL** [comment]
time_frequency/plot_compute_raw_data_spectrum.py:

before

after

**Comment by Eric89GXL** [comment]
preprocessing/plot_resample.py:

before


after

**Comment by Eric89GXL** [comment]
simulation/plot_simulate_raw_data.py:

before


after

**Comment by Eric89GXL** [comment]
stats/plot_linear_regression_raw.py:

before

after

**Comment by Eric89GXL** [comment]
forward/plot_source_space_morphing.py:

before


after

**Comment by Eric89GXL** [comment]
I'm going to stop now, ready for review/merge from my end.

**Comment by agramfort** [comment]
thx heaps @Eric89GXL

**Comment by jona-sassenhagen** [comment]
>stats/plot_linear_regression_raw.py:

Nice Eric!

**Pull request merged**
