### PR TITLE
allow grow_labels to use any surface

### PR DESCRIPTION
**Pull request by aestrivex**
Optionally use some other surface than the white surface in grow_labels(). Keep white as default.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
The surface argument should be moved to second-to-last (before `verbose`) to preserve backward compatibility in case people used args instead of kwargs in their calls.

Why do you need this? I thought that the vertices and connectivity of the white / spherical / pial etc. surfaces were conserved.

**Comment by aestrivex** [comment]
The application is to identify the labels which are contacted by invasive electrode leads. The connectivity is preserved across surfaces but the actual growing done based on distance can differ across different surface types. In this case the user adjusts the position of the electrode leads based on visualizing them on the pial surface, so it really is important to get the labels correct.

**Comment by Eric89GXL** [comment]
Ahh right, forgot it was based on distances, not on unit steps along the surface mesh. Take care of the argument order (which BTW is causing the testing errors) and we should be good.

**Comment by Eric89GXL** [comment]
Thanks for the enhancement!

**Comment by agramfort** [comment]
thanks @aestrivex 

next time run pep8 on your file :)

$ pep8 mne/label.py
mne/label.py:1328:77: W291 trailing whitespace
mne/label.py:1329:5: E125 continuation line with same indent as next logical line
mne/label.py:1329:5: E128 continuation line under-indented for visual indent

I am fixing it now in master.

**Comment by Eric89GXL** [comment]
@agramfort do you want me to add automated PEP8 checking? I've done it for several other repos, it's pretty easy.

**Comment by agramfort** [comment]
how?

**Comment by Eric89GXL** [comment]
Add a Travis run that executes flake8, or append it to the end of an
existing run.

**Comment by agramfort** [comment]
yes please do this.

**Pull request merged**
