### PR TITLE
ENH: addition of the argument show=True in viz functions when missing

### PR DESCRIPTION
**Pull request by cmoutard**
Reimplementing [#1968](https://github.com/mne-tools/mne-python/pull/1968) and generalizing to all viz functions when needed.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
I thought I saw another one missing recently and found it: https://github.com/mne-tools/mne-python/blob/master/mne/viz/topo.py#L236. Do you have time to look through all of our `viz` functions and add `show` arguments in the ones that don't have it?

**Comment by cmoutard** [comment]
Sure !

**Comment by Eric89GXL** [comment]
Great! FYI the viz functions that use `mayavi` (3D) instead of `matplotlib` probably will not have a similar argument, and it's okay to leave those alone.

**Comment by dengemann** [comment]
+1 for merge once @Eric89GXL  comment is addressed.

**Comment by Eric89GXL** [comment]
@cmoutard we're going to try and push the release out soon, so I'll take care of the remaining ones

**Comment by cmoutard** [comment]
Sorry, I was in the deep pampa the 2 last days. Targeting a release on Friday, I was thinking to finalize it tonight. Thanks @Eric89GXL for the caring !
PS : below is what I have done so far (just itemizing the functions) if this can help...

## _3d.py

* plot_evoked_field => mayavi
* plot_trans => mayavi
* plot_source_estimates => mayavi
* plot_sparse_source_estimates => show argument already implemented
* plot_dipoles => mayavi

## circle.py

* plot_connectivity_circle => show argument NOT implemented

## decoding.py

* plot_gat_matrix => show argument already implemented
* plot_gat_diagonal => show argument already implemented

## epochs.py

* plot_image_epochs => show argument already implemented
* plot_drop_log => show argument already implemented
* plot_epochs => show argument already implemented
* plot_epochs_psd => show argument NOT implemented

## evoked.py

* plot_evoked => show argument already implemented
* plot_evoked_image => show argument already implemented
* plot_evoked_white => show argument already implemented
* plot_snr_estimate => show argument already implemented

## ica.py

* plot_ica_sources => show argument already implemented
* plot_ica_scores => show argument already implemented
* plot_ica_overlay => show argument already implemented

## misc.py

* plot_cov => show argument already implemented
* plot_source_spectrogram => show argument already implemented
* plot_bem => show argument already implemented
* plot_events => show argument already implemented

## montage.py

* plot_montage => show argument NOT implemented

## raw.py

* plot_raw => show argument already implemented
* plot_raw_psd => show argument NOT implemented

## topo.py

* plot_topo => show argument NOT implemented
* plot_topo_image_epochs => show argument NOT implemented

## topomap.py

* plot_projs_topomap => show argument already implemented
* plot_topomap => show argument NOT implemented
* plot_ica_components => show argument already implemented
* plot_tfr_topomap => show argument already implemented
* plot_evoked_topomap => show argument already implemented
* plot_epochs_psd_topomap => show argument NOT implemented
* plot_psds_topomap => show argument NOT implemented

**Comment by Eric89GXL** [comment]
Is this update for latest master? I thought I got a lot of those in my follow-up PR.

**Comment by cmoutard** [comment]
Probably not, I have done this from the master I had on my laptop at that time (yesterday morning).

**Comment by agramfort** [comment]
check current master then. thx

**Comment by cmoutard** [comment]
So, after checking, it seems that all the viz functions do have now a show argument.
However, the show argument has not been implemented in some class functions calling these ones.
PR #2028 fix this.

**Pull request merged**
