### PR TITLE
FIX: Update EEGMI_URL

### PR DESCRIPTION
**Pull request by ragatti**
#### What does this implement/fix?
Update url link to dataset

### CODE REVIEW

**Comment by larsoner** [comment]
Could you update one (or preferably all) of:

- examples/decoding/plot_decoding_csp_eeg.py
- examples/decoding/plot_decoding_csp_timefreq.py
- examples/time_frequency/plot_time_frequency_erds.py
- tutorials/preprocessing/plot_40_artifact_correction_ica.py
- tutorials/source-modeling/plot_eeg_no_mri.py

Just make some tiny tweak to the wording, or even just some newline / word wrapping change. It will cause CircleCI to build these examples (only changed examples are built for PRs) and make sure things are working properly.

If it's not clear what I mean I can push a quick commit to do it.

**Comment by drammock** [comment]
@ragatti I've closed your other PRs; please make changes to the tutorials / examples *in this PR* so that the tutorials / examples get built *with the URL change you've done here* (so we can see that everything still works with the new URL).

**Comment by larsoner** [comment]
@ragatti can you add a quick entry to `changes/latest.inc` in the `BUG` section, and add your name to `changes/names.inc` so that you can get credit for these changes?

**Comment by ragatti** [comment]
Hi @larsoner, changes are ready. They are fine?

**Comment by larsoner** [comment]
Thanks @ragatti !

**Pull request merged**
