### PR TITLE
MRG: Improve docs

### PR DESCRIPTION
**Pull request by Eric89GXL**
I built the docs and got a bunch of warnings and errors. Working on fixing them.

### CODE REVIEW

**Comment by agramfort** [comment]
besides flake8 errors LGTM

when we setup the new nightly doc build we should receive the log by emails to stop the warnings when they appear.

thanks @Eric89GXL !

**Comment by Eric89GXL** [comment]
@agramfort I couldn't resist adding the `..versionadded` directive. I went through the current stable docs and compared to the current dev docs, then also used `whats_new` to fill it out. It renders as I hope that's okay.

**Comment by Eric89GXL** [comment]
It renders as "New in version 0.9.0.", that is.

**Comment by agramfort** [comment]
Looks good. Thanks @Eric89GXL 

please merge when Travis is happy

thx

**Comment by Eric89GXL** [comment]
FYI @teonlamont @mainakjas @dengemann @yousrabk we should from now on put `..versionadded` directives in our docstrings for new functions and parameters. I went back and did all the ones I could think of for 0.9, feel free to fill in the gaps if you notice any moving forward.

**Pull request merged**
