### PR TITLE
Fix docstrings

### PR DESCRIPTION
**Pull request by agramfort**
it just factorizes code for n_jobs, seed and random_state docstrings

### CODE REVIEW

**Comment by massich** [comment]
This `n_jobs` which ends up drving `n` in `_get_n_epochs` should be factorized aswell or not?
https://github.com/mne-tools/mne-python/blob/f4ff17015b4523675587f64cec94d8f5b783dc0b/mne/connectivity/effective.py#L89-L90
https://github.com/mne-tools/mne-python/blob/f4ff17015b4523675587f64cec94d8f5b783dc0b/mne/connectivity/spectral.py#L423-L434

**Comment by massich** [comment]
@larsoner what is the difference to decorate using `@verbose` or `@fill_doc`? 

I think we should add those things in the contributing guide. (or make developers guide with all those little things as a FAQ)

**Comment by larsoner** [comment]
@verbose does what @fill_doc does, plus controls the verbosity level. Use `verbose` if the function has a `verbose` arg and `fill_doc` if it does not

**Comment by drammock** [comment]
I was going to tackle this today after all the `RandomState` nonsense that got wrapped into the tutorials PR. Thanks @agramfort for the head start.  I pushed a fix for broken cross-refs (that were my fault anyway) and a fix for duplicate `random_state` defs in the docdict.

**Comment by drammock** [comment]
- [rendered example](https://13422-1301584-gh.circle-artifacts.com/0/dev/generated/mne.label.select_sources.html#mne.label.select_sources) of the new `random_state` template
- [rendered example](https://13422-1301584-gh.circle-artifacts.com/0/dev/generated/mne.simulation.add_eog.html#mne.simulation.add_eog) of same, but with additional info tacked on.

**Comment by agramfort** [comment]
thx @massich

**Comment by massich** [comment]
I've 2 commits that didn't go in (I could not understand why they were breaking). I'll contribute them in a separate PR.

**Pull request merged**
