### PR TITLE
More website fixes

### PR DESCRIPTION
**Pull request by drammock**
This PR:

1. removes some cruft files that were no longer used (e.g., `doc/_static/copybutton.js` superseded by `sphinx-copybutton` dependency)
2. refactors/simplfies our template files to take advantage of some new theme features
3. updates the version switcher slightly to make it easier for touchscreens (rectangular hit area instead of just the text)
4. tweaks the homepage gallery to address @larsoner's wish that the funders be more prominent (not offscreen at loadtime on a 1080p screen) --- this includes removing some excess whitespace in our main homepage logo SVG
5. updates one institution logo
6. tiny wording change on the funders page

marking as draft because there are some questions about the latest theme version causing big slowdowns with the rendering process (https://github.com/pydata/pydata-sphinx-theme/issues/381), and I want to see how bad they are for us before moving forward.

### CODE REVIEW

**Comment by drammock** [comment]
Here is the updated homepage, for reference: https://27181-1301584-gh.circle-artifacts.com/0/dev/index.html

The size / alignment of the gallery images could use some tweaking.  @larsoner feel free to push commits here if you want to experiment with getting the homepage the way you like it.

**Comment by agramfort** [comment]
you have a glitch in the footer

>

**Comment by hoechenberger** [comment]
Can we move the `Quick Start >` button above the `Funders`?

**Comment by drammock** [comment]
> you have a glitch in the footer

fixed: https://27238-1301584-gh.circle-artifacts.com/0/dev/index.html

> Can we move the `Quick start >` button above the `Funders`?

not easily, I'm afraid.

There is also now a second blocker (besides slower build time) that is keeping this as a draft PR: https://github.com/pydata/pydata-sphinx-theme/issues/383

**Comment by cbrnr** [comment]
I mentioned this in #9289 but it belongs here: the TOC in the right column is broken, at least in https://27238-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/io/plot_20_reading_eeg_data.html - clicking on the various TOC entries highlights different sections.

**Comment by drammock** [comment]
> I mentioned this in #9289 but it belongs here: the TOC in the right column is broken

upstream issue: https://github.com/pydata/pydata-sphinx-theme/issues/389

**Comment by jorisvandenbossche** [comment]
It seems to be the sphinx-gallery css that conflicts with the theme's css. Removing the rule for `.sphx-glr-example-title > :target::before`, it seems to behave correctly.

**Comment by drammock** [comment]
Thanks @jorisvandenbossche!  I've followed up over at https://github.com/pydata/pydata-sphinx-theme/issues/389

**Review by larsoner — APPROVED** [review]
@drammock I think the spacing bug should be fixed by a recent SG PR, feel free to merge if you're happy with this

**Pull request merged**
