### PR TITLE
MRG+2: Use Hamming window for psd_welch (and document it)

### LINKED ISSUE #4454: Add window argument to psd_welch?
I was wondering if a new `window` argument might be useful for the `mne.time_frequency.psd_welch` function, where the user can specify the window type (now the SciPy default is used, which corresponds to a Tukey 0.25 window). I usually use a Hamming or Hanning window, not because I know they work better but just out of habit. For reference, MATLAB uses a Hamming window by default for its [`pwelch` function](https://www.mathworks.com/help/signal/ref/pwelch.html).

### PR DESCRIPTION
**Pull request by cbrnr**
Fix #4454

### CODE REVIEW

**Comment by cbrnr** [comment]
As expected, the differences between Hann (previous default) and Hamming (new default) are extremely minor. Here are the PSDs for the sample data.

Hann:
figure_hann

Hamming:
figure_hamming

For all practical purposes, I think it is safe to switch to Hamming windowing for consistency with MATLAB.

**Comment by cbrnr** [comment]
Could someone please restart the two failed Travis jobs (the errors seem to be unrelated)?

**Comment by larsoner** [comment]
Travis should be fixed by #4485, which I just merged -- restarting builds now

**Comment by larsoner** [comment]
LGTM +1 for merge after `whats_new.rst` update in API sectoin (I don't think `hann` vs `hamming` will be worth a parameter or deprecation cycle but we should still document the change)

**Comment by agramfort** [comment]
+1 for MRG when Travis is happy

**Comment by larsoner** [comment]
Thanks @cbrnr

**Pull request merged**
