### PR TITLE
[BUG, MRG] Fix topomap extra plot generated, add util to check a range

### PR DESCRIPTION
**Pull request by alexrockhill**
Fixes the extra topomap plot and adds a check range function so that they can be used in the separate repo version of https://github.com/mne-tools/mne-python/pull/11352.

### CODE REVIEW

**Comment by alexrockhill** [comment]
Ah shoot, my bad, fixing now

**Review by drammock — COMMENTED** [review]
why the addition of `_check_range` here?  In the diff it's only being used in a test, which seems to be unrelated to the principal change (a change from `plt.subplots_adjust` to `Figure.subplots_adjust`)

**Comment by alexrockhill** [comment]
They're both things necessary for the GUI code. They could be in two separate PRs, they are unrelated but since the `_check_range` is just a utility, I thought I'd just stick in here.

**Comment by larsoner** [comment]
Thanks @alexrockhill !

**Pull request merged**
