### PR TITLE
FIX: coreg spin box calling set_parameter twice

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR is extracted from #10224:

* fixes the spin box "double call"

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
Maybe there is simpler... This is only what I suggest and tested locally :sweat_smile:

**Comment by GuillaumeFavelier** [comment]
What do you think @larsoner ?

**Comment by larsoner** [comment]
Why is this necessary? On `main` if I add a `print(f'set {value} {mode_name} {coord}')` as the first line in `_set_parameter_safe`, I already only get one value change per click I think (note that the "trans not shown at start" bug is still present on `main`):

```
$ mne coreg -s sample -d subjects -f MEG/sample/sample_audvis_raw.fif --trans MEG/sample/sample_audvis_raw-trans.fif
```


https://user-images.githubusercontent.com/2365790/151190271-2e399633-e970-476a-a01b-b8e2794bc79d.mp4




What I don't like is that the *display* seems to update twice, which I assume has to do with an errant `update=True` somewhere or something...

**Comment by GuillaumeFavelier** [comment]
You do not have this behaviour... Is it only me then?

**main**

https://user-images.githubusercontent.com/18143289/151191083-133b5537-572b-4d06-a8d4-233fc4a88f25.mp4

**PR**  

https://user-images.githubusercontent.com/18143289/151191116-96f97a30-2dd0-4839-8d08-82cb98162730.mp4

**Comment by larsoner** [comment]
Oh you said in #10244

> I tried using Qt.ConnectionType.QueuedConnection with PyQt5 5.15.6 but it still did not fix the issue locally.

It's too bad this didn't work :(

**Comment by GuillaumeFavelier** [comment]
I am using `PyQt5 5.15.6`:

```
❯ python -c "import mne; mne.sys_info()"
Platform:       Linux-4.19.223-1-MANJARO-x86_64-with-glibc2.17
Python:         3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0]
Executable:     /home/guillaume/source/anaconda3/envs/mne-py38/bin/python
CPU:            : 4 cores
Memory:         7.7 GB

mne:            1.0.dev0
numpy:          1.22.0 {}
scipy:          1.7.1
matplotlib:     3.5.1 {backend=QtAgg}

sklearn:        1.0
numba:          Not found
nibabel:        3.2.1
nilearn:        0.8.1
dipy:           1.4.1
cupy:           Not found
pandas:         1.3.3
pyvista:        0.32.0 {OpenGL 4.5.0 NVIDIA 495.44 via NVIDIA GeForce GTX 960M/PCIe/SSE2}
pyvistaqt:      0.8.dev0
ipyvtklink:     0.2.1
vtk:            9.1.0
PyQt5:          5.15.6
ipympl:         Not found
mne_qt_browser: Not found
pooch:          v1.5.2
```

I tried connecting the spin boxes with `QueuedConnection` [two days ago](https://github.com/mne-tools/mne-python/pull/10224#issuecomment-1020328391) but it did not solve the issue.

**Comment by larsoner** [comment]
Every time we parallelize something we make debugging harder, but this seems to be a real bug on your system at least so I guess we have to live with the complexity. Feel free to merge if it does fix things for you @GuillaumeFavelier , I at least notice no change in behavior (in a good way) on my system.

**Comment by GuillaumeFavelier** [comment]
Okay, but the other PRs have higher priority. Now that I know that this could be related to my system, I think I'll hold on a bit before merging.

I can try:
- [ ] a fresh new `conda` env
- [ ] a different version of `PyQt5`
- [ ] a different OS (on the same system)

**Comment by larsoner** [comment]
If you hit the bug, and it's a known behavior of Qt under some circumstances (based on the threads), it's at least somewhat likely some user will have this problem. We don't want to make them mess with Qt installs as a fix...

**Comment by hoechenberger** [comment]
Amazing detective work, @GuillaumeFavelier!

**Pull request merged**
