### PR TITLE
Added check to make sure pick_channels only accepts a list/tuple

### LINKED ISSUE #2371: Should pick_channels throw an error if you give a string?
I say this because it seems to assume that you're passing it an iterable, so if you pass a string then it will break it up into individual letters, which accidentally caused some problems for me earlier.

Another strange behavior is that it will not throw an error if you supply incorrect channel names, so long as at least one of the channel names supplied does match.

E.g., two examples of strangeness:

1. If my actual channel names are ['G1', 'G2', 'G3'] and I supply ['G1', 'MNERULES', 'YESITDOES'] as the channels, then it simply ignores the last two values and returns a `Raw` object with only 'G1' pulled out.

2. If my actual channels names are ['1', '2', '3'] and I supply 'ISTHISA2CHANNELNAME' to pick_channels (note it's a string not a list), then it will silently return a Raw copy with '2' as the picked channel.

It seems like one, or both, of these behaviors is undesirable, no?

### PR DESCRIPTION
**Pull request by choldgraf**
Should fix #2371

### CODE REVIEW

**Comment by Eric89GXL** [comment]
Maybe also `ndarray`? Some people might be using those.

**Comment by choldgraf** [comment]
good point

**Comment by choldgraf** [comment]
Hmm so this was breaking some tests where a string was supplied to this function. Instead of throwing an error, I could make it so that if a string is passed, then it converts it to a list of length 1. I think then the behavior is what you'd expect.

**Comment by Eric89GXL** [comment]
That seems fine. We do that in other places, too, I think.

**Comment by choldgraf** [comment]
Whoops...this got closed somehow. Does it auto-close a PR if you reset my repository's branch?

**Comment by mainakjas** [comment]
you could have simply reopened this PR instead of opening a new PR ...

**Pull request closed without merging**
