### PR TITLE
[DOC] Docstring for annotations.

### PR DESCRIPTION
**Pull request by jaeilepp**
Closes https://github.com/mne-tools/mne-python/issues/3468.

### CODE REVIEW

**Comment by agramfort** [comment]
does 

make test-doc

pass for you?

**Comment by mmagnuski** [comment]
docstring testing fails because mne is not imported (and raw is not defined) - maybe this should be a short example instead?

**Comment by Eric89GXL** [comment]
I think it should be in the function docstring. Just add the proper doctest
skip commands.

**Comment by jaeilepp** [comment]
Done.

**Comment by agramfort** [comment]
Thanks

**Pull request merged**
