### PR TITLE
Fixed the time indexing bug with to_data_frame

### PR DESCRIPTION
**Pull request by choldgraf**
I think that the bug reported on the listserv is fixed. In classy fashion, by implementing the "ToDataFrameMixin" base class, I also managed to undo the fix that led me to create the Mixin in the first place. I think that I've fixed it now, take a look and let me know if all looks well.

### CODE REVIEW

**Comment by dengemann** [comment]
@choldgraf does this solve our problem?

**Comment by choldgraf** [comment]
I recreated the bug that the person was speaking of, and then these changes
fixed it. Also wrote in a test to make sure it was working for raw arrays.

**Comment by Eric89GXL** [comment]
I think what you meant to say was "I created a test that failed and then fixed it with my changes", so we can claim a test-driven-development victory here :)

**Comment by Eric89GXL** [comment]
Do you think we should also check other objects? I can't remember how the branching works, but e.g. `SourceEstimate` might have a different flow...?

**Comment by choldgraf** [comment]
So basically the error was that we had this big object-dependent split at
the beginning, and in that split I was adding ('time', times) to the
multiindex. Then, later on, I was doing the times scaling and then
rounding, but only to the "times" object. So it didn't actually affect what
was already in the multiindex tuple. As a result, the index wasn't scaled,
so when it got rounded everything went to 0.

I removed all of the multi-index stuff until after the big split, and then
included the scaling / rounding correction as well as appending to
multiindex afterward. I can't remember if SourceEstimate would have a
problem with this - doesn't it use time as well, just has a different
configuration of columns?

**Comment by Eric89GXL** [comment]
Yeah it does, it's just that how you get the time information would be different (tmin / tstep as opposed to `sfreq`). But it from your response it's clear that this actually gets rid of some branching, which is great, and answers my question.

Thanks for the quick fix!

**Comment by agramfort** [comment]
thx

**Comment by Eric89GXL** [comment]
dang @agramfort beat me to it :)

**Comment by choldgraf** [comment]
Oops - it looks like I missed something. One line is duplicated (177 and
188)

**Comment by Eric89GXL** [comment]
Ahh, couldn't see that in the GitHub diff. I'll fix it in `master`. I should just be able to delete the second one, right?

**Comment by choldgraf** [comment]
Yeah, the one that's not paired with the "add to multiindex" line

**Pull request merged**
