### PR TITLE
MRG: Add support for hemi=split in time_viewer

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR starts the work on `hemi=split`. Let's go incrementally on this one. For now I put all the controls on the first view.

Using `plot_visualize_stc.py` with `hemi=split`:

2020-01-16_1920x1080

The zoom between the views is not linked, that would be nice to have I think.

**ToDo**
- [x] Unify `show_view()` when `hemi=split` or when `len(views)>1`
- [x] Fix playback when `len(views)>1`
- [x] Fix default orientation value

It's an item of #7162

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
Sadly with `hemi=split` and `views=['lat', 'med']`:

2020-01-16_1920x1080

**Comment by agramfort** [comment]
any idea what's going on?

>

**Comment by GuillaumeFavelier** [comment]
I'm not sure but it could be related to https://github.com/pyvista/pyvista/issues/513

**Comment by GuillaumeFavelier** [comment]
Or anyway I think we should wait for this issue to be solved in order to have full control on the sliders position between the views.

**Comment by larsoner** [comment]
Agreed

**Comment by GuillaumeFavelier** [comment]
Locally, following https://github.com/pyvista/pyvista/issues/513#issuecomment-575161649 method, I managed to retrieve them:

2020-01-16_1920x1080

I can try to patch in `_TimeViewer` while waiting on a decision upstream.

*Note: the views are not correct still but this is a different bug**

**Comment by GuillaumeFavelier** [comment]
How `show_view()` should work in a `hemi=split` scenario? For now all the views are linked I guess it's not the most useful.

Should we duplicate the orientation slider in each view?

**Comment by larsoner** [comment]
> How show_view() should work in a hemi=split scenario? 

My advice is to always look first at PySurfer to see what it does to at least get an idea:

https://pysurfer.github.io/generated/surfer.Brain.html#surfer.Brain.show_view

In this case it has `row/col` indices, which seems like a sensible API

> Should we duplicate the orientation slider in each view?

That would be great!

**Comment by GuillaumeFavelier** [comment]
I think it's better now but the default values for the orientation slider are still not correct. Note that interaction with the user remains correct:

2020-01-16_1920x1080

**Comment by GuillaumeFavelier** [comment]
This was a big refactor but now playback works too:

output

**Comment by larsoner** [comment]
Beautiful!

**Comment by GuillaumeFavelier** [comment]
With this, the issue with the default values of the orientation sliders should be fixed.

**Comment by larsoner** [comment]
Should we test/review/merge or wait for PyVista fixes upstream?

**Comment by GuillaumeFavelier** [comment]
Feel free to review/test/merge this one @larsoner , @agramfort

**Comment by GuillaumeFavelier** [comment]
Oh and actually in your original comment @larsoner, you wanted to move some UI elements. If you test and you're not satisfied by the current setup, you can also let me know

**Comment by larsoner** [comment]
Works beautifully, awesome @GuillaumeFavelier !

**Pull request merged**
