### PR TITLE
Update license year to 2024

### PR DESCRIPTION
**Pull request by cbrnr**
Another year, another license update (a bit late, but better than never).

### CODE REVIEW

**Comment by sappelhoff** [comment]
We actually dropped tracking the license year span in MNE-BIDS, for these reasons:

- https://hynek.me/til/copyright-years/
- https://daniel.haxx.se/blog/2023/01/08/copyright-without-years/

Do you think we should do the same for MNE-Python?

**Comment by cbrnr** [comment]
I would drop it, yes, but I think we've discussed this at some point and decided against it (unfortunately, I can't find the relevant issue).

**Comment by cbrnr** [comment]
Found it, here you go: https://github.com/mne-tools/mne-python/pull/10229

**Review by hoechenberger — COMMENTED** [review]
why not simply drop the "to" part?

**Comment by hoechenberger** [comment]
sorry i was on mobile and couldn't see the comments you'd made before

**Comment by larsoner** [comment]
Thanks @cbrnr !

**Pull request merged**
