### PR TITLE
Support reading/writing scipy.sparse.csr_matrix type from/to hdf5 files.

### PR DESCRIPTION
**Pull request by nfoti**
The h5py wrapper code did not support writing `scipy.sparse.csr_matrices` which is inconvenient because `SourceEstimate.compute_morph_matrix` returns a `csr_matrix`.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
This does not look like an exact drop-in update of our `_h5io.py` with the one from https://github.com/h5io/h5io/blob/master/h5io/_h5io.py, which it probably should be. Can you just copy-paste it?

**Comment by nfoti** [comment]
Yes, didn't realize this was just copied from that repo.

**Comment by Eric89GXL** [comment]
Yeah, everything from `mne/externals` is just a copy (or close to it anyway)

**Comment by Eric89GXL** [comment]
h5io's implementation does not appear to support `csc`, so if you want you could open a PR there for it

**Comment by nfoti** [comment]
The file you linked to seems to support both CSR and CSC.

**Comment by Eric89GXL** [comment]
Whoops, I thought it was CSR only.

**Comment by agramfort** [comment]
this is just a copy paste?

**Comment by nfoti** [comment]
Yes.

**Comment by Eric89GXL** [comment]
Argh, need to modify h5io to nest its pandas import (which it should probably do anyway)

**Comment by nfoti** [comment]
Do you want me to do it?

**Comment by Eric89GXL** [comment]
Sure if you're up for it

**Comment by Eric89GXL** [comment]
Change should be made in upstream h5io repo, then moved here

**Comment by nfoti** [comment]
Sounds good. Will do now. I'm assuming there's a test in h5io to catch this also?

**Comment by Eric89GXL** [comment]
One of the CIs runs with pandas and another without IIRC

**Comment by nfoti** [comment]
I just committed the version of `h5io/_h5io.py` that was just merged into `h5io`. The AppVeyor test seems to be failing on something unrelated to this, but I'm not sure what it is.

**Comment by agramfort** [comment]
@Eric89GXL if you're happy

**Comment by kingjr** [comment]
FYI https://github.com/mne-tools/mne-python/issues/3292 should thus now be possible.

**Comment by Eric89GXL** [comment]
Thanks @nfoti

**Pull request merged**
