### PR TITLE
MRG: [MINOR, DOCS] Add newer plot functions to Migrating from EEGLAB

### PR DESCRIPTION
**Pull request by jona-sassenhagen**
NM

### CODE REVIEW

**Comment by jona-sassenhagen** [comment]
It looks really messy, but it's just adding two functions.

Waiting for renders ...

**Comment by jona-sassenhagen** [comment]
https://12433-1301584-gh.circle-artifacts.com/0/dev/manual/migrating.html looks good

**Comment by larsoner** [comment]
Beautiful:

https://12433-1301584-gh.circle-artifacts.com/0/dev/manual/migrating.html

Thanks @jona-sassenhagen

**Comment by jasmainak** [comment]
Nice! I can't believe I wrote a migrating doc without ever having used EEGLAB :-)

**Pull request merged**
