### PR TITLE
FIX: Make find_ecg_events work even if ECG peak detection doesn't yield anything

### LINKED ISSUE #9225: mne.preprocessing.find_ecg_events has a non-descript error when it can't detect ecg events
#### Describe the bug
mne.preprocessing.find_ecg_events has a non-descript error when it can't detect ecg events

#### Steps to reproduce
Should work with just a straight line or zeros in an ECG channel. 

#### Expected results
Either return an empty array or generate a more descriptive error message

#### Actual results
line 230, in find_ecg_events
    ecg_events = remap[ecg_events]
IndexError: arrays used as indices must be of integer (or boolean) type

(This is because ecg_events is None)
#### Additional information
Platform:      Windows-10-10.0.19041-SP0
Python:        3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]
Executable:   ...python.exe
CPU:           Intel64 Family 6 Model 158 Stepping 13, GenuineIntel: 8 cores
Memory:        Unavailable (requires "psutil" package)
mne:           0.22.0
numpy:         1.19.2 {blas=mkl_rt, lapack=mkl_rt}
scipy:         1.5.2
matplotlib:    3.3.2 {backend=Qt5Agg}
sklearn:       0.24.1
numba:         0.52.0
nibabel:       Not found
nilearn:       Not found
dipy:          Not found
cupy:          Not found
pandas:        1.1.5
mayavi:        Not found
pyvista:       Not found
vtk:           Not found

### PR DESCRIPTION
**Pull request by hoechenberger**
Fixes #9225

### CODE REVIEW

**Comment by hoechenberger** [comment]
Ok this is ready for review.

**Review by agramfort — APPROVED** [review]

**Review by drammock — APPROVED** [review]

**Comment by hoechenberger** [comment]
I think this should (and can easily) be backported too, any objections?

**Comment by agramfort** [comment]
yes and we should release a new mne release too soon....

>

**Comment by hoechenberger** [comment]
One CI run times out, the others finished. I think this can safely be merged.

**Comment by larsoner** [comment]
Thanks @hoechenberger, backported

**Comment by hoechenberger** [comment]
Awesome, thank you!

**Pull request merged**
