### PR TITLE
s/n_folds/n_splits

### LINKED ISSUE #3578: BUG: Breakages in time_gen with latest numpy and sklearn
First one probably needs to be `np.maximum` instead of `np.max`:
```
  File "/home/larsoner/custombuilds/mne-python/mne/decoding/csp.py", line 604, in _ajd_pham
    tmp2 = (tmp * g12 - g21) / np.max(omega - 1, 1e-9)
  File "/home/larsoner/.local/lib/python2.7/site-packages/numpy-1.12.0.dev0+b91e8d8-py2.7-linux-x86_64.egg/numpy/core/fromnumeric.py", line 2249, in amax
    return amax(axis=axis, out=out, **kwargs)
  File "/home/larsoner/.local/lib/python2.7/site-packages/numpy-1.12.0.dev0+b91e8d8-py2.7-linux-x86_64.egg/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
TypeError: 'float' object cannot be interpreted as an index
```
Second one must be due to sklearn change:
```
  File "/home/larsoner/custombuilds/mne-python/mne/decoding/base.py", line 670, in _set_cv
    cv = XFold(n_folds=cv)
TypeError: __init__() got an unexpected keyword argument 'n_folds'
```
@kingjr do you have time to look?

### PR DESCRIPTION
**Pull request by agramfort**
closes #3578

### CODE REVIEW

**Comment by Eric89GXL** [comment]
Do we need to worry about old sklearn?

**Comment by kingjr** [comment]
IIUC this is a change of the API in the dev version. We're already checking for the version and should thus be compatible with the older sklearn

**Comment by Eric89GXL** [comment]
AppVeyor is unhappy, suggesting there is some API problem either with the test skipper or in the code version checking

**Comment by agramfort** [comment]
cannot look more now

please someone take over

**Comment by Eric89GXL** [comment]
This is why I opened a bug report instead of just substituting the name, sklearn fixes are never this quick :)

**Comment by agramfort** [comment]
I gave you the hint :)

**Pull request closed without merging**
