### PR TITLE
MRG: Better tutorials using connectivity

### LINKED ISSUE #4643: Permutation cluster tests should compute vertex connectivity explicitly
This has bitten two of my coworkers in the ass. The permutation clustering examples on source space (e.g. https://martinos.org/mne/stable/auto_tutorials/plot_stats_cluster_spatio_temporal.html) use this to compute the connectivity between vertices:

    connectivity = spatial_tris_connectivity(grade_to_tris(5))

However, this is not always appropriate, depending on mixtures of old freesurfer brains and old mne-python versions. If the connectivity matrix is wrong, the statistics will go haywire in unpredictable ways. Since our users are prone to copy-pasting our example code without a second thought, this will be safer:

    # Read the source space that the individual stcs were morphed to
    src = mne.read_source_space('/path/to/fsaverage-ico4-src.fif')
    connectivity =  spatial_src_connectivity(src)

### PR DESCRIPTION
**Pull request by larsoner**
Closes #4643.

@wmvanvliet feel free to have a look, this should do what we talked about earlier to get rid of `grade_to_tris`.

### CODE REVIEW

**Comment by wmvanvliet** [comment]
I just updated my sample data, but still:

```
FileNotFoundError: [Errno 2] No such file or directory: '.../MNE-sample-data/fsaverage/bem/fsaverage-ico-5-src.fif'
```

**Comment by larsoner** [comment]
Yeah I have a bad path in there, fixed

**Comment by wmvanvliet** [comment]
Better. On to the next error:

```
%run plot_stats_cluster_spatio_temporal_repeated_measures_anova.py

.. _tut_stats_cluster_source_rANOVA:

======================================================================
Repeated measures ANOVA on source data with spatio-temporal clustering
======================================================================

This example illustrates how to make use of the clustering functions
for arbitrary, self-defined contrasts beyond standard t-tests. In this
case we will tests if the differences in evoked responses between
stimulation modality (visual VS auditory) depend on the stimulus
location (left vs right) for a group of subjects (simulated here
using one subject's data). For this purpose we will compute an
interaction effect using a repeated measures ANOVA. The multiple
comparisons problem is addressed with a cluster-level permutation test
across space and time.

Simulating data for 7 subjects.
Morphing data.
Computing connectivity.
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~/BRU/mne-python/tutorials/plot_stats_cluster_spatio_temporal_repeated_measures_anova.py in <module>()
    200 # as we only have one hemisphere we need only need half the connectivity
    201 print('Computing connectivity.')
--> 202 connectivity = mne.spatial_src_connectivity(src[:1])
    203 
    204 #    Now let's actually do the clustering. Please relax, on a small

~/BRU/mne-python/mne/source_estimate.py in spatial_src_connectivity(src, dist, verbose)

~/BRU/mne-python/mne/utils.py in verbose(function, *args, **kwargs)
    726         with use_log_level(verbose_level):
    727             return function(*args, **kwargs)
--> 728     return function(*args, **kwargs)
    729 
    730 

~/BRU/mne-python/mne/source_estimate.py in spatial_src_connectivity(src, dist, verbose)
   2890         The connectivity matrix describing the spatial graph structure.
   2891     """
-> 2892     return spatio_temporal_src_connectivity(src, 1, dist)
   2893 
   2894 

~/BRU/mne-python/mne/source_estimate.py in spatio_temporal_src_connectivity(src, n_times, dist, verbose)

~/BRU/mne-python/mne/utils.py in verbose(function, *args, **kwargs)
    726         with use_log_level(verbose_level):
    727             return function(*args, **kwargs)
--> 728     return function(*args, **kwargs)
    729 
    730 

~/BRU/mne-python/mne/source_estimate.py in spatio_temporal_src_connectivity(src, n_times, dist, verbose)
   2765         connectivity = spatio_temporal_dist_connectivity(src, n_times, dist)
   2766     else:
-> 2767         connectivity = _spatio_temporal_src_connectivity_surf(src, n_times)
   2768     return connectivity
   2769 

~/BRU/mne-python/mne/source_estimate.py in _spatio_temporal_src_connectivity_ico(src, n_times)
   2698     used_verts = [np.unique(s['use_tris']) for s in src]
   2699     offs = np.cumsum([0] + [len(u_v) for u_v in used_verts])[:-1]
-> 2700     tris = np.concatenate([np.searchsorted(u_v, s['use_tris']) + off
   2701                            for u_v, s, off in zip(used_verts, src, offs)])
   2702     connectivity = spatio_temporal_tris_connectivity(tris, n_times)

IndexError: list index out of range
```

**Comment by wmvanvliet** [comment]
Beautiful. Everything is working now and it's a nice improvement of the tutorial!

**Comment by mmagnuski** [comment]
There is now a white bar where previously you could find "Duration significant (ms)" description.

**Comment by larsoner** [comment]
Yes this is an unrelated bug that is also in `master`:

https://martinos.org/mne/dev/auto_tutorials/plot_stats_cluster_spatio_temporal_2samp.html

It is caused by VTK being too old on CircleCI. This will probably take some effort to fix so we should do it separately.

**Comment by mmagnuski** [comment]
ok!

**Pull request merged**
