### PR TITLE
MRG: Add st_only option for temporal projection

### PR DESCRIPTION
**Pull request by Eric89GXL**
This allows using `maxwell_filter` in a temporal-projection-only (tSSS only) mode.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
cc @staulu

**Comment by agramfort** [comment]
CIs are happy...

**Comment by Eric89GXL** [comment]
@agramfort is the docstring clear enough for you to understand what it does, and why it might be useful? It also might be useful for people who want to try tSSS without the dimensionality reduction of SSS, for whatever reason.

**Comment by agramfort** [comment]
yeah it's clear enough. At least for me :)

**Comment by Eric89GXL** [comment]
Still skillfully avoiding #2868 @agramfort, don't think I didn't notice...

@wronk do you have time to take a look?

**Comment by wronk** [comment]
LGTM, and you have my +1 on the docstring :)

**Comment by Eric89GXL** [comment]
Thanks for the reviews

**Pull request merged**
