### PR TITLE
MRG: Add ARTEMIS123 helmet

### PR DESCRIPTION
**Pull request by larsoner**
@bloyl I used `Delaunay` to make a helmet for your system. This is what it looks like on `master`, where it errantly uses the Neuromag helmet:

master

And on this PR:

snapshot

Binary file is 2.1 kB.

### CODE REVIEW

**Comment by larsoner** [comment]
One question -- should it be `ARTEMIS123` or `Artemis123`?

Also here is the `gist` I used to create the helmet:

https://gist.github.com/larsoner/dbcf0b4c79732a82c3bc30a520a0a797

**Comment by bloyl** [comment]
I think it looks fine.
it should be Artemis123 (as per http://tristantech.com/artemis123babysquid). 

If I could get you CAD points of the actual helmet (as opposed to the coils) would that be of interest?

**Comment by larsoner** [comment]
> If I could get you CAD points of the actual helmet (as opposed to the coils) would that be of interest?

Yep, that would be even better

**Comment by larsoner** [comment]
(hopefully the locations of the coils relative to those CAD points would also be available so that they could be coregistered properly, unless the CAD already defines its origin as the device origin...)

**Comment by bloyl** [comment]
I was wrong, None of the files I have had CAD locations of points on the helmet surface. Sorry.

I would say move ahead with this, and I'll ask either at the next PM or at biomag.

**Pull request merged**
