### PR TITLE
Fix for `set_bipolar_reference`

### PR DESCRIPTION
**Pull request by jbschiratti**
This PR fixes a small bug in #4218 and proposes to add a `verbose` parameter to `set_bipolar_reference`. Indeed, in `set_bipolar_reference`, `inst.drop_channels(cathode)` raises an error if there is a non-empty intersection between the lists `anode` and `cathode` (we try to drop channels which no longer exist).

### CODE REVIEW

**Comment by jaeilepp** [comment]
Use verbose decorator like [here](https://github.com/mne-tools/mne-python/blob/master/mne/epochs.py#L402).

**Comment by jbschiratti** [comment]
@jaeilepp : Thank you. It's done.

**Comment by agramfort** [comment]
@jbschiratti can you update the test I recently modified?

**Comment by jbschiratti** [comment]
@agramfort : It's done. With this updated test, the previous code for `set_bipolar_reference` fails whereas it works fine with this PR.

**Comment by agramfort** [comment]
+1 for merge if travis is happy

**Comment by Eric89GXL** [comment]
thanks @jbschiratti

**Pull request merged**
