### PR TITLE
DOC: (Hopefully) small clarification to plot_evoked_topomap() docstring

### PR DESCRIPTION
**Pull request by hoechenberger**
#### What does this implement/fix?

I slightly changed the docstrings of the `vmin` and `vmax` parameters of `plot_evoked_topomap()`, and hope they are easier to understand now.

### CODE REVIEW

**Comment by drammock** [comment]
This seems like a case where it would be easier to document both parameters in one entry. Are we allowed to do `vmin, vmax : None | float | callable` as a single entry?

**Comment by larsoner** [comment]
> Are we allowed to do vmin, vmax : None | float | callable as a single entry?

I would say try it and see if `mne/tests/test_docstring_parameters.py` complains, and check the API page rendering.

Another option is just to document everything in `vmin : ` as we do now, and change `vmax : ` just to say "See vmin.".

**Comment by drammock** [comment]
In that case, I would suggest something like this:

```
vmin, vmax : float | callable | None
    Lower and upper bounds of the colormap, in the same units as the data.
    If ``vmin`` and ``vmax`` are both ``None``, they are set at ± the maximum
    absolute value of the data (yielding a colormap with midpoint at 0).
    If only one of ``vmin``, ``vmax`` is ``None``, will use ``min(data)``
    or ``max(data)``, respectively. If callable, should accept a
    :ref:`numpy array <numpy.ndarray>` of data and return a float.
```

**Comment by hoechenberger** [comment]
@drammock sounds excellent, will try this. Great phrasing too!

**Comment by hoechenberger** [comment]
@drammock Do I need to add `numpy.ndarray` to `numpydoc_xref_aliases` in `conf.py`, or how do I get rid of the warning Circle throws?

```
/home/circleci/project/mne/evoked.py:docstring of mne.Evoked.plot_topomap:22: WARNING: undefined label: numpy.ndarray (if the link has no caption the label must precede a section header)
/home/circleci/project/mne/evoked.py:docstring of mne.EvokedArray.plot_topomap:22: WARNING: undefined label: numpy.ndarray (if the link has no caption the label must precede a section header)
/home/circleci/project/mne/viz/topomap.py:docstring of mne.viz.plot_evoked_topomap:25: WARNING: undefined label: numpy.ndarray (if the link has no caption the label must precede a section header)
```

**Comment by agramfort** [comment]
I would avoid the cross-link with numpy and keep it simple and stupid

**Comment by hoechenberger** [comment]
Circle is happy now, Travis is struggling but unrelated.

btw @larsoner I don't have that "Restart Travis job" button, could you grant me the required permission to restart individual jobs?

**Comment by hoechenberger** [comment]
@agramfort If you're happy I believe we can merge, since @drammock kinda implicitly approved this, as the change I added was proposed by him, sans for my small NumPy reference adjustmen.

**Comment by agramfort** [comment]
LGTM

https://19114-1301584-gh.circle-artifacts.com/0/dev/generated/mne.viz.plot_evoked_topomap.html?highlight=plot_evoked_topomap#mne.viz.plot_evoked_topomap

**Comment by drammock** [comment]
Thanks @hoechenberger. FYI, I think the problem was that the link to ndarray should have been a `func` instead of a `ref`

**Comment by hoechenberger** [comment]
Ok, thanks! Should I change that in another PR or is the class-ref we have now good enough?

**Comment by drammock** [comment]
Oh, never mind. I didn't realize you'd resolved the linking; `class` is correct. I was just going by Alex's comment that you should remove it, and assuming that was what had happened. And then I mis-remembered the directive. That'll teach me to comment before I've had breakfast.

**Comment by hoechenberger** [comment]
Thx for the clarification, @drammock  :) And keep those comments coming, even before breakfast! ;)

**Pull request merged**
