### PR TITLE
Added misc channel to evoked plot.

### PR DESCRIPTION
**Pull request by jaeilepp**
Closes https://github.com/mne-tools/mne-python/issues/3647
Now misc channels included to evoked instance are also plotted.

### CODE REVIEW

**Comment by agramfort** [comment]
LGTM

**Comment by agramfort** [comment]
we'll need to backport

**Comment by jona-sassenhagen** [comment]
I ran into just this problem today, thanks @jaeilepp!

And good to see @kdoelling1919 fully committed to the good side :)

**Comment by agramfort** [comment]
@jaeilepp please merge and backport

thx

**Pull request merged**
