### PR TITLE
MRG: Deprecate do_forward_solution

### PR DESCRIPTION
**Pull request by Eric89GXL**
Ready for review/merge from my end.

@jona-sassenhagen where did you see `do_forward_solution` in a tutorial?

### CODE REVIEW

**Comment by jona-sassenhagen** [comment]
I think nowhere - I found make_forward_solution, had a problem, googled, came upon do_forward_solution.

**Comment by Eric89GXL** [comment]
Ahh okay -- we should fix the problem with `make_forward_solution`, please open a bug report. It helps if it does work with `do_forward_solution`, too.

**Comment by agramfort** [comment]
Lgtm 

Cool these red lines ;)

**Comment by agramfort** [comment]
Don't forget what's new and merge

**Comment by Eric89GXL** [comment]
Okay, will do once the CIs come back happy.

**Pull request merged**
