### PR TITLE
DOC: allow_maxshield

### PR DESCRIPTION
**Pull request by jjnurminen**
Doc for `allow_maxshield` is somewhat misleading (you don't "process" anything with MaxShield). I also expanded it a bit.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
You'll also need to modify both instances in `mne/evoked.py` and the other instance in `io/fiff/raw.py`, otherwise LGTM

**Comment by jjnurminen** [comment]
oops

**Comment by jjnurminen** [comment]
not sure why tests fail...

**Comment by Eric89GXL** [comment]
It's an unrelated Anaconda or tvtk big

**Comment by jjnurminen** [comment]
OK, thanks

**Comment by Eric89GXL** [comment]
Thanks @jjnurminen

**Pull request merged**
