### PR TITLE
[MRG] Correctly delete previous event texts

### LINKED ISSUE #4690: raw.plot error when there are events and annotations
When I plot raw data with both events and annotations, I get an `IndexError: pop from empty list` in

    mne/viz/raw.py", line 1025, in _plot_raw_traces
        params['ax'].texts.pop(0)

I didn't realize that there could be other texts besides events in `params['ax'].texts`, so I set `params['ax'].texts = []` in [line 1016](https://github.com/mne-tools/mne-python/blob/master/mne/viz/raw.py#L1016).

Any ideas how to fix this are very much appreciated. This is pretty serious, although the plot continues to work even after such an error.

### PR DESCRIPTION
**Pull request by cbrnr**
Fix #4690 - this is a first try and I think a step into the right direction. When adding new annotations ('a' key), some annotation texts are still overplotted.

### CODE REVIEW

**Comment by agramfort** [comment]
tell us when to look

**Comment by cbrnr** [comment]
One Travis job fails with a PEP8 error - where is it? I can't see it... 😕

**Comment by cbrnr** [comment]
I think this should work now - please take a look (and tell me why the PEP8 job fails).

**Comment by cbrnr** [comment]
Did anything change in the flake settings? The reported errors/warnings are not due to my changes. This also happens in #4696.

**Comment by agramfort** [comment]
can you submit another PR that adds E722 to ignored errors and fix the remaining one?

yes I think it's due to an updated of flake8 on anaconda...

**Comment by cbrnr** [comment]
Do you really want to globally disable E722? If yes, would the correct place be in the `Makefile` line 92:

    flake8 --count --ignore=E722 mne examples tutorials; \

Personally, I'd rather fix these errors.

**Comment by agramfort** [comment]
in setup.cfg

**Comment by cbrnr** [comment]
#4698

**Comment by larsoner** [comment]
I'd rather fix them, too

**Comment by larsoner** [comment]
This looks like a reasonable fix to me. It's implicit in the code but can you add an explict comment saying that events get added first then annotations, which is why `.pop(0)` and `.pop(-1)` are used? It might save the next dev who looks at the code in six months some mental gymnastics.

I assume you've tested and it works for you? Is there a good example file to run to check?

**Comment by cbrnr** [comment]
You're right, especially if the next dev in six months is me 😄 .

Any file with both annotations and markers works to check this fix. If it doesn't work and texts get overplotted, you'll see that because overplotted text looks a bit bolder than normal.

**Comment by cbrnr** [comment]
Done.

**Comment by agramfort** [comment]
so MRG?

**Comment by cbrnr** [comment]
Fine by me, but it would be good if at least one other person could test this and see if it works (I've tested it of course and it works for me).

**Comment by agramfort** [comment]
just tried and I get this:

```
In [3]: Traceback (most recent call last):
  File "/Users/alex/anaconda/envs/mne/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 389, in process
    proxy(*args, **kwargs)
  File "/Users/alex/anaconda/envs/mne/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 227, in __call__
    return mtd(*args, **kwargs)
  File "/Users/alex/work/src/mne-python/mne/viz/utils.py", line 1883, in _annotations_closed
    params['ax'].selector.disconnect_events()
AttributeError: 'NoneType' object has no attribute 'disconnect_events'
```

**Comment by cbrnr** [comment]
@agramfort this is reported in #4691. It seems like this never worked - @larsoner can you take a look at this in #4691?

Regarding this issue, this error does not completely crash the plot, you can continue to annotate and see if the annotation texts now render correctly.

**Comment by larsoner** [comment]
I can't replicate this problem, but can't we add `if params['ax'].selector is not None:` before calling `params['ax'].selector.disconnect_events()` to work around this?

**Comment by cbrnr** [comment]
Sure unless this is a more serious issue which we then should not silence. What do you think?

**Comment by larsoner** [comment]
> Sure unless this is a more serious issue which we then should not silence. What do you think

I would just add a comment like `# XXX hack workaround for what is probably another MacOSX plt backend bug`

**Comment by cbrnr** [comment]
OK, the (unrelated) error is fixed in #4739. After this is merged, @agramfort or @larsoner can you check if plotting events and annotations now works so that this PR can finally be merged?

**Comment by larsoner** [comment]
Yes, I can look later today

**Comment by larsoner** [comment]
So I am testing with:
```
import mne
raw = mne.io.read_raw_fif(mne.datasets.sample.data_path() +
                          '/MEG/sample/sample_audvis_raw.fif')
events = mne.find_events(raw, 'STI 014')
raw.annotations = mne.Annotations([1], [1], 'foo')
raw.plot(events=events)
```
On `master`, pressing "right" to view the 10-20 sec interval, the first event has no number above it. Hitting right-left (to approach the same segment from the right), all events have numbers.

On this PR, pressing "right" the last event has no number above it. Again approaching from the right it's correct.

Given it's on `master` we can fix it separately if you want.

After a few minutes of playing around on `master` adding some annotations and scrolling around I don't see any weird behavior other than the extension of the above, getting more event labels missing from the right end of the 10-20 sec interval when scrolling right (and on this PR, they are missing from the left). Can you give step-by-step instructions for how to reproduce?

**Comment by cbrnr** [comment]
Thanks @larsoner, your detailed description helped me fix the problem. It is working now, can you please confirm? If yes, then ready to merge!

**Comment by cbrnr** [comment]
As usual, OSX Travis tests fail for unrelated reasons, but everything else is green.

**Comment by larsoner** [comment]
Thanks @cbrnr

**Pull request merged**
