### PR TITLE
MRG: Fix CTF normals

### PR DESCRIPTION
**Pull request by Eric89GXL**
So far I just fixed some normal stuff. @agramfort do you want to review and merge this now, or should I tackle #2937 here, too?

### CODE REVIEW

**Comment by agramfort** [comment]
let's see how long it takes to have the phantom data working.

let's merge in 1 week if phantom ends up tricky

**Comment by mshamalainen** [comment]
The phantom data worked well in MNE with and without the fix. There was another more serious problem in BrainStorm.

> On Feb 24, 2016, at 12:00 PM, Alexandre Gramfort <notifications@github.com> wrote:
> 
> let's see how long it takes to have the phantom data working.
> 
> let's merge in 1 week if phantom ends up tricky
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/mne-tools/mne-python/pull/2939#issuecomment-188353246>.
> 



The information in this e-mail is intended only for the person to whom it is
addressed. If you believe this e-mail was sent to you in error and the e-mail
contains patient information, please contact the Partners Compliance HelpLine at
http://www.partners.org/complianceline . If the e-mail was sent to you in error
but does not contain patient information, please contact the sender and properly
dispose of the e-mail.

**Comment by agramfort** [comment]
How did you validate?

**Comment by Eric89GXL** [comment]
Thinking about it more, it probably makes sense to merge this one as-is, and tackle the tutorial separately. Would be easier to review, especially since this mostly contains C-equivalent bug fixes.

**Comment by agramfort** [comment]
fine with me.

merge if travis is happy

**Pull request merged**
