### PR TITLE
fix tempita some unicode

### PR DESCRIPTION
**Pull request by agramfort**

### CODE REVIEW

**Comment by yarikoptic** [comment]
ha -- actually you said in https://github.com/mne-tools/mne-python/pull/1568  that you had fixed it already a while back but differently... but without pointer so not sure how but may be this one is not even needed any longer? ;-)

**Comment by agramfort** [comment]
hum... how can I know if it's needed then? any test failing on your build farm?

**Comment by yarikoptic** [comment]
I could try that but better after that other one gets addressed

**Comment by jaeilepp** [comment]
@agramfort I think the test failure happens because one of the tests uses mayavi module even though there is only ``@requires_tvtk`` decorator.

**Comment by agramfort** [comment]
can you open a PR to fix in master? we'll backport to maint branch and let
yarik integrate in the debian package.

**Comment by jaeilepp** [comment]
I just pushed a fix patch to debian.

**Comment by agramfort** [comment]
@yarikoptic travis is broken with this patch... no idea why we need it for debian packaging...

**Pull request closed without merging**
