### PR TITLE
FIX: Read events from ceo file.

### LINKED ISSUE #9380: mne.io.read_raw_curry() cannot read the event file end with '.cdt.ceo'
#### Describe the bug
I have tried to use `mne.io.read_raw_curry()` to read my data created by Curry 8, but there were no annotations in the Raw object. But EEGLAB can import the data and show the annotations correctly.

#### Steps to reproduce
I read the source code of [curry.py](https://github.com/mne-tools/mne-python/blob/maint/0.23/mne/io/curry/curry.py), and I found this function cannot handle the ".cdt.ceo" file. 

So I change the file extension of my file from ".cdt.ceo" to "cdt.cef", and the function works smoothly.

#### Expected results
`mne.io.read_raw_curry()` can read cef file too, or it will make some users confused.

#### Additional information
I am sorry for my weak program skill. I have tried to fix this bug.

### PR DESCRIPTION
**Pull request by rezashr**
#### Reference issue
Fixes #9380 
Improves #9381 

#### What does this implement/fix?
With #9381, 'ceo' files can be imported after renaming to 'cef'. This PR adds '.ceo' extension to event file extensions.

### CODE REVIEW

**Review by agramfort — APPROVED** [review]
@DiGyt ok for you?

**Comment by larsoner** [comment]
@rezashr can you add an entry to `doc/changes/latest.inc` in the enhancements section?

**Comment by rezashr** [comment]
@larsoner there was an entry for reading '.cdt.ceo' events in latest.inc, so I merged this PR description to that one. Is it okay?

**Review by agramfort — APPROVED** [review]

**Comment by larsoner** [comment]
@rezashr I think you just need to add your name+URL to `doc/changes/names.inc` then we should be good here!

**Review by agramfort — APPROVED** [review]

**Comment by agramfort** [comment]
thx @rezashr

**Pull request merged**
