### PR TITLE
EHN: animated gif

### PR DESCRIPTION
**Pull request by kingjr**
taking over https://github.com/mne-tools/mne-python/pull/2242 because I suck at rebasing.

test code:
```
from mne.report import Report
import urllib
urllib.urlretrieve('http://funnyasduck.net/wp-content/uploads/2014/07/funny-pictures-ant-jumping-onto-spider-animated-gif.gif', 'g.gif')
report = Report()
report.add_images_to_section('g.gif', 'section', 'example', image_format='gif')
report.save()
```

@teonlamont can you check that your slider still works as intended with this?

### CODE REVIEW

**Comment by teonlamont** [comment]
it doesn't look like it conflicts. is it considered hazing if we force you to rebase your other pr ;)

**Comment by kingjr** [comment]
> it doesn't look like it conflicts. is it considered hazing if we force you to rebase your other pr ;)

I did try. I failed miserably after 30 minutes of weird conflicts editing.

I'm still waiting for a low-IQ compatible git interface.

**Comment by Eric89GXL** [comment]
LGTM, but could you add a simple test that uses the feature? I guess you don't have to check the output for correctness, just make sure it runs.

**Comment by agramfort** [comment]
closing for #2541

**Pull request closed without merging**
