### PR TITLE
FIX: implentation of tmin.setter and tmax.setter in _BaseEpochs

### PR DESCRIPTION
**Pull request by cmoutard**
Fix associated to issue  #2806

### CODE REVIEW

**Comment by Eric89GXL** [comment]
I don't think this is the right fix. `tmin` should be a property that points to `self.times[0]` as it does currently. I think the correct fix is just not to set `epochs.tmin` in that function, since it should be unnecessary.

**Comment by Eric89GXL** [comment]
We'll also need a test that demonstrates the behavior that would fail on master but pass here

**Comment by cmoutard** [comment]
Ok, thanks for this clarification. So - to be sure - I just cancel the previous commit and delete the lines overwriting tmin and tmax in decim ?

**Comment by Eric89GXL** [comment]
Yeah that should work. But please also write a test

**Pull request closed without merging**
