### PR TITLE
fix set_annotation with anonymize data

### PR DESCRIPTION
**Pull request by agramfort**
aims to close https://github.com/mne-tools/mne-bids/issues/403

cc @larsoner @hoechenberger 

this is still WIP as it's no so clear why this is needed. There is something fishy/inconsistent
somewhere.

### CODE REVIEW

**Comment by hoechenberger** [comment]
This does inded seem to fix the issue. I've tested with the localizer datast mentioned in the original issue, and with MNE's sample data `MEG/sample/sample_audvis_raw.fif`, and both seem to work!

**Comment by agramfort** [comment]
basically it's a nasty bug that occurs when meas_date is None and first_samp > 0 ...

@hoechenberger one should not have this issue with BIDS data as meas_date should be shifted in the  past when converting to BIDS and not removed. Pb is due to the fact that data was anonymized with mne before the days_back logic of raw.anonymize was implemented.

ok for you @larsoner ? we should ideally backport this...

**Comment by hoechenberger** [comment]
> @hoechenberger one should not have this issue with BIDS data as meas_date should be shifted in the past when converting to BIDS and not removed. Pb is due to the fact that data was anonymized with mne before the days_back logic of raw.anonymize was implemented.

Thanks for the explanation, I need to read up on the `days_back` thing, never really understood how it works (but hopefully soon!)

**Comment by agramfort** [comment]
have a look at https://github.com/mne-tools/mne-python/pull/6892/files
https://github.com/mne-tools/mne-python/pull/7016/files
for some background

>

**Comment by hoechenberger** [comment]
> have a look at https://github.com/mne-tools/mne-python/pull/6892/files https://github.com/mne-tools/mne-python/pull/7016/files for some background

Thanks @agramfort

**Comment by hoechenberger** [comment]
@agramfort I just discovered that this PR doesn't solve the entirety of the issue.

So far I had only looked at event sample numbers, which were off in `master`, and your PR fixes those.

Now I looked into the `Annotations` onset times, and there's still a problem. Have a look at this MWE:

```python
from tempfile import TemporaryDirectory
import mne
from mne_bids import make_bids_basename, read_raw_bids, write_raw_bids

mne.set_log_level(verbose=False)


subject = 'SB01'
raw_fname = 'SB01_Localizer_raw.fif'
raw = mne.io.read_raw_fif(raw_fname, allow_maxshield=True)
events = mne.find_events(raw, min_duration=2/raw.info['sfreq'])
bids_basename = make_bids_basename(subject=subject)
bids_fname = bids_basename + '_meg.fif'

with TemporaryDirectory() as bids_root:
    write_raw_bids(raw=raw,
                   bids_basename=bids_basename,
                   bids_root=bids_root,
                   events_data=events,
                   overwrite=True,
                   verbose=False)

    raw_read = read_raw_bids(bids_fname=bids_fname,
                             bids_root=bids_root,
                             extra_params=dict(allow_maxshield=True),
                             verbose=False)
    events_read, _ = mne.events_from_annotations(raw_read)

print(f'First event sample before writing:   {events[0, 0]}')
print(f'First event sample after reading:    {events_read[0, 0]}')
print(f'… after first_samp subtraction:      {events_read[0, 0] - raw_read.first_samp}')

print(f'Last time point after reading:       {raw_read.times[-1]}')
print(f'Last annotation onset after reading: {raw_read.annotations.onset[-1]}')
print(f'… after first_time subtraction:      {raw_read.annotations.onset[-1] - raw_read.first_time}')
```

Produces:
```
First event sample before writing:   24863
First event sample after reading:    24863
… after first_samp subtraction:      2363
Last time point after reading:       270.7495
Last annotation onset after reading: 281.966
… after first_time subtraction:      270.716
```

**Comment by hoechenberger** [comment]
@agramfort How should we proceed here?

**Comment by agramfort** [comment]
no time to look today :(

>

**Comment by hoechenberger** [comment]
> no time to look today :(

No worries, it's not urgent. Let me know if I can be of any help

**Pull request closed without merging**
