### PR TITLE
Add cone mode to quiver3d

### LINKED ISSUE #5985: BUG: plot_sparse_source_estimates broken
See last plot in [master](http://mne-tools.github.io/dev/auto_examples/inverse/plot_custom_inverse_solver.html) compared to [maint/0.17](http://mne-tools.github.io/stable/auto_examples/inverse/plot_custom_inverse_solver.html). @GuillaumeFavelier

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
#### Reference issue
Fixes #5985.

#### What does this implement/fix?
Add the missing `cone` mode to the `quiver3d` function in the default pysurfer/mayavi 3d backend.

### CODE REVIEW

**Comment by agramfort** [comment]
Merge when rendered doc looks good. Thx

**Comment by agramfort** [comment]
you need to touch the affected example so it's appears rendered in the doc.
Not like here:

https://11655-1301584-gh.circle-artifacts.com/0/dev/auto_examples/inverse/plot_custom_inverse_solver.html

>

**Comment by GuillaumeFavelier** [comment]
Ok

**Comment by GuillaumeFavelier** [comment]
The [cones](https://11660-1301584-gh.circle-artifacts.com/0/dev/_images/sphx_glr_plot_custom_inverse_solver_002.png) are displayed now but the result is still slightly different than in [maint/0.17](http://mne-tools.github.io/stable/auto_examples/inverse/plot_custom_inverse_solver.html). The algorithm have been modified in master maybe?

**Comment by larsoner** [comment]
Yes the results have changed slightly in the refactoring

**Comment by agramfort** [comment]
How come we got rid of right hemisphere sources ? Can we get them back by changing prépare forward options ?

**Comment by larsoner** [comment]
> Can we get them back by changing prépare forward options ?

I can check

**Pull request merged**
