### PR TITLE
MRG: Add mV support to BrainVision reader

### LINKED ISSUE #7537: read_raw_brainvision should support mV
While working on https://github.com/bids-standard/pybv/pull/39 (an option to explicitly specify the unit for the exported file), I noticed that `read_raw_brainvision` only supports signals in V, µV or nV, but not mV (https://github.com/mne-tools/mne-python/blob/master/mne/io/brainvision/brainvision.py#L504). Would it be OK if I added the missing mV unit?

### PR DESCRIPTION
**Pull request by cbrnr**
Fixes #7537.

### CODE REVIEW

**Comment by agramfort** [comment]
any test that can be trivially updated to check that it works?

**Comment by cbrnr** [comment]
For a test we would need to add at least one additional .vhdr file (which would specify channel units in mV). Are you OK with that?

I'm already testing the behavior in https://github.com/bids-standard/pybv/pull/39 but I guess we should have our own test here.

**Comment by cbrnr** [comment]
Or I could modify the existing `test_nV.vhdr` and include other units (i.e. `V` and `mV`).

**Comment by larsoner** [comment]
You can probably just fake one. Copy some existing .eeg file to a tmpdir and copy it's vhdr line by line, modifying the one you need. Then read the data and make sure it's allclose with the original data times 1e-3

You could for example reuse this fixture which does some of the annoying steps for you

https://github.com/mne-tools/mne-python/blob/master/mne/io/brainvision/tests/test_brainvision.py#L109

**Comment by cbrnr** [comment]
I edited the existing alternative header file, and for some reason mV does not work yet (V works fine though).

**Comment by cbrnr** [comment]
It seems like the `'range'` entry in the `ch` dict is incorrect for the mV case:

- For nV 'cal` is `500` and `range` is `1e-09`.
- For mV 'cal' is `0.0005` and `range` is `1.0` (should be `1e-03` IMO).
- For V 'cal' is `5e-07` and `range` is `1.0`.

Any ideas where this could be happening?

**Comment by cbrnr** [comment]
Found it, pushing the working version.

**Comment by agramfort** [comment]
don't forget to update latest.inc

thanks

**Comment by cbrnr** [comment]
Done.

**Comment by larsoner** [comment]
Thanks @cbrnr

**Comment by larsoner** [comment]
Backported

**Pull request merged**
