### PR TITLE
FIX: Montage Index error when importing CNT files

### LINKED ISSUE #5493: IndexError when importing raw CNT file
#### Describe the bug
- Failure to import a particular Neuroscan .cnt file via `read_raw_cnt()` due to out of bounds indexing in `cnt.py` line 251
- About half of our .cnt files work, half do not due to this error.

#### Steps and/or code to reproduce
```
from mne.io import read_raw_cnt

raw_fname = 'raw_eeg_data.cnt'
montage_fname = 'standard-10-5-cap385.elp'
raw = read_raw_cnt(raw_fname, montage=montage_fname, eog=('HEOG', 'VEOG'), emg=('EMG',), preload=True, verbose=True)
```

#### Expected results
- raw variable successfully populated with a RawCNT object upon reading the .cnt file
- no error message

#### Actual results
```
Traceback (most recent call last):
  File "/Users/corey/Documents/GitLab/01mne_python_automation/bin/source_localization.py", line 210, in <module>
    raw = read_raw_cnt(raw_fname, montage=montage_fname, eog=('HEOG', 'VEOG'), emg=('EMG',), preload=True, verbose=True)
  File "/anaconda3/envs/mne/lib/python3.6/site-packages/mne/io/cnt/cnt.py", line 95, in read_raw_cnt
    preload=preload, verbose=verbose)
  File "/anaconda3/envs/mne/lib/python3.6/site-packages/mne/io/cnt/cnt.py", line 361, in __init__
    data_format, date_format)
  File "/anaconda3/envs/mne/lib/python3.6/site-packages/mne/io/cnt/cnt.py", line 251, in _get_cnt_info
    stim_channel[event_time - 1] = event_id
IndexError: index 295313 is out of bounds for axis 0 with size 294560
```

#### Additional information
`sys_info()` : 
```
Platform:      Darwin-17.7.0-x86_64-i386-64bit
Python:        3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:07:29)  [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
Executable:    /anaconda3/envs/mne/bin/python
CPU:           i386: 8 cores
Memory:        16.0 GB

mne:           0.16.2
numpy:         1.15.0 {blas=mkl_rt, lapack=mkl_rt}
scipy:         1.1.0
matplotlib:    2.2.2 {backend=MacOSX}

sklearn:       0.19.1
nibabel:       2.3.0
mayavi:        4.6.1 {qt_api=pyqt5}
pycuda:        Not found
skcuda:        Not found
pandas:        0.23.3
```

### PR DESCRIPTION
**Pull request by massich**
Fixes #5493

### CODE REVIEW

**Comment by massich** [comment]
Just for the record, testing with some confidential files + some files on the web running the following

```py
import mne
import pytest
import os.path as op
from datetime import datetime
from mne import __file__ as _mne_file
from mne.tests.test_annotations import _assert_annotations_equal

regular_path = op.join(op.dirname(_mne_file), '..', 'sandbox', 'data')
confidential_path = op.join(regular_path, 'confidential', 'cnt')

flankers_path = op.join(regular_path, '914flankers.cnt')

cnt_files_with_eeglab_pair = [
    op.join(confidential_path, 'BoyoAEpic1_16bit.cnt'),
    op.join(confidential_path, 'cont_67chan_resp_32bit.cnt'),
    op.join(confidential_path, 'SampleCNTFile_16bit.cnt')
]


def test_ensure_meas_date(recwarn):
    raw = mne.io.read_raw_cnt(flankers_path, montage=None,
                              date_format='dd/mm/yy')
    meas_date = (datetime
                 .fromtimestamp(raw.info['meas_date'][0])
                 .strftime('%d/%m/%y %H:%M:%S'))

    assert meas_date == '23/09/07 12:22:15'


@pytest.mark.parametrize('fname', cnt_files_with_eeglab_pair, ids=op.basename)
def test_check_cnt_eeglab_pairs(fname, recwarn):
    raw_eeglab = mne.io.read_raw_eeglab(fname.replace('.cnt', '.set'),
                                        montage=None)
    raw_cnt = mne.io.read_raw_cnt(fname, montage=None)

    assert raw_cnt.info.keys() == raw_eeglab.info.keys()
    xx = object_diff(raw_cnt.info, raw_eeglab.info)
    print(xx)
```

I get: 
* The date work properly, 
* the info difference between `cnt` and its transformed `eeglab` version are
  * the `subject_info` anonymization (eeglab is none cnt has empty fields)
  * digitization mismatch (but this is beeing addressed somwhere else)
  * for one file `cnt` has a trigger channel marked as bad that does not appear in the eeglab version of the file. 

```sh
['chs'][63]['cal'] type mismatch (<class 'numpy.ndarray'>, <class 'float'>)
['chs'][63]['coord_frame'] value mismatch (4, 0)
['chs'][63]['loc'] array mismatch
['chs'][63]['unit_mul'] type mismatch (<class 'float'>, <class 'int'>)
['subject_info'] type mismatch (<class 'dict'>, <class 'NoneType'>)
```

**Comment by massich** [comment]
reading `914flankers.cnt` in master:

```sh
>               stim_channel[event_time - 1] = event_id
E               IndexError: index 583988 is out of bounds for axis 0 with size 582560
```

in this PR:

```sh
 sandbox/mwe/5493_montage_index_error.py ✓                                                100% ██████████
-------------------- generated xml file: /home/sik/code/mne-python/junit-results.xml --------------------
======================================= slowest 20 test durations =======================================
1.34s setup    sandbox/mwe/5493_montage_index_error.py::test_foo
0.02s call     sandbox/mwe/5493_montage_index_error.py::test_foo

(0.00 durations hidden.  Use -vv to show these durations.)

Results (1.55s):
       1 passed
```

**Comment by massich** [comment]
This PR goes after #6047 and misses whatsnew

**Comment by massich** [comment]
```sh
rootdir: /home/sik/code/mne-python, inifile: setup.cfg
plugins: timeout-1.3.3, sugar-0.9.2, mock-1.10.1, faulthandler-1.5.0, cov-2.6.1
timeout: 30.0s
timeout method: signal
timeout func_only: False
collecting ... 1526

 sandbox/mwe/5493_montage_index_error.py ✓                                       100% ██████████
--------------- generated xml file: /home/sik/code/mne-python/junit-results.xml ----------------
================================== slowest 20 test durations ===================================
1.29s setup    sandbox/mwe/5493_montage_index_error.py::test_foo
0.01s call     sandbox/mwe/5493_montage_index_error.py::test_foo

(0.00 durations hidden.  Use -vv to show these durations.)

Results (1.62s):
       1 passed

Compilation finished at Mon Mar 18 15:10:42
```

It reads without error and recovers 1526 events

**Comment by agramfort** [comment]
thx @massich

**Pull request merged**
