### PR TITLE
MRG: Add raw attribute

### PR DESCRIPTION
**Pull request by Eric89GXL**
Takeover of #3733 based on what we converged on.

Ready for review/merge from my end.

### CODE REVIEW

**Comment by jaeilepp** [comment]
LGTM. Perhaps this should be advertised somewhere?

**Comment by Eric89GXL** [comment]
Ahh yes I can add it to `whats_new.rst`. In the docs it's in the class documentation (https://3244-1301584-gh.circle-artifacts.com/0/home/ubuntu/mne-python/doc/_build/html/generated/mne.io.Raw.html#mne.io.Raw.acqparser), but I'll also add it to `AcqParserFIF`. I don't think we have a dataset suitable for using `AcqParserFIF` in an example yet, though.

**Comment by Eric89GXL** [comment]
@jaeilepp doc fixed. CI failure is unrelated (stupid TVTK bug)

**Comment by agramfort** [comment]
LGTM

**Comment by jaeilepp** [comment]
Thanks @Eric89GXL

**Comment by jjnurminen** [comment]
Thanks @Eric89GXL

I'm thinking about a further enhancement. With this PR, it's still necessary to do:

`raw.acqparser.get_condition(raw, 'category name')`

i.e. you need to supply raw as an argument. However AcqParserFIF could have a raw attribute, which would be set by the RawFIF constructor. Then it could be invoked as 

`raw.acqparser.get_condition('category name')`

raw could still be a kwarg, in case you want to use the conditions defined in the info but get the actual epochs from another raw file.

What do you think?

**Comment by agramfort** [comment]
I don't like that much... too much magic and very specific to FIF /
Neuromag data

**Comment by jjnurminen** [comment]
Well the whole thing is specific to FIF / Neuromag anyway.
Whether it's magic is a matter of taste. To me the repetition is ugly. Anyway, this PR already improves things quite a bit, so I'm fine either way.

**Comment by agramfort** [comment]
how would you do this in a clean way?

**Comment by jjnurminen** [comment]
Tentatively, I was thinking of giving a `raw_parent `attribute to `AcqParserFIF`, and making the `raw` argument of the `get_condition `API call a kwarg defaulting to None. If `raw=None`, get_condition would use the `raw_parent `attribute of the instance.

The `raw_parent `would be set by the RawFIF constructor. (It could also be set by the AcqParserFIF constructor whenever it gets raw as an argument.) If not set, it would default to None and user would have to supply `raw `into the `get_condition `API call.

@Eric89GXL WDYT. Is it too convoluted?

**Comment by agramfort** [comment]
I find it convoluted personally.

**Comment by jjnurminen** [comment]
Point taken @agramfort
But don't you suffer when you see `raw.acqparser.get_condition(raw, 'condition')`?

**Comment by agramfort** [comment]
I can live with it :)

**Pull request merged**
