### PR TITLE
Rename `preload_data` method to `load_data`

### PR DESCRIPTION
**Pull request by teonlamont**

### CODE REVIEW

**Comment by teonlamont** [comment]
related to #2451.

**Comment by agramfort** [comment]
travis is not happy

do we need to deprecate?

**Comment by teonlamont** [comment]
fixed. we don't need a deprecation since it was added during this cycle

**Comment by Eric89GXL** [comment]
LGTM, +1 for merge

**Comment by agramfort** [comment]
+1 for merge.

@dengemann merge if you're happy

**Comment by dengemann** [comment]
Thanks @teonlamont -- great to have a linguist on board for more elegant API design!

**Comment by Eric89GXL** [comment]
@teonlamont on closer inspection, I see that `raw.preload_data()` was added in 0.9:

https://github.com/mne-tools/mne-python/blob/master/doc/whats_new.rst#api-1

Can you open another PR to add it back and deprecate it?

**Pull request merged**
