### PR TITLE
MRG+1, DOC: footer logos

### PR DESCRIPTION
**Pull request by drammock**
- adds Uni-Graz to the footer logos (@cbrnr)
- uses separate file for each logo (so it's easier to add new ones)
- each logo is now clickable, and displays the institution name when hovering

Looks good for me locally; hopefully same on CircleCI

### CODE REVIEW

**Comment by drammock** [comment]
rendering of homepage: https://13556-1301584-gh.circle-artifacts.com/0/dev/index.html

**Comment by drammock** [comment]
rendering of homepage: https://13557-1301584-gh.circle-artifacts.com/0/dev/index.html

**Comment by cbrnr** [comment]
Thanks for adding my institution! Did you want to put the logos in three rows, where Inria is the only logo in the second row? If it is not possible to put them into one row anymore, I'd split them up into two rows.

**Comment by agramfort** [comment]
I agree. +1 for split them up into two rows.

>

**Comment by larsoner** [comment]
> Did you want to put the logos in three rows, where Inria is the only logo in the second row?

It looks like a CSS class problem, probably. Maybe `max-width` needs to be set? For me in chrome dev tools if I add `width=100px` to the Inria `img` I get two rows automatically, so the problem seems to be with that particular image (probably the SVG itself) trying to be 100% width.

**Comment by drammock** [comment]
For me in Firefox with a maximized browser window all logos are on one line, and inria looks fine. I'll test with other browsers after breakfast :)

**Comment by larsoner** [comment]
Chrome:

Screenshot from 2019-06-06 11-10-50

**Comment by drammock** [comment]
switching Inria from SVG to PNG solved the weird issue with Inria being on its own line; not sure what that was all about.  I also added some margins to the logos so they're not so crammed together.  What I can't figure out how to do is prevent the (now taller) footer from overlaying the last bit of the page content...  a `margin-bottom` on the main content container wouldn't be responsive to different window widths, and anyway I can't tell in `layout.html` where I would add an additional class to that `div` in order to target it differently from all the other `.container`s.  What we need is the equivalent of `clear:both`; I've read that `display:table` can be useful in such cases, but that didn't work when editing in the dev console...  I think I'll need help (@larsoner?) to sort this out.

**Comment by drammock** [comment]
actually, I think I got it. Will push a fix after confirming with a local re-build.

**Comment by larsoner** [comment]
FYI if the partial rebuilds are taking a while for you, you probably need https://github.com/numpy/numpydoc/pull/226

**Comment by cbrnr** [comment]
Thanks @drammock!

**Comment by cbrnr** [comment]
Can we backport this so that the changes go live with 0.18.2?

**Comment by agramfort** [comment]
yes. Can you open PR to maint/0.18 branch?

>

**Comment by cbrnr** [comment]
Thanks @larsoner!

**Pull request merged**
