### PR TITLE
fix example plotting montages

### LINKED ISSUE #10738: montage_sgskip.py example doesn't run
When trying to run the example in `examples/visualization/montage_sgskip.py`, I get an exception:

```python
ValueError: A head<->mri transformation matrix (trans) is required to plot head surfaces in head coordinates, `trans=None` is not allowed
```
It runs if I pass `trans='fsaverage'` but I'm not sure this is how this example intended to behave (as the BEM is based on a sphere here).

@agramfort care to take a look?

### PR DESCRIPTION
**Pull request by agramfort**
closes #10738

cc @hoechenberger

### CODE REVIEW

**Comment by hoechenberger** [comment]
Perfect!

Any idea why we didn't catch this earlier? Our doc builds should have failed, no?

**Review by hoechenberger — APPROVED** [review]

**Comment by agramfort** [comment]
sgskip in the name examples/visualization/montage_sgskip.py means it's not executed by sphinx-gallery

**Comment by hoechenberger** [comment]
Oh! I was already wondering about that weird name!!

**Comment by hoechenberger** [comment]
Thanks @agramfort!

**Pull request merged**
