### PR TITLE
Remove bad montage

### PR DESCRIPTION
**Pull request by cbrnr**
Remove bad montage file as discussed in #4403 @larsoner @dengemann. This file wasn't removed in #4400 but only renamed.

### CODE REVIEW

**Comment by agramfort** [comment]
can you see why CIs are red?

**Comment by cbrnr** [comment]
Could have been a doctest. Let's see if it works now.

**Comment by cbrnr** [comment]
No idea why CircleCI failed, could you restart it please?

**Comment by agramfort** [comment]
done

**Comment by agramfort** [comment]
forget about circle ci

thx @cbrnr

**Pull request merged**
