### PR TITLE
MRG, DOC: artifact repair with SSP tutorial

### PR DESCRIPTION
**Pull request by drammock**
This overhauls / expands the "artifact repair with SSP" tutorial.  @larsoner @agramfort who would be a good reviewer for this content?

Note: there are a few `TODO` comments in the tutorial source code with questions that I couldn't find answers to. The tutorial is written so that it reads fine right now, so adding answers to those questions is not necessarily a blocker (though I think it would improve the tutorial).

### CODE REVIEW

**Comment by drammock** [comment]
Rendered tutorial: https://15025-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/preprocessing/plot_50_artifact_correction_ssp.html

**Comment by larsoner** [comment]
You should probably add an average ref first before computing the ECG and EOG projectors for EEG.

In the section:

https://15025-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/preprocessing/plot_50_artifact_correction_ssp.html#repairing-ecg-artifacts-with-ssp

The EEG channels are spread quite a bit. If adding the average ref doesn't fix it, I'd add a `ecg_evoked.apply_baseline((None, None))`.

The same thing also happens in the EOG section.

Otherwise LGTM

**Comment by drammock** [comment]
rendered tutorial: https://15043-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/preprocessing/plot_50_artifact_correction_ssp.html

I left in the first butterfly with the widely-spread EEG channels, then added a second one after baselining, for pedagogical effect. Setting an average ref. made no difference (it just shifted the spread of channels down by ~100 uV). Just waiting for Travis at this point.

**Comment by larsoner** [comment]
Awesome, thanks @drammock

**Comment by agramfort** [comment]
you left this one
https://15043-1301584-gh.circle-artifacts.com/0/dev/_images/sphx_glr_plot_50_artifact_correction_ssp_012.png
on
purpose?

>

**Comment by drammock** [comment]
@agramfort yes, left it on purpose, so people know how to remedy it if they see that in their own data. The text right after it says 

> Looks like the EEG channels are pretty spread out; let’s baseline-correct and plot again:

**Comment by agramfort** [comment]
👌

**Pull request merged**
