### PR TITLE
[IGNORE] Ensure downstream compliance from PyVista

### PR DESCRIPTION
**Pull request by banesullivan**
**Please ignore!** 

This PR is to make sure we are not breaking anything downstream with some upcoming, major changes to PyVista in https://github.com/pyvista/pyvista/pull/272

I'm simply having your CI's install PyVista from a certain branch to see if anything breaks over here

Thanks!

### CODE REVIEW

**Comment by banesullivan** [comment]
@GuillaumeFavelier - is that failing test unrelated to PyVista?

**Comment by drammock** [comment]
@banesullivan it looks like an unrelated timeout error; I've triggered a re-run to make sure.

**Comment by banesullivan** [comment]
Thanks!

**Comment by banesullivan** [comment]
Looks good! Thanks!

**Pull request closed without merging**
