### PR TITLE
ENH: Add splash for coreg gui

### PR DESCRIPTION
**Pull request by larsoner**
The coreg gui loads a lot of stuff -- it takes 3-4 sec to come up on my system (see below). This PR adds a splash screen so that the user knows that something is happening:

https://user-images.githubusercontent.com/2365790/156785735-e83ee9cb-1c62-4701-9622-3116724c2543.mp4

@hoechenberger if you agree this is good, I could make a quick proper MNE splash screen, since the one here is just a placeholder. Maybe the MNE logo on a white background with rounded corners?

cc @marsipu in principle you could use this for mne-qt-browser, too, but your GUI always comes up very quickly so I don't think it's necessary...

### CODE REVIEW

**Comment by marsipu** [comment]
@larsoner This looks great. 
Maybe we can add this to mne-qt-browser when we implement command-line support via `mne browse_raw`

**Comment by larsoner** [comment]
> mne browse_raw

This already works since it's just a backend thing:


https://user-images.githubusercontent.com/2365790/156796608-3cbd8da9-2b08-4b5e-b0ad-7008e180dc22.mp4

By my estimation it's about 2.5 sec from start until it shows up:


https://user-images.githubusercontent.com/2365790/156797281-105a0518-6a9b-4b31-b046-cc2f5fe38116.mp4

> (EDIT: Starting up the python interpreter will probably add a bit to startup time, right?)

Yes, that and a Qt application. But unfortunately, both of these have to complete *before* the splash is shown. So really it's useful if displaying the window itself is the slow part. Looks like it does at least show up if I add it to mne-qt-browser:

https://user-images.githubusercontent.com/2365790/156797350-80614f09-0795-4c98-af1e-5a885d7a23bd.mp4

**Comment by hoechenberger** [comment]
Nice work, @larsoner!

Can we make the splash screen

- larger and
- a square or rectanlge?

e.g.

image

**Comment by larsoner** [comment]
How about:

Screenshot from 2022-03-04 11-54-38

**Comment by agramfort** [comment]
looks great !

**Comment by larsoner** [comment]
@GuillaumeFavelier feel free to merge if you're happy. @hoechenberger we can always improve the splash image in follow-up PRs!

**Comment by GuillaumeFavelier** [comment]
wait 3000 additions? I have to look.

**Comment by larsoner** [comment]
That's just the `.qrc`. Feel free to generate on your system and push, in theory there should be fewer lines changed that way since I think you generated the last one

**Comment by GuillaumeFavelier** [comment]
oh. `resources.py` of course

**Comment by hoechenberger** [comment]
@larsoner Amazing work, I love it!

**Comment by hoechenberger** [comment]
> wait 3000 additions? I have to look.

Well, Eric's been busy, you see! 🤣

**Review by GuillaumeFavelier — APPROVED** [review]
It works great for me :ok_hand: !

**Comment by GuillaumeFavelier** [comment]
Thank you @larsoner

**Comment by hoechenberger** [comment]
Speaking of visual feedback while we're doing something: mme sys_info easily takes 20, 30 seconds on my CI outer and sometimes a minute or even several minutes (!) on certain network-based installs I'm using. And I think on my M1 Mac it took about 3 minutes to return anything in the first run (through Rosetta 2). Any chance we could at least let users know that we're still alive there?
Additionally to all those imports, sometimes Matplotlib starts happily recreating its font caches which takes additional time. 🤦‍♀️

**Comment by GuillaumeFavelier** [comment]
Do you think a progress bar in the terminal would help?

**Comment by larsoner** [comment]
I think it's a bit of a corner case in that *users* will typically not hit because vtk and mpl are super slow for their first import (only). You but it was dev using CIs because they have fresh envs all the time. So I'd rather not make this a lot more complicated.

One easy change is to make outputs incremental as we accumulate each but of information. The way it works now, we construct the whole string and then print it all at once. Doing it incrementally will also add a tiny hint of information, namely what takes so long.

**Comment by larsoner** [comment]
... I can make a quick PR for this today

**Comment by GuillaumeFavelier** [comment]
> One easy change is to make outputs incremental as we accumulate each but of information

This sounds reasonable to me, what do you think @hoechenberger ?

**Pull request merged**
