### PR TITLE
MRG ENH: Update font

### PR DESCRIPTION
**Pull request by Eric89GXL**
Gives us a slightly nicer doc font.

### CODE REVIEW

**Comment by agramfort** [comment]
If you say it's nicer...

**Comment by Eric89GXL** [comment]
Did you build with it and check it out?

**Comment by Eric89GXL** [comment]
I'm not sure whether you're just trusting my judgment, or if you took a look and actually don't like it. If it's the latter I don't think we can be friends anymore.

**Comment by agramfort** [comment]
I trust you blindly before sleeping ...

**Pull request merged**
