### PR TITLE
MAINT: Avoid failures due to distutils

### PR DESCRIPTION
**Pull request by larsoner**
Should fix the failure observed by @wmvanvliet in https://github.com/mne-tools/mne-python/pull/11046/

### CODE REVIEW

**Review by wmvanvliet — APPROVED** [review]

**Comment by larsoner** [comment]
@alexrockhill I think it's a sphinx-gallery bug with the new API usage that this emits a warning. We shouldn't include graphs that create warnings, as building Sphinx with warnings-as-errors will create problems like here. I'm going to disable the API usage for now, but when you get a chance can you think about the right way to deal with this at the sphinx-gallery end?

**Comment by larsoner** [comment]
... also, I don't see `show_api_usage` in our `conf.py`, the default appears to be False in the SG code, yet we end up with API usage shown here anyway. This seems like a bug -- we should have to set it to `True` here to enable it

**Review by agramfort — APPROVED** [review]

**Comment by alexrockhill** [comment]
`show_api_usage` is just for the used entries, the unused entries are always shown...

**Comment by alexrockhill** [comment]
I'm not seeing the CI build failure related to the new graphs. I see the distutils depreciation warning but I don't know how that would be related... the only thing I did was add a graphviz dependency, I don't think that would cause that..

**Comment by larsoner** [comment]
Ahh so `.*` should be what excludes everything... I can put that back in here at some point. Feel free to open a PR to sphinx-gallery to fix `show_api_usage` or I can do it -- but either way it would be good to avoid the warning about the dot graph too big, as it will breaks people's builds like [9dae527](https://github.com/mne-tools/mne-python/pull/11132/commits/9dae5274fbe713fce3b0e0edae264d51fa992357) / https://app.circleci.com/pipelines/github/mne-tools/mne-python/16190/workflows/bec55c76-fb4c-4d93-9139-bac6e982a6f6/jobs/48744 .

This also makes me think we should have a way to disable everything in cases where bugs like this crop up. I wonder if `show_api_usage = False | True | 'unused'` might be a good idea, where False means "disable entirely", True means "used and unused, and 'unused' means "just the unused entries".

**Comment by alexrockhill** [comment]
That sounds good. Do you think just suppress the warning?

**Comment by larsoner** [comment]
That would work, or figure out a way to limit the graph size before it gets too big.

**Pull request merged**
