### PR TITLE
[MRG] Better fix to Scaler.

### PR DESCRIPTION
**Pull request by jaeilepp**
Follow up to https://github.com/mne-tools/mne-python/pull/3828

### CODE REVIEW

**Comment by Eric89GXL** [comment]
LGTM +1 for merge

**Comment by mmagnuski** [comment]
LGTM too

**Comment by agramfort** [comment]
LGTM

merge when Travis is happy

**Comment by Eric89GXL** [comment]
Thanks @jaeilepp

**Pull request merged**
