### PR TITLE
Adding support for Brainvision Analyser header version 2.0

### PR DESCRIPTION
**Pull request by mdovgialo**
TO DO: Add electrode location reading, check the unit multipliers, merge with original function

### CODE REVIEW

**Comment by agramfort** [comment]
@mdovgialo please don't duplicate the full code...

the idea of a PR is that we see the diff with current version of the code and we can integrate it.

are you ok doing this?

thanks heaps

**Comment by teonlamont** [comment]
@mdovgialo, could you share the v2 files so I can see the difference of the file format. we can just change the assert to an if which would handle the difference in versions

**Comment by teonlamont** [comment]
closes #2613

**Comment by agramfort** [comment]
@teonlamont you have sample files in #2613

**Comment by teonlamont** [comment]
closing for #2634

**Pull request closed without merging**
