### PR TITLE
MRG+1: Fix reject check

### LINKED ISSUE #2855: make RawArray fail gracefully
If you run this piece of code:
```py
import mne
import os.path as op
from mne.io import RawArray

raw = mne.io.RawFIF(
    op.join(mne.datasets.sample.data_path(), 'MEG', 'sample',
            'sample_audvis_raw.fif'))

raw_array = RawArray(raw.info, raw[:][0])
```
you get this error:

```py
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/home/mainak/Desktop/fail_gracefull.py in <module>()
      7             'sample_audvis_raw.fif'))
      8 
----> 9 raw_array = RawArray(raw.info, raw[:][0])

/home/mainak/Desktop/projects/mne-python/mne/io/array/array.pyc in __init__(self, data, info, first_samp, verbose)

/home/mainak/Desktop/projects/mne-python/mne/utils.pyc in verbose(function, *args, **kwargs)
    548         with use_log_level(verbose_level):
    549             return function(*args, **kwargs)
--> 550     return function(*args, **kwargs)
    551 
    552 

/home/mainak/Desktop/projects/mne-python/mne/io/array/array.pyc in __init__(self, data, info, first_samp, verbose)
     36     def __init__(self, data, info, first_samp=0, verbose=None):
     37         dtype = np.complex128 if np.any(np.iscomplex(data)) else np.float64
---> 38         data = np.asanyarray(data, dtype=dtype)
     39 
     40         if data.ndim != 2:

/home/mainak/anaconda/lib/python2.7/site-packages/numpy/core/numeric.pyc in asanyarray(a, dtype, order)
    523 
    524     """
--> 525     return array(a, dtype, copy=False, order=order, subok=True)
    526 
    527 def ascontiguousarray(a, dtype=None):

ValueError: could not convert string to float: acq_stim
```
I feel it could fail more gracefully

### LINKED ISSUE #2858: Value error no EOG key in rejection dict
`epochs._reject_setup` returns a ValueError because the `eog` value in the `idx` [dict](https://github.com/mne-tools/mne-python/blob/master/mne/epochs.py#L465) returns an empty list for Vectorview MEEG dataset with 60 EEG channels and EOG61 & EOG62. Debugger shows `idx` contains 60, 102, and 204 elements for `eeg`, `mag`, and `grad` keys. The EOG channels don't appear anywhere in `idx`.

Here is the trace:
 

>  File "/home/ktavabi/Projects/mne-python/mne/utils.py", line 551, in verbose
>     return function(*args, **kwargs)
>   File "/home/ktavabi/Projects/mne-python/mne/epochs.py", line 1863, in __init__
>     on_missing=on_missing, preload_at_end=preload, verbose=verbose)
>   File "/home/ktavabi/Projects/mne-python/mne/epochs.py", line 299, in __init__
>     self._reject_setup(reject, flat)
>   File "/home/ktavabi/Projects/mne-python/mne/epochs.py", line 471, in _reject_setup
>     "%s." % (key.upper(), key.upper()))
> ValueError: No EOG channel found. Cannot reject based on EOG.

### PR DESCRIPTION
**Pull request by Eric89GXL**
Two minor fixes in one PR to (hopefully) save reviewer and CI time.

Closes #2858.
Closes #2855.

### CODE REVIEW

**Comment by agramfort** [comment]
LGTM

+1 for merge with CIs are happy

**Comment by Eric89GXL** [comment]
Any other reviewer have time to look?

**Comment by kingjr** [comment]
LGTM

**Comment by Eric89GXL** [comment]
Thanks for the quick reviews

**Pull request merged**
