### PR TITLE
MRG: Test get_montage on fNIRS data

### PR DESCRIPTION
**Pull request by rob-luke**
#### Reference issue
See https://mne.discourse.group/t/montage-either-not-saved-in-fif-or-not-read/3356

#### What does this implement/fix?
Ensures get_montage() works with fNIRS data

#### Additional information
* The NIRx reader already worked with get_montage, so I added a test to ensure it keeps working.
* Added info[dig] to the SNIRF reader. And added test that get_montage returns data.

I always find the digitisation stuff tricky, so please review critically (as always 😉)

### CODE REVIEW

**Comment by rob-luke** [comment]
@larsoner @agramfort could you please review (assuming CIs go green).

**Comment by rob-luke** [comment]
Damn, I pinged too early. I will look at these errors.

**Review by agramfort — APPROVED** [review]
a what's new entry?

@larsoner merge if happy

thx @rob-luke !

**Comment by larsoner** [comment]
Thanks @rob-luke

**Pull request merged**
