### PR TITLE
MRG: Refactor EDF channel picking

### PR DESCRIPTION
**Pull request by larsoner**
@cbrnr to tackle #1766 I first want to refactor the EDF reader to hold a "sel" of the channels to be used. Can you see if this breaks anything with your set of EDF data files? Tests are passing at least.

### CODE REVIEW

**Comment by cbrnr** [comment]
All good. However, note that if there is a TAL channel, data must be preloaded (otherwise you get this `RuntimeError: EDF+ Annotations (TAL) channel needs to be parsed completely on loading. You must set preload parameter to True.`). I'm not sure if this is relevant for what you want to do.

**Comment by larsoner** [comment]
It won't really be relevant fortunately

**Comment by agramfort** [comment]
@cbrnr feel free to merge then.

**Comment by cbrnr** [comment]
@agramfort I don't have the permission to merge, but you guys go ahead, my test files can still be loaded!

**Comment by agramfort** [comment]
@cbrnr now you should be able to merge :)

**Comment by cbrnr** [comment]
Thanks @agramfort, I'm happy to be part of the team! Thanks @larsoner, PR merged.

**Pull request merged**
