### PR TITLE
MRG: Add "center" option to simulate_sparse_stc

### LINKED ISSUE #3307: Modes for `simulate_sparse_stc`
Currently the `simulate_sparse_stc` function chooses a random vertex in each label to set to the desired signal. It would be useful to also have a mode to use the vertex in each label that is closest (in Euclidean distance) to the center of mass of the label.

I have some stand-alone code that does this and am happy to make the changes to `simulate_sparse_stc`.

### PR DESCRIPTION
**Pull request by Eric89GXL**
~~Needs #3314 merged first.~~

Closes #3307.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
@nfoti can you see if this API would work for your use case and cover #3307?

**Comment by nfoti** [comment]
I think the API looks good, just a couple quick comments:

1. There is a typo in the docstring: to -> to.
2. I envisioned the `center` mode to simulate a signal at the center vertex so that the label values should be ignored. Perhaps it's worth adding in a third mode `weighted` that simulates a signal at all vertices in the label weighted by the label values. Obviously the `center` mode is a special case of this, but I like having the explicit `center` mode for convenience and the more flexible `weighted` mode for more sophisticated things. What do you think?

**Comment by Eric89GXL** [comment]
> Perhaps it's worth adding in a third mode weighted that simulates a signal at all vertices in the label weighted by the label values.

Yeah that's reasonable. Maybe you can make that PR after this one is in? I agree `center` is still useful even though it's a special case of the other one.

**Comment by nfoti** [comment]
Yes, I'll make PR for `weighted` mode after this is merged.

**Comment by Eric89GXL** [comment]
@agramfort ready for review/merge from my end, then

**Comment by agramfort** [comment]
may I ask for an example update or some piece of doc? maybe a tutorial on simulating data?

**Comment by Eric89GXL** [comment]
@nfoti is doing that in a follow up PR if that's okay

**Comment by agramfort** [comment]
okay !

**Pull request merged**
