### PR TITLE
[MRG] raw.plot_psd() with flat channel

### PR DESCRIPTION
**Pull request by christianbrodbeck**
Currently when running `raw.plot_psd()` with data containing a dead channel an empty plot is created. Should the fix treat the dead channel like a normal channel or raise a warning or error?

screen shot 2016-06-26 at 1 33 09 pm

### CODE REVIEW

**Comment by agramfort** [comment]
aren't you supposed to mark such channels as bad?

**Comment by christianbrodbeck** [comment]
Right, but if you forget to mark them as bad mne should not break but rather help figure out what's wrong, hence I am suggesting to warn or raise an error.

**Comment by agramfort** [comment]
ok so I'll let you come up with a good way to do this :)

**Comment by christianbrodbeck** [comment]
ok :) raising an error now...

**Comment by agramfort** [comment]
LGTM

any other opinion?

**Comment by jona-sassenhagen** [comment]
I'm only wondering if this check should be made more generally for other plotting functions. I sometimes do something wrong and end up trying to plot nan ERPs.

**Comment by Eric89GXL** [comment]
Perhaps, but that can be a follow-up PR. We probably want to use `np.isfinite` instead of `np.isinf`, for example, since `np.isfinite` will also catch NaN.

**Comment by dengemann** [comment]
Seems ok to me, but let' make sure not to implement it too high-level, down-stream, maybe useful in many other locations. To be checked.

**Comment by christianbrodbeck** [comment]
@Eric89GXL @dengemann are you making suggestions for this PR or discussing a more general solution?

**Comment by Eric89GXL** [comment]
Future PR for isfinite is fine

**Comment by agramfort** [comment]
thx @christianbrodbeck

**Pull request merged**
