### PR TITLE
added scipy function to avoid overflow

### PR DESCRIPTION
**Pull request by CarinaFo**
scipy.special.expit function takes care of overflow issues. 
#10650

### CODE REVIEW

**Review by mscheltienne — COMMENTED** [review]
I'm not sure what it is, but you added a massive `e` file. Can you please remove it?

**Comment by drammock** [comment]
hah. In fact, `scipy` is exactly one of those packages where we *enforce* doing it the way I suggested, because its submodules can be fairly big / slow to load. There's a test for it that is failing:

https://github.com/mne-tools/mne-python/runs/7091388874?check_suite_focus=true#step:12:3513

in the test error, "un-nested" means the import is at the top of the file instead of "nested" inside the function that uses it. So to "nest" the import you should put it here: 

https://github.com/mne-tools/mne-python/blob/c72cdaf002b5ecae75cc5f525e224bcac153acba/mne/preprocessing/infomax_.py#L103

**Review by agramfort — COMMENTED** [review]
diff looks good but can you see why CIs fail?

**Comment by drammock** [comment]
> diff looks good but can you see why CIs fail?

see my prev comment.

**Review by drammock — APPROVED** [review]

**Comment by drammock** [comment]
thanks @CarinaFo!

**Pull request merged**
