### PR TITLE
WIP: Make morphed source spaces easier

### PR DESCRIPTION
**Pull request by larsoner**
Need to:

- [x] Get updated morphed source space from MNE-C into `mne-testing-data`, ~~but still keep old one for testing~~
- [x] Mimic old `src` versions in tests by removing newly added fields
- [ ] Set `SourceEstimate.vertices` using `vertno_ord`
- [ ] Ensure we don't require `SourceEstimate.vertices` to be sorted for anything
- [ ] Write note in `to_original_src` that it's only needed for old source spaces
- [ ] Add check in `to_original_src` that it does just sanity checks if new source spaces are used (or otherwise fix it)
- [ ] Add tests for modern morphed source spaces in `test_morphed_source_space_return`
- [ ] Update `sample` data
- [ ] Update source-space morphing example not to use `to_original_src`

### CODE REVIEW

**Comment by larsoner** [comment]
@agramfort I realized there is a problem with our grand plan. At the end if you do (using `inv`s computed using `src`s that have been morphed from `fsaverage`):
```
stc_1 = apply_inverse(evoked_subj_1, inv_subj_1)
stc_2 = apply_inverse(evoked_subj_2, inv_subj_2)
```
We do have that `stc_1.data` and `stc_2.data` are aligned properly.

However, if you do:
```
stc_sum = stc_1 + stc_2
```
The `vertices` will not be the same, and the `stc.subject` will not be the same, so it will fail our sanity checks.

Also, there is no guarantee that `stc_1.data` and `stc_2.data` will even have the same number of vertices (or worse, they might have the same number but will no longer be matched), since the BEMs for subject 1 and subject 2 might remove source space vertices from the source spaces used for subject 1 and subject 2.

So I wonder if what we should do is still advocate the use of `to_original_src`, which does set the subject name to the original source space's subject name, etc., and not bother with this reordering business (though we could still use it as a speedup / shortcut somewhere maybe).

**Comment by agramfort** [comment]
hum....

yes mindist in forward will be a problem...

could we make the logic if subject changing earlier in the pipeline?
basically convert the forward to an fsaverage forward and then you would
get stcs with subject == fsaverage with apply_inverse?

**Comment by larsoner** [comment]
> could we make the logic if subject changing earlier in the pipeline?

I don' think so, we don't store the vertices of the original subject's source space so we can't make the `fsaverage` STC. Plus I think we want the option of viewing on the actual subject's surfaces, as well as `fsaverage`, which means we need a way to switch between the representations... which is exactly what `to_original_src` does.

**Comment by agramfort** [comment]
hum... we need another call to brainstorm on this one.

**Pull request closed without merging**
