### PR TITLE
MRG, ENH: Speed up morph map creation

### PR DESCRIPTION
**Pull request by larsoner**
Speed up morph map generation ~~4x~~ ~10x using `numba` and changes to `_compute_nearest` calls. This code:
```
import time
import mne
subjects_dir = mne.datasets.sample.data_path() + '/subjects'
t0 = time.time()
mne.surface._make_morph_map('sample', 'fsaverage', xhemi=False,
                            subjects_dir=subjects_dir)
print(time.time() - t0)
```
- On `master` takes ~18 sec
- After refactoring to be a tiny bit faster takes 17 sec (what people will get without `numba` installed)
- On first run with numba takes ~~6~~ ~5 sec (includes compilation time)
- On subsequent runs takes ~~2.5~~ ~1.7 sec (no longer needs to compile)

### CODE REVIEW

**Comment by agramfort** [comment]
is the new code slower when numba is not available?

**Comment by larsoner** [comment]
No it's 17s instead of 18s

**Comment by larsoner** [comment]
On my macOS laptop, the same code snippet:

- `master`: 27.9 sec
- This PR without numba: 27.1 sec
- This PR with numba, first run: 11.2 sec
- This PR with numba, subsequent runs (because the compilation is cached): 5.7 sec

**Comment by larsoner** [comment]
... and 2.5 sec on my Linux machine now cut down to 1.76 sec by using cKDTree instead of BallTree in the nearest step.

I think I'll stop optimizing now :)

**Comment by agramfort** [comment]
ok I just tested. It works indeed much faster. 2 things:

- numba should be added to mne.sys_info() (note also that vtk + pyvista should be added too cc @GuillaumeFavelier )
- check that numba version is actually >= 0.4 on import?
- do we have 2 codes (with our without numba) tested in our CIs?

thx @larsoner !

**Comment by larsoner** [comment]
> do we have 2 codes (with our without numba) tested in our CIs?

Yes the `minimal` dependencies version should test it

**Comment by larsoner** [comment]
Okay, next up I'll probably add `mne make_morph_maps`

**Pull request merged**
