### PR TITLE
fix: proper channel-type-specific vmin/vmax in topo image plots

### LINKED ISSUE #6112: question: puzzling results in epochs.plot_topo_image
Setup:
```
import os
import mne
sample_data_folder = mne.datasets.sample.data_path()
sample_data_raw_file = os.path.join(sample_data_folder, 'MEG', 'sample',
                                    'sample_audvis_raw.fif')
raw = mne.io.read_raw_fif(sample_data_raw_file, preload=True, verbose=False)
events = mne.find_events(raw, stim_channel='STI 014')
epochs = mne.Epochs(raw, events, preload=True)
```
I expected these two options to yield the same results, but they're very different:
```
# OPTION 1
epochs.copy().pick_types(meg=False, eeg=True).plot_topo_image()
```
Figure_1
```
# OPTION 2
eeg_layout = mne.channels.find_layout(raw.info, ch_type='eeg')                                                            
epochs.plot_topo_image(layout=eeg_layout)
```
Figure_2

Is the difference here intentional, or a bug?

### PR DESCRIPTION
**Pull request by drammock**
closes #6112 

NOTE: @massich and I are doing something special with this PR; everyone else please ignore for now.

### CODE REVIEW

**Comment by larsoner** [comment]
This pull request **introduces 2 alerts** when merging a11ac3992cd2cda2346dd871713fbb7d1829415c into 5a9ae3c3d66b6275fffec217cf560acf651913d7 - [view on LGTM.com](https://lgtm.com/projects/g/mne-tools/mne-python/rev/pr-5459cc1fb3f15f01a8ff02577a9ac20de553f5bd)

**new alerts:**

* 2 for Variable defined multiple times

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by drammock** [comment]
closing, will re-open a different PR.

**Comment by larsoner** [comment]
This pull request **introduces 2 alerts** when merging f9b8d463b7884b06746b22f9f537c1ad9076ae92 into 5a9ae3c3d66b6275fffec217cf560acf651913d7 - [view on LGTM.com](https://lgtm.com/projects/g/mne-tools/mne-python/rev/pr-222898c8cb86d289f9cb75977dc761080a809b63)

**new alerts:**

* 2 for Variable defined multiple times

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by drammock** [comment]
replaced by #6225

**Pull request closed without merging**
