### PR TITLE
FIX KIT reader in Maint/0.13

### PR DESCRIPTION
**Pull request by christianbrodbeck**
Maintenance release to fix KIT reader for old files (#3721)

Thanks @agramfort, should I update the version number? Add a note on 0.13.1 to whats_new?

### CODE REVIEW

**Comment by agramfort** [comment]
thx @christianbrodbeck 

shall we do a maint release now?

**Comment by christianbrodbeck** [comment]
From my part yes, this was the issue that I want to fix.

**Comment by agramfort** [comment]
I just pushed a 0.13.1 version on pypi

https://pypi.python.org/pypi/mne/0.13.1

**Comment by christianbrodbeck** [comment]
Great, thanks!!

**Pull request merged**
