### PR TITLE
MRG: Fix example [circle full]

### PR DESCRIPTION
**Pull request by Eric89GXL**
This should fix the recent CircleCI failure.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
All better, ready for review/merge from my end

**Comment by jaeilepp** [comment]
Thanks @Eric89GXL

**Comment by jaeilepp** [comment]
Circle seems fixed, but I just noticed that [Travis](https://travis-ci.org/mne-tools/mne-python/jobs/196500046) throws a huge amount of deprecation warnings
``DeprecationWarning: use "HasTraits.trait_set" instead``

**Comment by jaeilepp** [comment]
And a quick debug reveals that these are invoked by calls from mayavi, so nevermind.

**Comment by Eric89GXL** [comment]
Yeah, there might be some way to suppress them if we're careful, e.g. by doing some `stdout` / `stderr` catching while doing imports. But it's probably overkill. We can just wait until they get their libraries in order.

**Pull request merged**
