### PR TITLE
MINOR use _check_preload to check preload in ica

### LINKED ISSUE #4980: Minor: different errors for failure to preload?
This is a bit confusing:
`ValueError: Epochs must be preloaded to apply ICA`
`RuntimeError: raw.filter requires raw data to be loaded. Use preload=True (or string) in the constructor or raw.load_data().`

Maybe a preload-related failure should always give the same error (and always give the `inst.load_data()` hint).

### PR DESCRIPTION
**Pull request by jona-sassenhagen**
closes #4980

### CODE REVIEW

**Comment by jona-sassenhagen** [comment]
How bad can one person be at being PEP8 compliant?

**Comment by larsoner** [comment]
I'd imagine that most people using an editor without built-in PEP8 checking would be. I assume you're in that camp? :) 

If you already have built-in PEP8 checking, I don't know what to tell you...

**Comment by jona-sassenhagen** [comment]
I'm using PyCharm and it has all kinds of bells and whistles, reminding me the milk in the fridge is getting stale every 5 minutes, and I just crank up the Wu Tang and ignore all the warning lights.

You don't need to tell me anything :(

**Comment by jona-sassenhagen** [comment]
Good now.

**Comment by agramfort** [comment]
thx @jona-sassenhagen

**Pull request merged**
