### PR TITLE
MRG, DOC: Bump theme version

### PR DESCRIPTION
**Pull request by drammock**
a few recent changes to `pydata-sphinx-theme` allow us to simplify things on our end:

- they've implemented a comprehensive system-native font stack.  Consequently I have un-vendored our webfonts to speed up page load times.  Our site now continues to use Source Sans Pro and Source Code Pro if they're present on the user's system, and will fall back to a system-appropriate default otherwise.
- they've improved how navbar icon links (top right corner) are handled. This greatly simplifies our template override `doc/_templates/docs-navbar.html`

Other changes:
- CSS variables defined by the theme now all start with `--pst-`
- adds icon link to our Discord server
- small CSS fix so our in-text sidebar notes get done properly
- update the font versions that Circle uses

### CODE REVIEW

**Comment by hoechenberger** [comment]
The "sidebar fix" from ff23d41 could use a little padding at the bottom:

Screen Shot 2021-03-13 at 21 22 18

Also wondering if offering to make this box collapsible could be a good idea?

**Comment by hoechenberger** [comment]
How about:

```css
.sidebar {
  background-color: rgba(var(--pst-color-info)), 0.1);
  border: 1px solid rgb(var(--pst-color-info)));
  border-radius: 4px;
  padding: 1em 1em 0 1em;
  margin-bottom: 2rem;
  width: 90%;
}
```
?

**Comment by drammock** [comment]
hmm, circle build is not matching what I saw locally @hoechenberger.  I'm not surprised you had complaints about it :)  I'll see what went wrong.

**Comment by drammock** [comment]
OK well, I am stumped.  the `.. sidebar::` directive on *the sphinx site itself* is rendered as a `div` tag with class `sidebar`.  The same happens locally for me.  But on our Circle server, it gets rendered as an `aside` tag.  A solid hour of comparing package versions, searching docs, and grepping source trees has me no closer to figuring out why this difference exists or what is causing it.  So I'm just going to apply the CSS style to both `div.sidebar` and `aside.sidebar` and be done with it.

**Comment by drammock** [comment]
OK, [it's working now](https://25744-1301584-gh.circle-artifacts.com/0/dev/install/pre_install.html) @hoechenberger:

Screenshot_2021-03-13_17-21-28

**Comment by drammock** [comment]
turns out that `div` -> `aside` was a change in the HTML5 writer of [docutils v0.17](https://docutils.sourceforge.io/RELEASE-NOTES.html#release-0-17).

**Comment by drammock** [comment]
CI failures are LGTM's "cannot build merge commit" snafu, and a failure of `test_make_screenshot[pyvista]` on macOS py3.8

Ready for review/merge

**Review by agramfort — APPROVED** [review]

**Comment by agramfort** [comment]
thx @drammock

**Pull request merged**
