### PR TITLE
MRG: PyQt5.10

### PR DESCRIPTION
**Pull request by larsoner**
I expect this to break AppVeyor, let's see. If it does we can do something special there. I'll test locally with a Windows VM to see if it works for users.

### CODE REVIEW

**Comment by larsoner** [comment]
Okay 5.10 breaks things on Windows for users, not just AppVeyor. Updated to add a note for OSX users that they need to update PyQt with `pip` manually :(

**Comment by larsoner** [comment]
Updated instructions:

https://7923-1301584-gh.circle-artifacts.com/0/html/install_mne_python.html

**Comment by larsoner** [comment]
@cjayb @jasmainak or anyone else (@massich @dengemann @christianbrodbeck ?) on OSX, does this give you a working setup? We need to sort this out before we can officially release.

In particular doing on OSX:
```
$ conda env create - f environment.yml
$ source activate mne
$ python -c "from mayavi import mlab; mlab.test_plot3d(); mlab.show()"
```
Should produce a black window. Then doing:
```
$ pip install --upgrade pyqt5>=5.10
$ python -c "from mayavi import mlab; mlab.test_plot3d(); mlab.show()"
```
Should produce the standard, interactive `test_plot3d` output.

**Comment by larsoner** [comment]
(I have done this locally on my macOS High Sierra machine and it works, but one data point is probably not enough here)

**Comment by agramfort** [comment]
I can replicate on Sierra.

**Comment by agramfort** [comment]
thx @larsoner

**Comment by jasmainak** [comment]
late to the party, but anyway I don't have mac :)

**Pull request merged**
