### PR TITLE
MRG, BUG: Fix sphere glyphs

### LINKED ISSUE #8192: BUG: Arrows gone in mixed norm plotting
Glyph in glass brain in : 

https://mne.tools/dev/auto_examples/inverse/plot_time_frequency_mixed_norm_inverse.html#sphx-glr-auto-examples-inverse-plot-time-frequency-mixed-norm-inverse-py

do not show up. I should see 2 sources.

_Originally posted by @agramfort in https://github.com/mne-tools/mne-python/pull/8188#issuecomment-685065216_

### PR DESCRIPTION
**Pull request by larsoner**
Closes #8192

In this PR on mayavi:

Screenshot from 2020-09-01 16-28-42

pyvista:

Screenshot from 2020-09-01 16-29-02

these look different but I think it might just be a subtle angle/perspective difference (?), here's a different angle:

Screenshot from 2020-09-01 16-29-55
Screenshot from 2020-09-01 16-30-29

@GuillaumeFavelier can you look and see if the difference is meaningful and if necessary push commits to fix it? Also might be a good idea to check the code for any other instances of `if/elif/elif` and change them to `if/elif/else` with an `assert` like I did here (preferably with a user-friendly `_check_option` so that the `assert` is just an internal sanity check).

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
Many thanks for refactoring `quiver3d()`, it greatly helps! 

There is indeed a difference on how the glyph is centered.

*lower opacity on the glyph, center with a red sphere*:

mayavi | pyvista
---------|-----------
image | image

Of course we want the backends to be consistent. By default, I will assume that Mayavi is the desired result and modify `_pyvista.py` accordingly.

**Comment by GuillaumeFavelier** [comment]
Using the `sphere` mode, I have second thoughts though...

Mayavi | PyVista
------|------
image | image

**Comment by GuillaumeFavelier** [comment]
Ideally, I think we want the glyphs to behave like Mayavi in `cone` mode but like PyVista if the `sphere` mode is selected right? @agramfort , @larsoner

**Comment by hoechenberger** [comment]
> Ideally, I think we want the glyphs to behave like Mayavi in `cone` mode but like PyVista if the `sphere` mode is selected right? @agramfort , @larsoner

I would very much say: **yes**

**Comment by hoechenberger** [comment]
No wait. The center of the sphere should be at the exact location where the "red dot / origin" of the cone is. I cannot see in the pics whether for pyvista, the center of the sphere is shifted "to the outside" of the brain, away from the surface. This is not what we want: the center should rest on the surface.

**Comment by GuillaumeFavelier** [comment]
For PyVista, the center of the spheres and the red dots are at the position. Does it answer your question? I can push a test commit and you can verify.

**Comment by hoechenberger** [comment]
> For PyVista, the center of the spheres and the red dots are at the position. Does it answer your question? I can push a test commit and you can verify.

Great, that answers my question.

**Comment by GuillaumeFavelier** [comment]
I pushed d2fc5fb for testing purpose only. You can take a look @hoechenberger, @larsoner. It could be reverted before merge.

x | Mayavi | PyVista
---|---|----
**cone** | image | image
**sphere** | image | image

**Comment by GuillaumeFavelier** [comment]
I pushed 8d51365 to make the cone radius consistent too:

Mayavi | PyVista
---------|--------
image | image

**Comment by larsoner** [comment]
That looks right to me. For quiver matplotlib has the "pivot" argument, but we should just document that it's always the tail for arrows and cones and center for sphere (and make sure that this is the case). Not sure which cylinder should be, probably tail.

**Comment by hoechenberger** [comment]
> Not sure which cylinder should be, probably tail.

I would say tail, too, to be consistent with cones.

**Comment by GuillaumeFavelier** [comment]
For `plot_sparse_source_estimates()` no `cylinder` mode is available but in general, when `quiver3d()` is used with `cylinder`, there is a `glyph_center` parameter to change the 'pivot'.

**Comment by larsoner** [comment]
Ahh okay, so no changes needed then I think!

**Comment by agramfort** [comment]
@larsoner and @GuillaumeFavelier merge if you're happy

thx

**Review by hoechenberger — APPROVED** [review]

**Pull request merged**
