### PR TITLE
FIX run_ica():  pass eog_criterion parameter

### PR DESCRIPTION
**Pull request by christianbrodbeck**
Small bug

### CODE REVIEW

**Comment by Eric89GXL** [comment]
LGTM, can you add a line to the BUG section of whats_new.py?

**Comment by christianbrodbeck** [comment]
Added a line to whats_new

**Comment by agramfort** [comment]
+1 for merge when CIs are happy

**Comment by dengemann** [comment]
@christianbrodbeck are you actually using this function? It has been around for longtime but it's development got marginalised. To me it's dead code. I might need to take a look again and see if we can improve it based on more recent experiences and external 3rd party code.

**Comment by Eric89GXL** [comment]
@dengemann should we consider deprecation?

**Comment by christianbrodbeck** [comment]
Hm, I was just about to use it after someone in the lab told me he used it. Would you just use ICA directly? Should it be deprecated if it's not maintained?

**Comment by dengemann** [comment]
>  Should it be deprecated if it's not maintained?

Maybe we can just update it. What is instead maintained and works great on many data is this: 

https://github.com/dengemann/meeg-preprocessing/blob/master/meeg_preprocessing/preprocessing.py#L120

**Comment by Eric89GXL** [comment]
Are there are two equivalent pipelines? It would be nice if we could go with one suggested way.

**Comment by dengemann** [comment]
I think the ``run_ica`` is actually a neat flexible pipeline function, the defaults are not good though and outdated. We could carry over the strategies that turned out to have worked well. But I cannot reall see how much effort it would take. The other pipeline also is very neat at reporting and does nice plots and gives you summary statistics of amplitude ranges. `run_ica` was something I wrote very long time ago.

**Comment by christianbrodbeck** [comment]
Thanks @dengemann I will work with this instead. Should there be a note in the documentation about the defaults?

**Comment by dengemann** [comment]
> Should there be a note in the documentation about the defaults

I think what we should probably do is refactor `run_ica` a bit, I would have some ideas for a general detection API that has different slots that can be used.
The default slots should be the code I have in the other repo. Other slots could later be added. We could have a `preprocessing/workflows.py` module for that. Then you could collect in a dictionary with key as method and values as components the different proposals for artefacts and do with it later what you want. The only problem here would be that it takes an afternoon at leas, which I don't have at the moment. I'm happy to work together with anyone of you who wants to do this.

**Comment by agramfort** [comment]
I think we should merge this as it's a bug fix

**Comment by dengemann** [comment]
Ah yes I agree. My comments were just for future dev and concerning deprecation.

**Pull request merged**
