### PR TITLE
MAINT: Make public Figure3D class

### LINKED ISSUE #9961: BUG: 3D functions return non-public members
@GuillaumeFavelier we need a public equivalent to mayavi.core.api.Scene for whatever we currently return for create_3d_figure that users can pass around to 3D functions as fig=fig etc. Can you work on this separately? Then we can `git grep "PyVista renderer"` and know all the places we need to put in a reference that links properly.

*adapted from https://github.com/mne-tools/mne-python/pull/9945#issue-772527626*

### LINKED ISSUE #10343: BUG: URL broken
@teonbrooks what URL do you want? Currently [we get](https://app.circleci.com/pipelines/github/mne-tools/mne-python/12860/workflows/883d7bf1-72a5-4036-a399-343929e59811/jobs/41625):
```
generated/_names.rst:11: [broken] https://teonbrooks.github.io: 404 Client Error: Not Found for url: https://teonbrooks.github.io/
```

### PR DESCRIPTION
**Pull request by larsoner**
Closes #9961
Closes  #10343

1. I decided to make the abstract base class public, as we can't make `PyVistaFigure3D` for example public, because we can't necessarily import it based on our import mechanics in `backends`. I don't think this is a problem in practice.
2. I also did something a bit weird, which was to make what was in `__init__` go in a new `_init`. This makes it so that we don't have to document all the params in the docstring, and it becomes even clearer that users are not supposed to instantiate directly, and instead should use `create_3d_figure`.
3. Fixed a bug with `plot_sparse_source_estimates` where what we returned (tuple of `(vtkActor, PolyData)`) did not match what we said we returned (PyVista surface). Now we just return the Figure3D, and people can query the `fig.plotter` instance to get a list of actors for example if they want.

There is a remaining bug where you can pass `scene=False` to get the `Renderer` instance. I documented this as an advanced option for now. We do unfortunately make use of it in at least one example/tutorial, so it'll be a bit more work to fix that. But in the meantime I think this is good incremental progress.

@GuillaumeFavelier can you look and see if it makes sense to you?

### CODE REVIEW

**Comment by larsoner** [comment]
I'm also going to get rid of `__hash__` from our public docstrings. For about 40 of our classes, we see an entry for `__hash__` that is unhelpful:

Screenshot from 2022-02-15 09-27-34

The idea of hashing an object is very advanced -- and it's far more common that the class doesn't have it -- so I don't think it's helpful to keep it in our docs. People who care about these things will probably know to look for `__hash__` when thinking about `hash(obj)`. Removing it, the docs are cleaner:

Screenshot from 2022-02-15 09-32-20

**Comment by GuillaumeFavelier** [comment]
> I'm also going to get rid of __hash__ from our public docstrings.

Do you have to do it in this PR? If 40 classes are involved it might be difficult to track the changes here

**Comment by GuillaumeFavelier** [comment]
Solid changes so far!

> This makes it so that we don't have to document all the params in the docstring

Good idea, `_Figure` was really just a convenient class as old as Renderer itself, we can improve that in another PR.

> Fixed a bug with plot_sparse_source_estimates

Good catch @larsoner !

> We do unfortunately make use of it in at least one example/tutorial,

I'll see how to fix from my end. I do not recall why this was necessary but at the time, it could be for compatibility.

**Comment by larsoner** [comment]
> Do you have to do it in this PR? If 40 classes are involved it might be difficult to track the changes here

All we have to change is `doc/conf.py` and `_doc/templates/class.rst` so it's not too bad

> I'll see how to fix from my end. I do not recall why this was necessary but at the time, it could be for compatibility.

It's because in some examples/tutorials, we want to add custom meshes. At the time `renderer.mesh` was the way to do it, and had to be done that way because we supported both Mayavi and PyVista. But nowadays it would probably be better to showcase how we can use PyVista directly to do these things, like we do for `matplotlib.pyplot` stuff.

**Review by GuillaumeFavelier — APPROVED** [review]
LGTM

**Pull request merged**
