### PR TITLE
Decoding examples with pyRiemann

### PR DESCRIPTION
**Pull request by alexandrebarachant**
I use MNE to illustrate decoding with my toolbox [pyRiemann](https://github.com/alexandrebarachant/pyRiemann), a toolbox for classification of biosignal using Riemannian geometry.

The [examples](https://github.com/alexandrebarachant/pyRiemann/tree/master/examples) are derived from the decoding examples provided with MNE.

I thought it may be interesting to integrate a couple of them in mne.
I picked two of them : 
* plot_decoding_sensors_riemann.py : Decoding of Evoked potential from MEG signals. This is basically the decoding method that help me won the [DecMeg2014](https://www.kaggle.com/c/decoding-the-human-brain) challenge and the [BCI @ NER 2015](https://www.kaggle.com/c/inria-bci-challenge) challenge on kaggle
* plot_decoding_riemann_eeg.py : Decoding of motor imagery from EEG signals. Same kind of thing, but for motor imagery

There is more examples [here](https://github.com/alexandrebarachant/pyRiemann/tree/master/examples) that may be interesting (Multiclass decoding or Riemannian geometry based permutation test)

Let me know what you think of this.

### CODE REVIEW

**Comment by dengemann** [comment]
@alexandrebarachant this is super interesting! Thanks for sharnig it. Any chances that you could re-license your code a license that's BSD-3 comptabile so we could add PyRiemann to mne/externals. The GPL license you chose does not allow us easily to include your code.

**Comment by alexandrebarachant** [comment]
@dengemann I prefer to keep the GPLv3 licence but i will think about it. it is probably a better idea to rely on pypi rather than integrating the code. The toolbox is still very young (as for my python skills, i started less than 6 month ago). I will keep the API the same but the code is subject to a lot of optimizations.

**Comment by dengemann** [comment]
Then we will need to think about how to include it. It might then be
another option to put this example to your toolbox. We are usually rather
reluctant of adding optional dependencies. Let's see what the others think
and discuss it.

2015-05-23 19:23 GMT+02:00 alexandre barachant <notifications@github.com>:

**Comment by Eric89GXL** [comment]
I don't think we can even add it as a dependency due to licensing issues.
It's the same reason we can't use fftw.

**Comment by dengemann** [comment]
> I don't think we can even add it as a dependency due to licensing issues.
It's the same reason we can't use fftw.

That's true ...

**Comment by alexandrebarachant** [comment]
I understand the reluctance to add dependencies, it is always painful to manage. and it may not worth it for only two examples. On the other hand, adding it to mne/externals is an overkill.

But i dont understand why using pypi will cause licensing issues :(

**Comment by dengemann** [comment]
> But i dont understand why using pypi will cause licensing issues :(

I don't know the exact reason but there were many simliar cases in the scipy / numpy dev discussion. 
Eric, do you know more about it?
Also ping @agramfort

**Comment by agramfort** [comment]
random thoughts....

- using externals allows to guarantee that the version we ship works with
current master. Cf joblib in sklearn
- if pyriemanian code moves quickly I would make mne a dependency of
pyriemanian and move the examples to pyriemanian until it stabilizes. This
would limit maintenance on the MNE side.
- if you stick to GPL then we cannot ship code that is using it. People
downloading mne expect to get BSD or MIT style code.

now on a more positive part:

- the current PR updates examples so doing "import mne" is not viral.
- we have an example using neo BUT it's BSD.

my personal feeling:

- we should gather forces and avoid fragmenting the dev community. The code
in decoding needs love and I am sure you fixed some API issues we have
overlooked. If a user can switch from mne CSP to riemanian spatial filters
in one line everybody wins. That's the big strength of sklearn : the API.

- If you ship code with MNE and accept to use BSD license you benefit from
MNE review process, packaging (e.g. debian) and probably gets more
visibility as you benefit from MNE existing user base.

my 2c

**Comment by Eric89GXL** [comment]
+1 for combining forces as much as possible.

But since this comes up from time to time, I dug into the licensing issues a little bit.
@alexandrebarachant it looks like as soon as we have code that does `import x` where `x` is GPL licensed, our code [becomes governed by GPL] (http://programmers.stackexchange.com/questions/87446/using-a-gplv3-python-module-will-my-entire-project-have-to-be-gplv3-licensed). See also [here] (http://www.gnu.org/licenses/gpl-faq.html#GPLStaticVsDynamic) and [a more pejorative description] (http://en.wikipedia.org/wiki/Viral_license). LGPL might get around this, though.

**Comment by dengemann** [comment]
I can only second what @agramfort and @Eric89GXL said, not splitting the community would be the best. As a matter of fact the scientific Python is mainly BSD oriented so this is kind of the normative model. Putting PyRiemann to externals would not be overkill, we also did it with scot for EEG connectivity.

**Comment by alexandrebarachant** [comment]
@Eric89GXL Thanks for the links. There is generally a lot of FUD around the GPL, it is hard to find reliable sources.

I don't mind changing the licence. I originally made this choice because i like the GPL and i don't want to restrict myself if i want to use GPL licensed code.
I will check if this cause trouble with my code, and switch to a BSD (although the beer-ware licence is tempting me)

:+1: for not splitting the community. However, MNE is very domain specific. pyRiemann aims to be a bit more generic. For example, i use it for image and texture classification. All the high level modules are build upon scikit learn (as a matter of fact, they inherit of base sklearn modules). I would like to keep it as light as possible.

The code of this PR is already provided as part of pyRiemann. My goal is not to create another M/EEG signal processing toolbox, but to provide some basic code for manipulation and classification of covariance matrices with Riemannian Geometry (which is not limited to the specific case of biosignals). 

I'm really enthusiastic about improving the decoding part of MNE so let me know if you have specific need for this.

**Comment by dengemann** [comment]
> The code of this PR is already provided as part of pyRiemann. My goal is not to create another M/EEG signal processing toolbox, but to provide some basic code for manipulation and classification of covariance matrices with Riemannian Geometry (which is not limited to the specific case of biosignals).

as sklearn is BSD-3 licenced you would also win potential sklearn users by switching ;)

> I'm really enthusiastic about improving the decoding part of MNE so let me know if you have specific need for this.

Absolutely, your inputs are welcomed! And I would personally love to make use of your Riemannian tools in some production code in which we cannot use GPL licensed software because part of our codes might become a medical product.

**Comment by alexandrebarachant** [comment]
Licence changed to BSD :+1: 

>Absolutely, your inputs are welcomed! And I would personally love to make use of your Riemannian tools in some production code in which we cannot use GPL licensed software because part of our codes might become a medical product.

GLP does not forbid commercial use, but require that if modifications are made **and** software distributed, modified sources have to be made available (at least on request). However since python is interpreted, it's a grey area since every "import" can somehow be interpreted as a part of the same software.

**Comment by dengemann** [comment]
> Licence changed to BSD :+1:

@alexandrebarachant amazing!  

> GLP does not forbid commercial use, but require that if modifications are made and software distributed, modified sources have to be made available (at least on request). 

There we go ... at least some limitations.

**Comment by Eric89GXL** [comment]
AFAIK GPL forbids use in applications that do not distribute their own source code, even by static or dynamic linking to the GPL library:

http://www.gnu.org/licenses/gpl-faq.html#GPLStaticVsDynamic

So I guess you could presumably use it in commercial code as long as you shared your source code... which would limit its usability in commercial applications for a lot of folks. That's what leads to things like FFTW's licensing scheme:

http://www.fftw.org/fftw2_doc/fftw_8.html

If most commercial applications could easily use the free GPL license, they'd have no need to provide paid licensing.

**Comment by Eric89GXL** [comment]
In other words, if something so simple as dynamic linking can force you to abide by the GPL terms, I think anything done with python import would fall under the same restriction. It would be nice if it weren't the case because I'd love to get the speedups from FFTW for mne-python, but I don't think we can.

**Comment by alexandrebarachant** [comment]
@dengemann Well, i hope that if you modify my code, you will be kind enough to push a few commits ... :)

@Eric89GXL agreed, the GPL is not very well suited for libraries. it's more of a compiled software thing. this is actually the purpose of the LGPL

all joke appart, if it wasn't for the GPL, linux will not be as successful as it is.

**Comment by dengemann** [comment]
> @dengemann Well, i hope that if you modify my code, you will be kind enough to push a few commits ... :)

You bet! Actually so far we have good experiences with this at the MNE level, people who use our code commercially usually tell us.
Can't wait to play with pyRiemann ;) You'll hear from me.

**Comment by alexandrebarachant** [comment]
>  You bet! Actually so far we have good experiences with this at the MNE level, people who use our code commercially usually tell us.

i guess that nowadays most company have integrated the fact that contributing to OSS is good for them. Even microsoft start to think about it ...

**Comment by agramfort** [comment]
I see some python issues and possible improvements in the pyRiemanian code.
It would benefit from a review process.

regarding improvement on decoding code, I guess just try to use it for your
work and see the potential limitations. Are you happy with our CSP code?

**Comment by alexandrebarachant** [comment]
> I see some python issues and possible improvements in the pyRiemanian code.
> It would benefit from a review process.

Feedback is really appreciated. I'm still a python noob. the code is not tested for python 3.x , and i only have documentation for base modules. Let me know what is your standards, i will work on it.

> regarding improvement on decoding code, I guess just try to use it for your
> work and see the potential limitations.

i don't really work on BCI currently, but as a side project i'm working on a multi-dataset benchmark for decoding algorithms. I will give you feedback.

> Are you happy with our CSP code?

So far it looks good, better than most implementation (you have regularization). Then i'm not a big fan of spatial filtering when it comes to classification. i try to avoid it if i can so did not really used it.

**Comment by agramfort** [comment]
>
> I see some python issues and possible improvements in the pyRiemanian code.
> It would benefit from a review process.
>
> Feedback is really appreciated. I'm still a python noob. the code is not
> tested for python 3.x , and i only have documentation for base modules. Let
> me know what is your standards, i will work on it.
>
I would need to review on a PR. I'll have a look on your recent GDF PR.

>  regarding improvement on decoding code, I guess just try to use it for
> your
> work and see the potential limitations.
>
> i don't really work on BCI currently, but as a side project i'm working on
> a multi-dataset benchmark for decoding algorithms. I will give you feedback.
>
cool


>  Are you happy with our CSP code?
>
> So far it looks good, better than most implementation (you have
> regularization). Then i'm not a big fan of spatial filtering when it comes
> to classification. i try to avoid it if i can so did not really used it.
>
ok. I would say if you meet something you don't like when working on MNE
please open an issue to discuss it and help us improving the usability of
the package.

**Comment by Eric89GXL** [comment]
@alexandrebarachant planning to come back to this at all?

**Comment by agramfort** [comment]
see discussion above on why it was not continued.

**Comment by agramfort** [comment]
@dengemann next to me just told me that license is now BSD on pyRiemann we should reconsider...

**Comment by dengemann** [comment]
If I am not mistaken there is actually not blocker for finalizing and merging this PR, it is a highly welcomed contribution.

**Comment by jona-sassenhagen** [comment]
I see the Potato showing up in papers a bit.

MNE should be kept at the forefront of xEG decoding :)

**Comment by kingjr** [comment]
Maybe now is a good time to merge? :)

**Comment by alexandrebarachant** [comment]
Hum, the code is probably out of date :(
I made several major change in pyRiemann, and a new and stable release is long due ...

My advice would be to cancel this PR, and i will work on a better one during the summer.

**Comment by jona-sassenhagen** [comment]
I am sure everyone who's interested in decoding and using MNE would highly appreciate that.

**Comment by agramfort** [comment]
approved.

please close then for now.

thx !

**Pull request closed without merging**
