### PR TITLE
MRG: Use mags for shielding factor

### PR DESCRIPTION
**Pull request by Eric89GXL**
@wronk can you have a quick look? I didn't realize that mags (only) were supposed to be used to calculate the shielding factor. This gives us more reasonable shielding values, do you agree?

### CODE REVIEW

**Comment by Eric89GXL** [comment]
cc @staulu is this about what you'd expect for shielding values? For some reason the 3D cal is worse than the 1D, so I suspect we have some bug there. How difficult would it be for you to calculate the shielding factor (ratio of RMS of across all mags before and after SSS) from using 1D and 3D cals on this file?

https://github.com/mne-tools/mne-testing-data/blob/master/SSS/test_move_anon_erm_raw.fif?raw=true

It can be with or without cross-talk correction or tSSS or regularization, whatever's easiest/simplest with your code.

**Comment by Eric89GXL** [comment]
FYI it's a file from UW

**Comment by Eric89GXL** [comment]
Figured out that the 3D isn't worse than 1D, but that *this particular* 3D is worse than *this other* 1D -- I don't think they were generated from the same file / using the same process. If I modify the 3D file only to have 1D coefficients, then 3D is better than 1D. So we can delve into why one is better than the other once fine cal calculation is implemented, and we potentially have the source empty room recordings.

**Comment by staulu** [comment]
It looks like there's still quite a lot of investigation to be done to understand the calibration better. I think we should have a separate project on this and eventually publish our improved understanding and results. I suggest we have a meeting in January on the topics discussed here and in the email exchange with Jukka et al.

**Comment by agramfort** [comment]
fine with me.

a separate project for now would make experimentations and iterations
faster.

**Comment by Eric89GXL** [comment]
Sounds good. The good news for `mne-python` is that it looks like 3D cal is supported properly. I'll go ahead and merge this changeset after the CIs come back happy unless anyone objects.

**Comment by agramfort** [comment]
Fine with me

**Pull request merged**
