### PR TITLE
[MRG] Kit2fiff GUI: Test event settings

### PR DESCRIPTION
**Pull request by christianbrodbeck**
Some enhancements to the KIT2FIFF GUI:

- button to preview the events: this is something I've wished for many times, makes it easier to make sure one has selected the right event settings
- button to plot raw (just uses `raw.plot()`). On my setup this works nicely with the traits gui.

screen shot 2016-07-27 at 10 39 42 am

### CODE REVIEW

**Comment by christianbrodbeck** [comment]
Two errors that seem opaque to me since they don't seem to be relate to the changes. Do these look familiar to anyone?

```
  File "/home/ubuntu/miniconda/envs/circleenv/lib/python2.7/site-packages/pyface/ui/qt4/code_editor/pygments_highlighter.py", line 39, in get_tokens_unprocessed
    for item in action(self, m):
TypeError: 'NoneType' object is not callable
```
and 
```
X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
  Major opcode of failed request:  72 (X_PutImage)
  Resource id in failed request:  0x200013
  Serial number of failed request:  45
  Current serial number in output stream:  48
```

**Comment by Eric89GXL** [comment]
Yes the first is a recurring problem (not ours, pyface) and so is the
second (not ours, mayavi)

**Comment by christianbrodbeck** [comment]
In that case this is ready. The changes in non-GUI code are minimal, restricted to factoring out some functionality now required in the GUI.

**Comment by Eric89GXL** [comment]
LGTM +1 for merge but you need a rebase

**Comment by christianbrodbeck** [comment]
Rebased. The Travis error is 
```
X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
```

**Comment by Eric89GXL** [comment]
I get that error locally, too, sometimes. It's an unrelated `mayavi` problem (cc @agramfort this is what always prevents me from building doc)

**Comment by Eric89GXL** [comment]
Any KIT users out there who could test this? @teonbrooks is that just you?

**Comment by teonbrooks** [comment]
@kingjr, free to test it?

**Comment by kingjr** [comment]
Not really

**Comment by christianbrodbeck** [comment]
I've tested it with multiple people's data by now if that helps...

**Comment by Eric89GXL** [comment]
Looks like Travis bombed with the VTK segfault of death. I'll restart and see if it works at least intermittently.

**Comment by Eric89GXL** [comment]
It bombed again, I restarted it again. But really if it fails this often we need to fix it -- can't have the CIs fail that often. Did you add something in this PR that would cause it to render differently? VTK on Travis (and Ubuntu in general) is buggy, so we have to find a way to make it work.

**Comment by christianbrodbeck** [comment]
I don’t think there is anything in that PR that should cause it to fail more… What is the failure rate on other PRs?

**Comment by Eric89GXL** [comment]
Near zero failures

**Comment by christianbrodbeck** [comment]
Is there a way to run it on the intermediate commits to see whether it starts failing at a specific point?

**Comment by Eric89GXL** [comment]
You can re-push them one by one (like via force-push for the first one) or enable Travis-CI on your own repository and push to some other branch there

**Comment by agramfort** [comment]
travis and appveyor

+1 for merge

**Comment by christianbrodbeck** [comment]
Sorry, don't merge, I'm in the process of repushing individual commits to see whether the VTK error starts happening consistently at a specific point

**Comment by christianbrodbeck** [comment]
@Eric89GXL I've identified the problem, the Travis error occurred whenever the test of Kit2FiffModel opened a Progress Dialog. I've added a flag to the model to only show GUI elements when run from the actual GUI, not when run on its own.

**Comment by Eric89GXL** [comment]
Great, thanks for taking the time to figure that out!

**Pull request merged**
