### PR TITLE
[MRG] fix typo

### PR DESCRIPTION
**Pull request by teonbrooks**
The CTF data were mislabeled in the docstring

### CODE REVIEW

**Comment by jona-sassenhagen** [comment]
Looks good to me.

Weird nobody ever noticed this!

**Comment by mmagnuski** [comment]
LGTM too :)

**Comment by larsoner** [comment]
You both have commit rights, I trust you to do the right thing (i.e., merge once there is +2) :)

**Comment by larsoner** [comment]
(actually all three of you do, but it's ideal if @teonbrooks doesn't merge his own PR)

**Pull request merged**
