### PR TITLE
MRG, FIX: Fix curry reader

### LINKED ISSUE #7300: Error in mne.io.read_raw_curry
#### Describe the bug
Error when reading curry file. The error is pasted in actual results.

#### Steps to reproduce

Test data is large in size. I am placing the download link here:
https://mega.nz/#F!pdMmxayI!eKQaoIN_VYMwCYHRhDS_tw
All curry files with .ceo, .dap, .dat and .rs3 extensions of the same name are shared in the above link

```python
fullfile = 'S23_AAD_2R'
eegdata = mne.io.read_raw_curry(fullfile)
```

#### Expected results
The raw data should be available in **eegdata**

#### Actual results

```python-traceback
ValueError                                Traceback (most recent call last)
~/Documents/python/example_scripts/test_aad.py in 
      2 file_name = 'S23_AAD_1L'
      3 fullfile = data_path+file_name
----> 4 S23_1L_raw = mne.io.read_raw_curry(fullfile)

 in read_raw_curry(fname, preload, verbose)

~/anaconda3/envs/eegsp/lib/python3.7/site-packages/mne/utils/_logging.py in wrapper(*args, **kwargs)
     88             with use_log_level(verbose_level):
     89                 return function(*args, **kwargs)
---> 90         return function(*args, **kwargs)
     91     return FunctionMaker.create(
     92         function, 'return decfunc(%(signature)s)',

~/anaconda3/envs/eegsp/lib/python3.7/site-packages/mne/io/curry/curry.py in read_raw_curry(fname, preload, verbose)
    272 
    273     """
--> 274     return RawCurry(fname, preload, verbose)
    275 
    276 

 in __init__(self, fname, preload, verbose)

~/anaconda3/envs/eegsp/lib/python3.7/site-packages/mne/utils/_logging.py in wrapper(*args, **kwargs)
     88             with use_log_level(verbose_level):
     89                 return function(*args, **kwargs)
---> 90         return function(*args, **kwargs)
     91     return FunctionMaker.create(
     92         function, 'return decfunc(%(signature)s)',

~/anaconda3/envs/eegsp/lib/python3.7/site-packages/mne/io/curry/curry.py in __init__(self, fname, preload, verbose)
    297         curry_paths = _get_curry_file_structure(fname, required=["info",
    298                                                                  "data",
--> 299                                                                  "labels"])
    300 
    301         data_fname = op.abspath(curry_paths.data)

~/anaconda3/envs/eegsp/lib/python3.7/site-packages/mne/io/curry/curry.py in _get_curry_file_structure(fname, required)
     49 
     50     # we don't use os.path.splitext to also handle extensions like .cdt.dpa
---> 51     fname_base, ext = fname.split(".", maxsplit=1)
     52     version = _get_curry_version(ext)
     53 

ValueError: not enough values to unpack (expected 2, got 1)
```

#### Additional information

import mne...
Platform:      Linux-4.15.0-74-generic-x86_64-with-debian-buster-sid
Python:        3.7.6 (default, Jan  8 2020, 19:59:22)  [GCC 7.3.0]
Executable:    /home/abhijith/anaconda3/envs/eegsp/bin/python
CPU:           x86_64: 8 cores
Memory:        15.5 GB

mne:           0.19.2
numpy:         1.18.1 {blas=mkl_rt, lapack=mkl_rt}
scipy:         1.4.1
matplotlib:    3.1.3 {backend=module://ipykernel.pylab.backend_inline}

sklearn:       0.22.1
numba:         0.48.0
nibabel:       3.0.1
cupy:          Not found
pandas:        1.0.0
dipy:          1.1.1
mayavi:        4.7.1 {qt_api=pyqt5, PyQt5=5.9.2}
pyvista:       0.23.1
vtk:           8.1.2

### PR DESCRIPTION
**Pull request by larsoner**
Our curry reader currently does not populate `info['chs'][ii]['loc']`, `info['dig']`, or `info['dev_head_t']` properly. 

@DiGyt did you try to do any source localization, `plot_sensors`, etc. with the curry reader?

1000 nAm current phantom results have 2.1 mm error, 99%+ GOF:

Screenshot from 2020-02-10 13-42-20

Todo:

- [x] Add or mock some test data where `dev_head_t` is actually calculated
- [x] ~~Update `get_phantom_dipoles`~~
- [x] ~~Add phantom data as OSF.io dataset~~
- [x] ~~Add Curry phantom example~~

Closes #7300

### CODE REVIEW

**Comment by agramfort** [comment]
cross link with #7300

**Comment by larsoner** [comment]
Okay with the latest commit and some 1000 nAm Curry phantom data I can get dipole loc error of 2.1 mm and GOFs 99%+. I'll add a todo above, some items will require waiting for the curry folks to respond.

**Comment by agramfort** [comment]
tell me when to review/merge

**Comment by larsoner** [comment]
Okay I don't have permission to share the phantom data (yet!), but I did get confirmation that the geometry of my test setup is correct (to within 1mm) so I'm confident that the source localization is at least reasonable now.

I'll work on adding tests for the steps I've added, once that's done this should be good for merge.

**Comment by larsoner** [comment]
Okay ready for review/merge @agramfort

**Comment by larsoner** [comment]
Okay let's get this in but @DiGyt please give it a try when you get a chance

**Pull request merged**
