### PR TITLE
fixed link to gist in resample method doc

### LINKED ISSUE #4994: Link to github gist is broken (404) in .resample method doc
https://github.com/mne-tools/mne-python/blob/e84b316cb188043c69a4958b74884bfb556d78d8/mne/io/base.py#L1410-L1411

### PR DESCRIPTION
**Pull request by sappelhoff**
fixes #4994

### CODE REVIEW

**Comment by jona-sassenhagen** [comment]
LGTM

**Comment by jona-sassenhagen** [comment]
Travis seems unrelated?

```

―――――――――――――――――――――――――――― test_plot_annotations ―――――――――――――――――――――――――――――
    def test_plot_annotations():
        """Test annotation mode of the plotter."""
        raw = _get_raw()
        raw.info['lowpass'] = 10.
        with warnings.catch_warnings(record=True):  # matplotlib
>           _annotation_helper(raw)
raw        = <Raw  |  test_raw.fif, n_channels x n_times : 9 x 14400 (24.0 sec), ~4.0 MB, data loaded>
mne/viz/tests/test_raw.py:223: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
raw = <Raw  |  test_raw.fif, n_channels x n_times : 9 x 14400 (24.0 sec), ~4.0 MB, data loaded>
    def _annotation_helper(raw):
        """Helper for testing interactive annotations."""
        import matplotlib.pyplot as plt
        n_anns = 0 if raw.annotations is None else len(raw.annotations.onset)
    
        fig = raw.plot()
        data_ax = fig.axes[0]
        fig.canvas.key_press_event('a')  # annotation mode
        # modify description
        ann_fig = plt.gcf()
        for key in ' test':
            ann_fig.canvas.key_press_event(key)
        ann_fig.canvas.key_press_event('enter')
    
        ann_fig = plt.gcf()
        # XXX: _fake_click raises an error on Agg backend
>       _annotation_radio_clicked('', ann_fig.radio, data_ax.selector)
E       AttributeError: 'Figure' object has no attribute 'radio'
```

**Comment by agramfort** [comment]
travis error is unrelate. @larsoner any idea why?

**Comment by larsoner** [comment]
Yes #4999 you already approved it :)

**Comment by larsoner** [comment]
Thanks @sappelhoff

**Pull request merged**
