### PR TITLE
MRG, ENH: Add real datatype check, avoid joblib for now

### PR DESCRIPTION
**Pull request by larsoner**
joblib and SciPy's FFT do not get along:

https://github.com/joblib/joblib/issues/906

For now set `n_jobs=1` in the tests to make things green again, and make our dtype check a bit stricter/consistent (only allow np.float64 in resampling and filtering). Once joblib or SciPy are fixed we can put `n_jobs=2` in a test somewhere.

### CODE REVIEW

**Comment by larsoner** [comment]
New upstream issue:

https://github.com/scipy/scipy/issues/10422

Hopefully will be fixed within a few days, but nonetheless the changes here should be helpful.

**Comment by larsoner** [comment]
Also now adds support for `np.random.Generator` instances in `check_random_state`.

**Comment by larsoner** [comment]
@agramfort all green, feel free to review and merge. PR ended up larger than expected to clean up our internal uses of `rng.*` to use functions that are in both the old `RandomState` API and new `Generator` API in a backward compatible way.

**Comment by agramfort** [comment]
Thx @larsoner

**Pull request merged**
