### PR TITLE
MRG: TimeViewer matplotlib figure color

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR updates the background and foreground colors of the internal matplotlib figure depending on the palette chosen for `_Brain`.

background="white" | background="black" (default)
----|-----
image | image

It's an item of #7162

### CODE REVIEW

**Comment by agramfort** [comment]
can we add this to the doc somewhere?

**Comment by agramfort** [comment]
I was told some years ago "if there is no doc it does not exist" :)

**Comment by GuillaumeFavelier** [comment]
`_Brain` is a private class but its signature and features are designed to follow PySurfer's.

**Comment by agramfort** [comment]
yes but does it justify not documenting this option in the doc?

>

**Comment by GuillaumeFavelier** [comment]
AFAIK it's the case already:

https://github.com/mne-tools/mne-python/blob/e2e114d00ccb8eebca790550cbb3bb30eba81ecb/mne/viz/_brain/_brain.py#L60-L65

**Comment by agramfort** [comment]
I mean in the tutorials in the narrative doc. I would love to see the
screenshots you shared appear
on the mne website. Makes sense?

>

**Comment by larsoner** [comment]
#7927

**Comment by larsoner** [comment]
Thanks @GuillaumeFavelier !

**Pull request merged**
