### PR TITLE
[MRG] Fix reader for gdf.

### PR DESCRIPTION
**Pull request by jaeilepp**
Closes https://github.com/mne-tools/mne-python/issues/4252

NaNs cannot be added to integer arrays.

### CODE REVIEW

**Comment by agramfort** [comment]
too hard to add a test?

**Comment by jaeilepp** [comment]
I think I would have to add a test file. The one I have is 7MB. Not sure about the license.

**Comment by agramfort** [comment]
do what you can

**Comment by agramfort** [comment]
thanks @jaeilepp

**Pull request merged**
