### PR TITLE
[MRG] Randomised pca

### LINKED ISSUE #3220: Sklearn warnings for RandomizedPCA
In running the `plot_artifacts_correction_ica.py` tutorial with latest `sklearn`:
```
DeprecationWarning: Class RandomizedPCA is deprecated; RandomizedPCA will
be removed in 0.20. Use PCA(svd_solver='randomized') instead. The new implementation
DOES NOT store whiten components_. Apply transform to get them.
```
Any volunteer to fix it?

### PR DESCRIPTION
**Pull request by agramfort**
fixes #3220

### CODE REVIEW

**Comment by Eric89GXL** [comment]
LGTM, is this MRG?

**Comment by agramfort** [comment]
Yes






On Sun, Jul 24, 2016 at 3:39 AM +0200, "Eric Larson" <notifications@github.com> wrote:












LGTM, is this MRG?

**Comment by agramfort** [comment]
CIs happy

**Comment by Eric89GXL** [comment]
Thanks @agramfort

**Comment by dengemann** [comment]
Thanks Alex for this one.

**Pull request merged**
