### PR TITLE
ENH+BF: skip two tests requiring mayavi, and include into SkipTest caught exception

### LINKED ISSUE #3645: few errors while building 0.13 debian pkg
lazy me decided just to ask how to fix/address those two 

```
======================================================================
ERROR: Test CombineMarkersModel Traits Model
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/python-mne-0.13+dfsg/mne/utils.py", line 827, in dec
    return function(*args, **kwargs)
  File "/build/python-mne-0.13+dfsg/mne/gui/tests/test_marker_gui.py", line 33, in test_combine_markers_model
    assert_false(model.mrk3.can_save)
AttributeError: 'function' object has no attribute 'can_save'

======================================================================
FAIL: Test CombineMarkersModel Traits Model.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/python-mne-0.13+dfsg/mne/utils.py", line 827, in dec
    return function(*args, **kwargs)
  File "/build/python-mne-0.13+dfsg/mne/gui/tests/test_kit2fiff_gui.py", line 35, in test_kit2fiff_model
    assert_false(model.can_save)
AssertionError: <bound method Kit2FiffModel.<lambda> of <mne.gui._kit2fiff_gui.Kit2FiffModel object at 0x7ff3e84eea10>> is not false
    '<bound method Kit2FiffModel.<lambda> of <mne.gui._kit2fiff_gui.Kit2FiffModel object at 0x7ff3e84eea10>> is not false' = self._formatMessage('<bound method Kit2FiffModel.<lambda> of <mne.gui._kit2fiff_gui.Kit2FiffModel object at 0x7ff3e84eea10>> is not false', "%s is not false" % safe_repr(expr))
>>  raise self.failureException('<bound method Kit2FiffModel.<lambda> of <mne.gui._kit2fiff_gui.Kit2FiffModel object at 0x7ff3e84eea10>> is not false')
```

### PR DESCRIPTION
**Pull request by yarikoptic**
Now it should include msg why actually skipping, e.g.

```
SKIP: Test test_kit2fiff_model skipped, requires mayavi. Got exception (No module named pyface.tvtk_scene)
``` 

Closes #3645

### CODE REVIEW

**Comment by agramfort** [comment]
@christianbrodbeck can you have a look?

I think it's redundant with your open PR.

thanks @yarikoptic for taking the time to investigate.

**Comment by christianbrodbeck** [comment]
Yes https://github.com/mne-tools/mne-python/pull/3648 should take care of it eventually, except for the decorator modification.

**Comment by agramfort** [comment]
@christianbrodbeck I propose to merge @yarikoptic's PR and that you rebase.

ok for you?

**Comment by christianbrodbeck** [comment]
Yes we can do that

**Comment by christianbrodbeck** [comment]
Thanks @yarikoptic !

**Pull request merged**
