### PR TITLE
WIP: Add CrossSpectralDensity.compute_coherence method

### PR DESCRIPTION
**Pull request by wmvanvliet**
Computing sensor level coherence is quite simple, and useful if you for
example want to compute coherence between each MEG sensor and an
external source.

Todo:

 - [x] Implement `csd.compute_coherence` method
 - [x] Refactor `csd.plot(mode='coh')` to make use of the new method
 - [x] Unit test
 - [ ] Add example for computing sensor-level coherence with external source
 - [ ] Add entry to what's new

### CODE REVIEW

**Comment by larsoner** [comment]
Maybe a test that on some small set of `epochs` computing `spectral_connectivity` gives the same result as computing `CrossSpectralDensity` + `csd.compute_coherence`?

**Comment by wmvanvliet** [comment]
I actually wonder if this is needed at all, given that `spectral_connectivity` already exists. Probably not.

**Comment by wmvanvliet** [comment]
Still, we should probably have a tutorial for computing coherence with an external source.

**Comment by larsoner** [comment]
Indeed, some SSVEP/ASSR dataset would be nice for this, and would also work well for sorting out #7671

**Pull request closed without merging**
