### PR TITLE
MAINT: fix click testing

### PR DESCRIPTION
**Pull request by drammock**
hopefully fixes our MPL 3.4.0 testing woes

### CODE REVIEW

**Comment by drammock** [comment]
cc @alexrockhill @larsoner

**Review by larsoner — APPROVED** [review]
LGTM +1 for merge. Let's get it in as soon as CIs come back happy!

I'm just hoping the old / compat CIs don't complain

**Comment by larsoner** [comment]
Do you want to fix https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=12918&view=logs&jobId=25a52bd8-0e32-5080-16fd-ef6520ac93ab&j=25a52bd8-0e32-5080-16fd-ef6520ac93ab&t=ed0c6a43-6c02-5c37-64bf-ac1c672f0690 by `with warnings.catch_warnigs(record=True): warnings.simplefilter('ignore')`ing inside the mayavi import that fails?

**Comment by drammock** [comment]
it's failing in 10 different tests.  Isn't there a way to ignore specific warnings via regex?  we could ignore `DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.`

**Comment by larsoner** [comment]
Yes you can put it in `conftest.py`

**Comment by larsoner** [comment]
Green, in we go. Thanks a ton @drammock !

**Pull request merged**
