### PR TITLE
BUG: Fix bug with themes on macOS

### LINKED ISSUE #10486: Argument `theme` of `raw.plot()` or config key does not work on macOS
As spotted following the discussion here https://github.com/mne-tools/mne-qt-browser/issues/83 the argument `theme` does not change the theme on either my macOS or Windows computer.

Sample code:

```
import mne


folder = mne.datasets.sample.data_path() / 'MEG' / 'sample'
raw = mne.io.read_raw(folder / 'sample_audvis_filt-0-40_raw.fif', preload=True)
raw.plot(theme='dark')
```

### PR DESCRIPTION
**Pull request by larsoner**
@hoechenberger @mscheltienne . This code:
```
python -c "import mne; raw = mne.io.read_raw_fif(mne.datasets.sample.data_path() / 'MEG' / 'sample' / 'sample_audvis_raw.fif'); raw.plot(theme='auto', block=True)"
```
Gives

| macOS mode | `theme='auto'` | `theme='dark'` | `theme='light'` |
| -- | -- | -- | -- |
| dark | Screen Shot 2022-04-08 at 8 43 28 AM | Screen Shot 2022-04-08 at 8 44 35 AM | Screen Shot 2022-04-08 at 8 45 24 AM | 
| light | Screen Shot 2022-04-08 at 8 46 07 AM | Screen Shot 2022-04-08 at 8 46 33 AM | Screen Shot 2022-04-08 at 8 46 59 AM |

Fixes #10486
Fixes https://github.com/mne-tools/mne-qt-browser/issues/100

The one real downside I think is that when the system is in light mode, dark mode uses the `qdarkstyle` blue-ish dark mode rather than the native macOS dark mode. I think we'd want a PR to qdarkstyle (or something) to try to fix that, as it's probably a large undertaking. In the meantime, this at least gets us closer to native styling on macOS and fixes some bugs.

Todo:

- [x] Add tests for bgcolors when `theme` is passed (or `'auto'`)

### CODE REVIEW

**Comment by larsoner** [comment]
Ready for review/merge from my end

**Review by agramfort — APPROVED** [review]
@hoechenberger merge if happy

**Comment by hoechenberger** [comment]
Thank you, I will have a look this afternoon! In any case, thanks for putting in this effort, @larsoner!

**Comment by mscheltienne** [comment]
On a fresh install with bare minimum `mne-python` and `mne-qt-browser` dependencies (installed with `python setup.py develop` and nothing else), I am still getting a dark theme with `theme='light'` and I'm getting this warning as well:

`To use light mode, "qdarkstyle" has to be installed! You can install it with `pip install qdarkstyle`

And indeed, after installing `qdarkstyle` I can now have the `light` mode with `theme='light'`. I'm a bit confused, isn't the light theme the default and the dark theme the extra that required `qdarkstyle`? 😕 

|       | Main | PR |
| --- | :---: | :---:|
| Dark | ![dark][1] | ![after-dark][2] |
| Light | ![light][3] | ![after-light][4] |

[1]: https://user-images.githubusercontent.com/73893616/162443232-f59159f0-b334-456f-b676-0350ff55fa88.png
[2]: https://user-images.githubusercontent.com/73893616/162443287-ee7d545e-295d-4527-9fd5-2edb3052199c.png
[3]: https://user-images.githubusercontent.com/73893616/162443252-0ed1b1ae-8de7-4c5b-a91c-d3bf351d73a0.png
[4]: https://user-images.githubusercontent.com/73893616/162443348-946d2c04-ee4f-4540-a8af-0cf927083d39.png

**Comment by larsoner** [comment]
> And indeed, after installing qdarkstyle I can now have the light mode with theme='light'. I'm a bit confused, isn't the light theme the default and the dark theme the extra that requires qdarkstyle? 😕

On macOS, when in system-dark mode you need qdarkstyle to have the light mode CSS for the browser. When in system-light mode, you need qdarkstyle to have the dark mode CSS for the browser.

**Comment by larsoner** [comment]
(In other words, I think the behavior is expected and installing `qdarkstyle` was the right thing to do to fix it / the warning worked)

**Comment by mscheltienne** [comment]
That's unintuitive 😅 By the way, shouldn't `qdarkstyle` be a dependency of `mne-qt-browser`? Or at least in a `requirement_extra.txt`? 
Same for `psutil`, I think I had a warning telling me to install `psutil` to retrieve available RAM at some point.

**Comment by larsoner** [comment]
> That's unintuitive 😅

Yes `qdarkstyle` is a bit of a misnomer

> By the way, shouldn't qdarkstyle be a dependency of mne-qt-browser? Or at least in a requirement_extra.txt?
> Same for psutil, I think I had a warning telling me to install psutil to retrieve available RAM at some point.

This could be useful, feel free to open an issue about this in the mne-qt-browser repo

**Comment by larsoner** [comment]
FYI it also looks like this problem is fixed on Qt>=5.13, so once we move to PySide6 (hopefully, as our default) the workarounds here to make the toolbar and status bar the correct color won't really be needed anymore. On this PR and https://github.com/mne-tools/mne-qt-browser/pull/104, I get what appears to be a nicely native dark UI when in dark mode, but our workarounds seem okay to me:

| Qt >= 5.13 | Qt <= 5.12 |
| -- | -- |
| Screen Shot 2022-04-08 at 2 24 29 PM | Screen Shot 2022-04-08 at 2 25 54 PM |

**Comment by larsoner** [comment]
@hoechenberger any chance to get this merged? It's blocking https://github.com/mne-tools/mne-python/pull/10510 / https://github.com/mne-tools/mne-qt-browser/pull/104 etc.

**Comment by agramfort** [comment]
thx @larsoner

**Pull request merged**
