### PR TITLE
Backport PR #12616 on branch maint/1.7 (Fix `EpochsTFR.add_channels()`)

### PR DESCRIPTION
**Pull request by meeseeksmachine**
Backport PR #12616: Fix `EpochsTFR.add_channels()`

### CODE REVIEW

**Comment by drammock** [comment]
@larsoner is the bot handling changelog entries correctly? I think they should get added into `v1.7.rst` rather than separate files in `devel/` right?

**Comment by larsoner** [comment]
In a usable way I think... in `maint/1.7` there is [no `devel` section](https://mne.tools/stable/development/whats_new.html) so adding these files is kind of a no-op, which is okay (they haven't actually landed in any released version). But then when we eventually want to cut a point release, we can tell `towncrier` to take all those stubs and generate RST for us that we can add to `v1.7.rst`, which is probably the right time to add them to the changelog anyway.

If we wanted we could add a `v1.7.1 (unreleased)` heading that held the pending point-release changes. But I doubt anyone follows our changelog that closely, so probably not worth the effort.

**Comment by drammock** [comment]
> In a usable way I think

OK as long as there's a sensible way to handle it when the point-release goes out, no need to adjust what the bot does at backport time.

**Comment by cbrnr** [comment]
On a related note, I was wondering if we want to have the bot as the sole author of all changes (see e.g. https://github.com/mne-tools/mne-python/releases/tag/v1.7.1)?

**Comment by cbrnr** [comment]
@mscheltienne but I'm not sure if any authors other than bots show up in a backport?

**Comment by mscheltienne** [comment]
True.. and I guess it will not only remove it from the author list but also from the bulletpoint list of changes, leaving an empty changelog.

**Pull request merged**
