### PR TITLE
[MRG] better error msg for missing names for plot_topomap

### PR DESCRIPTION
**Pull request by jona-sassenhagen**
A minor PR hopefully helpful for stupid people like me.

Currently, if you try `plot_topomap(..., show_names=True)` without supplying `names`, the following error is raised: `TypeError: object of type 'NoneType' has no len()`.
This adds the dependency of `show_names` on `names` to the doc, and gives a more meaningful error message when this is not done.

### CODE REVIEW

**Comment by agramfort** [comment]
any chance to add or change a tiny test?

**Comment by jona-sassenhagen** [comment]
Test added.

Note: this is only for stand-alone usage of `plot_topomap`. `evoked.plot_topomap`/`plot_evoked_topomap` doesn't need this, because it uses `_prepare_topoplot`.

**Comment by agramfort** [comment]
cool.

let's merge when travis is green

**Comment by Eric89GXL** [comment]
Thanks @jona-sassenhagen

**Pull request merged**
