### PR TITLE
BUG: Fix backward compat check_version

### LINKED ISSUE #10404: BUG: _compare_version backward incompat
cc @hoechenberger:
```
>>> import mne
>>> mne.fixes._compare_version('1.0.dev0', '>=', '1.0')
False
>>> from distutils.version import LooseVersion
>>> LooseVersion('1.0.dev0') >= LooseVersion('1.0')
<stdin>:1: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
True
```
This is a problem because we usually want the second result :(

The `git grep check_version | wc -l`  count is 67 and `git grep _compare_version | wc -l` is 26, I'd rather not have to change all of these to allow for `.dev0` extensions. Plus other submodules like `mne-nirs` that already use this (where I saw the problem actually!) will not work properly...

I'm tempted to change this to cut off any `.dev` from the end to make life easy, but then we depart from standard. But it seems a bit like the lesser of two evils here.

### PR DESCRIPTION
**Pull request by larsoner**
Closes #10404

A fun little regex exercise :)

### CODE REVIEW

**Comment by cbrnr** [comment]
Do you want to include a hyphen as a potential separator (e.g. `1.2.3-dev0`), or is this never used in the Python world?

**Comment by larsoner** [comment]
Plus is listed instead of hyphen as a separator in [PEP440](https://www.python.org/dev/peps/pep-0440/) and I didn't see it in my examples at least. So I'd assume YAGNI until we hit a case...

**Comment by cbrnr** [comment]
OK! I always thought that PEP440 is identical to semantic versioning, but apparently that's not the case!

**Comment by cbrnr** [comment]
BTW, wouldn't a [compatible release](https://www.python.org/dev/peps/pep-0440/#compatible-release) specifier do exactly what we need here? So comparing `1.0` with e.g. `~= 1.0.dev0` should yield `True`.

**Comment by larsoner** [comment]
Maybe, but I'm not sure how that interacts with `parse` and using it properly

**Pull request merged**
