### PR TITLE
[BUG, MRG] Fix links, add note to Blender tutorial

### PR DESCRIPTION
**Pull request by alexrockhill**
Fixes https://github.com/mne-tools/mne-python/issues/10684 part.

### CODE REVIEW

**Comment by alexrockhill** [comment]
I looked into larger refactoring but the Blender API really isn't that helpful for navigating the application which is why so much is on YouTube. It's not ideal but I think this tutorial should probably stay close to as written for the time being, otherwise surface editing in Blender will probably not go well for people following the tutorial without screenshots. The screenshots are out-of-date but they are a lot of work to annotate. They are close-ish so that you can figure it out with the new version so I think maybe just leaving that be too is okay.

I looked into automatically converting from LIA to RAS as well and scaling since the units are way off. I can add that in another PR but it would break backward compatibility for obj files written in LIA and mm so that might not be as easy either. Happy to add if others feel that would be nice. I'd really like to add an `mne.viz.Brain.export_to_blender` or such method so the coordinates could be fixed at that level instead of surface I/O so I was thinking of just doing that.

**Comment by alexrockhill** [comment]
@hoechenberger, I made a quick video tutorial since that might be easier. Not sure how we are hosting these, just on github or on a YouTube channel or what. It's a lot easier to shoot a video than reformat the static images, I'd be fine updating the video on major Blender releases...

https://user-images.githubusercontent.com/13473576/173709276-d94b70b2-1a27-422b-afae-433409a80320.mp4

**Comment by hoechenberger** [comment]
This sounds great! I've uploaded MNE tutorials to my youtube channel, but maybe it's time to create an actual MNE channel. I'll look into this later today.

**Comment by larsoner** [comment]
> maybe it's time to create an actual MNE channel. I'll look into this later today.

Agreed, let's do it. Then let's try using https://github.com/sphinx-contrib/youtube or something similar to embed

**Comment by alexrockhill** [comment]
What do you think about merging this so that the links are not broken and then a followup changing most of the text and links for the video?

**Comment by hoechenberger** [comment]
Thank you very much, @alexrockhill!

**Pull request merged**
