### PR TITLE
MRG Histogram for epochs peak-to-peak values.

### PR DESCRIPTION
**Pull request by jaeilepp**
Histogram toggled with ``h`` key.
screenshot from 2015-07-14 21 16 10

### CODE REVIEW

**Comment by teonlamont** [comment]
looks good. could you label the x-, and y-axes?

**Comment by agramfort** [comment]
looks nice. +1 for axes labels

**Comment by mainakjas** [comment]
could you try more bins? The first bar (for mag and grad) looks like it could be more spread out ...

**Comment by dengemann** [comment]
Colors should match the regular plotting colors we use for sensor types.

**Comment by agramfort** [comment]
thanks @jaeilepp !

**Comment by agramfort** [comment]
merged by rebase after a tiny cosmit. A fig.clf() was missing.

**Pull request closed without merging**
