### PR TITLE
MRG: Brain save movie

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR brings back the part of https://github.com/mne-tools/mne-python/pull/7257 about `save_movie` in `_Brain`.

It's an item of https://github.com/mne-tools/mne-python/issues/7162

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
I intend to add compatibility with `_TimeViewer` in another PR so this is ready for reviews.

Also I typically use this feature with:

```py
import os
import mne
from mne.datasets import sample
data_path = sample.data_path()
sample_dir = os.path.join(data_path, 'MEG', 'sample')
subjects_dir = os.path.join(data_path, 'subjects')
fname_stc = os.path.join(sample_dir, 'sample_audvis-meg')
stc = mne.read_source_estimate(fname_stc, subject='sample')
mne.viz.set_3d_backend('pyvista')
brain = stc.plot(subjects_dir=subjects_dir, hemi='lh',
                 clim=dict(kind='value', pos_lims=[3, 6, 9]),
                 time_viewer=False)
brain.save_movie('movie.mov', time_dilation=8.)
```

which requires `imageio-ffmpeg`, should I add it to the requirements too @larsoner, @agramfort ?

**Comment by agramfort** [comment]
can I save a movie from the interface? cmd+shift+ something?

>

**Comment by GuillaumeFavelier** [comment]
> can I save a movie from the interface? cmd+shift+ something?

It's not possible in this PR. It focuses on `time_viewer=False`. 

So do you mean to add it in this context?

**Comment by agramfort** [comment]
ok then this works as it is now.

>

**Comment by larsoner** [comment]
Yes +1 for adding it to requirements.txt and environment.yml

**Comment by GuillaumeFavelier** [comment]
I'll push a commit to add it right now.

**Comment by GuillaumeFavelier** [comment]
Failures on Circle don't seem related:

```
/home/circleci/project/doc/auto_tutorials/intro/plot_20_events_from_raw.rst:87: WARNING: term not in glossary: STIM channel

/home/circleci/project/doc/auto_tutorials/preprocessing/plot_60_maxwell_filtering_sss.rst:236: WARNING: term not in glossary: hpi

/home/circleci/project/doc/auto_tutorials/raw/plot_20_event_arrays.rst:43: WARNING: term not in glossary: STIM channel
```

*I'll update after further investigation*

**Comment by agramfort** [comment]
rebase on master?

>

**Comment by GuillaumeFavelier** [comment]
> rebase on master?

Maybe.

**Comment by GuillaumeFavelier** [comment]
It's already up-to-date apparently.

**Comment by agramfort** [comment]
and master is green?

>

**Comment by GuillaumeFavelier** [comment]
> and master is green?

AFAIK all is good and green there

**Comment by GuillaumeFavelier** [comment]
I restarted Circle for now

**Comment by agramfort** [comment]
@GuillaumeFavelier can you just update latest.inc ? thx

**Comment by agramfort** [comment]
thx @GuillaumeFavelier

**Pull request merged**
