### PR TITLE
MRG, BUG: Fix scaling of sources

### LINKED ISSUE #6615: ICA.plot_sources(epoch) scaling (?) is wrong
The plot_sources method for ICA only produces a wall of blue when the Inst is an Epoch. This occurs even with a fresh conda environment with the stable .18 version. I assume this is a scaling issue, but trying to manually scale it down hasn't gotten me anywhere.

You should be able to reproduce this as follows:
```Python
import mne
path =  mne.datasets.sample.data_path()
raw = mne.io.Raw(path + '/MEG/sample/sample_audvis_raw.fif')
events = mne.read_events(path+"/MEG/sample/sample_audvis_raw-eve.fif")
epo = mne.Epochs(raw,events)
ica = mne.preprocessing.ICA(n_components=100)
ica.fit(epo)
ica.plot_sources(epo)
```

### PR DESCRIPTION
**Pull request by larsoner**
Closes #6615.

@jshanna100 can you confirm this fixes your problem?

### CODE REVIEW

**Comment by jshanna100** [comment]
It doesn't fix it on my end.

**Comment by agramfort** [comment]
neither for me

**Comment by larsoner** [comment]
Whoops, I tested it incorrectly. Should be fixed now!

**Comment by jshanna100** [comment]
LGTM

**Comment by agramfort** [comment]
thx heaps @larsoner

**Pull request merged**
