### PR TITLE
docs: Fix a few typos

### PR DESCRIPTION
**Pull request by timgates42**
There are small typos in:
- mne/decoding/tests/test_ssd.py
- mne/epochs.py
- mne/io/constants.py
- mne/io/meas_info.py
- tutorials/io/30_reading_fnirs_data.py

Fixes:
- Should read `frequency` rather than `freqquency`.
- Should read `discouraged` rather than `discoraged`.
- Should read `characteristic` rather than `charactersitic`.
- Should read `acquisition` rather than `acquition`.
- Should read `occurred` rather than `ccurred`.

Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

### CODE REVIEW

**Review by agramfort — APPROVED** [review]
thx @timgates42 !

**Comment by larsoner** [comment]
@timgates42 thanks! Can you add an entry to `latest.inc` with a `**new contributor**` tag like `Darin Erat Sleiter` did:

https://github.com/mne-tools/mne-python/blob/702d727c9a039e4ddfce0b00f9e7c3ce8de22c0e/doc/changes/latest.inc#L34-L42

And then your name + URL to the bottom of [`names.inc`](https://github.com/mne-tools/mne-python/blob/main/doc/changes/names.inc#L405)? That way you can get proper credit for your first contribution in our next release.

(BTW, If you are looking for another PR to make, you could add these typos and their fixes to codespell, which is our automated spell checking tool that missed these errors: https://github.com/codespell-project/codespell/blob/master/codespell_lib/data/dictionary.txt)

**Comment by timgates42** [comment]
thx @larsoner I've updated latest.inc and names.inc

**Comment by timgates42** [comment]
Oh no - codespell doesn't like my name Tim and wants it to be Time instead.

**Comment by larsoner** [comment]
Just add to ignore_words.txt (I think it needs to be all lower case)

**Comment by timgates42** [comment]
Have gone with my full name - Timothy

**Review by agramfort — APPROVED** [review]
thx @timgates42 !

**Comment by larsoner** [comment]
Thanks @timgates42 !

**Comment by larsoner** [comment]
@timgates42 every week with our `linkcheck` CI run we get a timeout error on your URL:

https://github.com/timgates42

I even just got the Unicorn trying to look now! It's perhaps because you have so many cloned repositories, making it probably a GitHub problem. Do you have an alternative URL we could use? If not, I can also just remove the link -- let me know what you prefer.

**Comment by larsoner** [comment]
For now I went with https://au.linkedin.com/in/tim-gates-0528a4199 in https://github.com/mne-tools/mne-python/commit/9df7022fb488c4e06cb27f278dc81b1cd46e28fb#diff-2251dce798fba74c4df58306756b5f4796d604ce037adf3dbe267ae40e7727b6

**Pull request merged**
