### PR TITLE
[DOC, MAINT] Standardize reference links

### PR DESCRIPTION
**Pull request by alexrockhill**
There was a lot of variation in just the first few lines of each example and tutorial as far as 1) the utf8 encoding 2) having a reference tag and its format and 3) the format of the first header. I thought, for new contributors especially, it would be nice to have things standardized. It took a little bit of time, but it was fun to take a minute to see all the examples. 

For a next step, especially for the examples section, it might be nice to have a higher-level document like examples EEG researchers should look at, examples for time-frequency researchers etc.

The other thing that is nice is that, for intersphinx in other projects, there are links for everything and developers in other projects can reference without having to become a contributor (if they don't want to).

A last note is that the examples label_source_activations and label_activations_from_stc seem redundant and so maybe should be consolidated and tutorials/evoked/40_whitened is pretty short and should probably be an example or added to the end of another tutorial.

### CODE REVIEW

**Comment by larsoner** [comment]
> The other thing that is nice is that, for intersphinx in other projects, there are links for everything and developers in other projects can reference without having to become a contributor (if they don't want to).

For what it's worth, this already exists. Sphinx-gallery will always add a `.. _sphx_glr_auto_examples_visualization_whatever_it_is.py::` to the titles. The `.. _ex-whatever::`s are just our shorthand. I guess having our own labels is nicer because we can always rename the files later if we want, and the labels can stay the same. But then it breaks the standardization a bit so... who knows.

So far I think we were just using the shorthand versions any time we wanted to save ourselves some typing (and space) in references, but I guess there isn't too much harm in having them everywhere now.

Overall I'm +0.5 on these changes, though. Unless anyone objects, I'll merge for 1.0 in the next couple of days.

**Comment by alexrockhill** [comment]
Yeah, low priority, I just thought it would be nice to standardize them. Good to know about the sphinx gallery tags.

**Comment by agramfort** [comment]
I would have relied myself on sphinx gallery automatic links but it also tells me that these are hard to discover...

no objection to merge here.

**Comment by larsoner** [comment]
Thanks @alexrockhill

**Pull request merged**
