### PR TITLE
TST: Check PyQt5 AttributeError on version 5.14.1

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR is a follow up of https://github.com/mne-tools/mne-python/pull/7172#issuecomment-571076181 and try to reproduce the issue on Travis with `PyQt5 5.14.1`.

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
Apparently this is a brand new version:

image

**Comment by GuillaumeFavelier** [comment]
I was able to reproduce the issue on `master`, [Travis job #24200.3 errored](https://travis-ci.org/mne-tools/mne-python/jobs/633217472?utm_medium=notification&utm_source=github_status):

```AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'```

**Comment by GuillaumeFavelier** [comment]
To mitigate this, I can suggest the following in `.travis.yml`:

`pip install "pyqt5>=5.10,<5.14.1";`

**Comment by GuillaumeFavelier** [comment]
This is not macOS related so no need to change `.travis.yml`

**Comment by GuillaumeFavelier** [comment]
Now it's better. What do you think @agramfort, @larsoner ?

**Comment by larsoner** [comment]
I would use != rather than <= because it's likely 5.14.2 release would fix the problem

**Comment by larsoner** [comment]
You'll need to also update the installation instructions

**Comment by GuillaumeFavelier** [comment]
In here?

image

**Comment by larsoner** [comment]
Yep

**Comment by agramfort** [comment]
LGTM

**Comment by GuillaumeFavelier** [comment]
All CIs are green now.

**Comment by agramfort** [comment]
thx @GuillaumeFavelier

**Pull request merged**
