### PR TITLE
WIP: Refactor raw and epochs plotting, add butterfly and group_by kwargs

### LINKED ISSUE #4850: ENH: `group_by` for epochs.plot()
Any reason not to have it (other than no time to implement it yet)? It might be nice to have like we do for `raw.plot`.

### PR DESCRIPTION
**Pull request by larsoner**
Looking at `mne/viz/raw.py` and `mne/viz/epochs.py` there appears to be a lot of duplicated code in terms of 1) plot setup, 2) key press handling, and 3) butterfly setup. At the same time, `epochs.plot` is less capable than `raw.plot` in terms of (at least) `butterfly` and `group_by` options. This PR aims to fix this.

Todo:
- [x] make `epochs.plot(butterfly=True)` work and add test (easy)
- [x] wait for #4799 to be merged to avoid bad conflicts
- [x] fix epochs `params['offsets']` use
- [x] fix labels for whitened data in butterfly mode
- [x] make `epochs.plot(group_by='type')` work
- [x] fix `raw.plot(group_by='selection')`
- [ ] Unify `types` in setup functions
- [ ] Unify `_setup_butterfly`
- [ ] Unify `onscroll`
- [ ] Unify `onkey`
- [ ] implement `epochs.plot(group_by='selection')`
- [ ] add tests for `group_by`
- [ ] fix ICA plotting breakages, if any

Closes #4850.

### CODE REVIEW

**Comment by larsoner** [comment]
So the `raw` butterfly mode to me looks better than the `epochs` butterfly mode (I haven't changed this behavior yet):

https://7066-1301584-gh.circle-artifacts.com/0/tmp/circle-artifacts.CtE6jQa/html/auto_tutorials/plot_whitened.html

Any objections with unifying these to plot the same way, and plot the way it's done for raw data?

**Comment by agramfort** [comment]
yes epochs seem more cluttered. but it would be nice to add units to Raw in
yaxis

**Comment by larsoner** [comment]
Epochs browser decluttered a bit:

https://7071-1301584-gh.circle-artifacts.com/0/tmp/circle-artifacts.jYKTBYE/html/auto_tutorials/plot_whitened.html

Feel free to comment on the aesthetic as I plan to make both epochs and raw ylabels look like this version of the epochs browser

**Comment by agramfort** [comment]
looks great !

**Comment by agramfort** [comment]
@larsoner you'll have to rebase this one too :)

**Comment by larsoner** [comment]
This is a bit of a nightmare. Closing for now.

**Pull request closed without merging**
