### PR TITLE
BUG: Fix bug with Report.add_ica component number

### PR DESCRIPTION
**Pull request by larsoner**
Closes https://github.com/mne-tools/mne-bids-pipeline/issues/573

cc @hoechenberger

See for example https://mne.tools/mne-bids-pipeline/1.4/examples/ds000248_ica/sub-01_task-audiovisual_report.html#ICA 

1. Fix component numbers which used to just be `range(len(picks))` as noted in https://github.com/mne-tools/mne-bids-pipeline/issues/573
2. Always write the cumulative variance explained. Even though it's not informative for the first component, it makes the slider behavior between the first and second components more uniform and thus easier to use.
3. Fix bug where `{round(x)}` was used, but `round` always returns a `float` so these were displayed with `.0` at the end, which is misleading (looks like there is one decimal point of precision when there are none). This now formats better with `{x:0.1f}` which is more accurate in the same number of characters.

### CODE REVIEW

**Comment by hoechenberger** [comment]
This looks good to me

And reminded me that we're still reporting an incorrect explained variance here

I think we fixed it in the pipeline ... but let's tackle this later

**Comment by hoechenberger** [comment]
@larsoner I've found it, we want to use this:

https://github.com/mne-tools/mne-python/pull/11141

**Comment by larsoner** [comment]
> @larsoner I've found it, we want to use this:

I looked into doing this briefly. I'm a bit worried that it will be expensive and slow. If you have 10 components for example you'll have to do `ica.apply` 10 times. If you have 2 channel types you now have to do it 20 times, etc. For now I'll remove the explained variance stuff because it's wrong -- it's using PCA explained variance not var exp by each ICA component.

And even once we do it per component, we probably don't want a cumulative one since they aren't necessarily orthogonal (I think?) you could end up with more than 100% variance explained if you add up the variances explained by all components. In that sense it doesn't really make sense to make it cumulative.

**Comment by larsoner** [comment]
@hoechenberger if you think it's worth the computational cost feel free to open an issue pointing to this discussion so we don't forget to add it back in. We might want for example `exp_var=True | False` kwarg to say whether or not to do these computations

**Comment by hoechenberger** [comment]
> We might want for example `exp_var=True | False` kwarg to say whether or not to do these computations

Absolutely!

**Review by drammock — APPROVED** [review]

**Comment by larsoner** [comment]
Failures are unrelated and should be fixed by fixes I snuck into https://github.com/mne-tools/mne-python/pull/12026

**Review by hoechenberger — APPROVED** [review]

**Comment by hoechenberger** [comment]
Thanks @larsoner!

**Pull request merged**
