### PR TITLE
MRG: Remove 2.6

### LINKED ISSUE #3529: python 2.6 and nibabel - how about dropping python 2.6?
Travis is failing on python 2.6 due to zero length field name in format [here - in nibabel]( https://github.com/nipy/nibabel/blob/master/nibabel/deprecator.py#L149).
Nibabel does not support python 2.6 - maybe it's time to drop support of python 2.6 in mne too? :)

### PR DESCRIPTION
**Pull request by Eric89GXL**
Closes #3529.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
Let's see if the CIs are happy with this

**Comment by Eric89GXL** [comment]
Ready for review/merge from my end. CIs are happy, including a `[circle full]` build in there that included all CircleCI-relevant changes.

**Comment by mmagnuski** [comment]
Looks good - especially the red in line changes and the green of happy CIs. :)

**Comment by agramfort** [comment]
LGTM

@yarikoptic any potential issue for Debian packaging?

**Comment by yarikoptic** [comment]
nope! we are well beyond 2.6.. pushed to alioth pkging update:

```
commit 413eda34d04aebb7df520a6aa4de0e9b7cb992c9
Author: Yaroslav Halchenko <debian@onerussian.com>
Date:   Fri Aug 26 12:13:43 2016 -0400

    upcoming release drops compat with python 2.6

diff --git a/debian/control b/debian/control
index 2a2af01..b5984de 100644
--- a/debian/control
+++ b/debian/control
@@ -28,7 +28,7 @@ Standards-Version: 3.9.8
 Vcs-Browser: http://anonscm.debian.org/gitweb/?p=debian-med/python-mne.git
 Vcs-Git: git://anonscm.debian.org/debian-med/python-mne.git
 Homepage: http://martinos.org/mne
-X-Python-Version: >= 2.6
+X-Python-Version: >= 2.7
```

**Comment by agramfort** [comment]
Great thx guys !

**Pull request merged**
