### PR TITLE
[MRG] Layout created for spatial_colors if not found.

### PR DESCRIPTION
**Pull request by jaeilepp**
Closes https://github.com/mne-tools/mne-python/issues/3411
Now the layout is generated from channel positions if it is not detected when plotting with ``spatial_colors``.

### CODE REVIEW

**Comment by jona-sassenhagen** [comment]
Looks good to me, thanks @jaeilepp !

**Comment by jasmainak** [comment]
I can confirm it works for me

**Comment by agramfort** [comment]
thx @jaeilepp you deserved your tennis game...

**Comment by jaeilepp** [comment]
I sure did.

**Pull request merged**
