### PR TITLE
WIP,MNT: Use the GUI API in Intracranial Electrode Locator

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR follows https://github.com/mne-tools/mne-python/issues/9710#issuecomment-1102877540 and refactors the `IntracranialElectrodeLocator` to use the mne GUI API. The goal is to allow consistent support on both `pyvistaqt` and `notebook` (hopefully). It also centralizes the bare "Qt" code in `mne.viz.backends._qt`.

This is still work in progress. For example, I plan to refactor the "button bar" concept by the `_AbstractToolBar` and "bottom bar" by `_AbstractStatusBar`.

ToDo:
- [x] create a `_MNEMainWindow`
- [x] initialize the window
- [x] add support for grid layout
- [x] refactor "button bar" into `_AbstractToolBar`
- [x] refactor "bottom bar" into `_AbstractStatusBar`
- [x] refactor message box into `_AbstractDialog`
- [x] refactor "slider bar" into `_AbstractDock`
- [x] Fix the group selector
- [x] add support to `QListView`
- [x] Find a solution for `_key_press_event`
- [x] Fix `QLineEdit`
- [ ] Split the PR (qt_keypress, qt_list_view, qt_dialog, qt_window)

Further consideration:
* Remove duplicated widget code between containers (centralize in a `_CoreWidget` class)

Closes #9710

### CODE REVIEW

**Comment by larsoner** [comment]
> Extract in smaller PRs

So far the PR is remarkably small, so hopefully we won't need this. Once the abstraction is done and @alexrockhill is happy with the interactions, if everything works and it's still fairly small (~+300/-300 ish?) then I don't think we need to split.

**Comment by larsoner** [comment]
I just noticed you say so at the top. So never mind my question, go go @GuillaumeFavelier !

**Comment by GuillaumeFavelier** [comment]
> ... and the goal here is really to close https://github.com/mne-tools/mne-python/issues/9710, right?

Good call, I forgot to mention it. I'll update the first comment.

**Comment by alexrockhill** [comment]
Should I test it now?

**Comment by larsoner** [comment]
Can we pin to a version that works, preferably with `!=` for now? Then hopefully the next version they release doesn't have this problem. If it does, we add another `!=`. It really seems like something they'd want to fix, you shouldn't need to build wheels locally nowadays...

**Comment by larsoner** [comment]
I will review as you split it up -- @alexrockhill can you do the hands-on testing here to see how things work?

**Comment by alexrockhill** [comment]
I think this is more related to the darkmode changes than this PR but the white text on gray of the header and bottom bars don't look very good.

Screen Shot 2022-05-18 at 9 50 25 AM

One thing that would be nice to add I'm realizing is a zoom text box, that's for a PR after this though. That way if you zoom too far out or in you can reset to 1.

The only thing related to this PR that seems a bit off is that when you go to manually assign the color group of the contact with the dropdown color menu, as you scroll your cursor along the different colors, each is covered by the current color so you can't see the color you're about to select. I think before, the color wasn't changed until it was selected, not just hovered over.

**Comment by GuillaumeFavelier** [comment]
> I think this is more related to the darkmode changes than this PR but the white text on gray of the header and bottom bars don't look very good.

I understand the situation with the screenshot. For now, theming is disabled because it is not compatible with the color menu, it changes the style too. Also automatic theme detection is not implemented yet either so a workaround would be to reopen the app after changing the theme I guess.

> One thing that would be nice to add I'm realizing is a zoom text box

Good idea!

>  as you scroll your cursor along the different colors, each is covered by the current color so you can't see the color you're about to select.

That's a strange one, I think I have the same issue on `main` though. I'll see how to fix this.

**Comment by GuillaumeFavelier** [comment]
I have to clarify two elements:
* I disabled any type of dark theme support in this PR because it is not compatible with the color menu. I introduced the `theme_support` variable for that, which prevents the `_window_set_theme()` function to set a stylesheet.

This is how it looks on my linux with `MNE_3D_OPTION_THEME=dark` and `theme_support=True`:

https://user-images.githubusercontent.com/18143289/169494109-450a241c-be41-4e25-b700-bfe47fe46e4d.mp4

This is how it looks on my linux with `MNE_3D_OPTION_THEME=dark` and `theme_support=False`:

https://user-images.githubusercontent.com/18143289/169496577-fe89724a-c051-4264-abf4-413d3d9ff7e9.mp4

So the automatic theme code is not broken @larsoner, this is just because of this new variable.

But the screenshot shared by @alexrockhill shows that `theme_support=False` is not enough to mitigate this for macOS. It's probably that the system itself just overrides the widget style anyway.

I could not find an easy fix for the color menu in dark mode but maybe we could set the theme to light instead?

Note that "automatic theme switching" is a different scenario, that's why I said:

> a workaround would be to reopen the app after changing the theme I guess.

* > Also automatic theme detection is not implemented yet either

Sorry for the confusion, what I mean here is "automatic theme switching", which works only on macOS AFAIK but is not implemented yet. This is related to https://github.com/mne-tools/mne-python/issues/9182#issuecomment-1064149038

**Comment by GuillaumeFavelier** [comment]
My previous comment is long. **TL;DR**: I will set the theme to `light` until the issue with the color menu is fixed and also add support for "automatic theme switching" shortly.

**Comment by GuillaumeFavelier** [comment]
I tried forcing the theme to `'light'` but the color menu has the same issue. So basically as long as the palette is changed, the color menu has this bug. I'll see how to fix it.

**Comment by GuillaumeFavelier** [comment]
Meanwhile I will open a PR to add support for automatic theme switching, it still benefits the other apps.

**Comment by GuillaumeFavelier** [comment]
I fixed the issue with the color menu so the `theme_support` variable is not necessary anymore

**Comment by GuillaumeFavelier** [comment]
... which means the Intracranial Electrode Locator can support dark mode again with the GUI API.

**Comment by larsoner** [comment]
@alexrockhill could you take over and finish?

**Comment by alexrockhill** [comment]
Ok, I've looked this over thoroughly now and my opinion is to slow this way down. We are definitely not getting not getting the notebook abstraction for free, it's coming at a rather large readability and usability cost of passing everything through the renderer instead of properly abstracting each widget/GUI item. I really do not want to be involved in maintaining the iEEG location GUI if it's going to have notebook support at this cost. I am happy to slowly move each item over PR-by-PR but since a lot of this is already written in abstract classes that have already been merged, I fear the roadmap has been laid in a direction I am very much not in favor of. I propose starting over by removing and re-adding everything in `mne/viz/backends/_abstract.py` that has been added that would go into the iEEG GUI. It can just be changed not removed, but clearly that will impact the notebook backend and things that depend on it. Looking now, it looks like all of this is already in the `coreg` GUI and so would have to be rewritten. Since this was a big undertaking, that's not really something I want to take on so it looks like there's an impasse as far as the two Qt-Dependent MNE-Python GUIs. @hoechenberger, mentioned a top-to-bottom rewrite again of the coreg GUI since it's not at all intuitive so maybe that's a direction forward. I just foresee this being a huge time sink although I am happy to work on abstracting this more slowly in coming PRs on GUIs.

**Comment by larsoner** [comment]
@alexrockhill should we close this in favor of transitioning the existing GUI to your new framework? Do you see this as a lot of work?

**Comment by alexrockhill** [comment]
> @alexrockhill should we close this in favor of transitioning the existing GUI to your new framework? Do you see this as a lot of work?

I don't think it will be too much work but it will definitely take some PRs. I did it for the stc viewer and it took a couple hours. It would be nice to move that to the new GSoC GUI though so mne.viz.Brain can be a bit cleaner.

**Pull request closed without merging**
