### PR TITLE
[MRG] Interactive times in topomap.

### PR DESCRIPTION
**Pull request by jaeilepp**
Still needs work on visuals.

### CODE REVIEW

**Comment by jaeilepp** [comment]
This is how it looks like now:
topomap

Ready for review.

**Comment by Eric89GXL** [comment]
There is no doc update about `interactive` mode? Otherwise LGTM.

Maybe we should have a separate `interactive` flag. This would allow setting the initial time and making it interactive, which is nice.

Then I think the question becomes what do we do with multiple time points and `interactive=True`. We could e.g. keep the spacing the same between the chosen time points when the user clicks. This could make for some cool browsing (e.g., if you do `times=[0., 0.1, 0.2], interactive=True` you could watch the activity flow right to left an you click rightward). Or for simplicity we error if `interactive=True` and `times` is multiple points.

**Comment by agramfort** [comment]
I would stick to times='interactive" and don't add another option. So I
think the current API is fine

**Comment by Eric89GXL** [comment]
Okay I can live with it.

**Comment by agramfort** [comment]
travis is not happy and I think you broke the default behavior.

here is my debug script:

```
import os.path as op
import mne

data_path = mne.datasets.sample.data_path()
fname = op.join(data_path, 'MEG', 'sample', 'sample_audvis-ave.fif')
evoked = mne.read_evokeds(fname, baseline=(None, 0), proj=True, condition=0)
evoked.plot_topomap()
```

**Comment by agramfort** [comment]
@jaeilepp it's working but I see a red vertical bar in the background of the black butterplot plot

can you confirm and if so remove it?

see with:

```
import os.path as op
import mne

data_path = mne.datasets.sample.data_path()
fname = op.join(data_path, 'MEG', 'sample', 'sample_audvis-ave.fif')
evoked = mne.read_evokeds(fname, baseline=(None, 0), proj=True, condition=0)
evoked.plot_topomap(times='interactive')
```

**Comment by jaeilepp** [comment]
It's the time point in the beginning. Feature of mpl. I'll see if it can be removed.

**Comment by agramfort** [comment]
works perfectly !

thx @jaeilepp

**Pull request merged**
