### PR TITLE
[MAINT, MRG] Fix nilearn intersphinx

### PR DESCRIPTION
**Pull request by alexrockhill**
Fixes warning causing CIs to fail in https://github.com/mne-tools/mne-python/pull/10824.

### CODE REVIEW

**Comment by alexrockhill** [comment]
I was editing the wrong configuration file in the main `mne` module and not in `docs` this should fix it now.

**Comment by alexrockhill** [comment]
It looks like this fixed the warning but nilearn's intersphinx obj is timing out... It was doing that intermittently locally.

**Comment by alexrockhill** [comment]
Turns out it wasn't intermittent, they just moved to a stable/latest structure.

**Comment by drammock** [comment]
rather than ignoring the warning, it would be better to fix this upstream. See, e.g.

- https://github.com/mcmtroffaes/sphinxcontrib-bibtex/pull/302
- https://github.com/numpy/numpydoc/pull/403

for examples

**Comment by alexrockhill** [comment]
Huh the job was abandoned at 98% complete. Okay, @drammock, I'm removing the warning filters and I'll write a PR over there.

**Comment by alexrockhill** [comment]
This should be good to merge, it will fix one thing going wrong with the CIs today at least.

**Comment by larsoner** [comment]
Thanks @alexrockhill

**Pull request merged**
