### PR TITLE
FIX: Brain lights

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR fixes the 3 light system:

PR | master
--|--
image | image

The patch is just shared to all renderers. Such a function is already implemented on pyvista master so the function `update_lighting()` will be replaced by `enable_3_lights()` in the future.

### CODE REVIEW

**Comment by larsoner** [comment]
Perhaps a separate bug, it looks like the lighting is asymmetric:

1. the back/posterior of the left hemisphere and the front/anterior of the right hemisphere are illuminated, and
2. the front/anterior of the left hemisphere and the back/posterior of the right hemisphere are dark

Are the lights set up to illuminate equivalently the left and right? Are they attached to the camera, or to the world?

**Comment by GuillaumeFavelier** [comment]
> Are the lights set up to illuminate equivalently the left and right?

I think we use the `_orient_lights()` function for that:

https://github.com/mne-tools/mne-python/blob/2c485d57331543652b16a29167c86a4b5b0ee128/mne/viz/_brain/_brain.py#L528-L529

https://github.com/mne-tools/mne-python/blob/2c485d57331543652b16a29167c86a4b5b0ee128/mne/viz/backends/_pyvista.py#L265-L270

**Comment by GuillaumeFavelier** [comment]
> Are they attached to the camera, or to the world?

`Light 0` is a Headlight, `Light 1` and `Light 2` are CameraLights.

And according to VTK doc:

> A Headlight is always located at the camera and is pointed at the camera's focal point. The renderer is free to modify the position and focal point of the camera at any time.

> A CameraLight is also attached to the camera, but is not necessarily located at the camera's position. CameraLights are defined in a coordinate space where the camera is located at (0, 0, 1), looking towards (0, 0, 0) at a distance of 1, with up being (0, 1, 0). CameraLight uses the transform matrix to establish this space.

Reference: https://vtk.org/doc/nightly/html/classvtkLight.html#a1e0175706ef066ca837726425bdcc6d7

**Comment by larsoner** [comment]
Okay here it was on your commit:

Screenshot from 2021-03-01 12-43-03

And here it is on mine that I just pushed -- the lighting is uniform left/right which I think is important (otherwise you end up with the asymmetry I mention above):

Screenshot from 2021-03-01 13-00-01

Okay for you @GuillaumeFavelier ?

**Review by agramfort — APPROVED** [review]

**Comment by GuillaumeFavelier** [comment]
Yes, all good 👌

**Comment by larsoner** [comment]
Thanks @GuillaumeFavelier !

**Pull request merged**
