### PR TITLE
scale figsize in plot_events depending on n unique events

### PR DESCRIPTION
**Pull request by sappelhoff**
- xref #12835 

@larsoner what do you think of this "low hanging fruit" improvement?

Using this MWE (if you checkout and install my branch here), this scales well to a number of 40 unique events. It looks a bit small in this PR preview, but on my screen it looks fine. Beyond scaling factor 2, it all gets wonky.

```python
# %%
import numpy as np
import mne

events = np.arange(300).reshape(-1, 3)

if 1:
    for i in range(10, 100, 10):
        fig = mne.viz.plot_events(events[:i, :], show=True)
        figsize = fig.get_size_inches()
        print(f"previous was: n events: {i}, Figure size: {figsize}")

# Looks good up to 40 unique events
report = mne.Report("try")
report.add_events(events[:40, :], title="events", sfreq=100)
report.save("try.html", overwrite=True)
```

# 20 unique events (no changes compared to `main` ... and any fewer events will also produce same size fig)

image

# 30 unique events (slightly bigger figure, no events cut off)
image

# 40 unique events (max scaling, no events cut off)
image

# 60 unique events (same scaling as for 40, now some events cut off)
image

### CODE REVIEW

**Comment by larsoner** [comment]
Looks good!

Maybe another easy improvement would be to only create the legend for the first `[:40]` handles and labels? That way we cut off the legend ourselves. Could even use the first `[:40]` handles and `labels[:39] + ["..."]` in cases where there are more than 40 to make it clear we've truncated?

**Review by agramfort — APPROVED** [review]
useful magic :)

**Comment by sappelhoff** [comment]
> Maybe another easy improvement would be to only create the legend for the first [:40] handles and labels?

@larsoner with https://github.com/mne-tools/mne-python/pull/12844/commits/dac65e44d8a1c2611485570af0e2ea4a018bc49f I opted instead to "magically" spread the legend over more columns.

This fixes the layout also for plots that contain really high amounts of different events, see for example the previous case of 60 unique events:

```python
import numpy as np
import mne

events = np.arange(300).reshape(-1, 3)
n = 60
event_id = {f"very long string indeed even longer {i}": j for i, j in enumerate(events[:n, -1])}
fig = mne.viz.plot_events(events[:n, :], event_id=event_id, show=True)
```

image

With respect to the `mne.Report`, the changes here will also make it work "out of the box" for more cases than before, but will still lead to problems for some edge cases like:

- even more unique events (so the additional figure scaling is still not enough)
- very long `event_id` keys (so spreading over legend columns would lead to cutoffs in the horizontal again)

But all in all, I think this is about as much magic as we should introduce:

- it fixes a good amount of cases
- it does not introduce new problems (in that: people getting their plots cut off, would also have had them cut off with the previous code)
- remaining issues should be approached with proper PRs, like dealing with html, as you suggested in [#12835 ](https://github.com/mne-tools/mne-python/issues/12835#issuecomment-2337907662)

Ready for merge from my side :-)

**Comment by sappelhoff** [comment]
@larsoner I had one more idea on how to make the overview better when many events are supplied (and not worse when only few are supplied), see: https://github.com/mne-tools/mne-python/pull/12844/commits/b499f7b47e3c19c8610087fcf31a0bacb9d48c0f

When there are many events, the visual mapping between a dot on the canvas and the event_id becomes impossible. therefore a "duplicating" (strictly speaking) mapping in the legend would lead to a better correspondence, see examples:

Instead of having the count `n` just as `some event id string (n)` or `N=n` when `event_id=None`, it is now:

- `some event id string (id=1234; N=n)`
- `id=1234; N=n`


image


image

**Comment by larsoner** [comment]
Beautiful!

How about touching some events tutorials/examples and the report tutorial just so we can see CircleCI render them, then marking for ready assuming they look good?

If you really want to venture into bonus territory you could open a PR to MNE-BIDS-Pipeline that [makes CircleCI there install MNE-Python using your `sappelhoff:events` branch](https://github.com/mne-tools/mne-bids-pipeline/blob/9b35993408729456b483e5ea8fab64ebf3578f2b/.circleci/config.yml#L51) rather than `upstream/main` and we could inspect the reports there. But if not then we can merge this assuming MNE-Python's tutorials look good and I can bother you later if I see problems in MNE-BIDS-Pipeline :slightly_smiling_face:

**Comment by sappelhoff** [comment]
Thanks for the feedback, I will go to the bonus territory as soon as I find a chunk of time!

**Comment by sappelhoff** [comment]
# Examples for mne website

unfortunately, all of them are clipped now 🥲 

1. [before](https://mne.tools/stable/auto_examples/preprocessing/epochs_metadata.html#sphx-glr-auto-examples-preprocessing-epochs-metadata-py), [after](https://output.circle-artifacts.com/output/job/f845dc84-db16-4c53-a879-3c3e3a9b1bf9/artifacts/0/html/auto_examples/preprocessing/epochs_metadata.html#sphx-glr-auto-examples-preprocessing-epochs-metadata-py)
1. [before](https://mne.tools/stable/auto_tutorials/raw/20_event_arrays.html#sphx-glr-auto-tutorials-raw-20-event-arrays-py), [after](https://output.circle-artifacts.com/output/job/f845dc84-db16-4c53-a879-3c3e3a9b1bf9/artifacts/0/html/auto_tutorials/raw/20_event_arrays.html#sphx-glr-auto-tutorials-raw-20-event-arrays-py)
1. [before](https://mne.tools/stable/auto_examples/datasets/limo_data.html#sphx-glr-auto-examples-datasets-limo-data-py), [after](https://output.circle-artifacts.com/output/job/f845dc84-db16-4c53-a879-3c3e3a9b1bf9/artifacts/0/html/auto_examples/datasets/limo_data.html#sphx-glr-auto-examples-datasets-limo-data-py)
1. [before](https://mne.tools/stable/auto_tutorials/clinical/60_sleep.html#sphx-glr-auto-tutorials-clinical-60-sleep-py), [after](https://output.circle-artifacts.com/output/job/f845dc84-db16-4c53-a879-3c3e3a9b1bf9/artifacts/0/html/auto_tutorials/clinical/60_sleep.html#sphx-glr-auto-tutorials-clinical-60-sleep-py)
1. [before](https://mne.tools/stable/auto_tutorials/preprocessing/70_fnirs_processing.html#sphx-glr-auto-tutorials-preprocessing-70-fnirs-processing-py), [after](https://output.circle-artifacts.com/output/job/f845dc84-db16-4c53-a879-3c3e3a9b1bf9/artifacts/0/html/auto_tutorials/preprocessing/70_fnirs_processing.html#sphx-glr-auto-tutorials-preprocessing-70-fnirs-processing-py)
1. [before](https://mne.tools/stable/auto_tutorials/intro/10_overview.html#sphx-glr-auto-tutorials-intro-10-overview-py), [after](https://output.circle-artifacts.com/output/job/f845dc84-db16-4c53-a879-3c3e3a9b1bf9/artifacts/0/html/auto_tutorials/intro/10_overview.html#sphx-glr-auto-tutorials-intro-10-overview-py)


# Examples from mne-bids-pipeline

- [ERP CORE P3 before](https://mne.tools/mne-bids-pipeline/stable/examples/ERP_CORE/sub-015_ses-P3_task-P3_report.html#Events)

image

- [ERP CORE P3 after](https://output.circle-artifacts.com/output/job/aeb4cd25-7136-43d5-9891-0218f6eb3a20/artifacts/0/site/examples/ERP_CORE/sub-015_ses-P3_task-P3_report.html#Events)

image


---

- [mobi gait before](https://mne.tools/mne-bids-pipeline/stable/examples/ds001971/sub-001_task-AudioCueWalkingStudy_report.html#Events)

image

- [mobi gait after](https://output.circle-artifacts.com/output/job/aeb4cd25-7136-43d5-9891-0218f6eb3a20/artifacts/0/site/examples/ds001971/sub-001_task-AudioCueWalkingStudy_report.html#Events)

image


---

As mentioned above, some plots are not affected at all (apart from more info about id and N in legend).

- [faces data before](https://mne.tools/mne-bids-pipeline/stable/examples/ds000117/sub-01_ses-meg_task-facerecognition_report.html#Events)

image

- [faces data after](https://output.circle-artifacts.com/output/job/aeb4cd25-7136-43d5-9891-0218f6eb3a20/artifacts/0/site/examples/ds000117/sub-01_ses-meg_task-facerecognition_report.html#Events)

image



- [attentional blink before](https://mne.tools/mne-bids-pipeline/stable/examples/ds001810/sub-01_ses-anodalpost_task-attentionalblink_report.html#Events)

image

- [attentional blink after](https://output.circle-artifacts.com/output/job/aeb4cd25-7136-43d5-9891-0218f6eb3a20/artifacts/0/site/examples/ds001810/sub-01_ses-anodalpost_task-attentionalblink_report.html#Events)

image


---

And some previously existing problems are not touched / solved at all (here: clipping the legend due to long event_id keys).

- [matching pennies before](https://mne.tools/mne-bids-pipeline/stable/examples/eeg_matchingpennies/sub-05_task-matchingpennies_report.html#Events)

image

- [matching pennies after](https://output.circle-artifacts.com/output/job/aeb4cd25-7136-43d5-9891-0218f6eb3a20/artifacts/0/site/examples/eeg_matchingpennies/sub-05_task-matchingpennies_report.html#Events)

image

**Comment by sappelhoff** [comment]
@larsoner the long texts in the legend are problematic.

For most cases, this could be fixed with text wrapping: https://stackoverflow.com/a/47058132/5201771

Do you think that is something worth trying? any other ideas?

**Comment by sappelhoff** [comment]
# Updated after https://github.com/mne-tools/mne-python/pull/12844/commits/0be3f9a0caf47b0c3b6eb61a19d64cc8b6e435fa

## from mne docs

1. [before](https://mne.tools/stable/auto_examples/preprocessing/epochs_metadata.html#sphx-glr-auto-examples-preprocessing-epochs-metadata-py), [after 0be3f9a0](https://output.circle-artifacts.com/output/job/1bc2c458-67e9-491d-a9f6-a24785abcb07/artifacts/0/html/auto_examples/preprocessing/epochs_metadata.html#sphx-glr-auto-examples-preprocessing-epochs-metadata-py)
1. [before](https://mne.tools/stable/auto_tutorials/raw/20_event_arrays.html#sphx-glr-auto-tutorials-raw-20-event-arrays-py), [after 0be3f9a0](https://output.circle-artifacts.com/output/job/1bc2c458-67e9-491d-a9f6-a24785abcb07/artifacts/0/html/auto_tutorials/raw/20_event_arrays.html#sphx-glr-auto-tutorials-raw-20-event-arrays-py)
1. [before](https://mne.tools/stable/auto_examples/datasets/limo_data.html#sphx-glr-auto-examples-datasets-limo-data-py), [after 0be3f9a0](https://output.circle-artifacts.com/output/job/1bc2c458-67e9-491d-a9f6-a24785abcb07/artifacts/0/html/auto_examples/datasets/limo_data.html#sphx-glr-auto-examples-datasets-limo-data-py)
1. [before](https://mne.tools/stable/auto_tutorials/clinical/60_sleep.html#sphx-glr-auto-tutorials-clinical-60-sleep-py), [after 0be3f9a0](https://output.circle-artifacts.com/output/job/1bc2c458-67e9-491d-a9f6-a24785abcb07/artifacts/0/html/auto_tutorials/clinical/60_sleep.html#sphx-glr-auto-tutorials-clinical-60-sleep-py)
1. [before](https://mne.tools/stable/auto_tutorials/preprocessing/70_fnirs_processing.html#sphx-glr-auto-tutorials-preprocessing-70-fnirs-processing-py), [after 0be3f9a0](https://output.circle-artifacts.com/output/job/1bc2c458-67e9-491d-a9f6-a24785abcb07/artifacts/0/html/auto_tutorials/preprocessing/70_fnirs_processing.html#sphx-glr-auto-tutorials-preprocessing-70-fnirs-processing-py)
1. [before](https://mne.tools/stable/auto_tutorials/intro/10_overview.html#sphx-glr-auto-tutorials-intro-10-overview-py), [after 0be3f9a0](https://output.circle-artifacts.com/output/job/1bc2c458-67e9-491d-a9f6-a24785abcb07/artifacts/0/html/auto_tutorials/intro/10_overview.html#sphx-glr-auto-tutorials-intro-10-overview-py)


## from mne-bids-pipeline

- [ERP CORE P3 before](https://mne.tools/mne-bids-pipeline/stable/examples/ERP_CORE/sub-015_ses-P3_task-P3_report.html#Events)

image

- [ERP CORE P3 after 0be3f9a0](https://output.circle-artifacts.com/output/job/5df697e7-d3ec-4c79-88aa-5f3c7a6adfa1/artifacts/0/site/examples/ERP_CORE/sub-015_ses-P3_task-P3_report.html#Events)

image

---

- [mobi gait before](https://mne.tools/mne-bids-pipeline/stable/examples/ds001971/sub-001_task-AudioCueWalkingStudy_report.html#Events)

image

- [mobi gait after 0be3f9a0](https://output.circle-artifacts.com/output/job/5df697e7-d3ec-4c79-88aa-5f3c7a6adfa1/artifacts/0/site/examples/ds001971/sub-001_task-AudioCueWalkingStudy_report.html#Events)

image

---

- [faces data before](https://mne.tools/mne-bids-pipeline/stable/examples/ds000117/sub-01_ses-meg_task-facerecognition_report.html#Events)

image

- [faces data after 0be3f9a0](https://output.circle-artifacts.com/output/job/5df697e7-d3ec-4c79-88aa-5f3c7a6adfa1/artifacts/0/site/examples/ds000117/sub-01_ses-meg_task-facerecognition_report.html#Events)


image

---
- [attentional blink before](https://mne.tools/mne-bids-pipeline/stable/examples/ds001810/sub-01_ses-anodalpost_task-attentionalblink_report.html#Events)

image

- [attentional blink after 0be3f9a0](https://output.circle-artifacts.com/output/job/5df697e7-d3ec-4c79-88aa-5f3c7a6adfa1/artifacts/0/site/examples/ds001810/sub-01_ses-anodalpost_task-attentionalblink_report.html#Events)

image
---
- [matching pennies before](https://mne.tools/mne-bids-pipeline/stable/examples/eeg_matchingpennies/sub-05_task-matchingpennies_report.html#Events)

image

- [matching pennies after 0be3f9a0](https://output.circle-artifacts.com/output/job/5df697e7-d3ec-4c79-88aa-5f3c7a6adfa1/artifacts/0/site/examples/eeg_matchingpennies/sub-05_task-matchingpennies_report.html#Events)

image

**Comment by sappelhoff** [comment]
☝️ https://github.com/mne-tools/mne-python/pull/12844/commits/0be3f9a0caf47b0c3b6eb61a19d64cc8b6e435fa clearly overshot with the `fontsize="x-small"` setting.

However, I have tested many more cases locally and found a few extra adjustments that we can try. See: https://github.com/mne-tools/mne-python/pull/12844/commits/754a8a4c45b59ab79bea503d4fbe0c08fec917e6

For me this works quite well locally (on my personal examples), and also looks good when running the examples.

Let's see how it looks online.

**Comment by larsoner** [comment]
Yes I think overall the wrapping is an improvement. I don't think we can aim at perfection and what you have now is already an improvement in almost all cases so I think we can merge once you have another look through the examples. No need to link them all again since you've already linked plenty above -- I'm happy to trust your eyes for the last run(s), so you can just look and say "yes they look better" to save yourself some time :slightly_smiling_face: 

And at the end of the day if people have event ids that are super long they should probably consider renaming them with abbreviations in the `event_id` they pass in to `plot_events` or something like that. So I'm okay with those looking a little wacky. You could document this option/idea, though, if it's not in there. Or we can add it later once we check that it actually works.

**Comment by sappelhoff** [comment]
>  I don't think we can aim at perfection and what you have now is already an improvement in almost all cases

Thanks! I was starting to go mad :-)

A little improvement was everything I was aiming for in the first place. Seemingly low hanging fruit 😉 

I will report back when the circleci renderings for mne and mne-bids-pipeline are out and I am happy.

**Comment by sappelhoff** [comment]
@larsoner I checked all outputs again, and (if you ask me) we have an improvement for every example I looked at now. Ready for merge from my side!

**Comment by larsoner** [comment]
Failure is unrelated, thanks @sappelhoff !

**Pull request merged**
