### PR TITLE
RM simple reading

### PR DESCRIPTION
**Pull request by teonlamont**
this will increase the coverage of the edf module. since there wasn’t
test data, the option for uneven sampling rates was never checked.
instead, we have forced the reading of data channel-wise.

also include an uneven test file.

### CODE REVIEW

**Comment by teonlamont** [comment]
I think we should also resolve issue https://github.com/mne-tools/mne-python/issues/1783 with this pr.

**Comment by agramfort** [comment]
can you have a look at travis?

+1 for addressing #1783

**Comment by teonlamont** [comment]
travis is happy again. as for whether we should make the data compatible with EEGLab, I feel like the EEGLab way just adds unnecessary copies of the data for the resampling since there's no interpolation over the new time samples. One idea is that in the testing we could just do the resample there when we compare it to EEGLab. another option is to have an option to switch between the two ways although i'm -1 for adding another argument, if possible.

**Comment by agramfort** [comment]
I love these red lines :)

did you check with all your test files?

**Comment by agramfort** [comment]
no strong opinion on eeglab stuff

**Comment by teonlamont** [comment]
@agramfort I decided to leave it the way we have but to upsample the uneven edf file to compare the data. mind looking at the `test_edf.test_edf_data`? i'm getting a 0.045%  mismatch :/

**Comment by agramfort** [comment]
how big is the mismatch? what if you use decimal=4 in assert_almost_equal?

**Comment by teonlamont** [comment]
even with decimal=4, it's mismatch 0.0454545454545%

**Comment by teonlamont** [comment]
so i just discovered that there is some jitter in their resampling of the data so that the transition between their original data values shift by a sample, but the jitter is not periodic. this is why the arrays are mismatched ever so slightly. there are 80 data points that are affected.

**Comment by agramfort** [comment]
bug in eeglab?

**Comment by teonlamont** [comment]
yeah, there is. it's because they do the following:
-upsample = the least common multiple of the channel sampling rate
-sample = channel sampling rate
 
```data((1:size(data) * upsample / samp) / (samp / upsample), : )```

instead of 
``reshape(repmat(data, 1, upsample / samp)', 1, size(data, 1)*upsample / samp)``

i just emailed the developer of the BIOSIG, the package shared between fieldtrip and eeglab, to point out the jitter that could occur.

I have an updated exported data from me changing the line in the source code.

**Comment by agramfort** [comment]
can you squash commits?

then +1 for merge

thanks @teonlamont !

**Pull request merged**
