### PR TITLE
MRG+2: Add convenience function for launching docs

### PR DESCRIPTION
**Pull request by Eric89GXL**
I would use a function like this a lot, I assume I'm not alone?

### CODE REVIEW

**Comment by jona-sassenhagen** [comment]
Cool idea I think.

Maybe a hint at this existing could be given when a user first import `mne`.

**Comment by Eric89GXL** [comment]
I don't like printing things unless people ask.

But we could eventually add it to tutorials, teaching materials, etc.

**Comment by agramfort** [comment]
LGTM

**Comment by dengemann** [comment]
Nice idea. I like this.

**Comment by dengemann** [comment]
Maybe the name could be more explicit. Docs is not an English verb and gives us no clue that `mne.utils.docs` is there to be called. Why not `get_docs` or so?

**Comment by mmagnuski** [comment]
I like that too, and agree that `get_docs` or `open_docs` might be a little better.

**Comment by agramfort** [comment]
+1 for open_docs

**Comment by dengemann** [comment]
+1 for `open_docs`

**Comment by Eric89GXL** [comment]
I don't like `open_docs` as much as `docs` because I'll be annoyed at having to type extra letters every time (and given how often I want to do it, that will add up), but since it's the consensus I can live with it. Pushed.

**Comment by Eric89GXL** [comment]
> Docs is not an English verb and gives us no clue that mne.utils.docs is there to be called

FWIW it's exposed in `mne` so it would have just been easily just `mne.docs()`, not `mne.utils.docs()`. Now it's `mne.open_docs()` in any case

**Comment by christianbrodbeck** [comment]
`mne.help()` would be shorter and consistent with the builtin `help()` for opening docs (although not in the browser)... but you might then expect to be able to use it like `mne.help(mne.io)`

**Comment by Eric89GXL** [comment]
Yeah, that and the no-no of shadowing a builtin dissuaded me from using
help (it was actually the name I used locally originally)

**Comment by agramfort** [comment]
thx @Eric89GXL

**Pull request merged**
