### PR TITLE
MRG: Split _timeviewer.py into multiple files

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
`_timeviewer.py` is getting big, around 1500 lines on `master` and will probably continue to grow as more features are added.

This PR moves some classes in their own files and keep the main `_TimeViewer` class:
* `MplCanvas` which manages `matplotlib` integration as a `QWidget`
* the viewer callbacks (ShowView, IntSlider, TimeSlider, SmartSlider, BumpColorbarPoints, UpdateColorbarScale)
* `_LinkViewer` which synchronize multiple instances of `_TimeViewer`

It's only refactoring but it may help with https://github.com/mne-tools/mne-python/issues/7959

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
This is ready for reviews @agramfort, @larsoner

**Review by agramfort — APPROVED** [review]
@larsoner merge if happy

**Comment by larsoner** [comment]
@GuillaumeFavelier codecov gave some inline comments (awesome!), do you want to take a few minutes to see if you can hit a few of them?

**Comment by GuillaumeFavelier** [comment]
Yes, I'll see what I can do :)

**Comment by GuillaumeFavelier** [comment]
Locally I missed some lines related to matplotlib events in `mplcanvas.py`.

**Comment by larsoner** [comment]
These can be difficult to hit, but we do have `_fake_click` you could use. But we can save that for another PR

**Comment by larsoner** [comment]
(or you can just manually call the callbacks yourself if you want, since we probably have access to them)

**Comment by larsoner** [comment]
Thanks @GuillaumeFavelier

**Pull request merged**
