### PR TITLE
MRG: Make epochs.times read only

### LINKED ISSUE #5642: BUG: Manipulating the times property of Epochs results in wrong data after average if data was not loaded.
#### Describe the bug
An `Epochs` object has a `times` property that can be modified. The effect of modifying this property is inconsistent, depending on whether the `Epochs` object has preloaded data (i.e. `load_data`) was called or not.

I created a test for this bug: https://github.com/thht/mne-python/blob/th/test_timeshift_master/mne/tests/test_timeshift.py

### PR DESCRIPTION
**Pull request by larsoner**
Closes #5642.

### CODE REVIEW

**Comment by dengemann** [comment]
Ok. @larsoner this means upon merge we really need a EpochsPSD object with .freqs as attribute. I wanted to contribute this for a few years now but this may force things :)

**Comment by thht** [comment]
i fear that the following might happen in the (distant) future:

1. somebody writes a method that modifies the `_times` property.
2. nobody remembers that the person is supposed to use `_set_times` instead.
3. the `times` property is not strictly read only anymore.

that is the reason why my PR set the `WRITEABLE` flag to `False` in the property method.

**Comment by larsoner** [comment]
People who change variables whose names are prefixed with an underscore should not expect their code to work for very long (if at all). Such behavior is not supported. Private variables can change name, change behavior, or be removed with no warning. So if we need to worry about this, it's in more a generic documentation / coding practice sense.

**Comment by thht** [comment]
i was referring to the case in which somebody writes a method for `Epochs`, in which case it is, as far as i know, ok to change underscored variables. (decimate et al. do just that, for example)

for instance, i will start implementing the `shift_time` method for `Epochs` soon. knowing this PR and the whole discussion, i am aware that i am supposed to use `_set_times` and even if i did not, you are still aware that `_times` must not be changed directly.

however, let's imagine, i am going to implement this in a few months. i forgot about this PR, see that there is a protected property called `_times` which should do the trick and which i may touch when implementing a method for that class. all tests go green.

are you 100% sure that somebody will notice/remember that `_times` should not be changed directly but always via `_set_times` and stop this from being merged?

**Comment by larsoner** [comment]
Internally yes we will need to use it.

No I am not certain someone will notice, and I agree it's a risk. But 

1. the probability should be high since they are likely to see how we set it elsewhere in epochs.py, and
2. the risk is worth it in my mind for the refactoring it allowed (setting read only once when it's set, and effectively unsetting it only when necessary)

**Comment by thht** [comment]
what about making _times a really private property by calling it __times? this way, it would be more intuitive for future developers that it is probably a bad idea to touch it directly. and it would create something like a hierarchy wrt _set_times.

**Comment by larsoner** [comment]
> what about making _times a really private property by calling it __times

Good call. Even though we haven't used this pattern elsewhere I agree it makes things clearer. Feel free to have a look

**Comment by larsoner** [comment]
(at the commit I just pushed I mean)

**Comment by larsoner** [comment]
... actualy the `__` prefix seemed to be causing problems, so I went with the name `_times_readonly`, whose purpose is more explicit anyway.

**Comment by thht** [comment]
i like it. it's salient and explicit.

**Comment by larsoner** [comment]
Travis is happy other than the `mpl` bug plaguing `master`, ready for review/merge from my end. @thht are you happy?

**Comment by thht** [comment]
i am happy. thanks for taking over!

**Comment by larsoner** [comment]
Thanks for working through what seemed like it should be an easy change, when I made it not so much :)

**Comment by agramfort** [comment]
thx @larsoner and @thht for the team effort !

**Pull request merged**
