### PR TITLE
MRG, MAINT: Fix output

### PR DESCRIPTION
**Pull request by larsoner**
Run our circle-front to check to see if we have the same problem as https://github.com/QB3/sparse-ho/pull/13

### CODE REVIEW

**Comment by larsoner** [comment]
Indeed we have a problem with it being mostly black (the colorbar shows up but not the mesh):

https://38888-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/inverse/30_mne_dspm_loreta.html

**Comment by larsoner** [comment]
... I'll probably look into this early next week

**Comment by larsoner** [comment]
Interesting, we do *not* have the problem with the docker image:

https://38909-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/inverse/30_mne_dspm_loreta.html

But we *do* have a problem with the machine config, as above.

It would be nice to be able to use the docker image... in any case, it would be worth trying our `_BrainScraper` for QB3/sparse-ho#13. I can push a commit for that tomorrow US time unless someone beats me to it

**Comment by larsoner** [comment]
It looks like the machine config, which doesn't work, has a newer Mesa:
```
0.32.dev0 {OpenGL 4.5 (Core Profile) Mesa 21.0.3 via llvmpipe (LLVM 12.0.0, 256 bits)}
```
the docker config, which does work, has an older one:
```
0.32.dev0 {OpenGL 3.3 (Core Profile) Mesa 18.3.6 via llvmpipe (LLVM 7.0, 256 bits)}
```
I have no idea why this would be the case, but it's probably the culprit. I'll try some MESA tweaks to see if I can fix it. It would be nice if we could use the machine config, as it's not only faster + more mem but the docker ones are deprecated and will be removed according to an email I got today from CircleCI.

**Comment by larsoner** [comment]
Found the fix, and I even used our [own docs](https://mne.tools/0.22/generated/mne.viz.set_3d_options.html) (and our [old issues](https://github.com/mne-tools/mne-python/issues/7977#issue-653234935)!

Will merge once I make sure `MNE_3D_OPTIONANTIALIAS=false` was the correct fix and that `MESA_GL_VERSION_OVERRIDE=3.3` was not necessary

**Review by agramfort — APPROVED** [review]

**Review by drammock — APPROVED** [review]
nice detective work @larsoner

**Pull request merged**
