### PR TITLE
WIP: implement sparse matrices for linear_regression_raw

### PR DESCRIPTION
**Pull request by jona-sassenhagen**
Closes #2377 and addresses half of #2331

Q: I'd like to use find_outliers here. However, I get a circular import if I import it in mne.stats.regression. Can I move find_outliers to mne.utils? @dengemann

### CODE REVIEW

**Comment by agramfort** [comment]
Travis not happy. Besides looks clean.

Is it faster on your data? How much?

**Comment by jona-sassenhagen** [comment]
If I'm reading this correctly, average memory usage is down by a lot while speed is perhaps a bit improved.

**Comment by agramfort** [comment]
finally works on my laptop ;)

**Comment by agramfort** [comment]
can you just profile to know where time is spent?

**Comment by agramfort** [comment]
did you test this implementation on your personal datasets?

**Comment by wmvanvliet** [comment]
Ran both versions on 12 subjects.

Original version:

    ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        12   86.727    7.227  636.132   53.011 regression.py:143(linear_regression_raw)

Sparse version:

    ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        12    4.319    0.360  264.253   22.021 regression.py:143(linear_regression_raw)

A huge decrease in time!

**Comment by agramfort** [comment]
Get the same result ? If so let's merge

**Comment by jona-sassenhagen** [comment]
I haven't managed to set up the profiler myself, but that's some impressive numbers. Subjectively, I see decent improvements too. So merge.

**Pull request merged**
