### PR TITLE
FIX: use filtered raw to reduce memory in overview tut

### LINKED ISSUE #6322: BUG: Intro example uses too much memory
Running:
```
$ mprof run plot_introduction.py
$ mprof plot
```
I get:

Screenshot from 2019-05-15 14-44-16

Examples that use over ~1.5 GB (and 1.0 GB is a safer goal) are prone to die on CircleCI, e.g.:

https://circleci.com/gh/mne-tools/mne-python/13124

@drammock can you find a way to cut down the memory usage? Often cropping to a shorter duration (e.g., 60 sec) is enough. Or using `preload=False` where possible. Also a new note of this loose requirement in the revamped dev docs might help.

### PR DESCRIPTION
**Pull request by drammock**
closes #6322

### CODE REVIEW

**Comment by drammock** [comment]
@agramfort @larsoner to me the plots are acceptable when rendered locally. Here is the mprof change:

Figure_1

**Comment by larsoner** [comment]
Can you run a commit with `[circle full]`? That will tell us if it should work on `master`, since the mem requirements are more restrictive when running all examples than when running one.

**Comment by drammock** [comment]
here is the updated rendering: https://13139-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/intro/plot_introduction.html

I'm good with this approach.

**Comment by agramfort** [comment]
thx @drammock 

travis error is legit with new numpy but unrelated to this PR

**Pull request merged**
