### PR TITLE
MRG: Fix example

### PR DESCRIPTION
**Pull request by Eric89GXL**
This should fix recent CircleCI failures.

@mmagnuski can you see if you agree? Basically it makes `raw.plot_psd()` more flexible.

### CODE REVIEW

**Comment by mmagnuski** [comment]
I think this is weird that by default `n_fft` is 256 but when it is set to None then it can be 2048...
Maybe plot_psd should specify n_fft this way? Still, I would find it a bit surprising that I get different spectral resolution when I use `psd_welch` or `plot_psd`...

Another thing is that any int default (like 2048) will be different for files with 250 or 1000 Hz sampling rate (so maybe plot_psd should use a sfreq-dependent n_fft?).

All in all I think that such flexibility would be better set in plot_psd (if None -> min(2048, n_samples)).
Additionally: plot_psd should also have `n_per_seg` that would be passed to `psd_welch`

**Comment by mmagnuski** [comment]
We could also revert throwing error when n_fft > n_samples (in `psd_welch`)

**Comment by Eric89GXL** [comment]
> I think this is weird that by default n_fft is 256 but when it is set to None then it can be 2048...

Whoops, yeah I didn't mean to have it be that way...

>  Still, I would find it a bit surprising that I get different spectral resolution when I use psd_welch or plot_psd...

That's the way it has been for a long time, so this isn't the right place to change it. Let's discuss separately.

> Another thing is that any int default (like 2048) will be different for files with 250 or 1000 Hz sampling rate (so maybe plot_psd should use a sfreq-dependent n_fft?).

Yeah I had the same thought while doing this PR. Let's also do that in another issue/PR.

> All in all I think that such flexibility would be better set in plot_psd (if None -> min(2048, n_samples)).

That's how I had it originally, but it is problematic because the signal length is actually determined within `psd_welch`. So I guess I could put the logic there.

**Comment by Eric89GXL** [comment]
> We could also revert throwing error when n_fft > n_samples (in psd_welch)

I like having this there for people who actually want to manually calculate things. It makes them be more explicit. But for quick things like `raw.plot_psd()` they should just always work.

**Comment by Eric89GXL** [comment]
Okay @mmagnuski, I limited the scope a bit

**Comment by mmagnuski** [comment]
Thanks, I like that better :) LGTM

**Comment by Eric89GXL** [comment]
This is broken on `master` and is making PRs not build properly, so I'll merge once the CIs come back happy

**Comment by agramfort** [comment]
lgtm

**Comment by Eric89GXL** [comment]
Travis full is happy, so I'll merge so the rest of our PRs can benefit

**Comment by mmagnuski** [comment]
Thanks, @Eric89GXL, sorry for the trouble - I somehow missed it on my PR.

**Comment by Eric89GXL** [comment]
So did I and at least one other reviewer, don't sweat it

**Pull request merged**
