### PR TITLE
Replace sec -> s

### PR DESCRIPTION
**Pull request by cbrnr**
I think we should use the official symbol s instead of sec.

### CODE REVIEW

**Comment by cbrnr** [comment]
Errors are related to mne-testing-data hash out of date...

**Comment by cbrnr** [comment]
I can't test this, the download isn't working (`Failed to download 'mne-testing-data-0.141.tar.gz'. Will attempt the download again 2 more times.`).

**Review by agramfort — APPROVED** [review]

**Comment by cbrnr** [comment]
The Sphinx error seems unrelated (error building wheel for `pydata-sphinx-theme`)...

**Comment by cbrnr** [comment]
Upgrading `pydata-sphinx-theme` to the latest commit on `main` seems to fix the problem. I'll move this to a separate PR (and remove it here).

**Review by sappelhoff — APPROVED** [review]

**Comment by agramfort** [comment]
thx @cbrnr

**Pull request merged**
