### PR TITLE
remove old numpy call

### PR DESCRIPTION
**Pull request by massich**

### CODE REVIEW

**Comment by massich** [comment]
Since #6735 uses numpy v.1.12 these lines are no longer needed. 

Shall we add it to `enviroment.yml` as well?

```diff
- - numpy
+ - numpy>=1.12
```

**Comment by agramfort** [comment]
@larsoner any idea what the issue is with circle?

**Comment by larsoner** [comment]
They probably reverted the change having to do with where `RandomState` is documented, I'll push a fix

**Comment by larsoner** [comment]
> Shall we add it to enviroment.yml as well?

Maybe in a different PR. So far we don't list the requirements this way though we probably should. So we should just do all at once.

**Pull request merged**
