### PR TITLE
MAINT: Apply UP038

### PR DESCRIPTION
**Pull request by larsoner**
Convert `isinstance(x, (a, b))` into `isinstance(x, a | b)`.

I guess we need to decide if we actually want this first. But I'm happy to follow `ruff`'s lead/opinion on what's best style practice.

Once merged we should add to `.git-blame-ignore-revs`.

### CODE REVIEW

**Comment by mscheltienne** [comment]
Happy to follow ruff's rules.

**Comment by hoechenberger** [comment]
the | operator only works for Python 3.10+ IIRC

otherwise we need a future import 

i'm happy to see the change in any case

**Comment by agramfort** [comment]
works for me it passes our minimal dep python version.

**Comment by larsoner** [comment]
We will require 3.10+ in the next release so we should be good.

Ruff was actually smart enough to use our `pyproject.toml` to know whether or not to apply the rule, which is neat!

**Comment by agramfort** [comment]
+1

**Comment by hoechenberger** [comment]
Great!

**Review by hoechenberger — APPROVED** [review]

**Review by drammock — APPROVED** [review]

**Review by sappelhoff — APPROVED** [review]

**Pull request merged**
