### PR TITLE
[Release] Bump v0.18.1

### PR DESCRIPTION
**Pull request by massich**

### CODE REVIEW

**Comment by massich** [comment]
@larsoner shall we do something else?

**Comment by larsoner** [comment]
Needs #6350 which needs https://github.com/mne-tools/mne-realtime/pull/5

**Comment by massich** [comment]
But #6350 is brutal. that would break `import mne.realtime`. 

I would have done:
- 0.18 keeps it as it is (deprecated but with all the code)
- 0.19 removes the code, imports `mne_realtime` under the hood and decorates with deprecation
- 0.20 GONE

**Comment by larsoner** [comment]
No, the code is still there. The imports should still work. The docs and examples are removed.

**Comment by larsoner** [comment]
0.18 marks as deprecated and removes from doc, 0.19 removes. This is our standard deprecation pattern...

**Comment by massich** [comment]
#6350 removes from the doc only! great.

**Comment by larsoner** [comment]
Now "just" need:

1. https://github.com/mne-tools/mne-python/commit/f36037d26ac7120e11c7e9823d056299f155bb21 to build on master [on CircleCI](https://circleci.com/gh/mne-tools/mne-python/13260)
2. Restart CircleCI in https://github.com/mne-tools/mne-realtime/pull/5, ensure green
3. Wait for `mne-realtime` master to build on CircleCI
4. Make sure `mne-realtime` deploys to https://mne-tools.github.io/mne-realtime
5. Restart CircleCI build in #6350, ensure green
6. Merge to master, ensure green
7. Then we can backport this stuff to 0.18, ensure green, then release 0.18
8. Remove `mne.realtime` from 0.19.0.dev0 as was being done in #6342 (sorry @teonbrooks I was wrong, they should be removed almost immediately -- but still a new PR after all this tinkering is probably easier since it will just be a `rm -Rf mne/realtime; git commit -am 'API: Remove realtime'` or so)

**Comment by larsoner** [comment]
Closing for #6351

**Comment by larsoner** [comment]
@massich I see the remaining steps as:

- [ ] Merge #6351 to backport deprecation fixes to 0.18
- [ ] Merge #6352 to remove `mne.realtime` from 0.19.0.dev0
- [ ] Ensure both branches green on circle and Travis
- [ ] Check websites for dev and stable (that both link to `mne_realtime` properly)
- [ ] Release 0.18.1 on PyPi

I might but probably won't get around to those two merges. After that we need to wait for CircleCI to update the websites for `dev` and `stable`. Assuming both work, then 0.18.1 should be good to go I think. Feel free to make the release if all goes according to plan!

**Comment by massich** [comment]
After giving a second thought what is the problem of having the real-time tutorials in MNE documentation? In the same way that we have some examples of how to use external libraries with mne? wdyt @drammock ?

**Comment by larsoner** [comment]
I'd rather not, it puts more maintenance burden on us because it's not always trivial to get those examples working and stable

**Comment by agramfort** [comment]
I agree. The point is to make the mne-python project lighter including
to build the doc. We'll add cross-links to external/satellite projects

**Comment by massich** [comment]
ok, I can push the release then

**Comment by larsoner** [comment]
It should be safe to do so, even if https://circleci.com/gh/mne-tools/mne-python/13286 fails for some reason I can fix it today (and the only thing changing there is fixing a link to `mne_realtime`).

**Comment by massich** [comment]
I've run the testsuit so it should work. publishing.

**Comment by massich** [comment]
we can start tweeting about it. cc: @dengemann

**Comment by larsoner** [comment]
First we need to send out the email to the `mne_analysis` listserv, can you do it?

**Comment by massich** [comment]
@larsoner sure. Can you make sure that martions is up-to-date?

**Comment by drammock** [comment]
quoting from what I told @massich on gitter:

> ...given all the hoops that Teon had to jump through at the sprint (with getting separate threads to send/recieve the data) to make an example work, I sort of prefer that all that nightmare get pushed into a separate set of docs for mne-realtime rather than having to deal with it inside MNE-Python docs

**Pull request closed without merging**
