### PR TITLE
ENH: add cov new io

### LINKED ISSUE #1745: ENH: save cov method + loglik to disk
ok @agramfort ?

### PR DESCRIPTION
**Pull request by dengemann**
Addresses and closes #1745 

cc @agramfort

### CODE REVIEW

**Comment by dengemann** [comment]
@agramfort firsrt PR for longtime that has more red than green lines :)

**Comment by dengemann** [comment]
... although I might need to remove the last commit. The strategy will unify computation but of course it will compute the cov on the full raw data in memory.

**Comment by dengemann** [comment]
Removed last commit. Ready to merge.

**Comment by dengemann** [comment]
I squashed / rebased AppVeyor apparently shows the tests for the last commit that I removed while travis is green. Should be good to merge.

**Comment by agramfort** [comment]
Thanks

**Pull request merged**
