### PR TITLE
[release]MNT: bump 0.20 + remove dead code

### PR DESCRIPTION
**Pull request by massich**

### CODE REVIEW

**Comment by massich** [comment]
ok this should be green now and we should be good to go for another amazing journey. This time 0.20.dev0

**Comment by larsoner** [comment]
You going to take care of all of the `montage` deprecation stuff in the next PR then I take it?

**Comment by massich** [comment]
I would do remove the deprecation of the montage in a different PR. (it does not raise error) This PR only took care of the bare minimum to get the CIs green and fix the websites.

My plan was to do montage in a different PR. What I'm not sure is the following: Shall we first refactor the mne/channels and then remove the deprecated code? or remove the deprecated code and then refactor? The latter sounds better, but it has the problem that branch 0.19.x and 0.20 would have differed quite a bit. and might be good to backport it. WDYT?

**Comment by larsoner** [comment]
I would remove then refactor, deal with backporting pain later if we have to

**Pull request merged**
