### PR TITLE
ENH: add helmet view option in coreg

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR adds a checkbox to display the helmet in the Coregistration GUI interface.

image

The diff is relatively short and the feature can be useful as far as I understand.

It's part of #8833

### CODE REVIEW

**Comment by hoechenberger** [comment]
**Amazing** 😍 
This will make my and @SophieHerbst's life much easier, as one won't have to resort to `plot_alignment()` to see the final result of coregistration process!

**Review by hoechenberger — APPROVED** [review]

**Review by agramfort — APPROVED** [review]
great 👍 @GuillaumeFavelier

**Comment by agramfort** [comment]
thx @GuillaumeFavelier

**Comment by hoechenberger** [comment]
❤️

**Pull request merged**
