### PR TITLE
[MRG] ENH: navigate time with keyboard in plot_volume_source_estimates

### PR DESCRIPTION
**Pull request by jasmainak**
Following conversation with @sarangnemo today, I thought I can attack a few low hanging fruits from #5457

### CODE REVIEW

**Comment by agramfort** [comment]
it does not seem to work for me

**Comment by jasmainak** [comment]
oh no, sounds like a mac specific thing. I'll have to check with someone who has a mac ...

**Comment by agramfort** [comment]
Yes I worked when I used the qt backend

**Comment by agramfort** [comment]
it would be great to see if someone else can test

**Comment by larsoner** [comment]
Works and code looks good, thanks @jasmainak

**Comment by larsoner** [comment]
... actually could you add a quick `whats_new.rst` update? then we can merge

you probably should rebase first since @dengemann already added something to `whats_new.rst`

**Comment by jasmainak** [comment]
updated what's new.

**Pull request merged**
