### PR TITLE
(bug?) The `brain_color` parameter of `plot_dipole_locations` seems unused

### PR DESCRIPTION
**Pull request by wmvanvliet**
@Eric89GXL: what's up with the `brain_color` and `mesh_color` parameters of the `plot_dipole_locations` function? The former doesn't seem to be used. It seems to be copied from `plot_sparse_source_estimates`, where it is used to set the color of the glass mesh. In this function, the `mesh_color` parameter is used for this. Perhaps we should deprecate `mesh_color` and use `brain_color` in both functions?

### CODE REVIEW

**Comment by agramfort** [comment]
here brain is "inner skull" right?

**Comment by wmvanvliet** [comment]
yes, `bem/inner_skull.surf`

**Comment by Eric89GXL** [comment]
Yeah that looks like a bug to me, good call

**Comment by wmvanvliet** [comment]
do you agree with the resolution proposed in this PR?

**Comment by Eric89GXL** [comment]
I think it's actually okay not even to deprecate because it was unused and a bug to have it in the first place. Also I doubt this particular function is heavily used.

**Comment by agramfort** [comment]
yes just remove. it's a bug fix.

good catch @wmvanvliet

**Comment by wmvanvliet** [comment]
closing in favor of #2798

**Pull request closed without merging**
