### PR TITLE
MAINT: Fixes for sphinx 7.3

### PR DESCRIPTION
**Pull request by larsoner**
Fix for latest Sphinx leveraging https://github.com/sphinx-gallery/sphinx-gallery/pull/1289

The solution is just to move a bunch of code to `sphinxext/mne_doc_utils.py` and then pass `"mne_doc_utils.<whatever>"` as `str` config values to `sphinx_gallery_conf`

### CODE REVIEW

**Review by agramfort — APPROVED** [review]

**Comment by larsoner** [comment]
@drammock should be ready for manual merge since I skipped azure and actions

**Review by drammock — APPROVED** [review]
we should also really update line 82 of `conf.py` (`needs_sphinx = "2.0"`) to match pyproject.toml (which says `>=6`).  It's too far outside the diff to change via GH gui though :(

**Comment by drammock** [comment]
@larsoner I pushed a commit to update the `needs_sphinx` variable, and broke this PR in a way I've never seen before: linter CI says "error during mergeable check" and circle says  `fatal: Not possible to fast-forward, aborting.` But AFAICT there is no conflict with upstream... GH glitch?

**Comment by larsoner** [comment]
GitHub is having a really bad day

https://www.githubstatus.com/

**Pull request merged**
