### PR TITLE
MRG: Fix flake

### LINKED ISSUE #5657: Travis not passing
For whatever reason, the pep8 checks in travis no longer pass in master. See this:
https://travis-ci.org/massich/mne-python/builds/445633436?utm_source=github_status&utm_medium=notification

### PR DESCRIPTION
**Pull request by larsoner**
Closes #5657.

### CODE REVIEW

**Comment by massich** [comment]
@larsoner you were faster. Do you know anything about the artist error we have in MAC [(here)](https://travis-ci.org/massich/mne-python/jobs/445633439#L2362)?

```sh
―――――――――――――― ERROR collecting mne/channels/tests/test_layout.py ――――――――――――――
mne/channels/tests/test_layout.py:10: in <module>
    import matplotlib
../../../miniconda/envs/test/lib/python3.6/site-packages/matplotlib/__init__.py:1111: in <module>
    rcParamsOrig = RcParams(rcParams.copy())
../../../miniconda/envs/test/lib/python3.6/site-packages/matplotlib/__init__.py:891: in __getitem__
    from matplotlib import pyplot as plt
../../../miniconda/envs/test/lib/python3.6/site-packages/matplotlib/pyplot.py:32: in <module>
    import matplotlib.colorbar
../../../miniconda/envs/test/lib/python3.6/site-packages/matplotlib/colorbar.py:28: in <module>
    import matplotlib.artist as martist
E   AttributeError: module 'matplotlib' has no attribute 'artist'
```

**Comment by massich** [comment]
does it happens in your machine @agramfort

**Comment by larsoner** [comment]
No. I was just looking at it. I'm going to get my OSX laptop and see if I can replicate. I think `matplotlib` released recently, it's possible there is a broken `matplotlib` package in there :(

**Comment by agramfort** [comment]
It passes on my mac laptop

**Comment by larsoner** [comment]
I tried updating `conda` on macOS and starting with a fresh `mne` env and it seems to pass, too

**Comment by larsoner** [comment]
Going to merge this since the failures are unrelated to `flake` and tackle those separately

**Pull request merged**
