### PR TITLE
WIP use nilearn viz for LCMV vol example

### PR DESCRIPTION
**Pull request by agramfort**
here is how it looks like:

figure_3

needs an unreleased version of nilearn so let's wait before merging.

### CODE REVIEW

**Comment by dengemann** [comment]
@agramfort pretty cool. Btw it would be awesome to have some surface reinterpolation mapper to dissplay surface STCs in a volume.

**Comment by agramfort** [comment]
nilearn 1.1 got released so we could merge

@mluessi you'll need to update the buildbot so I'll let you click the green button when you have time.

**Comment by agramfort** [comment]
@mluessi can you install nilearn on buildbot so we can merge this?

**Comment by Eric89GXL** [comment]
@agramfort please add `nilearn` to the Travis and Appveyor builds. If you don't have time I can do it.

**Comment by agramfort** [comment]
this is only needed for the doc build and not by travis. shall we add it anyway?

**Comment by Eric89GXL** [comment]
Ohh right, it's their function not ours so we don't test it or anything. Then no, don't bother. We *could* start having Travis build docs if we want, then we would need it. Would that be worthwhile? If so, feel free to open an issue and I can try it in a subsequent PR at some point.

**Comment by agramfort** [comment]
we need full sample to build the full doc. Not possible with travis... we
need a dedicated public VM...

**Comment by agramfort** [comment]
@mluessi can you just run "pip install nilearn" on buildbot so we can merge this?

**Pull request merged**
