### PR TITLE
Add Python 3.12

### PR DESCRIPTION
**Pull request by cbrnr**
I've replaced Python 3.11 with Python 3.12 in our `pip-pre` test on `ubuntu-latest`.

Which versions do we want to test explicitly? Currently (with this change), we're testing 3.9 (ubuntu-latest/minimal, macos-latest/mamba, ubuntu-20.04/old), 3.10 (ubuntu-latest/conda, windows-latest/mamba), and 3.12.

### CODE REVIEW

**Comment by cbrnr** [comment]
Package dependency hell:

    The user requested numpy>=2.0.0.dev0
    scikit-learn 1.4.dev0 depends on numpy>=1.19.5
    scipy 1.12.0rc1 depends on numpy<1.29.0 and >=1.22.4

**Comment by larsoner** [comment]
I wouldn't do it on the pip-pre job but instead bump a different job. One of the `conda` ones might actually be easiest

> Which versions do we want to test explicitly? Currently (with this change), we're testing 3.9 (ubuntu-latest/minimal, macos-latest/mamba, ubuntu-20.04/old), 3.10 (ubuntu-latest/conda, windows-latest/mamba), and 3.12.

That sounds reasonable. We want to test oldest and newest at a minimum. Beyond that having some coverage is desirable but I don't think full Python version coverage is required.

**Comment by cbrnr** [comment]
> I wouldn't do it on the pip-pre job but instead bump a different job. One of the conda ones might actually be easiest

OK, I bumped the three conda-based jobs. However, conceptually it would make a lot of sense to also use the latest Python for pip-pre IMO.

**Comment by larsoner** [comment]
Looks like `numba` is a problem on those conda runs. Maybe `conda` isn't the way to go, then. These CI configs can be a pain and require lots of experimentation and adjustment!

**Comment by larsoner** [comment]
(Or maybe it's just numba-on-windows-3.12 -- you could try putting that one back to whatever version it was before and see if the Linux and macOS jobs work!)

**Comment by cbrnr** [comment]
Numba 0.59, which hasn't been released yet, will support Python 3.12 (https://github.com/numba/numba/pull/9246).

**Comment by cbrnr** [comment]
[0.59RC1](https://pypi.org/project/numba/0.59.0rc1/) is available on PyPI, so maybe use that with pip-pre?

**Comment by larsoner** [comment]
One solution would be to change just one job (conda linux?) to use 3.12 and before the setup-miniconda or whatever we use nowadays, modify `environment.yml` inplace to remove the `numba` line (only in that job) until a compatible numba is released.

**Comment by larsoner** [comment]
> 0.59RC1 is available on PyPI, so maybe use that with pip-pre?

I thought pip-pre was the job with the incompat due to NumPy 2.0.0.dev0+Py3.12, no? It's unlikely that that RC is NumPy2.0 compatible in any case (and I do think we want to keep testing NumPy 2.0 in the pre job if possible).

Another option since they're already on RC is just to wait a week or two or whatever, *then* bump a conda job (or a few as done here).

**Comment by cbrnr** [comment]
Yes, but the incompatibility was because of SciPy. You're probably right that Numba won't support NumPy 2, but who knows, maybe they have already made their code compatible. So it's probably best to wait a couple of days.

**Comment by larsoner** [comment]
@cbrnr can I push a commit to try my idea of editing `environment.yml`? Then when numba lands we can just remove the 4-5 lines in `tests.yml` that I'd be adding (and would have 3.12 in the meantime)

**Comment by cbrnr** [comment]
Yes, sure!

**Comment by larsoner** [comment]
Okay enabling auto-merge, but will need to manually adjust CI reqs in branch protection rules once it comes back green. I'll try to remember to check back in a bit but if someone sees everything green feel free to ping me

**Review by drammock — APPROVED** [review]

**Comment by larsoner** [comment]
Thanks @cbrnr !

**Comment by cbrnr** [comment]
Thank you @larsoner, you did all the work!

**Pull request merged**
