### PR TITLE
MRG: Move so doctest doesnt use it

### PR DESCRIPTION
**Pull request by Eric89GXL**
Probably a better place for it to be to match up with `flow_diagram.py` anyway

### CODE REVIEW

**Comment by Eric89GXL** [comment]
Ready for review/merge @jaeilepp @jasmainak

**Comment by agramfort** [comment]
Fine with me

**Comment by jasmainak** [comment]
LGTM. Feel free to merge if Travis is happy

**Comment by jaeilepp** [comment]
Thanks @Eric89GXL

**Pull request merged**
