### PR TITLE
Fix incorrect type hint in Neuralynx I/O module

### PR DESCRIPTION
**Pull request by hoechenberger**
An incorrect type hint sneaked in via #11969, causing confusion to static type checkers.

Since we don't use type hints in MNE yet (except for some very rare exceptions), I simply removed the faulty one instead of fixing it.

cc @KristijanArmeni 

FYI the correct hint for our supported versions of Python would be `Optional[List[str]]` or `Union[None, List[str]]`

### CODE REVIEW

**Comment by hoechenberger** [comment]
@larsoner I also think it's unusual that `verbose` isn't the last keyword in the function signature; and the last two parameters should probably be keyword-only. Thoughts?

**Comment by larsoner** [comment]
Yes `verbose` should be last and kw-only (okay to change the exclude one, too). Can you make that change in this PR and I'll merge and backport? I think we can push out a 1.6.1 quickly to get the fix out there before the `*` annoys too many people :)

**Comment by hoechenberger** [comment]
Can you take over please? I'm a bit busy with other stuff :)

**Comment by hoechenberger** [comment]
@larsoner I rearranged the signature but didn't add a changelog entry yet

**Comment by hoechenberger** [comment]
Thanks for cleaning things up, @larsoner!

**Pull request merged**
