### PR TITLE
[DOC] Hyphenation consistency

### PR DESCRIPTION
**Pull request by alexrockhill**
Most tutorials are like so `_tut-working-with-ecog` but a few used underscores as in `_tut_working_with_ecog`. This just makes them all consistent the way the majority are.

### CODE REVIEW

**Comment by alexrockhill** [comment]
Looks like the build had an out-of-date cache from the other PR but it doesn't look legit.

**Review by agramfort — APPROVED** [review]
no objection.

@drammock I think you're the best person to approve this :)

thx @alexrockhill

**Review by agramfort — APPROVED** [review]
no objection.

@drammock I think you're the best person to approve this :)

thx @alexrockhill

**Review by drammock — APPROVED** [review]

**Comment by drammock** [comment]
changes look good, but CircleCI is failing on the "working with SEEG data" tutorial.

**Comment by alexrockhill** [comment]
> changes look good, but CircleCI is failing on the "working with SEEG data" tutorial.

I think there's issues with the cache so it would probably be easiest if #9478 was merged first and then it was rebased. I think that would fix it.

**Comment by alexrockhill** [comment]
Good to merge?

**Review by drammock — APPROVED** [review]

**Pull request merged**
