### PR TITLE
MRG Evoked plots should error nicely on NaN input

### PR DESCRIPTION
**Pull request by jona-sassenhagen**
Trying to plot data with NaNs included can result in some pretty weird output. This raises a `ValueError` at a hopefully sufficiently early time point.

### CODE REVIEW

**Comment by larsoner** [comment]
Is it possible to alternatively handle `nan` nicely e.g. by using `masked_array` and/or `np.nanmean` / `np.nanstd`? For mpl for example it can just mean "omit" which is nice. But if it's too much work we can just error for now and relax it later to be handled properly later.

**Comment by jona-sassenhagen** [comment]
I agree ideally, we would have nicer NaN handling, but I don't have the capacity right now .. For now I prefer to at least fail nicely

**Comment by agramfort** [comment]
@jona-sassenhagen use a proper check function like done in sklearn:

https://github.com/scikit-learn/scikit-learn/blob/f0ab589f/sklearn/utils/validation.py#L47

the code will be easier to understand.

**Comment by larsoner** [comment]
Are +/-inf handled properly? If not, we could use the more general `not np.isfinite(D).any()` and say that we only support finite vals.

**Comment by agramfort** [comment]
+1 for using `np.isfinite(D).any()`

**Comment by jona-sassenhagen** [comment]
It is done.

**Comment by agramfort** [comment]
thx @jona-sassenhagen

**Pull request merged**
