### PR TITLE
WIP:  Interpolator class to cache interpolation matrix

### PR DESCRIPTION
**Pull request by christianbrodbeck**
Addressing #4651

This should be the bare bones of the refactoring.

@larsoner is this enough to make it savable?

And what additional information should we store? The list of bad channels might be good, to make sure it's the same as `inst` before applying?

### CODE REVIEW

**Comment by jasmainak** [comment]
practically speaking, how much speed gain do you observe for EEG and for MEG by caching these matrices?

**Comment by christianbrodbeck** [comment]
computing one interpolation matrix takes in the order of seconds for me

**Comment by jasmainak** [comment]
also for EEG?

**Comment by christianbrodbeck** [comment]
I haven't looked at EEG, only MEG.

**Comment by larsoner** [comment]
> And what additional information should we store? The list of bad channels might be good, to make sure it's the same as inst before applying?

I think the things we'd need to check would be:

1. The set (and order) of good and bad channel names should need to match exactly for it to operate.
2. The sensor coordinates in the head coordinate frame must match to numerical precision.
3. The origin (for MEG, maybe also EEG?) of the approximation must match to numerical precision.

I *think* this is enough to guarantee that the same interpolator can be used.

**Comment by jasmainak** [comment]
okay. IMO, it makes sense only to cache `self_dots` and `self_dots` as EEG interpolation is rather fast

**Comment by christianbrodbeck** [comment]
@jasmainak If we already go through the trouble of managing a cached object, is there an advantage to not caching the rest? I'm also thinking of epoch-wise interpolation, where you might want to apply an interpolator hundreds of times, so it might be preferable to store the highest level possible.

**Comment by jasmainak** [comment]
@christianbrodbeck from what I understood, you only store the `mapping_matrix` but not `self_dots` and `cross_dots` in the Interpolator object. The problem with this approach is that it won't help in epoch-wise interpolation if different epochs have different bad channels ... (if you all epochs have the same bad channel, you might as well do the interpolation on the raw object once before epoching)

My first thought had been to compute an `n_channels` x `n_channels` mapping matrix and slice it, but it cannot be sliced to give you a mapping matrix of `n_channels` x `n_bads`. The math doesn't work out. You can only slice the `self_dots` and `cross_dots` and then you have to assemble the `mapping_matrix` again, but that already saves you significant computation

**Comment by larsoner** [comment]
> You can only slice the self_dots and cross_dots and then you have to assemble the mapping_matrix again, but that already saves you significant computation

If this is indeed the bottleneck, then for you would only ever need one of these for each MEG system, since the electrodes do not move. That would be nice. However, for EEG I doubt it's this simple since it uses some other interpolation mode.

@christianbrodbeck this one is pretty old, perhaps we should close and reconsider the best way to cache the interpolation next time someone hits a need for it?

**Comment by larsoner** [comment]
I'll close since it seems unlikely that this will be implemented soon, and rebases are needed anyway

**Pull request closed without merging**
