### PR TITLE
MRG, MAINT: Smaller PNGs during doc build

### PR DESCRIPTION
**Pull request by larsoner**
Also modernizes our inclusion of backrefs, and considates CircleCI `apt-get` to a single line.

### CODE REVIEW

**Comment by larsoner** [comment]
Manually killing Travis and Azure non-style because they are not relevant

**Comment by larsoner** [comment]
Seems to work, in it goes

**Comment by agramfort** [comment]
did you quantify the gain?

**Comment by larsoner** [comment]
In the Sphinx-gallery PR I did some testing suggesting you could get 20-25% gains with little added build time, but didn't actually test here. Looking at the `mne-tools.github.io` right now, we have `du -hs` of `dev/_images` of 98M and the last couple builds took 1:21:55 and 1:28:04. The `master` build from merging this PR timed out on `plot_mne_dspm_source_localization`, so we'll have to wait for another hour and a half to see the sizes and times now...

**Comment by larsoner** [comment]
I was wrong about the times above, should have listed them as 1:45:40 and 1:53:23. CircleCI finished and uploaded, looks like before/after:

- `dev/_images` size decreases from 98M to 79M (thumbs only: 2.9M to 2.4M)
- Build time increases from 1:53:23 to 2:00:30

There is a lot of variability in the build times, so this could actually be a bit better or worse. But it doesn't look like it's going to end up being too bad.

**Comment by agramfort** [comment]
ok so a 20% decrease roughly

>

**Comment by larsoner** [comment]
yeah

**Pull request merged**
