### PR TITLE
Retain baseline after combining channels

### PR DESCRIPTION
**Pull request by cbrnr**
As discussed [here](https://mne.discourse.group/t/when-is-baseline-correction-applied/4986), this PR retains baseline information after using `mne.channels.combine_channels()` on `Epochs` or `Evoked`.

### CODE REVIEW

**Review by agramfort — APPROVED** [review]
can you add a what's new entry @cbrnr ? 🙏

**Comment by hoechenberger** [comment]
Im wondering if we should keep creating EpochsArray with baseline=None and then inject inst.baseline into the created instance, to make it very clear that the data is in fact not being altered. Because passing baseline to EpichsBaseline is really a no-op except for setting the respective attribute. WDYT?

**Comment by cbrnr** [comment]
Sure, this sounds good!

**Comment by hoechenberger** [comment]
Or just add a comment, maybe that's cleaner?

**Comment by cbrnr** [comment]
Wait, I don't understand. What is the problem with setting `baseline=inst.baseline`?

**Review by agramfort — APPROVED** [review]

**Comment by cbrnr** [comment]
But shouldn't this be clear given how `baseline` works in general? I mean, I don't think it is clear at all (that's why I asked in the forum *when* baselining is actually performed), but once this is clear I don't think a comment here will help. The problem is that at least for me I'm not sure when baseline correction is performed, so maybe we should improve the `Epochs` docs (and related tutorials)?

**Comment by hoechenberger** [comment]
Either I misunderstood something or we're talking about different things :)

All I'm saying is that if you have data with baseline correction already applied, applying the same type of baseline correction **again** won't alter the data.

And my understanding is that this is the case here when you construct `Epochs/EvokedArray`.

Your fix – passing `baseline=inst.baseline` – doesn't alter the data, as it's already baseline-corrected. Or is this assumption false?

If that assumption is correct, the only effect passing `baseline=inst.baseline` will have is that we set `Epochs/EvokedArray.baseline` to the correct value correct provenance.

Therefore I thought it could make sense to document this

But don't feel obliged to hold off with merging here just because I'm acting a little concerned and confused ;)

**Comment by cbrnr** [comment]
> Either I misunderstood something or we're talking about different things :)
>
> All I'm saying is that if you have data with baseline correction already applied, applying the same type of baseline correction again won't alter the data.

Yes. But that's how baselining works in MNE-Python, right?

> And my understanding is that this is the case here when you construct `Epochs/EvokedArray`.
>
> Your fix – passing `baseline=inst.baseline` – doesn't alter the data, as it's already baseline-corrected. Or is this assumption false?

No, that's correct. We're essentially copying metainformation to the new instance with combined channels. I thought this was clear, because we already did it with `tmin=inst.times[0]`.

> If that assumption is correct, the only effect passing `baseline=inst.baseline` will have is that we set `Epochs`/`EvokedArray.baseline` correctly, for provenance.

Yes.

> Therefore I thought it could make sense to document this

I think I get it now. Would a comment like `# copy metainformation to new instance` or something like that be helpful? This implies (at least for me) that we don't actually do anything with the data here.

**Comment by cbrnr** [comment]
I think I'll add this comment right before the new instances are created:

```
# create new instances and make sure to copy important attributes
```

WDYT?

**Comment by hoechenberger** [comment]
Yes, that would be perfect!

**Comment by hoechenberger** [comment]
Perfect, thank you!

**Pull request merged**
