### PR TITLE
MRG: Fix make_watershed_bem() docs

### PR DESCRIPTION
**Pull request by hoechenberger**

### CODE REVIEW

**Comment by hoechenberger** [comment]
Doc artifact:
https://24213-1301584-gh.circle-artifacts.com/0/dev/generated/mne.bem.make_watershed_bem.html?highlight=watershed_bem#mne.bem.make_watershed_bem

**Review by drammock — APPROVED** [review]

**Comment by agramfort** [comment]
thanks a lot @hoechenberger 

can you push the backport in the maint/0.22 branch?

**Comment by agramfort** [comment]
forget it @hoechenberger I just did the backport

**Comment by hoechenberger** [comment]
Thanks agramfort !

**Pull request merged**
