### PR TITLE
MRG+1: Add eximia reader

### PR DESCRIPTION
**Pull request by fraimondo**
Allows Eximia NXE files to be read. Includes testing and comparison with fieldtrip reader.

I still need to update the mne-testing dataset before merging.

It is mostly @larsoner old code with some minor modifications.

### CODE REVIEW

**Comment by fraimondo** [comment]
Now it's good to go.

**Comment by agramfort** [comment]
appveyor is not happy

**Comment by larsoner** [comment]
The PEP8 monster strikes again

https://travis-ci.org/mne-tools/mne-python/jobs/358389671

**Comment by fraimondo** [comment]
Don’t want to fix this one so it doesn’t mix things in PR.

mne/inverse_sparse/mxne_optim.py:282:44: E127 continuation line over-indented for visual indent

**Comment by larsoner** [comment]
Agreed, I fixed it in `master`

**Comment by larsoner** [comment]
CI failure is only due to #5045. @agramfort feel free to merge if you're happy. 

@chrismullins if you are still working with Eximia data you might be interested in trying this.

**Comment by larsoner** [comment]
Actually @fraimondo it looks like you didn't take this check from my PR:

https://github.com/mne-tools/mne-python/pull/3523/files#diff-9bea79340ff7d5d88d51ca40c1015ee7R173

Or the updates to `doc/manual/io.rst`:

https://github.com/mne-tools/mne-python/pull/3523/files#diff-ae8298dab716c60d37e9dc7f52ec1dfb

Any reason why?

**Comment by fraimondo** [comment]
There is a reasonable explanation: I prepared the PR some months ago but I had no testing data and I was tired of merging whenever I was pulling from master. So I left all the conflicting code out, including documentation. And now I forgot to add this stuff.

Update coming.

**Comment by agramfort** [comment]
thx @fraimondo and @larsoner !

**Comment by fraimondo** [comment]
Always a pleasure to collaborate with you.

**Comment by agramfort** [comment]
likewise !

**Pull request merged**
