### PR TITLE
MRG: Add binder to homepage

### PR DESCRIPTION
**Pull request by Eric89GXL**
Should also take care of some other things with #2906 before merge.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
Current render just adds to the homepage:

https://2309-1301584-gh.circle-artifacts.com/0//home/ubuntu/mne-python/doc/_build/html/index.html

**Comment by Eric89GXL** [comment]
This is what the new homepage looks like:

https://2385-1301584-gh.circle-artifacts.com/0//home/ubuntu/mne-python/doc/_build/html/index.html

And this is what the new intro looks like:

https://2385-1301584-gh.circle-artifacts.com/0//home/ubuntu/mne-python/doc/_build/html/auto_tutorials/plot_introduction.html

Ready for review/merge from my end.

**Comment by jaeilepp** [comment]
I don't think it's because of this PR, but something has made the top banner twice the size. Compare it to the stable website http://martinos.org/mne/stable/index.html.

**Comment by mmagnuski** [comment]
@jaeilepp I see the top banner the same size as before. Maybe you are referring to the window-size dependent behavior of the banner?
Narrow window, looks good:
wnd01


Wider window, looks weird:
wnd02

**Comment by jasmainak** [comment]
I think this is a `sphinx-gallery` issue. See also: 
screwedup

**Comment by mmagnuski** [comment]
Yeah, I've seen these golden buttons many times :) I looked throught the sphinx-gallery issues but it seems  these problems were not reported there. And the issue with the banner seems to be sphinx in general, because it works this way everywhere on mne web page.

**Comment by kingjr** [comment]
(Why is it written *basic* MEG processing? We don't do basic here, we do cutting-edge.)

**Comment by Eric89GXL** [comment]
@kingjr that is the basic tutorial page, not the homepage.

I don't think the mentioned comments need to be fixed by this PR (they are unrelated to these commits) -- anything that needs to be done here?

**Comment by kingjr** [comment]
(You see me reassured :))

**Comment by jaeilepp** [comment]
Yeah, I think the issues mentioned here are related to sphinx. Thx @Eric89GXL

**Pull request merged**
