### PR TITLE
[MRG][DOC/ENH] Reorder examples

### PR DESCRIPTION
**Pull request by massich**
This PR reorder the examples in the doc based on some criteria rather than alphabetical.

### CODE REVIEW

**Comment by larsoner** [comment]
Circle is not happy

**Comment by larsoner** [comment]
@drammock can you look?

**Comment by agramfort** [comment]
here is how it looks https://11278-1301584-gh.circle-artifacts.com/0/dev/auto_examples/index.html

I think it's a good improvement.

**Comment by drammock** [comment]
I'm +1 for merging; if it turns out the order can be improved, we can easily change it later.

**Comment by larsoner** [comment]
Thanks @massich

**Pull request merged**
