### PR TITLE
MRG Handle triggers split between buffers

### PR DESCRIPTION
**Pull request by jasmainak**
Taking over https://github.com/mne-tools/mne-python/pull/3696

Closes https://github.com/mne-tools/mne-python/pull/3696 and https://github.com/mne-tools/mne-python/issues/3695

cc @odingod and @LauriParkkonen. Let me know if this works for you guys. Tests pass on my box.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
LGTM. @Odingod can you take a look?

**Comment by Odingod** [comment]
Seems to be working, except for one small bug that is not worth fixing in my opinion. If the the first buffer starts with the trigger channel active the onset is missed and the code gets stuck like it used to. However the trigger channel shouldn't be high at the beginning of the measurement (unless using some kind of continuous measure pressure e.g.?). Maybe this is still worth a mention?

**Comment by Odingod** [comment]
Let's take that back. There was trouble with a test I added that has two triggers at two consecutive buffer lines. For some reason the first one is not found. I'll take a closer what breaks this time. The test can be found from my branch if you'd like to take a look.

**Comment by jasmainak** [comment]
> On closer look everything was fine I just forgot to change the assertion comparison...

Great, so ready to merge?

> Seems to be working, except for one small bug that is not worth fixing in my opinion. If the the first buffer starts with the trigger channel active the onset is missed and the code gets stuck like it used to. However the trigger channel shouldn't be high at the beginning of the measurement (unless using some kind of continuous measure pressure e.g.?). Maybe this is still worth a mention?

I would say it is expected that an event is not detected? Does this get detected as an `event` in the offline version? I think what is perhaps a bit unintuitive to the user is the "getting stuck" part since the `isi_max` is set to 0.5. I think it is worth changing [this behavior](https://github.com/mne-tools/mne-python/blob/master/mne/realtime/epochs.py#L268-L283) so that the `rt_client` stops if there are no epochs even in the first `isi_max` seconds. I'd probably keep it for another PR. What do you think @Eric89GXL @Odingod ?

**Comment by jasmainak** [comment]
Thanks @Odingod for taking a stab at this. Looking forward to more contributions! We should increase the [bus factor](https://en.wikipedia.org/wiki/Bus_factor) of the `realtime` module.

**Comment by Odingod** [comment]
@jasmainak changing the behavior so that the isi_max is respected in all situations might make things more consistent, but is worth a second PR. I don't see any other problems for merging, so go ahead!

**Comment by jasmainak** [comment]
Merged!

**Pull request merged**
