### PR TITLE
MRG, MAINT: Use context manager for tests

### PR DESCRIPTION
**Pull request by larsoner**
@GuillaumeFavelier I think that in theory this should be equivalent to what is in `master` but cleaner because it uses a `contextmanager`.

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
> I think that in theory this should be equivalent to what is in `master`

I totally agree, I had something similar in mind. It's just that I would like to avoid to manipulate directly `pyvista.OFF_SCREEN` somehow and maybe use a new fixture like `renderer_interactive`

**Comment by GuillaumeFavelier** [comment]
Also, it's an item of #7162

**Comment by larsoner** [comment]
The tests pass now, which is nice. I wonder if it's random variation, or maybe something actually wasn't getting set properly in `master` but is now ...?

I can try turning it into `renderer_interactive`, should be doable

**Comment by GuillaumeFavelier** [comment]
> The tests pass now, which is nice. I wonder if it's random variation, or maybe something actually wasn't getting set properly in master but is now ...?

Where did it fail?

**Comment by larsoner** [comment]
Ahh I thought `master` had been failing, but maybe it was just the TimeViewer PR(s)

**Comment by larsoner** [comment]
@GuillaumeFavelier feel free to merge if you're happy

**Comment by larsoner** [comment]
... and then you could rebase / merge into #7247

**Pull request merged**
