### PR TITLE
[BUG, MRG] Actually fix circular bug this time

### PR DESCRIPTION
**Pull request by alexrockhill**
Fixes https://github.com/mne-tools/mne-python/issues/9938.

### CODE REVIEW

**Comment by alexrockhill** [comment]
Ok very sorry, I should have checked more carefully and was in too much of a hurry, the previous fix avoided the circular issue but introduced a short-circuit. This one shouldn't give the warning and should work as intended and I wrote comments to hopefully make it easier to understand in the future.

**Review by agramfort — APPROVED** [review]

**Comment by agramfort** [comment]
it's however a bit a bad pattern to merge code without tests...

@larsoner I let you merge if you thing it's ok.

@alexrockhill if we could have a test that would be awesome

**Comment by larsoner** [comment]
> @alexrockhill if we could have a test that would be awesome

Agreed, any way a unit test could/should have caught this? Maybe we need another test case, or our existing test case wasn't checked for correctness properly?

**Comment by larsoner** [comment]
I'm going to merge this so that we can get 0.24 out the door sooner, but @alexrockhill a test would be appreciated if you can make one in a separate PR!

**Comment by alexrockhill** [comment]
Will do

**Pull request merged**
