### PR TITLE
Add Missing Fields to RawEEGLAB and EpochsEEGLAB Classes Using DataContainerEEGLAB

### LINKED ISSUE #12772: Add Missing Fields to RawEEGLAB and EpochsEEGLAB Classes
### Describe the new feature or enhancement

The current implementation of the `RawEEGLAB` and `EpochsEEGLAB` classes in the MNE library does not load all available fields from EEGLAB .set files. Important fields such as 'icaact', 'icawinv', and several others are missing. This feature request aims to extend the functionality of these classes to include all possible fields present in EEGLAB .set files.

The following fields should be added to both `RawEEGLAB` and `EpochsEEGLAB` classes:
- `icaact`
- `icawinv`
- `icasphere`
- `icaweights`
- `icachansind`
- `chanlocs`
- `urchanlocs`
- `chaninfo`
- `ref`
- `event`
- `urevent`
- `eventdescription`
- `epoch`
- `epochdescription`
- `reject`
- `stats`
- `specdata`
- `specicaact`
- `splinefile`
- `icasplinefile`
- `dipfit`
- `history`
- `saved`
- `etc`
- `run`
- `roi`
- `datfile`

###  Using Composition and Create a DataContainerEEGLAB Class

I think `Composition` is a good solution. This class will be responsible for storing and managing all the fields from the EEGLAB .set file. The class will be initialized with a Bunch object containing EEG data and will extract and store all possible fields. Then `RawEEGLAB` and `EpochsEEGLAB` classes will have a `data_container` field. 

###  Multiple Inheritance

I think it is better not to use multiple inheritance because it may cause problems such as having the same name of the methods, etc.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MohammadMow**
#### Reference issue
Example: Fixes #12772.

#### What does this implement/fix?
Explain your changes. 
This pull request adds new fields to the `DataContainerEEGLAB` class to ensure all relevant fields from an EEGLAB .set file are properly stored. This enhancement aims to improve the completeness and usability of the class.

## Changes

- Added attributes to the `DataContainerEEGLAB` class to store additional fields from the EEGLAB .set file.
- Updated the `RawEEGLAB` and `EpochsEEGLAB` classes docstring to reflect the new attributes.

## New Attributes

- `setname`
- `filename`
- `filepath`
- `subject`
- `group`
- `condition`
- `session`
- `comments`
- `nbchan`
- `trials`
- `pnts`
- `srate`
- `xmin`
- `xmax`
- `times`
- `data`
- `icaact`
- `icawinv`
- `icasphere`
- `icaweights`
- `icachansind`
- `chanlocs`
- `urchanlocs`
- `chaninfo`
- `ref`
- `event`
- `urevent`
- `eventdescription`
- `epoch`
- `epochdescription`
- `reject`
- `stats`
- `specdata`
- `specicaact`
- `splinefile`
- `icasplinefile`
- `dipfit`
- `history`
- `saved`
- `etc`
- `run`
- `roi`
- `datfile`

## Proposed Solution

Using the composition design pattern, the `DataContainerEEGLAB` class encapsulates an instance of the `Bunch` object containing the EEG data. This approach ensures modularity and clean organization of code, enhancing maintainability and readability.

#### Additional information
Any additional information you think is important.

### CODE REVIEW

**Comment by larsoner** [comment]
I am not totally sold on this idea. I think the goal of the ICA EEGLAB reader is to get EEGLAB-computed ICA to conform to the same conventions / use cases as the MNE-Python computed `ICA`. This PR doesn't adhere to this, instead adding a bunch of EEGLAB-specific stuff.

I think rather than attaching this to the object, I'd rather have an `Examples` section in the docstring or an actual `examples/preprocessing/<something>.py` that shows people how to use `pymatreader` directly to access all these additional, non-MNE-style attributes.

**Comment by MohammadMow** [comment]
Thank you for your feedback on the proposed changes. I appreciate your concerns about maintaining consistency with MNE-Python conventions and your suggestion to provide an example for users to access EEGLAB-specific attributes directly using pymatreader.

However, I believe that integrating EEGLAB-specific attributes directly into the DataContainerEEGLAB class offers several significant benefits that enhance the overall usability and efficiency of the MNE-Python framework. This changes may improve  integration, by incorporating these attributes directly into the DataContainerEEGLAB class, we create a more seamless and integrated experience for users working with both MNE and EEGLAB. This approach allows users to access all relevant information within a single object, streamlining workflows and reducing the need to switch between different data structures and also users benefit from having immediate access to both MNE-style and EEGLAB-specific attributes without the need for additional code to extract these fields. This not only saves time but also minimizes the potential for errors, thereby increasing productivity and user satisfaction.

**Comment by scott-huberty** [comment]
Disclaimer: I am not a reviewer of this PR. 

But I just want to highlight, in addition to what Eric mentioned, that `Raw`/`Epochs`/`Evoked` classes aren't really supposed to have these type of extra/non-standard attributes, and they won't survive an I/O round trip. This has come up a [few](https://github.com/mne-tools/mne-python/issues/12262) [times](https://github.com/mne-tools/mne-python/issues/11825).

**Comment by mscheltienne** [comment]
I'm -1 on this, it's purely a container-class which return a subselection of the EEGLAB fields loaded by `data = pymatreader.read_mat("fname.set")` which returns **all** the EEGLAB fields. 

It adheres with non of MNE's standards and interact with non of MNE's function. 

However, if our current readers are missing some **relevant** fields from the `.set` file, it would be great to correct this and to parse those fields in their respective MNE object, as for instance `mne.preprocessing.read_ica_eeglab` is doing for ICA fields.

**Comment by drammock** [comment]
> I'm -1 on this, it's purely a container-class which return a subselection of the EEGLAB fields loaded by `data = pymatreader.read_mat("fname.set")` which returns **all** the EEGLAB fields.

I agree with @mscheltienne here. If there are *specific fields/attributes* in the EEGLAB object that don't have an equivalent in the MNE objects created by our `read_*_eeglab` reader functions, *and* you can explain why you actually need that information to achieve a particular analysis goal, then I'm interested. But as @mscheltienne says, I don't really see the value in providing an object wrapper around the output of `pymatreader.read_mat("fname.set")`.

Closing, but if you do in fact have a concrete use case where you need some of the info we currently don't include, feel free to re-open.

**Pull request closed without merging**
