### PR TITLE
[MRG] update to pymatreader 0.0.23

### PR DESCRIPTION
**Pull request by thht**
pymatreader received an update. it now works correctly with complex numbers and a few crashes were fixed.

### CODE REVIEW

**Comment by thht** [comment]
mhhh.... something wrong with eeglab stuff it seems.....

**Comment by larsoner** [comment]
For the:
```
E   UserWarning: Complex objects (like classes) are not supported. They are imported on a best effort base but your mileage will vary.
```
I would just enclose it with a `with pytest.warns(UserWarning, match='Complex objects'):`.

For the event count one, that will require more investigation and could be real. Let me know if you need help looking into it

**Comment by thht** [comment]
ok, this looks good... should i put a note in changes?

**Comment by thht** [comment]
ok, seems to be all good...

**Comment by thht** [comment]
the failed job is caused by some error in `mne\minimum_norm\tests\test_inverse.py:182: in _compare_inverses_approx` so it does not seem to have anything to do with my changes...

**Comment by larsoner** [comment]
Thanks @thht

**Pull request merged**
