### PR TITLE
MRG: Use JUnit on CircleCI

### PR DESCRIPTION
**Pull request by larsoner**
Let's see if https://github.com/sphinx-gallery/sphinx-gallery/pull/454 makes things better for us.

### CODE REVIEW

**Comment by larsoner** [comment]
JUnit says that the SPoC example took 5 minutes to run:

https://circleci.com/gh/mne-tools/mne-python/11642

Ready for review/merge from my end.

**Comment by agramfort** [comment]
it's a regression as it's much faster on 0.17

I think it's related to the refactoring of the whitening code.

>

**Comment by larsoner** [comment]
Okay let's fix that separately

**Comment by agramfort** [comment]
ok to merge when rebased and CIs are green.

**Pull request merged**
