### PR TITLE
Disable mandatorily downloading the testing data while setting up the egi_mff_pns_fname path.

### PR DESCRIPTION
**Pull request by Aniket-Pradhan**
#### Additional information
Any additional information you think is important.

Discussed this over Gitter with @larsoner ;D

### CODE REVIEW

**Comment by larsoner** [comment]
@Aniket-Pradhan can you add a line to the top of the BUG section in `doc/changes/latest.inc`, and if it's your first contribution do the RST bolding trick we did with `Eduard Ort`, and then also add your name + URL to `doc/changes/names.inc`? These steps ensure proper credit for your contribution!

If you are busy with Fedora packaging, if you give me your name + URL I can also push these changes -- thanks!

**Comment by Aniket-Pradhan** [comment]
Added the info, and squashed the two commits into one (so that it doesn't mess with the git history)

**Comment by larsoner** [comment]
> Added the info, and squashed the two commits into one (so that it doesn't mess with the git history)

Thanks! FYI we use the "squash and merge" option anyway so no need to squash. I also just pushed two tiny commits, one to fix the `latest.inc` formatting and another to fix a PEP8 / line-length issue. Will merge once CIs come back happy!

**Comment by Aniket-Pradhan** [comment]
That's great! I am used to normal merge, hence the squash :P

**Comment by larsoner** [comment]
Thanks @Aniket-Pradhan ! Will backport and hopefully release 0.21.1 in the next couple of days. Does that schedule work for you?

**Comment by Aniket-Pradhan** [comment]
> Thanks @Aniket-Pradhan ! Will backport and hopefully release 0.21.1 in the next couple of days. Does that schedule work for you?

Works great for me. :smile:

**Pull request merged**
