### PR TITLE
MRG: move peak_finder

### PR DESCRIPTION
**Pull request by larsoner**
See #6097

### CODE REVIEW

**Comment by larsoner** [comment]
The diff is terrible, but it's really a `git mv` followed by this in `mne.preprocessing.peak_finder.py`:
```
import sys

from ..utils import copy_doc, deprecated
from ._peak_finder import peak_finder as _peak_finder


class peak_finder_wrapper(object):

    @deprecated('mne.preprocessing.peak_finder.peak_finder is deprecated and '
                'will be removed in 0.19, use mne.preprocessing.peak_finder'
                'directly instead. (For one cycle this will be a wrapper class'
                ' with a peak_finder method, and in 0.19 it will turn into a '
                'standard function.')
    @copy_doc(_peak_finder)
    def peak_finder(self, x0, thresh=None, extrema=1, verbose=None):
        return _peak_finder(x0, thresh, extrema, verbose)

    @copy_doc(_peak_finder)
    def __call__(self, x0, thresh=None, extrema=1, verbose=None):
        return _peak_finder(x0, thresh, extrema, verbose)


sys.modules[__name__] = peak_finder_wrapper()
```

Not sure it's worth all this vs minor backward compat break to tell people to do `from mne.preprocessing import peak_finder` instead of `from mne.preprocessing.peak_finder import peak_finder` given how hopefully uncommon this is.

Also maybe we don't want to have `peak_finder` be public anyway, and just want to deprecate and use `mne.preprocessing._peak_finder._peak_finder` instead :)

**Comment by agramfort** [comment]
```
Not sure it's worth all this vs minor backward compat break to tell people to do from mne.preprocessing import peak_finder instead of from mne.preprocessing.peak_finder import peak_finder given how hopefully uncommon this is.
```

I would say it's fine given how uncommon this is.

**Comment by mmagnuski** [comment]
I wouldn't deprecate, but throwing error and forcing people to use `from preprocessing import peak_finder` is good to me.

**Comment by larsoner** [comment]
done

**Comment by mmagnuski** [comment]
Great, thanks @larsoner!

**Pull request merged**
