### PR TITLE
fix setting xlabel and ylabel in example

### PR DESCRIPTION
**Pull request by jjnurminen**
This is a small fix for an example by @dengemann, where labels of a subplot weren't being set correctly.

### CODE REVIEW

**Review by sappelhoff — APPROVED** [review]
good catch! thanks :-)

**Comment by dengemann** [comment]
I am surprised about how long these obviously wrong two lines could exist without correction :) very good catch. Thank you!

**Review by dengemann — APPROVED** [review]

**Review by agramfort — APPROVED** [review]

**Comment by jjnurminen** [comment]
The original code is interesting, because it replaces the instance methods with strings, which I guess is completely legal.
On the other hand, it seems that one can put any arbitrary stuff in the callbacks (like `non_existent_function()` or `raise NoSuchException`) and never see any error messages. :)

**Comment by larsoner** [comment]
Thanks @jjnurminen

**Pull request merged**
