### PR TITLE
Updated copyright to 2016

### PR DESCRIPTION
**Pull request by Famguy**

### CODE REVIEW

**Comment by jasmainak** [comment]
are you looking to do GSoC?

**Comment by Famguy** [comment]
Yes @jasmainak I was actually looking for an opportunity to contribute to. If there could be anything that I could help in, please guide me to it. Thanks!

**Comment by jasmainak** [comment]
This is an easy one: https://github.com/mne-tools/mne-python/issues/1853. Maybe this one too: https://github.com/mne-tools/mne-python/issues/2330 but it's slightly more challenging.

You'll probably want to use the command line git for these.

**Comment by agramfort** [comment]
thx @Famguy

**Comment by Famguy** [comment]
Thanks @jasmainak I'll have a look at them and come up with my solutions.

**Pull request merged**
