### PR TITLE
Bugfix issue 2349

### LINKED ISSUE #2349: event.py define_target_events error
I brought this up on mne_analysis_request mailing list, then looked at the code, and wasn't sure the best way to point out the issue, so here it is:

Line 141:         lag[lag != fill_na] *= tsample

If fill_na is None, then lag != fill_na returns True, so this only multiplies lag[1] by tsample, leaving all other entries in lag as number of samples rather than number of milliseconds. Not sure the most elegant way to fix it - maybe just if fill_na is None, do lag *= tsample, else do the current line 141. But it also seems risky to index this way; what if the true lag is 47 and my fill_na is 47 as well?

Thanks,

Natalie

### PR DESCRIPTION
**Pull request by natalieklein**
closes #2349  

I wanted all lags to multiply by tsample and to guard against the possibility that a lag would equal fill_na, which would cause unexpected behavior. 

What I did: If fill_na is not None, I append None to lag at the "na event" indices. Then np.abs turns these values to nan, so the returned lag list contains millisecond lag values for the found events and nan for the "na events".

I also attempted to add my test case to mne/test/test_events.py in the test_define_events function, but if this was the incorrect way to incorporate the test, please let me know!

Thanks

### CODE REVIEW

**Comment by agramfort** [comment]
Thanks heaps

I will let @dengemann double check the logic

**Comment by mainakjas** [comment]
@natalieklein I updated your comment so that the issue gets closed automatically when this PR is merged.

**Comment by mainakjas** [comment]
@natalieklein you have travis failing because you didn't comply to pep8 conventions. Most editors (sublime text, spyder, atom etc.) have flake8 / pep8 checkers and you should enable them. Or else, just run it from the command line before you push.

**Comment by natalieklein** [comment]
@mainakjas Apologies! I did the PR before travis finished last time... I think I fixed it with the current push but the test is still in progress. Thanks for your help.

**Comment by agramfort** [comment]
LGTM

@dengemann ?

**Comment by dengemann** [comment]
Looks good to me, thanks @natalieklein ! Merging.

**Pull request merged**
