### PR TITLE
Removed EpochsVectorizer from docs

### LINKED ISSUE #3673: EpochsVectorizer is in docs but not code
@kingjr `EpochsVectorizer` shows up in `manual/decoding.rst` and `python_reference.rst`. Do you have time to update the docs with whatever procedure is meant to be used now?

### PR DESCRIPTION
**Pull request by kaichogami**
Closes #3673

### CODE REVIEW

**Comment by agramfort** [comment]
@kingjr merge if you're happy

**Comment by kingjr** [comment]
@Eric89GXL Appveyor isn't happy, shall we discard it?

**Comment by Eric89GXL** [comment]
Sorry I missed the ping. Yeah it should be okay

**Comment by kingjr** [comment]
Thanks @kaichogami !

**Pull request merged**
