### PR TITLE
Fix make_dig_montage documentation for correct coord_frame values

### PR DESCRIPTION
**Pull request by dhasegan**
Thanks for contributing a pull request! Please make sure you have read the
[contribution guidelines](https://mne.tools/dev/install/contributing.html)
before submitting.

Please be aware that we are a loose team of volunteers so patience is
necessary. Assistance handling other issues is very welcome. We value
all user contributions, no matter how minor they are. If we are slow to
review, either the pull request needs some benchmarking, tinkering,
convincing, etc. or more likely the reviewers are simply busy. In either
case, we ask for your understanding during the review process.

Again, thanks for contributing!

#### Reference issue
None

#### What does this implement/fix?
Just changing documentation to reflect correct values for coord_frame

#### Additional information
non important

### CODE REVIEW

**Comment by dhasegan** [comment]
@larsoner I hope the target branch is correct.

**Comment by larsoner** [comment]
> I hope the target branch is correct.

We always merge into `main` first, then backport as needed. I just changed the target branch (by clicking "edit" at the top) and now the commits are a bit messed up. Let me know if you need help fixing this. If "Allow edits by maintainers" is checked, I can force-push commits to fix it

**Comment by dhasegan** [comment]
Yea, can you force push please?

**Comment by larsoner** [comment]
Done and marked for merge when green, thanks in advance @dhasegan !

**Pull request merged**
