### PR TITLE
MRG: Fix DICS rank handling

### PR DESCRIPTION
**Pull request by wmvanvliet**
DICS handing of the `rank` parameter was completely broken. It was changed from a single number to something more complicated, but the code was not updated appropriately.

Still needs unit test to cover this case, but here at least is a fix for the code.

### CODE REVIEW

**Comment by larsoner** [comment]
I wonder if fixing this would allow us to remove the `reduce_rank=True` from here:

https://mne.tools/dev/auto_examples/inverse/plot_dics_source_power.html?highlight=dics#compute-source-power-using-dics-beamformer

**Comment by larsoner** [comment]
Spoiler alert: it doesn't. I guess this makes sense since the `reduce_rank` has to do with the 3-orientations rank as opposed to the `n_ch` rank / whitening.

**Comment by wmvanvliet** [comment]
The computations have not changed. It's just that setting the `rank` parameter to anything other than `None` was broken.

**Review by larsoner — APPROVED** [review]
I just pushed a test and `latest.inc` update, LGTM +1 for merge

**Review by agramfort — APPROVED** [review]

**Comment by wmvanvliet** [comment]
Thanks @larsoner! I really appreciate you picking this up.

**Pull request merged**
