### PR TITLE
MRG, DOC: update tutorial for Info object

### PR DESCRIPTION
**Pull request by drammock**
also exposes `mne.io.pick.channel_type` and `mne.io.pick.channel_indices_by_type` in the main `mne` namespace, adds them to the `python_reference`, and makes minor fixes to their docstrings.

Note: I'm not married to the that namespace location for `channel_type` and `channel_indices_by_type`, I just chose it because that's where most of the other functions in `mne.io.pick` get exposed.

### CODE REVIEW

**Comment by drammock** [comment]
rendering: https://13893-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/intro/plot_info.html

**Comment by agramfort** [comment]
```
..warning::
Both pick_channels() a
```
does not render well

**Comment by agramfort** [comment]
besides LGTM

**Comment by larsoner** [comment]
Thanks @drammock

**Pull request merged**
