### PR TITLE
Add reader for Localite dig files

### PR DESCRIPTION
**Pull request by cbrnr**
We now have a [Localite digitizer system](https://www.localite.de/en/products/eeg-pinpoint/), so MNE-Python needs a reader 😄.

### CODE REVIEW

**Comment by cbrnr** [comment]
I _think_ the failing test is unrelated.

**Review by agramfort — COMMENTED** [review]
I suspect some see also need to be updated as well the API page

**Comment by cbrnr** [comment]
@agramfort the failing test is [mne/minimum_norm/tests/test_inverse.py::test_make_inverse_operator_diag](https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=14820&view=logs&j=fa98c7b3-575e-55b6-6946-22dea6f6daf8&t=c0866e65-eed5-5461-eadc-f0ff150eefd8&l=3141), I can't see how this should be related (especially since it only fails for Python 3.9 conda. What else do I need to update?

**Comment by drammock** [comment]
I think @agramfort was asking you to update some "see also" sections; it looks like you already updated the API page.

**Comment by cbrnr** [comment]
I'm sorry, I didn't get it for some reason. I've added/extended all relevant sections.

**Review by drammock — APPROVED** [review]
LGTM.  +1 for merge when CIs green.

**Comment by cbrnr** [comment]
All green, @agramfort or @drammock feel free to merge.

**Review by sappelhoff — APPROVED** [review]
looks like a nice system, I wish they had a short video on how it works on their website :-)

**Comment by sappelhoff** [comment]
thanks @cbrnr

**Pull request merged**
