### PR TITLE
DOC: Document Linux desktop workaround

### LINKED ISSUE #12899: MNE-Python application icon broken in Ubuntu 24.04
... I think due to the use of Gnome3 newer Ubuntu seems to by default now *require* a `.desktop` file to use something other than this in the dock:

image

I tried a bunch of Qt stuff and none of it worked. At some point I stumbled upon a post that mentioned `.desktop` with `StartupWMClass` could fix it and indeed this seems to work:

<details>
<summary>~/.local/share/applications/mne-python.desktop</summary>

```
[Desktop Entry]
Type=Application
Version=1.5
Name=MNE-Python
StartupWMClass=MNE-Python
Icon=/home/larsoner/python/mne-python/mne/icons/mne_default_icon.png
SingleMainWindow=true
NoDisplay=true
```

</details>

image

@hoechenberger our installers currently add files like `mne-python-180_prompt-mne.desktop` but I'm not sure if it's possible to have them create a separate linux-only file, do you?

Either way, we could consider adding a note about this to our install docs somewhere as well.

### PR DESCRIPTION
**Pull request by larsoner**
Helps with  #12899

### CODE REVIEW

**Comment by larsoner** [comment]
https://output.circle-artifacts.com/output/job/922b0a68-23aa-4440-a16f-d5281e271f9b/artifacts/0/html/install/advanced.html#fixing-dock-icons-on-linux

**Review by drammock — APPROVED** [review]

**Comment by hoechenberger** [comment]
shouldn't we simply deploy this file ourselves on MNE startup if it doesn't exist?

**Comment by larsoner** [comment]
Seems too invasive to me to do it automagically. It's easy enough for people to edit and save this file if they want

**Comment by hoechenberger** [comment]
But they also need to manually download an image ... I don't know. I mean I'm okay with keeping these instructions (and thanks for writing them down!) but I'd be surprised if more than, say, 5 people will ever follow them 🤨

**Comment by drammock** [comment]
> Seems too invasive to me to do it automagically. It's easy enough for people to edit and save this file if they want

FWIW I think of things like icons and desktop files as normal/expected part of installing new GUI-based tools, so to me it doesn't seem invasive. I was assuming there was some technical limitation (permissions etc) but looking again I see that everything goes in `~/`, so I'd be fine with the installer putting the icon in `~/.mne/icons/` and putting the `.desktop` file in `~/.local/share/applications` (and as long as those files get cleaned up during uninstall).

**Comment by larsoner** [comment]
> FWIW I think of things like icons and desktop files as normal/expected part of installing new GUI-based tools... I'd be fine with the installer putting the icon in ~/.mne/icons/ and putting the .desktop file in ~/.local/share/applications (and as long as those files get cleaned up during uninstall).

Totally agree -- the installer already installs stuff here and with https://github.com/conda-forge/mne-feedstock/pull/139 shortly our installers will do this. I think the discussion/suggestion @hoechenberger made is about *MNE-Python itself* (rather than the installer) creating files under `~/.local`. This to me is too invasive as there is no reasonable user expectation that `import mne` will add such GUI-related files.

(And as a side note, sadly there isn't an uninstaller to complement our Linux installer script but we do at least have instructions for how to uninstall manually, including the `.desktop` files that the installer produces.)

**Comment by hoechenberger** [comment]
We're creating a config file without asking too, I don't see how this is any different

For me the real question is: How do we want to present ourselves by default? Ugly with a generic icon, or pretty with a useful, identifiable icon. So it's also a question of aesthetics and accessibility

Creating a small text file to achieve better aesthetics and a11y is a small price to pay IMHO

**Comment by drammock** [comment]
> I think the discussion/suggestion @hoechenberger made is about _MNE-Python itself_ (rather than the installer) creating files under `~/.local`. This to me is too invasive as there is no reasonable user expectation that `import mne` will add such GUI-related files.

ah oops, I missed that distinction.

> We're creating a config file without asking too, I don't see how this is any different [...] Creating a small text file to achieve better aesthetics and a11y is a small price to pay IMHO

it would also mean shipping a binary (logo) file in our wheel I think (not just a text file). But that aside: to me it's annoying but acceptible if a python package creates a dotted config dir in `~` (though I prefer it when packages/programs create those in `~/.config/` instead). But it *does* seem a bit invasive for `import mne` to have side effects in other places in the filesystem.

I feel like it used to be the case that matplotlib windows would get the MPL logo in the doc (just tried it and on my machine I see a blurry/pixelated version of the python snakes --- but I also just updated from 22.04 to 24.04 so maybe I'm seeing the same behavior change as @larsoner?)  Anyway I bring that up because I'm on the fence, and if I knew MPL were installing `.desktop` files into `~/.local/share/applications` then I wouldn't feel so bad doing it ourselves.

**Comment by larsoner** [comment]
Correct MPL also used to get a matplotlib icon and no longer does for me as well. I'm happy with escalating to their level since they think a lot harder about UI design and we can do whatever they decide

**Pull request merged**
