### PR TITLE
shrink versionadded notes in docstrings

### LINKED ISSUE #11816: How long do we keep "New in version ..." around?
### Proposed documentation enhancement

I don't think we ever remove the "New in version ..." notices, but things like "New in version 0.9" seem a bit out of place nowadays. I suggest that we remove these notices once they are older than a certain amount of time (or certain amount of releases).

1. Are you OK with the general idea of removing old notices?
2. If so, which threshold would you suggest? We could remove them after 3 releases, similar to our deprecation warnings.

Note that since we make our documentation for previous versions available, it would still be possible to check when a specific method/attribute has been added (although this requires a bit more work then).

### PR DESCRIPTION
**Pull request by drammock**
closes #11816 

First attempt worked pretty well, I thought:

Screenshot 2023-07-21 at 10-20-24 mne Epochs — MNE 1 4 0 dev127 g9145025c4 d20230423 documentation

Until I did a quick scan of `git grep versionadded` results, and checked some other API pages, and found this in `CSP.plot_filters`:

Screenshot 2023-07-21 at 11-31-10 mne decoding CSP — MNE 1 4 0 dev127 g9145025c4 d20230423 documentation

### CODE REVIEW

**Comment by larsoner** [comment]
For now can we alter just `versionadded` and leave `versionchanged` as it is (or still at the bottom but smaller)? Versionchanged is rarely going to fit up there and often is more relevant/important than `versionchanged` anyway

**Comment by drammock** [comment]
Even restricting to just `versionadded` there are cases that aren't going to work I'm afraid:

Screenshot 2023-07-21 at 14-04-19 mne decoding CSP — MNE 1 4 0 dev127 g9145025c4 d20230423 documentation

I even tried hacking the sphinx default text to make it shorter but it still overlaps:

Screenshot 2023-07-21 at 15-35-48 mne decoding CSP — MNE 1 4 0 dev127 g9145025c4 d20230423 documentation

I have one more idea to try before I consider giving up. If y'all have ideas, send them my way.

**Comment by drammock** [comment]
OK I think this is as good as it's going to get. I can't put it inline with the param name, so inlining it at the end of the param description is the best we're going to get (at least until the CSS `:has()` gets wider support)

**Comment by drammock** [comment]
This looks good but there is still one more fix to be done here: the versionchanged note on extrapolate needs to be moved out of the docdict. Will do on Monday

**Review by larsoner — APPROVED** [review]
Nice! Feel free to self-merge once you fix the remaining issue.

For anyone else curious:

- [A versionadded](https://output.circle-artifacts.com/output/job/29fafb64-24b4-44de-a3d9-1d8849b21051/artifacts/0/html/generated/mne.preprocessing.maxwell_filter.html)

   Screenshot 2023-07-22 at 8 26 07 AM

- [Another versionadded](https://output.circle-artifacts.com/output/job/29fafb64-24b4-44de-a3d9-1d8849b21051/artifacts/0/html/generated/mne.preprocessing.maxwell_filter.html)

   Screenshot 2023-07-22 at 8 26 17 AM

- [A versionchanged](https://output.circle-artifacts.com/output/job/29fafb64-24b4-44de-a3d9-1d8849b21051/artifacts/0/html/generated/mne.events_from_annotations.html)

   Screenshot 2023-07-22 at 8 28 07 AM

- [An inline deprecation](https://output.circle-artifacts.com/output/job/29fafb64-24b4-44de-a3d9-1d8849b21051/artifacts/0/html/generated/mne.io.read_raw_eyelink.html)

   Screenshot 2023-07-22 at 8 29 38 AM

**Comment by cbrnr** [comment]
Thanks @drammock, this is a huge improvement!

**Pull request merged**
