### PR TITLE
MRG+2: Better zorder

### LINKED ISSUE #2919: seaborn
If one is up for it, it would be great to get the viz compatible with [seaborn](https://github.com/mwaskom/seaborn) as it is become more and more standard for scientific plotting.

At the moment, we still get some weird viz every now and then: e.g. the evoked plot lines are behind the grid.

plot_seaborn

What do you think?

### PR DESCRIPTION
**Pull request by Eric89GXL**
Closes #2919.

Ready for review/merge from my end. @jaeilepp do you have time to look?

Running `plot_from_raw_to_epochs_to_evoked` with `import seaborn` added to the top, before/after:

screenshot from 2016-02-26 10-03-14

screenshot from 2016-02-26 10-03-32

 screenshot from 2016-02-26 10-03-11

screenshot from 2016-02-26 10-03-52

### CODE REVIEW

**Comment by kingjr** [comment]
Thanks @Eric89GXL !

**Comment by kingjr** [comment]
LGTM

**Comment by agramfort** [comment]
LGTM

+1 for merge when CIs are happy

**Comment by Eric89GXL** [comment]
Thanks for the quick reviews, will merge once the CIs are happy

**Pull request merged**
