### PR TITLE
[DOC, MRG] Fix misleading colorbar in cluster permutation example

### PR DESCRIPTION
**Pull request by alexrockhill**
In the example I changed, the T-statistic for the significant clusters was plotted with no `vmin` or `vmax` arguments to `imshow` with a diverging (`RdBu_r`) colormap. The T-statistic is strictly positive so I think this is misleading as it colored significant but smaller T values blue and significant and larger T values red. The intent was, as far as I can tell, to plot decreases power in blue and increases in red, so I made a change to multiply the T statistic by the sign of the difference in means of the two conditions.

cc @agramfort since you're listed as the author and hopefully I didn't mess things up :)

### CODE REVIEW

**Comment by larsoner** [comment]
Thanks @alexrockhill !

**Comment by agramfort** [comment]
T stats should be signed. I don't get why you say it's always positive? F-stats are always positive not T

**Comment by larsoner** [comment]
Agreed, but in this particular case the significant ones are positive so should all be red instead of some red some blue

**Comment by alexrockhill** [comment]
Maybe there is a deeper fix in the code then because I ran this on ~1000 channels for a motor task with both beta ERD and beta rebound and all the T values were strictly positive. I thought they would be signed too, which is why I let the whole thing run for 24 hours + and had to do it again...

**Comment by alexrockhill** [comment]
There's an easy way to test:

```
import numpy as np
import matplotlib.pyplot as plt

import mne
from mne.time_frequency import tfr_morlet
from mne.stats import permutation_cluster_test
from mne.datasets import sample

print(__doc__)

# %%
# Set parameters
data_path = sample.data_path()
meg_path = data_path / 'MEG' / 'sample'
raw_fname = meg_path / 'sample_audvis_raw.fif'
event_fname = meg_path / 'sample_audvis_raw-eve.fif'
tmin, tmax = -0.2, 0.5

# Setup for reading the raw data
raw = mne.io.read_raw_fif(raw_fname)
events = mne.read_events(event_fname)

include = []
raw.info['bads'] += ['MEG 2443', 'EEG 053']  # bads + 2 more

# picks MEG gradiometers
picks = mne.pick_types(raw.info, meg='grad', eeg=False, eog=True,
                       stim=False, include=include, exclude='bads')

ch_name = 'MEG 1332'  # restrict example to one channel

# Load condition 1
reject = dict(grad=4000e-13, eog=150e-6)
event_id = 1
epochs_condition_1 = mne.Epochs(raw, events, event_id, tmin, tmax,
                                picks=picks, baseline=(None, 0),
                                reject=reject, preload=True)
epochs_condition_1.pick_channels([ch_name])

# Load condition 2
event_id = 2
epochs_condition_2 = mne.Epochs(raw, events, event_id, tmin, tmax,
                                picks=picks, baseline=(None, 0),
                                reject=reject, preload=True)
epochs_condition_2.pick_channels([ch_name])

decim = 2
freqs = np.arange(7, 30, 3)  # define frequencies of interest
n_cycles = 1.5

tfr_epochs_1 = tfr_morlet(epochs_condition_1, freqs,
                          n_cycles=n_cycles, decim=decim,
                          return_itc=False, average=False)

tfr_epochs_2 = tfr_morlet(epochs_condition_2, freqs,
                          n_cycles=n_cycles, decim=decim,
                          return_itc=False, average=False)

tfr_epochs_1.apply_baseline(mode='ratio', baseline=(None, 0))
tfr_epochs_2.apply_baseline(mode='ratio', baseline=(None, 0))

epochs_power_1 = tfr_epochs_1.data[:, 0, :, :]  # only 1 channel as 3D matrix
epochs_power_2 = tfr_epochs_2.data[:, 0, :, :]  # only 1 channel as 3D matrix

threshold = 6.0
T_obs, clusters, cluster_p_values, H0 = \
    permutation_cluster_test([epochs_power_2, epochs_power_1], out_type='mask',
                             n_permutations=100, threshold=threshold, tail=0)

times = 1e3 * epochs_condition_1.times  # change unit to ms

T_obs_plot = np.nan * np.ones_like(T_obs)
for c, p_val in zip(clusters, cluster_p_values):
    if p_val <= 0.05:
        T_obs_plot[c] = T_obs[c]

plt.imshow(T_obs,
           extent=[times[0], times[-1], freqs[0], freqs[-1]],
           aspect='auto', origin='lower', cmap='gray')
plt.imshow(T_obs_plot,
           extent=[times[0], times[-1], freqs[0], freqs[-1]],
           aspect='auto', origin='lower', cmap='RdBu_r', vmin=-15, vmax=15)

plt.xlabel('Time (ms)')
plt.ylabel('Frequency (Hz)')
plt.title('Induced power (%s)' % ch_name)
```

Gives:

Screen Shot 2022-02-26 at 8 12 23 AM

So looks to me like the T values are not signed since I switched the conditions in the test.

**Pull request merged**
