### PR TITLE
Cichy dataset.

### PR DESCRIPTION
**Pull request by jaeilepp**
To enable https://github.com/mne-tools/mne-python/pull/3552.

### CODE REVIEW

**Comment by agramfort** [comment]
why did you remove hcp stuff?

also I would call dataset `object_visual` rather than cichy but please put the refs to cichy's paper in docstrings

maybe someone can come up with a better name

ping @kingjr 

@kingjr that should allow you to resurrect your RSA example

**Comment by jaeilepp** [comment]
WTF. I blame git.

**Comment by jaeilepp** [comment]
I'll make a clean PR

**Comment by jaeilepp** [comment]
>maybe someone can come up with a better name

How about just 'recognition' dataset. Or 'vis_rec'.

**Comment by kingjr** [comment]
I would say visual_96_categories or something like this. The more explicit the better. Radek might release some additional data in the future, so I wouldn't name it by his name.

Else LGTM

**Comment by Eric89GXL** [comment]
+1 for visual_96_categories

**Comment by agramfort** [comment]
+1

**Pull request closed without merging**
