### PR TITLE
ENH _find_kit_layout():  add fallback on automatic layout

### LINKED ISSUE #6891: missing template for topoplot
Hello, 
Trying to use evoked.plot_topomap on MEG data with .sqd format and receive this message error:

"The layout for the KIT system with ID 35 is missing. Please contact the developers about adding it."

Thanks for your help!
Claire

### PR DESCRIPTION
**Pull request by christianbrodbeck**
#### Reference issue
Example: Fixes #6891.

#### What does this implement/fix?
When no corresponding KIT layout is built in generate one automatically (previously raised an error).

#### Additional information
Leaves open the possibility to add manually built layout for any system later.

### CODE REVIEW

**Comment by agramfort** [comment]
can you see what azure complains and add a what's new entry?

**Comment by larsoner** [comment]
I pushed a fix for the Azure failure (one channel pos was all `nan` so I just set it to zero like the last few channels were anyway), but @christianbrodbeck feel free to force push over this if it's not correct, and then add a note to `latest.inc`

**Comment by christianbrodbeck** [comment]
It's strange that it seems to be Windows specific.

**Comment by agramfort** [comment]
errors are unrelated. Merging. Thx @christianbrodbeck

**Pull request merged**
