### PR TITLE
MRG: Try envs

### LINKED ISSUE #4419: Improve documentation installation info
A few things I notice:

* Do we *really* need to recommend python 2.7 to new users? IMO it makes MNE seem behind-the-times. Mayavi does technically work on python 3 now, though it's a pain to install IME.
* The installation instructions are very text heavy. We should streamline.
* Do we really need to explicitly call out `matlab` in the instructions?
* I think we should have a separate page for installing the development version. If we have newbies coming to this page we don't want them seeing `python setup.py develop` IMO.
* We should figure out who this set of instructions *doesn't* work for so that we can improve them.

### PR DESCRIPTION
**Pull request by larsoner**
The CIs seem bored today so let's see if the 3.6 env works yet.

Closes #4419.

### CODE REVIEW

**Comment by larsoner** [comment]
So the Python3.6 + `clinicalgraphics` VTK-7.1 environment seems to work on Linux *and* Windows (!), but [breaks OSX on Travis](https://travis-ci.org/mne-tools/mne-python/jobs/282911951). I can't even get it to `import vtk` on my OSX system, but I must be doing something wrong there.

@agramfort if you have time, can you try this latest environment and see if:

1. `conda env remove -n mne` (if necessary)
2. `conda env create -f environment.yml`
3. `source activate mne`
4. `pip uninstall -y mne`
5. `python setup.py develop` for latest `master` version of MNE
6. `pytest mne/gui`

Passes on your OSX system? If step (6) fails, can you try `pytest mne/viz` to see if that at least passes?

**Comment by agramfort** [comment]
working !!!

good to go then?

**Comment by larsoner** [comment]
I want to update docs here, too. Otherwise YES!

**Comment by larsoner** [comment]
`info['bads']` is fine

**Comment by larsoner** [comment]
Crap, wrong GitHub tab

**Comment by larsoner** [comment]
Updated doc

https://6073-1301584-gh.circle-artifacts.com/0/tmp/circle-artifacts.2fIiuDA/html/install_mne_python.html

**Comment by larsoner** [comment]
Setting back to WIP because I want to tweak the Travis runs a bit

**Comment by larsoner** [comment]
Okay ready for review/merge from my end (just the second OSX CI run finishing up currently, so should come back happy)

**Comment by agramfort** [comment]
can you add a line that to download the env file from terminal one can do:

```
curl -O https://raw.githubusercontent.com/mne-tools/mne-python/master/environment.yml
```

so to install once anaconda is setup it's just

```
curl -O https://raw.githubusercontent.com/mne-tools/mne-python/master/environment.yml
conda env create -f environment.yml
```

**Comment by larsoner** [comment]
@agramfort done

**Comment by larsoner** [comment]
This one is still good to go

**Comment by agramfort** [comment]
thx heaps @larsoner

**Pull request merged**
