### PR TITLE
MRG: EDF warning

### PR DESCRIPTION
**Pull request by Eric89GXL**
@kingjr can you try this?

@teonlamont can you have a look to see if it makes sense to you? The conditional is kind of awful, but I think it's correct.

AFAICT we currently don't have any test files that actually test that this warning gets thrown. @kingjr do you have some small sample EDF/BDF file that we could add to the testing dataset to hit this warning? We've had problems with these lines not being tested before.

### CODE REVIEW

**Comment by kingjr** [comment]
works for me, thanks

**Comment by Eric89GXL** [comment]
Great, thanks. @kingjr do you happen to have some small file that has this need for resampling? It would be good to add one to the test suite so we can properly test this and other behaviors.

**Comment by kingjr** [comment]
This is the smallest I have 18 mo: http://we.tl/q2mphLtzop

**Comment by Eric89GXL** [comment]
That's probably small enough to include in our testing data to catch this sort of thing. Okay if I include it in the testing repo publically?

**Comment by Eric89GXL** [comment]
That took me to some random text file...?

**Comment by kingjr** [comment]
link updated

**Comment by kingjr** [comment]
sure go ahead. I'm confident that I had anonymized it, but in case, if you know how to read the header, a second check wouldn't be worthless.

**Comment by Eric89GXL** [comment]
Okay test added. Ready for review/merge from my end.

**Comment by kingjr** [comment]
LGTM

**Comment by agramfort** [comment]
+1 for merge when CIs are happy

**Comment by agramfort** [comment]
you have conflicts now :(

+1 for merge

**Comment by Eric89GXL** [comment]
Rebased, I'll go ahead and merge once the CIs come back happy. @teonlamont no rush to review but feel free to have a look when you get a chance.

**Comment by teonlamont** [comment]
I have a whole suite of delightfully flexible edf files that I have been keeping locally since there are so many edge cases. Is there a common place to store them?

**Comment by teonlamont** [comment]
the warning conditions look fine, were we missing some warnings before or is this just to make it explicit?

**Comment by Eric89GXL** [comment]
This moved where the warning happened. It used to happen on every read. This wasn't a problem when we were doing `warnings.warn`, but recently we changed to a dual approach of `warnings.warn` and `logger.warn`, so now users were getting tons of warnings. This made it so the warning is only emitted once per file read (during `read_raw_edf` instantiation of the class). 

It might be good to double-check all the corner cases work properly since we've been tweaking lately. But @kingjr did get me a test file for this particular case, which helped.

**Comment by teonlamont** [comment]
ah, thanks for the recap. i just followed all the conversations, i had a lot of unread notification ;)

**Comment by Eric89GXL** [comment]
No problem, the issue was more complicated than it seemed *prima facie*

**Pull request merged**
