### PR TITLE
[MRG] FIX fwd info

### LINKED ISSUE #2225: BUG make_fwd_solution is broken
I was trying to make a fwd solution and I got an error.

```python
/Applications/packages/mne-python/mne/io/pick.pyc in pick_types(info, meg, eeg, stim, eog, ecg, emg, ref_meg, misc, resp, chpi, exci, ias, syst, seeg, include, exclude, selection)
    191     from .meas_info import Info
    192     if not isinstance(info, Info):
--> 193         raise TypeError('info must be an instance of Info, not %s' % info)
    194     nchan = info['nchan']
    195     pick = np.zeros(nchan, dtype=np.bool)

TypeError: info must be an instance of Info, not {'dev_head_t':...```

it's because the internal dict that is being generated is not an instance of Info, just a regular dict. this is a problem when you do pick_types on it.

cc: @agramfort, @Eric89GXL

### PR DESCRIPTION
**Pull request by teonlamont**
closes #2225

### CODE REVIEW

**Comment by teonlamont** [comment]
the first build timed out. it completed on my branch's build: https://travis-ci.org/teonlamont/mne-python/builds/67713119.

**Comment by Eric89GXL** [comment]
@teonlamont actually you should just use `Info(**kwargs)` instead of `create_info`. The forward solution info struct contains fewer fields than what `create_info` will populate. Also, I already fixed this in my Epochs PR I think...

FYI you can also restart Travis builds on the Travis site. Do you not see the "X" for running builds and restart circle for finished ones? You might not, depending on repo permissions, but I think anyone with push access should have it.

**Comment by agramfort** [comment]
+1 for Info(**kwargs)

**Comment by teonlamont** [comment]
fixed in #2211

**Comment by teonlamont** [comment]
btw, I don't see those options to reset with my Travis builds.

**Pull request closed without merging**
