### PR TITLE
Create codeql-analysis.yml

### PR DESCRIPTION
**Pull request by larsoner**
[LGTM is being phased out](https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/) in favor of [this](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/setting-up-code-scanning-for-a-repository#setting-up-code-scanning-manually). I'll make a subsequent commit to remove LGTM-related stuff, and delete this branch on merge. (Sorry for the `upstream` branch push, it happened automatically when I followed their tutorial.)

### CODE REVIEW

**Comment by larsoner** [comment]
Wow, its analysis took 26 minutes. Maybe we have too much code :)

**Comment by agramfort** [comment]
did you learn anything from this?

**Comment by larsoner** [comment]
That we don't have any security issues that they could identify. Seems worth keeping around as long as it doesn't slow down our CIs

**Review by drammock — APPROVED** [review]
LGTM! 😝

**Pull request merged**
