### PR TITLE
MRG: Add minimum-phase filtering

### LINKED ISSUE #3598: ENH: Add minimum-phase filtering
We should have minimum phase filtering. It could especially be useful in realtime applications, cc @aj-ptw @m-brantheim. We need the upstream SciPy PR https://github.com/scipy/scipy/pull/6497 to land first. But it should only be 1-2 months away.

### PR DESCRIPTION
**Pull request by Eric89GXL**
Closes #3598.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
Updated example:

https://3158-1301584-gh.circle-artifacts.com/0/home/ubuntu/mne-python/doc/_build/html/auto_tutorials/plot_background_filtering.html#applying-fir-filters

Ready for review/merge from my end.

**Comment by agramfort** [comment]
doc Ifeachor and Jervis, 2002[2]_, p. 321 does not render fine

my feeling is that what uses will miss and when to use what filter.
eg when should you consider using a minimum phase filter?

we should have a filter FAQ:

- when should I consider using a minimum phase filter?
- when should I consider using an IIR filter like a butterworth?
- when should I use a causal filter?

etc.

I know that some of these info are there but we could make the info
either to find. I think an FAQ is a good option

my 2c

**Comment by Eric89GXL** [comment]
Do you want that as part of this PR? I probably won't get around to that for a while

**Comment by agramfort** [comment]
@Eric89GXL please update what's new page and merge.

thx

**Comment by Eric89GXL** [comment]
Done thanks @agramfort

**Pull request merged**
