### PR TITLE
[MRG] FIX: snirf length units

### PR DESCRIPTION
**Pull request by sappelhoff**
I noticed this because the mne-bids CI failed. These are probably reasonable fixes, wdyt @rob-luke?

https://github.com/mne-tools/mne-bids/runs/6338742975?check_suite_focus=true#step:15:400

### CODE REVIEW

**Comment by rob-luke** [comment]
I implemented the same fix in #10611, so I think it's a pretty good fix 😉. But let's get this merged as it might be faster than getting my pr approved that had a few other things that might have a review cycle.

**Review by rob-luke — APPROVED** [review]
Thanks @sappelhoff

**Comment by hoechenberger** [comment]
Do we need a changelog entry?

**Review by hoechenberger — APPROVED** [review]

**Comment by hoechenberger** [comment]
Thanks @sappelhoff

**Pull request merged**
