### PR TITLE
refactor bootstrap ci

### PR DESCRIPTION
**Pull request by jona-sassenhagen**
The bootstrap CI (and the other CI functions), originating with @dengemann 's GFP example, is moved to utils and the example now also relies on it. Also I'm giving proper credit :)

I'm not so sure it should be made public yet though ...

Addresses #4159

### CODE REVIEW

**Comment by larsoner** [comment]
CIs are a stats thing, put in `mne.stats`

Don't make public until we need to

**Comment by jona-sassenhagen** [comment]
Hmm ... where in stats? We don't have stats.utils/misc. One of the functions is parametric, the other is resampling based.

**Comment by larsoner** [comment]
> One of the functions is parametric, the other is resampling based.

One should go in parametric, the other in resampling, and both imported in `mne/stats/__init__.py`

**Comment by jona-sassenhagen** [comment]
Ok, and as it defaults to the bootstrap, I'll put the meta function (that can call the other two) with the resampling stuff (=actually, stats.permutations, but I guess it'll be ok).

**Comment by jona-sassenhagen** [comment]
@dengemann can you take a look?

**Comment by dengemann** [comment]
@jona-sassenhagen looks good to me! Thank you!

**Pull request merged**
