### PR TITLE
MRG, FIX: Brain add/remove labels

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR fixes the bug in `remove_labels()` preventing it to have any effect. I also updated the tests to avoid regression.

Closes https://github.com/mne-tools/mne-python/issues/8815

### CODE REVIEW

**Review by larsoner — APPROVED** [review]

**Comment by GuillaumeFavelier** [comment]
This is better I think @jasmainak 

image

**Comment by GuillaumeFavelier** [comment]
I added some commits to fix color and unnamed labels and improve tests.

**Review by jasmainak — APPROVED** [review]
Perfect, thanks for the fix!

**Comment by larsoner** [comment]
Thanks @GuillaumeFavelier !

**Pull request merged**
