### PR TITLE
[MRG] Fix documentation broken by stim_channel deprecation

### PR DESCRIPTION
**Pull request by massich**

### CODE REVIEW

**Comment by massich** [comment]
I'll find some time along the day to work on this one.

**Comment by larsoner** [comment]
Couldn't resist the urge to fix :)

**Comment by larsoner** [comment]
All better

https://10227-1301584-gh.circle-artifacts.com/0/html/auto_examples/visualization/plot_roi_erpimage_by_rt.html

Travis style passed so I'll merge. There is an unrelated breakage in 2.7 that I will fix next

**Comment by massich** [comment]
Cool thx

**Pull request merged**
