### PR TITLE
ENH: Add overlap add classes

### PR DESCRIPTION
**Pull request by larsoner**
This PR just refactors existing code to:

1. Make use of a generic overlap-add processing class (OTP), and
2. Make `Interp2` more flexible

This will eventually allow combining the two methods and using them more easily. For examlpe, @mmagnuski suggested that the reason `spectrum_fit` does not work and takes forever (#7577) is perhaps because it does not work in overlapping windows, but rather the entire raw file. With the `_OLA` class it should be much easier to make it operate on overlapping windows.

### CODE REVIEW

**Comment by larsoner** [comment]
Basically as long as the raw `simulation` tests pass (Interp2) and the OTP tests pass (_OLA), along with the builtin tests for Interp2 and _OLA, we should be able to trust the results here (I hope!).

Ready for review/merge from my end

**Comment by agramfort** [comment]
it's just a refactoring using a class / generator?

**Comment by larsoner** [comment]
Yes to make it easier to use it elsewhere

**Comment by agramfort** [comment]
+1 for MRG if green then

>

**Pull request merged**
