### PR TITLE
Plot title of excluded components in gray

### PR DESCRIPTION
**Pull request by cbrnr**
I think it would be helpful if excluded components (i.e. components that are in `ica.exclude`) were plotted differently in `ica.plot_components`. I've changed the component title to gray to distinguish them from normal ones.

IMO it would also be useful if the user could add components to the excluded list by clicking on their title. What do you think?

### CODE REVIEW

**Comment by agramfort** [comment]
good idea

but maybe red is a better color for "bad" ?

**Comment by jona-sassenhagen** [comment]
Light red? :) Like rgb(192, 113, 98)

**Comment by cbrnr** [comment]
I'd try to be consistent with `raw.plot`, where bad channels are marked in gray 😄  - but whatever you think is best.

What about marking ICs by clicking on the title? Should I try to implement that as well?

**Comment by agramfort** [comment]
yes we use red everywhere except in raw.plot as it can hide the good data.

**Comment by Eric89GXL** [comment]
> it can hide the good data.

We already set the `zorder` IIRC so this probably isn't such a huge concern for us. Maybe we should use the "light red" a.k.a. pink as suggested by @jona-sassenhagen to unify everything.

**Comment by cbrnr** [comment]
Either color is fine with me - we could also expose this as an argument and set the default to red for all plots except the raw plot, where the default could be gray. Personally, bad channels displayed in red would create a huge distraction from the good channels no matter if the z order is way at the back or not.

**Comment by agramfort** [comment]
whatever. We can change color later after playing with the feature

**Comment by agramfort** [comment]
@cbrnr shall I merge this or do you plan to add the interactive clicking option in this PR?

**Comment by agramfort** [comment]
ok merging. We can improve later.

**Pull request merged**
