### PR TITLE
BUG: Fix bug with weakref

### PR DESCRIPTION
**Pull request by larsoner**
Should fix the mysterious timeout observed in https://github.com/mne-tools/mne-bids-pipeline/pull/793. This one was tough to track down. Somehow having `n_jobs > 1` and having these `subscribe`s caused what I assume is a circular reference problem. Could be related to `Agg` backend not emitting the `close` event, not sure. Locally this `_auto_weakref` fixes the error at least when testing with:
```
rm -Rf ~/mne_data/derivatives/mne-bids-pipeline/ds000248_base/ && pytest mne_bids_pipeline -k ds000248_base
```
cc @wmvanvliet we'll need to be mindful of creating these circular references going forward I think :shrug: 

No idea how to make a nicely self-contained test for this so I'll open a PR to mne-bids-pipeline to make sure the doc build works when built against this branch, then I'll restart the `ds000248_base` run a few times.

Within-release bugfix so I don't think we need a changelog entry

### CODE REVIEW

**Comment by larsoner** [comment]
This does appear to fix the timeout from https://github.com/mne-tools/mne-bids-pipeline/pull/793

**Comment by hoechenberger** [comment]
Wow, things are getting complicated 😕

**Comment by wmvanvliet** [comment]
The `Brain` and `EvokedField` objects have unit-tests for memory leaks. When @ruuskas modified `DraggableColorbar` we never added a memory leak unit test. We shoud indeed be more diligent adding these tests. Indeed, these circular references are becoming a big pain :)

**Comment by wmvanvliet** [comment]
Maybe this can help us: https://pythonhosted.org/Pympler/muppy.html

**Pull request merged**
