### PR TITLE
MRG, ENH: Add ori on MRI slices

### PR DESCRIPTION
**Pull request by larsoner**
Part of #2995

### CODE REVIEW

**Review by hoechenberger — APPROVED** [review]
Code looks good, excited to see how the examples come back :)

**Comment by larsoner** [comment]
- https://21931-1301584-gh.circle-artifacts.com/0/dev/auto_examples/inverse/plot_mixed_norm_inverse.html#sphx-glr-auto-examples-inverse-plot-mixed-norm-inverse-py
- https://21931-1301584-gh.circle-artifacts.com/0/dev/auto_examples/inverse/plot_time_frequency_mixed_norm_inverse.html#sphx-glr-auto-examples-inverse-plot-time-frequency-mixed-norm-inverse-py
- https://21931-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/source-modeling/plot_dipole_fit.html#sphx-glr-auto-tutorials-source-modeling-plot-dipole-fit-py+

**Comment by agramfort** [comment]
this image seems wrong:

https://21931-1301584-gh.circle-artifacts.com/0/dev/_images/sphx_glr_plot_mixed_norm_inverse_003.png

and so is this one to some extent : https://21931-1301584-gh.circle-artifacts.com/0/dev/_images/sphx_glr_plot_dipole_fit_001.png

also for some reason the glyph in glass brain in : https://21931-1301584-gh.circle-artifacts.com/0/dev/auto_examples/inverse/plot_time_frequency_mixed_norm_inverse.html#sphx-glr-auto-examples-inverse-plot-time-frequency-mixed-norm-inverse-py do not show up. I should see 2 sources.

**Comment by larsoner** [comment]
> this image seems wrong:

This is (literally) a matter of perspective (projection), and illustrates why this is so useful. Here is the same image on my machine:

Screenshot from 2020-09-01 15-02-09

Then rotated to *almost* the three orthogonal views -- only *almost* so you can actually tell that there are two arrows...

Screenshot from 2020-09-01 15-02-19

Screenshot from 2020-09-01 15-02-24

Screenshot from 2020-09-01 15-02-28


> also for some reason the glyph in glass brain 

This is true in `master`:

https://mne.tools/dev/auto_examples/inverse/plot_time_frequency_mixed_norm_inverse.html#sphx-glr-auto-examples-inverse-plot-time-frequency-mixed-norm-inverse-py

I'll open a separate issue

**Review by agramfort — APPROVED** [review]
indeed. Really perfect !

thx @larsoner

**Comment by drammock** [comment]
sorry to notice this too late, but there is actually something off about those images.  The "stem" that connects the dipole vector to the orthogonal surfaces seems to be partially occluded by the MRI slices.  So, hopefully just a z-order problem?

**Comment by larsoner** [comment]
> So, hopefully just a z-order problem?

This is a matplotlib 3D bug. Even when I move them 1 cm inward, the z ordering gets messed up / occluded. I think we have to live with it unless we want to fix their 3D routines...

**Pull request merged**
