### PR TITLE
[WIP] ENH: combine annotations of different orig_time

### PR DESCRIPTION
**Pull request by massich**
#### What does this implement/fix?
Implements concatenating two annotations with different `orig_time`. 
(See https://github.com/mne-tools/mne-python/pull/5416#discussion_r219706912)

### CODE REVIEW

**Comment by larsoner** [comment]
@massich do we need this for 0.17?

**Comment by larsoner** [comment]
To me it does not seem like a blocker and we can add it later

**Comment by massich** [comment]
Yes this can go to 18

**Comment by mmagnuski** [comment]
BTW - could we sort the annotations based on onset when joining (or add `.sort()` method)? Currently I use `+` to append them and then sort them myself. It doesn't affect how annotations are used but it is cleaner to have them sorted.

**Comment by larsoner** [comment]
Opened an issue for `annotations.sort` in #5854 since I noticed the need for it again in #5851

**Comment by massich** [comment]
closed in favor of #5851

**Pull request closed without merging**
