### PR TITLE
Clim fix

### PR DESCRIPTION
**Pull request by wronk**

### CODE REVIEW

**Comment by Eric89GXL** [comment]
LGTM

**Comment by Eric89GXL** [comment]
@mainakjas have a look and see if it makes sense to you

**Comment by mainakjas** [comment]
new warning looks good. Feel free to merge if tests pass

**Comment by Eric89GXL** [comment]
You need to get rid of the test that had `assert_raises` for `stc.plot()` with no args

**Comment by agramfort** [comment]
@mainakjas happy?

does it mean that stc.plot() now works out of the box without any warning?

the what's new should be clear about the changes.

**Comment by mainakjas** [comment]
No it still throws a warning out of the box I think. The warning is just more meaningful

**Comment by agramfort** [comment]
Are you happy ? If so we have +1 with Eric's

**Comment by mainakjas** [comment]
yes, I'm good. Feel free to merge

**Comment by Eric89GXL** [comment]
Thanks @wronk

**Pull request merged**
