### PR TITLE
Move more metadata and build flags from setup.py to pyproject.toml

### PR DESCRIPTION
**Pull request by hoechenberger**
Make better use of pyproject.toml by moving project metadata and build system settings there from setup.py. Now, basically all that setup.py does is dynamically generating package dependencies.

### CODE REVIEW

**Comment by hoechenberger** [comment]
@larsoner Still, in [4684d3c](https://github.com/mne-tools/mne-python/pull/12060/commits/4684d3ccb982ec1a34a8d41c7e75c9367357e9d7) we catch some black errors that we don't see on `main` (even though these style violations **are** present in the `main` code!)

**Comment by larsoner** [comment]
No idea why that's happening but I don't mind the change and PR looks good so I'm inclined to mark for merge when green assuming you're done (still in draft mode currently)

**Comment by hoechenberger** [comment]
@larsoner this is ready to go

**Comment by larsoner** [comment]
Marking for merge when green, thanks in advance @hoechenberger !

**Pull request merged**
