### PR TITLE
Update SPM dataset.

### PR DESCRIPTION
**Pull request by jaeilepp**
Closes https://github.com/mne-tools/mne-python/issues/4410

Now contains the new trans-file, short (5s) fif-file with the dig points and the original headshape.mat.

### CODE REVIEW

**Comment by jaeilepp** [comment]
The amplitudes seem larger with the new trans compared to the [old](https://mne-tools.github.io/dev/auto_examples/datasets/plot_spm_faces_dataset.html?highlight=spm)

spm

**Comment by agramfort** [comment]
yes it's expected if you fixed the coreg. You should update the colormap
values to it highlights are more focal region in the ventral cortex.

**Comment by Eric89GXL** [comment]
> short (5s) fif-file with the dig points and the original headshape.mat.

You shouldn't need to do this -- you can use `read_dig_montage` and `DigMontage.save` which work with FIF files.

**Comment by Eric89GXL** [comment]
(and by "this" I mean, have any raw data at all -- it can be a FIF file that just contains the digitization information)

**Comment by agramfort** [comment]
yes I mean a tiny fif file not tiny raw fif file. Just with the dig.

**Comment by agramfort** [comment]
thx @jaeilepp see:

https://1750-35097627-gh.circle-artifacts.com/0/tmp/circle-artifacts.NvkmdJM/html/auto_examples/datasets/plot_spm_faces_dataset.html

**Comment by jaeilepp** [comment]
> it can be a FIF file that just contains the digitization information

I noticed that ``mne.gui.coregistration`` can't load the digitization from ``dig_montage``.

**Comment by agramfort** [comment]
it just loads from fif right?

**Comment by jaeilepp** [comment]
I think it has to be ``raw``, ``epochs`` or ``evoked``.

**Comment by agramfort** [comment]
indeed it should not be necessary. Can you have a look?

**Pull request merged**
