### PR TITLE
[MRG] Make traces in raw.plot_psd less transparent

### LINKED ISSUE #4802: Traces in `raw.plot_psd(average=False)` are too faint
The output of `raw.plot_psd(average=False)` currently looks like this:
psd_current

The alpha level is 0.1, which IMO is way to low. I propose changing this value to 0.75, which results in the following much improved output:
psd_075

Or am I missing the reason for setting such a low alpha value?

### PR DESCRIPTION
**Pull request by cbrnr**
Fixes #4802

### CODE REVIEW

**Comment by agramfort** [comment]
no objection. I had the same feeling too.

**Comment by larsoner** [comment]
How does it look for an example with MEG data (204 grad channels)? Probably `tutorials/plot_visualize_raw.py` does this

**Comment by cbrnr** [comment]
@larsoner current master:
psd_current
proposed change:
psd_new
I'd say the latter is much better.

**Comment by agramfort** [comment]
agreed

**Comment by larsoner** [comment]
Indeed, thanks @cbrnr

**Pull request merged**
