### PR TITLE
Fix to clickable image example.

### PR DESCRIPTION
**Pull request by jaeilepp**
Closes https://github.com/mne-tools/mne-python/issues/2567

### CODE REVIEW

**Comment by agramfort** [comment]
Is there a way to test this feature ?

**Comment by jaeilepp** [comment]
It's just a fix to ``plot_clickable_image`` so try running that.

**Comment by agramfort** [comment]
Pep8 error

You should add flake8 plugin to your editor

**Comment by jaeilepp** [comment]
It's not a PEP8 error. File downloading timed out.

**Comment by agramfort** [comment]
oups my bad. Read too quickly.

merging by rebase + backport

**Pull request merged**
