### PR TITLE
MRG: Add codecov

### PR DESCRIPTION
**Pull request by Eric89GXL**

### CODE REVIEW

**Comment by Eric89GXL** [comment]
We've used this in `scipy` and it seems to work well. Currently testing to see if this is better than `coveralls`.

**Comment by Eric89GXL** [comment]
Can't get a great sense of it until it's in `master`, but here is the sort of output it gives:

https://github.com/scipy/scipy/pull/5989

It updates the single comment, too, instead of posting new ones which is nice.

**Comment by agramfort** [comment]
looks nice.

let us know if it works

**Comment by Eric89GXL** [comment]
The thing to do is probably to merge this, and then tweak as things go. We can't do much comparison since there isn't currently a `master` build for it to compare against.

**Comment by agramfort** [comment]
Merge then






On Thu, May 12, 2016 at 1:29 PM -0700, "Eric Larson" <notifications@github.com> wrote:












The thing to do is probably to merge this, and then tweak as things go. We can't do much comparison since there isn't currently a master build for it to compare against.

**Pull request merged**
