### PR TITLE
MRG, MAINT: Fix PySurfer-related crash

### PR DESCRIPTION
**Pull request by larsoner**
Let's see if https://github.com/larsoner/mayavi/commit/c2a8a238c338074b43538448ea4e5dea268c5bf4 fixes [our Azure failures](https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=5345&view=logs&jobId=b195a6e3-7484-5943-e627-0b35c27605d6&j=b195a6e3-7484-5943-e627-0b35c27605d6&t=e39460f3-8bf4-5a9c-a10e-ca10a5c92a7f). Based on the traceback it might.

Will require several restarts of the Azure runs because this is a bit of a random bug.

### CODE REVIEW

**Comment by larsoner** [comment]
First test successful, restarting

**Comment by larsoner** [comment]
Trying again with a new approach that changes PySurfer's `__del__`

- [ ] [First test](https://github.com/mne-tools/mne-python/pull/7295/checks?check_run_id=431830515)

**Comment by larsoner** [comment]
Neither worked :(

Next I'll see if it's a PyVista or Mayavi problem by removing each of those.

**Comment by larsoner** [comment]
Pushed a commit to try to clean things up explicitly with `gc.collect` in case mayavi/pyface/PySurfer/whoever has a bug:

- [x] [first test](https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=5408&view=results)
- [ ] [second test](https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=5410&view=results)

**Comment by larsoner** [comment]
It looks like this might fix our sporadic failures. I'll go ahead and merge if we get through 10 iterations without error, okay @GuillaumeFavelier @agramfort ?

**Comment by GuillaumeFavelier** [comment]
It's okay for me

**Comment by agramfort** [comment]
yes... although the diff is puzzling...

**Comment by larsoner** [comment]
> yes... although the diff is puzzling...

Briefly, from what I understand:

- PySurfer does some `mlab.close` when objects get `.close` or `__del__`'ed (i.e., during garbage collection)
- We can't be sure of when the GC happens (and triggers the `__del__`)
- When creating two `brain` objects, it can be the case that the end up using the *same* Mayavi figure because of how Mayavi keeps track of its figures and how we create them in PySurfer (this is probably a bug with PySurfer's use of Mayavi)

Thus you can end up in some test creating a `Brain` instance with a Mayavi figure, then Python does GC and calls the `__del__` from a previous `Brain` that shared that figure, killing the resources, and when your shiny new `Brain` instance goes to draw somewhere down the line (Mayavi or TVTK) it tries to draw some objects that have been killed by `mlab.close`.

This PR works around this corner case stuff by forcing GC. Eventually we should probably fix PySurfer, too, but even once we do, these GC calls shouldn't hurt anything.

**Comment by agramfort** [comment]
thanks for the explanations

>

**Comment by larsoner** [comment]
This behavior might also now be fixed by https://github.com/nipy/PySurfer/pull/285, but I plan to merge this PR to MNE after test #10 so that we can have stable CIs again while we wait for that to be merged (and released, etc.)

**Pull request merged**
