### PR TITLE
[MRG] Deprecate montage param from all EEG raw readers

### PR DESCRIPTION
**Pull request by agramfort**
alternative to #6526

### CODE REVIEW

**Comment by agramfort** [comment]
crap my master was behind :( :( 

@massich I tried to the job with what i consider a dumb approach....

**Comment by agramfort** [comment]
we have the same error on master now https://travis-ci.org/mne-tools/mne-python/jobs/555779112

not sure about the circle failure though

**Comment by larsoner** [comment]
```
/home/circleci/project/doc/whats_new.rst:75: WARNING: py:func reference target not found: mne.io.read_epochs_eeglab
```

**Comment by massich** [comment]
This PR only deprecates that montage has to be None. It does not deprecate the montage parameter itself.

**Comment by agramfort** [comment]
done

>

**Comment by massich** [comment]
+1, once travis is green I'll fix the whatsnew and merge it.

**Comment by massich** [comment]
we should not be able to create info with montage shuold we?
https://github.com/mne-tools/mne-python/blob/master/mne/io/meas_info.py#L1586

**Comment by agramfort** [comment]
it should be possible but accepting a Digitization instance should be aimed for.

**Pull request merged**
