### PR TITLE
removes outdated comment

### PR DESCRIPTION
**Pull request by pbnsilva**

### CODE REVIEW

**Comment by Eric89GXL** [comment]
Thanks @pbnsilva. Working on some new reader, or did you hit a bug somewhere?

**Comment by pbnsilva** [comment]
Did a reader for OpenBCI's format; is it something you'd be interested in having here ?

**Comment by Eric89GXL** [comment]
Yeah that would be great. The latest reader that was added was `cnt`, so that might be a good one to base your work off of.

Also, I'm not sure if it would have any relationship to #2671 @teonbrooks?

**Comment by teonbrooks** [comment]
so we didn't want to add a reader for the OpenBCI data format from Processing because it is essentially just a csv, and you get it in with `mne.RawArray` or https://github.com/OpenBCI/mne_openbci. we had a lengthy discussion about it here (https://github.com/mne-tools/mne-python/pull/2462). 

We think the streaming option of #2671 that @Eric89GXL mentioned is the best way to go. we're actively developing nodejs implementation of OpenBCI [here](https://github.com/OpenBCI/openbci-js-sdk) and [here](https://github.com/NeuroJS/openbci-dashboard).

If you would like to chat, we're on gitter [here](https://gitter.im/OpenBCI/openbci-js-sdk) and [here](https://gitter.im/NeuroJS/openbci-dashboard)

**Comment by teonbrooks** [comment]
also, if you would like to work on #2462, feel free to add to it. I had to put it on the back burner for a while. @trachelr is also working with OpenBCI and is on the PR as well. if you would like, we could discuss what we might want to do with MNE and OpenBCI together. timestamping for evoked response is something else we have been working on. and there might be a good solution soon

**Comment by pbnsilva** [comment]
I agree; really like the idea of a streaming option. Will see how I can help once I'm back home next week.

**Pull request merged**
