### PR TITLE
[BUG, MRG] Fix Quiver3D default behavior

### LINKED ISSUE #10382: [BUG] Pyvista backend `quiver3d` behavior inconsistent
Here is a minimally reproducible example:

```
import mne
import os.path as op
data_path = mne.datasets.sample.data_path()  # get the sample data path
subjects_dir = op.join(data_path, 'subjects')
brain = mne.viz.Brain(subject_id='sample', hemi='both', surf='pial',
                      subjects_dir=subjects_dir, alpha=0.1)
brain._renderer.quiver3d(0, 0, 0, 0, 0, 10, 'red', 10, 'arrow')  # does nothing
brain._renderer.quiver3d(0, 0, 0, 0, 0, 10, 'red', 10, 'arrow',
                         scale_mode='scalar')  # still does nothing
brain._renderer.quiver3d(0, 0, 0, 0, 0, 10, 'red', 10, 'arrow',
                         scale_mode='scalar', scalars=[1])  # works
brain._renderer.quiver3d(0, 0, 0, 0, 0, 10, 'blue', 20, 'arrow',
                         scalars=[1])  # broken again
```

What I'm stuck on as far as fixing it is that the call goes to `_glyph` with `scalar=[1]` and the key line is 1101:

```
    if isinstance(scalars, str):
        dataset.active_scalars_name = scalars
```

Which shouldn't be a string so I have no idea how the one call that works does in fact work... Maybe @larsoner might have just a minute to take a peek.

### PR DESCRIPTION
**Pull request by alexrockhill**
Fixes #10382.

### CODE REVIEW

**Comment by alexrockhill** [comment]
This fixes all the examples from the issue, most importantly

```
import mne
import os.path as op
data_path = mne.datasets.sample.data_path()  # get the sample data path
subjects_dir = op.join(data_path, 'subjects')
brain = mne.viz.Brain(subject_id='sample', hemi='both', surf='pial',
                      subjects_dir=subjects_dir, alpha=0.1)
brain._renderer.quiver3d(0, 0, 0, 0, 0, 10, 'red', 10, 'arrow')
```

which uses the default arguments for the "arrow" mode works and shows an arrow instead of a silent error with nothing shown (current behavior). I checked `examples/visualization/brain` and `tutorials/inverse/35_dipole_orientations` and they both look good.

**Review by GuillaumeFavelier — APPROVED** [review]
Thank you for diving into the difficult `quiver3d()` function!

I'm okay with the changes but can you maybe touch the examples you mention so that Circles can render them in here?

**Comment by GuillaumeFavelier** [comment]
All good for me! Feel free to merge when the CIs return green :ok_hand: 

[PR](https://output.circle-artifacts.com/output/job/c002d56b-aaf2-4268-9855-cdf5310bf560/artifacts/0/dev/auto_tutorials/inverse/35_dipole_orientations.html) | [main](https://mne.tools/stable/auto_tutorials/inverse/35_dipole_orientations.html)
--|--
image | image

**Comment by alexrockhill** [comment]
https://output.circle-artifacts.com/output/job/c002d56b-aaf2-4268-9855-cdf5310bf560/artifacts/0/dev/auto_examples/visualization/brain.html#sphx-glr-auto-examples-visualization-brain-py

https://output.circle-artifacts.com/output/job/c002d56b-aaf2-4268-9855-cdf5310bf560/artifacts/0/dev/auto_tutorials/inverse/35_dipole_orientations.html?highlight=35_dipole#loose-dipole-orientations

Looks the same to me, note the second one was broken in MNE 0.24 but was fixed in 1.0

**Comment by alexrockhill** [comment]
> All good for me! Feel free to merge when the CIs return green 👌
> 
> [PR](https://output.circle-artifacts.com/output/job/c002d56b-aaf2-4268-9855-cdf5310bf560/artifacts/0/dev/auto_tutorials/inverse/35_dipole_orientations.html)	[main](https://mne.tools/stable/auto_tutorials/inverse/35_dipole_orientations.html)
> image	image

Huh that's odd, it almost looks like there's an issue with `main`, it could just be the perspective though

**Comment by alexrockhill** [comment]
I messed up a test so I refactored which actually helped reduce all the `scale`/`scalar` reuse which makes things so confusing!

**Comment by GuillaumeFavelier** [comment]
> it could just be the perspective though

Probably there was an issue related to glyph scaling but it's solved in here

**Comment by alexrockhill** [comment]
I think actually it just made the arrows slightly longer in this PR which looks much nicer than `main`, I don't think there was a bug.

**Comment by GuillaumeFavelier** [comment]
It sure looks like an improvement to me

**Review by agramfort — APPROVED** [review]

**Comment by agramfort** [comment]
thx @alexrockhill

**Comment by agramfort** [comment]
thx @alexrockhill

**Comment by agramfort** [comment]
backported

**Review by larsoner — COMMENTED** [review]
Sorry for the slowness @alexrockhill , but LGTM! @GuillaumeFavelier probably understands this VTK scalar business better than me anyway, so glad he was able to look + test

**Pull request merged**
