### PR TITLE
MRG: Dont use mne_surf2bem

### LINKED ISSUE #3709: avoid use of mne_surf2bem
we should remove the use of mne C tool mne_surf2bem in mne-python.

### PR DESCRIPTION
**Pull request by Eric89GXL**
Closes #3709.

### CODE REVIEW

**Comment by agramfort** [comment]
travis is not happy.

what command did you use to check we're good here. Are our tests good enough?

**Comment by Eric89GXL** [comment]
Haven't tested it myself yet. I suspect that our tests are not sufficient,
so I need to...

**Comment by agramfort** [comment]
that's my feeling too :)

**Comment by agramfort** [comment]
there is a related travis error

**Comment by Eric89GXL** [comment]
@agramfort we currently do decimation using TVTK or something, but it's not the same as MNE-C. Should we make it use the MNE-C routine? It should be faster and more consistent, but I think we would need a new param and deprecation cycle.

**Comment by Eric89GXL** [comment]
Actually never mind, I think what we have is fine

**Comment by Eric89GXL** [comment]
Tests improved, ready for review/merge from my end

**Comment by agramfort** [comment]
thx @Eric89GXL !

**Comment by agramfort** [comment]
please update what's new in master directly.

**Pull request merged**
