### PR TITLE
API: Return Path in data_path

### LINKED ISSUE #10320: ENH: Return Path in `data_path`?
I saw @hoechenberger's code [here](https://github.com/mne-tools/mne-qt-browser/pull/43/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R38-R40):
```
sample_dir = mne.datasets.sample.data_path()
raw_path = Path(sample_dir) / 'MEG' / 'sample' / 'sample_audvis_raw.fif'
```
And thought it was a bit sad that he had to `Path(...)` the `data_path()` result.

Since 1.0 is coming out, I think one small breaking change we could make would be to return `Path` instead of `str` in `data_path`.

1. It actually matches the name of the function better
2. It should help people modernize their code a bit with things like `...data_path() / 'subject'`
3. `op.join` still works and returns `str`

The big problem I see is:

1. This fails:
    ```
    >>> Path('.') + '/foo'
    TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'
    ```
    The fix is pretty easy in this case, but it will break people's code. The fix is pretty easy, but it's still some pain...

We can probably get around this, though, with some class magic -- we could subclass `PosixPath` and `WindowsPath` with support for a `+` operator, where if the other arg is a `str` then we cast to `str` and return `op.join(path_str, other_str)` (after stripping `op.sep` from the `other_str`).

Thoughts?

An alternative would be to do something like `data_path(..., out='path')`, but I'm not sure that's much better than having people import from `pathlib` (though I guess it's shorter). One advantage of that approach is that we could deprecate `out='str'` -> `out='path'` to give people time to change.

### PR DESCRIPTION
**Pull request by larsoner**
Closes #10320

WIP because I still need to change ~200 instances in examples and tutorials. Pushing now to get CIs happy to make sure the simple magic class isn't breaking anything. The one thing I "broke" on purpose was `35_dipole_orientations.py` where `+` is used but I didn't change it yet, just to make sure the DeprecationWarning shows up there.

### CODE REVIEW

**Review by agramfort — APPROVED** [review]
looks good !

mne looks less old school now :)

**Comment by larsoner** [comment]
I have a fix for the Windows failure. Just waiting to hear from CircleCI about which examples I messed up or missed...

**Comment by larsoner** [comment]
Okay, let's see how it goes!

**Comment by cbrnr** [comment]
Nice! Why did you decide to go with an unmodified `pathlib.Path` in the end?

**Comment by larsoner** [comment]
> Nice! Why did you decide to go with an unmodified pathlib.Path in the end?

I didn't, it's a modified version called `MNEPath`. We call it a `Path` in the docs just for simplicity (and technically it is `isinstance(x, Path)` so not *too* misleading)

**Pull request merged**
