### PR TITLE
MRG: Fix info

### PR DESCRIPTION
**Pull request by larsoner**
Should fix AppVeyor, will merge assuming it passes.

### CODE REVIEW

**Comment by agramfort** [comment]
what was the pb? why is new?

**Comment by larsoner** [comment]
`numpy` outputs something like:
```
blas_info
   NOT AVAILABLE
```
Must be some new NumPy `1.14` bug

**Comment by larsoner** [comment]
Upstream bug:

https://github.com/numpy/numpy/issues/10386

**Comment by agramfort** [comment]
thx @larsoner

**Pull request merged**
