### PR TITLE
MRG: Fix resizing

### LINKED ISSUE #5346: Resizing after dropping flat epochs fails - does not own its data
Hi,

I get the following error:

```
4 bad epochs dropped
Traceback (most recent call last):

  File "<ipython-input-11-6faf2142abd0>", line 13, in <module>
    epochs.drop_bad(flat=dict(seeg=100e-10))

  File "<string>", line 2, in drop_bad

  File "c:\users\user\documents\github\mne-python\mne\utils.py", line 725, in verbose
    return function(*args, **kwargs)

  File "c:\users\user\documents\github\mne-python\mne\epochs.py", line 1053, in drop_bad
    self._get_data(out=False)

  File "<string>", line 2, in _get_data

  File "c:\users\user\documents\github\mne-python\mne\utils.py", line 725, in verbose
    return function(*args, **kwargs)

  File "c:\users\user\documents\github\mne-python\mne\epochs.py", line 1254, in _get_data
    data.resize((n_out,) + data.shape[1:], refcheck=False)

ValueError: cannot resize this array: it does not own its data
```

A similar case has been reported [here](https://github.com/mne-tools/mne-python/pull/2211). @larsoner provided a [fix](https://github.com/mne-tools/mne-python/pull/2211/commits/3b3a68b9591de1240da90f8e137473d0a05dfda7) back then.

### PR DESCRIPTION
**Pull request by larsoner**
Closes #5346.

@stfnrpplngr can you see if this fixes your problem?

### CODE REVIEW

**Comment by stfnrpplngr** [comment]
It solves the problem from the initial minimal example. I needed to add some lines, now it shows the error from before. The gist is updated:

https://gist.github.com/stfnrpplngr/3460831b982bffbb1ac9405f39cf25fc

**Comment by larsoner** [comment]
Okay should be fixed

**Comment by stfnrpplngr** [comment]
Works like a charm. Thank you.

**Comment by agramfort** [comment]
thx @larsoner

**Pull request merged**
