### PR TITLE
WIP : combine_evoked

### PR DESCRIPTION
**Pull request by agramfort**
that's a follow up on a conversation with @mshamalainen in Helsinki about contrasting evoked. Weighted contrasts should be an option and weights with nave is not always the good approach eg. in an oddball task.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
This one is too far behind to rebase appropriately, closing for follow-up PR.

**Comment by kingjr** [comment]
I just discovered this issue after a painful bug tracking. 
I think we should warn the user if +/- are used and nave aren't equal, and provides clearer documentations in + / -.

**Comment by agramfort** [comment]
where do you suggest we put this doc?

See

https://github.com/mne-tools/mne-python/issues/1934

**Comment by kingjr** [comment]
Something like:

```
    def __sub__(self, evoked):
       """ Applies a subtraction of evoked datasets
            /!\ The subtraction is weighted by the number of epochs originally
           averaged (evoked.nave) """
        this_evoked = deepcopy(evoked)
        this_evoked.data *= -1.
        if self.nave != this_evoked.nave:
             warnings.warn('The evokeds do not have identical nave! '
                        'This will generate a weighted subtraction.')
        out = combine_evoked([self, this_evoked])
        if self.comment is None or this_evoked.comment is None:
            warnings.warn('evoked.comment expects a string but is None')
            out.comment = 'unknown'
        else:
            out.comment = self.comment + " - " + this_evoked.comment
        return out
```

**Comment by agramfort** [comment]
I would not make it a warning which are displayed only once anyway. I'd use
the logger. I think it's valuable info for users.

**Comment by kingjr** [comment]
> I would not make it a warning which are displayed only once anyway. I'd use
the logger. I think it's valuable info for users."
Perhaps both?

On second thought, I agree with what 's been said above: the very large majority of naive users will think that '-' does a classic '-' operation, not a weighted one, so I vote for an important change there, even if this means changing a lot of code based on the assumption that the subtraction is weighted.

In the meantime, we could also explicit the code:
```
def __sub__():
...
out = combine_evoked([self, this_evoked], , weights='nave')
```

**Comment by agramfort** [comment]
not using nave by defaults means breaking inverse modeling params by
default... that's my concern

**Comment by kingjr** [comment]
I understand the issue indeed. Do you have an example where this would break? Could we think of a test that checks the space (sensor or source) of the subtraction?

**Comment by agramfort** [comment]
>
> I understand the issue indeed. Do you have an example where this would
> break? Could we think of a test that checks the space (sensor or source) of
> the subtraction?
>
basically the amplitudes of sLORETA / dSPM would be wrong and the
regularization using SNRs will be bad too. Now in practice it might not
change much on some data the output. It just opens the door to improper and
uncontrolled modeling.

**Comment by dengemann** [comment]
Adding verbosity should do the job.
Log sth like:

Computing weighted average, nave ...

**Comment by kingjr** [comment]
I think you overestimate users' reading ability / attention capacity...

**Comment by agramfort** [comment]
so how do you make sure they properly use nave to control noise level?

**Comment by dengemann** [comment]
But it's wrong not to do it for probably most of the cases and it corresponds to the traditional MNE behavior. We would break conistency with code that's been around for more than a decade.

**Comment by dengemann** [comment]
I would vote for adding verbosity and maybe a contrast tutorial which points out differences for sensor space and source space handling and highlights the use of the function in certain cases.

**Comment by dengemann** [comment]
deprecating the +/- operators will be expansive. It's used everywhere. Changing their meaning is not good either.

**Comment by kingjr** [comment]
Yes, it's a classic conservative versus logic debate. Is it not possible to test for the type of subtraction one does (i.e. source or sensor space)?

**Comment by dengemann** [comment]
>  Is it not possible to test for the type of subtraction one does (i.e. source or sensor space)?

this is not the question, it's always in sensor space when this operation is performed. It's about getting the sensor space contrast right for later source localization.

**Comment by kingjr** [comment]
damned

**Comment by dengemann** [comment]
So traditionally MNE has been a source localization software and I think the Python package followed these goals. In addition to the classical use case which has been exisiting for more than a decade and is reflected in our long term user population, we now have folks that do MEG and EEG in sensor space. We would need to deprecate the +/- for evoked and point everyone to using the function and educate about different use cases, depending on experimental protocol and the intention to source localize.

**Comment by Eric89GXL** [comment]
+1 for deprecation. This comes up repeatedly, and even with clear logging and/or documentation users can still easily make an error, which is unsafe. Forcing them to use a function should be safer.

**Comment by dengemann** [comment]
>  Forcing them to use a function should be safer.

Thinking about it a bit this would probably be worth the pain on the long run. We need defaults that make sense to all of our users.

**Comment by kingjr** [comment]
>Thinking about it a bit this would probably be worth the pain on the long run. We need defaults that make sense to all of our users.

+1

**Pull request closed without merging**
