### PR TITLE
MRG: Change _TimeViewer slider style

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
It occurs to me that I never asked for feedbacks for the slider style, I just went with what I found practical but apparently the current design has some limitations. For example, since the slider tube is very thin it's easy to miss it and rotate the brain instead (reported in https://github.com/mne-tools/mne-python/pull/7247#issuecomment-583536539 and offline by @hoechenberger). This PR tries to address that by changing the style of the slider (and by doing so, modify it's hitbox).

I suggest 2 styles of sliders. In both styles I removed the end cap. In style 1, I increased the tube width but the overall style stays similar. The style 2 is a bit extreme but fixes the original issue quite easily.

<details>

```py
import os
import mne
from mne.datasets import sample
data_path = sample.data_path()
sample_dir = os.path.join(data_path, 'MEG', 'sample')
subjects_dir = os.path.join(data_path, 'subjects')
fname_stc = os.path.join(sample_dir, 'sample_audvis-meg')
stc = mne.read_source_estimate(fname_stc, subject='sample')
initial_time = 0.1
mne.viz.set_3d_backend('pyvista')
brain = stc.plot(subjects_dir=subjects_dir, initial_time=initial_time,
                 clim=dict(kind='value', pos_lims=[3, 6, 9]),
                 hemi='lh',
                 )
```

</details>

`master` | Style 1 | Style 2
------------|-----------|-----------
image | image | image

Except the size, it's also possible to change the colors (*c.f.* https://github.com/pyvista/pyvista/pull/511):

image

Sadly, changing the shape or replacing the handle by a texture would require way more work on the VTK part.

It's an item of #7162

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
What do you think @agramfort, @hoechenberger, @larsoner, @drammock ?

**Comment by hoechenberger** [comment]
+1 for style 2 with slightly less thick tube & slider. This then also mimics the sensor-level plots (e.g. `Raw.plot()`) and it's also the kind of slider used in all (?) modern operating systems / GUIs: tube has the same width as the slider.

**Comment by GuillaumeFavelier** [comment]
Style 3 is just a rework of 2) but with the same size used in `master`.

**Comment by GuillaumeFavelier** [comment]
Also feel free to share if you have any suggestions for the colors.

**Comment by hoechenberger** [comment]
> Style 3 is just a rework of 2) but with the same size used in `master`.

That could work! What do the others think? Sure, I think it's more aesthetically pleasant to look at those sliders where the tube is narrower than the slider element, but I think this here is an important tradeoff to make between eye candy and usability.

Regarding the colors, can you adjust the tube color to be slightly less salient? Very-light-gray-ish or something?

**Comment by GuillaumeFavelier** [comment]
> Regarding the colors, can you adjust the tube color to be slightly less salient? Very-light-gray-ish or something?

Good idea!

**Comment by hoechenberger** [comment]
It's not by any chance possibly to specify a color for the _outline_ (border) of the tube, is it? Bc then you could make the tube black (as the background) and still indicate that this is a slider widget by having a fine outline drawn, inside which the slider can move.

**Comment by GuillaumeFavelier** [comment]
AFAIK not just with sliders but maybe with vtkBorderWidgets...

Reference: https://vtk.org/Wiki/VTK/Examples/Cxx/Widgets/BorderWidget

**Comment by hoechenberger** [comment]
> AFAIK not just with sliders but maybe with vtkBorderWidgets...

Seems too complicated… let's see if a less prominent tube color does the trick for now :)

**Comment by GuillaumeFavelier** [comment]
Trying with my firefox slider on KDE:

image

I obtain:

image

**Comment by hoechenberger** [comment]
@GuillaumeFavelier looks good to me!!

**Comment by hoechenberger** [comment]
@GuillaumeFavelier I just pulled and tried this out and I noticed another (minor) oddity:

When I click a slider somewhere left or right of its horizontal center point and then start dragging, as soon as dragging begins, the slider jumps such that it's centered horizontally below the cursor.

**Comment by GuillaumeFavelier** [comment]
If you click the tube it's normal that the slider jumps but when I drag, the slider moves only at the end of the interaction for me. I don't think I can reproduce this

**Comment by hoechenberger** [comment]
@GuillaumeFavelier I've recorded a video:
https://drive.google.com/open?id=1EkPfPqRT47euD87_E8Idrr4P98PQX2hp

**Comment by agramfort** [comment]
I think we can live with that :)

>

**Comment by GuillaumeFavelier** [comment]
>  I've recorded a video

Thank you, now I understand what you mean.

**Comment by larsoner** [comment]
Looks great to me, I do like the slider filling up the entire height of the tube

**Comment by GuillaumeFavelier** [comment]
This is ready for merge then

**Comment by larsoner** [comment]
Thanks @GuillaumeFavelier

**Pull request merged**
