### PR TITLE
MRG, DOC: categorize tutorials

### PR DESCRIPTION
**Pull request by drammock**
this creates sub-categories for tutorials (parallel to how examples are already organized).  This is the first step in an overhaul of tutorials; next they'll be put into a specific order and edited / combined / supplemented.

One thing I tried to do was remove any cross-references of the `sphx_glr_xxx.py` type, and replace with named references.  I also tried to make the named references consistent: always using hyphen-separators between words (since underscores can be meaningful in rST) and prefixing tutorials with `tut-` and examples with `ex-`.  I doubt that I caught all of them, but I at least seem to have caught all the ones that were pointing into or out of the tutorials that were moved.

### CODE REVIEW

**Comment by agramfort** [comment]
good to go or still WIP?

>

**Comment by drammock** [comment]
Good to go @agramfort. There will be separate PRs for the subsequent steps.

**Comment by agramfort** [comment]
thx @drammock !

**Comment by agramfort** [comment]
for the record here is the rendered page of tutos: https://12962-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/index.html

**Comment by massich** [comment]
great job! thx @drammock

**Pull request merged**
