### PR TITLE
make compute_psd work on a BaseEpochs instance

### PR DESCRIPTION
**Pull request by agramfort**
BaseEpochs can appear from the code base eg when concatenating Epochs.

### CODE REVIEW

**Comment by drammock** [comment]
I had no idea that BaseEpochs could occur in the wild.  To me it the right fix is to make concatenation return `Epochs` instead of `BaseEpochs`.  Is that not an option?

**Comment by larsoner** [comment]
Or maybe `EpochsArray`? I agree it's weird to have it return BaseEpochs. But maybe we should do that in another PR

**Comment by agramfort** [comment]
we agreed during meeting today that we should use EpochsArray

Dan accepted to have a look.

Let's not merge this one for now.

**Comment by larsoner** [comment]
Coming back to this and thinking about it more -- internally I'm not sure why we wouldn't ever just check for `BaseEpochs`. If we ever add a new `read_epochs_*` that returns a `EpochsSomething` class that inherits from `BaseEpochs` and implements the right `_get_raw_from_disk` or whatever, it should work. For example, we already have this pattern with `read_epochs_eeglab`, which returns a `EpochsEEGLAB` that only inherits from `BaseEpochs` -- which seems like the right pattern to me -- and the `epochs.compute_psd` *should* be made to work with this object. If it works for this one, I'm not sure why it wouldn't work for anything that inherits from BaseEpochs...

@drammock could we check to see if it's `BaseEpochs` and then iterate over the object? Or if we require preloading just do `_check_preload` then use `._data`?

**Comment by larsoner** [comment]
Ohh I see, it should already work for anything that *inherts from BaseEpochs* but not a bare BaseEpochs instance itself. In that case, maybe we don't need this after #11309. Let's try without it, and resurrect this if needed...

**Comment by drammock** [comment]
> Ohh I see, it should already work for anything that _inherts from BaseEpochs_ but not a bare BaseEpochs instance itself.

Yep exactly!  so #11309 should be enough.

**Pull request closed without merging**
