### PR TITLE
Ignore event_offset in cnt when no events exist.

### PR DESCRIPTION
**Pull request by jaeilepp**
cf. mailing list.

Adding a test would require adding a small file which I don't have.

### CODE REVIEW

**Comment by agramfort** [comment]
Would it be possible to have a test?

Can you update what's new?

**Comment by agramfort** [comment]
@jaeilepp did you try on the problematic file ? how do you know it works?

**Comment by jaeilepp** [comment]
Yeah, I have the problematic file. It's 2GB. The event_offset field in the file header was a negative value. Rest of the header seems okay.

**Comment by agramfort** [comment]
ok let's say it works then...

**Comment by agramfort** [comment]
thx @jaeilepp

**Pull request merged**
