### PR TITLE
MAINT: Fix for pydata-sphinx-theme

### LINKED ISSUE #10598: Version switcher broken when viewing dev docs
When looking at the devel docs e.g. at:

https://mne.tools/dev/index.html

and then trying to use the version switcher dropdown to switch to the documentation of an earlier release, one gets a 404.

### PR DESCRIPTION
**Pull request by larsoner**
Closes #10598

Fix for backward incompat change https://github.com/pydata/pydata-sphinx-theme/pull/604 which fails silently and gives bad URLs

### CODE REVIEW

**Comment by larsoner** [comment]
Hah, https://nodejs.org/download/release/v16.13.2 is down with a 500 error. I guess we'll try later!

**Comment by larsoner** [comment]
All better! https://output.circle-artifacts.com/output/job/aea5ead8-6ef0-4364-812c-c3a09a62d850/artifacts/0/dev/index.html

**Comment by hoechenberger** [comment]
@larsoner I don't think this one has been backported, should we do it?

**Comment by larsoner** [comment]
All of the links seem to work in https://mne.tools/stable/ so I'm not sure we need to

**Comment by larsoner** [comment]
... but if we continue backporting things and want to push a website update, we might need to. Not sure

**Comment by hoechenberger** [comment]
Let's just drop this then :)

**Pull request merged**
