### PR TITLE
ENH: set color for bad channel with spatial_colors=True

### LINKED ISSUE #12137: Should PSD plots in the report contain bad channels by default?
Since we switched from plot_psd() to compute_psd().plot(), PSD plots in the Report contain bad channels. Is this a default we want to keep? I was using MNE-BIDS-Pipeline and triple-checked my data until I realized what's going on. (I thought something was wrong with my BIDS conversion) 
So even if we keep this behavior for Report, we should reconsider it for MNE-BIDS-Pipeline (and transfer this issue if needed)

### PR DESCRIPTION
**Pull request by larsoner**
Closes #12137

@hoechenberger can you try it with your data to see if it helps?

This will affect at least `evoked.plot` and `spectrum.plot` as `spatial_colors=True` by default.

- [x] See if it actually helps with reports
- [x] Add test
- [x] Add changelog entry

### CODE REVIEW

**Comment by hoechenberger** [comment]
@larsoner i don't know when I'll will have time to test this, don't wait for me 🥹

**Comment by larsoner** [comment]
On `main`:
```
import mne
raw = mne.io.read_raw_fif(mne.datasets.sample.data_path() / "MEG" / "sample" / "sample_audvis_filt-0-40_raw.fif")
raw.pick("eeg", exclude=()).load_data()
raw.plot_psd(exclude=())
```
gives:

Screenshot from 2023-10-26 11-51-49

On this PR it's:

Screenshot from 2023-10-26 11-55-43

There is a bug on `main` where `bad_ch_idx=[]` so the dashed-ness was never applied. But I like that in this PR that is applied *and* it's gray -- I think it works well.

With the gray we could consider getting rid of the dashing which makes the bad one easier to resolve:

Screenshot from 2023-10-26 11-56-49

**Comment by hoechenberger** [comment]
I like the last figure you posted!

**Comment by larsoner** [comment]
Ready for review/merge from my end.

When I modified the Report tutorial with dashing turned off it [looked like this](https://output.circle-artifacts.com/output/job/1b0c282a-66cf-4018-a4bc-ad73c72fca8e/artifacts/0/html/auto_tutorials/intro/report_epochs.html#Epochs_from__epochs_). So I decided in the end to keep it to make it [slightly more differentiable](https://output.circle-artifacts.com/output/job/e48355d8-33c3-46b4-8337-81cbc2b3ae13/artifacts/0/html/auto_tutorials/intro/report_epochs.html#Epochs_from__epochs_).

**Review by drammock — APPROVED** [review]

**Review by hoechenberger — APPROVED** [review]
👌

**Pull request merged**
