### PR TITLE
MRG, ENH: Allow reading file-like objects

### LINKED ISSUE #5867: ENH: Reading file-like objects
#### Describe the problem

Some data reading APIs provide open file objects, and do not provide a full path to the file. For example, [gcsfs](https://gcsfs.readthedocs.io/en/latest/) provides an API to read files directly from Google File Storage

```
fs = gcsfs.GCSFileSystem(project='my-gcp-project')
with fs.open("my_bucket/data.fif") as f:
    # Do things with an open file object
    ...
```    

It would be useful to be able to do: 

```
fs = gcsfs.GCSFileSystem(project='my-gcp-project')
with fs.open("my_bucket/data.fif") as f:
    raw = io.read_raw_fif(f)
```

But `io.read_raw_fif` can only take a string as input.

So it would be good if there was some way to take an open file object and use that instead. 

Sorry: I have no idea what the implementation details would be.

### PR DESCRIPTION
**Pull request by larsoner**
Closes #5867.

@arokem is it easy for you to test what you wanted to do in #5867? The caveat is that you must use `preload=True` or `preload='/some/memmap/filename'`.

### CODE REVIEW

**Comment by agramfort** [comment]
cool ! I was expecting a much more painful diff

**Comment by arokem** [comment]
Looks promising! Thanks for implementing this. I'll test it out with my use-case and report back.

**Comment by larsoner** [comment]
Based on tests and feedback I'll merge, but @arokem please do still test and let us know how it goes. Happy to make a follow-up PR if necessary

**Comment by arokem** [comment]
Sorry for the slowness here. I will test and follow, but it will probably only be next week. I'm swamped with other stuff atm.

**Comment by teonbrooks** [comment]
cool. thanks @larsoner! do you think we could extend this to the `edf` module?

**Comment by larsoner** [comment]
It's probably possible to do this for most readers, yeah

**Pull request merged**
