### PR TITLE
Fix setting csd.tmin/csd.tmax for csd_morlet

### PR DESCRIPTION
**Pull request by wmvanvliet**
Found a small bug in my CSD code.

### CODE REVIEW

**Comment by wmvanvliet** [comment]
`csd.tmin` and `csd.tmax` are set purely for bookkeeping reasons. When using `csd_morlet`, they were not set properly. Now they are.

**Comment by larsoner** [comment]
Is this worth backporting to 0.16?

**Comment by wmvanvliet** [comment]
Depends on the effort that would take. This is a noncritical bug. Of course, the code change to fix it is trivial. Your call :)

**Comment by agramfort** [comment]
LGTM

can you merge and backport to maint/0.16?

thx

**Comment by larsoner** [comment]
done

**Pull request merged**
