### PR TITLE
MRG: Fix raw sim with BEM and use_cps=True

### PR DESCRIPTION
**Pull request by larsoner**
Fixes a bug when using a BEM where:

1. Corner case: the BEM surface was transformed without copy for the purposes of forward omission testing, so on return if `bem` was passed directly it was modified.
2. Fix accounting of `src[ii]['patch_info']` and `src[ii]['pinfo']`, instead of delete recreate after reducing source space as in `_make_forward.py` so that patch stats can actually be used.

Still need to:

- [x] add round-trip testing for forward w/identity
- [x] add non-modification-of-BEM test

### CODE REVIEW

**Comment by larsoner** [comment]
Okay tests pushed, ready for review/merge from my end.

**Comment by larsoner** [comment]
Failures and just of the standard iffy unrelated OSX variety

**Comment by agramfort** [comment]
good to go. Please back port thx

**Comment by larsoner** [comment]
Merged by rebase and backported

**Pull request closed without merging**
