### PR TITLE
ENH: Add vertical line to raw plot

### PR DESCRIPTION
**Pull request by Eric89GXL**
Allows clicking in between the channels to draw a vertical line like in `mne_browse_raw`.

Ready for review/merge from my end.

### CODE REVIEW

**Comment by mainakjas** [comment]
@Eric89GXL works like a charm. Is it hard to add the time point somewhere in the plot? For example, if I click at 5.3 seconds, it tells me that.

**Comment by Eric89GXL** [comment]
Let me see if it's easy

**Comment by Eric89GXL** [comment]
@mainakjas see if you're happy now

**Comment by mainakjas** [comment]
That was fast @Eric89GXL !

**Comment by Eric89GXL** [comment]
Try now @mainakjas

**Comment by mainakjas** [comment]
works fine. I love this addition because it lets me look at the spacing between triggers very easily. Do you think we could improve the placement of the text a bit? Not super important but it looks a bit weird on the gray brackground. At least I don't have a very good suggestion (maybe corner?), so maybe we could just leave it there.

**Comment by mainakjas** [comment]
other than that, I see no problem. You have my +1

**Comment by Eric89GXL** [comment]
I actually originally had it to the left of the scroll axis, I've moved it back, see what you think

**Comment by mainakjas** [comment]
yeah, much better!

**Comment by Eric89GXL** [comment]
Cool, I'll go ahead and merge once the CIs are happy then. Shouldn't you be asleep anyway? This is some @dengemann territory you've wandered into.

**Comment by mainakjas** [comment]
haha, I discovered once upon a time that I can be uninterrupted at night and I've loved that ever after :)

**Comment by Eric89GXL** [comment]
Thanks for the quick review @mainakjas.

**Pull request merged**
