### PR TITLE
[MRG] Fix ica.plot_sources exception

### LINKED ISSUE #8966: ica.plot_sources ignores ica_names if picks is used
#### Describe the bug
if you specify `picks` to `ica_plot_sources` the labels are in order starting with ICA0000, ICA0001....

For instance
`ica.plot_sources(raw, picks=[4, 6])`
will make a plot whose ch_name labels are ICA0000 ICA0001

#### Steps to reproduce
this is reproduced in the final plot of the ica example
https://mne.tools/dev/auto_examples/preprocessing/plot_run_ica.html#sphx-glr-auto-examples-preprocessing-plot-run-ica-py

CC @drammock

### PR DESCRIPTION
**Pull request by bloyl**
#### What does this implement/fix?
```
ica.exclude = [0]
ica.plot_sources(raw, picks=[1, 2])
```
would raise an exception.

`RuntimeError: bad channel(s) ['ICA000'] marked do not exist in info`

Also fixed a typo in ctf.io

I don't think either of these have made it to release so no whats new.

closes #8966

### CODE REVIEW

**Comment by larsoner** [comment]
Just a heads up that the pip 3.9 and pip pre builds are broken currently, feel free to ignore them

**Comment by drammock** [comment]
Looks like this does not actually fix the problem:
https://25470-1301584-gh.circle-artifacts.com/0/dev/auto_examples/preprocessing/plot_run_ica.html#sphx-glr-auto-examples-preprocessing-plot-run-ica-py

I'll take a closer look.

**Comment by drammock** [comment]
The example looks correct now: https://25473-1301584-gh.circle-artifacts.com/0/dev/auto_examples/preprocessing/plot_run_ica.html#sphx-glr-auto-examples-preprocessing-plot-run-ica-py

But I don't think the change to the test file is actually testing what we want it to, so don't merge until after I've updated that (off to a meeting now)

**Comment by bloyl** [comment]
Sorry I should have been clearer. My commits were intended to just fix the behavior in the PR description and in the test, not the issue opened (#8966).

Your commits seem to close that issue as well. Thanks!

**Comment by drammock** [comment]
> Sorry I should have been clearer.

I think this was a case of me not reading carefully enough :)

Anyway I think now both problems are fixed.

**Review by drammock — APPROVED** [review]

**Comment by drammock** [comment]
thanks @bloyl !

**Pull request merged**
