### PR TITLE
Add describe method for annotations

### PR DESCRIPTION
**Pull request by rob-luke**
#### Reference issue
#8782

#### What does this implement/fix?
Adds `describe()` to annotations. Completely inspired by #8760

#### Additional information
Just an initial attempt, if people are interested I can expand. If its too basic then will close.

### CODE REVIEW

**Comment by cbrnr** [comment]
I think the standard `repr` is sufficient for most use cases, e.g.

```
<Annotations | 30 segments: T0 (15), T1 (8), T2 (7)>
```

I'd rather have a `to_data_frame` method for analyzing annotations in more detail, because in contrast to `raw.describe` I think what measures are interesting depends a lot on the specific use case.

**Comment by agramfort** [comment]
I agree with @cbrnr 
I would add a to_data_frame method to Annotations and then it seems it's just a groupby('description').count()

**Comment by hoechenberger** [comment]
I'd like to second the idea of allowing DataFrame export, and potentially tweaking the string representation a bit

**Review by agramfort — APPROVED** [review]

**Comment by agramfort** [comment]
thx @rob-luke

**Comment by rob-luke** [comment]
Thanks for the improved approach.

**Pull request merged**
