### PR TITLE
only delete topmost annotation on right-click

### PR DESCRIPTION
**Pull request by drammock**
cc @mscheltienne 

This needs tests, but it turned out that refactoring z-order was not all that hard to do. (I say that now, having not written the tests yet 😉 )

crossref to https://github.com/mne-tools/mne-qt-browser/pull/173

### CODE REVIEW

**Comment by mscheltienne** [comment]
Thanks for taking a stab at the matplotlib backend.
It doesn't behave exactly in the same way because it does not add a way to _change_ which annotation is on top. In https://github.com/mne-tools/mne-qt-browser/pull/173, I'm changing the z-order when the selected description is changed thus giving priority to the currently selected description.
Maybe we can do something similar with the matplotlib backend, change the z-order when one of the radiobutton from the annotation pop-up is pressed to select an existing annotation description?

P.S. I'm noticing now that https://github.com/mne-tools/mne-qt-browser/pull/173 is not entirely working either..

**Comment by mscheltienne** [comment]
OK, I fixed https://github.com/mne-tools/mne-qt-browser/pull/173, I forgot to consider annotations added at loading 🙈 
Below a short screencast with the behavior on both PRs.

https://github.com/mne-tools/mne-python/assets/73893616/900163c8-7c92-4e97-b12e-f67e44787007

**Comment by drammock** [comment]
I think now the behaviors should be in sync 🤞🏻 Still no tests though, that will have to be for tomorrow (unless you want to push some @mscheltienne)

**Comment by mscheltienne** [comment]
Works great!

**Comment by drammock** [comment]
@mscheltienne I added a test here that should fail for pyqtgraph `main` and seems like it *should* pass on mne-tools/mne-qt-browser#173 ... only locally it's not working for me. Can you take a look at the test and see if you spot my mistake?

What I'm seeing is that on the first round of `pytest.parametrize` where it's supposed to select annotation type "a" in the annotations bar, it works; and on the second round where it's supposed to select annotation type "b" in the annotation bar it fails.  But running with `pytest --pdb mne/viz/tests/test_raw.py -k overlap`, what I see when it fails is that "b" *is* in fact selected in the annotations bar, and yet annotation span "a" is the missing one (the one that was deleted by the click on the overlap area).

**Comment by mscheltienne** [comment]
I'll have a look tomorrow, thanks!

**Comment by mscheltienne** [comment]
Wrong signal used here: https://github.com/mne-tools/mne-qt-browser/blob/c9127524f896d766818d102f56edfef687b68d10/mne_qt_browser/_pg_figure.py#L2231

Thus, when you do `buttons.setCurrentIndex(active_annot_idx)` it doesn't send the correct signal.
Fixed in https://github.com/mne-tools/mne-qt-browser/pull/173

**Comment by drammock** [comment]
This is going to fail because it's interrelated with https://github.com/mne-tools/mne-qt-browser/pull/173 (they require each other to pass). We can either merge one on faith and then make sure the other passes before merging, or temporarily switch which version is installed by the CIs, see that they pass, then switch back.  @larsoner any preference there?

**Comment by larsoner** [comment]
I usually temporarily switch. That way you can make sure that all exceptions/versions/whatever are handled properly. I would probably have https://github.com/mne-tools/mne-qt-browser/pull/173 use this branch rather than `main` and see if it's green, it should run very quickly. Then if it's green revert the branch change and merge it over there, and then rerun CIs here. (If things are broken in mne-qt-browser for a day or two it's much less painful than if things are broken here, so containing the risk to `mne-qt-browser` repo is probably best.)

**Comment by drammock** [comment]
In the end there were a couple of real bugs here, not dependent on qt-browser. Hopefully CIs will go all green this time and this can go in regardless.

That said, I've already *attempted* to get the mne-qt-browser CIs to use this branch in https://github.com/mne-tools/mne-qt-browser/pull/173/commits/f6dc5d868d3885f4456f9adfd30ae88ffa8c81f3 but I think I did it wrong :/

**Comment by drammock** [comment]
OK!  Only test failures now are the 3 `test_overlapping_annotation_deletion[qt]` ones

https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=25838&view=logs&j=d2de176e-a8da-5d2d-82f1-e561f5072d99&t=f4deb373-ce79-59c7-15db-2653b3e8f79f&l=213

(and same 3 tests failing in Cirrus M1 CI)

**Comment by drammock** [comment]
Soooo confused. I have no idea where to go from here. Prior to https://github.com/mne-tools/mne-python/pull/11760/commits/8a7148259c84e7eaec1d1468d7d1c2ea5c548db1 I was more or less convinced that this was ready to merge, but now...

When actually installing the relevant mne-qt-browser branch into Azure, we go from `3 failed, 64 passed` to now `64 failed, 3 passed`.  But the 3 that pass now *are not* the 3 that failed before (they're all in `test_commands.py`)... the 64 failures now all look like

```
_________ ERROR at setup of test_overlapping_annotation_deletion[qt-0] _________
Forbidden skipped test - Skipped: mne_qt_browser 0.2.0.dev186+g8b2e95e requires PyQt5, API is PySide6
```

The version looks weird (0.2.0.dev+whatever) and probably would resolve if @mscheltienne pushed tags to his mne-qt-browser fork (`git push origin v0.5.1` should do it) BUT the installed version is actually the correct one (the hash 8b2e95e matches the latest hash on https://github.com/mne-tools/mne-qt-browser/pull/173).  I don't know why it's suddenly not getting the right flavor of pyQt. Help?

**Comment by larsoner** [comment]
> BUT the installed version is actually the correct one (the hash 8b2e95e matches the latest hash on mne-tools/mne-qt-browser#173). I don't know why it's suddenly not getting the right flavor of pyQt. Help?

from `git grep "check_version.*mne_qt.*" in MNE-Python I found a conditional in our `conftest` that checks the version:

https://github.com/mne-tools/mne-python/blob/cc1d1825c41144c8c4c3dd1cbb44f8af7bf78e9b/mne/conftest.py#L459-L461

So you'll need to push the tags to the fork... to fix the version numbering... to make `conftest.py` so it doesn't skip tests... so it doesn't cause `pytest-error-for-skips` to raise skip-as-error.

**Comment by mscheltienne** [comment]
🤞

**Comment by larsoner** [comment]
All green here so I'll merge the `mne-qt-browser` PR then we can undo the branch changes here

**Comment by larsoner** [comment]
We will also need to revert CI changes here. That might mean that some tests will need to triage what they do based on mne-qt-browser version

**Comment by larsoner** [comment]
Should be fixed very soon: https://github.com/scipy/scipy/pull/18973

**Comment by larsoner** [comment]
Okay I guess this should be expected but tests fail with the latest mne-qt-browser release 0.5.1:

https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=25873&view=logs&jobId=d2de176e-a8da-5d2d-82f1-e561f5072d99&j=d2de176e-a8da-5d2d-82f1-e561f5072d99&t=f4deb373-ce79-59c7-15db-2653b3e8f79f

We could fix the test here by conditionally `xfail`ing on `mne-qt-browser <= 0.5.1`... but I'm inclined to just cut a 0.5.2 for mne-qt-browser instead. I think the process is automated so we just need to make a GH release over there. And we'll want it for the 1.5 release which we should do soon. WDYT @drammock ?

**Comment by larsoner** [comment]
I thought about it a bit more and didn't want to cut a 0.5.2 release with red CIs, so I added the conditional here. Then I'll go to mne-qt-browser and add the patch for the 1.4 release CIs which should get things green. Then I'll cut 0.5.2 there 😩

**Pull request merged**
