### PR TITLE
[MRG+2] Force ica.n_samples_ to int during serialization

### PR DESCRIPTION
**Pull request by jona-sassenhagen**
#2715
Straight-forward.

### CODE REVIEW

**Comment by jona-sassenhagen** [comment]
@dengemann you deal with the py35 int case for the dict fields in line 1754 onwards, but I thought this approach here is sufficient for the n_samples field.

**Comment by agramfort** [comment]
LGTM

+1 for merge when travis is green

**Comment by jona-sassenhagen** [comment]
I think the Travis errors are gamma_map, ie., unrelated? @Eric89GXL can you check?

**Comment by Eric89GXL** [comment]
Indeed. I restarted the builds. In so doing, I noticed your commit message and LOLed

**Comment by Eric89GXL** [comment]
Thanks @jona-sassenhagen

**Pull request merged**
