### PR TITLE
[ENH] WIP Dipole Model GUI for Teaching/Demo Purposes

### PR DESCRIPTION
**Pull request by alexrockhill**
I thought it would be nice to have a GUI demo of how a dipole inside the brain is translated to electrical and magnetic potentials as read by MEG and EEG at the scalp. I didn't see any way for it to render using Sphinx in an interactive way but it could still be run and I think it would be useful for teaching, demonstrations and/or talks.

@mshamalainen, do you have the code for generating these images still? I could rewrite it but I figured it might be written since these were generated already. 
image

The demo is currently working with an arrow representing the dipole that you can move around, but the sensor space is not yet represented, I can work on it but if the code already exists that would speed things up.

### CODE REVIEW

**Comment by alexrockhill** [comment]
image

**Comment by agramfort** [comment]
@alexrockhill we have been working hard to remove mayavi from our examples.

I would suggest to make a binder app with ipywidgets for such education purpose. You can use make_field_maps https://mne.tools/stable/generated/mne.make_field_map.html to replicate matti's slide.

**Comment by alexrockhill** [comment]
Thanks @agramfort! No resistance from me moving away from mayavi, I just didn't know how to implement it otherwise. Clearly I should have looked at your slides as well! Thanks for the advice :)

**Comment by agramfort** [comment]
see https://github.com/agramfort/mne-web-apps

also @wmvanvliet has some examples with mayavi in the notebooks on binder

our new pyvista backend with panel installed may also work. See https://github.com/mne-tools/mne-python/pull/7056

**Comment by wmvanvliet** [comment]
See https://github.com/wmvanvliet/neuroscience_tutorials for a `Dockerfile` that sets up Mayavi in binder. See https://github.com/wmvanvliet/neuroscience_tutorials/blob/master/mne-intro/adept.ipynb for a notebook that has some Mayavi figures embedded in it.

**Comment by agramfort** [comment]
these tutorials are awesome. You should advertise them more :)

>

**Pull request closed without merging**
