### PR TITLE
MRG, FIX: Backward compat read for vol stc

### PR DESCRIPTION
**Pull request by larsoner**
Fixes reading STCs written with old versions of MNE.

### CODE REVIEW

**Comment by larsoner** [comment]
@poojaprabhu9 on this PR I can run this:
```
import os.path as op
import mne
stc = mne.read_source_estimate('morphed_lgamma_power-stc.h5')
mri_dir = op.join(mne.get_config('SUBJECTS_DIR'), 'fsaverage', 'mri')
lut, _ = mne.read_freesurfer_lut(op.join(mri_dir, 'HCPMMP1ColorLUT.txt'))
labels = mne.read_labels_from_annot('fsaverage', 'HCPMMP1', 'both')
# limit to just the HCPMMP labels with this, or omit it to keep subcortical:
lut = {label.name: lut[label.name] for label in labels}
atlas = op.join(mri_dir, 'HCPMMP1+aseg.mgz')
src = mne.setup_volume_source_space(
    'fsaverage', pos=5., sphere=(0, 0, 0, 90), sphere_units='mm',
    verbose=True)
# This one is better
label_tc = mne.extract_label_time_course(stc, (atlas, lut), src)
stc_label = stc.in_label(1001, atlas, src)
```
And get:
```
>>> stc_label
<VolSourceEstimate  |  15 vertices, subject : fsaverage1, tmin : -1200.0 (ms), tmax : 1200.0 (ms), tstep : 5.0 (ms), data shape : (15, 481)>
>>> label_tc.shape
(362, 481)
```

**Comment by poojaprabhu9** [comment]
That's nice. 
I am not able to read stc file to do this, even after upgrading mne dev version.
Could you please send the HCPMMP1+aseg.mgz, HCPMMP1_combined+aseg.mgz, and LUT files of both.

**Comment by larsoner** [comment]
> I am not able to read stc file to do this, even after upgrading mne dev version.

This PR has not been merged, you'll need to install the `larsoner/stc` branch to see if it fixes things

> Could you please send the HCPMMP1+aseg.mgz, HCPMMP1_combined+aseg.mgz, and LUT files of both.

It would be better if you could try to follow the instructions linked in [this comment](https://github.com/mne-tools/mne-python/pull/7639#issuecomment-625907891) to make sure the instructions actually work

**Comment by poojaprabhu9** [comment]
> It would be better if you could try to follow the instructions linked in this comment to make sure the instructions actually work

I was trying the [code](https://gist.github.com/larsoner/8e664205cd8285ca7c46211403ad12ce)
`    header = """
# Below is the color table for the cortical labels of the seg volume
# created by mri_aparc2aseg in which the aseg cortex label is replaced
# by the labels in the %s aparc.
#No.    Label Name:                         R   G   B   A
""" % (parc,)
I think there is something missing in this line.

**Pull request merged**
