### PR TITLE
FIX: paintEvent/resizeEvent & update

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
It seems that https://github.com/mne-tools/mne-python/pull/8852 was not enough. I'll investigate the issue thoroughly in here and come back to https://github.com/mne-tools/mne-python/pull/9010 afterwards.

Progress:
- [x] Fix "minimized" issue
- [x] Fix update issue

ToDo:
- [x] Touch example as baseline
- [x] Revert `qt_disable_paint`
- [x] Investigate `set_3d_view`

Related to https://github.com/mne-tools/mne-python/pull/9010#issuecomment-805002328, https://github.com/mne-tools/mne-python/pull/8828

### CODE REVIEW

**Comment by larsoner** [comment]
Also can you check that `tutorials/sample-datasets/plot_phantom_4DBTi.py` plots correctly in this PR (make some change to it)? On my system the first plot looks like:

Screenshot from 2021-04-19 08-55-59

And if I click-drag anywhere it gets fixed:

Screenshot from 2021-04-19 08-56-03

So it seems to just be some update problem here, too.

**Comment by GuillaumeFavelier** [comment]
I'll add it to the list

**Comment by GuillaumeFavelier** [comment]
The 'quarter' rendering issue is reproduced:

https://27421-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/source-modeling/plot_source_alignment.html#sphx-glr-auto-tutorials-source-modeling-plot-source-alignment-py

**Comment by larsoner** [comment]
Can you reproduce locally with `PATTERN=source_alignment make html_dev-pattern`? That way you won't have to wait for CircleCI (and use up its cycles).

Some hint at the problem is perhaps that the plain `plot_alignment` calls are bad, but the one that changes the view looks good. So somehow that view-setting call fixes things.

**Comment by GuillaumeFavelier** [comment]
I tried and I do not reproduce with my usual desktop manager. A similar environment is probably building on a TTY with a running xvfb though.

**Comment by GuillaumeFavelier** [comment]
`qt_disable_paint` is definitely related to the issue somehow:

https://27430-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/source-modeling/plot_source_alignment.html?highlight=alignment

**Comment by GuillaumeFavelier** [comment]
Apparently fixed with Update&Process :

https://27438-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/source-modeling/plot_source_alignment.html#sphx-glr-auto-tutorials-source-modeling-plot-source-alignment-py

**Comment by larsoner** [comment]
@GuillaumeFavelier we are also seeing some [problems on CircleCI for main](https://app.circleci.com/pipelines/github/mne-tools/mne-python/7888/workflows/26ebfff7-4b79-426c-9c8a-786e954ce2e6/jobs/27434):
```
Traceback (most recent call last):
  File "/home/circleci/.local/lib/python3.8/site-packages/sphinx_gallery/scrapers.py", line 333, in save_figures
    rst = scraper(block, block_vars, gallery_conf)
  File "/home/circleci/.local/lib/python3.8/site-packages/pyvista/utilities/sphinx_gallery.py", line 49, in __call__
    plotter.screenshot(fname)
  File "/home/circleci/.local/lib/python3.8/site-packages/pyvista/plotting/plotting.py", line 3122, in screenshot
    return self._save_image(self.image, filename, return_img)
  File "/home/circleci/.local/lib/python3.8/site-packages/vtkmodules/qt/QVTKRenderWindowInteractor.py", line 335, in __getattr__
    raise AttributeError(self.__class__.__name__ +
AttributeError: BackgroundPlotter has no attribute named image
```
Is this a PyVista bug with their scraper?

**Comment by larsoner** [comment]
So far these both look good at least!

https://27452-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/source-modeling/plot_source_alignment.html
https://27452-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/sample-datasets/plot_phantom_4DBTi.html

**Comment by GuillaumeFavelier** [comment]
> Is this a PyVista bug with their scraper?

Hm... probably :thinking:

**Comment by GuillaumeFavelier** [comment]
I'm still trying to figure out where this comes from. AFAIK, `self.image` is a property of `BasePlotter`, I don't understand why the scraper complains.

**Comment by larsoner** [comment]
Okay well I'll merge this once CIs come back happy, feel free to open a new PR for that error

**Comment by GuillaumeFavelier** [comment]
Will do

**Comment by larsoner** [comment]
Thanks @GuillaumeFavelier !

**Pull request merged**
