### PR TITLE
FIX: fix sphere radius in topomap

### PR DESCRIPTION
**Pull request by mmagnuski**
@larsoner
That was the tiny bug that caused sphere not being of requested radius. The `sphere` variable was not passed to `_find_topomap_coords`.

Now it looks a bit better:

but the extrapolation is still not correct. I will check in a while, maybethe `sphere` is not passed also to some extrapolation functions?

### TODO:
- [x] change / fix previous border test
- [x] fix extrapolation

### CODE REVIEW

**Comment by larsoner** [comment]
Nice catch!

**Comment by mmagnuski** [comment]
Hm, the extrapolation is not directly related to `sphere` - it was just not originally planned with such small examples (5 channels) in mind. It still may be worth improving - I will check that later.

**Comment by mmagnuski** [comment]
Ok, small changes to the head circle extrapolation fix this:
* two times more extrapolation points on the head circle
* extrapolation points are at 1.1 head radius, not exactly on the head (I think it makes sense because the extrapolation points should be outside of the head aperture)

now it looks like this:
image

**Comment by larsoner** [comment]
Much nicer!

Once you're happy and think everything is working correctly, can you push a commit with `[circle full]` so that we can inspect all the examples? I don't expect them to change much but we should check

**Comment by mmagnuski** [comment]
@ yes, definitelly!
The extrapolation points (green) are now placed like this:

**Comment by mmagnuski** [comment]
@larsoner Done. Everything looks good. Probably running all examples was not necessary as `extrapolate='head'` is rarely used. There is one example for sure that uses this option, here are the changes:

master


PR:

**Comment by mmagnuski** [comment]
BTW - I think the [topomap example](https://17698-1301584-gh.circle-artifacts.com/0/dev/auto_examples/visualization/plot_evoked_topomap.html#sphx-glr-auto-examples-visualization-plot-evoked-topomap-py) could be extended a bit (with using `mne.viz.plot_topomap` directly, controlling `sphere` and `border` for example) and might be a good fit for a tutorial. It's already more verbose than many examples, so tutorials might be a better fit.

**Comment by larsoner** [comment]
> BTW - I think the topomap example could be extended a bit

Please do turn it into a tutorial. Maybe a new `visualization` sub-folder? WDYT @drammock ? I have a feeling we'll have enough content on how to make nice visualizations that this could be useful. For example the publication figure example could live there, too.

**Comment by larsoner** [comment]
Thanks @mmagnuski !

**Comment by mmagnuski** [comment]
Thanks @larsoner and @agramfort 🚀 (I will try to get to the tutorial stuff soon)

**Pull request merged**
