### PR TITLE
ENH : add units parameter to read_raw_edf in case units is missing from the file

### PR DESCRIPTION
**Pull request by agramfort**
related to https://github.com/mne-tools/mne-bids/pull/1045 and https://github.com/mne-tools/mne-bids/issues/1044

now with the data from ds003775 you can just do:

`raw = mne.io.read_raw_edf(bp, units='uV')`

and in mne-bids

`raw = read_raw_bids(bp, extra_params={'units': 'uV'})`

what do you think @sappelhoff @hoechenberger ?

### CODE REVIEW

**Comment by hoechenberger** [comment]
@agramfort Looks good, but I'd call the parameter `unit` (singular), since it's just one unit (i.e., the same one) for all channels in the most common scenario (user passes a string). WDYT?

An alternative approach could also be to introduce a  parameter `scaling` instead? And accept an an int or float by which we'll multiply the input data? I feel this would fit better into the existing MNE-Python API, but it's slightly less convenient for users (?)

What bugs me a little bit about calling the parameter `unit(s)` is that we **don't** actually perform a unit conversion, but simply adjust the scaling factor. Hence the idea of having `scaling` instead.

**Comment by sappelhoff** [comment]
LGTM!

I like "units" (plural), because one can also pass a dict of units (one for each channel).
Regarding "scaling(s)" --> true, we are not doing unit conversions ... but won't `get_scalings` warn/error when a user passes a unit that does not correspond to the unit the channel type is in? 

Still, I'd be fine with bot units and scalings.

**Comment by hoechenberger** [comment]
> I like "units" (plural), because one can also pass a dict of units (one for each channel).

But I believe we usually follow the convention that variable names for dictionaries are singular, while names for lists are plural, no?

I'm not vetoing "units", just thinking out loud.

**Comment by agramfort** [comment]
@hoechenberger do a git grep in the repo with units. You will see that we call units many parameters that are dict of units for the different channels. I think this naming is consistent with mne

**Comment by hoechenberger** [comment]
Thanks @agramfort!

**Comment by hoechenberger** [comment]
Oh, I merged without requesting a test.

@agramfort Care to add a small test case in a followup PR?

**Pull request merged**
