### PR TITLE
MRG: Add verbose decorator to cross_val_multiscore()

### PR DESCRIPTION
**Pull request by hoechenberger**

### CODE REVIEW

**Comment by hoechenberger** [comment]
CI error is unrelated

I've remove some ancient logging code that simply used `print()`
At first I tried replacing it with `logger.info()` but I realized it only messed up the screen when running with `n_jobs > 1`. The output it provided wasn't super useful either: basically, run time and score for each CV fold. So I decided to remove this entirely.

**Comment by agramfort** [comment]
@hoechenberger can you see who wrote these prints historically and check if it's ok to remove them?

**Comment by hoechenberger** [comment]
@agramfort The prints were added by @kingjr about 5 years ago during a refactoring

I had actually never seen them in my output, as the function defaulted to `verbose=0` and the prints were only triggered for `verbose > 1`! I doubt anyone ever saw them … except for @kingjr? :D

**Comment by hoechenberger** [comment]
… if you're worried sb might still be needing those, I could add them back as `logger.debug`? But it feels a bit unnecessary to me personally! WDYT?

**Comment by agramfort** [comment]
@kingjr any objection to kill them?

**Comment by kingjr** [comment]
No objection :)

**Pull request merged**
