### PR TITLE
FIX: separate MPL canvas

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR fixes the issue of `stc.plot` whith `show_traces='separate'`.

### CODE REVIEW

**Review by hoechenberger — APPROVED** [review]

**Review by agramfort — APPROVED** [review]
Lol 😂

**Comment by larsoner** [comment]
So apparently we have some coverage lapse :)

Can you add a test that would have caught this?

**Comment by hoechenberger** [comment]
> Lol 😂

Yes that's what **we** thought ;)

**Comment by larsoner** [comment]
I'd still like a test to prevent this from happening in the future...

**Comment by GuillaumeFavelier** [comment]
I'll add one!

**Pull request merged**
