### PR TITLE
MRG: show channel name on mouse hover

### LINKED ISSUE #4673: ENH: show channel in plot_evoked_topo()
In the `plot_evoked_topo` display, the status bar could show which channel you are hovering over. Currently if you want to zoom in to e.g. MEG 1711 you probably will have no idea where it is (unless you are intimately familiar with the sensor layout).

### PR DESCRIPTION
**Pull request by jjnurminen**
Shows the channel name in the status bar for topo plots. 
Closes #4673

### CODE REVIEW

**Comment by jjnurminen** [comment]
Looks like this:

image

**Comment by dengemann** [comment]
Nice!

**Comment by jasmainak** [comment]
Yes! awesome feature

**Comment by jjnurminen** [comment]
Seems to work also for multiaxis plots also, I tested with the `plot_topo_customized` example.

I'm not sure how to write a test for this. I checked matplotlib sources and there seems to be no way to get the current status message (at least without writing backend specific code). Any suggestions, or we go without a test?

**Comment by larsoner** [comment]
You could directly call `ax.format_coord(...)` and check that the output is correct for some known `x, y` position. Then the testing assumption is only that `mpl` correctly passes `x, y` coords and uses the returned string properly

**Comment by larsoner** [comment]
... and perhaps we should decrease the line width of those plots to 1.0 (if it's not already) while we're making this more usable, WDYT?

**Comment by jjnurminen** [comment]
>You could directly call ax.format_coord(...) and check that the output is correct for some known x, y

Ok, I'll do that.

>and perhaps we should decrease the line width of those plots to 1.0

Well the lines do look a bit thick, so +1 from me.

**Comment by larsoner** [comment]
> Well the lines do look a bit thick, so +1 from me.

Feel free to tweak to taste and paste a CircleCI link, maybe 0.5 would look best with these tiny plots. Hopefully we won't get too many bike-shedders with the changes :)

**Comment by jjnurminen** [comment]
Added tests.
For the 'unified' single axis plot, I'm testing the callback only for a single channel with known coordinates. I tried to loop over the layout and check all channels, but the layout that `_iter_topography` internally has  is subtly different from the layout loaded in `test_topo.py`, so it didn't work. I was too lazy to figure out where and how the layout gets modified in the call chain.

**Comment by agramfort** [comment]
ready for testing/review?

**Comment by jjnurminen** [comment]
The latest commit drops topo plot linewidth to .5

>ready for testing/review?

Yep please go ahead :)

**Comment by agramfort** [comment]
works like a charm.

please udpate what's new and let's merge when CIs are happy.

thx @jjnurminen

**Comment by larsoner** [comment]
Thanks @jjnurminen

**Pull request merged**
