### PR TITLE
MRG: Add scalarbar() and text3d() to pyvista 3d backend

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
Fixes part of #6518.

This PR adds the missing `scalarbar()` function to the pyvista 3d backend.

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
This PR adds `text3d()` too now.

**Comment by agramfort** [comment]
How does it look?

**Comment by GuillaumeFavelier** [comment]
Using the `examples/connectivity/plot_sensor_connectivity.py`:

image

**Comment by GuillaumeFavelier** [comment]
Visually we can observe rectangular patches around the labels which are not present with the mayavi backend.

**Comment by agramfort** [comment]
Looks good

**Comment by GuillaumeFavelier** [comment]
It's fixed now:

image

**Comment by GuillaumeFavelier** [comment]
This one is ready to be merged. What do you think @agramfort , @larsoner ?

**Comment by agramfort** [comment]
thx @GuillaumeFavelier

**Pull request merged**
