### PR TITLE
MRG, FIX: Fix interaction with one time in macOS

### LINKED ISSUE #7544: BUG: PyVista segfault on macOS with a single time point
Plotting a STC with PyVista that only has a single time point with `time_viewer=True`, then clicking anywhere in the window leads to a segfault:
<details>
<summary>MWE</summary>

```
import os.path as op
import mne

data_path = mne.datasets.sample.data_path()
sample_dir = op.join(data_path, 'MEG', 'sample')
subjects_dir = op.join(data_path, 'subjects')
inv = mne.minimum_norm.read_inverse_operator(op.join(
    sample_dir, 'sample_audvis-meg-eeg-oct-6-meg-eeg-inv.fif'))
evoked = mne.read_evokeds(op.join(sample_dir, 'sample_audvis-ave.fif'))[0]
evoked.apply_baseline((None, 0)).crop(0.1, 0.1)
stc = mne.minimum_norm.apply_inverse(
    evoked, inv, method='dSPM', verbose='debug', pick_ori=None)  # 'vector')

with mne.viz.use_3d_backend('pyvista'):
    brain = stc.plot(subjects_dir=subjects_dir)
```

</details>

```
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x00007fff6e70c7fa __pthread_kill + 10
1   libsystem_c.dylib             	0x00007fff6e6233a2 raise + 26
2   libsystem_platform.dylib      	0x00007fff6e7be42d _sigtramp + 29
3   ???                           	000000000000000000 0 + 0
4   libvtkInteraction-8.1.1.dylib 	0x000000063fec1469 vtkSliderRepresentation2D::StartWidgetInteraction(double*) + 313
5   libvtkInteraction-8.1.1.dylib 	0x000000063fec5ac7 vtkSliderWidget::SelectAction(vtkAbstractWidget*) + 135
6   libvtkCommon-8.1.1.dylib      	0x000000062c0db281 vtkCallbackCommand::Execute(vtkObject*, unsigned long, void*) + 33
7   libvtkCommon-8.1.1.dylib      	0x000000062c245dfc vtkSubjectHelper::InvokeEvent(unsigned long, void*, vtkObject*) + 1004
8   libvtkRenderingKitPython37D-8.1.1.dylib	0x000000063ab149a8 PyvtkRenderWindowInteractor_LeftButtonPressEvent(_object*, _object*) + 136
9   python                        	0x000000010ed0c18e _PyMethodDef_RawFastCallKeywords + 350
10  python                        	0x000000010ee48e42 call_function + 306
11  python                        	0x000000010ee46aec _PyEval_EvalFrameDefault + 46092
12  python                        	0x000000010ed0b8d5 function_code_fastcall + 117
13  python                        	0x000000010ed0ece2 method_call + 130
14  python                        	0x000000010ed0c752 PyObject_Call + 130
15  sip.cpython-37m-darwin.so     	0x0000000121747d40 sip_api_call_procedure_method + 208
16  QtOpenGL.so                   	0x000000064103c1c7 sipQGLWidget::mousePressEvent(QMouseEvent*) + 103
17  QtWidgets                     	0x000000012265d058 QWidget::event(QEvent*) + 424
18  QtOpenGL.so                   	0x000000064103b9a0 sipQGLWidget::event(QEvent*) + 192
...
```

Not sure why this happens, maybe something about the time viewer bounds. I noticed on Linux before the hiding code that they ended up negative/backward somehow when there was a single time point. My guess is that we need to be more careful about instantiation in the single time point case.

cc @GuillaumeFavelier in case you can look at the code and immediately see the problem

### PR DESCRIPTION
**Pull request by larsoner**
Closes #7544.

@GuillaumeFavelier can you look?

### CODE REVIEW

**Comment by hoechenberger** [comment]
Working for me! A colleague of mine stumbled upon this one yesterday too, so it's actually a relevant corner case.

Any chance you/we could add a test for this? For me the crash only occurs once I interact with the window, so idk how to test this…

**Comment by larsoner** [comment]
> Any chance you/we could add a test for this? For me the crash only occurs once I interact with the window, so idk how to test this…

No, I'm not sure how to reliably test this sort of thing

**Comment by hoechenberger** [comment]
> No, I'm not sure how to reliably test this sort of thing

Bummer! I'd say, then, let's go ahead and merge :)

**Comment by larsoner** [comment]
Backported

**Pull request merged**
