### PR TITLE
MRG, BUG: Fix add_reference_channels (more)

### PR DESCRIPTION
**Pull request by larsoner**
@nbara feel free to try this to see if it fixes your problem

### CODE REVIEW

**Review by nbara — APPROVED** [review]
That solves my issue, thanks!

**Review by hoechenberger — APPROVED** [review]

**Comment by hoechenberger** [comment]
@larsoner Could you add a changelog entry please?

**Comment by larsoner** [comment]
There is already one about this fix, this just (hopefully) completes it. I considered appending the PR number but decided not to bother with it, but I can do it for the sake of completeness if needed

**Comment by hoechenberger** [comment]
> There is already one about this fix, this just (hopefully) completes it. I considered appending the PR number but decided not to bother with it, but I can do it for the sake of completeness if needed

That would be cool 👍 Otherwise LGTM

**Pull request merged**
