### PR TITLE
TST: Check Travis

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
I investigate https://github.com/mne-tools/mne-python/pull/7620#issuecomment-617100952 in this PR

### CODE REVIEW

**Comment by larsoner** [comment]
@GuillaumeFavelier also #7674 should help, it should I think make the test show up as a failure rather than killing the whole test suite with a segfault. At least that's what I've seen happen when `pytest-xdist` has been used in SciPy

**Comment by GuillaumeFavelier** [comment]
I'll add it in the next run, thanks for the tip :+1:

**Comment by GuillaumeFavelier** [comment]
For reference:

https://github.com/mne-tools/mne-python/pull/7674#issuecomment-619207074

**Comment by larsoner** [comment]
Things seem more stable now so I'll go ahead and close this

**Pull request closed without merging**
