### PR TITLE
FIX: random pca solver in sklearn v.18

### LINKED ISSUE #3582: RandomizedPCA deprecation
I get this deprecation warning:
```
DeprecationWarning: Class RandomizedPCA is deprecated; RandomizedPCA was deprecated in 0.18 and will be removed in 0.20. Use PCA(svd_solver='randomized') instead. The new implementation DOES NOT store whiten components_. Apply transform to get them.
```
It would be good to make this change. I can do it unless you're motivated @kingjr

### PR DESCRIPTION
**Pull request by kingjr**
closes #3582

### CODE REVIEW

**Comment by Eric89GXL** [comment]
LGTM, +1 for merge once CIs are happy. The previously-failing test passes here now.

In case you're up for another, I still have this warning:
```
Test TimeDecoding ... /home/larsoner/.local/lib/python2.7/site-packages/sklearn/cross_validation.py:43: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
```
So somewhere we're still using an old module. But I can also make a separate issue for that.

**Comment by kingjr** [comment]
ok, I'm going to stop now, I need to work a bit

**Comment by kingjr** [comment]
mmmh, what is the error?

**Comment by Eric89GXL** [comment]
All better locally and on the CIs, thanks for the quick fix @kingjr 

It says there is a coverage drop but I find it hard to believe for this PR. Looking at the actual diff on CodeCov I don't see it.

**Pull request merged**
