### PR TITLE
MRG, FIX: Fix encoding bug

### LINKED ISSUE #7313: Can't load raw nirx data, due to encoding issue
When I try to load NirX data with the `mne.io.read_raw_nirx` function, I'm facing encoding issue with the `.hdr` file. For now, I'm solving this manually by converting the `.hdr` to `utf8` with a simple text file editor like `geany`.

#### MWE

I recorded a test dataset (in a `test_github` folder), which is composed of the following files :
```bash
./NIRS-2020-02-13_001.evt  --  inode/x-empty; charset=binary
./NIRS-2020-02-13_001.set  --  text/plain; charset=us-ascii
./NIRS-2020-02-13_001.wl1  --  text/plain; charset=us-ascii
./Standard_probeInfo.mat  --  application/octet-stream; charset=binary
./NIRS-2020-02-13_001.dat  --  text/plain; charset=us-ascii
./NIRS-2020-02-13_001.tpl  --  text/plain; charset=us-ascii
./NIRS-2020-02-13_001_config.txt  --  text/plain; charset=us-ascii
./NIRS-2020-02-13_001.wl2  --  text/plain; charset=us-ascii
./NIRS-2020-02-13_001.hdr  --  application/x-wine-extension-ini; charset=iso-8859-1
./NIRS-2020-02-13_001.inf  --  text/plain; charset=us-ascii
./NIRS-2020-02-13_001.avg  --  application/octet-stream; charset=binary
```
These informations were obtained with the following command (linux) : 
```bash
for f in `find | egrep -v Eliminate`; do echo "$f" ' -- ' `file -bi "$f"` ; done
```
On python side, here is the code that I intend to use to load the data. I'm using the last version of MNE (0.20.dev0).
```python
#!/usr/bin/env python3
import os
import mne

path = os.sep.join([os.getcwd(), 'test_github'])
raw_intensity = mne.io.read_raw_nirx(path, verbose=True).load_data()
```
As mentioned [here](https://mne.tools/dev/auto_tutorials/preprocessing/plot_70_fnirs_processing.html?highlight=nirs), I should obtain this kind of output :
```python
Loading /home/circleci/mne_data/MNE-fNIRS-motor-data/Participant-1
Reading 0 ... 23238  =      0.000 ...  2974.464 secs...
```
But actually, the `read_raw_nirx` command raises the following Traceback :
```python


Loading /home/bvaler01/Documents/programmes/NBack/test_github
Traceback (most recent call last):
  File "processing_github.py", line 6, in <module>
    raw_intensity = mne.io.read_raw_nirx(path, verbose=True).load_data()
  File "/home/bvaler01/.local/lib/python3.7/site-packages/mne/io/nirx/nirx.py", line 39, in read_raw_nirx
    return RawNIRX(fname, preload, verbose)
  File "</home/bvaler01/.local/lib/python3.7/site-packages/mne/externals/decorator.py:decorator-gen-198>", line 2, in __init__
  File "/home/bvaler01/.local/lib/python3.7/site-packages/mne/utils/_logging.py", line 89, in wrapper
    return function(*args, **kwargs)
  File "/home/bvaler01/.local/lib/python3.7/site-packages/mne/io/nirx/nirx.py", line 113, in __init__
    hdr_str = f.read()
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 62: invalid continuation byte
```
The test dataset is available [here](http://s000.tinyupload.com/download.php?file_id=15443728717331148895&t=1544372871733114889579038) (`.zip`). It is a ten-seconds recording, from `NirStar 15.2`. It should contain noise only (headless record).

### PR DESCRIPTION
**Pull request by larsoner**
Closes #7313

No need for `latest.inc` update because `read_raw_nirx` is a new function in 0.20

### CODE REVIEW

**Comment by cbrnr** [comment]
Why `codecs.open` and not just plain old `open(..., encoding='latin1')`?

**Comment by cbrnr** [comment]
https://docs.python.org/3.8/library/codecs.html says that `open` is recommended: "While the builtin open() and the associated io module are the recommended approach for working with encoded text files, this module provides additional utility functions and classes that allow the use of a wider range of codecs when working with binary files."

**Comment by larsoner** [comment]
Just how I did it last time I had this problem, probably because of Python 2.7 or something. I'll switch to open

**Comment by cbrnr** [comment]
TBH I wouldn't define a new function just for setting this one arg (`mode='r'` is the default).

**Comment by larsoner** [comment]
> TBH I wouldn't define a new function just for setting this one arg (mode='r' is the default).

There is some uncertainty about whether or not `latin-1` is actually correct, so it is a bit of future proofing in the sense that if we need to use `chardet` or something similar to figure out the encoding we can do it in hopefully one place instead of many. But even without it this seems like a six of one half dozen of the other situation...

**Comment by drammock** [comment]
tx @larsoner

**Pull request merged**
