### PR TITLE
RFC: Include the number of dropped epochs in the `Epochs` repr

### PR DESCRIPTION
**Pull request by hoechenberger**
For quick diagnostic purposes and sanity checks, I find it helpful being able to quickly see how many epochs were dropped. The changes in this PR include the number of dropped epochs in the string and HTML `repr`.

Before epochs were dropped:

```python
<Epochs |  86 events (good & bad; none dropped), -0.199795 – 0.499488 s, baseline -0.199795 – 0 s, ~3.2 MB, data not loaded,
 '1': 20
 '2': 20
 '3': 20
 '4': 18
 '5': 4
 '32': 4>
```

After epochs were dropped:
```python
<Epochs |  85 events (good & bad; 1 dropped), -0.199795 – 0.499488 s, baseline -0.199795 – 0 s, ~3.2 MB, data not loaded,
 '1': 20
 '2': 19
 '3': 20
 '4': 18
 '5': 4
 '32': 4>
```

After preloading:
```python
<Epochs |  85 events (all good; 1 dropped), -0.199795 – 0.499488 s, baseline -0.199795 – 0 s, ~105.9 MB, data loaded,
 '1': 20
 '2': 19
 '3': 20
 '4': 18
 '5': 4
 '32': 4>
```

HTML rep:
Screenshot 2024-04-17 at 21 31 22

MWE:
```python
# %%
import mne

sample_dir = mne.datasets.sample.data_path()
sample_fname = sample_dir / 'MEG' / 'sample' / 'sample_audvis_raw.fif'
raw = mne.io.read_raw_fif(sample_fname)
raw.crop(tmax=60)
events = mne.find_events(raw, stim_channel='STI 014')

# %%
epochs = mne.Epochs(raw, events=events)
print(repr(epochs))
epochs

# %%
epochs.drop(0)
print(repr(epochs))
epochs

# %%
epochs.load_data()
print(repr(epochs))
epochs
```

### CODE REVIEW

**Comment by cbrnr** [comment]
In general, I'm not a huge fan of excessive reprs, but since the `Epochs` repr was already pretty long, it's probably fine to add this.

On a slightly related note, your example reminds me that the concepts of good, bad, and dropped epochs can be confusing, especially since these change after loading. I'm not sure including even more information in the repr helps to clarify the situation.

**Comment by mscheltienne** [comment]
+1 for this chanbge, but I agree with @cbrnr that the concepts of good/bad/dropped can be unclear. In your example, the `good & bad` and `all good` strings are confusing. Maybe `good only` would be a bit clearer after preload.

**Comment by hoechenberger** [comment]
The notion of good and bad has been a source of confusion for all users of MNE I've ever encountered. I'd say it's out of scope of this PR to addresses this.

I'm inclined to revert my change to the repr and only keep it for the HTML repr. would that be okay with you, @mscheltienne?

**Comment by mscheltienne** [comment]
I would keep it for both repr, I think this change is beneficial in both cases.

**Comment by cbrnr** [comment]
Why do we need `"good & bad"` in the first place? Isn't this already reflected by `"data not loaded"`? I'd remove this and only show how many dropped epochs there are (if there aren't any, I would not include it). So:

```
<Epochs |  86 events, -0.199795 – 0.499488 s, baseline -0.199795 – 0 s, ~3.2 MB, data not loaded,
 '1': 20
 '2': 20
 '3': 20
 '4': 18
 '5': 4
 '32': 4>
```

```
<Epochs |  85 events (1 dropped), -0.199795 – 0.499488 s, baseline -0.199795 – 0 s, ~3.2 MB, data not loaded,
 '1': 20
 '2': 19
 '3': 20
 '4': 18
 '5': 4
 '32': 4>
```

```
<Epochs |  85 events (1 dropped), -0.199795 – 0.499488 s, baseline -0.199795 – 0 s, ~105.9 MB, data loaded,
 '1': 20
 '2': 19
 '3': 20
 '4': 18
 '5': 4
 '32': 4>
```

**Comment by hoechenberger** [comment]
I like @cbrnr's suggestion

**Comment by cbrnr** [comment]
While you are at it, could you change the following minor things in the standard repr (to make them shorter):

- There are two spaces after the `|`, there should be only one.
- Times should be rounded to two decimal places.
- There should be no spaces around `–`.

This would look like this:

```
<Epochs | 85 events (1 dropped), -0.20–0.50 s, baseline -0.20–0 s, ~105.9 MB, data loaded,
 '1': 20
 '2': 19
 '3': 20
 '4': 18
 '5': 4
 '32': 4>
```

Maybe we should even omit trailing zeros, i.e. `-0.2–0.5 s, baseline -0.2–0 s`.

**Comment by hoechenberger** [comment]
> There should be no spaces around –.

no, this will make a negative upper bound unreadable.

**Comment by hoechenberger** [comment]
> Maybe we should even omit trailing zeros, i.e. -0.2–0.5 s (baseline -0.2–0 s).

hard disagree, this inconsistency in precision hurts my eyes.

**Comment by hoechenberger** [comment]
and really i don't want to touch any of this in this PR @cbrnr

**Comment by cbrnr** [comment]
> hard disagree, this inconsistency in precision hurts my eyes.

But it doesn't bother you in the current string? We show `0` and not `0.00` or even `0.000000`...

**Comment by hoechenberger** [comment]
> > > hard disagree, this inconsistency in precision hurts my eyes.
> > 
> > 
> > 
> > But it doesn't bother you in the current string? We show `0` and not `0.00` or even `0.000000`...
> > 
> > 
> 
> yep it does bother me actually 😅

then again I might be inclined to cut the 0 as a special case some slack 😅😅

**Comment by cbrnr** [comment]
See #12550 @hoechenberger.

**Comment by hoechenberger** [comment]
Thanks @cbrnr!

**Pull request closed without merging**
