### PR TITLE
FIX: Force int type

### LINKED ISSUE #4843: Plotting ica properties returns ValueError (dtype 64)
I'm trying to follow the Artifact Correction with ICA example with Python 2.7.14 under Spyder in 64-bit mode (conda version 4.3.29). Everything works as expected until:

**ica.plot_properties(raw, picks=0)**

which leads to an ValueError.

>   File "<ipython-input-33-e9d421a0f5d6>", line 1, in <module>
>     ica.plot_properties(raw,picks=picks)
> 
>   File "...\Anaconda3\envs\py27\lib\site-packages\mne\preprocessing\ica.py", line 1435, in plot_properties
>     figsize=figsize, show=show)
> 
>   File "...\Anaconda3\envs\py27\lib\site-packages\mne\viz\ica.py", line 241, in plot_ica_properties
>     psds, freqs = psd_multitaper(epochs_src, picks=picks, **psd_args)
> 
>   File "<string>", line 2, in psd_multitaper
> 
>   File "...\Anaconda3\envs\py27\lib\site-packages\mne\utils.py", line 728, in verbose
>     return function(*args, **kwargs)
> 
>   File "...\Anaconda3\envs\py27\lib\site-packages\mne\time_frequency\psd.py", line 292, in psd_multitaper
>     n_jobs=n_jobs, verbose=verbose)
> 
>   File "<string>", line 2, in psd_array_multitaper
> 
>   File "...\Anaconda3\envs\py27\lib\site-packages\mne\utils.py", line 728, in verbose
>     return function(*args, **kwargs)
> 
>   File "...\Anaconda3\envs\py27\lib\site-packages\mne\time_frequency\multitaper.py", line 521, in psd_array_multitaper
>     low_bias=low_bias)
> 
>   File "...\Anaconda3\envs\py27\lib\site-packages\mne\time_frequency\multitaper.py", line 201, in dpss_windows
>     select_range=(N - Kmax, N - 1))
> 
>   File "...\Anaconda3\envs\py27\lib\site-packages\scipy\linalg\decomp.py", line 847, in eigvals_banded
>     return eig_banded(a_band, lower=lower, eigvals_only=1,
> 
>   File "...\Anaconda3\envs\py27\lib\site-packages\scipy\linalg\decomp.py", line 587, in eig_banded
>     raise ValueError('expected two-dimensional array')
> 
>   File "...\Anaconda3\envs\py27\lib\site-packages\scipy\linalg\decomp.py", line 478, in _check_select
>     if sr.dtype.char.lower() not in 'lih':
> 
> **ValueError: when using select="i", select_range must contain integers, got dtype int64**

I'm quite new to Python, but I guess it has something to do with using the 64-bit version? I tried it with 32-bit mode, but then I ended up with a MemoryError. Does anyone have a suggestion on how to resolve this problem?

### PR DESCRIPTION
**Pull request by larsoner**
Closes #4843

### CODE REVIEW

**Comment by larsoner** [comment]
Upstream fix is https://github.com/scipy/scipy/pull/8608 but it will take a while to land

**Comment by agramfort** [comment]
@nrosjat can you confirm this fixes your pb?

**Comment by larsoner** [comment]
@nrosjat can you try this one? If not, what change fixes it?

**Comment by nrosjat** [comment]
@larsoner for me it's working when np.int64 is changed to np.int32:

`Kmax = np.int32(operator.index(Kmax))`
`N = np.int32(operator.index(N))`

**Comment by agramfort** [comment]
how come this is not caught up by appveyor?

**Comment by larsoner** [comment]
Not sure. We only run 2.7 64-bit on AppVeyor. However, this is what @Davi93 is running so that doesn't explain it. Maybe the actual OS version matters?

In any case, I've changed it to `np.int32` so this should fix it. Can you confirm @nrosjat ?

**Comment by nrosjat** [comment]
Yes, this one is working for me.

**Pull request merged**
