### PR TITLE
[MRG] Use latin-1 encoding for some EDF header fields

### LINKED ISSUE #5943: Loading BDF file fails on UTF-8 decoding error
#### Describe the bug
Please provide a clear and concise description of the bug.

The header of my BDF file has a patient with a name that contains the character `è`, which causes line 600 of `io/edf/edf.py` to fail with error:

```python
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 4: invalid continuation byte
```

#### Steps and/or code to reproduce

Loading any `.bdf` file with that accent causes the issue. The issue occurs with the most recent pip package and the current head of master.

#### Additional information

We temporarily solved our issue by changing the line to:

```python
# patient ID
pid = fid.read(80).decode(errors='ignore')
```

However, it may be worthwhile to replace the offending character with a space or something harmless.

### PR DESCRIPTION
**Pull request by cbrnr**
Fixes #5943.

### CODE REVIEW

**Comment by agramfort** [comment]
can you please update what's new?

**Comment by cbrnr** [comment]
Done

**Comment by agramfort** [comment]
thx @cbrnr

**Comment by Lx37** [comment]
Hi,
I get the exact same issue/solving as #5943 with EDF files, (edf.py line 537) using 
 `.decode('latin-1')` on `meas_id['recording_id']`.
(The dates of the EDF files are in french with accents)
best

**Comment by agramfort** [comment]
@Lx37 do you have the pb with latest 0.20 version?

**Comment by Lx37** [comment]
Yep,
(installed from pip)
https://github.com/mne-tools/mne-python/blob/maint/0.20/mne/io/edf/edf.py
line 537, I change 
        meas_id['recording_id'] = fid.read(80).decode().strip(' \x00')
to 
        meas_id['recording_id'] = fid.read(80).decode('latin-1').strip(' \x00')
and now the recording ID (french dates in my case, with accents..) are correctly loaded

**Comment by agramfort** [comment]
can you send us a PR?

**Comment by Lx37** [comment]
ok, I tried to #7600 but only on master (0.21.dev0)

**Pull request merged**
