### PR TITLE
BUG: Fix constrained layout in psd.plot

### LINKED ISSUE #12090: follow up tweaks after adopting constrained layout
```
spectrum = epochs["visual/right"].compute_psd()
spectrum.plot_topomap()
```
in [this tutorial](https://output.circle-artifacts.com/output/job/02879e35-b188-4d6f-aa04-a7e396737a39/artifacts/0/html/auto_tutorials/epochs/20_visualize_epochs.html#sphx-glr-auto-tutorials-epochs-20-visualize-epochs-py) looks wonky, and the x axis title is getting cut off by the bottom edge of the figure in the immediately prior plot on that same page.

Let's handle those in a follow-up PR (along with whatever else we notice in the coming weeks)

_Originally posted by @drammock in https://github.com/mne-tools/mne-python/issues/12050#issuecomment-1751582224_

### PR DESCRIPTION
**Pull request by larsoner**
Closes #12090

@drammock feel free to review/merge if you're happy. TL;DR is that `_line_figure` is only used by `Spectrum.plot` and we were using `layout=None` there instead of `layout='constrained'`. Touched a Raw and an Epochs tutorial, both `psd.plot()`s that I checked in those looked good locally.

### CODE REVIEW

**Review by drammock — APPROVED** [review]
rendered examples look good, thanks @larsoner

**Comment by drammock** [comment]
actually, this won't fix the `plot_topomap()` issue in #12090 will it? IIRC we discussed that would require a `shrink` on the colorbars. Disabling auto-merge in case you want to fix that here, otherwise feel free to remove the `closes` magic and then self-merge.

**Comment by larsoner** [comment]
Ahh I'll fix that, too, forgot about that one.

I also think that now that we use `layout='constrained'` the `MNELineFigure` is unnecessary. I'll try removing it in this PR to see if everything continues to work as expected.

**Comment by drammock** [comment]
> I also think that now that we use `layout='constrained'` the `MNELineFigure` is unnecessary. I'll try removing it in this PR to see if everything continues to work as expected.

FWIW the long-term intent was to use MNELineFigure for more than just spectra (evoked plots etc) --- see the comments at the top of `mne/viz/_mpl_figure.py`.  I don't recall if `fig.mne` stores anything crucial for `MNELineFigure` the way that it does for `MNEBrowseFigure` so if removing it be sure to test interactivity carefully.

**Comment by larsoner** [comment]
Okay I kept it around but just simplified it quite a bit. Now it's basically just a `MNEFigure` that sets `sharex=True` and creates axes, which is useful enough. Also it'll be nice to have the subclass shown to be `MNELineFigure` when deing `__repr__` rather than bare `MNEFigure` I think

**Comment by larsoner** [comment]
Okay I think I fixed the topomap colorbar issue and also tightened up / improved `epochs.plot_image`

**Comment by drammock** [comment]
failures seem related? wrong number of axes passed

**Comment by larsoner** [comment]
Should be good @drammock 

- [evoked](https://output.circle-artifacts.com/output/job/69627505-902a-485f-a463-3cdb8c34f6a1/artifacts/0/html/auto_tutorials/evoked/20_visualize_evoked.html#sphx-glr-auto-tutorials-evoked-20-visualize-evoked-py)
- [epochs](https://output.circle-artifacts.com/output/job/69627505-902a-485f-a463-3cdb8c34f6a1/artifacts/0/html/auto_tutorials/epochs/20_visualize_epochs.html#sphx-glr-auto-tutorials-epochs-20-visualize-epochs-py)
- [raw](https://output.circle-artifacts.com/output/job/69627505-902a-485f-a463-3cdb8c34f6a1/artifacts/0/html/auto_tutorials/raw/40_visualize_raw.html#sphx-glr-auto-tutorials-raw-40-visualize-raw-py)

**Comment by drammock** [comment]
looks great, thanks @larsoner!

**Pull request merged**
