### PR TITLE
WIP: Port 3d testing to BackgroundPlotter completely

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR ports testing of the PyVista 3d backend to the `BackgroundPlotter` completely.

As a consequence, the variable `MNE_3D_BACKEND_TESTING` needs refactoring.

**Known issue**
- The dimensions of a screenshot taken with the `BackgroundPlotter` are not equal to `win_height x win_width x 3` but slightly less. I suppose that the real dimensions taken into account are effectively those of the render view (which is smaller than the window).

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
I reported this behaviour in https://github.com/pyvista/pyvista/issues/703

**Comment by GuillaumeFavelier** [comment]
One way to mitigate this issue is to use `setMinimumSize()` on the render view widget so that the window don't automatically shrink it.

**Comment by GuillaumeFavelier** [comment]
> the window does not automatically shrink it.

The drawback is that the user is no longer able to resize the window to a geometry smaller then `window_size`.

**Comment by GuillaumeFavelier** [comment]
This can be relevant to https://github.com/mne-tools/mne-python/pull/7211 (about minimum/fixed widget geometry)

**Comment by larsoner** [comment]
> The drawback is that the user is no longer able to resize the window to a geometry smaller then window_size.

Can you set this until the `super` init finishes, then un-set it?

**Comment by GuillaumeFavelier** [comment]
I use it after `BackgroundPlotter` init to resize the render view. I'll see if there is a way to un-set it without updating the geometry of the window.

**Comment by larsoner** [comment]
> I use it after BackgroundPlotter init to resize the render view. 

Can you see if it's possible to do *before* initializing the view? It should help prevent more jerky resizes, if those happen with the current approach

**Comment by GuillaumeFavelier** [comment]
The window is resized before being shown so I don't think this will lead to jerkiness. But this is a workaround without a way to setting it at init. So far, locally the main issue I notice is with `show_traces=True`. When the window opens:

image

I have to manually resize to get all the content:

image

Also, the CIs do not seem to like those changes.

**Comment by larsoner** [comment]
Probably whatever `setMinSize` you do for the 3D area, you need to do for the 2D area as well. Maybe at 1/4 of whatever the requested 3D vertical size is?

**Comment by larsoner** [comment]
For now you could `assert_allclose(shape, expected_shape, atol=40)  # XXX undo once size fixed` or so to get things to pass. Seems worth it to get the actual BackgroundPlotter used, then we can deal with fixing the size separately

**Comment by GuillaumeFavelier** [comment]
Awesome idea, thank you. I was stuck with `SetMinimumSize()` tbh

**Comment by larsoner** [comment]
The Azure failure is fixed by #7740, but I couldn't see the failed OSX log so I restarted that build.

**Comment by larsoner** [comment]
Failures on OSX apparently seem real

https://travis-ci.org/github/mne-tools/mne-python/builds/683971748

**Comment by GuillaumeFavelier** [comment]
Actually if https://github.com/mne-tools/mne-python/pull/7758 is chosen, I would prefer to keep testing on both plotters.

**Pull request closed without merging**
