### PR TITLE
ENH: Faster time diffs

### LINKED ISSUE #2379: equalize_epoch_count uses lots of RAM
```mne.epochs.equalize_epoch_counts``` (using "mintime") takes 90GB of RAM for a single subject on some of our data sets, and is really slow. However, the "truncate" method seems undesirable. If ```mne.epochs.equalize_epoch_counts``` can't be optimized trivially, how about something like this?

```
larger, smaller = ((ep1, ep2) if len(ep1.events) > len(ep2.events) else (ep2, ep1))

from copy import deepcopy
arr = deepcopy(larger.events)

tts = []
for t in np.random.permutation(smaller.events[:,0]):
    idx = (np.abs(arr[:,0]-t)).argmin()
    tts.append(arr[idx,0])
    arr = np.delete(arr, idx, axis=0)

larger.drop_epochs(np.in1d(larger.events[:,0], tts) == False, 
                   reason='EQUALIZED_COUNT')
```

### PR DESCRIPTION
**Pull request by Eric89GXL**
Closes #2379.

@jona-sassenhagen this takes `_minimize_time_diff` on your sample files from 32 sec to 2.9 sec on my machine.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
@jona-sassenhagen can you see if this works better for you?

**Comment by Eric89GXL** [comment]
Made one more tweak, down to 2 sec on my machine now.

**Comment by agramfort** [comment]
merging

@jona-sassenhagen close the issue if it works now for you.

thanks @Eric89GXL for the quick fix !

**Comment by jona-sassenhagen** [comment]
Nice!

**Pull request merged**
