### PR TITLE
FIX, WIP: auto select ch_type when plotting ica components with picks

### LINKED ISSUE #2333: ISSUE? ica.plot_components() requires ch_type when picks is not None
With my Brainvision data, these work:
```
ica.plot_components()
```

```
ica.plot_components(picks=[1,2], ch_type="eeg")
```

but this doesn't:

```
ica.plot_components(picks=[1,2])
```

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-16-64eeca493160> in <module>()
----> 1 ica.plot_components(picks=[1,2])

/home/FB/fb05/sassenha/tools/mne-working/mne-python/mne/preprocessing/ica.py in plot_components(self, picks, ch_type, res, layout, vmin, vmax, cmap, sensors, colorbar, title, show, outlines, contours, image_interp, head_pos)
   1352                                    outlines=outlines, contours=contours,
   1353                                    image_interp=image_interp,
-> 1354                                    head_pos=head_pos)
   1355 
   1356     def plot_sources(self, inst, picks=None, exclude=None, start=None,

/home/FB/fb05/sassenha/tools/mne-working/mne-python/mne/viz/topomap.py in plot_ica_components(ica, picks, ch_type, res, layout, vmin, vmax, cmap, sensors, colorbar, title, show, outlines, contours, image_interp, head_pos)
    690 
    691     data_picks, pos, merge_grads, names, _ = _prepare_topo_plot(ica, ch_type,
--> 692                                                                 layout)
    693     pos, outlines = _check_outlines(pos, outlines, head_pos)
    694     if outlines not in (None, 'head'):

/home/FB/fb05/sassenha/tools/mne-working/mne-python/mne/viz/topomap.py in _prepare_topo_plot(inst, ch_type, layout)
     56 
     57         if len(picks) == 0:
---> 58             raise ValueError("No channels of type %r" % ch_type)
     59 
     60         if layout is None:

ValueError: No channels of type 'mag'
```

Am I missing something, or is this a bug?

### PR DESCRIPTION
**Pull request by jona-sassenhagen**
Closes #2333 

It's really trivial, I think somebody just forgot to turn on the routine for the case of less than 20 components to pick. Should I make a test still?

### CODE REVIEW

**Comment by jona-sassenhagen** [comment]
And there I thought this would be super straight-forward.

So: currently, in plot_ica_components, ch_type is set differently depending on how many components are plotted. If > 20, _get_ch_type is activated. If not, and ch_type is None, it is set to 'mag'. 

I think _get_ch_type should always be called? However, it requires _contains_ch_type, which requires an info object. The test doesn't give an info object it seems. How to proceed?

**Comment by agramfort** [comment]
@dengemann likely wrote this.

**Comment by jona-sassenhagen** [comment]
@Eric89GXL do I misunderstand the intended purpose of this function? It seems right now, _get_ch_type is only called for fewer than 20 maps, and the default is set to 'mag' when the recursive call for more than 20 maps is done.

**Comment by Eric89GXL** [comment]
I have no idea, I've never used that function. If `git blame` points to me, it should only be for some small fix. Sorry I can't help, hopefully @dengemann or @teonlamont can, I remember them discussing some 20-ch limit regarding ICA before

**Comment by agramfort** [comment]
to me it's a bug. We plot 20 channels at a time for speed.

**Comment by jona-sassenhagen** [comment]
Sorry - I was indeed going by the Blame!

**Comment by Eric89GXL** [comment]
No problem, it's right most of the time (or at least some) :)

**Comment by jona-sassenhagen** [comment]
@teonlamont @dengemann ?

**Comment by dengemann** [comment]
Travis is not happy.

**Comment by jona-sassenhagen** [comment]
Nope - the test fails, because if we always use _get_ch_type for plot_components, one test fails. I'm asking, 1. *should* plot_comps always use _get_ch_type, 2. if so, what to do about the test?

**Comment by teonlamont** [comment]
@jona-sassenhagen, I will look at this tomorrow, been swamped... :(

**Comment by jona-sassenhagen** [comment]
Another issue: when plotting with ica.plot_components, the channels to be plotted are given via the types keyword. If no picks are given, it (in principle ... see this issue) auto-selects e.g. "eeg" (if it's an EEG dataset). This means that if you have some channels marked as "eog", they will not be displayed on the default plot. This seems very suboptimal, because plotting the loadings of components to the eog channels is crucial for visually estimating eog ICs.

**Comment by jona-sassenhagen** [comment]
@teonlamont @dengemann any chances of looking at this now? I'm just asking if the test should be changed, or if the test is good as is and I'm missing something.

**Comment by jaeilepp** [comment]
I think the best option would be just adding ``ch_type`` to the test (``assert_raises(RuntimeError, ica.plot_components, 1, ch_type='mag')`` or change the error type to ``ValueError``. The logic changed somewhat, so the assertions should change too.

**Comment by jona-sassenhagen** [comment]
Sounds good to me!

**Comment by agramfort** [comment]
@jaeilepp you can take over the PR if you want.

**Comment by jona-sassenhagen** [comment]
close for #2525

**Pull request closed without merging**
