### PR TITLE
MRG: Allow unknown KIT systems

### LINKED ISSUE #4923: Importing Yokogawa/KIT data
I try to import data from Brainstorm tutorial: http://neuroimage.usc.edu/brainstorm/Tutorials/Yokogawa and get an error. However, I can import it in Brainstorm. My MNE version 0.15.2
I run this code:
```
import mne
mne.io.read_raw_kit('SEF_000-export.con')
```
output:
```
Extracting SQD Parameters from SEF_000-export.con...
Creating Raw.info structure...
```

error:
`IOError: Unknown FLL type: 300`

### PR DESCRIPTION
**Pull request by larsoner**
Closes #4923.

Running this code on the Brainstorm KIT example data:
```
>>> import mne
>>> data_path = '/home/larsoner/mne_data/sample_yokogawa/data'
>>> raw = mne.io.read_raw_kit(data_path + '/SEF_000-export.con', preload=True)
RuntimeWarning: Unknown site filter settings (FLL) for system "Meg160/Analysis" model "PQA160C" (ID 1001), will assume FLL 300->200, check your data for correctness!
>>> raw.plot_psd()
RuntimeWarning: Channel locations not available. Disabling spatial colors.
```
Produces:
figure_1

This might be good enough for now, until we find a better way to get the definitions. The FLL seems not 100% necessary, since it should just set `highpass, lowpass, line_freq` in `info`.

@christianbrodbeck do you agree?

@makkostya can you confirm this allows you to proceed?

### CODE REVIEW

**Comment by christianbrodbeck** [comment]
The FLL also affects the conversion to Tesla, maybe add a recommendation to specifically check that the Tesla values are reasonable?

**Comment by larsoner** [comment]
That appears to be determined by `FLL_TYPE >= 100` or not, which I assume has to do with a point in time of a hardware upgrade, so hopefully we're safe there. I'll modify the note just in case, though.

**Comment by christianbrodbeck** [comment]
> hopefully

That's why I would recommend to check :)

**Comment by makkostya** [comment]
@larsoner It seems ok for me, thx.

**Comment by larsoner** [comment]
Thanks for the quick checks!

**Pull request merged**
