### PR TITLE
TST: Speedup testing of pyvista backend

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR disables anti-aliasing, line smoothing, smooth shading and decreases the polygon counts of tubes during testing of the pyvista 3d backend. Hopefully this will decrease testing time especially on macOS.

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
`49 mni 52 sec` is not much of a speedup:

image

**Comment by GuillaumeFavelier** [comment]
Better to look how to speedup the slowest ones:

```
42.08s call     mne/inverse_sparse/tests/test_mxne_optim.py::test_iterative_reweighted_tfmxne

27.91s call     mne/viz/_brain/tests/test_brain.py::test_brain_init[pyvista]

24.00s call     mne/io/eeglab/tests/test_eeglab.py::test_io_set_raw[test_raw_h5.set]

22.48s call     mne/viz/tests/test_3d.py::test_plot_evoked_field[pyvista]

21.48s teardown mne/viz/tests/test_3d.py::test_plot_sparse_source_estimates[pyvista]

19.14s call     mne/channels/tests/test_interpolation.py::test_interpolate_meg_ctf

18.97s call     mne/viz/tests/test_ica.py::test_plot_ica_overlay

17.24s call     mne/tests/test_chpi.py::test_calculate_chpi_coil_locs_artemis

16.58s call     mne/channels/tests/test_interpolation.py::test_interpolation_eeg[0.0]

15.95s call     mne/simulation/tests/test_raw.py::test_iterable

14.83s call     mne/viz/_brain/tests/test_brain.py::test_brain_screenshot[pyvista]

14.35s call     mne/beamformer/tests/test_lcmv.py::test_make_lcmv_sphere[None-None]

14.10s call     mne/viz/_brain/tests/test_brain.py::test_brain_add_label[pyvista]

14.08s teardown mne/viz/tests/test_3d.py::test_link_brains[pyvista]

14.04s call     mne/viz/tests/test_ica.py::test_plot_ica_properties

13.26s call     mne/io/artemis123/tests/test_artemis123.py::test_data

12.61s call     mne/commands/tests/test_commands.py::test_clean_eog_ecg

12.45s call     mne/commands/tests/test_commands.py::test_setup_forward_model

12.34s call     mne/viz/tests/test_3d.py::test_renderer[mayavi]
```

**Comment by GuillaumeFavelier** [comment]
The last one is already a bit better with `44 min 16 sec`:

image

```
========================== slowest 20 test durations ===========================

36.99s call     mne/inverse_sparse/tests/test_mxne_optim.py::test_iterative_reweighted_tfmxne

23.45s call     mne/io/eeglab/tests/test_eeglab.py::test_io_set_raw[test_raw_h5.set]

22.00s call     mne/viz/tests/test_3d.py::test_plot_evoked_field[pyvista]

19.57s teardown mne/viz/tests/test_3d.py::test_plot_sparse_source_estimates[pyvista]

18.00s call     mne/viz/tests/test_ica.py::test_plot_ica_overlay

16.95s call     mne/tests/test_chpi.py::test_calculate_chpi_coil_locs_artemis

15.88s call     mne/channels/tests/test_interpolation.py::test_interpolation_eeg[0.0]

15.55s call     mne/simulation/tests/test_raw.py::test_iterable

15.09s call     mne/channels/tests/test_interpolation.py::test_interpolate_meg_ctf

14.09s call     mne/viz/_brain/tests/test_brain.py::test_brain_init[pyvista]

13.58s call     mne/viz/_brain/tests/test_brain.py::test_brain_add_label[pyvista]

13.41s call     mne/viz/_brain/tests/test_brain.py::test_brain_screenshot[pyvista]

13.17s call     mne/beamformer/tests/test_lcmv.py::test_make_lcmv_sphere[None-None]

13.13s call     mne/viz/tests/test_ica.py::test_plot_ica_properties

12.71s teardown mne/viz/tests/test_3d.py::test_link_brains[pyvista]

11.75s call     mne/tests/test_epochs.py::test_reject

11.74s call     mne/io/artemis123/tests/test_artemis123.py::test_data

11.71s call     mne/commands/tests/test_commands.py::test_setup_forward_model

11.48s call     mne/viz/tests/test_epochs.py::test_plot_psd_epochs_ctf

11.21s call     mne/commands/tests/test_commands.py::test_clean_eog_ecg
```

**Comment by GuillaumeFavelier** [comment]
The failure of Azure style is not related, I opened https://github.com/mne-tools/mne-python/issues/7721

**Comment by GuillaumeFavelier** [comment]
I did not find any other obvious ways to speed the tests further. I will look into again after #7697 but for now this is ready to be merged.

**Comment by larsoner** [comment]
@GuillaumeFavelier it looks like a lot of the time is in `test_brain`. I imagine a lot of that is in the initialization of the `brain` object itself. Monolithic tests in general are not great, but in this case it might be worth it to make them all one test to save more time. But that can be another PR if you want

**Comment by larsoner** [comment]
Thanks @GuillaumeFavelier !

**Comment by GuillaumeFavelier** [comment]
>  Monolithic tests in general are not great, but in this case it might be worth it to make them all one test to save more time

This is a good idea, I'll try it out

**Pull request merged**
