### PR TITLE
[MRG] FIX:  path regex on windows

### PR DESCRIPTION
**Pull request by christianbrodbeck**
@Eric89GXL waiting to see if CIs are fixed...

### CODE REVIEW

**Comment by Eric89GXL** [comment]
CIs look happy, and I suspect that's the correct fix. Is it easy for you to test locally that it doesn't break Unix systems if there is a `\` in the path?

**Comment by christianbrodbeck** [comment]
I haven't tested it, can do that, but I first put it into a conditional for
windows and then realized that if you had a backslash in a Linux path you
would also need I escape it in the pattern, this just never came up because
nobody puts backslashes into paths.

**Comment by christianbrodbeck** [comment]
```
$ mkdir a\\a
$ ls
a\a
$ ipython
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08) 
Type "copyright", "credits" or "license" for more information.

IPython 5.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import re

In [2]: import os

In [3]: print [p for p in os.listdir('.') if re.match('a\\a', p)]
[]

In [4]: print [p for p in os.listdir('.') if re.match('a\\\\a', p)]
['a\\a']

```

**Comment by agramfort** [comment]
LGTM

@Eric89GXL merge if it works for you

**Comment by Eric89GXL** [comment]
Thanks @christianbrodbeck

**Pull request merged**
