### PR TITLE
[FIX] Add warning for non-unique time points in `events`

### PR DESCRIPTION
**Pull request by jona-sassenhagen**
The previous warning message for non-unique time points was a bit cryptic.
@kingjr

### CODE REVIEW

**Comment by kingjr** [comment]
Thanks!

**Comment by agramfort** [comment]
Lgtm 

Can you just add a tiny test?

**Comment by jona-sassenhagen** [comment]
Test done @agramfort

**Comment by agramfort** [comment]
Thanks !

**Pull request merged**
