### PR TITLE
FIX: Minor fixes

### PR DESCRIPTION
**Pull request by Eric89GXL**
Fixes our use of `np.array([])` when we mean `np.array([], int)`. Also adds scrolling support to `raw.plot()`.

Ready for review/merge once the CIs are happy.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
I have no idea why AppVeyor refuses to download the testing file archive, it's definitely still there. This PR should be good to go, though.

**Comment by dengemann** [comment]
Because it runs on Windows ;-)

2015-01-23 23:39 GMT+01:00 Eric Larson <notifications@github.com>:

**Comment by agramfort** [comment]
i dont see the scrolling changes

besides lgtm

**Comment by Eric89GXL** [comment]
Sorry, I forgot I had `commit --amend`ed the commit, and hadn't pushed. Push forced, feel free to review and merge.

**Comment by agramfort** [comment]
Thanks

**Pull request merged**
