### PR TITLE
MRG, ENH: Add method links to examples

### PR DESCRIPTION
**Pull request by larsoner**
I went to look for examples for [raw.plot_psd](https://martinos.org/mne/stable/generated/mne.io.Raw.html#mne.io.Raw.plot_psd) but noticed there were none there. I suspect that we need this in our autosummary RST files. Haven't tested but I'm optimistic it should work.

### CODE REVIEW

**Comment by larsoner** [comment]
Okay it didn't work, probably a limitation in Sphinx-gallery that it does not pick up methods properly in the backreference generation step

**Comment by larsoner** [comment]
This is the sort of thing I'm going for:

https://14544-1301584-gh.circle-artifacts.com/0/dev/generated/mne.io.Raw.html#mne.io.Raw.plot_psd

But I need to make it not show up in cases where there are no actual examples. This will probably require some modifications at the SG end.

**Comment by larsoner** [comment]
(also the list is incomplete but that will be fixed by https://github.com/sphinx-gallery/sphinx-gallery/pull/525)

**Comment by jasmainak** [comment]
This would be great! I wanted to have it too

**Comment by larsoner** [comment]
Commit pushed that only appends the `include` line if there is something to include:

https://14583-1301584-gh.circle-artifacts.com/0/dev/generated/mne.io.Raw.html#mne.io.Raw.plot_psd

Now we just need https://github.com/sphinx-gallery/sphinx-gallery/pull/526 to be merged, I'll revert the change to `.circleci/config.yml` and then we should be good to go.

**Comment by larsoner** [comment]
@drammock WDYT?

https://14662-1301584-gh.circle-artifacts.com/0/dev/generated/mne.io.Raw.html#mne.io.Raw.filter

**Comment by drammock** [comment]
Still specifies your fork of sphinx-gallery...  are we still waiting for changes there to be merged? Other than that I think this is a really useful change.

**Comment by larsoner** [comment]
Okay the SG PR was merged and I updated this PR and things still seem to work, see for example:

https://14664-1301584-gh.circle-artifacts.com/0/dev/generated/mne.io.Raw.html#mne.io.Raw.add_events

**Comment by larsoner** [comment]
Pushed a commit to fix [two broken examples in master](https://circleci.com/gh/mne-tools/mne-python/14672), will merge once CircleCI comes back happy.

**Pull request merged**
