### PR TITLE
[MRG] Wrap title in tutorial.

### PR DESCRIPTION
**Pull request by jaeilepp**
Closes https://github.com/mne-tools/mne-python/issues/4235

### CODE REVIEW

**Comment by agramfort** [comment]
how does it look like now?

**Comment by jaeilepp** [comment]
image

https://1618-35097627-gh.circle-artifacts.com/0/home/ubuntu/mne-python/doc/_build/html/auto_tutorials/plot_visualize_evoked.html

**Comment by agramfort** [comment]
looks but now looking at it it really seems a poor choice of colors.

anyone strongly in favor of a dark background?

**Comment by mmagnuski** [comment]
I'm strongly *against* black background :) (same in `plot_psd_topo`)

**Comment by agramfort** [comment]
I have to admit I agree with you. It was an early decision to mimic the
Neuromag / mne_analyze interface.

**Comment by jaeilepp** [comment]
There are keywords for changing the colors. Updating the tutorial is probably sufficient?

**Comment by agramfort** [comment]
how does it look like with white background?
if it's nicer +1 to deprecate

**Comment by jaeilepp** [comment]
figure_1

**Comment by agramfort** [comment]
hum... yellow on white...

**Comment by Eric89GXL** [comment]
We should use the default mpl color cycle if no colors are provided

**Comment by mmagnuski** [comment]
I agree with @Eric89GXL. Also aren't the lines a little too thick?

**Comment by agramfort** [comment]
thanks @jaeilepp 

I'm giving a try to the white background and better default colors

**Pull request merged**
