### PR TITLE
MRG ENH: Faster import

### PR DESCRIPTION
**Pull request by Eric89GXL**
Some minor cleanups. This takes `import mne` time on my system down from 0.52 sec to 0.16 sec. Turns out `sklearn` and `scipy.*` imports were the biggest culprits, so I nested the ones that weren't terrible to implement. I think these nested imports are worth it.

~~WIP because I need to fix a test.~~

### CODE REVIEW

**Comment by dengemann** [comment]
@Eric89GXL to comment on and summarize your chosen strategy, by moving imports into functions, the module imports are speeded up, right?

Can you give numbers on the speed improvement?

**Comment by Eric89GXL** [comment]
See original description for speed improvement

**Comment by Eric89GXL** [comment]
And yeah, that is the idea, some of those imports were slow

**Comment by dengemann** [comment]
Looks good to me. Merge once travis is happy!

**Comment by Eric89GXL** [comment]
BTW a lot of the remaining 160ms is spent due to our `verbose` decorator, specifically in the `mne.externals.decorator` code that wraps things. It's probably not worth dealing with it, but it would be nice if we didn't have to use that to get our docstrings and introspection to work properly.

**Comment by Eric89GXL** [comment]
Ready to go from my end

**Comment by agramfort** [comment]
so now scipy.sparse, signal and ndimage etc... require nested imports?

we only allow scipy.linalg as top import?

I could have leaved with the way it was... you were annoyed with import time?

**Comment by Eric89GXL** [comment]
Yeah, half a second to import a package can get tiresome when trying to do and test simple little things. I also `import mne.filter` in another package, and so the time adds up.

It looks like I didn't nest all `scipy.sparse`, so I can un-nest the ones that I did nest. It looks like `linalg`, `sparse`, and `fftpack` ended up being the ones that didn't take too long to import.

**Comment by Eric89GXL** [comment]
To put things in a slightly different light, what would it mean if all package maintainers had the attitude that a > half-second import is okay? It would not be good :) Granted, we are somewhat higher-level than most other packages, but IMO this is a small price to pay to lower our import burden.

**Comment by agramfort** [comment]
ok point taken but I just fear now that problems appears again. Could we have a script that tests we don't import scipy modules globally except if it's linalg ?

**Comment by Eric89GXL** [comment]
Yeah, that should be doable

**Comment by Eric89GXL** [comment]
@agramfort test added

**Comment by agramfort** [comment]
cool

merge when travis is happy

**Pull request merged**
