### PR TITLE
[MRG] FIX : make DICS work with volume source space

### PR DESCRIPTION
**Pull request by agramfort**

### CODE REVIEW

**Comment by agramfort** [comment]
can I merge?

**Comment by dengemann** [comment]
Thanks Alex!

**Comment by teonlamont** [comment]
this makes for the 1500th closed pr, yay!

**Comment by teonlamont** [comment]
well, technically #2461 was closed the latest for the official one but this pr number is higher so it was prioritize the top of the closed pr list when i wrote it ;)

**Pull request merged**
