### PR TITLE
Fix problems with spaced names in brainvision.py #7243

### LINKED ISSUE #7243: Brain Vision: Assertion error with channel names containing spaces
Hi,
I have plenty of Brain Vision files with channel names containing spaces:
```
Channels
--------
#     Name      Phys. Chn.    Resolution / Unit   Low Cutoff [s]   High Cutoff [Hz]   Notch [Hz]    Series Res. [kOhm] Gradient         Offset
1     ECoG 1      1                 10 µV             DC              250              Off                0                 
2     ECoG 2      2                 10 µV             DC              250              Off                0      
```

and when I try to read them, I get following Assertion Error:
```
File "...\lib\site-packages\mne\io\brainvision\brainvision.py", line 637, in _get_vhdr_info
    assert ch in line_amp

AssertionError
```
because the channel name "ECoG 1" is splited into "ECoG" and "1" in the line 636
```line_amp = re.split(divider, settings[idx_amp + i])```
and then the channel name is not found in the resulting list.
It works, when I change the line 611 from
```divider = r'\s+'```
to 
```divider = r'\s\s+'```
and remove all the shift related code for the highpass and lowpass search but this will of course break in case of names with multiple white spaces or probably also very long channel names.

### PR DESCRIPTION
**Pull request by major-s**
Fixes broken reading of Brain Vision files with channel names containing spaces. Now the name is looked up in before split and the shift for reading highpass and lowpass filter settings is corrected. It works with multiple or no spaces.

closes #7243

### CODE REVIEW

**Comment by agramfort** [comment]
@major-s can you update a test for this ? Thx

**Comment by agramfort** [comment]
done @major-s please have a look at https://github.com/mne-tools/mne-python/pull/7252/commits/0107dc81e4f54316b774e46de4805ae8f86ba1d8 and let me know if it's ok for you. thanks a lot for reporting this issue.

**Comment by major-s** [comment]
@agramfort: Perfect. Pragmatic solution for the test...

**Comment by larsoner** [comment]
Thanks @major-s

**Pull request merged**
