### PR TITLE
bug fix #5356 scan for BrainVision sections using ^ and $

### LINKED ISSUE #5356: Brainvision marker parser fails w/ [] characters
I have a (perhaps poorly chosen) marker in a file I received, 
```ini
Mk9=Comment,Discontinuit? [B] 4156 ms,136544,1,0
```
which at `brainvision.py:269` is being found with 
```python
items = re.findall(r"^Mk\d+=(.*)", mk_txt, re.MULTILINE)
```
but this regex stops completely at the `[` character, not finding the rest of the line nor the markers which follow.

I'm not a regex ninja but if I manage to fix, I'll send a PR.  In the meantime, I will change remove the offending characters in the file and move on.

### PR DESCRIPTION
**Pull request by sappelhoff**
fixes #5356

### CODE REVIEW

**Comment by jona-sassenhagen** [comment]
Can we modify a test datafile?

**Comment by jona-sassenhagen** [comment]
E.g. modify a line in mne/io/brainvision/tests/data/test.vmrk

**Comment by sappelhoff** [comment]
@jona-sassenhagen what *new* feature would you like to test? The present PR more or less fixes a bug that prevented us to read markers such as:

`Mk9=Comment,Discontinuit? [B] 4156 ms,136544,1,0`

we'd have to write a new test that reads all markers and then asserts that the `Mk9` listed above is part of the mne events. Just changing/adding a line to `.vmrk` would not test for this bugfix.

**Comment by jona-sassenhagen** [comment]
Uh ...

- add the line you suggested to the middle of the vmrk file
- add a line testing the length of the read-out events (i.e., ensure it parses events after the one with the brackets)

**Comment by sappelhoff** [comment]
@jona-sassenhagen, this should be it :-)

**Comment by jona-sassenhagen** [comment]
Thanks @sappelhoff

**Pull request merged**
