### PR TITLE
MRG: Add misc to circle data

### PR DESCRIPTION
**Pull request by Eric89GXL**
Needed for one of the examples, see the bad logging that shows up in the example here:

https://circle-artifacts.com/gh/mne-tools/mne-python/543/artifacts/1/home/ubuntu/mne-python/doc/_build/html/auto_examples/preprocessing/plot_movement_compensation.html#sphx-glr-auto-examples-preprocessing-plot-movement-compensation-py

@jaeilepp feel free to merge if you agree.

Also, it looks like we're getting errors on `master` with the uploading step, the key is getting rejected...?

### CODE REVIEW

**Comment by jaeilepp** [comment]
For some reason the key didn't seem to work. Now I managed to add a second key to it. It's the same that I used on my fork. Let's see if it works.

**Comment by jaeilepp** [comment]
Thanks @Eric89GXL

**Comment by jaeilepp** [comment]
It worked! It's now pushing to production branch, but perhaps it could be changed to push straight to master so the dev pages would be found at http://mne-tools.github.io/dev/index.html?

Also, I noticed that the build failed at least once because the caching didn't work and the time limit was reached as all the data had to be downloaded again. I suppose it's not a big problem as long as most of the builds succeed? And I think the download times can be reduced as there is actually some data downloaded which isn't used by the examples.

**Comment by agramfort** [comment]
+1 to push directly to master when doc build passes on our master branch.

you should also activate the fail on error option of sphinx gallery so we
don't push
a broken doc build

**Pull request merged**
