### PR TITLE
[MRG] License update (#10228)

### PR DESCRIPTION
**Pull request by stevemats**
#### Reference issue

- Fixes issue #10228

#### What does this implement/fix?
- Updates License dates on README.rst
- Updates License dates on LICENSE file

### CODE REVIEW

**Comment by cbrnr** [comment]
We could also think about not updating the current year because it doesn't seem to be necessary: https://hynek.me/til/copyright-years/

**Comment by stevemats** [comment]
> We could also think about not updating the current year because it doesn't seem to be necessary: https://hynek.me/til/copyright-years/

Thanks for sharing this. My original thought was that derivative works can appear and use your copyright in 2022 and say that you didn't have/claim the copyright this year hence, giving permission for anyone to use the copyright with no claim.

**Comment by cbrnr** [comment]
Yes, that's apparently not how it works.

**Comment by wmvanvliet** [comment]
Still, seems neater to me to have it updated.

**Review by agramfort — APPROVED** [review]

**Comment by agramfort** [comment]
thx @stevemats

**Pull request merged**
