### PR TITLE
MRG: Fix CTF fiducials

### LINKED ISSUE #4589: CTF: coregistration issue
With @avkasdan, we're having some issues with the coregistration of CTF data.

we used `mne.io.read_raw_ctf`  to read save the MEG data as a `fif` file.

we then use `mne.gui.coregistration` but the first issue is that we cannot save the trans file (the save button is not activated)
screen shot 2017-09-14 at 5 53 42 pm

After digging down, it seems that changing the `info['dig']` of the fif file, solves this issue. Specifically, we changed all entries of `kind==3` into `kind=1` (no idea why, but this seems to be the sufficient thing to change to make `save_as` reappear).

However, now we still are unable to fit the fiducials with the HPI, even with MRI rescaling:
screen shot 2017-09-20 at 3 51 19 pm

Any help would be greatly appreciated: the freesurfer, fif, and ctf (`*.ds/`) data is available here:
https://www.dropbox.com/sh/tqiymp8ymo62n85/AAAl1D0WKY3efMR-UeNH3qoOa?dl=0

(Linked to #3243?)

### PR DESCRIPTION
**Pull request by larsoner**
Closes #4589.

@kingjr can you see if it fixes your CTF coreg problem?

### CODE REVIEW

**Comment by avkasdan** [comment]
Now it throws an error when we try to load the head shape source file (`raw.fif`).

Note that we have no error and no problem fitting doing this with `mne_analyze`.

**Comment by larsoner** [comment]
Okay try again please. This works for me (once I set the MRI fids and align them using the align button):
```
mne coreg -s ESA28 -d ~/Desktop/ctf --no-guess-mri -f ~/Desktop/ctf/ESA28_01.fif
```
"cardinal point" is another name for "fiducial" in this context

**Comment by agramfort** [comment]
I see errors like:

""""
  File "/Users/alex/work/src/mne-python/mne/gui/_coreg_gui.py", line 405, in omit_hsp_points
    new_filter = np.ones(len(self.hsp.raw_points), np.bool8)
AttributeError: 'DigSource' object has no attribute 'raw_points'
""""

I also see tiny pink balls that seem far from the skin. Do you see this?

**Comment by larsoner** [comment]
No. When I do:
```
mne coreg -s ESA28 -d ~/Desktop/ctf --no-guess-mri -f ~/Desktop/ctf/ESA28_01.fif
```
I get this screen (and no errors):
screenshot from 2017-09-27 09-27-38
Then I click on the MRI where I think the LPA is; click the "Set: Nasion" (on the left) and click on the MRI where I think the nasion is; click the "Set: RPA" and click on the MRI where I think the RPA is; then click "Lock" (on the left), and I get the ability to set the coreg (note ungrayed options):
screenshot from 2017-09-27 09-29-27
Clicking "fit fiducials" on the right panel I get a not-great fit (but it can be adjusted via scaling):
screenshot from 2017-09-27 09-29-33

**Comment by larsoner** [comment]
@kingjr can you try?

**Comment by agramfort** [comment]
what are the pink dots at the back of the head?

@larsoner try clicking on fit lpa/rpa and fit fiducials.

and maybe "omit"

this is how I got the errors.

**Comment by larsoner** [comment]
> what are the pink dots at the back of the head?

They appear to be about as far from the head as the fiducials are from one another, so I think this might not be a great dig fit. They are of EEG kind in the `info['dig']`.

> and maybe "omit"

Yes I can replicate with this, but it should be fixed with the latest commit. You can test with @kingjr's data, but then also verify with some data that actually have `EXTRA` points:

```
mne coreg -s sample -d ~/mne_data/MNE-sample-data/subjects --no-guess-mri -f ~/mne_data/MNE-sample-data/MEG/sample/sample_audvis_raw.fif
```

**Comment by avkasdan** [comment]
> what are the pink dots at the back of the head?

No idea, we have those for all CTF recordings, I've asked, I'll wait for the answer. Up to now I always omitted them.

> I think this might not be a great dig fit.

Indeed the fit in this particular subject is pretty bad, but it seems to be the same issue with `mne_analyze`

However, the omission function seems different: using 10 mm 
* remove the dots in `mne_analyze` 
* does not do anything in `mne.gui.coregistration`, which instead indicates `Excluding 0 head shape points with distance >= 0.010 m.


Apart from this omission issue, this branch fixes the load/save error: we can load the head shape source from gui, and the error message doesn't pop up anymore. Thanks @larsoner 

JR & Anna

**Comment by larsoner** [comment]
> the omission function seems different: using 10 mm

In `mne_analyze` it must remove even EEG dig points, in `coreg` it only removes the extra (headshape) dig points.

**Comment by larsoner** [comment]
@agramfort okay with you to merge once the CIs come back happy?

**Comment by agramfort** [comment]
works for me on sample and this ctf data (at least no crash)

thx @larsoner

**Pull request merged**
