### PR TITLE
[MRG+1] FIX: `concatenate_epochs` available from mne

### PR DESCRIPTION
**Pull request by kingjr**
Closes https://github.com/mne-tools/mne-python/issues/2983#issuecomment-192182428

### CODE REVIEW

**Comment by dengemann** [comment]
I thin the python reference rst also needs an update. Check as we have done with the other functions.

**Comment by kingjr** [comment]
Is this me who makes an awful lot of modules crash on one of the Travis' version?

**Comment by dengemann** [comment]
looks like travis has some endogenous sufferings ...

**Comment by dengemann** [comment]
Ah non. It seems as if we have a classical circular import problem. Can you import mne on your branch without issues?

**Comment by kingjr** [comment]
> Ah non. It seems as if we have a classical circular import problem. Can you import mne on your branch without issues?

Ah oui :)

**Comment by dengemann** [comment]
Surprising. Let me take a look. Bug smell.

**Comment by dengemann** [comment]
Running tests locally.

**Comment by kingjr** [comment]
> Running tests locally.

did it pass?

**Comment by dengemann** [comment]
Inmporting yes, and If our tests were faster I could tell you already ;)

**Comment by kingjr** [comment]
which test do you run nosetools doc? This fails on mine, but I think I have a problem with beautifulsoup

**Comment by dengemann** [comment]
One of the options in our Makefike, make all or test-doc

**Comment by kingjr** [comment]
ok good to know

**Comment by agramfort** [comment]
no example or test to update?

**Comment by kingjr** [comment]
> no example or test to update? 

I don't know. Since there's now more than one way to load `concatenate_epochs`, update isn't necessary. 

No example use `concatenate_epochs`.

**Comment by dengemann** [comment]
I confirm. This function has been a bit secret nothing else to update. I think the error is unrelated. My +1.

**Comment by agramfort** [comment]
thx @kingjr

**Pull request merged**
