### PR TITLE
[Backport #5841] EDF stim_channel

### PR DESCRIPTION
**Pull request by massich**
This PR backports #5841.

It mainly adds the same test to show its behaviour, and changes the warning doc.

### CODE REVIEW

**Comment by massich** [comment]
I'm not quite sure what to do here.

If we call `raw = read_raw_edf('test_stim_channel.edf', stim_channel=None)` 
where `'test_stim_channel.edf'` has only 3 channels named: `'status'`, `'trigger'`, and `'sine 1 Hz'` it tries to something with channel name called `'EDF Annotations'` whatever... which seems really wrong.

```
E           RuntimeWarning: 1 channel names are too long, have been truncated to 15 characters:
E           ['EDF Annotations-1']
```

This is not the case in master (obviously 'cos the code is completely different).
So I guess the question is: Should we solve all these bugs? or tell people to use 0.18? Or should we just copy paste whatever is in `edf.py` for version `0.17.1` ?

**Comment by agramfort** [comment]
LGTM

thx @massich

**Comment by agramfort** [comment]
@larsoner please merge if happy

**Comment by larsoner** [comment]
Thanks @massich

**Pull request merged**
