### PR TITLE
[MRG, DOC] Remove CSD average reference note

### PR DESCRIPTION
**Pull request by alexrockhill**
Addresses https://github.com/mne-tools/mne-python/issues/9319

### CODE REVIEW

**Comment by alexrockhill** [comment]
I think the tests should pass and be the same because the test data was already in average re-reference.

**Comment by alexrockhill** [comment]
Ok, once the tests pass, this should be good to go. It just clarifies that the data does not need to be average referenced to apply the CSD by removing a comment that said that the data would be automatically average referenced.

**Comment by alexrockhill** [comment]
Doesn't look like the test failures are legitimate, I think this is good to go

**Review by agramfort — APPROVED** [review]

**Comment by larsoner** [comment]
Thanks @alexrockhill

**Pull request merged**
