### PR TITLE
MRG, DOC: Split changes

### LINKED ISSUE #5731: whats new refactor
the whats new it's getting long. I suggest we split it. I think that matplotlib did it long ago, and scikit-learn did it last year (https://github.com/scikit-learn/scikit-learn/issues/9124)

we could recycle much of the work. 

We could also try whatever use people from [pytest](https://docs.pytest.org/en/latest/changelog.html) and force the whats new by the CI

### PR DESCRIPTION
**Pull request by larsoner**
Closes #5731.

A bunch of copy-paste. The only new content is what is now in `whats_new.rst` which links to the copy-pasted docs, which are `doc/changes/<ver>.inc` now.

### CODE REVIEW

**Comment by larsoner** [comment]
No idea what `codecov` is talking about. Coverage should be the same. Rendering looks correct:

https://14807-1301584-gh.circle-artifacts.com/0/dev/whats_new.html

**Comment by agramfort** [comment]
looks good https://14812-1301584-gh.circle-artifacts.com/0/dev/whats_new.html merging.

**Comment by agramfort** [comment]
I am sure @massich his happy about this :)

**Comment by massich** [comment]
super happy!! its crashing all my PRs. But I'm happy about it!!

**Comment by agramfort** [comment]
shit... I might have merged it too quickly. really sorry about this
@massich :( :(

**Pull request merged**
