### PR TITLE
[ENH, MRG] Add Hilbert to TFR methods comparison

### PR DESCRIPTION
**Pull request by alexrockhill**
I think this is an important methods comparison as the Hilbert transform is a popular choice in some electrophysiology circles. I definitely have been asked about it and I think it's nice to compare in this example. Also, it's a good demonstration of how to coerce this kind of data to fit within the API since it doesn't fit naturally very well with the other time-frequency methods.

### CODE REVIEW

**Comment by alexrockhill** [comment]
Hmmm, I didn't change this code, perhaps this example hasn't been modified in long enough that it never got run checking for warnings.

**Comment by alexrockhill** [comment]
Huh so I touched up the example a bit more to make things consistent as I was trying to fix the Stockwell transform. I ended up just converting a warning to an info here https://github.com/mne-tools/mne-python/blob/main/mne/time_frequency/_stockwell.py#L27-L35 since there's an `elif n_fft < n_times` that leads to a value error and an `if n_times < n_fft` immediately after that leads to a warning. The default `n_fft` is twice the length of the signal so I assume it's meant to be used with zero padding and this warning should just be an info about how much padding is applied. I think it's best not to have an unavoidable error or warning, it was confusing to me at least.

**Comment by alexrockhill** [comment]
https://output.circle-artifacts.com/output/job/cae0df43-aac3-426d-ad85-aed1c4313607/artifacts/0/dev/auto_examples/time_frequency/time_frequency_simulated.html?highlight=tfr

**Comment by larsoner** [comment]
For you @wmvanvliet ?

**Review by agramfort — APPROVED** [review]

**Comment by alexrockhill** [comment]
Thanks for clarifying the prose @wmvanvliet!

**Comment by agramfort** [comment]
@wmvanvliet please merge if you're happy

🙏 @alexrockhill

**Comment by wmvanvliet** [comment]
Thanks @alexrockhill!

**Comment by alexrockhill** [comment]
> I have never used Hilbert transforms, so I don't know about any special considerations that need to be taken into account. Just a few touchups to the comments from me. If the Hilbert transform is indeed commonly used to compute TFR's, then having an example of how to do it is valuable. Perhaps we should even have this as a proper function someday.

I was reading this paper https://doi.org/10.1523/JNEUROSCI.1996-19.2020 and thought of this comment and that it might be helpful to provide an example of a paper where the authors do this for reference.

**Pull request merged**
