### PR TITLE
WIP: orientation selection for unit-gain LCMV

### PR DESCRIPTION
**Pull request by britta-wstnr**
Filling in the gaps in the ``lcmv`` code: this computes the optimal selection for the unit-gain LCMV beamformer if ``pick_ori='max_power'``, which was before only implemented for the unit-noise-gain LCMV.

@agramfort @dengemann @sarangnemo

### CODE REVIEW

**Comment by agramfort** [comment]
good

let me know when you have a test and validation on phantom data.

**Comment by britta-wstnr** [comment]
@agramfort yes, working on that! will let you know

**Comment by britta-wstnr** [comment]
One obstacle for creating tests is that this version of the LCMV does not inherently take care of the center-to-head bias. This means, we either need to compare conditions or normalize the leadfield to get meaningful results. @agramfort and @dengemann : is leadfield normalization implemented?
So far, I validated this version against the version implemented in Fieldtrip, which gives a perfect overlap.

**Comment by agramfort** [comment]
what do you call leadfield normalization?

**Comment by britta-wstnr** [comment]
Fieldtrip calls it leadfield normalization or depth normalization.
It's L/norm(L) with L being the leadfield

**Comment by agramfort** [comment]
L is leadfield per location? so a matrix n_sensors x 3 ?
and norm is Frobenius ?

**Comment by britta-wstnr** [comment]
Yes, per voxel. And straight norm, cf. Chapter 4.1.2 in Sekihara & Nagarajan, 2008.

**Comment by agramfort** [comment]
ok. Do what you have to do to get correct estimates on phantom data and I
will be convinced :)

**Comment by wmvanvliet** [comment]
our DICS implementation also normalizes the leadfield for exactly the same reason.

**Comment by agramfort** [comment]
good to know.

**Comment by britta-wstnr** [comment]
@wmvanvliet 
As stated over at https://github.com/mne-tools/mne-python/pull/4797, it might make sense to get the same leadfield normalization code available for both DICS and LCMV, right?

We've been discussing this PR off Github a bit - I will give a summary of what we discussed and what I tried code-wise here ASAP and then hopefully we can also push this PR forward again!

**Comment by wmvanvliet** [comment]
We can move the normalization to the `forward` module then. Something like `normalize_forward_solution`.

**Comment by agramfort** [comment]
as just said please do this in the beamformer module

**Comment by sarangnemo** [comment]
@agramfort Depth weighting,
 as [already implemented in MNE-Python](https://martinos.org/mne/stable/manual/source_localization/inverse.html#depth-weighting) for the min-norm techniques, is already equivalent to lead field normalization. :-) As there is no effective difference between the justification or method for doing lead field normalization between beamforming and min-norm (the point is exactly to do depth weighting in both cases), I strongly suggest that this becomes a public function that can be used by both families of algorithms. Otherwise, it'll result in a duplication of code that is attempting to accomplish the same thing.

**Comment by agramfort** [comment]
>
> @agramfort <https://github.com/agramfort> Depth weighting,
> as already implemented in MNE-Python
> <https://martinos.org/mne/stable/manual/source_localization/inverse.html#depth-weighting>
> for the min-norm techniques, is already equivalent to lead field
> normalization. :-)
>

yes but MNE does not fully scale the columns cf depth which is set to 0.9
and not 1 for example.

if you scale with 1 then the MNE code will change it's behavior.

rather than a public function I prefer using the same _prepare_gain private
function
as it is done right now (or should be done)

**Comment by britta-wstnr** [comment]
Progress status: with the planned refactoring of ``lcmv`` and ``dics`` (https://github.com/mne-tools/mne-python/issues/5109), leadfield normalization will be available to ``lcmv`` and then this can move forward!

**Comment by mmagnuski** [comment]
Is this still relevant or was this done along #5134 or #5135 ?

**Comment by larsoner** [comment]
This appears to exist now and is checked off in #5365

**Pull request closed without merging**
