### PR TITLE
[FIX?] Exclude ref_meg for channel interpolation of CTF data

### PR DESCRIPTION
**Pull request by jeythekey**
Proposed fix for #5965

### CODE REVIEW

**Comment by larsoner** [comment]
We have a tiny CTF test file https://github.com/mne-tools/mne-python/blob/master/mne/io/tests/data/test_ctf_raw.fif. Can you add a test that gives a bad interpolation on `master` (e.g., mark a good channel as bad, interpolate it using the other channels, and see that the correlation of interpolated with true data is low) and that it's fixed in this PR (the correlation is higher)?

**Comment by jeythekey** [comment]
OK, I'll do this probably next week. 3 seconds might be too short, but we'll see. Thanks!

**Comment by larsoner** [comment]
The interpolation is spatial, 3 sec should be plenty for the `corrcoef`

**Comment by suhailmatar** [comment]
New here -- but was wondering if/when this will be merged, since I and a bunch of colleagues have the exact same issue (resolved locally using the same changes).

**Comment by agramfort** [comment]
the PR has been close by @jeythekey without a reason. We assumed the problem was solved.

**Comment by suhailmatar** [comment]
Unfortunately, the problem with bad values when interpolating bads persists. What would you recommend? A fresh PR (with the same changes)?

**Comment by jeythekey** [comment]
I am sorry for the delay. I did not close this PR on purpose, I don't know what happened. I just pushed the formal test for the change, Eric requested, to my branch. Do I have to do anything to re-open the PR?

**Comment by agramfort** [comment]
LGTM

can you update the whats_new.rst page to document the fix? you may need to rebase on current master as a lot of updates have been done to this page in the mean time.

thx @jeythekey

**Comment by larsoner** [comment]
Something tragic has happened with the `git` history here, maybe start a clean branch based on `upstream/master` and cherry-pick your relevant commits?

**Comment by jeythekey** [comment]
Done in #6242, @larsoner.

**Pull request closed without merging**
