### PR TITLE
MRG, FIX, DOC: modify brainmask default value

### LINKED ISSUE #7216: Default brainmask value in mne.bem.make_watershed_bem would incur an error by Freesurfer(dev) mri_watershed
#### Describe the bug
Default brainmask value in `mne.bem.make_watershed_bem` would incur an error by Freesurfer (dev a76846c, latest atm) `mri_watershed`

https://github.com/mne-tools/mne-python/blob/maint/0.19/mne/bem.py#L1036

******************************
Saving /home/foucault/data/derivatives/freesurfer/sub-103/bem/watershed/ws
error: unknown file type for file (/home/foucault/data/derivatives/freesurfer/sub-103/bem/watershed/ws)

If the `brainmask='brainmask.mgz'`or `brainmask='ws.mgz'` is set, there's no error message then.

### PR DESCRIPTION
**Pull request by zuxfoucault**
#### Reference issue
Fixes #7216

#### What does this implement/fix?
Modify the brainmask default value in `mne.bem.make_watershed_bem` and the corresponding part in the document.

### CODE REVIEW

**Comment by larsoner** [comment]
@zuxfoucault have you tested this locally to make sure it works?

**Comment by zuxfoucault** [comment]
Yes it worked locally, judged by the final folder structure. Although, I couldn't see the stdout yielded from FreeSurfer with the latest master.

**Comment by larsoner** [comment]
This should be much more usable than the `ws` directory full of `COR` files.

@zuxfoucault could you update `changes/latest.rst` to mention this change? I guess it would go in the `BUG` section.

**Comment by zuxfoucault** [comment]
> This should be much more usable than the `ws` directory full of `COR` files.
Would `mne.bem.make_watershed_bem` generate `COR` files? I seem to not find one, or I couldn't recognize them.
> 
> @zuxfoucault could you update `changes/latest.rst` to mention this change? I guess it would go in the `BUG` section.

@larsoner Sure, and done!

**Comment by agramfort** [comment]
thx @zuxfoucault

**Pull request merged**
