### PR TITLE
MAINT: Use mamba in CIs

### PR DESCRIPTION
**Pull request by larsoner**
~~One way to move toward being able to recommend mamba is by including it in `environment.yml`, so I added it here.~~ I made our solvers use `mamba` by including it in the `setup-miniconda` action [according to the instructions here](https://github.com/marketplace/actions/setup-miniconda#example-6-mamba). Note that they even say it's experimental, and I'm assuming that's because `mamba` is moreso than the action itself:

> Example 6: Mamba
> Experimental! Use mamba to handle conda installs in a faster way. mamba-version accepts a version string x.y (including "*"). It requires you specify conda-forge as part of the channels, ideally with the highest priority.

FWIW @drammock Azure was already using `mamba env update` on Windows, IIRC to speed up the solve time.

### CODE REVIEW

**Comment by larsoner** [comment]
Okay, just asking it to install `mamba` as the solver broke things / created conflicts. This does not bode well for people trying `conda install -c conda-forge mamba` in their `base` environments :(

I'm going to try it now with better proper channel priority (as suggested in the `setup-miniconda` docs) and hope that works. I guess that's more in line with our instructions anyway, which suggest `--strict-channel-priority` at least some of the time.

**Comment by larsoner** [comment]
... apparently this works on macOS but not Linux. I'm tempted to close for now and revisit in a few months hoping some conda, mamba, and/or `setup-miniconda` fixes land in the meantime

**Comment by drammock** [comment]
using mambaforge fixed compat-old and compat-minimal. Only notebook is failing now, with:
```
 Warning: 
  UnsatisfiableError: The following specifications were found
  to be incompatible with the existing python installation in your environment:
  
  Specifications:
  
    - defaults/linux-64::brotlipy==0.7.0=py310h7f8727e_1002[md5=a8dfa5aefcc49d5e78000b16d2b7714e] -> python[version='2.7.*|3.5.*|3.6.*|3.6.12|3.6.12|3.7.10|3.7.10|3.7.12|3.8.12|3.8.16|3.9.16|>=3.11,<3.12.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|3.9.10|>=3.6,<3.7.0a0|3.7.9|3.6.9|3.6.9|3.6.9|>=2.7,<2.8.0a0|3.6.9|>=3.5,<3.6.0a0|3.4.*',build='0_73_pypy|4_73_pypy|0_73_pypy|1_73_pypy|0_73_pypy|5_73_pypy|5_73_pypy|3_73_pypy|2_73_pypy|1_73_pypy']
    - defaults/linux-64::conda-content-trust==0.1.3=py310h06a4308_0[md5=69f1c06e7c9ce52d4a9b5787c74cac20] -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.11,<3.12.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0|3.4.*']
    - defaults/linux-64::cryptography==38.0.1=py310h9ce1e76_0[md5=f9aba54a3e93124c31846c700f502f9d] -> python[version='3.6.12|3.6.12|3.7.10|3.7.10|3.7.12|3.8.12|3.8.16|3.9.16|>=3.11,<3.12.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|3.9.10|>=3.6,<3.7.0a0|3.7.9|3.6.9|3.6.9|3.6.9|>=2.7,<2.8.0a0|3.6.9',build='0_73_pypy|4_73_pypy|0_73_pypy|1_73_pypy|0_73_pypy|5_73_pypy|5_73_pypy|3_73_pypy|2_73_pypy|1_73_pypy']
    - defaults/linux-64::ruamel.yaml==0.17.21=py310h5eee18b_0[md5=0a54e321078e043b72b6f68d10472b62] -> python[version='>=3.11,<3.12.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0']
  
  Your python: defaults/linux-64::python==3.10.8=h7a1cb2a_1[md5=c50aebbb632aea22b13bd654dfe80a5b]

[... a lot more omitted]
```

**Comment by drammock** [comment]
All green! mambaforge FTW. @larsoner merge if happy.

**Comment by drammock** [comment]
actually, we should check the job timings. maybe I'm reading things wrong but it looks like the usage minutes went *up* for the last run of CIs on this PR, when compared to recent runs on #11473 (a randomly chosen PR for comparison). IDK how to query GH Actions timings efficiently though, maybe you do?

**Comment by larsoner** [comment]
Okay I restarted linux_conda, compat_minimal, and compat_old and will check against runs from https://github.com/mne-tools/mne-python/pull/11479 which are happening concurrently

**Comment by larsoner** [comment]
Timings are 6min / 2min / 2min, respectively, on this PR, and 8min / 1min / 1min on #11479 (roughly). But macOS improves from 11 to 7 min on this PR, too, which is nice. Since it's at least as fast overall and tests `mamba` let's merge and continue!

**Comment by agramfort** [comment]
🙏 @larsoner

**Pull request merged**
