### PR TITLE
MRG+1: Use read_mat for eeglab

### PR DESCRIPTION
**Pull request by larsoner**
I have changed the code to use `read_mat`. So far I noticed that I needed `uint16_codec` to be exposed to `read_mat`, which I added. Now all the `.mat` reading versions work. However, there are failures in the `.h5` versions of the files, indicating a likely problem with `read_mat`'s conversion.

@thht since the problems are with the `h5`-to-dict conversion, do you have time to take a quick look? It wasn't obvious from the traceback or `pymatreader` code what changes would be necessary to make it work.

### CODE REVIEW

**Comment by larsoner** [comment]
For example:

https://travis-ci.org/mne-tools/mne-python/jobs/401817551#L3346

**Comment by thht** [comment]
hi,
last week saw the arrival of my baby son. so, as you can imagine, things are a bit crazy right now. i think, i should be able to take a look at it at the weekend or latest beginning of next week. i hope that this is not too late.

**Comment by larsoner** [comment]
Congrats @thht! No rush from my end on this

**Comment by larsoner** [comment]
Ping @thht this might be a fun distraction from your lack of sleep :)

**Comment by thht** [comment]
@larsoner : working on it ;-)

**Comment by thht** [comment]
ok, good news. i managed to recreate the problem in pymatreader directly, wrote a test for it and the problem seems to be fixed.

i need to do some final work on pymatreader now but you can expect a pull request with the updated code latest tomorrow.

**Comment by larsoner** [comment]
Great thanks @thht !

**Comment by thht** [comment]
ok, i just did the PR: #5367 

sorry for the delay.

**Comment by larsoner** [comment]
No problem, thanks for tackling it! I'll merge your PR, rebase this, and continue

**Comment by larsoner** [comment]
Okay tests pass now. @smgutstein can you try with some of your data to see if this works?

@mmagnuski @jona-sassenhagen it looks like you have worked on the EEGLAB bits previously, do you have time to check quickly if this works on some of your files? In particular checking the `chanlocs` behavior would be good.

**Comment by mmagnuski** [comment]
Sure, I can test today. I don't think I have any files in the new matlab format, but I can try re-saving some older ones.

**Comment by larsoner** [comment]
That would be good. Also checking that events, channel locations, etc. are still correct in old and new formats would help.

**Comment by mmagnuski** [comment]
I am able to read my current files without any problems. Will check on data in new-format once I have access to matlab (in a few hours).

**Comment by mmagnuski** [comment]
I've spotet some potential problems and finally have access to matlab so I'll give an update soon.

**Comment by smgutstein** [comment]
Sorry. Am on vacation and only "semi-computercado". Will be back 1st week
of August and take a look then.

**Comment by mmagnuski** [comment]
Ok, the "problem" was something that changed not so long ago in mne, but that does not seem relevant to this PR.
EEGLAB changes event latencies to floats after resampling (to indicate their original position in the original sampling frequency). If there was a boundary event at the beginning of the file (which usually have a float latency like `163.5` to indicate that they occur in between samples) that event has latency of `0.5` and after downsampling that value will drop down. Mne python rounds this value to 0 while reading, and then turns it to -1, when correcting for 1-based matlab indexing. Then the user gets this kind of error:
```python-traceback
Traceback (most recent call last):

  File "<ipython-input-2-7dcf75535eb9>", line 10, in <module>
    raw1 = mne.io.read_raw_eeglab(op.join(data_dir, fname1))

  File "C:\src\mne-python\mne\io\eeglab\eeglab.py", line 193, in read_raw_eeglab
    verbose=verbose, uint16_codec=uint16_codec)

  File "<string>", line 2, in __init__

  File "C:\src\mne-python\mne\utils.py", line 724, in verbose
    return function(*args, **kwargs)

  File "C:\src\mne-python\mne\io\eeglab\eeglab.py", line 350, in __init__
    event_id_func=event_id_func)

  File "C:\src\mne-python\mne\io\eeglab\eeglab.py", line 671, in read_events_eeglab
    raise ValueError('At least one event sample index is negative. Please'

ValueError: At least one event sample index is negative. Please check if EEG.event.sample values are correct.
```

**Comment by mmagnuski** [comment]
Ok, I am to blame: #4951 😞

**Comment by larsoner** [comment]
Does everything else seem to work okay? That would be great!

I would say if the event is `>= -1` emit a warning (about downsampling, etc.). If it's `< -1` then throw this error. WDYT?

**Comment by mmagnuski** [comment]
I checked again, removing that one boundary event, and can confirm that I was not able to find any other problems. I also think we have pretty good tests of eeglab reading functionality, so I trust their greenness. :) BTW - do we have tests for reading older matlab format, saving in hdf5 and reading back the same file?

**Comment by larsoner** [comment]
That's how the h5 flies were created. As long as the existing tests were sufficiently exhaustive this should effectively be tested already

**Comment by mmagnuski** [comment]
Great! I checked chanlocs and events as you previously asked and everything as it was before (before_PR_oldformat == after_PR_oldformat == after_PR_newformat).
And I agree about emitting warnings for latency == -1.

**Comment by mmagnuski** [comment]
Yes, I've read through the changes now and I'm +1. I've also learned about `tmpdir` in pytest thanks to your changes so that's +1.5 altogether :) I can open a PR for negative latency, but once this PR gets merged (it will be easier with testing for example).

**Comment by agramfort** [comment]
if there is no what's new update to make feel free to merge.

**Comment by larsoner** [comment]
There is, let me add and merge

**Comment by larsoner** [comment]
@smgutstein @thht can you make sure this is okay or offer alternative URLs, this is the best I could do with 2 minutes of Google

https://github.com/mne-tools/mne-python/pull/5326/commits/fa0733b7e0bff57db7a802f631cf0dcdfd3831f8

**Comment by thht** [comment]
@larsoner do you mean the links to pymatreader and my username? those are fine. if you were referring to something else, let me know...

Am 30. Juli 2018 21:58:26 MESZ schrieb Eric Larson <notifications@github.com>:
>@smgutstein @thht can you make sure this is okay or offer alternative
>URLs, this is the best I could do with 2 minutes of Google
>
>https://github.com/mne-tools/mne-python/pull/5326/commits/fa0733b7e0bff57db7a802f631cf0dcdfd3831f8
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mne-tools/mne-python/pull/5326#issuecomment-408990353

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by larsoner** [comment]
In it goes, @smgutstein if the URL / name is wrong feel free to make a small PR to `master` to fix it!

**Comment by thht** [comment]
@larsoner i just made a PR for updating pymatreader:  #5379

Am 30. Juli 2018 21:58:26 MESZ schrieb Eric Larson <notifications@github.com>:
>@smgutstein @thht can you make sure this is okay or offer alternative
>URLs, this is the best I could do with 2 minutes of Google
>
>https://github.com/mne-tools/mne-python/pull/5326/commits/fa0733b7e0bff57db7a802f631cf0dcdfd3831f8
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mne-tools/mne-python/pull/5326#issuecomment-408990353

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Pull request merged**
