### PR TITLE
Refine high-pass filter warning in tutorial

### PR DESCRIPTION
**Pull request by cbrnr**
As discussed in #4394 with @jona-sassenhagen, I changed the text in order to not imply that HP filtering is problematic _only_  for ERP/ERF analysis.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
I killed the CI builds except CircleCI and Travis-nodata (PEP checks).

@jona-sassenhagen are you happy with this?

**Comment by jona-sassenhagen** [comment]
Yes. 
Sorry, I'm German, I'm obliged to nitpick :D

**Comment by agramfort** [comment]
@jona-sassenhagen merge if you're happy

**Comment by jona-sassenhagen** [comment]
Done. Thanks @cbrnr

**Pull request merged**
