### PR TITLE
FIX: add implicit overwrite h5

### LINKED ISSUE #3774: BUG/API: overwrite flag not passed in SourceEstimate.save with ftyp='h5'
The title says it all.

cc @Eric89GXL

### PR DESCRIPTION
**Pull request by dengemann**
fixes and closes #3774.

cc @Eric89GXL

### CODE REVIEW

**Comment by Eric89GXL** [comment]
At some point we should add an `overwrite` parameter to `stc.save` as a slightly better fix

**Comment by Eric89GXL** [comment]
@dengemann there were legitimate CI failures like

https://travis-ci.org/mne-tools/mne-python/jobs/176826295#L3082

Merged too quickly on this one

**Comment by jaeilepp** [comment]
Fixed on master.

**Comment by dengemann** [comment]
I apologise, it was a slip, I did not mean to merge.
For the overwrite parameter I'm a bit unhappy, first of all I've never used
overwrite=False, and the not every function has this parameter.
I would not mind removing this parameter alltogether.

**Comment by dengemann** [comment]
Thank you!

**Comment by Eric89GXL** [comment]
It's a pretty nice safeguard. It's not everywhere but it is probably in
more places than not. I think we should try to have it everywhere.

**Comment by agramfort** [comment]
loo priority for me

**Pull request merged**
