### PR TITLE
[MRG+2] Annotation aware eog/ecg epochs.

### PR DESCRIPTION
**Pull request by jaeilepp**
Cf. mailing list.

I'm wondering if ``compute_raw_covariance`` should be annotation aware too.

### CODE REVIEW

**Comment by agramfort** [comment]
yes for compute_raw_covariance

can you add the version added?

**Comment by agramfort** [comment]
LGTM

can you make travis happy? and update what's new?

thx

**Comment by Eric89GXL** [comment]
@jaeilepp ready for merge from your end? If so, I'll merge once Travis comes back happy

**Comment by jaeilepp** [comment]
Yes, should be good to go.

**Comment by Eric89GXL** [comment]
FYI @drammock this should help fix your mailing list issue

**Comment by Eric89GXL** [comment]
Thanks @jaeilepp

**Pull request merged**
