### PR TITLE
Fix GDF NumPy >= 2

### LINKED ISSUE #12907: GDF reader incompatible with NumPy >= 2
As reported in our forum [here](https://mne.discourse.group/t/error-loading-gdf-file-with-mne-python-integer-256-out-of-bounds-for-uint8/10410) and [here](https://mne.discourse.group/t/overflow-error-when-trying-to-read-gdf/10432), GDF files produce an error with NumPy >= 2 (reproducible e.g. using [this dataset](http://bnci-horizon-2020.eu/database/data-sets/001-2017/S01_MI.zip)):

```
>>> raw = mne.io.read_raw("/Users/clemens/Downloads/S01_MI/motorimagination_subject1_run1.gdf")
Extracting EDF parameters from /Users/clemens/Downloads/S01_MI/motorimagination_subject1_run1.gdf...
GDF file detected
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    raw = mne.io.read_raw("/Users/clemens/Downloads/S01_MI/motorimagination_subject1_run1.gdf")
  File "/Users/clemens/Projects/mne-python/mne/io/_read_raw.py", line 180, in read_raw
    return reader(fname, **kwargs)
  File "/Users/clemens/Projects/mne-python/mne/io/edf/edf.py", line 1902, in read_raw_gdf
    return RawGDF(
        input_fname=input_fname,
    ...<6 lines>...
        verbose=verbose,
    )
  File "<decorator-gen-207>", line 12, in __init__
  File "/Users/clemens/Projects/mne-python/mne/io/edf/edf.py", line 294, in __init__
    info, edf_info, orig_units = _get_info(
                                 ~~~~~~~~~^
        input_fname, stim_channel, eog, misc, exclude, True, preload, include
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/clemens/Projects/mne-python/mne/io/edf/edf.py", line 538, in _get_info
    edf_info, orig_units = _read_header(
                           ~~~~~~~~~~~~^
        fname, exclude, infer_types, include, exclude_after_unique
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/clemens/Projects/mne-python/mne/io/edf/edf.py", line 516, in _read_header
    return _read_gdf_header(fname, exclude, include), None
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/clemens/Projects/mne-python/mne/io/edf/edf.py", line 1446, in _read_gdf_header
    n_events = n_events + ne[i] * 2 ** (i * 8)
                          ~~~~~~^~~~~~~~~~~~~~
OverflowError: Python integer 256 out of bounds for uint8
```

### PR DESCRIPTION
**Pull request by cbrnr**
Fixes #12907.

### CODE REVIEW

**Review by cbrnr — COMMENTED** [review]
This fixes the issue encountered e.g. with [this dataset](http://bnci-horizon-2020.eu/database/data-sets/001-2017/S01_MI.zip).

However, and this is likely unrelated, I was wondering why the log contains `next(self.gen)`:

```
>>> raw = mne.io.read_raw("/Users/clemens/Downloads/S01_MI/motorimagination_subject1_run1.gdf")
Extracting EDF parameters from /Users/clemens/Downloads/S01_MI/motorimagination_subject1_run1.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
F3, F1, Fz, F2, F4, FFC5h, FFC3h, FFC1h, FFC2h, FFC4h, FFC6h, FC5, FC3, FC1, FCz, FC2, FC4, FC6, FTT7h, FCC5h, FCC3h, FCC1h, FCC2h, FCC4h, FCC6h, FTT8h, C5, C3, C1, Cz, C2, C4, C6, TTP7h, CCP5h, CCP3h, CCP1h, CCP2h, CCP4h, CCP6h, TTP8h, CP5, CP3, CP1, CPz, CP2, CP4, CP6, CPP5h, CPP3h, CPP1h, CPP2h, CPP4h, CPP6h, P3, P1, Pz, P2, P4, PPO1h, PPO2h, eog-l, eog-m, eog-r, thumb_near, thumb_far, thumb_index, index_near, index_far, index_middle, middle_near, middle_far, middle_ring, ring_near, ring_far, ring_little, litte_near, litte_far, thumb_palm, wrist_bend, roll, pitch, gesture, armeodummy, armeodummy, armeodummy, armeodummy, armeodummy, armeodummy, armeodummy, armeodummy, armeodummy, armeodummy, armeodummy, armeodummy, armeodummy
Creating raw.info structure...
/Users/clemens/.local/share/uv/python/cpython-3.12.7-macos-aarch64-none/lib/python3.12/contextlib.py:144: RuntimeWarning: Channel names are not unique, found duplicates for: {'armeodummy'}. Applying running numbers for duplicates.
  next(self.gen)
```

Or is it just my setup?

**Review by agramfort — APPROVED** [review]

**Comment by larsoner** [comment]
Thanks @cbrnr !

**Comment by cbrnr** [comment]
I forgot to add the "backport-candidate" label to this PR (I just slapped it on the issue), so I assume this has not been backported automatically?

**Comment by larsoner** [comment]
@MeeseeksDev backport to maint/1.8

**Pull request merged**
