### PR TITLE
MRG, FIX: Modernize coreg tests

### PR DESCRIPTION
**Pull request by larsoner**
Seeing if we can make some progress on #5728, first by modifying the test infrastructure we use.

### CODE REVIEW

**Comment by larsoner** [comment]
@thht @fraimondo @Hellg0re @dasdiptyajit can you see if this fixes your `mne coreg` subject-switching segfault described in #5728 and #5600 ? Locally it does for me interactively, and in the modified test (which showed the same problem on my machine at least).

**Comment by larsoner** [comment]
@jasmainak can you see if you can replicate the problem in #5728 on `master` and see if this fixes it? For me I could reproduce by switching sample->fsaverage->sample, but really the problematic case seems to be when you go from a subject with N vertices to one with fewer than N (head shape, I think) vertices.

**Comment by jasmainak** [comment]
@larsoner I am able to reproduce the problem and your branch fixes it.

However, while doing this, I discovered another issue. It seems that the anatomy is loaded into the GUI only if I set the SUBJECTS_DIR first before opening ipython. The selection of SUBJECTS_DIR from the GUI does not seem to work for me.

**Comment by larsoner** [comment]
Let's open a separate issue for that

**Comment by larsoner** [comment]
FYI the upstream fix for the bug fixed by this PR is https://github.com/enthought/mayavi/pull/771

**Pull request merged**
