### PR TITLE
API: Change name to qt

### PR DESCRIPTION
**Pull request by larsoner**
Closes https://github.com/mne-tools/mne-qt-browser/issues/45

cc @marsipu

### CODE REVIEW

**Comment by mmagnuski** [comment]
Looks good, but I think it would be nice to mention somewhere in the docs or docstrings that pyqtgraph is used when selecting the 'qt' backend.

**Review by agramfort — APPROVED** [review]

**Comment by larsoner** [comment]
> I think it would be nice to mention somewhere in the docs or docstrings that pyqtgraph is used when selecting the 'qt' backend.

The fact that it uses `pyqtgraph` is more of an implementation detail -- the key is really that it uses `mne-qt-browser`. Hopefully this part is in our docs already...

**Comment by larsoner** [comment]
> Hopefully this part is in our docs already...

It is not! Pushing a commit now that adds it to `set_browser_backend`

**Comment by hoechenberger** [comment]
Amazing, thanks!

**Pull request merged**
