### PR TITLE
MRG, FIX: HDF5 datetime bug

### LINKED ISSUE #7283: plotting: address mpl deprecation warning when calling plt.subplots() several times.
I am plotting several topographies using `mne.viz.plot_evoked_topomap` so that for different conditions I can get a single figure with:

- each row is a condition
- each column is a different time point
- each panel is a topography

this is my code:

```Python
def plot_topos(erp_dict):
    """Plot a topography over time."""
    # Figure settings
    step = 0.1
    times = np.arange(-0.1, 0.8, step)
    average = step
    
    # Set up figure
    n_keys = len(erp_dict)
    fig, ax = plt.subplots(n_keys, len(times), figsize=(15, 2*n_keys))
    ax = np.atleast_2d(ax)
    
    for ii, key in enumerate(erp_dict):
        # Form grand average
        ga = mne.grand_average(erp_dict[key])        
        mima = np.abs(ga.data).max() * 1e6
        mne.viz.plot_evoked_topomap(ga, times=times, vmin=-mima, vmax=mima,
                                    axes=ax[ii, :], colorbar=True)
        ax[ii, 0].set_ylabel(key)
        
        
    fig.suptitle('Sample ERP')

    return fig
```

Using this, I run into the following warning:

> MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.

I think this is triggered by the following line:

https://github.com/mne-tools/mne-python/blob/f474eb196eca50104f09948c6a4215d628a971f5/mne/viz/topomap.py#L1682

We can probably fix it by changing the line as follows:

```diff
-cax = plt.subplot(1, n_fig_axes + 1, n_fig_axes + 1)
+cax = plt.gcf().add_subplot(1, n_fig_axes + 1, n_fig_axes + 1)
```

Has anyone else encountered this issue? Is this a sensible solution? Should I make a PR?

### PR DESCRIPTION
**Pull request by agramfort**
closes #7283

@larsoner any suggested way to fix this?

### CODE REVIEW

**Comment by agramfort** [comment]
shouldn't we add a test to h5io to make sure IO roundtrip is correct for datetime?

**Comment by larsoner** [comment]
Like this?

https://github.com/h5io/h5io/pull/43

**Comment by agramfort** [comment]
yes perfect !

not sure why CIs complain though

**Comment by larsoner** [comment]
I wonder if this is the problem that @GuillaumeFavelier has been seeing, just with a clearer traceback now. I'll try decorating a test to see if I can fix it, and maybe it will magically fix his vertex-picking PR, too.

https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=5345&view=logs&jobId=b195a6e3-7484-5943-e627-0b35c27605d6&j=b195a6e3-7484-5943-e627-0b35c27605d6&t=e39460f3-8bf4-5a9c-a10e-ca10a5c92a7f

**Comment by agramfort** [comment]
Thx @larsoner

**Pull request merged**
