### PR TITLE
STY: prefer _DefaultEventParser to _Counter

### PR DESCRIPTION
**Pull request by massich**
Things I wanted to ask in #6326 but I didn't have the chance. 

It avoids returning `lambda: None` + adds a test in case `event_id='random string'`. What I did not got away with is a form to not pass `raw` to `_check_event_id`. (which can be big and so on). @larsoner can you see a way? Maybe defining the function within or braking it again in two functions which we end up at the same place as we started.

Anyways, feel free to push in the branch or close

### CODE REVIEW

**Comment by agramfort** [comment]
why is the size of raw a problem? it's passed by reference. What do I miss. Patch looks good

**Comment by massich** [comment]
It's just me getting confused. https://docs.python.org/3/faq/programming.html#how-do-i-write-a-function-with-output-parameters-call-by-reference 
Python passes the parameters by assignment. Which is a way to say that they pass the reference by value. (so yes some sort of passed by reference)

**Comment by massich** [comment]
This would make codecov more happy, but I don't think is more readable. 
```py
def __call__(self, description, offset=1):
    if description not in self.event_ids:
        out = offset + len(self.event_ids)
        self.event_ids[description] = out
    else:
        out = self.event_ids[description]

    return out
```

Is there any function in dict that does this and I'm not aware of it?

**Comment by larsoner** [comment]
```
    if description not in self.event_ids:
        out = offset + len(self.event_ids)
        self.event_ids[description] = out
    else:
        out = self.event_ids[description]
```
is equiv to
```
    self.event_ids[description] = self.event_ids.get(description, offset + len(self.event_ids))
    out = self.event_ids[description]
```

**Comment by massich** [comment]
```sh
~/code/mne-python refactor_digitation* 2m 55s
(mne) ❯ ipython
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %paste                                                                                                                              
def xx():
    dd = dict()
    for _ in range(50):
        if 'a' not in dd:
            dd['a'] = len(dd)+1
        out = dd['a']
    for _ in range(50):
        dd = dict()
        if 'a' not in dd:
            dd['a'] = len(dd)+1
        out = dd['a']

def yy():
    dd = dict()
    for _ in range(50):
        dd['a'] = dd.get('a', len(dd)+1)
        out = dd['a']
    for _ in range(50):
        dd['a'] = dd.get('a', len(dd)+1)
        out = dd['a']
## -- End pasted text --

In [2]: %timeit -n100 -r100 xx()                                                                                                            
11.5 µs ± 2.31 µs per loop (mean ± std. dev. of 100 runs, 100 loops each)

In [3]: %timeit -n100 -r100 yy()                                                                                                            
14.9 µs ± 2.42 µs per loop (mean ± std. dev. of 100 runs, 100 loops each)

In [4]: %timeit -n100 -r100 xx()                                                                                                            
10.6 µs ± 701 ns per loop (mean ± std. dev. of 100 runs, 100 loops each)

In [5]: %timeit -n100 -r100 yy()                                                                                                            
The slowest run took 7.67 times longer than the fastest. This could mean that an intermediate result is being cached.
17 µs ± 13 µs per loop (mean ± std. dev. of 100 runs, 100 loops each)

In [6]: %timeit -n100 -r100 xx()                                                                                                            
11.2 µs ± 1.74 µs per loop (mean ± std. dev. of 100 runs, 100 loops each)

In [7]: %timeit -n100 -r100 yy()                                                                                                            
14.9 µs ± 3.33 µs per loop (mean ± std. dev. of 100 runs, 100 loops each)

In [8]: %timeit -n100 -r100 xx()                                                                                                            
11.3 µs ± 1.58 µs per loop (mean ± std. dev. of 100 runs, 100 loops each)

In [9]: %timeit -n100 -r100 yy()                                                                                                            
14.5 µs ± 1.57 µs per loop (mean ± std. dev. of 100 runs, 100 loops each)
```

**Comment by massich** [comment]
I'll merge as it is.

**Pull request merged**
