### PR TITLE
[MRG] Picks argument to layout.plot.

### PR DESCRIPTION
**Pull request by jaeilepp**
Closes https://github.com/mne-tools/mne-python/issues/4093

### CODE REVIEW

**Comment by agramfort** [comment]
LGTM

can you update what's new?

**Comment by Eric89GXL** [comment]
LGTM. @kambysese can you check to see if this works for you?

**Comment by kambysese** [comment]
Great! This works for me, thank you all very much.

**Comment by Eric89GXL** [comment]
Thanks @jaeilepp

**Pull request merged**
