### PR TITLE
ENH whats_new, test_add_htmls_to_section

### PR DESCRIPTION
**Pull request by teonlamont**
Minor tweaks to #1859

### CODE REVIEW

**Comment by dengemann** [comment]
LGTM!

**Comment by mainakjas** [comment]
how much time does it save to change from `decim=2` to `decim=4`?

**Comment by teonlamont** [comment]
i ran each twice, it seems that with current default decim=2, it finishes
in 75s, and 86s on my box, and with decim = 4, takes 90s, 54s. so i can't
really draw any conclusions in terms of performance.

-teon

**Comment by mainakjas** [comment]
75 s or 86 s is a lot! can you decimate by more?

**Comment by agramfort** [comment]
!!!!!! Use decim=50 or so. We fight all the time to keep test time low. Please make it run in a couple of seconds or update an existing test to keep test time almost constant

**Comment by teonlamont** [comment]
lol...i've never really used the _render_bem function from the parse_folder before and I didn't realize that the decimation made that big of a diff. decim=50, test time = 30.149s.

**Comment by dengemann** [comment]
Can you select the highest decimation value that still produces a passing test?

**Comment by teonlamont** [comment]
so @mainakjas just discussed the test and we noticed that _render_bem is already being tested in test_render_mri so instead of reproducing this, we are just testing an html string and whether it is properly added to the report

**Comment by Eric89GXL** [comment]
Is this good to go, then?

**Comment by teonlamont** [comment]
I believe so

-teon

**Comment by dengemann** [comment]
Glad to now have the string 'awesome' in our code base!

**Comment by agramfort** [comment]
Cool. Please fix ASAP

Thx

**Comment by dengemann** [comment]
> Please fix ASAP

?

**Comment by mainakjas** [comment]
AWESOME in caps :)

**Comment by agramfort** [comment]
Forget it...

**Comment by mainakjas** [comment]
test takes 2 seconds to run now

**Comment by dengemann** [comment]
> test takes 2 seconds to run now

This is real progress!

**Pull request merged**
