### PR TITLE
Fix #2892, if tmin or tmax are none or infinite, use first (or last) …

### LINKED ISSUE #2892: BUG: utils._time_mask is not well tested enough
the defaults with None will create np.inf, these willl generate infs in turn if sfreq is None, and give you masks full of false.

A potential fix would be to replace np.inf with times[-1] and -np.inf with times[0]

cc @jaeilepp @Eric89GXL I think your edits are behind this, in November 2015 or so this code was still working under the described conditions.

```Python
mne.utils._time_mask(np.arange(5))
# array([False, False, False, False,  True], dtype=bool)
# but should be  array([True, True, True, True,  True], dtype=bool)
```

### PR DESCRIPTION
**Pull request by fraimondo**
…time in array

### CODE REVIEW

**Comment by dengemann** [comment]
LGTM!

**Comment by Eric89GXL** [comment]
LGTM, @jaeilepp feel free to merge if you're happy and the CIs are too

**Comment by agramfort** [comment]
LGTM 2

**Comment by jaeilepp** [comment]
thx @fraimondo

**Pull request merged**
