### PR TITLE
FIX: Split dev and stable builds

### PR DESCRIPTION
**Pull request by Eric89GXL**
Split output dirs to facilitate https://github.com/mne-tools/mne-tools.github.io

### CODE REVIEW

**Comment by agramfort** [comment]
LGTM

@mluessi ok? as it will break your build system...

**Comment by dgwakeman** [comment]
@haribharadwaj is this you now?

**Comment by Eric89GXL** [comment]
ahh, true... I could revert the change so that `dev` builds into `html` instead of `html_dev` but `stable` can still build into `html_stable`. That will leave @mluessi's system in tact, and we can switch to this once we've fully migrated our build process. Sound good?

**Comment by agramfort** [comment]
sounds good

btw I pushed to master on mne-tools web repo

**Comment by Eric89GXL** [comment]
Great! So it looks like a decent setup then? Did you copy to (and then push) dev, stable, or both?

**Comment by agramfort** [comment]
I updated the makefile :)

**Comment by Eric89GXL** [comment]
Made it so that stable goes in `html_stable` and dev in `html` for now, feel free to merge @agramfort

**Pull request merged**
