### PR TITLE
hotfix elc reader

### PR DESCRIPTION
**Pull request by sappelhoff**
- follow up to #12830 
- see also #12837 

@larsoner a proper test to include would be to add to each pytest.parametrize item the expected channel names that the montage should contain. Do you think that's overkill, or should we do it?

### CODE REVIEW

**Comment by agramfort** [comment]
you don't have a file to test this?

**Comment by sappelhoff** [comment]
> you don't have a file to test this?

I do, but in the tests we do it as follows:

https://github.com/mne-tools/mne-python/blob/f3a3ca4430e1d4b9c539e7949c946f4f83bdb43f/mne/channels/tests/test_montage.py#L305-L327

☝️ I basically added the gist of the contents of the test file I have here

**Comment by agramfort** [comment]
I would personally add the test

**Comment by larsoner** [comment]
Added a test using parts of the failing file and touched the problematic example, marking for merge-when-green, thanks in advance @sappelhoff !

**Pull request merged**
