### PR TITLE
RawFIFF -> RawFIF

### PR DESCRIPTION
**Pull request by teonlamont**
follow up to #1881.

### CODE REVIEW

**Comment by agramfort** [comment]
LGTM assuming we don't need to keep backward compat for this.

I assume nobody used this class directly.

Let's see if travis is happy

**Comment by teonlamont** [comment]
I don't think this should break anyone's code. thoughts @Eric89GXL

**Comment by dengemann** [comment]
Thanks!

**Comment by Eric89GXL** [comment]
It's possible I used it somewhere but I can easily fix it, fine with me

**Pull request merged**
