### PR TITLE
MAINT: Bump minimums

### LINKED ISSUE #10977: Update theme pin and check docs build
**About a week before a new release**, make a PR that updates our pin of `pydata-sphinx-theme` to the theme's current `HEAD` commit, and do a full docs build (`[circle full]`).  If anything looks awry, do some combination of 

1. working backwards on the theme's tree until you find a commit that works/looks good on our site
2. reporting bugs to the theme (and ideally fixing them and updating the commit hash accordingly)

When you're satisifed that our dev site looks good, merge the PR with the new pin, but **DO NOT CLOSE THIS ISSUE!**  Instead, just bump its milestone so that the process will repeat at the next release.

Places to update the pin:

- `requirements_doc.txt`
- sometimes in the past we've done something different in `tools/circleci_dependencies.sh` so double-check if a change is needed there

### PR DESCRIPTION
**Pull request by larsoner**
Bumps min reqs in README.rst to those ~2 years old this April, and adjusts/removes code shims for deps lower than those. Also `nibabel` is now required for `read_surface` which I think is reasonable (it is pure Python and has been stable and pip/conda-installable for years now).

Closes #10977

### CODE REVIEW

**Comment by larsoner** [comment]
... if we make anything a new core dep in the future, we could consider doing it with nibabel. We could remove a lot of checks by doing it. And maintenance overhead shouldn't be bad because it's a pure-python dependency with a slow-moving deprecation cycle.

**Comment by drammock** [comment]
> `git grep matplotlib.*version` shows a few more:

I can tackle those if you don't have time.

**Comment by larsoner** [comment]
Nice catch! I think I got those now

**Review by drammock — APPROVED** [review]
will mark for merge-when-green; thx @larsoner

**Comment by larsoner** [comment]
```
_________ test_plot_evoked_topomap_units[testing_data-None-None-\xb5V] _________
mne/viz/tests/test_topomap.py:240: in test_plot_evoked_topomap_units
    assert len(cbar) == 1
E   assert 0 == 1
E    +  where 0 = len([])
```
I'll revert that last commit. The comment didn't specify/know the matplotlib version where we could use the simpler version... apparently it's something after 3.4!

**Review by agramfort — APPROVED** [review]
❤️

**Comment by larsoner** [comment]
pydata-sphinx-theme building failed on Windows and 0.13.1 is now out (as of about a week ago) so I'm going to pin to that. It gives us about a month to see issues with dev docs and either fix them before release or relax/revert the pin. In the meantime it'll speed up the doc builds

**Comment by drammock** [comment]
> pydata-sphinx-theme building failed on Windows and 0.13.1 is now out (as of about a week ago) so I'm going to pin to that. 

FYI I've been (quietly) trying to fix our site config to look good with 0.13.1. The one thing I haven't been able to fix yet is that we somehow lost margin/padding between the gallery tiles on the homepage, but it actually happened a while ago and I haven't had time to track down what PST change triggered it (I suspect it was the bootstrap4 -> bootstrap5 migration). So feel free to ignore that particular doc issue.

**Comment by larsoner** [comment]
Circle is having a bad day so merged manually

**Pull request merged**
