### PR TITLE
MAINT: Use github_changelog_generator for release notes

### LINKED ISSUE #11508: MAINT: Improve changelog documentation process
To aid in releases and PRs, it would be nice not to have to do so much changelog management. In particular, it would be great if:

1. We didn't have to tell people to add anything to `doc/changes/latest.inc` 
2. A changelog could be (at least nearly) automatically generated

Ideas:

- In sphinx-gallery we use [github-changelog-generator](https://github.com/github-changelog-generator/github-changelog-generator) in between releases. You label PRs (before or after merge!) to get them correctly categorized as enhancement/bug. I *think* you can even change the PR title *after the merge* to then have that text used in the changelog entry.

Clearly this list is incomplete :) @drammock or others feel free to add other ideas up here after commenting about them below

### PR DESCRIPTION
**Pull request by larsoner**
Closes #11508

- [x] Get basics in
- [ ] Tweak aesthetics
- [ ] Add post-processing for mne.* resolution
- [ ] Fix "Co-Authored-By" omission
- [ ] Fix removal of last couple of lines
- [ ] Turn into GitHub action that runs every night before the doc build (maybe)
- [ ] Merge after 1.6 is released

| main | PR |
| -- | -- |
| Screenshot 2023-10-02 at 10 18 40 PM | Screenshot 2023-10-03 at 12 01 23 AM |

We could in theory also change these to actual names, but I don't mind leaving that for `doc/authors.html` instead.

### CODE REVIEW

**Comment by drammock** [comment]
LGTM so far. would be good to read `Co-Authored-By` and list multiple authors for PRs that have them

**Comment by cbrnr** [comment]
It would be useful to discuss PR naming conventions, given that PR names will show up in the changelog. I'd get rid of any manual tags like starting with "FIX", "MAINT", "ENH", "[MRG]", etc., at least before a new release (e.g., "[MRG]" has been obsolete since draft PRs were introduced).

**Comment by larsoner** [comment]
> It would be useful to discuss PR naming conventions...

Agreed. The benefit of `github_changelog_generator` is that we can do this whenever we want, including now, and rerunning it will get the updated name. So this makes it so that instead of asking people to mess with the changelog before merge, we as maintainers ideally change it at merge time to reflect what we want the entry to look like, but if we get it wrong we can change it later if needed.

I also plan to do stuff like postprocess with regex `mne.*` to try to link to `:py:obj:` to get intersphinx links to get picked up.

> would be good to read Co-Authored-By and list multiple authors for PRs that have them

In principle this would require changing github-changelog-generator :( But I can try to fix it by postprocessing instead. This makes it seem like it might be faster at some point for us just to process the list of commits / PRs to `main` directly...

**Comment by drammock** [comment]
> It would be useful to discuss PR naming conventions, given that PR names will show up in the changelog. I'd get rid of any manual tags like starting with "FIX", "MAINT", "ENH", "[MRG]", etc., at least before a new release (e.g., "[MRG]" has been obsolete since draft PRs were introduced).

fortunately it is possible to change a PR title after it has been merged, without affecting the git history. So this allows the release manager to sanitize entries at release time. It would still be nice if we had explicit PR title conventions and if contributors and reviewers paid attention to them, but it's not a blocker if those aren't yet in place.

**Comment by cbrnr** [comment]
It is great that titles can always be changed at any time (so bad titles are definitely not a blocker), but it would be nice to have some conventions for good PR titles in place. Should we add this to the contributing guide? Or some other/better place?

**Comment by hoechenberger** [comment]
My changelog entries are often quite verbose as I'm usually (not always) trying to explain how that change will affect the user, and sometimes I mention how behavior now differs from before. I'm concerned that switching to a PR-title-based changelog, the changelog will become less usable (read: less user-friendly) as super long PR titles are impractical.

**Comment by hoechenberger** [comment]
> I'd get rid of any manual tags like starting with "FIX", "MAINT", "ENH", "[MRG]",

+1 on this one.

This is meta-information. If anything, this should be some kind of a "tag badge" or so, but it shouldn't appear as actual text as part of the changelog. Makes it super annoying to read.

**Comment by cbrnr** [comment]
> My changelog entries are often quite verbose as I'm usually (not always) trying to explain how that change will affect the user, and sometimes I mention how behavior now differs from before. I'm concerned that switching to a PR-title-based changelog, the changelog will become less useful (read: less user-friendly) as super long PR titles are impractical.

Good point. I guess we're trading automation for user-friendliness here. I'm not sure we can (and should) use anything other than PR titles for automatic generation, but the PRs are linked, so users can go and check them out. If you include an explanation of what the changes mean in the first post, I think this approach is still OK.

**Comment by hoechenberger** [comment]
> If you include an explanation of what the changes mean in the first post, I think this approach is still OK.

I don't think so. We currently do an awfully bad job at really telling users about new features and fixes in new releases beyond what's written in the changelog. If we now make things even harder to discover, UX gets even worse. Besides top comments in PRs often don't get updates as the PR objective changes following discussions and code review.

**Comment by drammock** [comment]
> super long PR titles are impractical.

Impractical enough to continue doing lots of manual work creating the changelog? I'd vote to try it and see how bad it is. Can you find an example merged PR and change its PR title to its changelog entry, and see if anything breaks?  Assume that Eric will be able to automatically put in the API crossrefs so you can even skip backticks and things like `:func:`.

**Comment by hoechenberger** [comment]
> Impractical enough to continue doing lots of manual work creating the changelog?

You're just shifting the manual work from modifying `latest.inc` to modifying the PR titles. I don't see how anyone gains anything here.

The problem with the backticks etc is mostly due to the unbearable syntax of RST, from which I suggested to move away many times :)

**Comment by hoechenberger** [comment]
Or let me put it this way:
If we can pledge to have better PR titles, then I might be okay with this change.

But realistically I just don't see it happen, and something like this (taken from the dev changelog) is … not practical **at all** as a PR title:

> Added functionality for linking interactive figures together, such that changing one figure will affect another, see [Using the event system to link figures](https://mne.tools/dev/auto_tutorials/visualization/20_ui_events.html#tut-ui-events) and [mne.viz.ui_events](https://mne.tools/dev/visualization.html#module-mne.viz.ui_events). Current figures implementing UI events are [mne.viz.plot_topomap()](https://mne.tools/dev/generated/mne.viz.plot_topomap.html#mne.viz.plot_topomap) and [mne.viz.plot_source_estimates()](https://mne.tools/dev/generated/mne.viz.plot_source_estimates.html#mne.viz.plot_source_estimates) ([#11685](https://github.com/mne-tools/mne-python/issues/11685) [#11891](https://github.com/mne-tools/mne-python/issues/11891) by [Marijn van Vliet](https://github.com/wmvanvliet))

**Comment by hoechenberger** [comment]
Another issue to consider is that we cannot use GitHub's review feature to propose change suggestions to PR titles, as opposed to `latest.inc`.

**Comment by cbrnr** [comment]
Maybe something else to consider: was it really that much work to ask each PR author to write a user-friendly changelog entry as the last step before the PR gets merged? For me, it's either a tradeoff if we really want automatic changelog generation, or if we would like to keep user-friendly explanations, then we're really only shifting the work from one place to another (so not worth it then IMO).

**Comment by larsoner** [comment]
> Another issue to consider is that we cannot use GitHub's review feature to propose change suggestions to PR titles, as opposed to latest.inc.

Correct, but we can just change them directly, which is easier from a maintainer's standpoint actually.

> Maybe something else to consider: was it really that much work to ask each PR author to write a user-friendly changelog entry as the last step before the PR gets merged?

Yeah, it's why we opened and discussed #11508 in the first place. Typically the flow involves many "gotchas". To name a few: often people don't add one -- this is true of almost all new contributors and even some experienced ones from time to time -- so we ask them to. (Doing it directly is a pain for us because they haven't touched the file, so we can't do it trivially from the GH interface.) Then they do it wrong with RST errors. Then we fix it by making a suggestion and committing it. If we're lucky, their PR gets merged before this creates a conflict. Often times there is a conflict. Then we resolve the conflict on GitHub, wait for CIs, and merge. Or worse, we forget entirely about adding the entry during review and only find out at release time by seeing `Authors` list that we create in `devel.rst` at release time *based on commits and thus PRs* have names that don't show up at the end of `devel.rst` changelog lines. There are at least one or two every release -- and this failsafe only works for new contributors, so some contributions/PRs by previous contributors have undoubtedly gone missing.

All of this takes maintainer time and CI resources that are better spent elsewhere, and is error prone at many stages.

> But realistically I just don't see it happen, and something like this (taken from the dev changelog) is … not practical at all as a PR title

This makes me think of a different solution which I think might save us some clicks but keep things as automated as possible. Instead of using titles, each PR can have in the top comment this (it can be in our PR template and it's trivial to write a GH action check to make sure it exists and isn't just the default message):
```
### Changelog entry

Add a brief (typically one-sentence) description of your changes here!
```
The `devel.rst`-generating action I'm thinking of writing could stop using `github_changelog_generator` (which is actually a bit of a pain) and instead directly parse the labels and PR's top-comment for this `### Changelog entry` line and create/update `devel.rst` entries from them, including `newcontrib` markup, PR number, name, etc. For users it's easy enough to try to add this at the start, and for maintainers we can edit this directly from the GitHub user interface on every PR with minimal clicks, ensuring what's there is properly formatted. And we know if it's totally broken at least because we have a CI that makes sure the line is there.

**Comment by drammock** [comment]
> Instead of using titles, each PR can have in the top comment this (it can be in our PR template and it's trivial to write a GH action check to make sure it exists and isn't just the default message)

+1 for this plan.  The GH Action could even attempt to parse the rST and make sure it's valid (it won't be 100% foolproof as it won't resolve crossrefs, but it will at least check some basic stuff. [rst2html5](https://rst2html5.readthedocs.io/en/latest/README.html) might work, or there might be an even simpler rST validator out there.

**Comment by cbrnr** [comment]
Although that's a nice solution, all of the checking could be achieved with an action as part of the committed code, i.e. it could check if the contributor added a changelog entry, if it's formatted correctly, etc.

**Comment by cbrnr** [comment]
> That's true but I don't think what you suggest will have a lower maintenance burden than my proposal, which is really what I'm working toward.

Yes, I know, I was thinking that my suggestion would have a similarly lower maintenance burden, but (1) would probably be easier to implement for PR contributors (they just have to add a changelog entry as part of their PR), and (2) would maybe be a bit less black magic (what? they're taking stuff from PR discussions for the changelog?).

Since you're the one who's implementing all of this, it is of course your decision. I just wanted to point out an alternative.

**Comment by cbrnr** [comment]
Now that we're using Towncrier, is this PR still a thing?

**Pull request closed without merging**
