### PR TITLE
FIX: Flake

### PR DESCRIPTION
**Pull request by larsoner**

### CODE REVIEW

**Review by hoechenberger — APPROVED** [review]

**Comment by hoechenberger** [comment]
@larsoner I'd love to merge this PR but apparently with the new restrictions, I don't have sufficient permissions as the Qt test was not passing. Could you please either relax this requirement, or give me elevated permissions, or can we maybe re-think this entire thing? As it is now, I'm feeling a bit "debilitated", which I'm sure was not the intention :)
Screen Shot 2022-04-18 at 09 43 59

**Review by agramfort — APPROVED** [review]

**Comment by agramfort** [comment]
thx @larsoner

**Comment by larsoner** [comment]
> or can we maybe re-think this entire thing? As it is now, I'm feeling a bit "debilitated", which I'm sure was not the intention :)

Agreed, it seems to be causing more harm than good. I never saw a "merge once all checks pass" anyway, I only ever saw the admin-level "merge now ignoring requirements". I've removed the requirements for now

**Comment by hoechenberger** [comment]
Thanks Eric!

**Comment by hoechenberger** [comment]
Thanks Eric!

**Pull request merged**
