### PR TITLE
ENH: coreg opacity slider

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR is extracted from #10224:

* adds a slider for the head surface opacity (semi-automatic behaviour)

### CODE REVIEW

**Comment by hoechenberger** [comment]
Generally I would approve, BUT the default of 0.95 doesn't work for me (in fact, not even 0.99 works for me). I'm pretty convinced there's a bug somewhere, probably in pyvista. As soon as even the tiniest bit of transparency is enabled, everything gets WAY to transparent and the usual "the back of the head looks like the front" happens for me.

**Comment by larsoner** [comment]
Easy enough to reproduce:

https://user-images.githubusercontent.com/2365790/151190973-b7b1e6c0-3b96-470a-942f-94c882073481.mp4

Enabling depth peeling (just pushed) fixes it for me, but 0.95 seems way too opaque:

https://user-images.githubusercontent.com/2365790/151191228-da315982-0510-4e54-933c-b3b238ee2ce9.mp4

@hoechenberger want to try on my commit and see what the ideal transparency value is to you? To me 0.8 works well because you can clearly see the bad black points:

Screenshot from 2022-01-26 10-20-43

**Comment by hoechenberger** [comment]
@larsoner Perfect!! I changed the default to 0.8 and pushed.

@GuillaumeFavelier  WDYT?

**Comment by GuillaumeFavelier** [comment]
This is a way better transition :100:

**Comment by GuillaumeFavelier** [comment]
Shall we update `mne/gui/tests/test_coreg_gui.py` and `mne/gui/__init__.py` too ?

```diff
diff --git a/mne/gui/__init__.py b/mne/gui/__init__.py
index 53719bf5d..ba9a1b00c 100644
--- a/mne/gui/__init__.py
+++ b/mne/gui/__init__.py
@@ -151,7 +151,7 @@ def coregistration(tabbed=False, split=True, width=None, inst=None,
         advanced_rendering = \
             config.get('MNE_COREG_ADVANCED_RENDERING', 'true') == 'true'
     if head_opacity is None:
-        head_opacity = config.get('MNE_COREG_HEAD_OPACITY', 0.95)
+        head_opacity = config.get('MNE_COREG_HEAD_OPACITY', 0.8)
     if head_inside is None:
         head_inside = \
             config.get('MNE_COREG_HEAD_INSIDE', 'true').lower() == 'true'
diff --git a/mne/gui/tests/test_coreg_gui.py b/mne/gui/tests/test_coreg_gui.py
index cfdf6dc84..386f7f979 100644
--- a/mne/gui/tests/test_coreg_gui.py
+++ b/mne/gui/tests/test_coreg_gui.py
@@ -185,7 +185,7 @@ def test_coreg_gui_pyvista(tmp_path, renderer_interactive_pyvistaqt):
     assert coreg._mark_inside
     assert_allclose(
         coreg._head_opacity,
-        float(config.get('MNE_COREG_HEAD_OPACITY', '0.95')))
+        float(config.get('MNE_COREG_HEAD_OPACITY', '0.8')))
     assert coreg._project_eeg == \
         (config.get('MNE_COREG_PROJECT_EEG', '') == 'true')
     assert coreg._hpi_coils
```

**Comment by larsoner** [comment]
Please do @GuillaumeFavelier

**Review by hoechenberger — APPROVED** [review]

**Comment by hoechenberger** [comment]
CI errors are due to download problems. We should try to restart in a few minutes (or in an hour??) or so

**Comment by hoechenberger** [comment]
🥳

**Pull request merged**
