### PR TITLE
MRG, ENH: BigSur-ized icon

### PR DESCRIPTION
**Pull request by larsoner**
For @hoechenberger , following the [BigSur icon style guide](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/) I switched to the rounded rectangle and added an inner drop shadow to differentiate from the background better, main/PR:

<table><tr><td>
Screen Shot 2021-04-03 at 10 14 50 AM
</td><td>
Screen Shot 2021-04-03 at 10 14 36 AM
</td><td>
Screen Shot 2021-04-03 at 10 11 44 AM
</td><td>
Screen Shot 2021-04-03 at 10 12 05 AM
</td></tr></table>

This was a quick hack in InkScape, and I think the rectangle is actually slightly too large -- I'll need to shrink the "MNE" to fit within the proper size. But it seemed like a fun weekend project so here's a start at least :)

@hoechenberger if you want to try making one you can use the template PNG to figure out dimensions from https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/ or more directly if you have Photoshop or one of the other commercial programs from https://developer.apple.com/design/resources/#macos-apps

### CODE REVIEW

**Comment by hoechenberger** [comment]
Great to see you're using Signal too 👍 

Oh and nice icon 🥳 

Yes it appears it's slightly too large, but I think it's already much better in terms of visual consistency when using Big Sur!

I can take a stab at this tomorrow to see if I can tweak the dimensions a little bit!

**Comment by larsoner** [comment]
Feel free to push directly to this branch

**Comment by larsoner** [comment]
Okay I tracked down an instance of Illustrator. I also noticed that vscode and Chrome's BigSur-ized icons are white, so I went with:

Screen Shot 2021-05-12 at 8 35 15 AM
 
WDYT @hoechenberger ?

**Review by agramfort — APPROVED** [review]
@hoechenberger @cbrnr merge if happy

**Comment by cbrnr** [comment]
Looks great! Thanks @larsoner!

**Pull request merged**
