### PR TITLE
Add raw stc

### PR DESCRIPTION
**Pull request by BabaSanfour**
Add functionality to extract raw time course of a brain region

In this commit, I have extended the script to include functionality that allows users to directly access the raw time courses of a specific brain region through its label without any transformation. This enhancement enables more flexible and detailed analysis of source data.

### CODE REVIEW

**Comment by wmvanvliet** [comment]
CI failure does not seem related to this PR.

I think it makes sense to add this functionality, although I was a bit confused by the term "raw" timecourses. I've changed the wording in the `changes/devel.rst` file when resolving a conflict there, but this is just a suggestion, feel free to change it again @BabaSanfour .

Could we add a unit test for the new functionality?

**Comment by BabaSanfour** [comment]
@wmvanvliet the change should be fine ; The CI failure is fixed - somehow.

For the unit test I will add it later today. I found this comment "# XXX we don't check pca_flip, probably should someday...".
Should I add pca_flip unit test also ?

**Comment by wmvanvliet** [comment]
If you could yes thank you :)

**Review by agramfort — COMMENTED** [review]
I assume you have some docstrings to fix. Can you check? eg regarding output shapes when using `raw`. thx

**Comment by BabaSanfour** [comment]
Not sure the errors are related to my pull request; they in viz and transform tests which I didn't touch

**Comment by wmvanvliet** [comment]
CI failures seem related:

```
 mne/tests/test_source_estimate.py:63:39: F401 [*] `mne.fixes._safe_svd` imported but unused
mne/tests/test_source_estimate.py:67:63: F401 [*] `mne.source_estimate._prepare_label_extraction` imported but unused
```

**Review by drammock — APPROVED** [review]
I changed `"raw"` to be `None` instead, after discussion with @larsoner, and then modified the logic accordingly. We agreed that `None` better reflected the user request, i.e., "no aggregation strategy across vertices".

marking for merge when CIs are green again, thanks @BabaSanfour!

**Comment by BabaSanfour** [comment]
I agree it better reflects the logic of mne. Thanks for your work! Glad to contribute.

**Pull request merged**
