### PR TITLE
Replicate errors found in the 3.7 env in travis

### PR DESCRIPTION
**Pull request by massich**
Try to replicate the errors we are facing in 3.7 travis runs in the following PRs: 

- [#5819](https://travis-ci.org/mne-tools/mne-python/jobs/479417953#L4424)
- [#5718](https://travis-ci.org/mne-tools/mne-python/jobs/479435659#L2390)

### CODE REVIEW

**Comment by massich** [comment]
I do replicate locally. I'll try to see what is all that about

**Comment by larsoner** [comment]
FYI same failures are happening on maint/0.17, so we'll want to backport

**Comment by massich** [comment]
> FYI same failures are happening on maint/0.17, so we'll want to backport

yes there has been a numpy realease and it's not compatible with scipy=1.2.0 (I think)

If this PR is green I suggest to merge it, and make a PR removing those 2 lines + fixing whatever is wrong.

**Comment by larsoner** [comment]
We probably don't need to fix anything, just wait for the SciPy 1.2.0 + NumPy 1.16.0 wheels to land. 1.16.0 came out yesterday IIRC so it might take a day or two ... ?

**Comment by massich** [comment]
https://github.com/numpy/numpy/issues/12736

**Comment by massich** [comment]
@larsoner yes, we can just do the PR to keep track of it, re run the CI in a couple of days and if its green. Done!!

**Comment by massich** [comment]
maybe there was a nicer way to rollback to 1.15.4, but ..

**Comment by larsoner** [comment]
Actually I get it to go away locally if I add:
```
ignore:numpy.ufunc size changed:RuntimeWarning
```
to setup.cfg.

This makes sense if the `sklearn` wheels are old, which they almost certainly are.

Can you see if this fixes things for you? If so we should add it for a day or two rather than pin the NumPy version.

**Comment by massich** [comment]
It does fix it on my end. 
How did you come up with that?

**Comment by massich** [comment]
I guess that if anything is crucial, some other test would actually break, some buffer would go crazy, or something.

**Comment by larsoner** [comment]
I looked at the topmost error in the log, it was our suite turning a warning into an error

**Comment by mattip** [comment]
This message is coming from scikit-learn apparently they are using `cython<=0.29` where the `numpy.pxd` was updated to not emit that warning when upgrading NumPy.

See scikit-learn/scikit-learn#12829

**Pull request closed without merging**
