### PR TITLE
[backport #5920] Fix sel

### PR DESCRIPTION
**Pull request by massich**
Fixes a nasty `Epochs` bug where using `Epochs(..., preload=True)` followed by `epochs.drop_bad(...)` causes the data and selection to be incorrect.

### CODE REVIEW

**Comment by larsoner** [comment]
CircleCI will need the `"pyqt5<5.12"` that is in `master`

**Comment by larsoner** [comment]
You should probably also cherry pick https://github.com/mne-tools/mne-python/commit/ec4844e0c6ba40a39030b06253f1adf7e7c55123

**Comment by larsoner** [comment]
... and the `<5.12` you need is in `.config/circle.yml`

**Comment by agramfort** [comment]
circle failure is legit @massich  https://circleci.com/gh/mne-tools/mne-python/11286?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

I can live with the pep violations on travis.

**Comment by massich** [comment]
circle is green.

**Pull request merged**
