### PR TITLE
Fix circle.

### PR DESCRIPTION
**Pull request by jaeilepp**
Circle seems to fail on master now. Maybe the bug in sphinx was fixed? Let's see if this works...

### CODE REVIEW

**Comment by Eric89GXL** [comment]
Wouldn't it be better and safer to fix the conditional?

**Comment by jaeilepp** [comment]
I don't understand why it returns true when it's not there. If you know how to fix it, please do.

**Comment by Eric89GXL** [comment]
Have you tried SSH building and logging in to debug?

**Comment by Eric89GXL** [comment]
Well we can always restore it later :)

**Comment by jaeilepp** [comment]
Yeah I tried SSH, and it seems that the conditional was true even when sphinx was not there.

**Pull request merged**
