### PR TITLE
ENH: collapse Jupyter Notebook html representations

### PR DESCRIPTION
**Pull request by vagechirkov**
Reference issues: #9249 #9177

Collapsed sections:

<details>

image

</details>

Expand sections:

<details>

image

</details>

### CODE REVIEW

**Comment by drammock** [comment]
For the last day or so, Circle CI was not properly rendering changed tutorials.  It should be fixed now; can you merge current `main` into this PR (or rebase against `main`) to see if it actually executes the "reports" tutorial, so we can see this in-situ?

**Comment by vagechirkov** [comment]
> merge current `main` into this PR

I am using this command:
```bash
>> git pull --rebase

```

Is it the correct way to rebase?

**Comment by vagechirkov** [comment]
I have also added for Circle CI rendering the tutorial `plot_20_events_from_raw.py` from issue #9249.

**Comment by drammock** [comment]
> > merge current `main` into this PR
> 
> I am using this command:
> 
> ```shell
> >> git pull --rebase
> ```
> 
> Is it the correct way to rebase?

There are a few different ways to do it. Assuming you're on the `collapsible-repr-html` branch already, you can do
```
git fetch upstream
git rebase upstream/main
```
or you can do
```
git pull --rebase upstream/main
```
For the purposes of MNE-Python development, this is also fine: `git pull upstream/main` or `git fetch upstream; git merge upstream/main`.  The reason it doesn't matter whether you rebase or merge is that when we merge PRs we squash all the PR commits into one commit, so the diff between main and this branch will end up looking the same either way.

**Comment by vagechirkov** [comment]
> > > merge current `main` into this PR
> > 
> > 
> > I am using this command:
> > ```shell
> > >> git pull --rebase
> > ```
> > 
> > 
> > Is it the correct way to rebase?
> 
> There are a few different ways to do it. Assuming you're on the `collapsible-repr-html` branch already, you can do
> 
> ```
> git fetch upstream
> git rebase upstream/main
> ```
> 
> or you can do
> 
> ```
> git pull --rebase upstream/main
> ```
> 
> For the purposes of MNE-Python development, this is also fine: `git pull upstream/main` or `git fetch upstream; git merge upstream/main`. The reason it doesn't matter whether you rebase or merge is that when we merge PRs we squash all the PR commits into one commit, so the diff between main and this branch will end up looking the same either way.

Thank you very much for the explanation!

**Comment by hoechenberger** [comment]
Sorry for not getting back to you, @vagechirkov. I will have time to take a closer look at this hopefully tonight!

**Comment by vagechirkov** [comment]
For me personally, it seems convenient to have HTML representations with an option to collapse sections. But this is probably more related to issue #9177 than #9249.

**Pull request closed without merging**
