### PR TITLE
MRG: Motion Annotation

### PR DESCRIPTION
**Pull request by bloyl**
`mne.preprocessing.annotate_movement` computes HPI displacements from an average position. Bad data segments (in `raw.annotations`) where meant to be excluded from this averaging. However there is a bug in computing the weights for averaging

Basically the weights (`seg_good`) are defined from `pos` which has different time samples from `raw`. So the onsets/durations of the bad annotations do line up with the indices of the `seg_good` array.

This PR uses `compute_average_dev_head_t` to compute an average transform (ignoring bad segments) and uses that to compute the average HPI locations.

Additionally, I'd like to propose adding a flag `use_raw_head_trans` (or similarly named) that if set would use `raw.info['dev_head_t']` as opposed to `compute_average_dev_head_t`. The default would be `False`

### CODE REVIEW

**Comment by larsoner** [comment]
> Additionally, I'd like to propose adding a flag use_raw_head_trans (or similarly named) that if set would use raw.info['dev_head_t'] as opposed to compute_average_dev_head_t. The default would be False

Maybe `use_dev_head_t='average' (default) | 'info'`? That way we can add other options later if need be, and it's fairly readable.

**Comment by AdoNunes** [comment]
Nice catch @bloyl.

I am just worried that the same could happen in the ``compute_average_dev_head_t``.

In function example, the pos had the same number of samples as the raw. I guess if the fit is not good it will remove pos samples? If so ``compute_average_dev_head_t`` would be wrong or crash.

```
    # Get time indices
    ts = np.concatenate((hp[:, 0], [(raw.last_samp + 1) / sfreq]))
    assert (np.diff(ts) > 0).all()
    ts -= raw.first_samp / sfreq
    idx = raw.time_as_index(ts, use_rounding=True)

    assert idx[-1] == len(seg_good)
```
Here the ts (pos time stamps) are converted to idx of the raw samples

```
   # Mark times bad that are bad according to annotations
    onsets, ends = _annotations_starts_stops(raw, 'bad')
    for onset, end in zip(onsets, ends):
        seg_good[onset:end] = 0
    dt = np.diff(np.cumsum(np.concatenate([[0], seg_good]))[idx])
```
then, ``seg_good`` initially ones are zeroed if bad_annotation.  The good time periods indexed by `idx` are used for computing the average dev_head_t.

OK, after writing this I think the function is fine. 
LGTM

**Comment by bloyl** [comment]
What about this as a docstring for the new parameter?
```
    use_dev_head_trans : 'average' (default) | 'info'
        Identify the device to head transform used to define the
        fixed HPI locations for computing moving distances.
        If ``average`` the average device to head transform is
        computed using ``compute_average_dev_head_t``.
        If ``info``, ``raw.info['dev_head_t']`` is used.
```

I'm not sure I'm using the `` correctly?

**Comment by larsoner** [comment]
Backticks look correct and description LGTM

**Comment by bloyl** [comment]
Codecov failed because of a testing timeout. I restarted the test but I'm not sure how to redo codecov.

**Comment by larsoner** [comment]
Thanks @bloyl !

**Pull request merged**
