### PR TITLE
MRG: Fix inst.pick_channels

### PR DESCRIPTION
**Pull request by larsoner**
Previously `inst.pick_channels` did not work the same as `pick_channels` -- it respected order and possibly duplicated channels.

### CODE REVIEW

**Comment by mmagnuski** [comment]
It says "(ignoring order)" in the whats new - I was previously using pick_channels to ensure the same channel order in all files (I often load eeglab files preprocessed by other people and eeglab sometimes changes channel order during interpolation). Is it still possible?

**Comment by larsoner** [comment]
> Is it still possible?

No not with this PR. Would adding a `reorder_channels` mixin work for you?

**Comment by mmagnuski** [comment]
`reorder_channels` would be great

**Comment by larsoner** [comment]
@agramfort okay with you?

**Comment by agramfort** [comment]
yes ok for me

thx @larsoner

**Comment by larsoner** [comment]
Done

**Comment by agramfort** [comment]
@mmagnuski merge if you're happy

+1 on my side

**Comment by mmagnuski** [comment]
Looks good, I've resolved conflicts in whats_new (through the GitHub gui - so I didn't know how to change commit name), the CIs are running again, but they were green before so I'm merging. 🚀

**Pull request merged**
