### PR TITLE
Backport #10658

### PR DESCRIPTION
**Pull request by hoechenberger**
cc @sappelhoff

### CODE REVIEW

**Comment by hoechenberger** [comment]
Seems I did something wrong / forgot about something… @sappelhoff Wanna take a look? Otherwise, we can just skip the backport…

**Comment by sappelhoff** [comment]
which git commands did you run?

```
git checkout -b maint/1.0
git checkout -b backport/10658
git cherry-pick a2f6fe7cb6b1ef38fea697ee82cb97eb65c79217 --allow-empty
git push -u origin backport/10658
```

and then opened this PR?

**Comment by hoechenberger** [comment]
Hm, still failing 🤔

**Comment by hoechenberger** [comment]
> which git commands did you run?
> 
> 
> 
> ```
> 
> git checkout -b maint/1.0
> 
> git checkout -b backport/10658
> 
> git cherry-pick a2f6fe7cb6b1ef38fea697ee82cb97eb65c79217 --allow-empty
> 
> git push -u origin backport/10658
> 
> ```
> 
> 
> 
> and then opened this PR?

IDK, I used VS Code as a GUI 😀

**Comment by hoechenberger** [comment]
Thanks @sappelhoff!

**Pull request merged**
