### PR TITLE
Fix rendering bug of plot_evoked_field()

### LINKED ISSUE #5970: [VIZ] Rendering bug in plot_evoked_field()
#### Describe the bug
Rendering bug introduced by the migration to the renderer backend.

Current result:
image

Correct result:
image

#### Steps and/or code to reproduce
Follow the example  : *Visualize Evoked data*
`$ ipython --matplotlib --gui=qt tutorials/plot_visualize_evoked.py`

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
#### Reference issue
Fixes #5970.

#### What does this implement/fix?
Fix the rendering bug of `mne/viz/plot_evoked_field()`

#### Additional information
Remove the useless default `(0.7, 0.7, 0.7)` color and allow adding scalars on surfaces.

### CODE REVIEW

**Comment by larsoner** [comment]
Can you please touch the `tutorials/plot_visualize_evoked.py` file (make some small wording fix) so that CircleCI will build it? That way we can visually verify the fix.

**Comment by GuillaumeFavelier** [comment]
Ok, I'm on it.

**Comment by GuillaumeFavelier** [comment]
do I need to use `[circle full]` in the commit message?

**Comment by larsoner** [comment]
No, that causes CircleCI to build *all* examples. The default mode when building a PR is to only build examples changed in the given PR.

**Comment by agramfort** [comment]
all better:

https://11428-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/plot_visualize_evoked.html

**Comment by larsoner** [comment]
Ran `flake` tests locally as well as `mne/viz` tests locally, so I'll go ahead and merge to save our CIs some cycles.

**Pull request merged**
