### PR TITLE
[MRG] DOC coreg-GUI:  error message for invalid subject

### PR DESCRIPTION
**Pull request by christianbrodbeck**
This provides a better error message in cases like #3844

```
$ mne coreg -s Donald
Traceback (most recent call last):
  File "/Users/christian/Code/mne-python/mne/commands/mne_coreg.py", line 49, in <module>
    run()
  File "/Users/christian/Code/mne-python/mne/commands/mne_coreg.py", line 43, in run
    guess_mri_subject=options.guess_mri_subject)
  File "/Users/christian/Code/mne-python/mne/gui/__init__.py", line 70, in coregistration
    gui = CoregFrame(inst, subject, subjects_dir, guess_mri_subject)
  File "/Users/christian/Code/mne-python/mne/gui/_coreg_gui.py", line 1264, in __init__
    raise ValueError(msg)
ValueError: Donald is not a valid subject. No subjects were found in 
subjects_dir=/Applications/freesurfer/subjects. Make sure all MRI subjects have 
head shape files (run $ mne make_scalp_surfaces).

```

### CODE REVIEW

**Comment by agramfort** [comment]
any chance to add a test?

**Comment by christianbrodbeck** [comment]
What would you want to test? Just that a ValueError is raised?

**Comment by agramfort** [comment]
whatever keeps the coverage high? :)

**Comment by christianbrodbeck** [comment]
Coverage +0.06% :)

**Comment by agramfort** [comment]
Thx

**Pull request merged**
