### PR TITLE
[ENH] Speed up `read_raw_neuralynx()` on large datasets with many gaps

### LINKED ISSUE #12370: [ENH] Speed up `read_raw_neuralynx()` when Neuralynx recording has many gaps
### Describe the new feature or enhancement

Using a larger non-public dataset (~1.7GB, cca 1 hour recording at 32Khz) with a large number of missing samples, I noticed that `read_raw_neuralynx(..., preload=False)` was talking quite long to return (tens of minutes). The bottleneck is the way search for samples corresponding to gap onsets was implemented.

It turns out to map detected gap starts onto sample numbers in the recording, it is using `gap_onsets = [np.where(samples == idx) for idx in gap_indices]` which will take long (tens of minutes) if a) there is a huge number to `samples` to search over and b) a large number of `gap_indies` to search for.

### Describe your proposed implementation

PR: #12371

The proposal is to drop `np.where` and infer gap sample onsets by cumulatively summing the segment sample sizes using `np.cumsum(segment_sizes)`. See PR for details.

Replacing `np.where` for `np.cumsum` removes the bottleneck:
image

### Describe possible alternatives

I'm sure there's even more efficient methods out there. But this is already a substantial improvement and removes the bottleneck.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by KristijanArmeni**
#### Reference issue
Fixes #12370.

#### What does this implement/fix?
**Drop `np.where` and compute onsets via `np.cumsum`** Instead of using `np.where` to iterative over gap indices and search over the recording samples, in this PR I compute all segment start samples by cumulatively summing segment sample sizes (see this change: [5b40d2](https://github.com/KristijanArmeni/mne-python/commit/5b40d21f33e92e1d101aa6de8866a15aea0b997d)).

This gives starting indices for all segments, then I select only those corresponding to gaps. Doing it this way, yields substantial improvements over using `np.where` as confirmed on a a few local datasets with increasing numbers of gaps (see Figure in #12370) 

#### Additional information
Any additional information you think is important.

### CODE REVIEW

**Review by larsoner — APPROVED** [review]
I don't think a changelog entry is needed for this so I'll label it as such, but feel free to add one if you want @KristijanArmeni (probably as `12371.newfeature.rst` since this is an enhancement) . I'll mark for merge-when-green, thanks in advance!

**Comment by KristijanArmeni** [comment]
> I don't think a changelog entry is needed for this so I'll label it as such, but feel free to add one if you want @KristijanArmeni (probably as 12371.newfeature.rst since this is an enhancement)

Thanks @larsoner! Added a changelog entry as suggested.

**Comment by larsoner** [comment]
pip-pre failures are unrelated, I opened #12372 to track it

**Comment by KristijanArmeni** [comment]
@larsoner just pinging here that it looks like this was not auto-merged (it was automatically disabled after my changelog commit). But I see pip-pre fails are now sorted and main is passing so I think just this just needs an update from main and should be all green.

**Comment by larsoner** [comment]
Thanks for the ping @KristijanArmeni, merged `main` into this branch reenabled auto-merge, and will keep an eye on it to make sure it lands today!

**Pull request merged**
