### PR TITLE
Ignore E722 (bare except) and fix E741 (ambiguous variable names)

### PR DESCRIPTION
**Pull request by cbrnr**
Fix pep errors in Travis job

### CODE REVIEW

**Comment by larsoner** [comment]
Is it okay with you if I take over and instead fix the bare excepts?

**Comment by cbrnr** [comment]
Oh yes, that's what I suggested anyway!

**Comment by larsoner** [comment]
Just saw you're willing to do it, @agramfort okay with you to actually fix
them?

**Comment by cbrnr** [comment]
@larsoner do we really need try/except around

    with open(fname, 'r') as f:
        lines = f.readlines()

when all we do is re-raise a `ValueError`?

**Comment by cbrnr** [comment]
Also, there are 72 occurrences of `except Exception` which amounts to the same thing. I'm not sure how to handle this. Suggestions?

**Comment by larsoner** [comment]
> Also, there are 72 occurrences of except Exception which amounts to the same thing.

`except:` will catch even `SystemExit` whereas `except Exception:` will not:

https://docs.python.org/2/library/exceptions.html#exceptions.Exception

If flake doesn't complain about these let's leave them alone.

>  do we really need try/except around

Usually we do this to raise a more informative error, so it depends on how useful the new message is

**Comment by cbrnr** [comment]
> except: will catch even SystemExit whereas except Exception: will not:

Sure, but even though they're not exactly identical both are too broad.

However, the pragmatic solution for now is to leave them alone. For now.

> Usually we do this to raise a more informative error, so it depends on how useful the new message is

    "Error while reading %s" % fname

**Comment by larsoner** [comment]
> both are too broad.

Well the `except:` is almost certainly too broad -- you don't want to catch `SystemExit` (without re-raising) unless you need to e.g. delete a file, which isn't what we want to do anywhere AFAIK.

I agree in cases where it can reasonably be limited to something smaller, which I think is your point, we should. But we can't always do it -- in many cases, `except Exception:` is a reasonable thing to do, where you want to do something no matter what the outcome of the code is. I think of it as a way of having local context-manager-like behavior (or raise-nicer-error behavior).

> "Error while reading %s" % fname

Hmmm.... this might have come from either an `IOError` (which wouldn't be informative) or a `UnicodeDecodeError` or similar, in which case it might be informative. You can remove it if you want I suppose

**Comment by cbrnr** [comment]
At least PEP8 doesn't bother with `except Exception`, so I replaced all bare excepts with that if I didn't know any better.

**Comment by larsoner** [comment]
Great, will merge once the CIs come back happy, thanks for taking care of this so quickly

**Comment by larsoner** [comment]
Thanks @cbrnr

**Pull request merged**
