### PR TITLE
ENH: Try newer Qt [circle front]

### PR DESCRIPTION
**Pull request by larsoner**
Let the pain continue!

### CODE REVIEW

**Comment by cbrnr** [comment]
Why?

**Comment by larsoner** [comment]
CircleCI segfaults on `make test-doc`, look at the latest `master` or `maint/0.16` builds

**Comment by cbrnr** [comment]
I thought it was working in the other PR?

**Comment by larsoner** [comment]
That only ran `make html_dev-noplot` essentially. On `master` commits and (in this PR) on `[circle front]` commits it runs `make test-doc`.

I don't know if the full doc build would have worked, either, but I'll test that here before merging.

**Comment by cbrnr** [comment]
But is it PyQt5 again? I saw that you tried pip upgrading, but then removed it again, so it seems like this is not the problem (as the title suggests).

**Comment by larsoner** [comment]
The latest commit (with conda package) segfaulted so I think the title might currently be accurate. But this is mostly coincidence because I'm not updating the title with each new thing I try

**Comment by cbrnr** [comment]
Sure, I just didn't immediately pin it down to PyQt5, and it is likely also not the same issue we had in the other PR. A good title would be your initial comment :smile:.

**Comment by larsoner** [comment]
Okay this mess fixes CircleCI:

https://8506-1301584-gh.circle-artifacts.com/0/html/index.html

I'll merge so we can be green again, and backport.

**Comment by cbrnr** [comment]
Indeed. Thanks for fixing it!

**Comment by agramfort** [comment]
thx heaps @larsoner !

**Comment by jasmainak** [comment]
so much fun ... :)

**Pull request merged**
