### PR TITLE
MRG, FIX: Fix eLORETA units

### PR DESCRIPTION
**Pull request by larsoner**
Finally worked out the math for eLORETA:

1. Updated docs
2. Got the units to nAm
3. Fixed the variance explained calculation
4. Fixed the residual calculation

Ready for review/merge from my end.

### CODE REVIEW

**Comment by larsoner** [comment]
Updated examples are [here](https://18143-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/source-modeling/plot_mne_dspm_source_localization.html#dipole-orientations)/[master](https://mne.tools/dev/auto_tutorials/source-modeling/plot_mne_dspm_source_localization.html#dipole-orientations) and [here](https://18143-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/source-modeling/plot_mne_solutions.html)/[master](https://mne.tools/dev/auto_tutorials/source-modeling/plot_mne_solutions.html). Estimates changed slightly, I think because the regularization parameter is actually properly factored in now. Previously I think it was off by a factor of something like a square root (hence why things are a bit more focal now).

@hichamjanati feel free to check out [the new equations in the eLORETA section](https://18143-1301584-gh.circle-artifacts.com/0/dev/overview/implementation.html#eloreta) if you're interested in more minimum-norm stuff.

**Comment by hoechenberger** [comment]
@larsoner Looking forward to this getting merged, always wanted to try out eLORETA but the numbers it produced (explained variance) seemed kinda weird, so I chose to avoid this algorithm altogether in the past :)

**Comment by hoechenberger** [comment]
Btw is there a specific reason why all source images appear twice in those tutorials?

**Comment by larsoner** [comment]
>  is there a specific reason why all source images appear twice in those tutorials?

#7228

BTW I'm setting this back to WIP because I found some other bug(s) that need fixing :( But we're getting close!

**Comment by larsoner** [comment]
Okay this is ready for review/merge failures are just GitHub having a bad day.

Updated examples:
- [here](https://18180-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/source-modeling/plot_mne_dspm_source_localization.html#dipole-orientations)/[master](https://mne.tools/dev/auto_tutorials/source-modeling/plot_mne_dspm_source_localization.html#dipole-orientations)
- [here](https://18180-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/source-modeling/plot_mne_solutions.html)/[master](https://mne.tools/dev/auto_tutorials/source-modeling/plot_mne_solutions.html).
- [new equations in the eLORETA section](https://18180-1301584-gh.circle-artifacts.com/0/dev/overview/implementation.html#eloreta)

**Comment by drammock** [comment]
naive question here, since I haven't been following the details of this PR very closely: should we expect these changes to *only* affect eLORETA results?  The brain plots for all three (dSPM, sLORETA, eLORETA) have all changed dramatically:

MASTER:
master

THIS PR:
this_pr

Is that just because you're specifying different `clim` now?

**Comment by larsoner** [comment]
Yeah it's just a `clim` change, I can try to set it so it's more like it was before

**Comment by larsoner** [comment]
URLs updated above, but here is what the new one looks like now:

Screenshot from 2020-02-25 14-29-15

**Comment by hoechenberger** [comment]
This is great! A question for another PR: Would it be possible to somehow make the color bar labels more... readable? Would a log transform make sense?

**Comment by larsoner** [comment]
That's a question for @GuillaumeFavelier and his viz enhancements, but unfortunately from what I understand VTK offers little to no way of tweaking the colorbar labeling. Someday we could maybe make our own colorbar class that is more configurable, but it would probably be pretty far down the priority list.

One thing that might help with MNE and eLORETA is having a `units` kwarg, as if you set it to `nAm` it could label it as such and multiply by `1e9`, so a lot of the scientific notation could go away.

**Comment by larsoner** [comment]
Maybe `units` and `scaling` or something to be consistent with other plotters... let's open an issue to discuss.

**Pull request merged**
