### PR TITLE
DOC: issue with scaling

### PR DESCRIPTION
**Pull request by jasmainak**

### CODE REVIEW

**Comment by jona-sassenhagen** [comment]
Ok I checked and it refers (obviously) to the scaled data (so *10e-6 for EEG). Just make it -15, 15 for the typical ERP range. 

And check line 438 for a similar issue!

**Comment by teonlamont** [comment]
cf. https://github.com/mne-tools/mne-python/issues/2344

**Comment by jona-sassenhagen** [comment]
I can't make a PR against this PR?

**Comment by Eric89GXL** [comment]
A PR is a request to merge some set of changes from one branch to another, so you can't really "make a  PR against a PR". It's a bit of a misnomer -- what you probably really want to do (and what people really mean when they say it) is that you can make a PR from some branch of yours against the branch in @jasmainak's fork of mne-python that forms the basis of this PR (which in turn is a request to merge changes from his fork's branch into mne-tools's `master` branch).

**Comment by agramfort** [comment]
LGTM

what's the pb @jona-sassenhagen ?

**Comment by Eric89GXL** [comment]
Probably line 438 based on the comment above...?

**Comment by jona-sassenhagen** [comment]
That, and -200, 200 are not typical values for ERPs. -15, 15 would be more appropriate.

**Comment by jona-sassenhagen** [comment]
I think it's confusing otherwise (people might begin to wonder about scalings)

**Comment by jona-sassenhagen** [comment]
Ie., it should be (-15, 15) both here and in 438.

**Comment by jona-sassenhagen** [comment]
And probably in 496.

**Comment by jona-sassenhagen** [comment]
And we could maybe make it explicit that `ylim` refers to the data after it has been scaled.

**Pull request closed without merging**
