### PR TITLE
WIP: irTF-MxNE using dual gap as stopping criterion

### PR DESCRIPTION
**Pull request by yousrabk**
@joewalter @agramfort I will need some help here, please. The dgap computation in the TF solver is somehow wrong. Here is a simple example with data on [Dropbox](https://www.dropbox.com/sh/aqwpqib4ye5qsqg/AACEhKrp-lh6WrkWfI78OWO2a?dl=0), showing a (big) negative dgap with a decreasing objective function.

@joewalter maybe you've got this when working on this?

### CODE REVIEW

**Comment by agramfort** [comment]
I can replicate the pb. @joewalter do you have time to look? I see negative dual gaps and computation does not stop even if the pobj and dobj stop moving.

**Comment by mathurinm** [comment]
I am not sure gap is the issue here. Using only tf_mixed_norm_solver and no time or space weights, I don't get the same active_set after one BCD pass one all sources on master and this branch.

**Comment by mathurinm** [comment]
I think we can close this as we have started to break it into smaller PRs

**Comment by agramfort** [comment]
+1

**Pull request closed without merging**
