### PR TITLE
STY: Higher contrast [circle front]

### PR DESCRIPTION
**Pull request by larsoner**

### CODE REVIEW

**Comment by larsoner** [comment]
@mathurinm @jasmainak @dengemann feel free to decide if you like this higher-contrast one better:

https://8109-1301584-gh.circle-artifacts.com/0/html/auto_tutorials/plot_mne_dspm_source_localization.html

And feel free to try other styles quickly if you want:

http://pygments.org/demo/6745072/?style=tango

**Comment by agramfort** [comment]
LGTM

**Comment by jasmainak** [comment]
I'm not a color expert but I like 'default' the best.

**Comment by larsoner** [comment]
Looks like this:

https://8111-1301584-gh.circle-artifacts.com/0/html/auto_tutorials/plot_mne_dspm_source_localization.html

**Comment by agramfort** [comment]
this last one is not enough contrasted I think.

**Comment by jasmainak** [comment]
hmm ... but I don't understand. On the pygments website, `default` had black fonts but on MNE, it is gray ... that's why the contrast is low. Perhaps something else is overriding this color combination?

**Comment by larsoner** [comment]
There was a tricky bug where `bootstrap` was overriding the `highlight` CSS. The latest commit should fix it

**Comment by larsoner** [comment]
(workaround found in https://github.com/rtfd/sphinx_rtd_theme/issues/166)

**Comment by jasmainak** [comment]
oh wow! That sounds like a non-trivial fix

**Comment by agramfort** [comment]
how does it look like now?

**Comment by dengemann** [comment]
I find acceptable the brighter high-contrast / light background schemes:

screenshot 2018-05-28 22 09 20
screenshot 2018-05-28 22 09 12
screenshot 2018-05-28 22 09 00
screenshot 2018-05-28 22 08 47
screenshot 2018-05-28 22 08 22
screenshot 2018-05-28 22 08 05

**Comment by larsoner** [comment]
How can you tell when @agramfort is drowning in emails? When CircleCI artifacts being more than one click away is insurmountable :)

This is default:

https://8114-1301584-gh.circle-artifacts.com/0/html/auto_tutorials/plot_mne_dspm_source_localization.html

**Comment by dengemann** [comment]
@larsoner can we try those above with a light background?

**Comment by jasmainak** [comment]
LGTM after bugfix. Other styles should also look better I guess.

**Comment by larsoner** [comment]
@dengemann can you be more specific as to what you mean? You posted 6 options are you asking if we can tweak the background color of each of them? Yes you can tweak CSS in chrome aas much as you want and post screenshots. 

If you want to get circle to render all 6 feel free to push commits to my branch, waiting after each until the build is complete

**Comment by dengemann** [comment]
No to me they are more or less equivalent. Let's just do something along
these lines.

**Comment by mathurinm** [comment]
I'll chip in. I like the ones which
- do no put some values in bold
- have a white background
- do not highlight stuff
- do not write comment in light gray
- do not use flashy colors

Borland lgtm

**Comment by larsoner** [comment]
To keep the number of permutations and iterations reasonable, can people you make a PR to my branch with your favorite option? I'll merge each and let it build stop we can all see (or post ascreenshot). I fear each person giving half a dozen options or constraints is too imprecise for aesthetic convergence.

For example, for now links are distinguished by being bold but you can change this if you want (look at the diff and you will see it). So it's not as simple as just setting it to borland and letting it build :(

**Comment by dengemann** [comment]
I like both. I just feel the background is more gray than on the demo
website.

**Comment by agramfort** [comment]
I like the white

**Comment by dengemann** [comment]
Actually much nicer! Great!

**Comment by agramfort** [comment]
can we make it slightly gray then?

also note that in
https://8130-1301584-gh.circle-artifacts.com/0/html/auto_tutorials/plot_mne_dspm_source_localization.html
you don't have the outputs between cells.

**Comment by massich** [comment]
it is true that there're no outputs https://8130-1301584-gh.circle-artifacts.com/0/html/auto_tutorials/plot_python_intro.html

**Comment by larsoner** [comment]
I have no idea why some examples are effectively running with `WARNING` log level -- some examples are running with the `INFO` and others `WARNING` :(

In any case, rendered version with different colors for code/output (now using SG default for output actually) can be seen here, where I used `verbose=True` to force it to print:

https://8160-1301584-gh.circle-artifacts.com/0/html/auto_tutorials/plot_mne_dspm_source_localization.html

**Comment by agramfort** [comment]
fine with this one for me.

**Comment by larsoner** [comment]
Updated version with terminal colors fixed in sphinx-gallery master:

https://8199-1301584-gh.circle-artifacts.com/0/html/auto_tutorials/plot_mne_dspm_source_localization.html

@dengemann @jasmainak @massich @mathurinm okay with you?

**Comment by massich** [comment]
Really cool. Thanks a lot.

**Comment by dengemann** [comment]
Looks pretty awesome!

**Pull request merged**
