### PR TITLE
WIP: Single trial time frequency decomposition

### PR DESCRIPTION
**Pull request by kingjr**
The single trial decomposition that outputs the complex values instead of the power will be useful for the decoding pipeline.

### CODE REVIEW

**Comment by kingjr** [comment]
@Eric89GXL ready for review

**Comment by Eric89GXL** [comment]
LGTM from a functionality standpoint, but I don't really like that we will now have `single_trial_power` and `single_trial_complex` when they are 99% the same function. @agramfort are you okay with deprecating `single_trial_power` for `single_trial_tfr` or something else? If not, I almost wonder if we should just add an `output` argument to `single_trial_power`, even though it's a misnomer, rather than make the namespace more densely populated. But really none of these options are all that appealing to me :(

**Comment by kingjr** [comment]
I agree. I m for a deprecation in favour of single_trial_tfr or any other
good name.

On Wednesday, 20 July 2016, Eric Larson <notifications@github.com> wrote:
> LGTM from a functionality standpoint, but I don't really like that we
will now have single_trial_power and single_trial_complex when they are 99%
the same function. @agramfort are you okay with deprecating
single_trial_power for single_trial_tfr or something else? If not, I almost
wonder if we should just add an output argument to single_trial_power, even
though it's a misnomer, rather than make the namespace more densely
populated. But really none of these options are all that appealing to me :(
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/b3UDNblgokack__ISYJ-6UpzGXIwmhRY-L5oOZY9-j0Y5rw-3JZOHusguIDZhucR0fN0z0d95WSDYeOnNb7Xc0VyKNXlNMrZOc_l24gNEtf7VLiX1oTKF_AsGlV2aezz80C2-9v88O-GPrXjYWdN4_dMhuxpbg=s0-d-e1-ft#https://github.com/notifications/beacon/AEp7DFgAYKaG8lz4v1WB-Eu5TZDWyYACks5qXuB_gaJpZM4JRRV8.gif
>

**Comment by agramfort** [comment]
yes single_trial_tfr should be deprecated.

tfr_xxx functions should have average=True / False parameter

would this do the job?

**Comment by kingjr** [comment]
@agramfort tfr_xxx functions are currently dedicated to instances (Epochs, Raw) and not to arrays. They pick, find the sfreq etc. We need lower level functions (possibly private) to be applied on arrays, don't we? 

IMO, it's easier to maintain the following architecture

```
def high_level(inst, **params):
    inst = inst.copy()
    inst.drop_bads()
    picks = _pick_data_channels(inst.info)
    inst.pick_channels(picks)
    X = inst.get_data()
    tfr = low_level(X, sfreq=inst.info['sfreq'], **params)
    return PSD(tfr, raw.info, freqs ...)

def low_level(X, sfreq, frequency, output='power'):
    wavelet = set_wavelet()
    tfr = parallel_func(convolution)
    if output == 'power':
        tfr = np.abs(power) ** 2
    return tfr
```

Than a big function that does it all.

Also, we currently don't have an instance for single trial power do we?

**Comment by cmoutard** [comment]
> Also, we currently don't have an instance for single trial power do we?

I have written a Tensor class trying to respect as much as possible the MNE style, with (partially implemented) tests.
And I have also used this class to adapt a NPLS (N-way Partial Least Square) algorithm which seems to work (still work in progress).

**Comment by kingjr** [comment]
Nice. Do you have a link? How is the class different from a numpy array?

**Comment by jona-sassenhagen** [comment]
Just throwing this in here: could the function also take raw objects? E.g. for encoding in the TF domain.

**Comment by kingjr** [comment]
@jona-sassenhagen IMO tfr_* functions should apply to Epochs, Raw or Evoked.

**Comment by jona-sassenhagen** [comment]
Ah, but that's probably not for this PR right?

**Comment by kingjr** [comment]
@jona-sassenhagen well, we have to decide whether numpy arrays/Raw/Epochs etc are passed to the same function or whether we divide the labor, so your question is not completely irrelevant.

**Comment by jona-sassenhagen** [comment]
Well it seems to me for the functions that return Average_TFR objects, it's clear they can take only epochs. But for those that do not average, it seems to me most straight-forward for them to return an array with dimensionality = input dims + 1, and take in arrays, Raw, Epochs, Evoked, and possibly even STCs.

That's the most obvious usage right?

**Comment by Eric89GXL** [comment]
> That's the most obvious usage right?

Probably considered as the function in isolation probably, but as a part of MNE-Python's TFR-related code I'm not sure. I think most places we separate between those that take ndarray, from those that take Epochs, from those that take Raw. If someone has time, it might be worth enumerating the functions we have in terms of naming, input/output, etc. to see if we have a consistent pattern to follow.

**Comment by jona-sassenhagen** [comment]
Actually Evoked and Raw output will be 100% compatible with the Average_TFR *format*, albeit not nomenclature ...

And it would be handy to have an object than can store a continuous data TF decomp with an attached info structure.

Hm.

**Comment by agramfort** [comment]
>
> @agramfort <https://github.com/agramfort> tfr_xxx functions are currently
> dedicated to instances (Epochs, Raw) and not to arrays. They pick, find the
> sfreq etc. We need lower level functions (possibly private) to be applied
> on arrays, don't we?


I would just refactor to have private functions called _tfr_xxx that take
ndarrays

**Comment by agramfort** [comment]
putting PR back to WIP as it's the not the right fix (I think).

**Pull request closed without merging**
