### PR TITLE
Remove versions from README.rst

### PR DESCRIPTION
**Pull request by cbrnr**
I've removed the dependency list, because it is constantly out of sync with the actual requirements. In addition, I don't think that we need to feature them that prominently in the README, since all the information is contained in the metadata anyway.

### CODE REVIEW

**Comment by drammock** [comment]
We already parse package metadata (ultimately from `pyproject.toml`) for syncing min python version in our docs:

https://github.com/mne-tools/mne-python/blob/53f258debb781aeee2c2e5cbf449f37822e3a898/doc/conf.py#L1297-L1300

We could do something similar with our README (i.e., a pre-commit hook that updates the README whenever min versions are changed in `pyproject.toml`)

**Comment by drammock** [comment]
> I wouldn't do that, let's not add more magic to things that could be simple. If someone needs to know the exact requirements, they should refer to `pyproject.toml`, the canonical and standardized location for such information.

I guess we have different definitions of "magic" 🧙🏻 --- to me, this is "sensible automation to reduce the manual work needed to keep things from getting out of sync / inaccurate". I also think there are many users who might end up on our repo webpage and not know what `pyproject.toml` is (much less to know that it is where they should look for dependency info --- especially given that there's a file called "READ ME" that contains similar information!)

So I am +1 for automating the `pyproject.toml` -> `README.md` synchronization (for key dependencies only). If folks aren't on board with that, then I'd rather remove the info from README entirely than have to manually keep it in sync.

**Comment by cbrnr** [comment]
+1 for removing entirely from README.

**Comment by larsoner** [comment]
To me `pyproject.toml` is a dev thing and README and our website are user-facing so it would be good to have the min deps listed in the README still. I don't think the magic to update would be all that complicated, and so far over the last few months the stuff we've added with `autofix` and via GHA have worked pretty well and reduced maintenance much more than they have added to it (net benefit), so I'm happy to have a bit more magic!

**Pull request closed without merging**
