### PR TITLE
DOC: Document BEM mesh fixes

### PR DESCRIPTION
**Pull request by larsoner**
Let's get these ideas in one place to improve discoverability and also allow us to iterate.

FYI @jasmainak you suggested using `mri_expand` with a negative value at one point, but my FreeSurfer 6 does not have this command. Is it named differently, or only available in the `dev` edition or something?

### CODE REVIEW

**Comment by jasmainak** [comment]
I think I might have mixed up the name. You can use the "less" and "more" arguments in `mri_watershed` command to do this, it seems: http://freesurfer.net/fswiki/mri_watershed

**Comment by jasmainak** [comment]
happy to merge after the expanding/shrinking with `mri_expand -more` is documented. It helps you prevent re-running the entire algorithm again.

nice contribution!

**Comment by larsoner** [comment]
What do you want it to say? There is no mri_expand command for me, so I'm not sure what exactly you're suggesting

**Comment by larsoner** [comment]
Do you mean for mri_watershed? It is already in the list to try other command line options for it, do you want "more" specifically mentioned?

**Comment by larsoner** [comment]
Added explicit `-less` mention to the `mri_watershed` step. I'll go ahead and merge this but if you think it could use adjustment feel free to tweak in a follow-up PR @jasmainak

**Comment by jasmainak** [comment]
yeah, that seems fine to me. thanks!

**Pull request merged**
