### PR TITLE
WIP: Coords

### PR DESCRIPTION
**Pull request by lneisenman**
This is the requested pull request to update the docs for channels.Montage and channels.DigMontage to specify that coordinates are given in meters. I have also added a comment to the plot_ecog demo stating that electrode coordinates are given in meters

### CODE REVIEW

**Comment by lneisenman** [comment]
I missed the plot_3d_to_2d visualization example which I will go back and add

**Comment by agramfort** [comment]
good to go @lneisenman ?

**Comment by lneisenman** [comment]
@agramfort good to go.

**Comment by agramfort** [comment]
thx @lneisenman

**Pull request merged**
