### PR TITLE
MRG, API: Deprecate n_pca_components in init

### LINKED ISSUE #8355: Remove n_pca_components from ICA.__init__
Following up the changes in #8351, I noted that because `n_pca_components` is only used in `ICA.apply` it should be removed from `ICA.__init__`. This would make ICA usage a lot easier and clearer, because right now one of the questions I frequently need to answer is about the two parameters `n_components` and `n_pca_components`. I'd prefer to have only `n_components` in `ICA.__init__` and `n_pca_components` only in `ICA.apply`. @hoechenberger @larsoner @agramfort

### PR DESCRIPTION
**Pull request by larsoner**
Closes #8355

### CODE REVIEW

**Comment by larsoner** [comment]
Updated docs: https://22673-1301584-gh.circle-artifacts.com/0/dev/generated/mne.preprocessing.ICA.html (CircleCI failure is just a broken link that I fixed with a [ci skip] commit)

**Review by cbrnr — APPROVED** [review]

**Comment by larsoner** [comment]
@hoechenberger can you review and merge if you're happy?

**Review by hoechenberger — APPROVED** [review]

**Comment by larsoner** [comment]
@hoechenberger it looks like somehow you killed the branch. Were you trying to resolve conflicts? If so I'll just locally rebase and fix

**Comment by larsoner** [comment]
... and cherry pick 6f23aa4

**Comment by hoechenberger** [comment]
> @hoechenberger it looks like somehow you killed the branch. Were you trying to resolve conflicts? If so I'll just locally rebase and fix

Ouch. Nope, I just pulled. I can revert, sorry.

**Comment by hoechenberger** [comment]
Guess I pulled the wrong branch.

**Comment by larsoner** [comment]
I can push force it back to how it was. Did you have some commits you wanted on top like 3073f10 or 6f23aa4?

**Comment by hoechenberger** [comment]
> I can push force it back to how it was. Did you have some commits you wanted on top like [3073f10](https://github.com/mne-tools/mne-python/commit/3073f1093a0d8a22e423f732fcb77b34eee76bcc) or [6f23aa4](https://github.com/mne-tools/mne-python/commit/6f23aa4610782a64a071c019452c8f52e269dcf9)?

Ok that would be the easiest, thank you :) Yes only these two commits, that's all I had to contribute!

**Comment by larsoner** [comment]
Done, okay to merge once CircleCI comes back green @hoechenberger ?

**Comment by hoechenberger** [comment]
Perfect! LGTM once CI goes green.

**Comment by hoechenberger** [comment]
> Done, okay to merge once CircleCI comes back green @hoechenberger ?

Yep!

**Pull request merged**
