### PR TITLE
plot method for Label

### PR DESCRIPTION
**Pull request by PRRvalli**

### CODE REVIEW

**Comment by agramfort** [comment]
@PRRvalli make sure you read this http://martinos.org/mne/stable/contributing.html

**Comment by PRRvalli** [comment]
I am beginner, hence sorry for the inconvenience .
I have found a few mistakes like 
1)All visualization functions must accept a show parameter and return a fig handle.
2)FIX: some message
is there anything else that I didn't spot.

**Comment by agramfort** [comment]
please send a proper PR

**Comment by wmvanvliet** [comment]
First of all, could you explain why we need a `Label.plot()` method? We can already do:
```python
import surfer
brain = surfer.Brain('fsaverage', 'both', 'inflated')
brain.add_label(label)
```

with your code, this would change into:
```python
brain = surfer.Brain('fsaverage', 'both', 'inflated')
label.plot(brain)
```

I don't see much difference to be honest.

**Comment by Eric89GXL** [comment]
Closing due to non-response, but @PRRvalli if you're interested in continuing I'm happy to reopen

**Pull request closed without merging**
