### PR TITLE
MRG+1: Fix _plot_topo_onpick (#3871)

### LINKED ISSUE #3871: When using mne.viz.iter_topography, on_pick callback is called with pyplot instance instead of the axes
This is the line:

https://github.com/mne-tools/mne-python/blob/master/mne/viz/topo.py#L223

Shouldn't it be the axes? This would suggest so: http://martinos.org/mne/stable/auto_examples/visualization/plot_topo_customized.html

Thanks,
Tk

### PR DESCRIPTION
**Pull request by Teekuningas**
Should fix #3871. I went through all mne-python's own related callback functions and seems they can all handle both axes object or pyplot coming.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
LGTM. Can you add an entry in `doc/whats_new.py` in the BUG section, and add a URL for yourself at the bottom if you're not already there?

**Comment by Eric89GXL** [comment]
Thanks for the quick update. I changed the title to have MRG prefix to show that it's ready (from your end) for merge, and MRG+1 to show I approve. Now we just wait for the CIs to come back happy and the next dev to look can merge.

**Comment by Teekuningas** [comment]
Thanks, happy to contribute, 

-- Tk

**Comment by agramfort** [comment]
@jaeilepp is that ok for you?

as @jaeilepp wrote this I'd like him to double check.

thx @Teekuningas

**Comment by mmagnuski** [comment]
Looks good 👍

**Comment by jaeilepp** [comment]
Looks like the right fix. Thanks @Teekuningas

**Pull request merged**
