### PR TITLE
DOC: Fix docs of surf source spaces

### LINKED ISSUE #11170: mne.source_space.add_source_space_distances not correctly populating some attributes
### Description of the problem

There is a problem with the values added by mne.source_space.add_source_space_distances.  I've run this on the sample data, using the oct-6 forward model, which contains (for the left hemisphere) 155407 vertices in the dense mesh with 3732 vertices in the subsampled mesh. 

According to the documentation, the attribute 'patch_inds' should represent, "for each vertex in the subsampled surface, the indices of the vertices in the dense surface that it represents." It is supposed to be a list of arrays. However, after running mne.source_space.add_source_space_distances, src[0]['patch_inds'] is not a list of arrays, it is a single array with length 3732. The values in the array don't even correspond to the single nearest vertex in the dense space, because the values in the array only range from 13 - 4097.

Similarly, the documentation states that 'nearest' represents, "for each vertex on the dense surface, the vertex index on the subsampled surface that its closest to." So 'nearest' should be an array with length 155407, with values between 0 and 3731. While it is an array of length 155407, the values range from 59 to 153933. 

### Steps to reproduce

```Python
import mne
from mne.datasets import sample, fetch_fsaverage
import numpy as np
# Paths to example data
sample_dir_raw = sample.data_path()
sample_dir = sample_dir_raw / 'MEG' / 'sample'
subjects_dir = sample_dir_raw / 'subjects'
fname_stc = sample_dir / 'sample_audvis-meg'

# Read the raw data
raw = mne.io.read_raw_fif(raw_fname)
fwd_fname = meg_path / 'sample_audvis-meg-oct-6-fwd.fif'
forward = mne.read_forward_solution(fwd_fname)
mne.source_space.add_source_space_distances(src,dist_limit=0.01)

# the contents of patch_inds - a single array
src[0]['patch_inds']
# if patch_inds gives the corresponding vertex in the original dense mesh, these 
# numbers should go up to the total number of vertices in the dense mesh; 155407. 
# But they max out at 4097
np.max(src[0]['patch_inds'])

# the contents of nearest. This is supposed to be the nearest vertex on the 
# subsurface for every vertex on the dense surface. So these values should only
# go up to the number of vertices on the subsurface - 3732
np.max(src[0]['nearest']
```

### Link to data

_No response_

### Expected results

The attribute 'patch_inds' should be a list of arrays (of length nuse), where each array contains the nearest vertices in the dense mesh - thus the range of values should be from 0 to np. 

The attribute 'nearest' should be an array with shape (np,) with values representing the nearest vertex in the subsampled mesh - thus the values should range from 0 to use

### Actual results

In [37]: np.shape(src[0]['patch_inds'])
Out [37]: (3732,)
In [38]: np.max(src[0]['patch_inds'])
Out [38]: 4097
In [39]: np.max(src[0]['nearest'])
Out [39]: 155330

### Additional information

Platform:         macOS-10.15.7-x86_64-i386-64bit
Python:           3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:03:09) [Clang 13.0.1 ]
Executable:       /Users/nugenta/opt/anaconda3/envs/mne2022/bin/python
CPU:              i386: 4 cores
Memory:           16.0 GB

mne:              1.1.0
numpy:            1.22.4 {blas=NO_ATLAS_INFO, lapack=lapack}
scipy:            1.9.0
matplotlib:       3.5.3 {backend=module://matplotlib_inline.backend_inline}

sklearn:          1.1.2
numba:            0.55.2
nibabel:          4.0.1
nilearn:          0.9.1
dipy:             1.5.0
cupy:             Not found
pandas:           1.4.3
pyvista:          0.36.1 {OpenGL 4.1 INTEL-14.7.28 via Intel(R) UHD Graphics 617}
pyvistaqt:        0.9.0
ipyvtklink:       0.2.2
vtk:

### PR DESCRIPTION
**Pull request by larsoner**
Closes #11170

### CODE REVIEW

**Review by agramfort — APPROVED** [review]
Thx @larsoner

**Comment by nugenta** [comment]
Perhaps I'm being dense, but is n_src_remaining stored anywhere? It does not seem to be an attribute of SourceSpaces. I don't know that I've run into a case where the forward model uses fewer vertices than nuse.

**Comment by larsoner** [comment]
It's just `src[0]['nuse']` after forward calculation. If you set `mindist=5` for example some subjects will have vertices excluded for being too close to the inner skull surface

**Comment by nugenta** [comment]
I apologize if I'm just not getting this. Right now, src[0]['patch_inds'] = np.arange(0,src[0]['nuse'],1). Under what circumstances would patch_inds give something different?

**Comment by larsoner** [comment]
> Right now, src[0]['patch_inds'] = np.arange(0,src[0]['nuse'],1). Under what circumstances would patch_inds give something different?

Yes probably for your data this is true both before and after forward calculation. But for `sample` where some vertices are excluded, it won't be:
```Python
>>> import mne
>>> data_path = mne.datasets.sample.data_path()
>>> src = mne.read_source_spaces(data_path / 'subjects' / 'sample' / 'bem' / 'sample-oct-6-src.fif')
>>> print(src)
<SourceSpaces: [<surface (lh), n_vertices=155407, n_used=4098>, <surface (rh), n_vertices=156866, n_used=4098>] MRI (surface RAS) coords, subject 'sample', ~27.4 MB>
>>> src_fwd = mne.read_source_spaces(data_path / 'MEG' / 'sample' / 'sample_audvis-meg-oct-6-fwd.fif')
<SourceSpaces: [<surface (lh), n_vertices=155407, n_used=3732>, <surface (rh), n_vertices=156866, n_used=3766>] MRI (surface RAS) coords, subject 'sample', ~27.4 MB>
```
so you see some have been excluded. Then `'pinfo'` is not modified:
```Python
>>> print(len(src[0]['pinfo']))
4096
>>> print(len(src_fwd[0]['pinfo']))  # unchanged!
4096
```
but `'patch_inds'` length is reduced to match the (reduced) number of vertices retained:
```Python
>>> print(len(src[0]['patch_inds']))
4098
>>> print(len(src_fwd[0]['patch_inds']))
3732
```
so you can use it to index into the original `'pinfo'`. For example to know which dense surface vertices are represented by the 100th `src[0]['vertno']` vertex (index 99), you would need to use `src[0]['pinfo'][src[0]['patch_inds'][99]]`. If you didn't have the `'patch_inds'` and just used `src[0]['pinfo'][99]`, you'd end up looking at the wrong `'pinfo'` entry because:
```Python
>>> src[0]['patch_inds'][99]
168
```
indicating that many of the removed vertices were in the first ~168 vertices of the subsampled mesh, because index-99 *remaining* subsampled vertex points to the index-168 entry in `src[0]['patch_inds']`. Or to say it with code, "how many of the first 168 vertices of the original subsampled mesh were retained after forward calculation eliminated some of them", we recover our 99 index:
```Python
>>> np.in1d(src[0]['vertno'][:168], src_fwd[0]['vertno']).sum()
99
```

I wouldn't be offended if you called this an "indexing nightmare", but hopefully it's at least all consistent and/or can be used for what you need :)

**Comment by nugenta** [comment]
OH! I see the source (no pun intended) of my confusion:
>>> forward = mne.read_forward_solution(fwd_fname)
>>> src = forward['src']
>>> len(src[0]['pinfo'])
4098
>>> mne.source_space.add_source_space_distances(src,dist_limit=0.02)
>>> len(src[0]['pinfo'])
3732

I don't know if this is desired behavior or not, but it is confusing...

**Comment by larsoner** [comment]
> I don't know if this is desired behavior or not, but it is confusing...

Ahh interesting. I've never seen people add patch/distance information after forward. In your case if you have `len(src[0]['pinfo']) == 3732` *and* you have that `array_equal(src[0]['patch_inds'], np.arange(3732)` then things are at least consistent, and the recommended indexing should work.

Maybe we should add a note that we recommend to add distances etc. at the source space creation stage before forward since it's more standard.

**Comment by nugenta** [comment]
Right! In this case, the data had been initially prepared with an application in mind that didn't require the distance information. Then we decided to do some simulations and testings of beamformer parameters. Since that required knowing localization accuracy (from the simulated active vertex) we needed information about neighbors. That led to using mne.source_space.add_source_space_distances to add the distances after the fact. Perhaps include a note in the doc for add_source_space_distances noting that when this function is applied after the forward model is already created, information about sources in the original subsampled space that were eliminated during forward model computation
 will not be retained.

**Pull request merged**
