### PR TITLE
MAINT: Use towncrier for release notes

### LINKED ISSUE #11508: MAINT: Improve changelog documentation process
To aid in releases and PRs, it would be nice not to have to do so much changelog management. In particular, it would be great if:

1. We didn't have to tell people to add anything to `doc/changes/latest.inc` 
2. A changelog could be (at least nearly) automatically generated

Ideas:

- In sphinx-gallery we use [github-changelog-generator](https://github.com/github-changelog-generator/github-changelog-generator) in between releases. You label PRs (before or after merge!) to get them correctly categorized as enhancement/bug. I *think* you can even change the PR title *after the merge* to then have that text used in the changelog entry.

Clearly this list is incomplete :) @drammock or others feel free to add other ideas up here after commenting about them below

### LINKED ISSUE #12233: DOC: Update changelog sections
> We should have na "Dependencies" section in the changelog to mention changes of dependencies. @larsoner WDYT?

_Originally posted by @hoechenberger in https://github.com/mne-tools/mne-python/issues/12218#issuecomment-1822460874_
            
We've had our changelog section names for a long time, but I'm not sure if they're the best. I agree it would be nice to have a place where we mention stuff like the 3.8->3.9 bump, NumPy min changes, and EDFlib-Python -> edfio changes.

I think we should look at how NumPy, SciPy, matplotlib, sklearn, and pandas do things. They've often thought hard about this stuff and it would be nice to maintain consistency with the scientific Python ecosystem.

### PR DESCRIPTION
**Pull request by larsoner**
From the dev meeting today, we discussed a bit different options. @sappelhoff @agramfort you also commented in #11508 so I thought I'd bring your attention to this PR.

Towncrier was suggested by @drammock in #11508. Turns out that it's used by pip, pytest, and astropy, so should be well supported. Advantages relative to what we do now, all of which should make maintenance and contributing easier:

1. No more merge conflicts
2. More standard tool
3. Can automate "hey, please add a changelog entry" using [an existing scientific-python action that checks for it](https://github.com/scientific-python/action-towncrier-changelog)
4. Can easily (I think) automate PR number addition (see below)

Minor arguable disadvantages:

1. Ordering is by PR number, so `newcontrib` no longer come first.
2. Automatic parenthetical at the end that links to the PR can only have a single PR number, so the workaround is to add any additional PRs as manual parentheticals like I do in this PR.
3. Notable changes must have bullet points and will have a PR number associated with them.

**However**, all three of these are pretty easy to fix manually at release time, so I think we can live with them for the benefits.

I think it will be easy at release time to use `towncrier` directly to create a `doc/changes/v1.7.rst` for example and remove the stubs from `devel`, which is great as well.

| main | PR |
| -- | -- |
| Screenshot from 2023-12-15 15-12-05 |Screenshot from 2023-12-15 15-10-58 |

`towncrier` wants to see files of the form `<issue>.<type>.ext`, so at the end of the day we need for example `doc/changes/devel/12345.enhancement.rst`. If you want to open a PR with an entry, currently you have to check to see what PR number you will get when you open by looking at the issues list, or open it *then* push your entry. With this PR, I'm going to write a little GitHub action (or improve the existing scientific-python one) so that you can just add `doc/changes/devel/enhancement.rst` and it will automatically `git mv` this to `doc/changes/devel/{{ github.event.number}}.enhancement.rst` for you!

Todo before merge I think:

- [x] Break out current changes into stub files
- [x] Use [`sphinxcontrib-towncrier`](https://github.com/sphinx-contrib/sphinxcontrib-towncrier) to populate `devel.rst` on the fly
- [x] Add `action-towncrier-changelog`
- [x] Verify that the action raises an error for this PR

Separate PR:

- New action to add PR number to `doc/changes/devel/*.rst` files

Closes #12233
Closes #11508

### CODE REVIEW

**Comment by drammock** [comment]
looks good so far!  One comment and one question:

- the screenshot says "Enhancements" rather than the "New Features" title we agreed on at the dev mtg.
- *When* do things get marked as "notable changes"? I'm guessing it could be done at PR time, or at release time, equally easily?
- *How* do things get added to "notable changes"? I can see 3 options, each with its own upsides/downsides:
    - PR only appears in "notable"
    - PR appears (copied verbatim) in "notable" and in its other natural category
    - PR appears in "notable" and in its natural category, but with different text in each place.

**Comment by larsoner** [comment]
Successfully failing!

Screenshot 2023-12-15 at 4 59 54 PM

> the screenshot says "Enhancements" rather than the "New Features" title we agreed on at the dev mtg.

Pushing to fix

> When do things get marked as "notable changes"?

`Notable changes` is a section just any any of the others (not special in any way). `towncrier` just takes all the `changes/devel/NNNNN.type.rst` files and creates the doc. Until we tell it to remove these and finalize the doc (which we'd do at release time), the `doc/changes/devel/*.rst` live in the repo, so they can be edited or appended to or whatever.

> How do things get added to "notable changes"?

Whenever you add a `12345.notable.rst` with whatever content you want. So it could be the same, different, etc. from any other entry to any other section. Nothing stops you from also adding a companion `12345.feature.rst` for example with whatever content you want. `towncrier` will add the contents of `12345.notable.rst` to `Notable changes` section and the `12345.feature.rst` to the `New features` section. So it's up to us to decide how to split it.

**Comment by drammock** [comment]
> So it's up to us to decide how to split it.

This is what I was actually trying to ask about (sorry that wasn't clear). So asking again: how do we *want* to populate the "notable changes" section?

1. with duplicates of entries from other sections
2. with entries from other sections, but reworded to be... better in some way (more high-level, less technical, more verbose, ...?)
3. as the sole entry for the PR to which it is related

**Comment by larsoner** [comment]
I think we can play it by ear / case-by-case. Generally I think (2) and (3) are better than (1). So far the case we do have is (2).

**Comment by cbrnr** [comment]
I'd prefer (3), (1) is the worst option IMO.

**Comment by sappelhoff** [comment]
> I'd prefer (3), (1) is the worst option IMO.

agreed! (2) would be acceptable for me, and then less technical+more verbose and high level would be good.

**Comment by hoechenberger** [comment]
I'm a big fan of option 2

**Comment by larsoner** [comment]
@drammock I think we can do the auto-add-PR-number as a separate follow-up PR. Okay to merge this once I fix the conflicts so we can give it a shot (assuming consensus/decision is reached in #12233)?

**Comment by drammock** [comment]
> @drammock I think we can do the auto-add-PR-number as a separate follow-up PR. Okay to merge this once I fix the conflicts so we can give it a shot (assuming consensus/decision is reached in #12233)?

I don't have time for a careful review of the code changes this morning, but I'm +1 to move ahead if CIs are green, you're satisfied with the config, and it follows https://github.com/mne-tools/mne-python/issues/12233#issuecomment-1858197294.

**Pull request merged**
