### PR TITLE
MRG: Public base classes

### LINKED ISSUE #3781: more consistent class instances/types
It is unintuitive and surprising (at least to me and @jasmainak) that:

```python
my_epochs = mne.read_epochs('my_data-epo.fif.gz')
isinstance(my_epochs, mne.Epochs)  # returns False ?!!
```

It would be nice if `mne.epochs.EpochsFIF` were a subclass of `mne.Epochs` so that type checking were more straightforward.  Similar argument applies to the various different types of `Raw` objects.  @Eric89GXL has suggested (on Gitter) making `_baseEpochs` public as one solution, with a caveat in the docstring that it shouldn't be instantiated directly in user code.

### PR DESCRIPTION
**Pull request by drammock**
closes #3781 

`make test-fast` passes locally; due to the nature of the changes (almost entirely find-replace) I didn't bother with `make test-full`.

### CODE REVIEW

**Comment by drammock** [comment]
@agramfort @Eric89GXL @dengemann Let me know whether this warrants an entry in `whats-new` or if there are specific changes to the docs that are needed.

**Comment by dengemann** [comment]
It does! This an important API event.

**Comment by mmagnuski** [comment]
I'm afraid multiple users (myself included) have relied on _BaseEpochs and _BaseRaw for type checks in their functions - so that would break their code. Now I'd have to check mne version and import _BaseRaw or BaseRaw in my code (so that it works for me and students/coworkers etc.). I'm not sure if deprecation cycle fits here, but although these classes were private - type checking for raw and epochs seems to be very basic and common...

**Comment by dengemann** [comment]
I am sorry but if a function is private it's private for a good reason. If
you build code based on private functions you do so at your own risk. Maybe
with a good text editor you can fix this rather easily on your end. Unless
we make something public there is absolutely no commitment to be made to
it. Hope it's not hotting you too badly.

**Comment by mmagnuski** [comment]
Yes, I understand that - it's no big deal. I just expect many other people using _BaseRaw and _BaseEpochs because checking if something is epochs was inconvenient without using the base class. But I may be the only one and I'm actually happy to have these base classes public :)

**Comment by dengemann** [comment]
I understand you very well, I am most probably concerned myself. But it's
our risk to rely on private functions. There is no API unless it's public.
And if we do not take this seriously we cannot get anything done at larger
scales. This is why we need to be so careful about it.

**Comment by agramfort** [comment]
@drammock you have some pep8 error cf travis 

besides LGTM

thx

**Comment by drammock** [comment]
@agramfort sorry, forgot to run `flake8` (embarrasing).  Fixed now.

**Comment by agramfort** [comment]
thx @drammock

**Pull request merged**
