### PR TITLE
BUG: Fixing Report multiprocessing

### LINKED ISSUE #9101: BUG: parse_folder() with n_jobs>1 for mne.Report causes attribute-error
#### Describe the bug
When changing the n_jobs-parameter for the parse_folder-method of mne.Report to a value greater than 1, an error is thrown.

#### Steps to reproduce
```python
import mne

path = mne.datasets.sample.data_path(verbose=False)
report = mne.Report(verbose=True)
report.parse_folder(path, pattern='*raw.fif', render_bem=False, n_jobs=2)
report.save('test.html', overwrite=True)
```

#### Expected results
No error.

#### Actual results
```python
Traceback (most recent call last):
  File "<decorator-gen-368>", line 22, in parse_folder
  File "C:\Users\marti\PycharmProjects\mne-python\mne\report.py", line 1620, in parse_folder
    r = parallel(p_fun(self, fname, info, cov, baseline, sfreq, on_error,
  File "C:\Users\marti\PycharmProjects\mne-python\mne\parallel.py", line 128, in run
    return fun(*args, **kwargs)
  File "C:\Users\marti\anaconda3\envs\mnedev\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "C:\Users\marti\anaconda3\envs\mnedev\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\Users\marti\anaconda3\envs\mnedev\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\Users\marti\anaconda3\envs\mnedev\lib\concurrent\futures\_base.py", line 440, in result
    return self.__get_result()
  File "C:\Users\marti\anaconda3\envs\mnedev\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
AttributeError: 'Report' object has no attribute 'projs'
```

#### Additional information
The error seems to be coming from line 362 in report.py. The report-object doesn't have the _projs_-attribute as if somehow lost attributes when being passed to the new process in __iterate_files_ (line 1620). Other attributes as _data_path_ and _title_ seem to survive.

### PR DESCRIPTION
**Pull request by marsipu**
#### Reference issue
Fixes #9101.

#### What does this implement/fix?
This fixes the bug appearing when calling Report().parse_folder() with n_jobs>1 by adding _projs_ to the list of pickled attributes in _get_state_params().

Solution suggested by @larsoner

### CODE REVIEW

**Comment by marsipu** [comment]
test_report returns 6 errors out of 23, which all seem to related to:
```python
ModuleNotFoundError: No module named 'tvtk.custom.renderer
```
And they also appear in the main branch.

**Comment by larsoner** [comment]
Locally I can't replicate that issue, at least on `main`. Can you try:
```
pip uninstall mayavi
pip install --no-cache mayavi
```
and see if it helps?

**Comment by marsipu** [comment]
Yes, that helped (although I just seem to have replaced the same version of mayavi (4.7.2))

**Comment by larsoner** [comment]
If you updated `vtk` in between it breaks Mayavi...

>No everything passes (except one Deprecation-Warning:

Maybe `pip install --upgrade pyreadline`? I have 2.1 and don't see this deprecation warning

**Comment by marsipu** [comment]
> 
> 
> If you updated `vtk` in between it breaks Mayavi...
> 
> > No everything passes (except one Deprecation-Warning:
> 
> Maybe `pip install --upgrade pyreadline`? I have 2.1 and don't see this deprecation warning

pyreadline is already 2.1 and the deprecation-warning stays. But I use Windows, maybe that makes a difference?
By the way, what method would you recommend to keep the development-conda-environment up to date?
`conda env  update -n mnedev -f environment.yml`?
And/or something pip-related?

**Comment by larsoner** [comment]
@marsipu can you add an entry in `doc/changes/latest.inc` to mention this fix? Then I think we can merge. We could in principle add a test but it's often a problem to do so with parallel processing. One potential test would be to pickle and unpickle and ensure `.projs` is there -- this should fail on `master` and pass on this PR I think.

**Comment by marsipu** [comment]
I added a test which just tests `parse_folder()` and `save()` of Report after pickling the object, which fails on `main`. What do you think?

Thanks.

**Review by larsoner — APPROVED** [review]
LGTM +1 for merge, thanks @marsipu !

**Review by agramfort — APPROVED** [review]

**Comment by agramfort** [comment]
thx @marsipu

**Comment by hoechenberger** [comment]
Great job!!

**Pull request merged**
