### PR TITLE
[BUG, MRG] Fix how montage is set in ieeg locate gui

### PR DESCRIPTION
**Pull request by alexrockhill**
Fixes https://mne.discourse.group/t/unable-to-transform-montage-following-ieeg-electrode-localization-with-gui/5647/8

### CODE REVIEW

**Comment by alexrockhill** [comment]
Looks good to go to me!

**Comment by alexrockhill** [comment]
I tacked on a fix to this CI error:

```
mne/viz/tests/test_topomap.py:427: in test_plot_topomap_basic
    fig1 = evoked.plot_topomap('interactive', ch_type='mag',
mne/evoked.py:435: in plot_topomap
    return plot_evoked_topomap(
mne/viz/topomap.py:1783: in plot_evoked_topomap
    slider = Slider(axes[-1], 'Time', evoked.times[0], evoked.times[-1],
/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/matplotlib/_api/deprecation.py:449: in wrapper
    warn_deprecated(
/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/matplotlib/_api/deprecation.py:96: in warn_deprecated
    warn_external(warning, category=MatplotlibDeprecationWarning)
/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/matplotlib/_api/__init__.py:388: in warn_external
    warnings.warn(message, category, stacklevel)
E   matplotlib._api.deprecation.MatplotlibDeprecationWarning: Passing the valinit parameter of __init__() positionally is deprecated since Matplotlib 3.7; the parameter will become keyword-only two minor releases later.
```

I can split out if necessary.

**Comment by alexrockhill** [comment]
Oh man, not my lucky day for CI failures, Circle is not recognizing `numpy` references for some reason:

```
/home/circleci/project/doc/auto_tutorials/forward/50_background_freesurfer_mne.rst:125: WARNING: py:func reference target not found: numpy.dot
/home/circleci/project/doc/auto_tutorials/intro/40_sensor_locations.rst:374: WARNING: py:func reference target not found: numpy.where
/home/circleci/project/doc/auto_tutorials/preprocessing/25_background_filtering.rst:283: WARNING: py:func reference target not found: numpy.fft.ifft
/home/circleci/project/doc/auto_tutorials/raw/10_raw_overview.rst:696: WARNING: py:func reference target not found: numpy.save
/home/circleci/project/doc/auto_tutorials/raw/20_event_arrays.rst:75: WARNING: py:func reference target not found: numpy.save
/home/circleci/project/doc/auto_tutorials/stats-sensor-space/10_background_stats.rst:817: WARNING: py:func reference target not found: numpy.transpose
/home/circleci/project/mne/epochs.py:docstring of mne.epochs.Epochs:104: WARNING: py:func reference target not found: numpy.pad
/home/circleci/project/mne/epochs.py:docstring of mne.epochs.Epochs:47: WARNING: py:func reference target not found: numpy.sum
/home/circleci/project/mne/epochs.py:docstring of mne.epochs.Epochs:47: WARNING: py:func reference target not found: numpy.mean
/home/circleci/project/mne/epochs.py:docstring of mne.epochs.Epochs:22: WARNING: py:func reference target not found: numpy.pad
/home/circleci/project/mne/epochs.py:docstring of mne.epochs.EpochsArray:104: WARNING: py:func reference target not found: numpy.pad
/home/circleci/project/mne/epochs.py:docstring of mne.epochs.EpochsArray:47: WARNING: py:func reference target not found: numpy.sum
/home/circleci/project/mne/epochs.py:docstring of mne.epochs.EpochsArray:47: WARNING: py:func reference target not found: numpy.mean
/home/circleci/project/mne/epochs.py:docstring of mne.epochs.EpochsArray:22: WARNING: py:func reference target not found: numpy.pad
/home/circleci/project/mne/evoked.py:docstring of mne.evoked.Evoked:104: WARNING: py:func reference target not found: numpy.pad
/home/circleci/project/mne/evoked.py:docstring of mne.evoked.Evoked:47: WARNING: py:func reference target not found: numpy.sum
/home/circleci/project/mne/evoked.py:docstring of mne.evoked.Evoked:47: WARNING: py:func reference target not found: numpy.mean
/home/circleci/project/mne/evoked.py:docstring of mne.evoked.Evoked:22: WARNING: py:func reference target not found: numpy.pad
/home/circleci/project/mne/evoked.py:docstring of mne.evoked.EvokedArray:104: WARNING: py:func reference target not found: numpy.pad
/home/circleci/project/mne/evoked.py:docstring of mne.evoked.EvokedArray:47: WARNING: py:func reference target not found: numpy.sum
/home/circleci/project/mne/evoked.py:docstring of mne.evoked.EvokedArray:47: WARNING: py:func reference target not found: numpy.mean
/home/circleci/project/mne/evoked.py:docstring of mne.evoked.EvokedArray:22: WARNING: py:func reference target not found: numpy.pad
/home/circleci/project/mne/decoding/receptive_field.py:docstring of mne.decoding.receptive_field.ReceptiveField:108: WARNING: py:func reference target not found: numpy.convolve
/home/circleci/project/mne/decoding/receptive_field.py:docstring of mne.decoding.receptive_field.ReceptiveField:108: WARNING: py:func reference target not found: numpy.correlate
/home/circleci/project/mne/filter.py:docstring of mne.filter.filter_data:99: WARNING: py:func reference target not found: numpy.pad
/home/circleci/project/mne/filter.py:docstring of mne.filter.notch_filter:110: WARNING: py:func reference target not found: numpy.pad
/home/circleci/project/mne/filter.py:docstring of mne.filter.resample:29: WARNING: py:func reference target not found: numpy.pad
/home/circleci/project/mne/io/fiff/raw.py:docstring of mne.io.fiff.raw.Raw:104: WARNING: py:func reference target not found: numpy.pad
/home/circleci/project/mne/io/fiff/raw.py:docstring of mne.io.fiff.raw.Raw:99: WARNING: py:func reference target not found: numpy.pad
/home/circleci/project/mne/io/fiff/raw.py:docstring of mne.io.fiff.raw.Raw:47: WARNING: py:func reference target not found: numpy.sum
/home/circleci/project/mne/io/fiff/raw.py:docstring of mne.io.fiff.raw.Raw:47: WARNING: py:func reference target not found: numpy.mean
/home/circleci/project/mne/io/fiff/raw.py:docstring of mne.io.fiff.raw.Raw:49: WARNING: py:func reference target not found: numpy.pad
/home/circleci/project/mne/io/array/array.py:docstring of mne.io.array.array.RawArray:104: WARNING: py:func reference target not found: numpy.pad
/home/circleci/project/mne/io/array/array.py:docstring of mne.io.array.array.RawArray:99: WARNING: py:func reference target not found: numpy.pad
/home/circleci/project/mne/io/array/array.py:docstring of mne.io.array.array.RawArray:47: WARNING: py:func reference target not found: numpy.sum
/home/circleci/project/mne/io/array/array.py:docstring of mne.io.array.array.RawArray:47: WARNING: py:func reference target not found: numpy.mean
/home/circleci/project/mne/io/array/array.py:docstring of mne.io.array.array.RawArray:49: WARNING: py:func reference target not found: numpy.pad
/home/circleci/project/mne/time_frequency/spectrum.py:docstring of mne.time_frequency.spectrum.EpochsSpectrum:32: WARNING: py:func reference target not found: numpy.sum
/home/circleci/project/mne/time_frequency/spectrum.py:docstring of mne.time_frequency.spectrum.EpochsSpectrum:32: WARNING: py:func reference target not found: numpy.mean
/home/circleci/project/mne/time_frequency/spectrum.py:docstring of mne.time_frequency.spectrum.Spectrum:32: WARNING: py:func reference target not found: numpy.sum
/home/circleci/project/mne/time_frequency/spectrum.py:docstring of mne.time_frequency.spectrum.Spectrum:32: WARNING: py:func reference target not found: numpy.mean
/home/circleci/project/mne/viz/topomap.py:docstring of mne.viz.topomap.plot_epochs_psd_topomap:63: WARNING: py:func reference target not found: numpy.sum
/home/circleci/project/mne/viz/topomap.py:docstring of mne.viz.topomap.plot_epochs_psd_topomap:63: WARNING: py:func reference target not found: numpy.mean
```

This can't be backported so I might fix it separately but if someone else gets to it first go for it.

**Review by agramfort — APPROVED** [review]
Lgtm provided CIs are happy

**Comment by drammock** [comment]
I restarted the CIs, hopefully just a temporary timeout of the NumPy objects.inv

**Comment by drammock** [comment]
upstream bug opened for the numpy intersphinx crossrefs: https://github.com/numpy/numpy/issues/23032

**Comment by larsoner** [comment]
Thanks @alexrockhill !

**Pull request merged**
