### PR TITLE
[MRG+1] Fix IIR filtering

### LINKED ISSUE #5238: padding issue when filtering
to replicate:

```
import numpy as np
import mne

data = np.random.randn(1084, 64, 1077)  # CRASHES
# data = np.random.randn(934, 64, 1077)  # WORKS
mne.filter.filter_data(data, 512.0, 8, 12, method='iir', iir_params=dict(ftype='butterworth', order=5))
```

### PR DESCRIPTION
**Pull request by larsoner**
Closes #5238.

### CODE REVIEW

**Comment by massich** [comment]
The code LGTM. What I could not figure out is why [this error](https://travis-ci.org/mne-tools/mne-python/jobs/385293462#L2821). The current line is `if not isinstance(output, string_types) or output not in ('ba', 'sos')`. So I'm not sure where is Travis picking `if output not in ['ba', 'zpk']` from.

**Comment by larsoner** [comment]
Ancient SciPy error

**Comment by massich** [comment]
I gess it has to do with the fact that requires scypi>=0.16

**Comment by massich** [comment]
yep, it took me some time. I see you have tag the test and we are done with it. 
great!

**Pull request merged**
