### PR TITLE
FIX: define edf._read_segment in terms of samples

### PR DESCRIPTION
**Pull request by teonlamont**
Instead of using sfreq to determine the reading, read_segment now uses
the number of samples information from the header for all cases. Addresses #1767.

### CODE REVIEW

**Comment by agramfort** [comment]
travis et al. are not happy :(

**Comment by teonlamont** [comment]
happy again :)

**Comment by agramfort** [comment]
so are you? I suppose you tested all the files you have?

**Comment by teonlamont** [comment]
yep, i am. i did, I tested it with the other scripts. I just found a lightweight edf test file we can add to test reading the uneven sampling rates in edf but I'm currently waiting to build gcc + octave...

**Comment by agramfort** [comment]
ok. how big is the file?

**Comment by teonlamont** [comment]
26kb. I just realized something. I was going to use eeglab as a standard to
compare to but depending on how they resample the downsampled channel, the
values may be different.

-teon


Teon Brooks, Pre-hD
NSF Fellow, Chateaubriand Fellow
PhD Candidate
Department of Psychology
New York University

On Wed, Feb 4, 2015 at 5:59 PM, Alexandre Gramfort <notifications@github.com

**Comment by agramfort** [comment]
give it a try.

**Comment by teonlamont** [comment]
so i just discovered that the edf reader in EEGLAB (BIOSIG) resamples all channels to the least common multiple and just copy the value whereas we resample the lower sampled channels to the highest sampled EEG channel cf: https://github.com/mne-tools/mne-python/issues/1660.

**Comment by agramfort** [comment]
hum good to know.

any reason to do one or the other? shall we support both options?

**Comment by teonlamont** [comment]
i guess we can support both but make the default the interpolation. i hate adding arguments to functions especially since this one has its own fair share. i feel like the BIOSIG method may create added overhead though, but it would be allow to test the reading functionality against another package for these special cases.

**Comment by agramfort** [comment]
ok merge and open an issue so we don't forget.

**Comment by agramfort** [comment]
thanks @teonlamont 

I am opening the issue

**Pull request merged**
