### PR TITLE
[RFC] Funky meas_date behaviour

### PR DESCRIPTION
**Pull request by massich**
When working with #5839, I found some things that I'm not sure are ok. 
Like the fact that `meas_date` and `annotations.orig_time` lose sync.

Do you think that if a user mess up with `meas_date` she/he should know what
she/he's doing? or shall we overwrite the set of the `meas_date` to manually
sync it? What do you think about the fact that `raw.info['meas_date'] = 0` is
perfectly valid but `raw.info['meas_date'] = 10` would break somewhere down the line 'cos `meas_date` is supposed to be a tupple?

Just some random thoughts...

### CODE REVIEW

**Comment by larsoner** [comment]
> What do you think about the fact that raw.info['meas_date'] = 0 is perfectly valid but raw.info['meas_date'] = 10 would break somewhere down the line 'cos meas_date is supposed to be a tupple?

I don't know why this would be the case, it seems like it should always check for tuple-ness. I thought we implemented a check like this sometime recently.

**Comment by massich** [comment]
If this is green, it can be closed. Its cover by #6313

**Comment by larsoner** [comment]
It's not green. Still okay to close?

**Comment by massich** [comment]
No, the operation order is broken. Do we care about though? 

The problem is that if you set `raw.annotations` and then you change `raw.info['meas_date']` the annotations are no longer valid and it's silent. We don't update the annotations nor raise no warning or error.
To do any of those things we need to capture the setting of the dictionary. I've no idea how to do that from the top of the head nor in a short time.

@larsoner if you (or anybody else) knows a quick fix for it feel free to take over and ping me. Otherwise, you can either label it as **wont-fix** or move it to 0.19 and I'll get back to it.

**Comment by larsoner** [comment]
> The problem is that if you set raw.annotations and then you change raw.info['meas_date'] the annotations are no longer valid and it's silent. We don't update the annotations nor raise no warning or error.

Users should not manually change entries in `info`, other than `info['bads']`, otherwise things will break. As long as things work under anonymization (which should be the only place we change `info['meas_date']`, I think) then it should be fine.

**Comment by drammock** [comment]
Since users aren't supposed to change the info dict, and they can break things if they do, maybe we should consider some way of making it hard / impossible for them to do so? Like making its entries into read-only attributes?

**Comment by larsoner** [comment]
I seem to recall this coming up before and ultimately not making it in. Maybe the discussion is somewhere here if anyone is interested in looking further: https://github.com/mne-tools/mne-python/pull/2765

**Comment by massich** [comment]
This means to modify the dictionary class. And I don't think it would be an easy fix. The anonymization works because we reset `raw.annotations.orig_time`. 

I think that the most pragmatic thing is to assume that [in python we are all consenting adults](https://python-guide-chinese.readthedocs.io/zh_CN/latest/writing/style.html#we-are-all-consenting-adults
and if you mess up with info, it's at your own risk. I did a quick search in the issue tracker and I couldn't find anyone reporting a bug. But I guess that it would be good to state that in the documentation so that if someone messes it up, we can point them there.

**Comment by massich** [comment]
The discussion about `raw.info`'s contract is in #2860

**Pull request closed without merging**
