### PR TITLE
Add annotations support for exporting epochs to eeglab format

### PR DESCRIPTION
**Pull request by jackz314**
#### Reference issue
N/A

#### What does this implement/fix?
Adds support for annotations when exporting epochs to eeglab (set) format. Based on updates to the [eeglabio](https://github.com/jackz314/eeglabio) package.

#### Additional information
Annotations will be converted and merged with the events array in eeglab, this behavior is consistent with when exporting raw data to eeglab. 

#### Breaking changes
users with the older version of eeglabio and the updated version of mne would have to update eeglabio to `>=0.0.2`, since the `annotations` field doesn't exist in older versions.

### CODE REVIEW

**Review by sappelhoff — COMMENTED** [review]
just a note that you still need to make the 0.0.2 release on GitHub :-)

https://github.com/jackz314/eeglabio/releases

**Comment by jackz314** [comment]
Thanks for the reminder, released.

**Review by sappelhoff — COMMENTED** [review]
Can you add a small test for this new feature?

**Comment by jackz314** [comment]
While writing round-trip tests, I encountered some problems due to how events/annotations are represented. Events and annotations from mne are merged into the `event` and `epoch` array in eeglab format, but when reading again in mne, it only takes the first event per epoch's latency and just merges the event types, which could mean potential data loss. This is not a concern for us currently, but I was wondering if it's intentionally designed this way for some reason.

**Comment by sappelhoff** [comment]
Is there something that could be changed in mne to make a round-trip of writing annotations to EEGLAB epochs possible?

Another question: When you write annotations to EEGLAB epochs from mne ... can you properly read these epochs in EEGLAB? And if yes, why does EEGLAB succeed but not mne?

**Comment by jackz314** [comment]
I'm still not exactly sure about all the use cases of the events array in mne, especially its relationship with epochs, so maybe there's a reason events and epochs are one-to-one matching. But I think allowing reading more than one event per epoch instead of ignoring or merging them could preserve all data from the EEGLAB format to mne. 

As for EEGLAB epochs, they're not tied to events, and instead are tied to another data structure [`epoch`](https://eeglab.org/tutorials/ConceptsGuide/Data_Structures.html#eegepoch), so these epochs still work even with random annotations. But mne seem to rely on these events to construct epochs somehow, which makes it fail.

I will look more into these later, but this is my understanding so far.

**Comment by sappelhoff** [comment]
I think @adam2392 implemented annotation support for epochs, perhaps he can help (now or later)

**Comment by cbrnr** [comment]
The changes in eeglabio 0.0.2 seem to have broken export on `main` (see also #11010):
https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=21054&view=logs&j=dded70eb-633c-5c42-e995-a7f8d1f99d91&t=6a33d698-56da-505a-4bdd-64e49791e9d1&l=3242

It would be good to fix this ASAP. In addition, since MNE is probably the most important (only?) consumer of eeglabio, would it be possible to at least run the tests in `mne.export` in your repo to avoid breaking changes @jackz314?

**Comment by jackz314** [comment]
The error you're referring seem to be caused by a warning for invalid event latencies, it occurs when event latencies don't start from 0. In eeglabio I just ignore them and generate a fake one that starts from 0 since I don't think there's a way to recover the original event latencies in an `Epoch` instance (we need the original starting sample to offset the event latencies).

**Comment by cbrnr** [comment]
But did you change this from 0.0.1 to 0.0.2?

**Comment by jackz314** [comment]
Yes, this is a new change in 0.0.2, I didn't know warnings would be treated as errors in the ci runs, I could change it to a simple print statement to avoid the errors.

**Comment by larsoner** [comment]
I'll merge this to get CIs green, thanks @jackz314 !

**Comment by cbrnr** [comment]
You could also log to info.

**Comment by larsoner** [comment]
Argh, CIs were green on this *before* the 0.0.2.post1 release. I'll make a quick PR to get things green at least

**Comment by larsoner** [comment]
https://github.com/mne-tools/mne-python/pull/11012

**Comment by jackz314** [comment]
> Argh, CIs were green on this _before_ the 0.0.2.post1 release. I'll make a quick PR to get things green at least

@larsoner I just switched to logging the warnings instead of raising them in `main` of eeglabio, it should fix the ci problems without your quick patch once I release the patched version.

**Pull request merged**
