### PR TITLE
Fix interactive zoom in plot_epochs_image.py (evoked=True)

### LINKED ISSUE #9108: Make an interactive ERP subplot for an ICA component
#### Describe the new feature or enhancement
Currently, when displaying the individual ICA component, the ERP subplot is not interactive. We want to make this subplot interactive .

#### Describe your proposed implementation
Implement a rectangle selector to zoom in and out for this plot.

### PR DESCRIPTION
**Pull request by mdclarke**
#### Reference issue
Fixes #9108

#### What does this implement/fix?
Stops curve from extending outside of axis when interactively zooming, and shares axes between both subplots when `plot_epochs_image(evoked=True)`

Can test on `plot_epochs_image` :

```
import os
import mne

# read in sample data
sample_data_path = mne.datasets.sample.data_path()
raw_fname = os.path.join(sample_data_path, 'MEG', 'sample', 
                         'sample_audvis_filt-0-40_raw.fif')
raw = mne.io.read_raw_fif(raw_fname, verbose=False)
events_fname = os.path.join(sample_data_path, 'MEG', 'sample', 
                            'sample_audvis_filt-0-40_raw-eve.fif')
events = mne.read_events(events_fname)
event_dict = {'auditory/left': 1, 'auditory/right': 2, 'visual/left': 3,
              'visual/right': 4}
tmin, tmax = (-0.2, 0.5) 
baseline = (None, 0)     
epochs = mne.Epochs(raw, events, event_dict, tmin, tmax, proj=True,
                    baseline=baseline, preload=True)
# test plot
epochs.plot_image(picks='grad', evoked=True)
```

### CODE REVIEW

**Comment by mdclarke** [comment]
@drammock I think the params to change the y-axis for the evoked plot in `plot_epochs_image` are set in the code for `plot_compare_evokeds`. I'm not sure if its best to change that since its used for a lot of other things. What do you think?

**Review by drammock — APPROVED** [review]

**Review by larsoner — COMMENTED** [review]
@mdclarke can you add an entry to `latest.inc` in the `Bug` section to mention this fix? Otherwise LGTM +1 for merge

**Comment by mdclarke** [comment]
> @mdclarke can you add an entry to `latest.inc` in the `Bug` section to mention this fix? Otherwise LGTM +1 for merge

Done. Thanks Eric!

**Comment by drammock** [comment]
```
changes/latest.inc:138: WARNING: Undefined substitution referenced: "Maggie Clarke".
changes/latest.inc:138: WARNING: Unknown target name: "maggie clarke".
```

You need to do 2 things:

1. add yourself to `doc/changes/names.inc`
2. near the top of `doc/changes/latest.inc` add a "new contributors substitution" line (LMK if it's not clear what to do from looking at the file)

**Review by drammock — APPROVED** [review]

**Comment by larsoner** [comment]
Thanks @mdclarke !

**Pull request merged**
