### PR TITLE
remove the verbose from construction of SlidingEstimator as it was not being used anywhere and it was only making people confused .

### PR DESCRIPTION
**Pull request by DeepakSingh260**
Thanks for contributing a pull request! Please make sure you have read the
[contribution guidelines](https://mne.tools/dev/install/contributing.html)
before submitting.

Please be aware that we are a loose team of volunteers so patience is
necessary. Assistance handling other issues is very welcome. We value
all user contributions, no matter how minor they are. If we are slow to
review, either the pull request needs some benchmarking, tinkering,
convincing, etc. or more likely the reviewers are simply busy. In either
case, we ask for your understanding during the review process.

Again, thanks for contributing!

#### Reference issue
Example: Fixes #1234.

#### What does this implement/fix?
Explain your changes.

#### Additional information
Any additional information you think is important.

### CODE REVIEW

**Comment by mmagnuski** [comment]
Hi @DeepakSingh26, we were just discussing this in #11444. I think it is better to make fix verbose instead of removing it.

**Comment by agramfort** [comment]
yes let's rather fix. It will avoid an API change and the need for a deprecation.

**Comment by DeepakSingh260** [comment]
Sure ,

**Comment by mmagnuski** [comment]
The verbose behavior for sliding and generalizing estimator has been fixed.

**Pull request closed without merging**
