### PR TITLE
MRG, BUG: Fix M/EEG topomap plotting

### LINKED ISSUE #3987: ENH: plot_topo layout creation
It seems like we keep hitting issues with topo scaling confusing people. I think we probably shouldn't change where (0., 0., 0.) is in any given channel layout, and instead ensure that our internal layouts are actually in head coordinates. I wonder if we could also just assume a head is e.g. 90 cm. That would make subselections of electrodes appear correct. A `normalize=True (default) | False` argument in functions that do such topologies could do it.

@jaeilepp WDYT?

### LINKED ISSUE #4880: Q: why eletrode positions plot is different from other tools like Fieldtrip?
In the Wikipedia [10–20 system (EEG)](https://www.wikiwand.com/en/10%E2%80%9320_system_(EEG)) the electrode positions when plotting are much like the following image (**EEG1010.lay**) extracted from Fieldtrip, where the midline (T9 -- Cz  -- T10) is definitely a straight line.

eeg1010 lay

But in MNE when I plot the standard montage like the following:

```python
import mne

montage = mne.channels.read_montage('standard_1020')
montage.plot()
```
I end up with this plot (**standard_1020**) where the (T9 -- Cz  -- T10) line is curved down.

standard_1020

Why there's this difference? And there are any implications on topomap visualizations?

Thanks in advance!

### LINKED ISSUE #5190: plotting: topomap electrode positions change depending on number of channels
When using topoplot functions in MNE, I run into problems with the electrode positions that are plotted. Namely, when using the code below, the resulting sensor plots should look identical for the electrodes in `chan_selection`. However, this is not the case:

```python
import mne

chan_selection = [u'FC5', u'FC1', u'C3', u'CP5', u'CP1', u'FC2', u'FC6', u'C4', u'CP2', u'CP6']

montage1020_full = mne.channels.read_montage(kind='standard_1020', ch_names=None)
montage1020_reduced = mne.channels.read_montage(kind='standard_1020', ch_names=chan_selection)

montage1020_full.plot()
montage1020_reduced.plot()

```

## Full
figure_1

## Reduced
figure_2

---------------------------

I am aware of a bunch of related issues (e.g., #4880). Issue #3987 seems to be the central issue for this problem ... is anyone working on this currently? It seems like a pretty crucial problem to be solved, given that topoplots are a very common visualization in our domain.

Is this perhaps even affecting the interpolation of voltages across the scalp? Or is this problem merely distorting the "plotted dots" symbolizing the electrodes?

PS: When I use real data and `mne.viz.plot_evoked_topomap`, I get yet another image for the same electrodes:

screenshot from 2018-05-06 10-50-22

### LINKED ISSUE #5471: ENH: (Optionally) modify the head shown in `plot_topomap` for MEG data
Currently `plot_topomap` always shows a head centered in the MEG layout, i.e., head centered relative to the sensor positions that have been 3d-to-2d projected device coordinate frame.

We should be able to improve the accuracy of this by translating + "rotating" this head by, according to the information in `dev_head_t`:

- [x] Show x/y translation by moving the x/y location of the head (in #7066)
- [ ] ~~Show z translation (depth) by shrinking the head~~ (not doing it because it's going to get too confusing with flattening / ortho vs perspective projection)
- [ ] EDIT: Not doing this either because it's a bit overkill: Show rotation of the head relative to the sensors by:
    1. Showing a (rotated) cross-hairs on the top of the head (in the center of the head iff the rotation part of `dev_head_t` is `np.eye(3)`)
    2. Showing the ears and nose rotated properly (in gray if they are not visible because they are rotated downward)

I talked to @agramfort and this should be optional so that people can always get the "standard" plot back. But basically I think how we show things right now is essentially incorrect so I think we should add a parameter `transform_head` that moves from `False`(master) ->`True` (this proposal) via deprecation cycle (users only get a warning when showing MEG data).

This is of course contingent on this representation actually visually looking more informative.

### LINKED ISSUE #6304: VIZ: EEG sensor locations wrong in inset plots
EEG sensor plot insets seem to be broken in some cases. Here are a couple examples. First, from `plot_compare_evokeds`:

eeg

Similar problem with `evoked.plot(spatial_colors=True):

evoked_plot_spatial_colors

Compare those to the sensor positions w/r/t the head on `mne.channels.make_eeg_layout(raw.info).plot()` (`raw.plot_sensors()` gives similar result):

sphx_glr_working_with_sensor_locations_003

### PR DESCRIPTION
**Pull request by larsoner**
Closes #3987
Closes #4880
Closes #5190 
Closes #5471
Closes #5472 
Closes #6304

Todo:
- [x] ensure our montages actually use the same head sizes (done by dig refactoring)
- [x] Make the `plot_sensors` be in physical coordinates
- [x] make all code assume a 0.095 m head radius
- [x] check that all examples in gist are fixed
- [x] deprecate params: `transform` in `montage`, `outlines`, ...
- [x] get tests to pass again
- [x] change to `sphere` rather than `head_radius` for consistency and flexibility
- [x] change units in `setup_volume_source_space` for consistency
- [x] move head relative to MEG sensors based on `info['dev_head_t']`
- [x] check `plot_topomap`, `plot_sensors`, `montage.plot` examples via `circle full`
- [x] add `setup_volume_source_space` param and `layout` deprecation to API section of `latest.inc`

cc @jona-sassenhagen @sappelhoff @cbrnr you might be interested in this plan.

After this, due to using physical units for the head, #5471 should be simpler.

### CODE REVIEW

**Comment by mmagnuski** [comment]
That is indeed a lot of refactoring! Great work, I will test it during the weekend!

**Comment by larsoner** [comment]
Also I realized the most consistent API is to have a "sphere" argument allowing you to specify the origin and reading of the sphere. We have this elsewhere and I think in auto mode for digitized EEG locations it will look better.

But feel free to test that things are fixed. The sphere functionality would be a superset of this functionality, and I don't think the defaults will change from what's there now (essentially 0, 0, 0 origin and 9.5cm radius).

**Comment by larsoner** [comment]
Here are the `[circle full]` outputs:

https://16870-1301584-gh.circle-artifacts.com/0/dev/index.html

One `setup_volume_source_space` example was broken on that run but fixed in 9c0525c (probably not interesting from an evaluate-whether-or-not-this-works perspective)

There are several examples that are broken, though, so I'll fix those. I think it has to do with loading a `layout` when it should use the `_auto_topomap_coords` function instead.

**Comment by larsoner** [comment]
Okay, docs built

https://16891-1301584-gh.circle-artifacts.com/0/dev/index.html

CIs happy other than a small problem with Travis that I just pushed a commit to fix

**Comment by mmagnuski** [comment]
[this example](https://16891-1301584-gh.circle-artifacts.com/0/dev/auto_examples/io/plot_read_proj.html#sphx-glr-auto-examples-io-plot-read-proj-py) looks a bit weird:
image
head outlies are not where they should be.

**Comment by mmagnuski** [comment]
BTW is extrapolate `'local'` by default now? (it looks so in the example)

**Comment by larsoner** [comment]
> BTW is extrapolate 'local' by default now? (it looks so in the example)

Even worse, I had some debugging cruft in there that made it always use `local`. Pushing a fix for projs topomap plotting now. But hopefully the rest of the examples look okay.

**Comment by drammock** [comment]
Many many thanks for tackling this.  A few comments:

- in [this image](https://16895-1301584-gh.circle-artifacts.com/0/dev/_images/sphx_glr_plot_10_overview_015.png) it seems like the EEG electrodes don't get as close to the edge of the head as they should.  I thought the idea was that if a sensor were in the plane of the fiducials, it should fall on the edge of the head outline, yet even what looks like electrode `Iz` (which ought to fall *below* the fiducial plane right?) is still well away from the edge

- [here](https://16895-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/intro/plot_40_sensor_locations.html#working-with-layout-files) in a few calls to `Layout.plot()` the outline is missing.

- A question: what is the new deciding factor for whether to do a scalp topography with or without skirt?  For example in the ICA tutorial, the `corrmap` plots do not have skirts, but `ICA.plot_components()`, `ICA.plot_properties()`, and `evoked.plot_joint()` all do have skirts on this PR (whereas on current master only `evoked.plot_joint()` has skirts).

note that I didn't come close to looking at *all* the tutorials or examples so don't consider this a thorough review.  I can make time to do that if it's needed.

**Comment by drammock** [comment]
also strangely [this ERP plot](https://16895-1301584-gh.circle-artifacts.com/0/dev/_images/sphx_glr_plot_10_overview_009.png) is now flat, whereas [it's not on master](https://mne.tools/dev/_images/sphx_glr_plot_10_overview_009.png)

**Comment by larsoner** [comment]
>  yet even what looks like electrode Iz (which ought to fall below the fiducial plane right?) is still well away from the edge

No electrodes have `z<0`:

<details>

```
aud_epochs.average().pick_types(meg=False, eeg=True).plot_sensors(kind='3d')
```
Screenshot from 2019-11-20 09-25-32

</details>

I don't aesthetically like this contraction, but it seems to be a more true depiction of the channel positions.

Using `sphere='auto'` (which changes the flattening origin and radius) you see something probably closer to what you'd expect:

<details>

Screenshot from 2019-11-20 09-43-34

</details>

> here in a few calls to Layout.plot() the outline is missing.

This is intentional. The idea is that:
- head outlines are only shown only if `info['chs']` positions are used, typically in topomap plots
- `layout`s are schematics to be used only in interactive sensor selection and also `topo`-style plots for better separation of sensors, and should never be plotted with a head outline because it's potentially misleading about the geometry / head-to-sensor relationship.

> A question: what is the new deciding factor for whether to do a scalp topography with or without skirt?

Whatever old defaults there were should remain unchanged in this PR (that's the goal anyway!). What I did was that, regardless of which skirt you choose, it will always plot at least out to all the electrode positions. So for things like MEG sensors, even if you do `skirt='head'` this will be effectively ignored because the sensors are way outside the head boundary.

> strangely this ERP plot is now flat

Fixed by commit I just pushed. It was actually unrelated to this PR, and had non-deterministic behavior. It seemed to have to do with doing `get_ylim` before the limits had actually been calculated properly (probably some deep mpl bug), adding a `figure.draw_idle()` seems to fix it locally. We'll see if CircleCI agrees.

> I didn't come close to looking at all the tutorials or examples so don't consider this a thorough review. I can make time to do that if it's needed.

It would be helpful, even if you just opened each one and quickly flipped through to look to see if anything is obviously wrong.

**Comment by larsoner** [comment]
Updated full build:

https://16912-1301584-gh.circle-artifacts.com/0/dev/index.html

**Comment by agramfort** [comment]
often the topos are clipped the bottom. See

https://16912-1301584-gh.circle-artifacts.com/0/dev/auto_examples/io/plot_read_proj.html#sphx-glr-auto-examples-io-plot-read-proj-py
https://16912-1301584-gh.circle-artifacts.com/0/dev/_images/sphx_glr_plot_50_artifact_correction_ssp_016.png

any idea why?

>

**Comment by mmagnuski** [comment]
It looks as if the center of the head outline was not where the center of the of the circular aperture is.  Because of this we see where the extrapolation box ends - it is not ocvered by the aperture.

**Comment by drammock** [comment]
oops sorry I didn't mean to push directly to your branch @larsoner (though the changes are relevant to this PR)

**Comment by larsoner** [comment]
No problem, I was tweaking those a little bit so further adjustment is fine by me. In the meantime I'll look into the box-cutting-off-circle issue (I think @mmagnuski is right about the issue), hopefully that's the last one :)

**Comment by larsoner** [comment]
Okay, clipping should be fixed. Made code more DRY and modified a min/max check in the last commit I pushed to fix it. The Circle full build will currently fail because we need #7099 or some similar variant for it to succeed. Hopefully we can get one merged today and I'll rebase and force-push.

@agramfort I trust you'll have free time over the weekend that you want to dedicate to looking through every example :)

**Comment by agramfort** [comment]
maybe this one is still broken https://16984-1301584-gh.circle-artifacts.com/0/dev/auto_examples/visualization/plot_evoked_arrowmap.html#sphx-glr-auto-examples-visualization-plot-evoked-arrowmap-py

also the EEG topos now look weird on sample. I would like to know if it's still comparable topos to fieldtrip on the same data. @dengemann had spent a lot of time years ago to have the topomaps looking at fieldtrip results.

**Comment by larsoner** [comment]
See comment above, I think it's a more accurate representation of the 3D coordinates for sample. They are actually all 2cm or more above z=0 line. sphere='auto' is a better choice for actually digitized data (and it's better for sample), but it's not a good default because it behaves not so nicely for montages because it's affected by channel subsection in that case.

**Comment by larsoner** [comment]
Specifically here 

https://github.com/mne-tools/mne-python/pull/7066#issuecomment-556044554

**Comment by larsoner** [comment]
Actually one option would be to use sphere=None to mean 'auto' if there are enough extra did points to do a fit, and the default (0,0,0,0.95) otherwise. This would look better for sample and real data, but also not change with channel picking

**Comment by larsoner** [comment]
> maybe this one is still broken

[Fixed](https://16998-1301584-gh.circle-artifacts.com/0/dev/auto_examples/visualization/plot_evoked_arrowmap.html#sphx-glr-auto-examples-visualization-plot-evoked-arrowmap-py).

> also the EEG topos now look weird on sample.

These plots should now look closer to how they did before -- making `None` the default makes things look better for real digitized locations, while not messing up montages. See the Circle full build for examples:

https://16998-1301584-gh.circle-artifacts.com/0/dev/index.html

> I would like to know if it's still comparable topos to fieldtrip on the same data. @dengemann had spent a lot of time years ago to have the topomaps looking at fieldtrip results.

They still probably won't be totally comparable to Fieldtrip, as we are no longer trying to replicate Fieldtrip (as was done years ago). Instead this PR aims to systematically process / control the head-to-sensor relationship in topomap plotting as we have discussed in the linked issues [going back a while](https://github.com/mne-tools/mne-python/issues/3987#issuecomment-298920228). I think things looking similar to FieldTrip would be nice, but should not be the primary goal.

**Comment by drammock** [comment]
Looking at [this ERP image](https://16998-1301584-gh.circle-artifacts.com/0/dev/_images/sphx_glr_plot_10_overview_013.png) with sensor inset, and [this scalp field map](https://16998-1301584-gh.circle-artifacts.com/0/dev/_images/sphx_glr_plot_10_overview_015.png) from the same tutorial, they're not the same.  In fact, in [this joint plot](https://16998-1301584-gh.circle-artifacts.com/0/dev/_images/sphx_glr_plot_10_overview_014.png) the channel location inset and the scalp topographies on the same figure aren't matching.  I thought they matched before, maybe the `None = "auto"` trick isn't working the same in insets vs scalp field maps?

**Comment by larsoner** [comment]
Yep, forgot to pass `info` in one call, [should be fixed now](https://17004-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/intro/plot_10_overview.html).

**Comment by agramfort** [comment]
this looks really nice. I am just a bit worried about the now automatic
extrapolation way beyond helmet boundaries.
See for example

https://17004-1301584-gh.circle-artifacts.com/0/dev/auto_examples/io/plot_read_proj.html
<https://17004-1301584-gh.circle-artifacts.com/0/dev/auto_examples/io/plot_read_proj.html#sphx-glr-auto-examples-io-plot-read-proj-py>

where you clearly get the extreme values at the boundaries loosing the
dynamical range of values
inside the helmet convex hull.

See how brainstorm does this
https://www.frontiersin.org/files/Articles/435877/fnins-13-00076-HTML-r1/image_m/fnins-13-00076-g005.jpg
by
clipping outside of the helmet convex hull. Also now it's not so clear
anymore how head and skirt differ.

sorry for being a pain @larsoner ...

**Comment by larsoner** [comment]
>  I am just a bit worried about the now automatic extrapolation way beyond helmet boundaries.

To me it's not very different from how it is on `master` (just a tiny bit larger), other than that the head is smaller inside the interpolation area:

- https://17004-1301584-gh.circle-artifacts.com/0/dev/auto_examples/io/plot_read_proj.html
- https://mne.tools/dev/auto_examples/io/plot_read_proj.html

Hence I'd rather change the behavior in a separate PR. We have an extrapolation mode that does a convex hull operation. But if you want me to change the default interpolation mode in this PR I can do it.

> Also now it's not so clear anymore how head and skirt differ.

Head and skirt will differ more obviously for EEG when all sensors fit roughly inside the head.

For MEG not much will change because the sensors are generally outside the head circle, so the 1.25x factor for the circle gets ignored because the smallest circle that encompasses sensors is used:

https://github.com/mne-tools/mne-python/pull/7066/files#diff-2f146eb9390ce209fa40cf8fb1c7153dR378

I could instead make it that for MEG "head" does the smallest circle that encompasses sensors, and "skirt" does 1.25x this size, but it will make the problem above worse.

**Comment by mmagnuski** [comment]
The topos look all very good to me, great work!

> Hence I'd rather change the behavior in a separate PR. We have an extrapolation mode that does a convex hull operation. But if you want me to change the default interpolation mode in this PR I can do it.

I think it would be a good idea to keep this separate from changes to interpolation, the PR is already very big.

**Comment by agramfort** [comment]
@cbrnr do you have an opinion here?

**Comment by mmagnuski** [comment]
Just one (two actually) more thing extrapolation `'head'` does not work very well now:
image
this seems to be because the extrapolation points are placed on the head circle in this extrapolation method, while now channels are often plotted outside the head circle. The readius of the extrapolation circle could be increased.

The other thing is how animate_topomap renders:
image

**Comment by larsoner** [comment]
>  this seems to be because the extrapolation points are placed on the head circle in this extrapolation method, while now channels are often plotted outside the head circle. The readius of the extrapolation circle could be increased.

Ahh, I did not look at the head extrapolation mode. I'll see if I can do this tomorrow, and update the docstring for `extrapolate` to say it will go to the head circle or the sensor bounding circle, whichever is larger.

> The other thing is how animate_topomap renders:

Whoops! It is indeed broken in the [example that uses it](https://17004-1301584-gh.circle-artifacts.com/0/dev/auto_examples/visualization/plot_evoked_topomap.html) so I'll fix that tomorrow, too.

**Comment by larsoner** [comment]
Actually thinking about it more, I think `extrapolate='head'` is doing what it says it will do, so I think it's okay to leave it as is. We could in principle expand the radius in cases where sensors are outside the head circle, but I would say that in those cases people should really just use `extrapolate='local'` instead. It's less magical in terms of what it's doing.

**Comment by mmagnuski** [comment]
Hm, it just made a lot more sense before when all the channels were within the head circle by default. But I understand the logic of your reasoning. In that case maybe only the tutorial should be changed to not show extrapolate=head
The only problem with `'local'` now is that it creates pixelated edges - but thats a separate issue. I can work on this some time soon.

**Comment by mmagnuski** [comment]
I like the changes to the docs, thanks @larsoner!

**Comment by larsoner** [comment]
Bugs fixed:

https://17104-1301584-gh.circle-artifacts.com/0/dev/auto_examples/visualization/plot_evoked_topomap.html

**Comment by larsoner** [comment]
Docstrings fixed after rebase on #7129, force pushed

**Comment by agramfort** [comment]
thx @larsoner

**Comment by mmagnuski** [comment]
:confetti_ball: :rocket: !

**Pull request merged**
