### PR TITLE
DOC: Cleaner command line doc

### PR DESCRIPTION
**Pull request by larsoner**
I find it not so easy to read our [command-line docs](http://mne-tools.github.io/dev/generated/commands.html#mne-flash-bem):

Screenshot from 2019-03-29 17-46-04

Basically I tried to compromise between:

1. Compactness
2. Readability
3. Our API doc style/sections
4. What's standard in command-line utils, which is:
    ```console
    larsoner@bunk:~/python/mne-python/doc$ grep --help
    Usage: grep [OPTION]... PATTERN [FILE]...
    Search for PATTERN in each FILE.
    Example: grep -i 'hello world' menu.h main.c

    Pattern selection and interpretation:
      -E, --extended-regexp     PATTERN is an extended regular expression
      -F, --fixed-strings       PATTERN is a set of newline-separated strings
      -G, --basic-regexp        PATTERN is a basic regular expression (default)
      -P, --perl-regexp         PATTERN is a Perl regular expression
    ...
    ```

This is the result:

Screenshot from 2019-03-29 17-45-31

### CODE REVIEW

**Comment by larsoner** [comment]
Rendered doc: https://12025-1301584-gh.circle-artifacts.com/0/dev/generated/commands.html

**Comment by mmagnuski** [comment]
Looks great!

**Comment by larsoner** [comment]
Tweaked slightly: https://12027-1301584-gh.circle-artifacts.com/0/dev/generated/commands.html

**Comment by agramfort** [comment]
great !

+1 for merge when CIs are green

**Comment by larsoner** [comment]
Two +1's so in it goes, thanks for the quick reviews

**Pull request merged**
