### PR TITLE
FIX: volume

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR fixes the issues encountered after https://github.com/mne-tools/mne-python/pull/8576.

Closes https://github.com/mne-tools/mne-python/issues/8623

### CODE REVIEW

**Review by agramfort — APPROVED** [review]
@larsoner merge if happy

**Comment by GuillaumeFavelier** [comment]
The artifacts are available:

* [plot_seeg.py](https://24006-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/misc/plot_seeg.html#sphx-glr-auto-tutorials-misc-plot-seeg-py)

* [plot_source_space_snr.py](https://24006-1301584-gh.circle-artifacts.com/0/dev/auto_examples/inverse/plot_source_space_snr.html#sphx-glr-auto-examples-inverse-plot-source-space-snr-py)

**Comment by GuillaumeFavelier** [comment]
Should I try `[circle full]` to be sure?

I suppose we'll go through this for the next release anyway.

**Comment by larsoner** [comment]
Works great! Let's see what `circle full` does when we merge

**Comment by GuillaumeFavelier** [comment]
The artifacts are available:

https://24010-1301584-gh.circle-artifacts.com/0/dev/auto_examples/index.html

**Pull request merged**
