### PR TITLE
[MRG] BUG: Do not allow baseline removal after preload

### PR DESCRIPTION
**Pull request by hoechenberger**
#### What does this implement/fix?

In `master` and 0.21 it's possible to preload `Epochs`, apply baseline correction, and (seemingly) remove it again via `apply_baseline(None)`. This should not be allowed: removing BL correction can only happen as long as the data has not been loaded.

### CODE REVIEW

**Review by agramfort — APPROVED** [review]

**Comment by hoechenberger** [comment]
One test on Azure fails because the test environment cannot be set up correctly. All others pass, including Travis. All tests passed before merging the changelog from `master`. So this should be good to merge.

**Comment by larsoner** [comment]
LGTM, feel free to merge and backport

**Comment by agramfort** [comment]
@larsoner merge if you're ok with this one

**Comment by larsoner** [comment]
Backported, thanks @hoechenberger

**Pull request merged**
