### PR TITLE
Exclude GDF channels

### LINKED ISSUE #8511: Excluding channels fails in GDF files
#### Describe the bug
`exclude()` doesn't seem to exclude the specified channels when reading GDF files (`mne.io.read_raw_gdf`)

#### Steps to reproduce
```python
>>> from mne import io
>>> io.read_raw_gdf("test.gdf", exclude=['Switches']).ch_names
Extracting EDF parameters from /tmp/test.gdf...
GDF file detected
Setting channel info structure...
Creating raw.info structure...
['Switches', 'ModEeg1', 'ModEeg2']
```

#### Expected results
```python
['ModEeg1', 'ModEeg2']
```

#### Additional information
Python 3.8.6 [GCC 10.2.0] on linux x64
mne 0.21.1

Test file used (created with [modeeg2ft_2chn](https://www.fieldtriptoolbox.org/development/realtime/modulareeg/)):
[test.gdf.zip](https://github.com/mne-tools/mne-python/files/5536270/test.gdf.zip)

### PR DESCRIPTION
**Pull request by cbrnr**
Fixes #8511. It seems like we neither implemented nor tested this feature. Let's see if existing tests pass, I'm going to add a specific test next.

### CODE REVIEW

**Comment by agramfort** [comment]
@cbrnr feel free to merge and backport 

thanks a lot

**Comment by cbrnr** [comment]
Is there a short description on how to backport specific PRs? I don't remember how I did it because that's been a long time.

**Comment by larsoner** [comment]
Nowadays I:

1. Squash and merge
2. Locally check out maint/0.21 up to date and tracking upstream branch
3. Cherry pick the squashed commit
4. Git mergetool to deal with the deleted file and any conflicts (usually just means hit "d" to delete latest.inc that doesn't exist on maint)
5. Manually copy-paste the change log line to 0.21.inc
6. Git add 0.21.inc
7. Git cherry pick --continue
8. Accept the log message
8. Git push

Sorry for the bad formatting, on mobile. But maybe this is enough hints. If not I can flesh out out later

**Comment by cbrnr** [comment]
Thanks @larsoner, this worked perfectly! Should we add these instructions to our dev docs?

One more question, I've pushed the changes directly to `upstream/maint/0.21` - was this correct or should I have used the branch on my fork? In any case, now I still see the "Create PR" message on the upstream MNE repository, how can I get rid of that?

**Comment by larsoner** [comment]
Yes push to upstream is correct.

No way to get rid of that prompt that I know of, but lately it has gone away on its own, I think even the same day sometimes

**Comment by larsoner** [comment]
Feel free to add this information to the wiki, it's probably better there than the dev docs. Only maintainers really need to care about this, similar to our release instructions (which also live in the wiki)

**Comment by drammock** [comment]
There's been talk of an advanced dev docs page getting added but I think I agree with @larsoner that backporting is rare enough that the wiki is the best place for it.

**Comment by cbrnr** [comment]
Thanks, I've added a page to the wiki: https://github.com/mne-tools/mne-python/wiki/How-to-backport-a-change

**Pull request merged**
