### PR TITLE
MRG, FIX: get_coef on multiclass

### PR DESCRIPTION
**Pull request by larsoner**

### CODE REVIEW

**Comment by larsoner** [comment]
FYI @agramfort currently I have a workaround which is to leave `scale` out of `clf`:
```Python
scale = mne.decoding.Scaler(epochs.info)
clf = make_pipeline(...)
time_gen = mne.decoding.GeneralizingEstimator(...)
X = scale.fit_transform(epochs.get_data())
y = epochs.events[:, 2]
clf.fit(X, y)
patterns = mne.decoding.get_coef(clf, 'patterns_', inverse_transform=True)
patterns = scale.inverse_transform(patterns)
```
And `patterns.shape` ends up being `(4, 306, 33)`, which seems right (4 conditions, 306 meg chs, 33 time points).

**Comment by agramfort** [comment]
I think we have a design issue which is that when you inverse transform a 2d array you don't know if it's 1 array for various models / time points or multiple coefs for one models as in multiclass...

**Comment by larsoner** [comment]
Maybe I'm missing something, but how can it be a problem in the inverse direction but not in the forward direction?

**Comment by larsoner** [comment]
@agramfort I think I finally fixed this one. I put a test in that is basically my use case, then `pytest.parametrize`'ed it, and it still passed. It would be good if you had time to take a good long look and test it out, though. So let's wait until you have time for a challenge :)

**Pull request merged**
