### PR TITLE
MRG: Fix setup.cfg

### LINKED ISSUE #4572: Is Mayavi required for mne-python?
I just updated to the latest version of mne python, but the `make test` failed :

```
$ make test
python setup.py build_ext -i
running build_ext
rm -f .coverage
py.test -m 'not ultraslowtest' mne
============================================================================== test session starts ===============================================================================
platform linux2 -- Python 2.7.12, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir: /home/smgutstein/Downloads/temp9/mne-python, inifile: setup.cfg
plugins: xdist-1.20.0, forked-0.2, cov-2.5.1, attrib-0.1.3
collected 706 items / 5 errors                                                                                                                                                    

===================================================================================== ERRORS =====================================================================================
_____________________________________________________________________ ERROR collecting mne/gui/_coreg_gui.py _____________________________________________________________________
mne/gui/_coreg_gui.py:47: in <module>
    from mayavi.core.ui.mayavi_scene import MayaviScene
E   ImportError: No module named mayavi.core.ui.mayavi_scene
___________________________________________________________________ ERROR collecting mne/gui/_fiducials_gui.py ___________________________________________________________________
mne/gui/_fiducials_gui.py:10: in <module>
    from mayavi.core.ui.mayavi_scene import MayaviScene
E   ImportError: No module named mayavi.core.ui.mayavi_scene
___________________________________________________________________ ERROR collecting mne/gui/_kit2fiff_gui.py ____________________________________________________________________
mne/gui/_kit2fiff_gui.py:20: in <module>
    from mayavi.core.ui.mayavi_scene import MayaviScene
E   ImportError: No module named mayavi.core.ui.mayavi_scen
```e
____________________________________________________________________ ERROR collecting mne/gui/_marker_gui.py _____________________________________________________________________
mne/gui/_marker_gui.py:12: in <module>
    from mayavi.core.ui.mayavi_scene import MayaviScene
E   ImportError: No module named mayavi.core.ui.mayavi_scene
______________________________________________________________________ ERROR collecting mne/gui/_viewer.py _______________________________________________________________________
mne/gui/_viewer.py:9: in <module>
    from mayavi.mlab import pipeline, text3d
E   ImportError: No module named mayavi.mlab
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 5 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=============================================================================== 2 tests deselected ===============================================================================
===================================================================== 2 deselected, 5 error in 3.98 seconds ======================================================================
Makefile:41: recipe for target 'test' failed
make: *** [test] Error 2
```

I don't have Mayavi installed and never had this problem before. Is Mayavi now necessary for mne-python? The last time I tried installing Mayavi, I ran into all sorts of problems wit my qt libraries and finally just decided to do without., so am hoping I don't need to refight that battle.

For the sake of completeness, here is my mne.sys_info():

```
>>> mne.sys_info()
Platform:      Linux-4.4.0-93-generic-x86_64-with-Ubuntu-16.04-xenial
Python:        2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]
Executable:    /usr/bin/python
CPU:           x86_64: 12 cores
Memory:        62.8 GB

mne:           0.15.dev0
numpy:         1.12.0 {lapack=openblas, blas=openblas}
scipy:         0.17.1
matplotlib:    2.0.0b3+1814.g3cb79ed

sklearn:       0.18
nibabel:       2.1.0
mayavi:        Not found
pycuda:        2016.1.2
skcuda:        0.5.2
pandas:        0.18.1
```
>>>

### PR DESCRIPTION
**Pull request by larsoner**
Closes #4572.

@smgutstein can you verify that `py.test mne/gui` works for you now?

### CODE REVIEW

**Comment by agramfort** [comment]
@smgutstein I'll merge if you confirm it solves your problem.

**Comment by smgutstein** [comment]
OK - I'll check tonight after work...

**Comment by smgutstein** [comment]
No, I still have the same problem. I just git pulled and ....

$ git log
commit d75f0821c39fff49e418ebb4df189f2a88a204c2
Author: Alexandre Gramfort <alexandre.gramfort@m4x.org>
Date:   Sun Sep 17 21:23:42 2017 +0200

    DOC : document channel types  in plot_info (#4571)

    * DOC : document channel types  in plot_info

    * fix formatting

but,

==============================================================================================
ERRORS
===============================================================================================
______________________________________________________________________________
ERROR collecting mne/gui/_coreg_gui.py
_______________________________________________________________________________
mne/gui/_coreg_gui.py:47: in <module>
    from mayavi.core.ui.mayavi_scene import MayaviScene
E   ImportError: No module named mayavi.core.ui.mayavi_scene
____________________________________________________________________________
ERROR collecting mne/gui/_fiducials_gui.py
_____________________________________________________________________________
mne/gui/_fiducials_gui.py:10: in <module>
    from mayavi.core.ui.mayavi_scene import MayaviScene
E   ImportError: No module named mayavi.core.ui.mayavi_scene
_____________________________________________________________________________
ERROR collecting mne/gui/_kit2fiff_gui.py
_____________________________________________________________________________
mne/gui/_kit2fiff_gui.py:20: in <module>
    from mayavi.core.ui.mayavi_scene import MayaviScene
E   ImportError: No module named mayavi.core.ui.mayavi_scene
______________________________________________________________________________
ERROR collecting mne/gui/_marker_gui.py
______________________________________________________________________________
mne/gui/_marker_gui.py:12: in <module>
    from mayavi.core.ui.mayavi_scene import MayaviScene
E   ImportError: No module named mayavi.core.ui.mayavi_scene
________________________________________________________________________________
ERROR collecting mne/gui/_viewer.py
________________________________________________________________________________
mne/gui/_viewer.py:9: in <module>
    from mayavi.mlab import pipeline, text3d
E   ImportError: No module named mayavi.mlab
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Interrupted: 5 errors during collection
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================================================
2 tests deselected
=========================================================================================
===============================================================================
2 deselected, 5 error in 3.27 seconds
==============================================================================

**Comment by larsoner** [comment]
You need to checkout my branch (should see commit 20d9f72342464eb5e5a3f0c61469bb2fb2d33d58 from this PR), not latest `master`

**Comment by agramfort** [comment]
thx @larsoner

**Pull request merged**
