### PR TITLE
FIX block loop

### PR DESCRIPTION
**Pull request by teonlamont**
A patch to bdf reader. this bug came about after fixing another bug. This should resolve the current issue mentioned on the listserv. The edf standard format is super (too) flexible, for better or for worse ;)

### CODE REVIEW

**Comment by agramfort** [comment]
I wonder how we could test these things to avoid breaking anything in the future.

@teonlamont do you keep on this debug files? we should keep them somewhere.

**Comment by teonlamont** [comment]
I have a collection of them all. I will try to see if I can make a shorter recording of them all to add to the test suite. I wasn't successful in compiling edfbrowser when I tried last week. 

Envoyé de mon iPhone

**Comment by agramfort** [comment]
at least keep the files somewhere and maybe make them available. Google
drive?

**Comment by teonlamont** [comment]
here's a link to all the various edf and bdf I've had to use:
https://drive.google.com/folderview?id=0BwtsPU6EWdKIQ1NKLWRJVXJRQlU&usp=sharing

Is there somewhere I should put this link for future ref?

**Pull request merged**
