### PR TITLE
FIX: brain add_label views parameter with pyvista

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR fixes the `views` parameter passed to the camera.

Closes part of #7143

### CODE REVIEW

**Comment by agramfort** [comment]
Ci failure is related ?

**Comment by GuillaumeFavelier** [comment]
I don't think so.... I restarted some CIs to have a better idea

**Comment by GuillaumeFavelier** [comment]
Now the 'medial' parameter is used correctly:

https://17225-1301584-gh.circle-artifacts.com/0/dev/auto_examples/inverse/plot_time_frequency_mixed_norm_inverse.html#sphx-glr-auto-examples-inverse-plot-time-frequency-mixed-norm-inverse-py

reference:

https://mne.tools/dev/auto_examples/inverse/plot_time_frequency_mixed_norm_inverse.html

**Comment by agramfort** [comment]
One down

**Pull request merged**
