### PR TITLE
 FIX : Allow manual rescaling for plot_topomap

### PR DESCRIPTION
**Pull request by alexandrebarachant**
This is a fix for  #2113.

The old behavior is set by default (automated rescaling), and we now allow parameters for a user-defined rescaling.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
I'm already working on it as part of my PR...

**Comment by Eric89GXL** [comment]
See changes here:

https://github.com/mne-tools/mne-python/pull/2114/files

**Comment by alexandrebarachant** [comment]
@Eric89GXL you are too fast, i can not compete :)

I added a few tests if you want to check

**Comment by Eric89GXL** [comment]
@alexandrebarachant feel free to open a PR into my branch to add your tests

**Pull request closed without merging**
