### PR TITLE
MRG, BUG: Force keywords for verbose in short sigs

### LINKED ISSUE #8258: Restrict allowed "verbose" values, or make the verbose kwarg a keyword-only argument?
Call me stupid but I just spent 5 minutes trying to "debug" why this wasn't doing as I expected:

```python
epochs.apply_baseline(None, 0)
```

Obviously, the baseline period should be specified as a tuple… What happened here is that instead of throwing an error message, I ended up with Epochs without baseline correction. Signature of `apply_baseline` is:
```python
    @verbose
    def apply_baseline(self, baseline=(None, 0), verbose=None):
```
So `verbose` was simply set to `0`.

While you could always argue that of course you should check your results and that you cannot make a software fool-proof, I was still wondering if we couldn't easily prevent some of those "user bugs" from happening. In this particular case, either being more restrictive on the allowed values of `verbose`, or declaring `verbose` to be a keyword-only argument would have successfully mitigated my inaptness :)

```python
    def apply_baseline(self, baseline=(None, 0), *, verbose=None):
```

Thoughts?

### PR DESCRIPTION
**Pull request by larsoner**
Closes #8258 
Closes #8263

### CODE REVIEW

**Comment by hoechenberger** [comment]
Great!!

**Review by hoechenberger — APPROVED** [review]

**Comment by hoechenberger** [comment]
Rendered API doc is now even messier than before, though:

Screenshot 2020-10-07 at 19 33 06

https://22643-1301584-gh.circle-artifacts.com/0/dev/generated/mne.Epochs.html

**Comment by larsoner** [comment]
Argh, that's the Sphinx tuple rendering bug...

**Comment by larsoner** [comment]
backported

**Comment by hoechenberger** [comment]
> Argh, that's the Sphinx tuple rendering bug...

Yep, and now with the `*` for kw-only args it looks even more hideous :D

**Comment by larsoner** [comment]
Looks like the sphinx bug was fixed 4 days ago so hopefully it lands in some pre-release soon

**Comment by larsoner** [comment]
https://github.com/sphinx-doc/sphinx/pull/8265

**Comment by hoechenberger** [comment]
Super good!!!

**Pull request merged**
