### PR TITLE
MRG, VIZ: equal aspect ratio for inset sensor maps

### PR DESCRIPTION
**Pull request by drammock**
this is an element of #7751

### CODE REVIEW

**Comment by drammock** [comment]
renderings:

**before/after**
Screenshot_2020-11-19_18-06-52 Screenshot_2020-11-19_18-07-26

**before**
before


**after**
after

**Comment by larsoner** [comment]
Does it maintain the aspect during resize? That would be magical...

**Comment by drammock** [comment]
> Does it maintain the aspect during resize? That would be magical...

Yes! 🧙‍♂️

**Review by agramfort — APPROVED** [review]

**Comment by larsoner** [comment]
Thanks @drammock -- I think this one is worth a `latest.inc` update in the `BUG` section -- feel free to add and merge!

**Pull request merged**
