### PR TITLE
Xdawn issue

### LINKED ISSUE #9005: clean up XDAWN example
in `examples/preprocessing/plot_xdawn_denoising.py` the references are printed at the top; move them to the bottom like they are in most other examples/tutorials.

While you're in there, read through the example and make sure you understand it; improve the wording/explanation of any parts that are awkward or unclear. How-to examples should be fairly short, but if adding a little something (a few extra sentences, one more plot, etc) would make it more informative or clear, add it.

### PR DESCRIPTION
**Pull request by catalinamagalvan**
#### Reference issue
Fixes #9005.

#### What does this implement/fix?
Change references position from the top to the bottom of the example.

### CODE REVIEW

**Comment by agramfort** [comment]
you should use:

.. footbibliography::

as done in:

https://github.com/mne-tools/mne-python/blob/main/tutorials/preprocessing/plot_35_artifact_correction_regression.py#L168

**Review by drammock — APPROVED** [review]

**Comment by drammock** [comment]
rendering looks good: https://25953-1301584-gh.circle-artifacts.com/0/dev/auto_examples/preprocessing/plot_xdawn_denoising.html?highlight=plot_xdawn_denoising

**Comment by larsoner** [comment]
Thanks @catalinamagalvan !

**Comment by catalinamagalvan** [comment]
Thanks to all!

**Pull request merged**
