### PR TITLE
MAINT: Fix search

### LINKED ISSUE #8705: Doc search on website is broken
The search doesn't work for me anymore in the dev documentation. Stable is still functional.

https://mne.tools/dev/search.html?q=compute_rank

doesn't produce any results and the JS console throws an exception, `ReferenceError: Can't find variable: Stemmer`

I'm using Safari 14.0.2

cc @drammock

### PR DESCRIPTION
**Pull request by larsoner**
Ideally we'd wait for the upstream PR to be merged and for a release to be made. But in the meantime we can fix the search by merging this, and update our `requirements_doc.txt` as those other steps occur.

That is assuming this actually fixes search. Current other PR builds like [this one](https://24504-1301584-gh.circle-artifacts.com/0/dev/index.html) show the issue so if this PR fixes it we should be good.

Closes #8705

### CODE REVIEW

**Review by agramfort — APPROVED** [review]

**Comment by larsoner** [comment]
Seems to work

https://24506-1301584-gh.circle-artifacts.com/0/dev/search.html?q=norm

**Comment by larsoner** [comment]
@drammock okay with you?

**Review by drammock — APPROVED** [review]
Yes, glad to have it working again so there's less time pressure for the theme changeover.

**Comment by drammock** [comment]
Thanks a million @larsoner !

**Comment by larsoner** [comment]
backported

**Pull request merged**
