### PR TITLE
[BUG] Allow `Epochs.compute_tfr()` for the multitaper method and complex/phase outputs

### LINKED ISSUE #12831: `Epochs.compute_tfr()` fails for complex and phase outputs in the multitaper method
### Description of the problem

When calling `Epochs.compute_tfr()` with `method="multitaper"` and `output="complex"/"phase"`, there is an `AssertionError` that the actual shape of the results does not match the expected shape (`self._shape`):
image

The expected shape is incorrect due to the tapers dimension of the multitaper complex/phase outputs not being properly indexed in the epoched data.

There are no errors when TFR is computed from epoched data without a tapers dimension (e.g., multitaper mode with power output; Morlet mode with any output), or from raw data with a tapers dimension (multitaper mode with complex or phase outputs).

`self._shape` is generated here:
https://github.com/mne-tools/mne-python/blob/013d6c9f630342e5af7633641162c7b85417782a/mne/time_frequency/tfr.py#L1527-L1537

TFR results with tapers have shape `([epochs, ]channels, tapers, freqs, times)`. When tapers are present, they are added to `expected_shape` in L1536 with `self._data.shape[1]`, however this only corresponds to the tapers dimension in non-epoched data. If the data is epoched, it corresponds to the number of channels, so `self._shape` becomes `(epochs, channels, channels, freqs, times)`. This causes the mismatch between the actual and expected shapes of the results.

This could be fixed with something like:
```
# deal with the "taper" dimension
if self._needs_taper_dim:
    tapers_dim = 1 if _get_instance_type_string(self) != "Epochs" else 2
    expected_shape.insert(1, self._data.shape[tapers_dim])
```

Inserting the number of tapers into `expected_shape` in position 1 is fine for both epoched and non-epoched data, since the number of epochs gets added later:
https://github.com/mne-tools/mne-python/blob/013d6c9f630342e5af7633641162c7b85417782a/mne/time_frequency/tfr.py#L3155

Happy to open a PR for this.

### Steps to reproduce

```Python
import traceback

import numpy as np
from mne import EpochsArray, create_info

# Generate data
rng = np.random.default_rng(44)
n_epochs, n_chans, n_times = (5, 2, 100)
sfreq = 50
data = rng.random((n_epochs, n_chans, n_times))
info = create_info(ch_names=n_chans, sfreq=sfreq, ch_types="eeg")
epochs = EpochsArray(data=data, info=info)
freqs = np.arange(10, sfreq // 2)

# Compute TFR
for output in ["power", "complex", "phase"]:
    try:
        tfr = epochs.compute_tfr(method="multitaper", freqs=freqs, output=output)
        print(f"\nOutput {output} passed.")
    except AssertionError:
        print(f"\nOutput {output} failed:")
        traceback.print_exc()
```

### Link to data

_No response_

### Expected results

No `AssertionError` should be raised for any of the outputs.

### Actual results

An `AssertionError` is raised for `"complex"` and `"phase"` outputs, but not `"power"`:

image

### Additional information

Platform             Windows-11-10.0.22631-SP0
Python               3.12.5 | packaged by conda-forge | (main, Aug  8 2024, 18:24:51) [MSC v.1940 64 bit (AMD64)]
Executable           c:\Users\tsbin\anaconda3\envs\mne\python.exe
CPU                  Intel64 Family 6 Model 154 Stepping 3, GenuineIntel (16 cores)
Memory               31.7 GB

Core
├☑ mne               1.9.0.dev20+g013d6c9f6 (devel, latest release is 1.8.0)
├☑ numpy             1.26.4 (OpenBLAS 0.3.23.dev with 16 threads)
├☑ scipy             1.14.1
└☑ matplotlib        3.9.2 (backend=qtagg)

### PR DESCRIPTION
**Pull request by tsbinns**
#### Reference issue
Fixes #12831.

#### What does this implement/fix?
Fixes a bug where an internal check of the shape of TFR results was unexpectedly failing for results with both an epochs and tapers (multitaper method and complex/phase output) dimension.

#### Additional information
The check for whether an epochs dimension is present cannot rely on `self._dims`, as `"epoch"` only gets added afterwards, so it is instead based on the data passed in (i.e., is it an epochs object?). We don't have to worry about whether an epochs dimension is still present (e.g., if `compute_tfr()` was called with `average=True`), since `average=True` is not allowed when `output="complex"/"phase"`.

There is currently no test checking the combination of multitaper method and complex/phase output, and I haven't added one here to avoid overburdening the test suite. If this is required I can add one.

### CODE REVIEW

**Comment by larsoner** [comment]
> There is currently no test checking the combination of multitaper method and complex/phase output, and I haven't added one here to avoid overburdening the test suite. If this is required I can add one.

Yes please do add it -- if the number of time points and channels is low it should be plenty fast, and it would be good to catch corner cases like this one!

**Comment by tsbinns** [comment]
Just added a very short test that multitaper complex/phase TFR runs.

**Review by larsoner — APPROVED** [review]

**Comment by larsoner** [comment]
Marking for merge-when-green, thanks in advance @tsbinns !

**Comment by tsbinns** [comment]
Seems some sklearn compliance checks are still failing.

**Pull request merged**
