### PR TITLE
Add _check_option return value

### LINKED ISSUE #8204: Should mne.utils._check_option return the checked value?
Currently, `mne.utils._check_option` returns `True` if a value matches a list of allowed values or else raises a `ValueError`. I'm often using it as follows:

```python
_check_option('component_order', component_order, ['alternate', 'mutual_info'])
self.component_order = component_order
```

It would be useful if `_check_option` returned the value instead of `True`, because this would shorten my example to:

```python
self.component_order = _check_option('component_order', component_order, ['alternate', 'mutual_info'])
```

I don't really see a problem with returning the value, but maybe others rely on the boolean return value (although a quick search didn't turn up any assignment to the return value of this function).

### PR DESCRIPTION
**Pull request by cbrnr**
Fixes #8204. Instead of just returning `True` if the argument is valid, the function now returns the valid argument for further use. This can simplify some code constructs.

### CODE REVIEW

**Review by agramfort — APPROVED** [review]

**Comment by hoechenberger** [comment]
@cbrnr Travis is not happy

**Review by hoechenberger — APPROVED** [review]
LGTM once CI goes green

**Comment by cbrnr** [comment]
@hoechenberger all green!

**Comment by hoechenberger** [comment]
Thanks, @cbrnr!

**Pull request merged**
