### PR TITLE
[MRG] ADD neighbors for KIT

### PR DESCRIPTION
**Pull request by teonlamont**
These neighborhood matrices were generated in fieldtrip with some slight modifications:
the channels had to be renamed from `AG001` --> `MEG 001`. script used to generate them is below:

```matlab
cfg = [];
cfg.dataset = '/Users/teon/Experiments/E-MEG/data/A0129/kit/A0129_OLDT1_calm.con';
data = ft_read_header(cfg.dataset);
for i= 1:length(data.grad.label)
    data.grad.label{i} = ['MEG ', data.grad.label{i}(3:end)];
    data.label{i} = data.grad.label{i};
end

cfg.method = 'triangulation';
neighbours = ft_prepare_neighbours(cfg, data);
save(['/Applications/packages/mne-python/mne/channels/data/neighbors/'...
      'KIT-AD_neighb.mat'], 'neighbours');


cfg = [];
cfg.dataset = '/Volumes/GLYPH-1 TB/Experiments/NMG/data/R0095/raw/R0095_NMG_calm.sqd';
data = ft_read_header(cfg.dataset);
for i= 1:length(data.grad.label)
    data.grad.label{i} = ['MEG ', data.grad.label{i}(3:end)];
    data.label{i} = data.grad.label{i};
end

cfg.method = 'triangulation';
neighbours = ft_prepare_neighbours(cfg, data);
save(['/Applications/packages/mne-python/mne/channels/data/neighbors/'...
      'KIT-NY_neighb.mat'], 'neighbours');
```

I haven't had a chance to use it yet because I ran into an unrelated roadblock with the spatiotemporal sensor space test. will make an issue for it.

### CODE REVIEW

**Comment by teonlamont** [comment]
related to #2082.

**Comment by agramfort** [comment]
let's see when you confirm it works. Btw I don't like the name of the
files. There are other KIT systems than NYU and AD :)

**Comment by agramfort** [comment]
what's up here?

**Comment by teonlamont** [comment]
was waiting to resolve https://github.com/mne-tools/mne-python/issues/2270 because I was planning to use the neighborhood information on the spatiotemporal cluster test using the t-values from the regression.

**Comment by agramfort** [comment]
you don't need this to check that it works. Imagine something simpler.

**Comment by teonlamont** [comment]
oh, ok. i just noticed we don't have a test for the other neighborhood mat files. any reason for that? also, should it be a general test that includes those files too?

**Comment by agramfort** [comment]
What should we test?

**Comment by teonlamont** [comment]
ooh, oops, i thought the hold up was that it needed a test. it was just the name. fixed. my b :)

**Comment by teonlamont** [comment]
i will confirm them now, probably with the plotter

**Comment by agramfort** [comment]
Ok

**Comment by teonlamont** [comment]
below, I plotted the sensor array (gray) for the 208 channel system, and then randomly selected a seed channel (red) and plotted its corresponding neighbors (white). 

neigh1
neigh2
neigh3
neigh4
neigh5

**Comment by teonlamont** [comment]
and for the 157 channel system, I followed the same procedure above.

snapshot1
snapshot2
snapshot3
snapshot4
snapshot5

**Comment by agramfort** [comment]
thanks

**Pull request merged**
