### PR TITLE
FIX circle CI

### PR DESCRIPTION
**Pull request by jasmainak**
Let's see if this works ...

I think PyQt5's latest release broke our build

### CODE REVIEW

**Comment by larsoner** [comment]
Merging to make CircleCI green again

**Comment by larsoner** [comment]
Thanks @jasmainak

**Comment by cbrnr** [comment]
I think we should look into what caused this issue, otherwise we will be stuck with this version forever. I'm pasting the relevant CircleCI output for reference:

```
$ #!/bin/bash -eo pipefail
  python -c "from mayavi import mlab; import matplotlib.pyplot as plt; mlab.figure(); plt.figure()"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/circleci/miniconda/envs/mne/lib/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/home/circleci/miniconda/envs/mne/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/home/circleci/miniconda/envs/mne/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import (
  File "/home/circleci/miniconda/envs/mne/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 19, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/home/circleci/miniconda/envs/mne/lib/python3.6/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/home/circleci/miniconda/envs/mne/lib/python3.6/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 54, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/home/circleci/miniconda/envs/mne/lib/python3.6/site-packages/matplotlib/backends/qt_compat.py", line 140, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ModuleNotFoundError: No module named 'PyQt5.sip'
Exited with code 1
```

**Comment by jasmainak** [comment]
It appears to be an issue with the latest PyQt5 release ...

**Comment by cbrnr** [comment]
There's a note at http://pyqt.sourceforge.net/Docs/PyQt5/installation.html:

> Note: When building PyQt5 v5.11 or later you must configure SIP using the `--sip-module PyQt5.sip` option to `configure.py` to create a private copy of the sip module.

Does CircleCI build PyQt5 from source?

**Comment by cbrnr** [comment]
I think we need to install [PyQt5-sip](https://pypi.org/project/PyQt5-sip/); see #5322.

**Comment by jasmainak** [comment]
okay thanks for the PR!

**Pull request merged**
