### PR TITLE
Minor MNE description improvement

### LINKED ISSUE #7713: Change description on homepage
Currently, the short description on the [MNE homepage](https://mne.tools/stable/index.html) says:

"Open-source Python software for exploring, visualizing, and analyzing human neurophysiological data: MEG, EEG, sEEG, ECoG, and more."

Maybe I'm too ignorant, but I don't even know what sEEG is (I always thought sEEG and ECoG are synonyms). Furthermore, NIRS support is probably more interesting for more users, so I'd change this sentence to:

"Open-source Python toolbox for exploring, visualizing, and analyzing human neurophysiological data: MEG, EEG, ECoG, NIRS, and more."

I'd also change "software" to "toolbox". WDYT?

### PR DESCRIPTION
**Pull request by cbrnr**
Fixes #7713.

### CODE REVIEW

**Comment by larsoner** [comment]
Thanks @cbrnr

**Comment by agramfort** [comment]
now it fits on 3 lines for me https://mne.tools/dev/

for you too?

**Comment by larsoner** [comment]
No:

Screenshot from 2020-05-04 16-07-59

Only once I resize to be smaller, which I think should be expected:

Screenshot from 2020-05-04 16-08-10

Get a bigger monitor :)

**Comment by agramfort** [comment]
or a bigger macbook pro although it's already the biggest :)

>

**Comment by cbrnr** [comment]
You have a 16" MBP? Did you change the resolution? By default it's just a retina full HD res, which is really pretty low.

**Comment by agramfort** [comment]
>
> You have a 16" MBP? Did you change the resolution? By default it's just a
> retina full HD res, which is really pretty low.
>

yes and my eyes are not so young anymore :)

**Pull request merged**
