### PR TITLE
ENH: Add n_jobs=None support

### LINKED ISSUE #10522: Improve control over number of threads used in an mne call
# Description
I propose to use [threadpoolctl](https://github.com/joblib/threadpoolctl) to improve control over the number of threads used throughout mne and in calls to external libraries like `numpy`. This is apparently the direction that `numpy` has moved to as discussed here: https://github.com/numpy/numpy/issues/11826

# Reasoning
I have had trouble completely controlling the number of threads used by various `mne` functions. Many mne functions have `n_jobs` arguments that control the number of threads used in that function, but there are cases where code within that function can escape this limit due to externally defined reference values. And then there are functions like `mne.chpi.filter_chpi` that do not have the `n_jobs` argument, but can still parallelize. It is possible to control this with environment variables as [dicussed here](https://stackoverflow.com/questions/30791550/limit-number-of-threads-in-numpy), but that only works before you import the respective library, e.g. numpy. The easiest way to control thread limits after an import has happened appears to be `threadpoolctl`.

# Proposed Implementation
I have successfully use the syntax 
```python
from threadpoolctl import threadpool_limits
with threadpool_limits(limits=n_jobs, user_api="blas"):
    mne.do_something()
```
to control threads used in an mne call. The same could be used internally to make better use of the existing `n_jobs` argument without forcing the user to do it themselves. If this proves successful, it might make sense to add the `n_jobs` argument in even more places.

### LINKED ISSUE #10570: mne.fit_dipole throwing AssertionError: (blank) when n_jobs=-1
#### Describe the bug
When setting `n_jobs=-1`  as an argument of `mne.fit_dipole()`, a blank AssertionError is thrown.
Reading up the trace, one can see there is an `assert n_jobs > 0`  within `mne/surface.py`.
Elsewhere in MNE-Py, setting `n_jobs=-1` is valid and selects maximum available workers, and the docs for `fit_dipole` state this.
Setting `n_jobs=16` runs successfully, where 16 is the maximum workers on my system, and the number of workers when using -1 in the steps prior to dipole fitting.

#### Steps to reproduce
Run:
```
dip = mne.fit_dipole(..., n_jobs=-1)
```

#### Expected results

The dipole fit to complete using maximum workers.

#### Actual results
```
(snip)
~\anaconda3\envs\mne\lib\site-packages\mne\surface.py in _points_outside_surface(rr, surf, n_jobs, verbose)
    561     rr = np.atleast_2d(rr)
    562     assert rr.shape[1] == 3
--> 563     assert n_jobs > 0
    564     parallel, p_fun, _ = parallel_func(_get_solids, n_jobs)
    565     tot_angles = parallel(p_fun(surf['rr'][tris], rr)

AssertionError: 
```

#### Additional information
<details>
  <summary>Output from `mne.sys_info()`</summary>
  
  Platform:       Windows-10-10.0.22000-SP0
  Python:         3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:36:06) [MSC v.1929 64 bit (AMD64)]
  Executable:     C:\Users\Matt\anaconda3\envs\mne\python.exe
  CPU:            Intel64 Family 6 Model 167 Stepping 1, GenuineIntel: 16 cores
  Memory:         63.8 GB
  
  mne:            0.24.1
  numpy:          1.22.0 {blas=NO_ATLAS_INFO, lapack=lapack}
  scipy:          1.7.3
  matplotlib:     3.5.1 {backend=module://matplotlib_inline.backend_inline}
  
  sklearn:        1.0.2
  numba:          0.53.1
  nibabel:        3.2.1
  nilearn:        0.8.1
  dipy:           1.4.1
  cupy:           Not found
  pandas:         1.3.5
  mayavi:         4.7.2
  pyvista:        0.33.2 {OpenGL 4.5.0 NVIDIA 496.49 via NVIDIA GeForce GTX 1070/PCIe/SSE2}
  pyvistaqt:      0.6.0
  ipyvtklink:     Not found
  vtk:            9.0.3
  PyQt5:          5.12.3
  ipympl:         Not found
  mne_qt_browser: 0.1.7
  pooch:          v1.5.2
  C:\Users\Matt\anaconda3\envs\mne\lib\site-packages\mne\utils\check.py:728: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    if LooseVersion(version) >= LooseVersion('5.10'):
  C:\Users\Matt\anaconda3\envs\mne\lib\site-packages\mne\utils\check.py:728: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    if LooseVersion(version) >= LooseVersion('5.10'):
</details>

### PR DESCRIPTION
**Pull request by larsoner**
Closes #10522
Closes #10570

- [x] Search-and-replace `n_jobs=1` -> `n_jobs=None`
- [x] `flake8` fixes, including some insertions of `*` before verbose when noticed/easy (not trying to be complete, incremental progress good enough, don't want to make judgment calls about whether to move it farther forward than just before `verbose`)
- [x] Look through diff to make sure all new `n_jobs=None` actually make sense
- [x] Figure out how to handle our `if n_jobs == 1` conditionals that now will fail (maybe with `check_n_jobs`?)
- [x] Actually make `n_jobs=None` do more than just be `n_jobs=1`
- [x] Update docstring to describe `n_jobs=None`
- [x] Add test that `n_jobs=None` can actually use more than one job with the right context

### CODE REVIEW

**Review by agramfort — COMMENTED** [review]
so far so good !

**Comment by larsoner** [comment]
Okay, the `parallel_backend` context manager should now be properly supported with `n_jobs=None`

**Review by hoechenberger — COMMENTED** [review]
I don't understand the purpose of `max_jobs`, even after reading the docstring. Could you please elaborate? How does it differ from `n_jobs`?

**Comment by larsoner** [comment]
> I don't understand the purpose of max_jobs, even after reading the docstring. Could you please elaborate? How does it differ from n_jobs?

Something to keep in mind is who has control over these two parameters, and where `parallel_func` gets used. `parallel_func` is meant to be used by us (devs) in internal code, not users. Users get control over `n_jobs` in our public APIs, and we get to use `max_jobs`. Why is this useful? In `main` we have a lot of this pattern:
```
n_jobs = check_n_jobs(n_jobs)
parallel, p_fun, _ = parallel_func(fun, n_jobs)
n_jobs = min(n_jobs, x.shape[0])
out = parallel(p_fun(x_split) for x_split in np.array_split(x, min(n_jobs, x.shape[0], axis=0)
```
In other words, we don't want to `array_split` any more times than the size of `x` along some dimension.
The purpose of `max_jobs` is to DRY this `min` pattern, here I introduce `max_jobs`, and the above code can be simplified:
```
parallel, p_fun, n_jobs = parallel_func(fun, n_jobs, max_jobs=x.shape[0])
out = parallel(p_fun(x_split) for x_split in np.array_split(x, n_jobs, axis=0)
```

**Review by hoechenberger — APPROVED** [review]

**Review by agramfort — APPROVED** [review]

**Pull request merged**
