### PR TITLE
clarify relationships among FWHM, sigma, and n_cycles in Morlet function docstrings

### LINKED ISSUE #11651: Allow for computation of TFR using Morlet wavelets but with fwhm as an alternative parameter to wave-number
### Describe the new feature or enhancement

It is nice to see `mne.time_frequency.fwhm` but it is a tad useless (except for final reporting), unless we can use `fwhm` values to construct the wavelets. For an instructive case, where this comes handy, see **Fig. 5 a (var)** in Cohen (2019).

### Describe your proposed implementation

As a new capability to `mne.time_frequency.morlet` and like methods.

### Describe possible alternatives

None

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by drammock**
closes #11651

### CODE REVIEW

**Comment by drammock** [comment]
`get_minimal_commands` is failing, seems like OSF is having server issues. Check this URL https://osf.io/g7dzs to see when it's fixed, then restart failed tests.

**Comment by agramfort** [comment]
thx @drammock  could you illustrate this in our doc?

**Comment by drammock** [comment]
actually I'm not so sure about the API I've created here.  I was forgetting that we already allow to pass `sigma` and there is a straightforward relationship between `sigma` and `fwhm` (namely `fwhm = sigma * 2 * np.sqrt(2 * np.log(2))`).  So we really don't need an extra parameter I think.  Just better documentation.  Converting to draft while I work on that.

**Comment by drammock** [comment]
This is now a docs-only change; it's all in the Notes section here:

https://output.circle-artifacts.com/output/job/fe92878e-c539-42fc-9239-34dab04ce704/artifacts/0/dev/generated/mne.time_frequency.morlet.html#mne.time_frequency.morlet

**Review by agramfort — APPROVED** [review]

**Comment by larsoner** [comment]
Thanks @drammock !

**Pull request merged**
