### PR TITLE
fix bibtex plot_15_handling_bad_channels

### LINKED ISSUE #8937: use bibtex in plot_15_handling_bad_channels.py
convert references in `tutorials/preprocessing/plot_15_handling_bad_channels.py` to use footcite / footbibliography

### PR DESCRIPTION
**Pull request by eort**
#### Reference issue
Fixes #8937.

#### What does this implement/fix?
Change the referencing to work with sphinxcontrib-bibtex

### CODE REVIEW

**Comment by eort** [comment]
small sidenote, the tutorial has the headline 
> Interpolating bad channels

however the file is called `plot_15_handling_bad_channels`. Also further down the tutorial, there is another head line `Interpolating bad channels`. Would it make sense to rename the tutorial to 

>Handling bad channels

?

**Comment by sappelhoff** [comment]
> Would it make sense to rename the tutorial to

do you mean by that to change line 5 of the tutorial from `Interpolating bad channels` to `Handling bad channels`?

I'd agree that that's an improvement.

**Comment by larsoner** [comment]
+1 for changing the title of the tutorial

**Comment by eort** [comment]
Rendered doc looks ok: https://25827-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/preprocessing/plot_15_handling_bad_channels.html

**Comment by eort** [comment]
> do you mean by that to change line 5 of the tutorial from `Interpolating bad channels` to `Handling bad channels`?

Yes, That's what I meant.

**Comment by sappelhoff** [comment]
> Rendered doc looks ok

cool, I suggest you change the title of the tutorial then :-)

**Review by drammock — APPROVED** [review]

**Pull request merged**
