### PR TITLE
replaced preload in IO

### PR DESCRIPTION
**Pull request by DiGyt**
As mentioned in PR #6272,
This PR will change the "preload" documentation in all relevant io read_raw_xy and RawXY docstrings to be read from utils/docs.py::docdict instead of being written out each time.

#### Additional information

The following "preload" docstrings were not replaced for various reasons. Please give a short note whether any of them should be replaced additionally:

- (array, fieldtrip): No preload option

- brainvision: String not equal/ not sure if equivalent
    `preload : bool
        If True, all data are loaded at initialization.
        If False, data are not read until save.`

- eximia: String not equal/ not sure if equivalent
    `preload : bool
        If True, all data are loaded at initialization.`

- eeglab::read_raw_eeglab: Additional information after preload string:
        `[...]Note that preload=False will be effective only if the data is stored in a
        separate binary file.`
    However, RawEEGLAB string did not have this addition and therefore was replaced

- kit::read_raw_kit: String not equal/ not sure if equivalent
    `preload : bool
        If True, all data are loaded at initialization.
        If False, data are not read until save.`
     However, RawKIT string was equal to docdict and therefore was replaced

- open::fiff_open: String not equal/ not sure if equivalent
    `preload : bool
        If True, all data from the file is read into a memory buffer. This
        requires more memory, but can be faster for I/O operations that require
        frequent seeks.`

- base::BaseRaw Additional information after preload string:
	` [...]If preload is an ndarray, the data are taken from that array. If False, data are not
        read until save.`

- base::BaseRaw.append: Additional information after preload string:
	`If preload is None, preload=True or False is inferred using the preload status
            of the raw files passed in.`

- base::BaseRaw.concatenate_raws: String not equal/ not sure if equivalent
	`If None, preload status is inferred using the preload status of the
        raw files passed in. True or False sets the resulting raw file to
        have or not have data preloaded.`

### CODE REVIEW

**Comment by larsoner** [comment]
Please do replace brainvision, eximia, and kit, their deviations are not useful/relevant/correct

For eeglab and base still use the string substitution, but append whatever you need to the end like:
```
    ...
    %(preload)s
        Extra stuff here.
    %(verbose)s
    ...
```
And it should render fine. It's just doing string substitution so you can imagine what it will do.

**Comment by DiGyt** [comment]
> Please do replace brainvision, eximia, and kit, their deviations are not useful/relevant/correct
> 
> For eeglab and base still use the string substitution, but append whatever you need to the end like:
> 
> ```
>     ...
>     %(preload)s
>         Extra stuff here.
>     %(verbose)s
>     ...
> ```
> 
> And it should render fine. It's just doing string substitution so you can imagine what it will do.

Thanks, @larsoner !
I replaced everything accordingly, except `BaseRaw.__init__` and `BaseRaw.append`, since i noticed that entering the docdict string there would replace the valid parameter types (`bool, str, or None (default None)` and `bool | str | ndarray` with `bool or str (default False)`...

**Comment by larsoner** [comment]
Yes I omitted those on purpose :)

**Comment by larsoner** [comment]
Thanks @DiGyt !

**Pull request merged**
