### PR TITLE
BUG: Fix bug with unscale=True

### PR DESCRIPTION
**Pull request by larsoner**
Looks like I never added a very good test for `unscale=True`, because the logic was backward :(

### CODE REVIEW

**Review by agramfort — APPROVED** [review]

**Comment by agramfort** [comment]
should we backport this?

**Comment by drammock** [comment]
> should we backport this?

isn't that what the `backport-candidate` label means? 😆

**Comment by agramfort** [comment]
😅

**Comment by larsoner** [comment]
backported

**Pull request merged**
