### PR TITLE
DOC: Fix/add links to BIDS

### PR DESCRIPTION
**Pull request by sappelhoff**
- fix outdated link to BIDS specification
- correct rst link syntax
- add new link to BIDS in the docs, when it is first mentioned

### CODE REVIEW

**Comment by jasmainak** [comment]
can you share the rendered doc on CircleCI?

**Comment by sappelhoff** [comment]
for the BIDS link: https://13379-1301584-gh.circle-artifacts.com/0/dev/install/pre_install.html

I guess my changes in `_get_valid_units` are not rendered in the API because it's a private function

**Comment by jasmainak** [comment]
okay makes sense. LGTM in that case!

**Comment by agramfort** [comment]
error is unrelated. thanks @sappelhoff

**Pull request merged**
