### PR TITLE
DOC: Document name properly [skip azp] [skip actions]

### LINKED ISSUE #10446: Update docs to reflect new MNE Installer menu entries
https://github.com/conda-forge/mne-feedstock/pull/86 changes the names of the menu entries. We need to update the docs accordingly. I think the only thing we mention explicitly is the `MNE Prompt`, which would be renamed to `Prompt (MNE)`, so we should probably refer to it just as `Prompt`.

cc @larsoner

### PR DESCRIPTION
**Pull request by larsoner**
Closes #10446

Once this is merged, I plan to start the 1.0 release process

### CODE REVIEW

**Comment by larsoner** [comment]
@hoechenberger feel free to review and approve if you're happy

Also, I really like that on conda-forge I can just add a `automerge` label to PRs when reviewing and have them go in when green. I'd like to do the same thing at some point, probably using [bulldozer](https://github.com/palantir/bulldozer). There are a few times per month (sometimes per week?) where I approve a PR and want to merge, but have to wait for CIs, so I leave the tab open and wait for the yellow dot to turn green (or close the tab and come back later). This would allow me to just add the `automerge` label and move on.

**Review by agramfort — APPROVED** [review]

**Review by hoechenberger — APPROVED** [review]
Perfect

**Comment by hoechenberger** [comment]
Thanks @larsoner!

**Comment by hoechenberger** [comment]
> Also, I really like that on conda-forge I can just add a `automerge` label to PRs when reviewing and have them go in when green. I'd like to do the same thing at some point, probably using [bulldozer](https://github.com/palantir/bulldozer).

Maybe we can also see what conda-forge uses and use the same thing here? Not sure how much magic is involved there though!

Otherwise: yes, +10 on having automerge!

Another thing I configured for `mne-tools/mne-installers` is auto-deletion of PR branches on merge. Always saves me a few clicks. Would it make sense to activate this here too?

**Comment by hoechenberger** [comment]
> I always delete my branches, but @agramfort never does as far as I have seen.

Maybe he needs help from an auto-delete action! 😁😅👍

**Pull request merged**
