### PR TITLE
MRG: Add plotting of dense head

### LINKED ISSUE #4694: support dense head surfaces in `plot_alignment`
There does not appear to be a way to specify whether to use the sparse or dense head in `mne.viz.plot_alignment`.  According to @larsoner this used to be possible with the now-deprecated `plot_trans` function.  Requesting an enhancement to allow this via `plot_alignment`.

The loading of the head surface is handled [here](https://github.com/mne-tools/mne-python/blob/master/mne/viz/_3d.py#L653-L659) so presumably that's where code to allow user-specified surface density would get plugged in.

### PR DESCRIPTION
**Pull request by larsoner**
Closes #4694.

@drammock can you see if this works for you?

### CODE REVIEW

**Comment by drammock** [comment]
nailed it.  Thanks!

**Comment by larsoner** [comment]
Updated example:

https://6278-1301584-gh.circle-artifacts.com/0/tmp/circle-artifacts.5yklUZS/html/auto_tutorials/plot_forward.html#visualization-the-coregistration

**Comment by agramfort** [comment]
LGTM

shall we backport?

**Comment by larsoner** [comment]
I don't think this one is critical enough for a backport

**Comment by agramfort** [comment]
ok fine with me

**Comment by drammock** [comment]
Agree that backport is not needed.  I can work off master (after merge); this is for a one-off figure, not part of an analysis pipeline.

**Pull request merged**
