### PR TITLE
[wip] [I will rewrite hist] work-on montage

### PR DESCRIPTION
**Pull request by massich**
My attempt to get my head around the montage problems. 
I will re-edit the PR, rewrite history and whatever..

### CODE REVIEW

**Comment by larsoner** [comment]
This pull request **introduces 4 alerts** when merging a681cd2f26bedd02a568d13c6e260720bfa7a7a0 into 12a85495333e07a80d676dcb0e19a562bd7d380f - [view on LGTM.com](https://lgtm.com/projects/g/mne-tools/mne-python/rev/pr-18001b15553362503d89185cb480a422c911b466)

**new alerts:**

* 3 for Variable defined multiple times
* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by massich** [comment]
I think EGI_256 is broken see https://11334-1301584-gh.circle-artifacts.com/0/dev/auto_examples/visualization/plot_montage.html (the `.csd` description was added in #1390)

**Comment by larsoner** [comment]
This pull request **introduces 2 alerts** when merging 80f926a439ddfb6c5bd712a2ff28884995feaebc into 44c2ba414f2ab11d83bd5a477c599b9370f28449 - [view on LGTM.com](https://lgtm.com/projects/g/mne-tools/mne-python/rev/pr-d660f61e7072206116d911527df500fcaa83b8ae)

**new alerts:**

* 2 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by larsoner** [comment]
This pull request **introduces 2 alerts** when merging d74beb5703ee7fb2a9ea329073560c767cdbf410 into 8b00fc96ec8574c364007ea6b9655eb288d464bb - [view on LGTM.com](https://lgtm.com/projects/g/mne-tools/mne-python/rev/pr-6fd98862cd299766b26ca3270fd2c827a7389b88)

**new alerts:**

* 2 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by massich** [comment]
I'm a bit lost with the `montage` problems. [here](https://11341-1301584-gh.circle-artifacts.com/0/dev/auto_examples/visualization/plot_montage.html) is a rendering of my first approach: load all the Montages and see what happen. 

The second approach (which is the current PR state) I created a dummy class contaning a valid `info['dig']` and plot the alignment. Just to play with the user API.
image

@agramfort , @larsoner 	wdyt? what am I missing?

In my opinion, the problem resides in the fact that `info['dig']` is linked to `trans`. If you think that this makes sense from the user point of view, we recode all montages and distribute the trans. And if someone needs something new, they would need to provide the registration.

**Comment by larsoner** [comment]
@massich the API proposal is in 

https://github.com/mne-tools/mne-python/issues/3893#issuecomment-271925975

Which step are you on?

**Comment by larsoner** [comment]
This pull request **introduces 5 alerts** when merging 1bf9e88b1ce4db1df87c2ff3ece1a117f2c6480f into 8b00fc96ec8574c364007ea6b9655eb288d464bb - [view on LGTM.com](https://lgtm.com/projects/g/mne-tools/mne-python/rev/pr-6c1a470c0c604fc73e644225a55d7a9972045f03)

**new alerts:**

* 3 for Unused import
* 1 for Variable defined multiple times
* 1 for Unused exception object

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by massich** [comment]
I've created a dummy version of `Digitization` that contains a valid `info['dig']` list. (Where each element has `kind`, `ident`, `r`, and `coord_frame`. More over all `coord_frame` are 4, which represent the head coordinate) However in order to create the plot I need a trans that maps `head->mri`. Or we should have an fsaverage such that he trans `head->mri` is the identity.

But here is where I get lost, why do we need an object whose internal representation matches *1-to-1* with `info['dig']`? what should `dev_head_t` be? which part of the `info['dig']` do we need to populate in                
 `info['chs'][idx]['loc'][:6]` and why do we need to keep duplicated data + visualization flags to toggle between one and the other?

**Comment by larsoner** [comment]
This pull request **introduces 5 alerts** when merging 8570e86325854f4353b26631f0ebe806c3d14567 into 4d932c2d2fea79e073715e42c08e94b06ea3cf9e - [view on LGTM.com](https://lgtm.com/projects/g/mne-tools/mne-python/rev/pr-ed2c5b9073aeb538ee0ceac7f5107710045d8bae)

**new alerts:**

* 3 for Unused import
* 1 for Variable defined multiple times
* 1 for Unused exception object

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by agramfort** [comment]
@larsoner do we always need dev_head_t ? is this just for MEG? Would we
need it for EEG w or w/o a standard montage?

thoughts anyone?

**Comment by larsoner** [comment]
Only need `dev_head_t` for MEG data.

> why do we need an object whose internal representation matches 1-to-1 with info['dig']

Because we want all of the data from `info['dig']` with some other convenience things. For example `dig.plot()` should just work, even if its internal representation of its data is this list of dict. Also, for example, `dev_head_t` computation comes into play for formats that give you points in two different coordinate frames, not just the head coord frame. In this case, matched points in the MEG coord frame and head coord frame can be used to give you the MEG<->Head transformation.

>  However in order to create the plot I need a trans that maps head->mri

We always have a `trans` parameter in our plotting functions to give the head<->MRI transformation, this should be the same. (It should not be part of the class.)

**Comment by agramfort** [comment]
but we agree that trans is not needed if you have dig points in MRI or head
coordinate system and you work with only EEG. ok?

>

**Comment by larsoner** [comment]
Yes agreed, `dev_head_t` is a minor side note and in most cases should not be needed.

**Comment by larsoner** [comment]
This pull request **introduces 7 alerts** when merging 2c273312836e118395d86a40c28e45e72161e393 into 7c21bd6c43c79d325fa47c39925daaa001882790 - [view on LGTM.com](https://lgtm.com/projects/g/mne-tools/mne-python/rev/pr-449809cc9ffece0b2916635085ce571e55505faa)

**new alerts:**

* 6 for Unused import
* 1 for Unused exception object

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by larsoner** [comment]
This pull request **introduces 22 alerts** when merging 0eb92d95d1c898f4dd965763c2f1df53f8e8450e into 7c21bd6c43c79d325fa47c39925daaa001882790 - [view on LGTM.com](https://lgtm.com/projects/g/mne-tools/mne-python/rev/pr-8b8ffe4865f534c2b41c43a36de715b263857b19)

**new alerts:**

* 19 for Unused import
* 2 for Unused local variable
* 1 for Unused exception object

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by larsoner** [comment]
This pull request **introduces 15 alerts** when merging 663121094e7d49959d92a291d9a3e6bfd1d798ef into 8dc463497f160e0c7fde772c7effec76beaa7f32 - [view on LGTM.com](https://lgtm.com/projects/g/mne-tools/mne-python/rev/pr-5b48f8a5c29bcbccfcd1c537d8eacfc944ee85c9)

**new alerts:**

* 9 for Unused import
* 3 for Variable defined multiple times
* 2 for Unused local variable
* 1 for Unused exception object

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by larsoner** [comment]
This pull request **introduces 15 alerts** when merging 8e7b83988c2612f0e2d446e18423e7454c3e6db5 into 4555011717b9008f41eaa4926d598bb570e42fca - [view on LGTM.com](https://lgtm.com/projects/g/mne-tools/mne-python/rev/pr-eca7d5f16a21aa022e91843018415e414ee1ae34)

**new alerts:**

* 9 for Unused import
* 3 for Variable defined multiple times
* 2 for Unused local variable
* 1 for Unused exception object

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by larsoner** [comment]
This pull request **introduces 9 alerts** when merging e27ab272ba5982ee7f1964c26edf0cbf08f0e3b9 into ece75432a4d51692dfc946fc7e6615be00b6a0dd - [view on LGTM.com](https://lgtm.com/projects/g/mne-tools/mne-python/rev/pr-ef53270d4d8ea2802a639ed44cd29efe11f1fc20)

**new alerts:**

* 3 for Unused import
* 3 for Variable defined multiple times
* 2 for Unused local variable
* 1 for Unused exception object

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request closed without merging**
