### PR TITLE
DOC: added reference to sesameeg package

### PR DESCRIPTION
**Pull request by sarasommariva**
#### What does this implement/fix?
Added reference to package [sesameeg](https://pybees.github.io/sesameeg/) into section [install](https://mne.tools/stable/install/pre_install.html) of the documentation.

### CODE REVIEW

**Comment by larsoner** [comment]
I think we need a new page for this, see #5484. Would you be up for creating a new page? Then we can push commits with other packages and merge a first version of it, and others can add things later...

**Comment by agramfort** [comment]
+1000

**Comment by drammock** [comment]
I added that "related projects" section to the "pre-install" page in #6522. And @sarasommariva is adding sesameeg into that list, which is the correct place in my mind.  @larsoner @agramfort what is the reasoning behind giving it a dedicated page?  To me the pre-install page doesn't seem overly crowded or long...

**Comment by agramfort** [comment]
+1 for MRG

we can deliberate later :)

>

**Comment by larsoner** [comment]
Ahh, forgot about that. Agreed it's not too long and we can live with it there for now at least.

**Comment by drammock** [comment]
thanks @sarasommariva

**Comment by sarasommariva** [comment]
thanks to you all guys! I'll be happy to help with the plug-in page when/if needed.. for now I'm lazy enough to agree with @drammock :)

**Pull request merged**
