### PR TITLE
FIX: reading large CNT files (more than 2Gb files)

### LINKED ISSUE #6535: Error reading big CNT file
MNE Group:
I tried to read several cnt files of different sizes using `mne.io.read_raw_cnt`.
```py
data = mne.io.read_raw_cnt('test.cnt', preload=True, montage=None, stim_channel=True)
```
If the cnt file is lower than 2G, the file can be successfully loaded.
However, if the file size exceeds 2G, I will receive the following error:
```sh
<ipython-input-25-acf0568a07e0>:1: RuntimeWarning: Could not define the number of bytes automatically. Defaulting to 2.
  data = mne.io.read_raw_cnt('test.cnt', preload=True, montage=None, stim_channel=True)
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-25-acf0568a07e0> in <module>
----> 1 data = mne.io.read_raw_cnt('test.cnt', preload=True, montage=None, stim_channel=True)

~/.local/lib/python3.5/site-packages/mne/io/cnt/cnt.py in read_raw_cnt(input_fname, montage, eog, misc, ecg, emg, data_format, date_format, preload, stim_channel, verbose)
    176     return RawCNT(input_fname, montage=montage, eog=eog, misc=misc, ecg=ecg,
    177                   emg=emg, data_format=data_format, date_format=date_format,
--> 178                   preload=preload, stim_channel=stim_channel, verbose=verbose)
    179
    180

~/.local/lib/python3.5/site-packages/mne/io/cnt/cnt.py in __init__(self, input_fname, montage, eog, misc, ecg, emg, data_format, date_format, preload, stim_channel, verbose)
    430         input_fname = path.abspath(input_fname)
    431         info, cnt_info = _get_cnt_info(input_fname, eog, ecg, emg, misc,
--> 432                                        data_format, _date_format, stim_channel)
    433         last_samps = [cnt_info['n_samples'] - 1]
    434         _check_update_montage(info, montage)

~/.local/lib/python3.5/site-packages/mne/io/cnt/cnt.py in _get_cnt_info(input_fname, eog, ecg, emg, misc, data_format, date_format, stim_channel_toggle)
    293         if stim_channel_toggle:
    294             data_format = 'int32' if n_bytes == 4 else 'int16'
--> 295             annot = _read_annotations_cnt(input_fname, data_format=data_format)
    296             events = (np.stack((annot.onset * sfreq,
    297                                 annot.duration * sfreq,

~/.local/lib/python3.5/site-packages/mne/io/cnt/cnt.py in _read_annotations_cnt(fname, data_format)
     68
     69     with open(fname, 'rb') as fid:
---> 70         teeg = _read_teeg(fid, teeg_offset=event_table_pos)
     71
     72     event_parser = _get_event_parser(event_type=teeg.event_type)

~/.local/lib/python3.5/site-packages/mne/io/cnt/_utils.py in _read_teeg(f, teeg_offset)
     26     teeg_parser = Struct('<Bll')
     27
---> 28     f.seek(teeg_offset)
     29     return Teeg(*teeg_parser.unpack(f.read(teeg_parser.size)))
     30

OSError: [Errno 22] Invalid argument
```

Also:
If I use:
```py
data = mne.io.read_raw_cnt('test.cnt', preload=True, montage=None)
```
I got different error:
```sh
<ipython-input-30-dbbb56936797>:1: FutureWarning: The parameter `stim_channel` controlling the stim channel synthesis has not been specified. In 0.18 it defaults to True but will change to False in 0.19 (when no stim channel synthesis will be allowed) and be removed in 0.20; migrate code to use `stim_channel=False` and :func:`mne.events_from_annotations` or set `stim_channel=True` to avoid this warning.
  data = mne.io.read_raw_cnt('test.cnt', preload=True, montage=None)
<ipython-input-30-dbbb56936797>:1: RuntimeWarning: Could not define the number of bytes automatically. Defaulting to 2.
  data = mne.io.read_raw_cnt('test.cnt', preload=True, montage=None)
Reading 0 ... 4528779  =      0.000 ...  4528.779 secs...
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-30-dbbb56936797> in <module>
----> 1 data = mne.io.read_raw_cnt(test.cnt', preload=True, montage=None)

~/.local/lib/python3.5/site-packages/mne/io/cnt/cnt.py in read_raw_cnt(input_fname, montage, eog, misc, ecg, emg, data_format, date_format, preload, stim_channel, verbose)
    176     return RawCNT(input_fname, montage=montage, eog=eog, misc=misc, ecg=ecg,
    177                   emg=emg, data_format=data_format, date_format=date_format,
--> 178                   preload=preload, stim_channel=stim_channel, verbose=verbose)
    179
    180

~/.local/lib/python3.5/site-packages/mne/io/cnt/cnt.py in __init__(self, input_fname, montage, eog, misc, ecg, emg, data_format, date_format, preload, stim_channel, verbose)
    439         data_format = 'int32' if cnt_info['n_bytes'] == 4 else 'int16'
    440         self.set_annotations(
--> 441             _read_annotations_cnt(input_fname, data_format=data_format))
    442
    443     @verbose

~/.local/lib/python3.5/site-packages/mne/io/cnt/cnt.py in _read_annotations_cnt(fname, data_format)
     68
     69     with open(fname, 'rb') as fid:
---> 70         teeg = _read_teeg(fid, teeg_offset=event_table_pos)
     71
     72     event_parser = _get_event_parser(event_type=teeg.event_type)

~/.local/lib/python3.5/site-packages/mne/io/cnt/_utils.py in _read_teeg(f, teeg_offset)
     26     teeg_parser = Struct('<Bll')
     27
---> 28     f.seek(teeg_offset)
     29     return Teeg(*teeg_parser.unpack(f.read(teeg_parser.size)))
     30

OSError: [Errno 22] Invalid argument
```
Here is my mne info
```sh
mne.sys_info()
Platform:      Linux-4.4.0-151-generic-x86_64-with-Ubuntu-16.04-xenial
Python:        3.5.2 (default, Nov 12 2018, 13:43:14)  [GCC 5.4.0 20160609]
Executable:    /usr/bin/python3
CPU:           x86_64: 12 cores
Memory:        Unavailable (requires "psutil" package)
mne:           0.18.1
numpy:         1.16.3 {blas=openblas, lapack=openblas}
scipy:         1.3.0
matplotlib:    3.0.1 {backend=TkAgg}

sklearn:       0.19.1
nibabel:       Not found
mayavi:        Not found
cupy:          Not found
pandas:        0.22.0
dipy:          Not found
```

### PR DESCRIPTION
**Pull request by massich**
Fixes #6535

### CODE REVIEW

**Comment by massich** [comment]
@LM-thinking can you try this in your files? Thx.

**Comment by massich** [comment]
lets see how the CIs tourn out

**Comment by AimerLee** [comment]
After reviewing the commit history of cnt.py, I found similar problem in #4520, where the issuer mentioned that files bigger than 2G will result the event_offset be negative.  
 > Yeah, I have the problematic file. It's 2GB. The event_offset field in the file header was a negative value. Rest of the header seems okay. The first if condition in the following code is used to simply check the event_offset overflow condition, and in fact is not needed after the bug is fixed.
``` python 
        if event_offset < data_offset:  # no events
            data_size = n_samples * n_channels
        else:
            data_size = event_offset - (data_offset + 75 * n_channels)
```

**Comment by AimerLee** [comment]
In the **_utils**, cnt file size is used to decide whether to caculate the event table pos. This is in fact not so robust, because 2G is not so match with the overflow threshold of the int32. 

One possible solution might as following code, which obtain the event table pos by check wheather the suffix of binary reprentation  between cacluated and the directly readed value of event_table_pos are identical. And infer the nbytes at the same time.
``` python

        # Header has a field for number of samples, but it does not seem to be
        # too reliable. That's why we have option for setting n_bytes manually.
        fid.seek(864)
        n_samples = np.fromfile(fid, dtype='<i4', count=1)[0]
``` 
``` python
fid.seek(SETUP_NSAMPLES_OFFSET)
(n_samples,) = np.frombuffer(fid.read(4), dtype='<i4')

fid.seek(SETUP_NCHANNELS_OFFSET)
(n_channels,) = np.frombuffer(fid.read(2), dtype='<u2')

fid.seek(SETUP_EVENTTABLEPOS_OFFSET)
(event_table_pos,) = np.frombuffer(fid.read(4), dtype='<i4')


def _infer_n_bytes_event_table_pos(readed_event_table_pos):
    readed_event_table_pos_feature = np.binary_repr(readed_event_table_pos).lstrip('-')

    for n_bytes in [2, 4]:
        event_table_pos = (900 + 75 * int(n_channels) + n_bytes * int(n_channels) * int(n_samples))
        if np.binary_repr(event_table_pos).endswith(readed_event_table_pos_feature):
            return n_bytes, event_table_pos
    raise Exception("event_table_dismatch") 
``` 

Note that all these mentioned above base on the fact that n_samples value is reliable, but the comment in cnt.py said the fact is not. After checking the source code of the EEGLAB, the readed n_samples is trusted.

**Comment by massich** [comment]
@AimerLee makes sense. However it is not working for me. I'm sure is a silly mistake.

**Comment by massich** [comment]
I liked 660eb9d, it used `event_table_pos` to compute `n_bytes` and it was clean. But I don't understand why does not work.

I've done this toy example from CNT private date people have been sharing with me overtime.

```py
import os.path as op

import numpy as np
import pytest

from mne import __file__ as _mne_file
from mne.utils import run_tests_if_main
from mne.io.cnt import read_raw_cnt
from mne.io.cnt._utils import CNTEventType1, CNTEventType2, CNTEventType3

def foo(fname):
    SETUP_NCHANNELS_OFFSET = 370
    SETUP_NSAMPLES_OFFSET = 864
    SETUP_EVENTTABLEPOS_OFFSET = 886

    with open(fname, 'rb') as fid:

        fid.seek(SETUP_NSAMPLES_OFFSET)
        (n_samples,) = np.frombuffer(fid.read(4), dtype='<i4')

        fid.seek(SETUP_NCHANNELS_OFFSET)
        (n_channels,) = np.frombuffer(fid.read(2), dtype='<u2')

        fid.seek(SETUP_EVENTTABLEPOS_OFFSET)
        (readed_event_table_pos,) = np.frombuffer(fid.read(4), dtype='<i4')

    print('readed_event_table_pos: ', readed_event_table_pos)
    print('xx : ', np.binary_repr(readed_event_table_pos))
    print('yy : ', np.binary_repr(readed_event_table_pos).lstrip('-'))
    readed_event_table_pos_feature = np.binary_repr(
        readed_event_table_pos).lstrip('-')

    for n_bytes_candidate in [2, 4]:
        computed_event_table_pos = (
            900 + 75 * int(n_channels) +
            n_bytes_candidate * int(n_channels) * int(n_samples))

        print('kk : ', np.binary_repr(computed_event_table_pos))
        if (
            np.binary_repr(computed_event_table_pos)
            .endswith(readed_event_table_pos_feature)
        ):
            n_bytes = n_bytes_candidate
            event_table_pos = computed_event_table_pos
            print('n_bytes: ', n_bytes)
            print('computed_event_table_pos: ', computed_event_table_pos)
            break

        else:
            n_bytes, event_table_pos = None, None

    if event_table_pos is None:
        print('read was good')

    return n_channels, n_samples, event_table_pos, n_bytes


pp = pytest.param
@pytest.mark.parametrize((
    'fname,expected_n_bytes,expected_event_type,expected_event_table_pos'), [
    pp(op.join(op.dirname(_mne_file),
               '../sandbox/data/914flankers.cnt'),
       4, CNTEventType2, 156474479),

    pp(op.join(op.dirname(_mne_file),
               '../sandbox/data/confidential/cnt/cont_68chan_32bit.cnt'),
       4, CNTEventType2, 57267440),

    pp(op.join(op.dirname(_mne_file),
               '../sandbox/data/confidential/cnt/'
               'pilote_resting_01_neurospin_2019-03-04_15-18-40.cnt'),
       2, CNTEventType2, 15518747),

    pp(op.join(op.dirname(_mne_file),
               '../sandbox/data/confidential/cnt/'
               'cont_22chan_4gb_32bit_toolong.cnt'),
       4, CNTEventType3, 4971618850),

    pp(op.join(op.dirname(_mne_file),
               '../sandbox/data/confidential/cnt/SampleCNTFile_16bit.cnt'),
       2, CNTEventType2, 133700),

    pp(op.join(op.dirname(_mne_file),
               '../sandbox/data/confidential/cnt/cnt_files/'
               'SampleCNTFile_16bit.cnt'),
       2, CNTEventType2, 133700),

    pp(op.join(op.dirname(_mne_file),
               '../sandbox/data/confidential/cnt/cnt_files/'
               'BoyoAEpic1_16bit.cnt'),
       2, CNTEventType2, 78536260),

    pp(op.join(op.dirname(_mne_file),
               '../sandbox/data/confidential/cnt/cnt_files/'
               'cont_67chan_resp_32bit.cnt'),
       4, CNTEventType2, 54570725),

    pp(op.join(op.dirname(_mne_file),
               '../sandbox/data/confidential/cnt/BoyoAEpic1_16bit.cnt'),
       2, CNTEventType2, 78536260),

    pp(op.join(op.dirname(_mne_file),
               '../sandbox/data/confidential/cnt/cont_67chan_resp_32bit.cnt'),
       4, CNTEventType2, 54570725),
], ids=[str(n) for n in range(10)]
)
def test_foo(fname, expected_n_bytes, expected_event_type,
             expected_event_table_pos):
    """Test reading raw cnt files."""
    print('\n')
    print('expected_n_bytes: ', expected_n_bytes)
    print('expected_event_table_pos: ', expected_event_table_pos)
    n_channels, n_samples, event_table_pos, n_bytes = foo(fname)
    assert True


run_tests_if_main()
```


Check out the trace:

```sh
rootdir: /home/sik/code/mne-python, inifile: setup.cfg
plugins: timeout-1.3.3, sugar-0.9.2, pudb-0.7.0, mock-1.10.3, faulthandler-1.5.0, cov-2.6.1
collecting ... 

expected_n_bytes:  4
expected_event_table_pos:  156474479
readed_event_table_pos:  156474479
xx :  1001010100111001110001101111
yy :  1001010100111001110001101111
kk :  100101001110011110011100101
kk :  1001010011100110001010100101
read was good

 sandbox/mwe/6535_test_cnt.py ✓                                                            10% █         

expected_n_bytes:  4
expected_event_table_pos:  57267440
readed_event_table_pos:  57267440
xx :  11011010011101010011110000
yy :  11011010011101010011110000
kk :  1101101001111011000110000
kk :  11011010011101010011110000
n_bytes:  4
computed_event_table_pos:  57267440
 sandbox/mwe/6535_test_cnt.py ✓✓                                                           20% ██        

expected_n_bytes:  2
expected_event_table_pos:  15518747
readed_event_table_pos:  15518747
xx :  111011001100110000011011
yy :  111011001100110000011011
kk :  101000100111011
kk :  1001100000110101
read was good
 sandbox/mwe/6535_test_cnt.py ✓✓✓                                                          30% ███       

expected_n_bytes:  4
expected_event_table_pos:  4971618850
readed_event_table_pos:  676651554
xx :  101000010101001110001000100010
yy :  101000010101001110001000100010
kk :  10010100001010100111011010100010
kk :  100101000010101001110001000100010
n_bytes:  4
computed_event_table_pos:  4971618850
 sandbox/mwe/6535_test_cnt.py ✓✓✓✓                                                         40% ████      

expected_n_bytes:  2
expected_event_table_pos:  133700
readed_event_table_pos:  133700
xx :  100000101001000100
yy :  100000101001000100
kk :  100000101001000100
n_bytes:  2
computed_event_table_pos:  133700
 sandbox/mwe/6535_test_cnt.py ✓✓✓✓✓                                                        50% █████     

expected_n_bytes:  2
expected_event_table_pos:  133700
readed_event_table_pos:  133700
xx :  100000101001000100
yy :  100000101001000100
kk :  100000101001000100
n_bytes:  2
computed_event_table_pos:  133700
 sandbox/mwe/6535_test_cnt.py ✓✓✓✓✓✓                                                       60% ██████    

expected_n_bytes:  2
expected_event_table_pos:  78536260
readed_event_table_pos:  78536260
xx :  100101011100101111001000100
yy :  100101011100101111001000100
kk :  1111111111111111111010100110111000100
kk :  11111111111111111110101000010101000100
read was good
 sandbox/mwe/6535_test_cnt.py ✓✓✓✓✓✓✓                                                      70% ███████   

expected_n_bytes:  4
expected_event_table_pos:  54570725
readed_event_table_pos:  54570725
xx :  11010000001010111011100101
yy :  11010000001010111011100101
kk :  1101000000110001100000101
kk :  11010000001010111011100101
n_bytes:  4
computed_event_table_pos:  54570725
 sandbox/mwe/6535_test_cnt.py ✓✓✓✓✓✓✓✓                                                     80% ████████  

expected_n_bytes:  2
expected_event_table_pos:  78536260
readed_event_table_pos:  78536260
xx :  100101011100101111001000100
yy :  100101011100101111001000100
kk :  1111111111111111111010100110111000100
kk :  11111111111111111110101000010101000100
read was good
 sandbox/mwe/6535_test_cnt.py ✓✓✓✓✓✓✓✓✓                                                    90% █████████ 

expected_n_bytes:  4
expected_event_table_pos:  54570725
readed_event_table_pos:  54570725
xx :  11010000001010111011100101
yy :  11010000001010111011100101
kk :  1101000000110001100000101
kk :  11010000001010111011100101
n_bytes:  4
computed_event_table_pos:  54570725
 sandbox/mwe/6535_test_cnt.py ✓✓✓✓✓✓✓✓✓✓                                                  100% ██████████
-------------------- generated xml file: /home/sik/code/mne-python/junit-results.xml --------------------


======================================= slowest 20 test durations =======================================

(0.00 durations hidden.  Use -vv to show these durations.)

Results (9.96s):
      10 passed

Compilation finished at Wed Jul 10 13:59:09
```

It works for some cases, in particular it fixes the >2Gb case:
```sh
expected_n_bytes:  4
expected_event_table_pos:  4971618850
readed_event_table_pos:  676651554
xx :  101000010101001110001000100010
yy :  101000010101001110001000100010
kk :  10010100001010100111011010100010
kk :  100101000010101001110001000100010
n_bytes:  4
computed_event_table_pos:  4971618850
```

But it is not able to capture cases where it should work.

**Comment by massich** [comment]
@agramfort, @AimerLee maybe we should merge with `<2Gb` for the moment and continue this converstation in #6550

**Comment by agramfort** [comment]
thx @massich

**Pull request merged**
