### PR TITLE
FIX: checking for surfaces

### PR DESCRIPTION
**Pull request by dengemann**
it seems this script's logic was broken. Surf was never None and mkheadsurf never got triggered in that case.

### CODE REVIEW

**Comment by dengemann** [comment]
cc @agramfort @Eric89GXL

**Comment by agramfort** [comment]
LGTM

Can you update what's new and backport?

**Comment by Eric89GXL** [comment]
+1 for merge as well

**Comment by dengemann** [comment]
Thanks for the quick review. I'll back port later if @Eric89GXL is not faster :)

**Comment by dengemann** [comment]
cherry-picked 6053d2eee into maint/0.14 and pushed.

**Pull request merged**
