### PR TITLE
DOC: Fixes a typo in ICA docstring

### PR DESCRIPTION
**Pull request by arokem**
#### What does this implement/fix?

"principle component" => "principal components"

### CODE REVIEW

**Comment by mmagnuski** [comment]
I'm not sure about this one: wikipedia gives singular "component"
https://en.wikipedia.org/wiki/Principal_component_analysis
is there an error there too?
but I'm no expert on english language. :)

**Comment by mmagnuski** [comment]
BTW, the wikipedia also uses the plural but less frequently.

**Comment by arokem** [comment]
I think that you are right. I think that both are allowable, but "component" is in more common use (e.g., google search for "principal components analysis" gives about 2.7 M pages and "principal component analysis" gives >10 M pages.

Fixed back in recent commit.

**Comment by larsoner** [comment]
Thanks @arokem

**Pull request merged**
