### PR TITLE
MRG: Fix doc links [circle front]

### PR DESCRIPTION
**Pull request by larsoner**
1. Fix download buttons due to recent SG update.
2. Remove link in `whats_new.rst`. We could add `get_channel_types` to `python_reference.rst` but it seems like a dev option mostly.
3. Rename `examples/plot_receptive_field.py` to `examples/plot_receptive_field_mtrf.py` to avoid naming collisions with `tutorials/plot_receptive_field.py`.

### CODE REVIEW

**Comment by larsoner** [comment]
https://6793-1301584-gh.circle-artifacts.com/0/tmp/circle-artifacts.QIpzD23/html/auto_tutorials/plot_receptive_field.html

**Comment by agramfort** [comment]
the sphinx gallery button is still off for me with chrome

**Comment by larsoner** [comment]
> the sphinx gallery button is still off for me with chrome

You'll need to post a screenshot. This is what I see with Chrome:

screenshot from 2018-01-17 15-08-42

**Comment by agramfort** [comment]
this what I consider broken :)

why not stick to download button at the bottom like everyone?

**Comment by larsoner** [comment]
Feel free to read the long discussion here:

https://github.com/sphinx-gallery/sphinx-gallery/pull/336

And here:

https://github.com/sphinx-gallery/sphinx-gallery/pull/329

If you disagree we can force the CSS to revert it I think.

**Comment by larsoner** [comment]
(In other words, this floating behavior is the new default, and this PR makes it work properly with our customizations.)

**Comment by agramfort** [comment]
ok I jsut reacted :)

**Comment by larsoner** [comment]
@agramfort we have three choices that I can see:

1. Reduce our width. This will be painful because `bootstrap` sets it, so -1 from me.
2. Fix the overlap, allow buttons to float to the right on wide displays. I've added this because it's consistent with what SG will do from now on.
3. Remove the floating completely (i.e., revert behavior). This is easily doable, as I had to effectively disable then reenable it separately in the CSS to implement (2).

Here is a link for testing with the fixed floating:

https://6798-1301584-gh.circle-artifacts.com/0/tmp/circle-artifacts.71BDpjQ/html/auto_tutorials/plot_receptive_field.html

**Comment by agramfort** [comment]
LGTM

+1 for MRG

thx @larsoner

**Pull request merged**
