### PR TITLE
Fix bug in index resorting

### PR DESCRIPTION
**Pull request by cle1109**
Here's the fix for #2630. Sorry about that. I'll create a test to avoid this error in the future in a separate PR.

### CODE REVIEW

**Comment by cle1109** [comment]
Why do I get this error now:

    Traceback (most recent call last):
      File "/Users/clemens/Repositories/mne-python/examples/decoding/plot_decoding_csp_eeg.py", line 112, in <module>
        unit='Patterns (AU)', size=1.5)
      File "/Users/clemens/Repositories/mne-python/mne/evoked.py", line 656, in plot_topomap
        axes=axes)
      File "/Users/clemens/Repositories/mne-python/mne/viz/topomap.py", line 1288, in plot_evoked_topomap
        plt_show(show)
      File "/Users/clemens/Repositories/mne-python/mne/viz/utils.py", line 56, in plt_show
        plt.show(warn=False, **kwargs)
      File "/Users/clemens/anaconda/lib/python3.5/site-packages/matplotlib/pyplot.py", line 155, in show
        return _show(*args, **kw)
    TypeError: __call__() got an unexpected keyword argument 'warn'

**Comment by Eric89GXL** [comment]
What version of `matplotlib` are you running? We'll need to update `plt_show` to check whether `warn` is in the argument list using `_get_args`. You can do it as part of this PR or I can take care of it if it's unclear.

**Comment by cle1109** [comment]
I'm running the latest version 1.5.0. According to the API, `plt.show` has only variable arguments: `matplotlib.pyplot.show(*args, **kw)`. That's why `_get_args` returns an empty list.

Why do you need to set the `warn` argument? Can't we just skip it?

**Comment by agramfort** [comment]
same pb here 

TypeError: __call__() got an unexpected keyword argument 'warn'

I'll merge this and let @Eric89GXL fix the plt error in another PR.

thanks @cle1109

**Comment by cle1109** [comment]
Thanks @agramfort!

**Pull request merged**
