### PR TITLE
MRG: Add fnirs and snirf support to report

### PR DESCRIPTION
**Pull request by rob-luke**
This is an issue as a PR, I have opened this for discussion.

#### What does this implement/fix?
Allows
```python
report = mne.Report()
report.parse_folder(path)
```
to read fNIRS files stored with the pattern `*-nirs.snirf` as defined in the draft BIDS standard https://bids-specification--802.org.readthedocs.build/en/802/04-modality-specific-files/10-functional-near-infrared-spectroscopy.html#fnirs-recording-data

#### Additional information
It seems report is currently used with fiff files, are we open to extending it to other file types?

Allowing the file pattern above will facilitate reading files in the BIDS format. The fNIRS BIDS specification has moved from a community feedback stage to draft proposal: https://github.com/bids-standard/bids-specification/pull/802 However, its not finalised (as I am the BEP lead it is extremely unlikely this file pattern will change, but I am trying to think of all possible issues here).

### CODE REVIEW

**Comment by larsoner** [comment]
> It seems report is currently used with fiff files, are we open to extending it to other file types?

Seems reasonable to me

**Comment by rob-luke** [comment]
> Seems reasonable to me

Well in that case, @larsoner @agramfort could you please review?

**Review by larsoner — COMMENTED** [review]
Needs latest.inc update, otherwise LGTM

**Review by agramfort — APPROVED** [review]
thx @rob-luke

**Comment by hoechenberger** [comment]
Thanks!!

**Pull request merged**
