### PR TITLE
MRG: Deprecate mask_type -> "and"

### LINKED ISSUE #4286: default for mask_type
Hi,
I was recently a bit surprised by the fact that when finding trigger events with a mask, `mne.find_events` defaults to `mask_type='not_and'`, whereas the `AcqParserFIF` class defaults to `mask_type='and'`

I cannot recall now if this was done deliberately, or is it a mistake?

### PR DESCRIPTION
**Pull request by Eric89GXL**
Closes #4286.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
cc @jjnurminen

**Comment by agramfort** [comment]
LGTM

**Comment by jjnurminen** [comment]
The AcqParserFIF class quietly defaults to `'mask_type=and'`. I guess that's ok?

**Comment by Eric89GXL** [comment]
Ahh good to check that -- in this case it's fine because it's already at the desired default

**Comment by teonbrooks** [comment]
I'm very happy the `mask_type` and "not_and" are finally going away.

**Comment by jaeilepp** [comment]
thx @Eric89GXL

**Pull request merged**
