### PR TITLE
FIX: Expose _set_3d_view and _set_3d_title

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR exposes the functions `_set_3d_view()` and `_set_3d_title()` to the `notebook` 3d backend.

Related to https://github.com/mne-tools/mne-python/issues/8388

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
Let me know if this solves your issue @timonmerk

**Comment by GuillaumeFavelier** [comment]
This is ready for reviews @agramfort, @larsoner

**Comment by larsoner** [comment]
Can you modify the `notebook` test such that it has better coverage?

**Review by agramfort — APPROVED** [review]

**Comment by larsoner** [comment]
@GuillaumeFavelier do we need to backport this?

**Comment by larsoner** [comment]
... it seemed to work without issue so I backported

**Pull request merged**
