### PR TITLE
group level cluster permutation WIP

### PR DESCRIPTION
**Pull request by SophieHerbst**

### CODE REVIEW

**Comment by drammock** [comment]
crossrefs:

- roadmap: https://mne.tools/dev/overview/roadmap.html#clustering-statistics-api
- big discussion: #4859

**Comment by larsoner** [comment]
It sounds like a goal is to make the stats clustering functions more user-friendly. As @drammock points out above, we've had a lot of conversations about this but little progress, so it would be nice to at least get something working!

Given the extent of the conversations above, it seems like it will be difficult to get a one-size-fits-all API settled that everyone can agree on and implemented in a week. From quick chats with @agramfort and @drammock we came up with the idea of putting this first in `mne-sandbox`, which is meant for experimental code. This allows us to start very small with something that hopefully works well and solves a relevant use case.

Then from there, later we can expand to other inputs with other dimensionality (frequency? 3D space? source labels with neighbor connectivity?), and other stats tests. And as people use it and we modify / update, eventually we can move it to MNE-Python. Thoughts?

**Comment by SophieHerbst** [comment]
@larsoner I don't know what mne-sandbox is, or how to use it? 
For now @hoechenberger and I did not touch the stats function used, but we are implementing a wrapper for group statistics that takes evokeds (to be extended to averageTFR) and spits out a results object. The intention being to provide something usable quickly and then make it more universal. 
Happy to discuss about how to pursue!

**Comment by hoechenberger** [comment]
> From quick chats with @agramfort and @drammock we came up with the idea of putting this first in `mne-sandbox`, which is meant for experimental code. This allows us to start very small with something that hopefully works well and solves a relevant use case.

I don't think that's necessary here; we're merely adding one new function and a new class, both of which are very slim. I think marking them as experimental ought to be enough.

I'm worried "burying" these developments in `mne-sandbox` won't give them the needed exposure to users…

**Comment by hoechenberger** [comment]
But isn't a draft PR good enough for this?

**Comment by agramfort** [comment]
Don’t expect to see this merged in a few weeks as is

**Comment by drammock** [comment]
> we're merely adding one new function and a new class, both of which are very slim. I think marking them as experimental ought to be enough.

to make @larsoner's point in a slightly different way: what does it mean to "mark them as experimental"?  We don't currently have an established way of doing that *within MNE-Python*.  The established way of doing that is to put it in MNE-Sandbox.

As an aside:

> the sandbox seems dead; I don't want to use it for my code. Feels like pouring it down the drain???

Just a few weeks ago someone asked about using my DSS code from one of my old papers, and I was able to point them to the scripts which say `from mne_sandbox.preprocessing import dss`.

**Comment by hoechenberger** [comment]
> Just a few weeks ago someone asked about using my DSS code from one of my old papers, and I was able to point them to the scripts which say `from mne_sandbox.preprocessing import dss`.

But if we're putting it in a separate repo / package, I might as well create my own one where I'm not restricted by MNE conventions. I don't see the point of the sandbox, sorry.

**Comment by hoechenberger** [comment]
We're continuing this at https://github.com/mne-tools/mne-sandbox/pull/31

**Comment by SophieHerbst** [comment]
@scott-huberty Added validation to explicitly check whether 'within_id' matches a variable in the df
https://github.com/SophieHerbst/mne-python/tree/new_cluster_stats_api_GSOC24

**Pull request closed without merging**
