### PR TITLE
MRG: Fix BTi reading for Magnes2500

### LINKED ISSUE #2170: FIX: io.bti coverage
@teonlamont any ideas on how to improve this?

https://coveralls.io/builds/2689771/source?filename=mne%2Fio%2Fbti%2Fbti.py

For example, `_read_ch_config` is about 50 lines (including comments) and isn't tested at all.

Do you know of any small files we could add to the testing dataset that would improve our coverage? It looks like a MAGNES2500 file might help?

There is also a section with `if False:  # XXX reminds us to support this as we go` can you elaborate on that, and preferably comment out those lines instead of using `if False`?

### PR DESCRIPTION
**Pull request by Eric89GXL**
@dengemann this touches some of your code from 2013 (!) that apparently has a bug. I guess these lines weren't covered or ever used before this :(

I am trying to read some BTi data, I think from MAGNES2500. I hit this bug where `d` was used instead of `n`, but after fixing it I hit a bug when it tries to read the next "block", so I suspect there is something wrong with these 2500-specific lines.

Do you have some MAGNES2500 data that you were using to test/develop originally? What did you use to figure out these lines?

Closes #2170.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
Looks like the expected size is 13620 but we're only reading 2268 bytes for that weight table

**Comment by dengemann** [comment]
> I am trying to read some BTi data, I think from MAGNES2500. I hit this bug where d was used instead of n, but after fixing it I hit a bug when it tries to read the next "block", so I suspect there is something wrong with these 2500-specific lines.

I never had WH2500 data and the code is not necessarily supposed to handle it. These lines are related to the ref channel weights, which did not have a working calibration in Jülich , so I never had a chance to really look into it.

**Comment by Eric89GXL** [comment]
> the code is not necessarily supposed to handle it.

Hmm... there are multiple branches in the code for version 1 (WH2500) versus version 2 data. Did you start writing support for it but stop? What were you basing the implementation on? Is there existing code or a spec somewhere?

**Comment by dengemann** [comment]
> Hmm... there are multiple branches in the code for version 1 (WH2500) versus version 2 data.

I would have to look into it. Various sources.

**Comment by Eric89GXL** [comment]
Please do if you have time, it would be good to support these older systems

**Comment by Eric89GXL** [comment]
Anybody have access to a small MAGNES2500 data file that I could use for testing?

**Comment by Eric89GXL** [comment]
I found some test data. @dengemann do you have time to review?

**Comment by dengemann** [comment]
Yes, can review in a few hours.

**Comment by dengemann** [comment]
@Eric89GXL are you happy? It looks clean to me and it seems the 3600 reading is not affected by your changes.

**Comment by Eric89GXL** [comment]
Yeah it should be good to go

**Comment by dengemann** [comment]
Ok, just tested with HCP data, no interference -- merging. Thank you Eric!

**Comment by Eric89GXL** [comment]
Thanks for the quick review @dengemann

**Pull request merged**
