### PR TITLE
purge _get_args helper func

### LINKED ISSUE #11089: check if `fixes._get_args` can be replaced by builtin `signature` func
We typically use `_get_args` from `fixes` for this. Can you use it here and/or open an issue that we should investigate whether we can migrate to `inspect.signature` directly nowadays? I can't remember if we just needed to wait until 3.7+ or if `.parameters` isn't enough sometimes, or something else

_Originally posted by @larsoner in https://github.com/mne-tools/mne-python/pull/10184#discussion_r954671494_

### PR DESCRIPTION
**Pull request by drammock**
closes #11089

@larsoner in all but one case, a simple `signature(f).parameters` (or `list(signature(f).parameters)` was sufficient.  IMO the helper function is not really needed, but if you disagree feel free to close this without merging.

### CODE REVIEW

**Review by agramfort — APPROVED** [review]

**Comment by drammock** [comment]
These failures passed for me locally... turns out I had scipy 1.8.x and they fail with 1.9.x.  Will fix:

```
_________________________ test_ica_additional[picard] __________________________
mne/preprocessing/tests/test_ica.py:789: in test_ica_additional
    for name, func in get_score_funcs().items():
mne/preprocessing/ica.py:121: in get_score_funcs
    assert 'pearsonr' in score_funcs
E   AssertionError
_________________________ test_ica_additional[fastica] _________________________
mne/preprocessing/tests/test_ica.py:789: in test_ica_additional
    for name, func in get_score_funcs().items():
mne/preprocessing/ica.py:121: in get_score_funcs
    assert 'pearsonr' in score_funcs
E   AssertionError
_______________________________ test_ica_labels ________________________________
mne/preprocessing/tests/test_ica.py:1374: in test_ica_labels
    ica.find_bads_eog(raw, l_freq=None, h_freq=None)
<decorator-gen-447>:12: in find_bads_eog
    ???
mne/preprocessing/ica.py:1889: in find_bads_eog
    self.labels_['eog'], scores = self._find_bads_ch(
mne/preprocessing/ica.py:1376: in _find_bads_ch
    scores += [self.score_sources(
<decorator-gen-443>:12: in score_sources
    ???
mne/preprocessing/ica.py:1318: in score_sources
    scores = _find_sources(sources, target, score_func)
mne/preprocessing/ica.py:2367: in _find_sources
    score_func = get_score_funcs().get(score_func, score_func)
mne/preprocessing/ica.py:121: in get_score_funcs
    assert 'pearsonr' in score_funcs
E   AssertionError
```

**Comment by drammock** [comment]
OK those tests pass locally now for me with scipy 1.8.0 and 1.9.1 so hopefully CIs are happy now

**Comment by agramfort** [comment]
@britta-wstnr I let you click the auto-merge button if it's ok for you.

**Review by larsoner — APPROVED** [review]

**Comment by agramfort** [comment]
thx @drammock

**Pull request merged**
