### PR TITLE
WIP,ENH: new coreg gui features (part 3)

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR is based on https://github.com/mne-tools/mne-python/pull/10085 and adds the following:
- [x] add support for the scaling parameters

It's part of #8833

*Can only be merged after https://github.com/mne-tools/mne-python/pull/10085*

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
Only the `ipywidgets` that inherit from `DOWWidget` support tooltips. From the [widget list](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html), those are `Button`, `ToggleButton` and `ToggleButtons`

**Comment by GuillaumeFavelier** [comment]
I looked at the code of the previous version to know more about the `scale` parameter and it seems to set the parallel projection scale of the camera. I'm not sure that's what we need, I'll have to try it out.

For now, this version of `scale` actually changes the geometry of the head surface.

**Comment by larsoner** [comment]
Don't worry about changing projection for now. We can add that later if we need it. The critical thing is actually scaling the head surface (and updating everything properly)

**Comment by GuillaumeFavelier** [comment]
I tried on the previous interface: 

https://user-images.githubusercontent.com/18143289/145599332-a4052be3-4472-4fb6-bff2-3d5c20a5f312.mp4

And `scale` seems to be similar to [zoom in pyvista](https://docs.pyvista.org/api/core/_autosummary/pyvista.Camera.zoom.html). I do not think I have to modify the geometry after all

**Comment by larsoner** [comment]
What you should be trying is the scaling mode in the upper right. It's none/disabled in your video

**Comment by GuillaumeFavelier** [comment]
Okay I misunderstood the 'scale parameter' then.

> the scaling mode in the upper right.

I'm on it

**Comment by GuillaumeFavelier** [comment]
Now it makes sense:

https://user-images.githubusercontent.com/18143289/145601927-c06428ea-7f80-47b7-9170-768da5ebf70c.mp4

**Comment by larsoner** [comment]
Yes exactly!

**Comment by GuillaumeFavelier** [comment]
I opened https://github.com/mne-tools/mne-python/pull/10141 with the features already available. I'll dedicate this PR to scale parameters.

**Comment by larsoner** [comment]
Sounds like a reasonable split!

**Comment by GuillaumeFavelier** [comment]
I spent some time comparing the 2 interfaces side-by-side and I checked both distance estimations and viz. I think the current state is good enough, this PR is now ready for reviews from my end @agramfort, @larsoner 

---

I also discovered that the pyvista app is maybe more strict on ICP? In my local testing, the algorithm finishes one iteration sooner. But it's not related to this PR (I reproduced on `main`), I just discovered it in here

**Review by larsoner — CHANGES_REQUESTED** [review]
Looks like it's mostly there! Just a few remaining points, mostly coming from how the new interface differs from the old one:

1. When ICP runs, the parameters (transform and scale factors) do not update until the end, it's useful to be able to see them update on each iteration:

   https://user-images.githubusercontent.com/2365790/146565944-a69f6558-7fac-4294-a607-8a27231b367d.mp4

 2. When saving, looks like a `f''` is missing:

   Screen Shot 2021-12-17 at 10 13 32 AM
 
3. When scaling mode is enabled, more needs to be saved than the `-trans.fif`. You need to save the scaled MRI as a new subject as well, and also create a new BEM solution. Try actually hitting "Save" using the old Mayavi UI (with "save BEM" enabled) and you'll see what I mean.

4. You actually need a second bank of "Fit Fiducials" and "Fit ICP" options that apply to the scaling mode (see the old Mayavi interface). This is because sometimes you want to iterate on the scaling (or set it manually), then once it's set, iterate on the alignment. In other words, the new/additional top set of fit buttons should fit/update the scale+trans, and the existing bottom ones only ever fit/update the trans. Moreover, the new scale+trans "Fit Fiducials" button should be disabled when in 3-axis mode, because there are too many DOF for the scale+trans to use just the fids (e.g., there is very little information about what Z axis scaling would be appropriate).

5. It looks like there are no updated unit tests. Perhaps some of the ones from the old Mayavi interface could be recycled here? If not, rescaling fsaverage to `sample`'s digitization is something you could do using the `testing` data. For example you could programmatically enable 1-axis mode, fit fiducials, enable 3-axis mode, run ICP. This is what I get with the current UI:

    Screen Shot 2021-12-17 at 10 13 32 AM

    It would be good to run this procedure with the old UI and see if the results match (they should!).

**Comment by GuillaumeFavelier** [comment]
I took care of `1.` and `2.` in https://github.com/mne-tools/mne-python/pull/10144 @larsoner

**Comment by GuillaumeFavelier** [comment]
I think I'm done with `4.` and `5.`. Now, I'm on the saving part. At first it seems tricky to port from the old app.

**Comment by GuillaumeFavelier** [comment]
For now, `skip_fiducials` and `prepare_bem` are not supported.

I also need to start the `scale_mri()` job in a different thread so that the main thread does not hang while waiting.

**Comment by larsoner** [comment]
Go go go @GuillaumeFavelier !

**Comment by GuillaumeFavelier** [comment]
I added another checkbox for `skip_fiducials` and now it's ready for review from my end @agramfort, @larsoner

**Comment by larsoner** [comment]
From our chat today, I think the plan is:

1. move the MRI scaling params to the left panel (keeping separate fit fid / fit icp buttons)
2. have save surrogate MRI subject button on the left
3. have the save -trans.fif button on the right
4. remove options for what to include/exclude when saving the surrogate subject, and instead make sure the saved subject is as much a copy of the old one as possible (copying labels, copying annot, scaling fiducials, copying bem, recomputing -bem-sol.fif, modifying and saving -src.fif if and only if the original subject had these files)

Others feel free to chime in if it seems like I missed something

**Comment by drammock** [comment]
> Others feel free to chime in if it seems like I missed something

One thing was to *not* have a default subj name filled in when saving anatomy; the user *must* enter a subject name (otherwise the save button will be greyed out).  Another idea was to have translation and rotation be in a 2-column arrangement; right now the input boxes are wider than they need to be and there's a lot of empty space between input boxes and their labels.

I think the rest was mostly about naming. Not sure which of these was ultimately agreed upon, but ideas were:
1. the new UI group in the left column could be called "MRI scaling"
2. "save scaled anatomy"
3. "fit fiducials with scaling" / "fit ICP with scaling" / "reset scaling"

One thing that didn't come up was where the fitting options end up after all this moving around of UI items...  the options affect both the (now left-column) fit-with-anatomy-scaling and also affect the right-column fit-with-translation-and-rotation-only procedure.  Moving MRI scaling to the left makes it less obvious that it will be affected by those options.

**Comment by GuillaumeFavelier** [comment]
The PR is not ready yet but here are the three main directions as mockups:

version 1 (`MRI Scaling` on the left):

image

version 2 (`Translation (t) and Rotation (r)`):

image

version 3 (`MRI Scaling` on the right):

image

**Comment by GuillaumeFavelier** [comment]
After refining a little bit:

`MRI Scaling` on the left:

image


`MRI Scaling` on the right:

image

**Comment by larsoner** [comment]
They seem pretty similar to me. If I had to choose I'd go with MRI scaling on the right because it matches more what people who use this are accustomed to. But no strong feeling, so just +0.5 on "MRI right" for me

**Comment by agramfort** [comment]
scaling params on the right works for me.

**Comment by GuillaumeFavelier** [comment]
Notes from the offline meeting:

* rename "Transform" groupbox into "HEAD <> MRI Transform"
* add a prompt check name already exists "overwrite or not"
* multiple threads should block window exit
* add a checkbox to set enable/disable transparency (alpha=0.95)

**Comment by larsoner** [comment]
> add a checkbox to set enable/disable transparency (alpha=0.95)

FWIW I think more people (me and @drammock) voted for a slider or double entry box than just a checkbox (@hoechenberger )

**Comment by larsoner** [comment]
Okay I found a few issues, but I think they can all be tackled in a follow-up PR, other than the issue of not actually computing the BEM solutions which I fixed in a113b48. As it is now, it allows me to scale + save a usable subject, so I'll go ahead and merge once this last commit comes back green -- thanks in advance @GuillaumeFavelier !

Remaining issues below, please add these and the points you made above to some issue to keep track @GuillaumeFavelier

### Non-scaling issues (3)

Okay first I did:
```
$ mne coreg -s sample -d subjects -f MEG/sample/sample_audvis_raw.fif --trans MEG/sample/sample_audvis_raw-trans.fif 
```
then checked "Lock fiducials". The plot is wrong (trans is not used):

Screenshot from 2022-01-14 13-07-06

Clicking up on the X translation (which makes a tiny change) it actually updates:

Screenshot from 2022-01-14 13-07-12

Next, after changing the X and clicking "Fit ICP" repeatedly (after waiting for it to finish), I get an error in the terminal (probably because only one ICP iteration is done, and no change is made):
```
Traceback (most recent call last):
  File "/home/larsoner/python/mne-python/mne/gui/_coreg.py", line 948, in _fit_icp
    self._fits_icp()
  File "/home/larsoner/python/mne-python/mne/gui/_coreg.py", line 979, in _fits_icp
    f"{self._current_icp_iterations} iterations.")
AttributeError: 'CoregistrationUI' object has no attribute '_current_icp_iterations'. Did you mean: '_set_icp_n_iterations'?
```

After clicking "Fit ICP with scaling" or "Fit ICP", the name of the button should become "Stop ICP with scaling" and "Stop ICP" respectively, and if you click it, the button should be disabled, ICP should stop, and then the button should have its label changed back and be reenabled. This is better UX and also prevents problems with accidentally double-clicking "Fit ICP" in the current UI (if you double-click, you will just get one iteration of ICP, rather than two sets of ICP trying to run at the same time, or whatever weirdness happens currently).

### Scaling issues (5)

Taking the same command above, do "lock fiducials", change to uniform scaling, and "Fit fiducials with scaling", then "Fit ICP with scaling", the head does a weird "flash" -- this is aesthetic, probably because of a remove/add/scale cycle with an `update=True` where it shouldn't exist (at the `add` step?), but we should fix it.

When in uniform scaling mode, the X should be enabled, but Y and Z disabled for user input. When X is updated, Y and Z should be updated to the same value. (In other words, there should be only one input value you can change, and when you do, it should change all three.)

Changing 3-axis mode to 1-axis mode does not actually change the head to 1-axis mode (it should use all the same value for x/y/z, probably the average of the three?); same with changing to None mode (it shouldn't scale).

The x/y/z double box increment is 100 (!), 1 is a more reasonable value.

Negative values (and ideally not even zero) should not be allowed in the x/y/z boxes. I would just set a minimum of 1., it seems reasonable enough. (If someday someone needs to scale to less than 1% we can change this.)

**Pull request merged**
