### PR TITLE
MAINT: 0.18.2 backports

### PR DESCRIPTION
**Pull request by larsoner**
Backports:

- #6355 (prefer default parser to _Counter)
- #6417 (BV events)
- #6420 (footer logos)
- #6426 (conftest.py fix)
- #6385 (docstring fixes)
- version bump to 0.18.2 in `__init__.py`

Tests pass locally, but will iterate until CIs are happy then merge.

Then maybe we cut 0.18.2?

### CODE REVIEW

**Comment by agramfort** [comment]
thx a lot @larsoner 

can you take care of pushing to pypi?

**Comment by cbrnr** [comment]
If there is still time, it'd be great if you also included #6429 (then I could immediately use this in MNELAB).

**Comment by agramfort** [comment]
please open PRs asap before we push in pypi

**Comment by cbrnr** [comment]
Never mind, I can't figure out how to quickly pick the relevant commits and rebase only these onto `maint/0.18`, so please just go ahead and make the release. Maybe next time I'll know how to do that.

**Comment by cbrnr** [comment]
OK, I figured it out: #6450

**Pull request merged**
