### PR TITLE
fix EDF reader

### PR DESCRIPTION
**Pull request by drammock**
- converts "missing channel type" warning to `logger.info`
- fixes bug where all channel `loc` fields in the info pointed to the same object in memory (so that when setting montage, all channels get the coords of whichever channel came last)
- updates sleep tutorial to reflect new channel name behavior
- fix the logic so that if user specifies `stim_channel` or `misc` args to `read_raw_edf` they don't get spurious warnings about unidentified channel types

### CODE REVIEW

**Review by larsoner — APPROVED** [review]
@adam2392 can you look ?

**Comment by adam2392** [comment]
This LGTM for the EDF reader part!

**Comment by drammock** [comment]
this is still missing a test that would have caught the previous error.  probably something in `mne/io/tests/test_meas_info.py`... I'll try to get to that before I sign off today

**Comment by larsoner** [comment]
Maybe `mne/io/tests/test_raw.py` in `_test_raw_reader`? That gets run by all `mne/io/*` readers

**Comment by drammock** [comment]
locally the smoke test fails on main and passes on this branch, so assuming CIs all go green this is ready for merge.

**Review by larsoner — APPROVED** [review]
LGTM, whoever sees green first feel free to merge

**Comment by drammock** [comment]
hmm, all green except for a timeout on Windows 3.9 conda 🤷🏻

**Comment by larsoner** [comment]
Thanks @drammock

**Pull request merged**
