### PR TITLE
[MAINT, MRG] Add params to csd_tfr

### PR DESCRIPTION
**Pull request by alexrockhill**
When I took out `kwargs` in this PR #10986, I really needed to put back in some of the args. This is just cleaning that up.

### CODE REVIEW

**Comment by alexrockhill** [comment]
Same unrelated failures related to EEGLAB exports

**Review by agramfort — COMMENTED** [review]
should you need to update any test?

**Comment by alexrockhill** [comment]
> should you need to update any test?

Sure, good point!

**Comment by larsoner** [comment]
Thanks @alexrockhill !

**Pull request merged**
