### PR TITLE
[MAINT, MRG] Fix Dipy link

### PR DESCRIPTION
**Pull request by alexrockhill**
Related to https://github.com/dipy/dipy/issues/2483. This will keep the documentation link to `Dipy` from going out of date every release.

### CODE REVIEW

**Comment by larsoner** [comment]
Next time can you push doc-build-only changes like this with `[skip azp] [skip actions]`? Then only CircleCI will run and save some cycles

**Review by larsoner — CHANGES_REQUESTED** [review]
https://38024-1301584-gh.circle-artifacts.com/0/dev/generated/mne.transforms.compute_volume_registration.html#mne.transforms.compute_volume_registration points to https://dipy.org/documentation/1.4.1./documentation/reference/dipy.align/#dipy.align.imwarp.DiffeomorphicMap which is a 404.

On main https://mne.tools/dev/generated/mne.transforms.compute_volume_registration.html#mne.transforms.compute_volume_registration points to https://dipy.org/documentation/1.4.0./reference/dipy.align/#dipy.align.imwarp.DiffeomorphicMap which is not 404. So we should not merge this until they fix their intersphinx (at least I think this is the problem?)

**Comment by alexrockhill** [comment]
I think it's just that https://dipy.org/documentation/1.4.1./documentation/ is the documentation landing page but https://dipy.org/documentation/1.4.1. is a 404. I changed it to the one that was an actual landing page but I think even though the link doesn't work by itself, it works with intersphinx.

**Comment by larsoner** [comment]
Can you push a commit (can be empty with `--allow-empty`) with `[skip azp] [skip actions]`? Locally with `make html_dev-noplot` are things fixed?

**Comment by alexrockhill** [comment]
I tested this locally and it works, apparently the `/` at the end of the web address is vital. Anyway should be good to go now.

**Comment by alexrockhill** [comment]
Just checked and the link works here as well https://38076-1301584-gh.circle-artifacts.com/0/dev/generated/mne.transforms.compute_volume_registration.html?highlight=compute_vol#mne.transforms.compute_volume_registration

**Comment by larsoner** [comment]
Thanks @alexrockhill !

**Pull request merged**
