### PR TITLE
MRG: Fix regression type

### LINKED ISSUE #3084: Kind mismatch with Evoked
I think the wrong flag is being written for evokeds. It is saving evokeds with the` standard_error` for kind instead of `average`. Also there is a mismatch in the name, `evoked.kind` should be `average`, not `mean` according to `_aspect_rev`.

```python
In [36]: evs = [rerf['word/prime/primed'], rerf['word/prime/unprimed']]

In [37]: evs[0]
Out[37]: <Evoked  |  comment : 'word/prime/primed', kind : mean, time : [-0.200000, 1.000000], n_epochs : 44, n_channels x n_times : 208 x 601>

In [38]: evs[0].kind
Out[38]: 'mean'

In [39]: mne.write_evokeds('/Users/teon/Desktop/test-ave.fif', evs)

In [40]: evs = mne.read_evokeds('/Users/teon/Desktop/test-ave.fif')
Reading /Users/teon/Desktop/test-ave.fif ...
    Read a total of 1 projection items:
        axial--0.100-0.030-PCA-01 (1 x 208) active
    Found the data of interest:
        t =    -200.00 ...    1000.00 ms (word/prime/primed)
        0 CTF compensation matrices available
        nave = 44 - aspect type = 101
Projections have already been applied. Setting proj attribute to True.
No baseline correction applied
    Read a total of 1 projection items:
        axial--0.100-0.030-PCA-01 (1 x 208) active
    Found the data of interest:
        t =    -200.00 ...    1000.00 ms (word/prime/unprimed)
        0 CTF compensation matrices available
        nave = 44 - aspect type = 101
Projections have already been applied. Setting proj attribute to True.
No baseline correction applied

In [41]: evs[0]
Out[41]: <Evoked  |  comment : 'word/prime/primed', kind : standard_error, time : [-0.200000, 1.000000], n_epochs : 44, n_channels x n_times : 208 x 601>

In [42]: evs[0].kind
Out[42]: 'standard_error'
```

### PR DESCRIPTION
**Pull request by Eric89GXL**
Closes #3084.

Ready for review/merge from my end.

### CODE REVIEW

**Comment by jaeilepp** [comment]
Travis is unhappy.

**Comment by Eric89GXL** [comment]
Travis is happy now

**Comment by agramfort** [comment]
thx @Eric89GXL !

**Comment by jona-sassenhagen** [comment]
Thanks Eric

**Pull request merged**
