### PR TITLE
WIP: Fix broken examples

### PR DESCRIPTION
**Pull request by larsoner**
From `git grep read_montage` I suspect that the examples modified here will fail now that #6765 is in. I hopefully fixed two of the three but left the last one with mismatched channel names for you @massich since I'm not sure what the plan was for this case.

### CODE REVIEW

**Comment by larsoner** [comment]
Looks like there are more broken examples than I thought, @massich can you look?

https://circleci.com/gh/mne-tools/mne-python/15468

**Comment by larsoner** [comment]
(looks like 9 total broken)

**Comment by massich** [comment]
I find more readable the dictionary. Its like a constant. Totally explicit. If we want to do it programatically, it can be done. But then I would hide it into a function in the dataset:

```py
raw.rename_channels(eegbci.eegbci_names_to_mne)
```

**Comment by agramfort** [comment]
Ok don’t touch then

**Comment by agramfort** [comment]
ok circle was happy !

now we need to rebase #6791

I don't know about #6764

**Pull request merged**
