### PR TITLE
MRG, BUG: _Renderer not found

### PR DESCRIPTION
**Pull request by larsoner**
Okay I remember why I went with `_get_renderer` (which was removed in #7292). @GuillaumeFavelier this code snippet:
```
import mne
mne.viz.create_3d_figure((800, 600))
```
gives:
```
Traceback (most recent call last):
  File "/Users/larsoner/Desktop/bug.py", line 2, in <module>
    mne.viz.create_3d_figure((800, 600))
  File "/Users/larsoner/python/mne-python/mne/viz/backends/renderer.py", line 245, in create_3d_figure
    renderer = _Renderer(fig=handle, size=size, bgcolor=bgcolor)  # noqa: F821
NameError: name '_Renderer' is not defined
```
We don't hit this in tests (and CircleCI) probably because by the time we call a `create_3d_figure` we have already done a `stc.plot` or something else that would have loaded a backend (or tried to load the given backend in a `pytest` way).

The simplest fix is probably to restore `_get_renderer`, but I leave it up to you to figure out @GuillaumeFavelier. In the meantime I've added a test to replicate the problem. Feel free to push directly to my branch to fix.

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
Good catch @larsoner.

 `_get_renderer` is still here:

https://github.com/mne-tools/mne-python/blob/26d0bfc879e41389bda7539037660b97b45d802b/mne/viz/backends/renderer.py#L37-L39

The goal of #7292 was just to have lazy loading of the 3d backend to avoid reloading more than necessary but I probably forgot to refactor `create_3d_figure` in the process, my bad. It still uses `_Renderer` instead of `_get_renderer`:

https://github.com/mne-tools/mne-python/blob/26d0bfc879e41389bda7539037660b97b45d802b/mne/viz/backends/renderer.py#L245-L246

**Comment by GuillaumeFavelier** [comment]
I could not figure how to push directly so I opened https://github.com/larsoner/mne-python/pull/36 😅

image

I don't think I have the right to do that, do I?

**Comment by larsoner** [comment]
If you have commit rights to this repo you should be able to. Is my remote URL in got remote -v prefixed with got://, https://, or git@github.com ?

**Comment by GuillaumeFavelier** [comment]
It's prefixed by `https://`:

```
$ git remote -v
...
larsoner	https://github.com/larsoner/mne-python.git (fetch)
larsoner	https://github.com/larsoner/mne-python.git (push)
```

**Comment by GuillaumeFavelier** [comment]
> If you have commit rights to this repo you should be able to

Solved now, thank you!

**Comment by GuillaumeFavelier** [comment]
The CIs are basically happy except one [Travis job](https://travis-ci.org/mne-tools/mne-python/jobs/654879569?utm_medium=notification&utm_source=github_status) which got timeout during uploading. It was so close.

Should we consider disabling `smooth_shading` for example as a cheap way to speedup the viz tests?

I also notice `test_plot_alignment[pyvista]` is among the slowest tests for some reason.

**Comment by larsoner** [comment]
> Should we consider disabling smooth_shading for example as a cheap way to speedup the viz tests?

No that build fails just because of https://github.com/numpy/numpy/issues/15580, we just need to wait for NumPy to fix it.

**Comment by larsoner** [comment]
@GuillaumeFavelier I improved the test, will merge once CIs come back happy

**Pull request merged**
