### PR TITLE
add doc build make targets for nightly build

### PR DESCRIPTION
**Pull request by agramfort**
@Eric89GXL feel free to take over. It does not work yet.

Once this works it means we update the website with

```
cd mne-python
make build-doc-dev
cd ../mne-tools.github.io
make pull
make copy-dev
make push
```

### CODE REVIEW

**Comment by Eric89GXL** [comment]
What doesn't work, the `xvfb-run` command?

**Comment by agramfort** [comment]
not sure.

does it work for you?

I tried on our common machine and got:

DISPLAY=:1 xvfb-run -f /tmp/xauthority-mne-python-doc --auto-servernum -s
"-screen 0 1280x1024x24 -noreset"  make html_dev
make: *** [build-doc-dev] Error 1

**Comment by Eric89GXL** [comment]
I have never tried to use `xvfb-run`, I might be able to look today

**Comment by Eric89GXL** [comment]
Docs built, go ahead and do `make pull && make copy-dev && make push`. I can't `pull` or `push` because those directories have you as the `git` login.

We should also add an option to the doc building that makes it so that any errors it occurs actually stops the build. As it stands, I can't tell if the build completed successfully or not (remotely) without a push.

**Comment by agramfort** [comment]
done

https://mne-tools.github.io/dev/

please go over the examples to see if you see any issue.

if Ok I think we can release. See:

https://github.com/mne-tools/mne-python/wiki/How-to-make-a-release

ping me if you need any help

once the web site with stable / dev is pushed github we can update martinos
and send the announcement email.

**Comment by Eric89GXL** [comment]
@agramfort can you push the doc-building commit to this PR that contains the code I added plus anything else you tweaked since then?

**Comment by Eric89GXL** [comment]
@agramfort the API reference is borked:

http://mne-tools.github.io/dev/python_reference.html

**Comment by Eric89GXL** [comment]
The builds are fine on my Ubuntu system (system python + custom builds) but I have the same issue on Windows, so this is probably a problem with `conda` since your build system also uses that

**Comment by agramfort** [comment]
GRRRR !!! sphinx problem? are you using sphinx maser?

**Comment by Eric89GXL** [comment]
I don't think so, I'll try updating and see if it breaks

**Comment by Eric89GXL** [comment]
installing latest master also broke it for me, I'll see if some older version works

**Comment by Eric89GXL** [comment]
at least d3615d does, going to `bisect` and open a Sphinx issue

**Comment by Eric89GXL** [comment]
@agramfort you can:
```
git clone git://github.com/sphinx-doc/sphinx.git
cd sphinx
git checkout b9fe829
python setup.py develop
```
And that should give you something that will actually build our docs for now. See: https://github.com/sphinx-doc/sphinx/issues/1891

**Comment by Eric89GXL** [comment]
PR sent:

https://github.com/sphinx-doc/sphinx/pull/1892

**Comment by Eric89GXL** [comment]
@agramfort if you want, you can set up your build bot to use my branch for now, and you should be good to go. If you install with `python setup.py develop` then when it gets merged upstream you can just switch and pull.

**Comment by agramfort** [comment]
fixed :

https://mne-tools.github.io/dev/python_reference.html

at least on dev

**Comment by Eric89GXL** [comment]
ping @agramfort please push your changes on your build system to this PR. it will need a rebase now BTW

**Comment by Eric89GXL** [comment]
Oh never mind, it looks like you've pushed them to `master` already. closing

**Pull request closed without merging**
