### PR TITLE
ENH: different color for each volume source space

### PR DESCRIPTION
**Pull request by vagechirkov**
Reference issue #5111.

Plot volumic source space with Freesurfer LUT colors.

### CODE REVIEW

**Comment by rob-luke** [comment]
I couldnt see why the single CI failed. So I have just restarted it, lets see if it works this time.

**Comment by rob-luke** [comment]
Yep CI's all green now 😄.

**Comment by larsoner** [comment]
This is still marked as a draft, is it ready to go @vagechirkov ?

**Comment by vagechirkov** [comment]
> This is still marked as a draft, is it ready to go @vagechirkov ?

There was an error, now it should work. Should I create a test before converting to the normal pull request?

**Comment by vagechirkov** [comment]
@larsoner I think there are no tests for mixed source space ```test_plot_alignment``` function. Should I add them?

**Comment by larsoner** [comment]
Yes you can use the [`mixed_fwd_cov_evoked` fixture](https://github.com/mne-tools/mne-python/blob/main/mne/conftest.py#L461), and use `mixed_fwd_cov_evoked[0]['src']`. It should have a mixed source space with two (I think?) volumes. Something like this should work:
```
def test_plot_alignment(..., mixed_fwd_cov_evoked):
    ...
    mixed_src = mixed_fwd_cov_evoked[0]['src']
    assert mixed_src.kind == 'mixed'
    plot_alignment(..., src=mixed_src)
```

**Review by agramfort — APPROVED** [review]
looks good

https://26131-1301584-gh.circle-artifacts.com/0/dev/auto_examples/inverse/plot_mixed_source_space_inverse.html#sphx-glr-auto-examples-inverse-plot-mixed-source-space-inverse-py

@larsoner I let you merge if happy

thx @vagechirkov

**Comment by agramfort** [comment]
@vagechirkov you need to fix a conflict. thx

**Comment by larsoner** [comment]
Thanks @vagechirkov !

**Pull request merged**
