### PR TITLE
MAINT: Refactor and simplify AA settings and tests

### PR DESCRIPTION
**Pull request by larsoner**
In theory this should work, will check examples to make sure they render okay.

### CODE REVIEW

**Comment by larsoner** [comment]
... they do not, so I'll have to investigate a bit

**Comment by larsoner** [comment]
So it turns out that when using MESA we can't actually enable MSAA because we need depth peeling, and they don't play well together (https://github.com/pyvista/pyvista/issues/4867). So this PR just cleans up our `pyvista` code a bit and removes some cruft. So I'll look at the example output to make sure it matches [current dev](https://mne.tools/dev/auto_tutorials/inverse/50_beamformer_lcmv.html#volumetric-rendering-3d-with-vectors) and then merge.

**Review by drammock — APPROVED** [review]
looks good!  Do you need to check Circle tutorial rendering before merge, or OK to auto-merge?

**Comment by drammock** [comment]
https://output.circle-artifacts.com/output/job/99382345-7f99-4dd8-ae71-a03aad089dd9/artifacts/0/html/auto_tutorials/forward/50_background_freesurfer_mne.html#sphx-glr-auto-tutorials-forward-50-background-freesurfer-mne-py

https://output.circle-artifacts.com/output/job/99382345-7f99-4dd8-ae71-a03aad089dd9/artifacts/0/html/auto_tutorials/inverse/50_beamformer_lcmv.html#sphx-glr-auto-tutorials-inverse-50-beamformer-lcmv-py

these look OK to me...

**Comment by larsoner** [comment]
I looked and think it's okay so enabled auto-merge already :+1:

**Pull request merged**
