### PR TITLE
[MRG] Autoselect ch type

### PR DESCRIPTION
**Pull request by jaeilepp**
Take over from https://github.com/mne-tools/mne-python/pull/2336.

### CODE REVIEW

**Comment by agramfort** [comment]
travis is not happy

**Comment by jaeilepp** [comment]
The errors seem unrelated. Tests pass on my computer.

**Comment by agramfort** [comment]
I restarted travis

**Comment by Eric89GXL** [comment]
Ahh, we're getting that error in multiple places. Probably because there is a new `numpy` release that is more strict. I'll open a PR to fix it.

**Comment by Eric89GXL** [comment]
fixed, go ahead and rebase and you should be good

**Comment by agramfort** [comment]
let us know when travis is green

**Comment by jaeilepp** [comment]
Again, looks like an unrelated test failure.

**Comment by Eric89GXL** [comment]
build restarted, will merge when it comes back green

**Comment by Eric89GXL** [comment]
Thanks @jaeilepp

**Pull request merged**
