### PR TITLE
less stringent check in _construct_bids_filename (req by derivatives)

### PR DESCRIPTION
**Pull request by agramfort**
following issues in mne study template as we write files called

_split-01_raw.fif 

in the derivatives folder.

### CODE REVIEW

**Comment by larsoner** [comment]
Style is unhappy, and we need a little test. You need help @agramfort ?

**Comment by agramfort** [comment]
error is unrelated https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=9906&view=logs&j=3f85e25b-fb23-5eb7-8385-51966a33df73&t=f34216fe-b66f-5dbd-2d4d-edccd28174d8

**Comment by larsoner** [comment]
Still needs a test

**Comment by agramfort** [comment]
thx heaps @larsoner !

**Pull request merged**
