### PR TITLE
Remove constrain on vtk version for windows

### LINKED ISSUE #10099: VTK version with python 3.9 and windows
I have set up a new venv on a different windows laptop for MNE and I wanted to move from Python 3.8.10 to 3.9.9. 
When doing `py -m pip install -r requirements.txt`, the installation fails because there are no wheels on Pypi for `vtk<=9.0.1` for windows/Python 3.9.
I installed version 9.1.0 instead; and for now, at least, I didn't notice any issues with MNE. I couldn't run yet the test suite as my battery died.. but if you have some tests in mind to make sure version 9.1.0 works fine; I can run them tomorrow. 

Maybe the requirement `vtk<=9.0.1; platform_system == "Windows"` is outdated?

### PR DESCRIPTION
**Pull request by mscheltienne**
Test if VTK version still needs to be constrained for Windows.

Closes #10099

### CODE REVIEW

**Review by larsoner — APPROVED** [review]
LGTM let's merge assuming CIs come back happy

**Comment by larsoner** [comment]
I killed CircleCI -- I don't think we need `circle full` because it doesn't use Windows / shouldn't be affected by this change

**Comment by mscheltienne** [comment]
Sure, I thought maybe some viz examples might show a failure.

**Comment by larsoner** [comment]
I had an idea how to possibly fix the Windows failure so I pushed it. We'll see if it works. If it doesn't, I can boot my Windows VM and test more directly.

**Comment by larsoner** [comment]
Argh okay, I'll have to actually test it out in Windows. I'll probably get to it tomorrow unless you beat me to it @mscheltienne

**Comment by mscheltienne** [comment]
I'll give it a shot, but I doubt I will figure that one out :) 
The failure looks limited; I think it would be worth spending the time to figure it out and to fix it to simplify the requirements.

**Comment by mscheltienne** [comment]
The test failing was 3.7 with pip, right? Do you know why 3.9 with pip was working? Locally, I had a failure for `test_renderer.py` with VTK 9.1.0 and python 3.9.9.

**Comment by mscheltienne** [comment]
Never mind, I just saw the safer close in `pyvistaqt`, the problem makes sense now.

**Comment by larsoner** [comment]
Thanks @mscheltienne !

**Pull request merged**
