### PR TITLE
RF: Change viz backend loading

### PR DESCRIPTION
**Pull request by hoechenberger**
When working on https://github.com/mne-tools/mne-bids/pull/376, which effectively turns all warnings into errors that make our unit tests fail, I discovered that `mne.viz.backends.renderer`
would always produce this odd warning:

```python
<frozen importlib._bootstrap>:1072: in _calc___package__
    ???
E   ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
        globals    = {'__name__': 'mne.viz.backends.renderer'}
        package    = None
        spec       = None
```

I found out that this is related to using `importlib.__import__()` for loading the required backend module. I have now switched the relevant code to `importlib.load_module()`, which makes
the warning disappear at least locally (Python 3.8, macOS).

### CODE REVIEW

**Comment by hoechenberger** [comment]
@GuillaumeFavelier btw why do you import all those functions into the global namespace? Couldn't they safely live in `_mod.xxx`? Or, maybe, `backend.xxx`...

**Comment by GuillaumeFavelier** [comment]
The way to import and reload the 3d backends is very different from it's first version. It grew more and more complicated as more features got added and the design of `renderer` got closer to it's end goal of being a backend-agnostic tool.

About:

```py
_fromlist = ('_Renderer', '_Projection', '_close_all', '_check_3d_figure',
             '_set_3d_view', '_set_3d_title', '_close_3d_figure',
             '_take_3d_screenshot', '_testing_context')
```

The implementation of these functions are different for each 3d backend and they need to be reloaded dynamically following the currently selected backend. Also, some of them are used in `mne/viz/backends/renderer.py` especially by their public counterpart `set_3d_view`, `set_3d_title`.

Your suggestions are really welcome! In particular if you know any way to simplify this part of the code.

I tested this PR and this [script](https://gist.github.com/GuillaumeFavelier/c6dcf2916bf1d1057c6f542af4f3fe03) fails here but not on `master`.

**Comment by hoechenberger** [comment]
Thanks @GuillaumeFavelier, will look into this.

**Comment by hoechenberger** [comment]
@GuillaumeFavelier Do you have a reference to a branch of yours where the change would break stuff?

**Comment by GuillaumeFavelier** [comment]
Very exciting changes, I don't have the issue with my script now. I will test more thoroughly

**Comment by hoechenberger** [comment]
If this works and CIs go green, we could have this in 0.20, as @larsoner suggested.

**Comment by larsoner** [comment]
Locally when I run:
```
pytest mne/viz --tb=short
```
I see a lot of:
```
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― ERROR at teardown of test_brain_init[mayavi] ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
mne/conftest.py:230: in renderer
    renderer._close_all()
E   AttributeError: module 'mne.viz.backends.renderer' has no attribute '_close_all'
```

**Comment by hoechenberger** [comment]
@larsoner Thx will look into this.

**Comment by GuillaumeFavelier** [comment]
One way to fix this would be to use `renderer.backend` instead of `renderer` directly: 

`git grep "renderer\._"`:

<details>

```diff
diff --git a/mne/conftest.py b/mne/conftest.py
index 5d34df1be..b93203800 100644
--- a/mne/conftest.py
+++ b/mne/conftest.py
@@ -227,7 +227,7 @@ def renderer(backend_name, garbage_collect):
     with _use_test_3d_backend(backend_name):
         from mne.viz.backends import renderer
         yield renderer
-        renderer._close_all()
+        renderer.backend._close_all()
 
 
 @pytest.yield_fixture
@@ -254,7 +254,7 @@ def renderer_interactive(backend_name_interactive):
     with _use_test_3d_backend(backend_name_interactive, interactive=True):
         from mne.viz.backends import renderer
         yield renderer
-        renderer._close_all()
+        renderer.backend._close_all()
 
 
 def _check_skip_backend(name):
diff --git a/mne/viz/backends/tests/test_renderer.py b/mne/viz/backends/tests/test_renderer.py
index 4b3aca2ab..ec3d20f4a 100644
--- a/mne/viz/backends/tests/test_renderer.py
+++ b/mne/viz/backends/tests/test_renderer.py
@@ -45,14 +45,14 @@ def test_3d_functions(renderer):
     """Test figure management functions."""
     fig = renderer.create_3d_figure((300, 300))
     # Mayavi actually needs something in the display to set the title
-    wrap_renderer = renderer._Renderer(fig=fig)
+    wrap_renderer = renderer.backend._Renderer(fig=fig)
     wrap_renderer.sphere(np.array([0., 0., 0.]), 'w', 1.)
-    renderer._check_3d_figure(fig)
-    renderer._set_3d_view(figure=fig, azimuth=None, elevation=None,
-                          focalpoint=(0., 0., 0.), distance=None)
-    renderer._set_3d_title(figure=fig, title='foo')
-    renderer._take_3d_screenshot(figure=fig)
-    renderer._close_all()
+    renderer.backend._check_3d_figure(fig)
+    renderer.backend._set_3d_view(figure=fig, azimuth=None, elevation=None,
+                                  focalpoint=(0., 0., 0.), distance=None)
+    renderer.backend._set_3d_title(figure=fig, title='foo')
+    renderer.backend._take_3d_screenshot(figure=fig)
+    renderer.backend._close_all()
 
 
 def test_3d_backend(renderer):
@@ -102,7 +102,7 @@ def test_3d_backend(renderer):
     cam_distance = 5 * tet_size
 
     # init scene
-    rend = renderer._Renderer(size=win_size, bgcolor=win_color)
+    rend = renderer.backend._Renderer(size=win_size, bgcolor=win_color)
     rend.set_interactive()
 
     # use mesh
diff --git a/mne/viz/tests/test_3d.py b/mne/viz/tests/test_3d.py
index 890fd7dfb..ca256eebd 100644
--- a/mne/viz/tests/test_3d.py
+++ b/mne/viz/tests/test_3d.py
@@ -177,7 +177,7 @@ def test_plot_alignment(tmpdir, renderer):
             'r': [0.08436285, -0.02850276, -0.04127743]}]
     write_dig(fiducials_path, fid, 5)
 
-    renderer._close_all()
+    renderer.backend._close_all()
     evoked = read_evokeds(evoked_fname)[0]
     sample_src = read_source_spaces(src_fname)
     bti = read_raw_bti(pdf_fname, config_fname, hs_fname, convert=True,
@@ -194,10 +194,10 @@ def test_plot_alignment(tmpdir, renderer):
             meg.append('ref')
         fig = plot_alignment(info, read_trans(trans_fname), subject='sample',
                              subjects_dir=subjects_dir, meg=meg)
-        rend = renderer._Renderer(fig=fig)
+        rend = renderer.backend._Renderer(fig=fig)
         rend.close()
     # KIT ref sensor coil def is defined
-    renderer._close_all()
+    renderer.backend._close_all()
     info = infos['Neuromag']
     pytest.raises(TypeError, plot_alignment, 'foo', trans_fname,
                   subject='sample', subjects_dir=subjects_dir)
@@ -208,9 +208,9 @@ def test_plot_alignment(tmpdir, renderer):
                   src=sample_src)
     sample_src.plot(subjects_dir=subjects_dir, head=True, skull=True,
                     brain='white')
-    renderer._close_all()
+    renderer.backend._close_all()
     # no-head version
-    renderer._close_all()
+    renderer.backend._close_all()
     # all coord frames
     pytest.raises(ValueError, plot_alignment, info)
     plot_alignment(info, surfaces=[])
@@ -219,7 +219,7 @@ def test_plot_alignment(tmpdir, renderer):
                              coord_frame=coord_frame, trans=Path(trans_fname),
                              subject='sample', mri_fiducials=fiducials_path,
                              subjects_dir=subjects_dir, src=src_fname)
-    renderer._close_all()
+    renderer.backend._close_all()
     # EEG only with strange options
     evoked_eeg_ecog_seeg = evoked.copy().pick_types(meg=False, eeg=True)
     evoked_eeg_ecog_seeg.info['projs'] = []  # "remove" avg proj
@@ -231,7 +231,7 @@ def test_plot_alignment(tmpdir, renderer):
                        surfaces=['white', 'outer_skin', 'outer_skull'],
                        meg=['helmet', 'sensors'],
                        eeg=['original', 'projected'], ecog=True, seeg=True)
-    renderer._close_all()
+    renderer.backend._close_all()
 
     sphere = make_sphere_model(info=evoked.info, r0='auto', head_radius='auto')
     bem_sol = read_bem_solution(op.join(subjects_dir, 'sample', 'bem',
@@ -279,7 +279,7 @@ def test_plot_alignment(tmpdir, renderer):
     fig = plot_alignment(trans=trans_fname, subject='sample', meg=False,
                          coord_frame='mri', subjects_dir=subjects_dir,
                          surfaces=['brain'], bem=sphere, show_axes=True)
-    renderer._close_all()
+    renderer.backend._close_all()
     if renderer.get_3d_backend() == 'mayavi':
         import mayavi  # noqa: F401 analysis:ignore
         assert isinstance(fig, mayavi.core.scene.Scene)
@@ -340,7 +340,7 @@ def test_plot_alignment(tmpdir, renderer):
     log = log.getvalue()
     assert '26 fnirs locations' in log
 
-    renderer._close_all()
+    renderer.backend._close_all()
 
 
 @pytest.mark.slowtest  # can be slow on OSX
@@ -520,7 +520,7 @@ def test_plot_dipole_orientations(renderer):
         dipoles.plot_locations(trans=trans, subject='sample',
                                subjects_dir=subjects_dir,
                                mode=mode, coord_frame=coord_frame)
-    renderer._close_all()
+    renderer.backend._close_all()
 
 
 @testing.requires_testing_data
```

</details>

**Comment by hoechenberger** [comment]
@larsoner Does this need a changelog entry?

Otherwise, should be good to merge!

**Comment by larsoner** [comment]
No need it's within-cycle added/changed functionality, thanks @hoechenberger

**Pull request merged**
