### PR TITLE
FIX: Fix plot_topomap with bads

### LINKED ISSUE #7213: BUG: Viz Topomap Produces ValueError Always Due to Cardinal Dig
## Describe the bug

In `mne.viz.topomap(data, info)`, I get an error in the latest version:

```
ValueError: Number of channels in the Info object and the data array does not match. Pick Info with e.g. mne.pick_info and mne.io.pick.channel_indices_by_type.
```

#### Steps to reproduce
If I run the following code:

```
from pprint import pprint

montage = mne.channels.make_standard_montage("standard_1020")
raw.set_montage(montage)
info = raw.info
pprint(info['dig'])
```

You'll notice that we have extra DigPoints.

#### Expected results
It should work as before (I think ~v0.19?) where it just plotted the topomap as long as the data shape matched.

If you use `mne.viz.plot_sensors`, it works as expected and only plots the EEG sensors.

### PR DESCRIPTION
**Pull request by larsoner**
Closes #7213

### CODE REVIEW

**Comment by adam2392** [comment]
This looks good! Thanks for such a quick PR. I would've been down to make one :p

**Comment by larsoner** [comment]
Ahh sorry about that @adam2392 I should have asked first, lost myself in the joy of bug fixing :)

**Comment by mmagnuski** [comment]
Oh, the "joy" of bug fixing 😆 
BTW, I thought that bads are excluded in plot_topomap because Evoked and other higher-level objects remove bads when passing values to plot_topomap, but it seems it's not the case. :)

**Comment by larsoner** [comment]
They should, they pick earlier than the call to `plot_topomap`:

https://github.com/mne-tools/mne-python/blob/master/mne/viz/topomap.py#L98-L109

**Comment by mmagnuski** [comment]
@larsoner Yes, but they pick `pos` on their own, so no problem. I originally thought that fixing this plot_topomap behavior would require changing how all these objects handle picking values and infos in their `.plot_topomap()` methods, but luckily thats not required. :)

**Comment by agramfort** [comment]
Thx @larsoner

**Pull request merged**
