### PR TITLE
ENH: Multiple raw instance support to head pos average

### PR DESCRIPTION
**Pull request by larsoner**
Needed for https://github.com/mne-tools/mne-bids-pipeline/issues/574

### CODE REVIEW

**Comment by larsoner** [comment]
All green, ready from my end @drammock !

**Review by agramfort — APPROVED** [review]

**Comment by agramfort** [comment]
thx @larsoner !

**Comment by drammock** [comment]
looks like this got merged while I was reviewing... feel free to ignore my comments (they were very minor / nitpicks anyway)

**Comment by agramfort** [comment]
oups :)

**Comment by drammock** [comment]
> oups :)

it's fine, no way you could have known!

**Pull request merged**
