### PR TITLE
ENH: Build API entry usage graphs

### PR DESCRIPTION
**Pull request by larsoner**
Toward https://github.com/mne-tools/mne-python/issues/11114, let's see if we can even get a graph to show and if it looks okay. If we can't, we should just close https://github.com/mne-tools/mne-python/issues/11114 since the feature will not be usable for us.

If it does look okay, I'll add it to the docs somewhere and we can merge.

### CODE REVIEW

**Comment by larsoner** [comment]
@drammock ready for review/merge from my end

https://output.circle-artifacts.com/output/job/ebae1e27-a0ed-4229-a48d-2e7114b49bfd/artifacts/0/html/sg_api_usage.html

It's not perfect but it does give us some targets for things to add. After this is merged we can create a new issue, mark it as easy, and link to the `mne.tools/dev` version of the page.

**Review by drammock — APPROVED** [review]
Nice addition. Some comments:

1. graph is basically unusable because the nodes are so small and spread out. Does the SG API let you adjust `nodesep` or other graphviz params?

2. It's interesting to note that this has similar problems as the minigallery directive. Minigallery will (sometimes! not always) link from an API entry to a tutorial even if the func/meth/class is merely *mentioned* in the rST prose of the tutorial (i.e. not actually used in the executed code). An example is the [mne.viz.plot_topomap minigallery](https://mne.tools/dev/generated/mne.viz.plot_topomap.html#examples-using-mne-viz-plot-topomap)'s link to the [working with sensor locations](https://mne.tools/dev/auto_tutorials/intro/40_sensor_locations.html) tutorial. An example where a method gets zero minigallery entries (despite mention in a tutorial) is [Epochs.del_proj()](https://mne.tools/dev/generated/mne.Epochs.html#mne.Epochs.del_proj), which is mentioned in the [Epochs overview tutorial](https://mne.tools/dev/auto_tutorials/epochs/10_epochs_overview.html). It even sometimes fails to create a minigallery link when the API element is in executed code, as in [Label.center_of_mass](https://mne.tools/dev/generated/mne.Label.html#mne.Label.center_of_mass) which gets no minigallery but is used in [the point spread tutorial](https://mne.tools/dev/auto_tutorials/simulation/70_point_spread.html) The "unused API entries" appears to have similar (the same?) problems.

**Comment by drammock** [comment]
feel free to merge if you don't want to address those points / if they're best addressed upstream in SG (they probably are)

**Comment by larsoner** [comment]
... except the node stuff. That we could probably change with this in `conf.py`:
```
graphviz_dot_args
Additional command-line arguments to give to dot, as a list. The default is an empty list.
This is the right place to set global graph, node or edge attributes via dot’s -G, -N and -E options.
```

**Comment by larsoner** [comment]
With defaults I get:

Screenshot from 2023-09-26 12-27-18

With a bunch of stuff tweaked I get:

Screenshot from 2023-09-26 13-52-52

Visible here:

https://output.circle-artifacts.com/output/job/2383cbc7-250a-41c5-9f8b-32d51f73f904/artifacts/0/html/sg_api_usage.html

It's not perfect (there is some overlap) but it seems much more usable/readable.

**Comment by drammock** [comment]
much better, thanks!

**Pull request merged**
