### PR TITLE
Rename get_edf_events to find_edf_events

### LINKED ISSUE #4497: Rename and relocate `get_edf_events`
I just noticed that we now have a new function `mne.io.get_edf_events`, which is used to extract events from the EDF family. I was thinking two things:  
1. shouldn't this belong at the top level mne. The logic behind this is that we have the function `mne.find_events` which exists there. 
2. this should be renamed `find_edf_events` to follow the naming pattern.

### PR DESCRIPTION
**Pull request by cbrnr**
Fix #4497

### CODE REVIEW

**Comment by agramfort** [comment]
did you go:

git grep get_edf_events

so see if all occurences are gone

**Comment by cbrnr** [comment]
Yes, now all occurrences are replaced.

**Comment by agramfort** [comment]
LGTM

@jona-sassenhagen ok for you?

**Comment by jona-sassenhagen** [comment]
Did you mean to ping @teonbrooks ? I don't use EDF really ... Looks ok to me though.

**Comment by agramfort** [comment]
arff I though you were an EDF expert @jona-sassenhagen :)

let's merge when green

**Comment by jona-sassenhagen** [comment]
Do you think all EEG people are the same? :D

(The only thing I'm an expert on is the German case system)

**Comment by agramfort** [comment]
thx @cbrnr

**Pull request merged**
