### PR TITLE
MRG: Minor fix for CTF systems

### LINKED ISSUE #2698: ctf2fif conversion problem
Hi guys, 
I am just starting to use mne-python on CTF data. I used the C tool mne_ctf2fif to convert the data ('mne_ctf2fif --ds data.ds/ --fif data01')
I have a .ds folder with the .meg4 file (ctf) of 1.11go and the resulting .fif file is only around 200mo. When I looked at the events, there is indeed more than three quarter of events missing. Nevertheless, it seems to work with smaller files (around 300mo). Is there a size limit? I am running under Apple el capitan on a macbookpro.
Thanks a lot!

### PR DESCRIPTION
**Pull request by Eric89GXL**
Closes #2698.

Unfortunately we don't have the files to add a test for this, but it works with the user's dataset.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
@agramfort ready for review/merge from my end.

BTW it looks like Travis for some reason passed for my first commit. I wonder if Anaconda had another nasty numpy/scipy bug crop up due to their old GCC build version that they had to fix.

**Comment by agramfort** [comment]
do you have any idea how this is handled in brainstorm or fieldtrip?

**Comment by Eric89GXL** [comment]
No, but I could look. Want me to do that before merge? I suspect the ignore
option will be useful regardless

**Comment by agramfort** [comment]
I agree but I am curious how BST or fieldtrip handle this case. We could
mimic their behavior to facilitate compat / API

**Comment by Eric89GXL** [comment]
Browsing the fieldtrip docs I don't see any mention of the system clock, and I can't find it in their code searching for things like "system", "clock", and "clk". Same with BrainStorm (nothing in tutorials/docs, nothing easily found in code).

**Comment by Eric89GXL** [comment]
In other words, I suspect that `ignore` is their behavior. We could eventually add a `read_epochs_ctf` function, too. They might have that sort of import functionality available.

**Comment by agramfort** [comment]
ok merging.

ping @ftadel if you have any comment to make :)

**Pull request merged**
