### PR TITLE
MRG, ENH: Add rank lines to plot_cov

### PR DESCRIPTION
**Pull request by larsoner**
Don't think we need to add a test given that the code paths should be checked by existing ones. Touched a tutorial so we could see an example output.

Also updated `_peak_finder.py` to log a bit more info, useful for debugging.

### CODE REVIEW

**Comment by larsoner** [comment]
https://15435-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/source-modeling/plot_compute_covariance.html#plot-the-covariance-matrices

**Comment by drammock** [comment]
nice!  Any reason not to write `rank ≈ 203` on the plot instead of just `203`?

**Comment by larsoner** [comment]
Nope, done

**Comment by larsoner** [comment]
https://15438-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/source-modeling/plot_compute_covariance.html#plot-the-covariance-matrices

**Comment by agramfort** [comment]
thx @larsoner !

**Pull request merged**
