### PR TITLE
Fix tessellate_sphere_surf.

### PR DESCRIPTION
**Pull request by jaeilepp**
``nuse`` was set to numpy.

### CODE REVIEW

**Comment by agramfort** [comment]
no test to update?

**Comment by jaeilepp** [comment]
I'm not sure how this effects anything.

**Comment by agramfort** [comment]
where is this used?

**Comment by jaeilepp** [comment]
It seems that even though ``nuse`` is intialized wrong here, it gets overwritten later in ``_create_surf_spacing``. So the test I added also passes on master. I suggest we just merge this.

**Comment by agramfort** [comment]
thx @jaeilepp

**Pull request merged**
