### PR TITLE
[DOC, MRG] Detail what picks=None does for ICA

### PR DESCRIPTION
**Pull request by mscheltienne**
Minor documentation improvement.

### CODE REVIEW

**Comment by mscheltienne** [comment]
Render: https://output.circle-artifacts.com/output/job/619b5c24-4922-4444-b143-2c33ddb573b3/artifacts/0/dev/generated/mne.preprocessing.ICA.html#mne.preprocessing.ICA.plot_components

**Comment by drammock** [comment]
Looking at the rendered docstring it seems to me like there is a subtle redundancy in the last 2 sentences (the one you added, and the one following it). Do you agree, and do you see an easy fix?

**Comment by mscheltienne** [comment]
Thanks for the double-check! It took so long to load the render that I barely looked at it, sorry! 
Fixed it by moving the description for ``None`` to the docdict entry instead of appending it to each `%(picks_ica)s`.

That change was motivated by getting rid of the same description appended here https://github.com/mne-tools/mne-icalabel/blob/33856dfc8401769f40ace9d924c771df190ad003/mne_icalabel/features/topomap.py#L31

**Comment by mscheltienne** [comment]
Do you want to keep the mention for `batch of 20` for the `plot_components` method?

**Comment by drammock** [comment]
> Do you want to keep the mention for `batch of 20` for the `plot_components` method?

Personally I don't think the "batches of 20" is so important to mention. 🤷🏻

**Review by drammock — APPROVED** [review]

**Review by agramfort — APPROVED** [review]

**Pull request merged**
