### PR TITLE
Add regression test for EEGLAB data with a chanlocs struct

### PR DESCRIPTION
**Pull request by hoechenberger**

### CODE REVIEW

**Comment by larsoner** [comment]
Usually we do this with whatever PR actually needs it

**Comment by hoechenberger** [comment]
> Usually we do this with whatever PR actually needs it

I guess so, but this specific release I need for testing MNE-BIDS 😅 wanted to add a test to MNE later

**Comment by hoechenberger** [comment]
Then again, I can already add a test to this PR. Will update this branch.

**Review by larsoner — APPROVED** [review]

**Review by agramfort — APPROVED** [review]

**Comment by agramfort** [comment]
@hoechenberger please merge when all green. thx

**Pull request merged**
