### PR TITLE
WIP: Fix mne.time_frequency.multitaper Nyquist adjustment

### PR DESCRIPTION
**Pull request by jona-sassenhagen**
I'm just gonna check what the tests are doing.

### CODE REVIEW

**Comment by jona-sassenhagen** [comment]
Test failures look like flakes to me.

```  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/_pytest/config/__init__.py", line 187 in console_main
  File "/opt/hostedtoolcache/Python/3.10.4/x64/bin/pytest", line 8 in <module>

Extension modules: numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg.lapack_lite, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, numba.core.typeconv._typeconv, numba._helperlib, numba._dynfunc, numba._dispatcher, numba.core.runtime._nrt_python, numba.np.ufunc._internal, scipy._lib._ccallback_c, matplotlib._c_internal_utils, PIL._imaging, matplotlib._path, kiwisolver._cext, matplotlib._image, zmq.backend.cython.constants, zmq.backend.cython.error, zmq.backend.cython.message, zmq.backend.cython.context, zmq.backend.cython.socket, zmq.backend.cython.utils, zmq.backend.cython._poll, zmq.backend.cython._version, zmq.backend.cython._device, zmq.backend.cython._proxy_steerable, tornado.speedups, psutil._psutil_linux, psutil._psutil_posix, vtkmodules.vtkCommonCore, vtkmodules.vtkCommonMath, vtkmodules.vtkCommonTransforms, vtkmodules.vtkCommonDataModel, vtkmodules.vtkCommonExecutionModel, vtkmodules.vtkCommonMisc, vtkmodules.vtkFiltersCore, vtkmodules.vtkRenderingCore, vtkmodules.vtkInteractionStyle, vtkmodules.vtkRenderingContext2D, vtkmodules.vtkFiltersGeneral, vtkmodules.vtkFiltersSources, vtkmodules.vtkInteractionWidgets, vtkmodules.vtkViewsCore, vtkmodules.vtkViewsInfovis, vtkmodules.vtkCommonColor, vtkmodules.vtkViewsContext2D, vtkmodules.vtkTestingRendering, vtkmodules.vtkPythonContext2D, vtkmodules.vtkImagingCore, vtkmodules.vtkImagingMath, vtkmodules.vtkRenderingHyperTreeGrid, vtkmodules.vtkRenderingUI, vtkmodules.vtkRenderingOpenGL2, vtkmodules.vtkRenderingVolume, vtkmodules.vtkRenderingVolumeOpenGL2, vtkmodules.vtkRenderingFreeType, vtkmodules.vtkRenderingLabel, vtkmodules.vtkRenderingLOD, vtkmodules.vtkRenderingImage, vtkmodules.vtkRenderingContextOpenGL2, vtkmodules.vtkIOVeraOut, vtkmodules.vtkIOTecplotTable, vtkmodules.vtkIOImage, vtkmodules.vtkIOSegY, vtkmodules.vtkIOXMLParser, vtkmodules.vtkIOXML, vtkmodules.vtkIOParallelXML, vtkmodules.vtkIOCore, vtkmodules.vtkIOPLY, vtkmodules.vtkIOMovie, vtkmodules.vtkIOOggTheora, vtkmodules.vtkIONetCDF, vtkmodules.vtkIOMotionFX, vtkmodules.vtkIOLegacy, vtkmodules.vtkIOGeometry, vtkmodules.vtkIOParallel, vtkmodules.vtkIOMINC, vtkmodules.vtkIOLSDyna, vtkmodules.vtkIOInfovis, vtkmodules.vtkIOImport, vtkmodules.vtkParallelCore, vtkmodules.vtkIOIOSS, vtkmodules.vtkIOHDF, vtkmodules.vtkIOVideo, vtkmodules.vtkRenderingSceneGraph, vtkmodules.vtkRenderingVtkJS, vtkmodules.vtkIOExport, vtkmodules.vtkIOExportPDF, vtkmodules.vtkRenderingGL2PSOpenGL2, vtkmodules.vtkIOExportGL2PS, vtkmodules.vtkIOExodus, vtkmodules.vtkIOEnSight, vtkmodules.vtkIOCityGML, vtkmodules.vtkIOChemistry, vtkmodules.vtkIOCesium3DTiles, vtkmodules.vtkIOCONVERGECFD, vtkmodules.vtkIOCGNSReader, vtkmodules.vtkIOAsynchronous, vtkmodules.vtkIOAMR, vtkmodules.vtkInteractionImage, vtkmodules.vtkImagingStencil, vtkmodules.vtkImagingStatistics, vtkmodules.vtkImagingGeneral, vtkmodules.vtkImagingMorphological, vtkmodules.vtkImagingFourier, vtkmodules.vtkIOSQL, vtkmodules.vtkImagingSources, vtkmodules.vtkInfovisCore, vtkmodules.vtkGeovisCore, vtkmodules.vtkInfovisLayout, vtkmodules.vtkRenderingAnnotation, vtkmodules.vtkImagingHybrid, vtkmodules.vtkImagingColor, vtkmodules.vtkFiltersTopology, vtkmodules.vtkFiltersSelection, vtkmodules.vtkFiltersSMP, vtkmodules.vtkFiltersPython, vtkmodules.vtkFiltersProgrammable, vtkmodules.vtkFiltersModeling, vtkmodules.vtkFiltersPoints, vtkmodules.vtkFiltersVerdict, vtkmodules.vtkFiltersStatistics, vtkmodules.vtkFiltersImaging, vtkmodules.vtkFiltersExtraction, vtkmodules.vtkFiltersGeometry, vtkmodules.vtkFiltersHybrid, vtkmodules.vtkFiltersTexture, vtkmodules.vtkFiltersParallel, vtkmodules.vtkFiltersParallelImaging, vtkmodules.vtkFiltersGeneric, vtkmodules.vtkCommonComputationalGeometry, vtkmodules.vtkFiltersFlowPaths, vtkmodules.vtkFiltersAMR, vtkmodules.vtkDomainsChemistry, vtkmodules.vtkDomainsChemistryOpenGL2, vtkmodules.vtkFiltersHyperTree, vtkmodules.vtkCommonPython, vtkmodules.vtkChartsCore, vtkmodules.vtkCommonSystem, numexpr.interpreter, xxsubtype, shiboken6.Shiboken, PySide6.QtCore, PySide6.QtGui, PySide6.QtDataVisualization, PySide6.QtWidgets, PySide6.QtOpenGLWidgets, PySide6.QtOpenGL, scipy.ndimage._nd_image, scipy.special._ufuncs_cxx, scipy.special._ufuncs, scipy.special._specfun, scipy.linalg._fblas, scipy.linalg._flapack, scipy.linalg._cythonized_array_utils, scipy.linalg._flinalg, scipy.linalg._solve_toeplitz, scipy.linalg._matfuncs_sqrtm_triu, scipy.linalg.cython_blas, scipy.linalg.cython_lapack, scipy.linalg._decomp_update, scipy.sparse._sparsetools, scipy.sparse._csparsetools, scipy.sparse.csgraph._tools, scipy.sparse.csgraph._shortest_path, scipy.sparse.csgraph._traversal, scipy.sparse.csgraph._min_spanning_tree, scipy.sparse.csgraph._flow, scipy.sparse.csgraph._matching, scipy.sparse.csgraph._reordering, scipy.special._comb, scipy.special._ellip_harm_2, _ni_label, scipy.ndimage._ni_label, scipy.sparse.linalg._isolve._iterative, scipy.sparse.linalg._dsolve._superlu, scipy.sparse.linalg._eigen.arpack._arpack, scipy.optimize._minpack2, scipy.optimize._group_columns, scipy._lib.messagestream, scipy.optimize._trlib._trlib, scipy.optimize._lbfgsb, _moduleTNC, scipy.optimize._moduleTNC, scipy.optimize._cobyla, scipy.optimize._slsqp, scipy.optimize._minpack, scipy.optimize._lsq.givens_elimination, scipy.optimize._zeros, scipy.optimize.__nnls, scipy.optimize._highs.cython.src._highs_wrapper, scipy.optimize._highs._highs_wrapper, scipy.optimize._highs.cython.src._highs_constants, scipy.optimize._highs._highs_constants, scipy.linalg._interpolative, scipy.optimize._bglu_dense, scipy.optimize._lsap_module, scipy.spatial._ckdtree, scipy.spatial._qhull, scipy.spatial._voronoi, scipy.spatial._distance_wrap, scipy.spatial._hausdorff, scipy.spatial.transform._rotation, numba.experimental.jitclass._box, _cffi_backend, scipy.interpolate._fitpack, scipy.interpolate.dfitpack, scipy.interpolate._bspl, scipy.interpolate._ppoly, scipy.interpolate.interpnd, scipy.interpolate._rbfinterp_pythran (total: 221)
/home/vsts/work/_temp/183d90b4-a6f2-4966-8d22-db4809f3f0a8.sh: line 4:  3027 Segmentation fault      (core dumped) pytest -m "not slowtest" ${TEST_OPTIONS}
##[error]Bash exited with code '139'.
Finishing: PySide6```

**Comment by jona-sassenhagen** [comment]
Perhaps there should be a regression test.

**Comment by larsoner** [comment]
> Perhaps there should be a regression test.

I guess you could but it seems like a pain here

**Comment by larsoner** [comment]
Okay to merge from your end @jona-sassenhagen ? I just did a merge with `main` that should fix CIs

**Comment by jona-sassenhagen** [comment]
Sure.

**Review by agramfort — COMMENTED** [review]
this deserves a bug fix entry and a backport no?

**Comment by mmagnuski** [comment]
@agramfort - I'm not sure a bug fix is necessary, `_mt_spectra` is a private function, and was called in `psd_array_multitaper` with `n_fft=None`, so the problem would not appear when using our public code.

**Review by mmagnuski — APPROVED** [review]

**Comment by mmagnuski** [comment]
@agramfort - Yes, I think there will be no effect at the level of the public API. But I was thinking recently of introducing n_fft to psd_array_multitaper (for padding) and then it would make a difference. :)

**Comment by agramfort** [comment]
thx @jona-sassenhagen

**Pull request merged**
