### PR TITLE
Add nanovolts to allowed units in brainvision files

### PR DESCRIPTION
**Pull request by tstenner**
The BrainVision export in Analyser exports EEG data in nanovolts.

Currently, these EEG channels get interpreted as MISC channels so the import fails. This PR adds nV as possible unit.

### CODE REVIEW

**Comment by cbrnr** [comment]
Is this the default option? It seems like all of our test files are in microvolts (although I didn't check), so it would be great to have a small test file that stores signals in nanovolts. Can you add this to a test? The file should go in our [testing data repo](https://github.com/mne-tools/mne-testing-data).

**Comment by tstenner** [comment]
> Can you add this to a test?

[Done](https://github.com/mne-tools/mne-testing-data/pull/35)

**Comment by cbrnr** [comment]
Nice! You could check that the channels are correctly loaded as EEG channels in `mne/io/brainvision/tests/test_brainvision.py` (you could add the test to the existing `test_brainvision_data` function. You can see how to work with data in the testing repo in `mne/io/edf/tests/test_edf.py`.

**Comment by larsoner** [comment]
Release 0.51 cut of `mne-testing-data`

https://github.com/mne-tools/mne-testing-data#add-or-change-files-in-the-repo-for-use-with-mne

**Comment by tstenner** [comment]
450108aa08c5143954b2080b1bfbe1e845a39fa0 adds a header file that's the same as the existing `test.vhdr`, except for the line `Ch1=FP1,,500,nV` (instead of `Ch1=FP1,,0.5,µV`) so the test just needs to check if both header files produce the same data.

**Comment by cbrnr** [comment]
Re-using an existing file is a good idea. However, this means that the changes in `mne-testing-data` should be reverted, right?

**Comment by tstenner** [comment]
I haven't quite understood the difference between the two repositories yet (`mne-testing-data` is for files too big for the main repository?), but the test cast in `mne-python` covers the changes already.

**Comment by agramfort** [comment]
see error at: https://travis-ci.org/mne-tools/mne-python/jobs/399039719#L3191

**Comment by tstenner** [comment]
> However, there are also PEP8 errors.

I've reformatted the file and rebased the commits. CircleCI still shows some unrelated error but Travis looks good so far.

**Comment by agramfort** [comment]
thx @tstenner

**Pull request merged**
