### PR TITLE
MRG: More doc cleanups

### PR DESCRIPTION
**Pull request by larsoner**
Simplifications to our build setup as well as fixes for a few link errors.

### CODE REVIEW

**Comment by agramfort** [comment]
API page looks good https://10676-1301584-gh.circle-artifacts.com/0/dev/python_reference.html

**Comment by larsoner** [comment]
Yeah the API page should look unchanged even though I deleted a bunch of lines. Basically it came from moving the `class.rst` and `function.rst` templates to a new dir where they would be auto-detected by `autosummary` so that we don't need to manually put in the `:template:` lines anymore.

Travis error was just a timeout on OSX so I restarted it.

**Comment by agramfort** [comment]
great LGTM then

>

**Comment by larsoner** [comment]
BTW with the `default_role = "autolink"` change, it's entirely possible that this will now work:
```
with `mne.Epochs`
```
instead of having to specify the ref type
```
with :class:`mne.Epochs`
```
But I haven't really tested it yet.

**Comment by agramfort** [comment]
thanks @larsoner

>

**Pull request merged**
