### PR TITLE
MAINT: Clean up use of verbose

### PR DESCRIPTION
**Pull request by larsoner**
A lot of places in our code, if we're doing something internal we might do:
```
def _check_sphere(...):
    out = fit_sphere_to_headshape(..., verbose=False)
```
with the goal of the `verbose=False` being "don't print info messages". However, this has an unintended side effect where this code:
```
with mne.use_log_level('error'):
    _check_sphere(...)
```
can still emit warnings even though the log level is ERROR. This PR adds a `_verbose_safe_false` function that returns `False` (which will be used as WARNING) if the current logging level is low enough (debug or info), but returns None ("do not modify") otherwise.

I cleaned up a few use cases for this in our codebase but not all of them. I think we can put more in as we see `verbose='error'` failing to silence warnings in the future.

It's possible this will help with #10612, because after this in theory we can use a `verbose='error'` somewhere (conditionally, probably) and have it properly sustain through to ignore any fit warnings when `spatial_colors=True` or so.

### CODE REVIEW

**Comment by drammock** [comment]
somewhat tangentially related: in my work on #11123 I'm finding a number of cases where `verbose` is in a function or method signature but isn't actually used anywhere (pylance helpfully highlights this by dimming the param name in the signature).  What should be done in those cases?  Should `verbose` be removed (and the decorator switched to `fill_doc`)?

**Comment by drammock** [comment]
> No this is in the magic of the `verbose` decorator

Ah right of course. I was forgetting what that actually does.

**Review by drammock — APPROVED** [review]

**Comment by larsoner** [comment]
@drammock I'm hoping that now in #10612, some well placed `verbose=_verbose_safe_false(kind='error')`s in the case of `spatial_colors=True` might make things work without a ton of warnings

**Comment by larsoner** [comment]
(Happy to let you work on it, but if you don't want to I could try later this week)

**Pull request merged**
