### PR TITLE
MRG: Add check for comps in inv

### PR DESCRIPTION
**Pull request by larsoner**
This PR adds checking that compensation grade of data matches that of forward. If it's not the case, it's probably a (fairly easily correctable) error on the part of the user.

@bloyl do you agree?

### CODE REVIEW

**Comment by bloyl** [comment]
+1 LGTM

**Comment by larsoner** [comment]
@agramfort okay for you?

**Comment by agramfort** [comment]
yes ok !

**Comment by larsoner** [comment]
In it goes then, @bloyl feel free to rebase your PR to make sure everything still works there

**Pull request merged**
