### PR TITLE
Fix: colorbar width regularized in plot_evoked_topomap

### PR DESCRIPTION
**Pull request by cmoutard**
The colorbar in plot_evoked_topomap is displayed in the last subplot of the line of topomap.
The code anticipate the fact that the colorbar width will be as large as the subplot x-axis. 
So a rectification of the axes dimensions is made, but after calling plt.colorbar(), what does not change the colorbar width on my machine (see picture below).
This PR proposes a fix, by calling plt.colorbar after the rectification of the axes dimensions.

capture du 2015-03-31 20 38 03

### CODE REVIEW

**Comment by mainakjas** [comment]
What can I do to reproduce this issue? If I run  examples/stats/plot_sensor_regression.py, I don't see this issue.

**Comment by cmoutard** [comment]
Maybe it is not using the same plot_topomap function. Have you tried to run examples/plot_evoked_topomap.py ?

**Comment by agramfort** [comment]
looks good here:

http://martinos.org/mne/dev/auto_examples/plot_evoked_topomap.html

@cmoutard I don't get your problem

**Comment by cmoutard** [comment]
This is strange.
I am using the most recent dev version of mne.
Here is the list of dependencies versions :

bisect": null, "_multiprocessing": null, "distutils": "2.7.9", "functools": null, "random": null, "tty": null, "subprocess": null, "sysconfig": null, "runpy": null, "gc": null, "pty": null, "pyparsing": "2.0.1", "mne": "0.9.dev0-HEAD:9e08c7d21252286a9369902c9f429574e270c5db", "PIL": null, "uuid": null, "tempfile": null, "mmap": null, "pprint": null, "_json": null, "platform": "1.0.7", "collections": null, "cProfile": null, "importlib": null, "zipimport": null, "string": null, "SocketServer": "0.4", "zipfile": null, "repr": null, "operator": null, "ssl": null, "scipy": "0.14.0", "_lsprof": null, "datetime": null, "decorator": "3.4.0", "ConfigParser": null, "tri": null, "httplib": null, "resource": null, "signal": null, "bisect": null, "decimal": "1.70", "cmd": null, "email": "4.0.3", "pydoc": "$Revision: 88564 $", "threading": null, "token": null, "shlex": null, "quopri": null, "multiprocessing": "0.70a1", "dis": null, "cgi": "2.6", "locale": null, "PyQt4": null, "atexit": null, "encodings": null, "calendar": null, "dateutil": "1.5", "abc": null, "plistlib": null, "bdb": null, "warnings": null, "tarfile": "$Revision: 85213 $", "urllib": "1.17", "re": "2.2.1", "new": null, "symbol": null, "math": null, "nose": "1.3.4", "fcntl": null, "ftplib": null, "ast": "82160", "optparse": "1.5.3", "UserDict": null, "inspect": null, "_ctypes": "1.1.0", "Queue": null, "exceptions": null, "ctypes": "1.1.0", "matplotlib": "1.4.0", "codecs": null, "colorsys": null, "struct": null, "shine": null, "_locale": null, "logging": "0.5.1.2", "socket": null, "thread": null, "StringIO": null, "traceback": null, "pkg_resources": null, "weakref": null, "itertools": null, "opcode": null, "pstats": null, "os": null, "marshal": null, "__future__": null, "_collections": null, "cStringIO": null, "_sre": null, "unittest": null, "__builtin__": null, "base64": null, "IPython": "2.2.0", "array": null, "hashlib": null, "select": null, "_heapq": null, "pkgutil": null, "imp": null, "errno": null, "_socket": null, "binascii": null, "sre_constants": null, "json": "2.0.9", "tokenize": null, "numpy": "1.9.2", "_warnings": null, "_functools": null, "cPickle": "1.71", "_codecs": null, "termios": null, "pwd": null, "webbrowser": null, "copy": null, "_sysconfigdata": null, "_struct": "0.2", "unicodedata": null, "_ast": "82160", "keyword": null, "uu": null, "_csv": "1.0", "storemagic": null, "zlib": "1.0", "posix": null, "fnmatch": null, "sre_parse": null, "pickle": "$Revision: 72223 $", "sklearn": "0.15.2", "mimetools": null, "FixTk": null, "copy_reg": null, "sre_compile": null, "_hashlib": null, "_random": null, "parser": "0.5", "site": null, "getpass": null, "contextlib": null, "numbers": null, "io": null, "__main__": null, "_cython_0_20_1": null, "shutil": null, "_io": null, "sip": null, "strop": null, "grp": null, "_weakrefset": null, "six": "1.9.0", "gettext": null, "heapq": null, "_abcoll": null, "sqlite3": null, "getopt": null, "csv": "1.0", "config": null, "genericpath": null, "stat": null, "_ssl": null, "rfc822": null, "glob": null, "urllib2": "2.7", "textwrap": null, "sys": null, "_sqlite3": null, "codeop": null, "readline": null, "types": null, "argparse": "1.1", "future_builtins": null, "_weakref": null, "difflib": null, "pdb": null, "urlparse": null, "linecache": null, "posixpath": null, "time": null, "gzip": null, "meeg_preprocessing": "0.1.dev0-HEAD:c4929eefe889fa07aab722b3bbbbd063eb1d4030"}

**Comment by cmoutard** [comment]
I am also using the argument show=False, but everything else is the same in my script.

**Comment by wmvanvliet** [comment]
I think this issue presents itself when the `title` parameter is set. See #1556

**Comment by mainakjas** [comment]
yes, I remember this. @cmoutard can you verify that your fix actually fixes such cases? I'd like to see a gist to reproduce the issue for such cases.

**Comment by dengemann** [comment]
The more advanced solution is to use axis dividers, see #1914

**Comment by cmoutard** [comment]
You are right @wmvanvliet, it was the title argument.
Unfortunately, my fix attempt does not solve this issue.

**Comment by dengemann** [comment]
Dont' give up. Use the axis divider method that I use in the PR mentioned above to produce proper colorbars.

**Comment by Eric89GXL** [comment]
@cmoutard will you have time to work on it this week? It would be nice to have for 0.9.

**Comment by mainakjas** [comment]
@cmoutard I was having similar problems. It seems the issue is with `tight_layout`. Have you tried?

**Comment by cmoutard** [comment]
I followed @dengemann's suggestion which gave me nice results. I still have to fix few things before pushing, soon...

**Comment by Eric89GXL** [comment]
If you can git it done this week it can go in the release, which would be great. Also FYI you need a rebase.

**Comment by cmoutard** [comment]
yes !

**Comment by Eric89GXL** [comment]
Ping @cmoutard :)

**Comment by cmoutard** [comment]
WIP !

**Comment by cmoutard** [comment]
Without a title :



With a title :

capture du 2015-04-17 21 51 21

Sorry for the dirty commits, some strange events happened.
At least, it seems functional, waiting for Travis...

**Comment by Eric89GXL** [comment]
Oof, looks like there were some botched merges with `master` in there. How many commits did you mean to have here? It looks like you must have push forced. Did you back up your branch before doing so?

**Comment by dengemann** [comment]
@cmoutard something went wrong here with indexing / rebasing.

**Comment by dengemann** [comment]
But the solution looks great!

**Comment by mainakjas** [comment]
@cmoutard any progress here? I might benefit from this in my PR

**Comment by Eric89GXL** [comment]
Closing for #1977 @cmoutard so that we can get this in and @mainakjas can use it. That PR is basically a rebased version (don't worry, your commits are in there) with a couple of tweaks.

**Pull request closed without merging**
