### PR TITLE
WIP: display fNIRS channels in plot_alignment

### PR DESCRIPTION
**Pull request by rob-luke**
#### What does this implement/fix?
This PR adds the ability to plot fnirs channels using `plot_alignment`

#### Additional information
Something seems wrong with the locations.

### CODE REVIEW

**Comment by rob-luke** [comment]
Using the testing dataset we expect a channel over approximately AFz, POz, FCC2h, FCC1h, CCP1h, CCP2h, [midpoint between T8 and TP8], [midpoint between T7 and TP7] ([see figure for expected locations marked by purple lines](https://user-images.githubusercontent.com/748691/63550410-f4c66900-c575-11e9-9701-a9a31b89c54d.png))

There appears to be an issue with the channel locations.
* Some sensors seem buried in the head (see below). The channels are defined as the mid point between source and detector, so it could cut slightly in to the head due to curved surface, but this looks extreme.
* A scaling by 1000 is required ([code](https://github.com/mne-tools/mne-python/pull/6853/files#diff-71445135e076e0dd8856e340d5e545c6R1021)). 
* The frontal and read source seems too low. Is there a way I can overlay the expected 10-20 locations on the same plot to validate my expectations?

@larsoner any suggestions where I might have gone wrong here?

Here is a minimal working example...
```python
import mne
import os.path as op
import numpy as np
from mayavi import mlab
mlab.init_notebook()
from mne.datasets.testing import data_path
from mne.viz import plot_alignment, snapshot_brain_montage
from mne.io import read_raw_nirx

fname_nirx = op.join(data_path(download=False), 'NIRx', 'nirx_15_2_recording_w_short')
raw = read_raw_nirx(fname_nirx, preload=True)

raw.pick(np.where(np.logical_not(raw._short_channels()))[0])  # Dont display short channels

subjects_dir = mne.datasets.sample.data_path() + '/subjects'
fig = plot_alignment(raw.info, trans = None,  subject='sample', subjects_dir=subjects_dir, surfaces=('head', 'white'), fnirs=True)

mne.viz.set_3d_view(fig, 0, 0)
mlab.gcf()
```
image
image

**Comment by agramfort** [comment]
@rob-luke how did you get the locations? what coordinate system are they in?

**Comment by rob-luke** [comment]
> @rob-luke how did you get the locations? what coordinate system are they in?

The locations are specified using the vendor software called NIRSite. You click on the locations in a GUI, this is then stored as a .mat file. Each time you take a measurement you tell the recording software which location file to use. When the recording is finished, a copy of the location file is renamed and automatically stored with the data. A more detailed description with images of this exact recording can be found at https://github.com/mne-tools/mne-testing-data/pull/51 

The coordinate system is MNI. Here is an extract from the manual..
image
The values are stored in cm (the manual says mm, but this is a mistake, I have confirmed this with the manufacturer). In step 4 [here](https://github.com/mne-tools/mne-testing-data/pull/51) the location of the optodes are listed in mm on the left of the figure. I have just opened a PR to ensure that the values read by the reader match those displayed in the vendor software but converted to m #6856 

Does this information make sense?

**Comment by rob-luke** [comment]
Closed in preference for @larsoner solution in #6856

**Pull request closed without merging**
