### PR TITLE
[MRG] Plot sEEG electrodes in plot_alignment

### PR DESCRIPTION
**Pull request by agramfort**

### CODE REVIEW

**Comment by larsoner** [comment]
I was going to celebrate this (probably) being the first time in MNE history that a single commit actually came back green and was ready for merge but then I saw you used two commits.

This one is pretty straightforward so I'll merge, thanks @agramfort

**Comment by agramfort** [comment]
:)

second commit is what's new update so I consider it a "home run" :)

**Comment by lneisenman** [comment]
Thanks for the quick update. `plot_alignment()` is now plotting SEEG electrodes for me.

I'm still having trouble with plotting electrodes whose coordinates are given in MRI space rather than the default MNE [space](https://gist.github.com/lneisenman/38ca9cf2e4075776f8476cebb114d2a1). Changing the `coord_frame` parameter in either `DigMontage` or  `plot_alignment()` doesn't seem to [help](https://gist.github.com/lneisenman/9d2b799475de57e20c0a0345b4547c5c).

**Comment by larsoner** [comment]
Your positions appear to be in `mm` they need to be in `m`, so divide by 1000. and hopefully it'll work

**Comment by lneisenman** [comment]
That did the trick. Thanks.

**Comment by larsoner** [comment]
@lneisenman is there somewhere we could update the documentation to make this bit clearer?

**Comment by lneisenman** [comment]
The units for the coordinates could be specified in the docs for [Montage](https://martinos.org/mne/stable/generated/mne.channels.Montage.html#mne.channels.Montage) and [DigMontage](https://martinos.org/mne/stable/generated/mne.channels.DigMontage.html#mne.channels.DigMontage) as part of the descriptions of the `pos` and `dig_ch_pos` parameters. A comment could also be added to the [ECOG demo](https://martinos.org/mne/stable/auto_examples/visualization/plot_3d_to_2d.html#sphx-glr-auto-examples-visualization-plot-3d-to-2d-py)  in the **Load Data** section such as 
```python
elec = mat['elec']  # Electrode coordinates are given in meters
```

Another helpful addition to the docs would be to suggest using `%gui qt` after importing PySurfer/Mayavi/MNE in python 3 notebooks as part of the notes about the [experimental python 3.6 env](https://martinos.org/mne/stable/install_mne_python.html).

**Comment by larsoner** [comment]
@lneisenman do you have time to make a pull request (PR) for some or all of these changes?

**Comment by lneisenman** [comment]
It may take a day or two.

**Comment by lneisenman** [comment]
@larsoner  Initial pull request is up but still needs another file updated. https://github.com/mne-tools/mne-python/pull/4913

**Pull request merged**
