### PR TITLE
MRG: Update Info docstring

### LINKED ISSUE #4290: What does raw.info["events"] contain?
When I load a BDF file, I need to call `mne.find_events(raw)` in order to extract the events found in the stim channel. However, I found that there is a key called `events` in the `raw.info` dictionary (which is usually empty for my files). What exactly is supposed to be in this list of dicts (according to the [docs](https://martinos.org/mne/stable/generated/mne.Info.html#mne.Info))? Is this field somehow related to the events I find with `mne.find_events`?

### PR DESCRIPTION
**Pull request by Eric89GXL**
Simple stuff:
* Updates `Info` docstring to be much more complete.
* Fixes some minor documentation bugs.

For discussion:
* Reorganizes some classes in the doc. The way we had it before, we had a "Classes" heading that only had some of the classes. This has been removed in favor of "Most-used classes", which has just Raw, Epochs, Evoked, and Info, all other classes have been moved to their respective sections. The alternative I see is to move *all* classes to the top Classes section. It seems a bit strange to have classes (partially or totally) centralized in one place and functions separated by use cases.

Closes #4290.

### CODE REVIEW

**Comment by agramfort** [comment]
you have a rendering pb in https://4708-1301584-gh.circle-artifacts.com/0/home/ubuntu/mne-python/doc/_build/html/python_reference.html#covariance-computation

besides LGTM when CIs are happy

**Comment by Eric89GXL** [comment]
Rendering problem fixed. I also got rid of the `Classes:` / `Functions:` headers in favor of just saying at the top that classes are CamelCase and functions are underscore_case

**Comment by Eric89GXL** [comment]
https://4720-1301584-gh.circle-artifacts.com/0/home/ubuntu/mne-python/doc/_build/html/python_reference.html

**Comment by agramfort** [comment]
thx @Eric89GXL

**Pull request merged**
