### PR TITLE
ENH: Add plot_projs_joint

### PR DESCRIPTION
**Pull request by larsoner**
Produces:

image

image

image

~~WIP because I'd still like to reduced test time, but figured I'd open for feedback on the API. We've been using this at UW for a while to help with analyzing/deciding about/QA'ing projections.~~

### CODE REVIEW

**Comment by hoechenberger** [comment]
Beautiful

**Review by agramfort — APPROVED** [review]
looks good https://output.circle-artifacts.com/output/job/8cc4524d-234f-4217-9223-7b040efb3b82/artifacts/0/dev/auto_tutorials/preprocessing/50_artifact_correction_ssp.html#repairing-ecg-artifacts-with-ssp

**Review by sappelhoff — COMMENTED** [review]
Even if it might be obvious from the docstr notes, it might benefit from adding "before (black) and after (green)" to the title.

could the legend labels of the right column also be made more obvious? Instead of `#1` --> `#1 (single norm factor)` and `#2` --> `#2 (ind. norm factor)`?

**Comment by larsoner** [comment]
I'm -1 on adding additional text to the legend. I'd agree with you for a paper figure, but this is meant to be used heavily/repeatedly during preprocessing. You only need to learn the labeling shorthand scheme *once* then you know it, but if we make it more verbose then you lose horizontal space to the legend text (because it will have to become larger to accommodate it) on *every* usage, which is unfortunate. Maybe a legend=True (current compact mode, default), 'full' (your suggestion), or False (not shown) could be useful, but I'm not sure it's totally necessary.

I'll see if I can get the left title text to fit to match ICA though.

**Comment by larsoner** [comment]
I thought of a compact way to make the legend perhaps clearer, let me give it a shot

**Comment by hoechenberger** [comment]
What I've found myself doing when working with the **report** is that I'm adding captions.

I wonder if we could add a small-font caption-style text to satisfy @sappelhoff's needs?

**Comment by sappelhoff** [comment]
> I'll see if I can get the left title text to fit to match ICA though.

Actually, this would already completely satisfy me :point_up: 

but I am excited to see what you come up with now :+1:

**Comment by larsoner** [comment]
I see a :+1: from @sappelhoff so I'll go ahead and merge once green unless there are other comments!

**Review by sappelhoff — APPROVED** [review]

**Comment by hoechenberger** [comment]
Very simply and helpful solution, nice!

**Pull request merged**
