### PR TITLE
MRG, VIZ, BUG: fix plot compare evokeds with list/tuple input when evoked comments not unique

### LINKED ISSUE #8588: plot_compare_evokeds only plots one waveform, given list of inputs and identical comments
Between v 0.20.7 and 0.21.2, the way mnw.viz.plot_compare_evokeds() deals with a list of inputs haschanged. 

#### Steps to reproduce
Given a dict of Evokeds such as this:

```
gavg = {'Condition A': <Evoked | 'Grand average (n = 20)' (average, N=20), [-0.19922, 1] sec, 64 ch, ~479 kB>,
        'Condition B': <Evoked | 'Grand average (n = 20)' (average, N=20), [-0.19922, 1] sec, 64 ch, ~479 kB>,
        'Condition C': <Evoked | 'Grand average (n = 20)' (average, N=20), [-0.19922, 1] sec, 64 ch, ~479 kB>,
        'Condition D': <Evoked | 'Grand average (n = 20)' (average, N=20), [-0.19922, 1] sec, 64 ch, ~479 kB>}
```

and the command:

`mne.viz.plot_compare_evokeds([gavg['Condition A'], gavg['Condition B']]`

...the previous (0.20.7) behavior was to plot a line for each input in the list.

The new (0.21.2) behavior plots a single line. 

The documentation for each version is below, with the change in bold:

What does not seem to be documented (and, IMHO, is a bug), is that if multiple inputs have the same comment, only the last input is plotted. Perhaps in this case all inputs could be plotted, but a warning could be issued about the identical comments?

Note as well the typo 'respectiv' in the newer version of the documentation.

### PR DESCRIPTION
**Pull request by drammock**
closes #8588 

For the record this was introduced in #8054.

### CODE REVIEW

**Comment by drammock** [comment]
@aaronjnewman are you able to confirm this fix by testing on your data with this PR branch?  (something like `pip install git+https://github.com/drammock/mne-python.git@fix-plot-compare-evokeds` should do it...

**Comment by drammock** [comment]
The last plot in [this tutorial section](https://23875-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/evoked/plot_20_visualize_evoked.html#comparing-evoked-objects) demonstrates the new behavior.

**Comment by aaronjnewman** [comment]
@drammock yes, it works now. Two lines are plotted for two inputs, and the (identical) comments for each input are shown in the legend.
Thank you!

**Review by agramfort — APPROVED** [review]

**Comment by drammock** [comment]
rebased & force-pushed, hopefully Azure CIs will be green now

**Comment by larsoner** [comment]
Thanks @drammock

**Pull request merged**
