### PR TITLE
MRG, MAINT: Update PyVista backend

### PR DESCRIPTION
**Pull request by larsoner**
Let's see if this part of #7060 breaks Azure.

### CODE REVIEW

**Comment by larsoner** [comment]
@GuillaumeFavelier this breaks it! I'll try removing the AA stuff and see if that fixes things

**Comment by GuillaumeFavelier** [comment]
+1 for testing AA

**Comment by larsoner** [comment]
Okay @GuillaumeFavelier pushed a commit that hopefully will "fix" things for us

**Comment by larsoner** [comment]
I'll kill these CIs for now and if the fix doesn't work, keep iterating here

**Pull request closed without merging**
