### PR TITLE
MRG FIX: Version checking

### LINKED ISSUE #2074: Q: Dataset versions
Have we gotten any useful information from embedding dataset versions in our tarballs? As far as I can tell it has just led to a bunch of warnings when doing imports (see e.g. Mainak's recent notebook examples). I propose we get rid of them for now, and replace them with a new system in the future if need be. But for now I think it's beyond YAGNI and into the adding-annoyance category...

### LINKED ISSUE #2075: raw.plot() does not work in ipython notebook
Here is the code to reproduce

```py
%matplotlib inline
import mne
from mne.datasets import sample
data_path = sample.data_path()

raw_fname = data_path + '/MEG/sample/sample_audvis_filt-0-40_raw.fif'
raw = mne.io.Raw(raw_fname, preload=False)
raw.plot()
```
and here is the traceback

```py
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-6c1dd611695c> in <module>()
      1 raw = mne.io.Raw(raw_fname, preload=False)
      2 print(raw)
----> 3 raw.plot()

/home/mainak/Desktop/projects/mne-python/mne/io/base.pyc in plot(self, events, duration, start, n_channels, bgcolor, color, bad_color, event_color, scalings, remove_dc, order, show_options, title, show, block, highpass, lowpass, filtorder, clipping)
   1088                         color, bad_color, event_color, scalings, remove_dc,
   1089                         order, show_options, title, show, block, highpass,
-> 1090                         lowpass, filtorder, clipping)
   1091 
   1092     @verbose

/home/mainak/Desktop/projects/mne-python/mne/viz/raw.pyc in plot_raw(raw, events, duration, start, n_channels, bgcolor, color, bad_color, event_color, scalings, remove_dc, order, show_options, title, show, block, highpass, lowpass, filtorder, clipping)
    697 
    698     if show:
--> 699         plt.show(block=block)
    700 
    701     return fig

/home/mainak/anaconda/lib/python2.7/site-packages/matplotlib/pyplot.pyc in show(*args, **kw)
    153     """
    154     global _show
--> 155     return _show(*args, **kw)
    156 
    157 

TypeError: show() got an unexpected keyword argument 'block'
```
cc @Eric89GXL

### PR DESCRIPTION
**Pull request by Eric89GXL**
Closes #2074.
Closes #2075.

Ready for review/merge from my end.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
I also added a deprecation of `block` for `raw.plot`. It doesn't always work / isn't always available in MPL, is an experimental option anyway, and only exists in `raw.plot` and not any of our other plotting functions. Also, YAGNI. If people really want it, it's easy enough for them to say `show=false` and do `plt.show(block=True)` manually (adds one line of code).

**Comment by dengemann** [comment]
@Eric89GXL the block feature is handy, I'm using it very often. -1 on deprecating it.

**Comment by Eric89GXL** [comment]
What do you think about the consistency argument? Should we add the option everywhere, or just deal with the inconsistency?

**Comment by Eric89GXL** [comment]
To me people having to add one extra line is worth the simplicity/consistency at the mne-python end...

**Comment by dengemann** [comment]
>What do you think about the consistency argument? Should we add the option everywhere, or just deal with the inconsistency?

we simple don't need it anywhere else. Think of a typical use case:

You loop over subjects and stop at each iteration to mark bad channels. When done, you close and move on.

We don't have any other function that would promote a similar workflow.

**Comment by Eric89GXL** [comment]
There are certainly other potential workflows that would require manual inspection of a plot / pausing at each stage... But I'll revert the changes since it sounds like it would mess with your code too much.

**Comment by dengemann** [comment]
@Eric89GXL out of curiosity, you mentioned that it does not always work. Can you give details. I was not aware that this option uses messy code.

**Comment by Eric89GXL** [comment]
The MPL docs it says it's experimental:

http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.show

We've had problems with it before:

https://github.com/mne-tools/mne-python/issues/903

And the `try/except` implemented here is implemented it still isn't working properly in IPython for @mainakjas. So it seems to be a bit of a buggy feature.

**Comment by Eric89GXL** [comment]
AFAIK the more common/accepted way of doing it is through `ion`/`ioff`.

**Comment by Eric89GXL** [comment]
Reverted deprecation and put a warning in the docstring instead.

**Comment by dengemann** [comment]
> Reverted deprecation and put a warning in the docstring instead.

Ok thanks. Let's keep on deloping and see where this goes. So far it's really useful in this particular context. Also not that plot_raw is the only viz function that allows you to set data.

**Comment by Eric89GXL** [comment]
CIs are happy, feel free to merge if you're happy @dengemann (or @agramfort)

**Comment by agramfort** [comment]
can you call the get_version() function in any of the tests? thx

besides LGTM

**Comment by Eric89GXL** [comment]
@agramfort done

**Comment by agramfort** [comment]
Thx

**Pull request merged**
