### PR TITLE
WIP: plot_erp_roi example

### PR DESCRIPTION
**Pull request by jona-sassenhagen**
See #2317, #1939 

Result:
figure_1

### CODE REVIEW

**Comment by jona-sassenhagen** [comment]
@ImmanuelSamuel does this work for you?

**Comment by jaeilepp** [comment]
``plot_erp_roi`` doesn't have .py extension.

**Comment by jaeilepp** [comment]
For me this throws an error:
```
ValueError                                Traceback (most recent call last)
/home/jaakko/mne-python/examples/visualization/plot_erp_roi in <module>()
    227 
    228 fs = plot_roi(evokeds, column_names=column_names, row_names=row_names,
--> 229               roi_to_chan="percentiles")
    230 
    231 fs.set_size_inches((12, 12))

/home/jaakko/mne-python/examples/visualization/plot_erp_roi in plot_roi(evokeds, column_names, row_names, roi_to_chan, ch_type, conds)
    161     if len(roi_to_chan) < (columns * rows):
    162         error = "Error: sensor coverage too sparse for requested layout."
--> 163         raise ValueError(error)
    164 
    165     if any([len(v) == 1 for v in roi_to_chan.values()]):

ValueError: Error: sensor coverage too sparse for requested layout.

```

**Comment by jona-sassenhagen** [comment]
@jaeilepp as-is? It works flawlessly for me on a just-pulled master.

**Comment by jaeilepp** [comment]
Yes. To me, ``roi_to_chan`` is a defaultdict so the check at line 155 fails because ``len(roi_to_chan)`` is 1.

**Comment by jona-sassenhagen** [comment]
Ah! So just so I get this right: it's not the example that fails, but the function with different arguments?

**Comment by jaeilepp** [comment]
Running the example fails for me.

**Comment by jaeilepp** [comment]
Reading deeper into the code: it actually probably fails because ``roi_names`` is not used after it's initialization. Does this really work for you?

**Comment by jaeilepp** [comment]
Looks like you removed the lines using ``roi_names`` with the latest commit.

**Comment by jaeilepp** [comment]
Okay, it fails because of integer division on lines 43 and 44. Cast columns and rows to float and it works. ``roi_names`` is just a leftover...

**Comment by jona-sassenhagen** [comment]
Ah! Better this way? Was that a Python 2/3 thing?

>Looks like you removed the lines using roi_names with the latest commit.

Yes, travis picked up on the fact they were actually never used ...

**Comment by jaeilepp** [comment]
Yeah, now it works.

**Comment by ImmanuelSamuel** [comment]
@jona-sassenhagen this looks great! Thanks for the awesome work.

**Comment by jona-sassenhagen** [comment]
@Eric89GXL What do you think?

**Comment by Eric89GXL** [comment]
Ahh sorry @jona-sassenhagen missed your ping on this one. I don't use these types of plots often so I'm not a great candidate to comment on the functionality, but I'm happy to review the code mechanics if you want. Maybe @dengemann @jasmainak or @agramfort have opinions on the functionality?

**Comment by jona-sassenhagen** [comment]
@teonlamont too.

Although I always appreciate your comments on my awful code, it would probably be better to first establish if we want this in master at all.

**Comment by jasmainak** [comment]
I quickly scanned the related issues. I'm not fully convinced that averaging ERP in an ROI is a good approach because you don't take the physics into account. We already have code for interpolation. Just pick the ROI and interpolate the channels to one channel. In practice, it probably doesn't make a big difference for EEG but I'd say for MEG averaging channels won't work.

**Comment by jona-sassenhagen** [comment]
>I quickly scanned the related issues. I'm not fully convinced that averaging ERP in an ROI is a good approach because you don't take the physics into account. 

In principle I agree, but this is more a standard thing done in EEG/ERP research. I personally neither think it's a particularly good approach, nor would I do this myself, but it's a standard thing. I'd say many EEG/ERP people expect something like this.

A similar thing would be plotting selected channels in a rectangular array btw, though I'm not sure how I'd go about the assignment/API here.

**Comment by agramfort** [comment]
honestly I would never use this. But it's just me.

Maybe ask on the MNE mailing list some people would be interested to have this in the next release ?

**Comment by jona-sassenhagen** [comment]
I have to many open PRs. Closing.

**Pull request closed without merging**
