### PR TITLE
MRG: Unify BTI transforms

### PR DESCRIPTION
**Pull request by Eric89GXL**
@dengemann I think this makes it clearer how different components are used, see if you agree.

### CODE REVIEW

**Comment by dengemann** [comment]
Cool @Eric89GXL -- I'll pull, evaluate and move on.

**Comment by wmvanvliet** [comment]
more red than green!

**Comment by dengemann** [comment]
More to come here: 
https://github.com/Eric89GXL/mne-python/pull/21

**Comment by Eric89GXL** [comment]
@dengemann can you take a look and make sure you're still happy? This is ready to go from my end now.

**Comment by dengemann** [comment]
Thanks Eric for this ping pong match ;)

**Comment by Eric89GXL** [comment]
No problem, now you just need to get the helmet out of the head :)

**Comment by dengemann** [comment]
> No problem, now you just need to get the helmet out of the head :)

thinking about the next surgical move ..

**Pull request merged**
