### PR TITLE
Update plot_filter, plot_ideal_filter functions

### PR DESCRIPTION
**Pull request by teanijarv**
#### Reference issue
Example: Edits for #7678 .

#### What does this implement/fix?
plot_filter - changed linewidth parameter to be the same value for all 3 plots + added grid to the plots
plot_ideal_filter - fixed the alpha argument not used in the function; changed linewidth

### CODE REVIEW

**Comment by agramfort** [comment]
@teanijarv can you run flake8 on your code to see the code style issues? 🙏

**Comment by teanijarv** [comment]
@agramfort I ran flake8 and did not get any code style errors/warnings, so it's all good :)

**Comment by teanijarv** [comment]
Sorry about that, but I haven't used flake before, but when I run flake, I don't get any errors. Is there anything I'm missing here?
```
make flake  /Users/tanijarv/Documents/GitHub/mne-python-edit/mne/viz/misc.py
Running flake8
0
flake8 passed
make: Nothing to be done for `/Users/tanijarv/Documents/GitHub/mne-python-edit/mne/viz/misc.py'.
```

**Comment by larsoner** [comment]
It's likely your `flake8` is out of date. Feel free to update it, or trust the CIs to tell you...

**Comment by teanijarv** [comment]
Let me know if anything else needs to be changed, the whole workflow/process of contributing to some big package is kinda new to me.

**Comment by larsoner** [comment]
@teanijarv I looked at the rendered HTML and it was nice! I added your name + URL to `doc/changes` and I'm marking for merge when green, thanks in advance!

**Comment by teanijarv** [comment]
@larsoner Great! Thank you!

**Pull request merged**
