### PR TITLE
WIP Epochs.apply_baseline return self and copy param

### LINKED ISSUE #3037: epochs.apply_baseline does not return self
`Epochs.apply_baseline` claims it returns `self`, but it returns nothing:
https://github.com/mne-tools/mne-python/blob/4b93a7051f8ee5bc46b02f2acf5823900029f418/mne/epochs.py#L437
https://github.com/mne-tools/mne-python/blob/4b93a7051f8ee5bc46b02f2acf5823900029f418/mne/epochs.py#L455

Also, shouldn't it have a copy method?

I can PR once I have another one merged.

### PR DESCRIPTION
**Pull request by jona-sassenhagen**
`Epochs.apply_baseline` does not currently return self, or have a `copy` option. IMO it should though.

closes #3037

### CODE REVIEW

**Comment by jona-sassenhagen** [comment]
Should this have a test?

**Comment by agramfort** [comment]
please update an existing test

**Comment by jona-sassenhagen** [comment]
It might become useful eventually to have a `copy` decorator to be applied to object methods to get rid of the repeated

```
inst = self.copy() if copy else self
...

return inst
```

**Comment by agramfort** [comment]
travis is broken

**Comment by jona-sassenhagen** [comment]
(Still WIP, I'm at a conference)

**Comment by agramfort** [comment]
merge by rebase after a few edits

thx @jona-sassenhagen

**Comment by jona-sassenhagen** [comment]
Thanks for taking over!






On Sat, Mar 26, 2016 at 8:15 AM -0700, "Alexandre Gramfort" <notifications@github.com> wrote:












Closed #3039.

**Comment by agramfort** [comment]
Social coding ;)

**Comment by kingjr** [comment]
change of API, don't forget what s new?

**Comment by agramfort** [comment]
Already done ;)

**Pull request closed without merging**
