### PR TITLE
[MRG][DOC] Add GFP to the glossary

### PR DESCRIPTION
**Pull request by massich**
This PR continues #5796 by adding an entry to the glossary and pointing at it.

@jona-sassenhagen can you (or anybody else) edit the glossary entry with
meaningful info? Thx. I think it would be good also to point to back to whatever
tuto/example explains better GFP. 
(maybe `examples/time_frequency/plot_time_frequency_global_field_power.py`?)

### CODE REVIEW

**Comment by massich** [comment]
@drammock can you take over this one? thx

**Comment by drammock** [comment]
In order to be write an honest glossary entry for GFP, we would need to do it the same way everywhere. Sadly that is not happening:

- `evoked.data.std(axis=0)` is used:
    - [mne.viz.utils._find_peaks](https://github.com/mne-tools/mne-python/blob/master/mne/viz/utils.py#L1317)
    - [tutorials/evoked/plot_object_evoked.py](https://github.com/mne-tools/mne-python/blob/master/tutorials/evoked/plot_object_evoked.py#L72)
- `sqrt(mean(evoked.data ** 2, axis=0))` is used:
    - [mne.viz.evoked._plot_lines](https://github.com/mne-tools/mne-python/blob/master/mne/viz/evoked.py#L460)
- `mne.baseline.rescale(sum(evoked.data ** 2, axis=0)` is used:
    - [examples/time_frequency/plot_time_frequency_global_field_power.py](https://github.com/mne-tools/mne-python/blob/master/examples/time_frequency/plot_time_frequency_global_field_power.py#L111-L112)

**Comment by drammock** [comment]
[rendered glossary](https://13423-1301584-gh.circle-artifacts.com/0/dev/glossary.html)

**Comment by larsoner** [comment]
Perhaps some of the confusion arises because for EEG data with a common average reference the RMS power at each time point across sensors is the same as the standard deviation (but without CAR it's not due to the mean subtraction step). I'm actually not sure which we should use everywhere, probably the `std`. But in any case, this looks good, thanks @drammock !

**Comment by drammock** [comment]
@larsoner it strikes me as low priority, but to improve consistency (and ensure future additions remain consistent) WDYT about adding a GFP function that triages based on instance type (and maybe incorporates some of the baselining functionality that @dengemann is using in that time-freq-GFP example?)

**Comment by larsoner** [comment]
Sure, a private function would be nice. It might not even need to triage based on type, it's entirely possible the `sum` should be `mean` in the TF code. But someone would need to check (and also check that you should subtract the mean at each time point, maybe you don't and just rely on the baselining or high-passing instead...)

**Pull request merged**
