### PR TITLE
Adding interactive plotting of magnetic field lines to Brain

### LINKED ISSUE #8382: interactive sensor-level field patterns browser
Our interactive source estimate viewer is so awesome, it makes me wish for an equally awesome sensor level viewer. For this, the venerable proprietary "Xfit" program that ships with the MegIn scanner may serve as inspiration.

With MEG, the raw sensor timecourses are quite difficult to interpret: gradiometers and magnetometers measure the field in different directions. The choice made by Xfit to make the field patterns the central visualization is a good one. See a short screencast of Xfit in action, here:

https://gfycat.com/jointaromatichorsemouse

For MNE-Python, I envision an interface similar to the source viewer, but with the field patterns instead of the pysurfer brain. On the bottom, we have the GFP timecourse.

What would be super nice would be the ability to "drop a dipole". Similar to clicking a vertex in the source viewer, have the ability to fit a dipole at the currently selected time, and see the dipole timecourse.

As extra bonus, it would be great if we would select a subset of channels and view the field patterns generated by only those sensors, and fit a dipole using only those sensors.

### PR DESCRIPTION
**Pull request by wmvanvliet**
Picking up from #8382 from way back, I've been working on a supercharged version of `mne.viz.plot_evoked_field` that uses our interactive `Brain` plotting object. Check it out:

movie1

The API for this is a new `add_field()` method for the `Brain` object:

```
field_map = mne.make_field_map(
    evoked,
    trans=trans,
    subject='sample',
    subjects_dir=f'{data_path}/subjects',
)

# Plot the source estimate
brain = stc.plot(
    'sample',
    subjects_dir=f'{data_path}/subjects',
    initial_time=0.08,
    hemi='both',
    surface='white',
)

# Add the field lines!
brain.add_field(evoked, field_map)
```

The above plot is a bit busy though. I find things are easier to interpret when we skip the EEG field patterns and we also don't plot the field density "blobs", just the contour lines:

movie2

The above is achieved by passing `ch_type='meg'` to `mne.make_field_map` and `show_density=False` to `Brain.add_field`, and `background=white` to `stc.plot`.

Screenshot of the GUI, notice the "Field strength" section in the dock:

screenshot

Example: Fixes #8382 

## Todo:

 - [x] Implement `Brain.add_field`
 - [x] Implement GUI elements
 - ~[ ] Find a way to plot just the field lines without an MRI~
 - ~[ ] Make `hemi='split'` work~
 - ~[ ] Refactor old `mne.viz.plot_evoked_field` function~
 - [ ] Unit tests
 - [ ] Example
 - [ ] API docs
 - [ ] What's new entry

### CODE REVIEW

**Comment by larsoner** [comment]
Looks nice! This is definitely something that I've missed from `mne_analyze` :)

A few high level thoughts/ideas offhand:

1. Do we have to be careful / think about the interaction with `brain.plot_sensors` (which can plot a helmet)?
2. I wonder if a more future compatible API might be `brain.add_evoked(evoked)` and `brain.add_field_map(map)`. Just trying to think a little bit more generally, someday we might want to have for example `brain.add_inverse(...)`, `brain.add_evoked(...)`, `brain.add_field_map(...)` and the object can automatically "do everything it can": apply the inverse to the evoked and plots the STC and the field map. But I guess this could also be done via `brain.add_inverse(inverse, evoked)`, too, so maybe overkill to go this direction.
3. Or even better -- rather than make `Brain` more and more complex by adding bits of code from other places, I've been hoping that at some point we could implement a proper plotting event/publisher-subscriber system (see https://github.com/mne-tools/mne-python/wiki/GSoC-Ideas#2-event-system-for-brain-and-evoked-plots). If we did, it seems like the functionality in this PR could be achieved by something like the following I think:
   ```
   brain = stc.plot(...)
   fig = mne.viz.plot_evoked_field(..., fig=brain.figure)
   brain.connect('on_time_change', fig.set_time)
   ```
   and you could get the benefit of also connecting a `mne.viz.plot_evoked_joint(...)` or `plot_evoked_topo` if you wanted those to update, etc.

Even if (3) seems like a better way of accomplishing this (and it might not!) then it doesn't necessarily have to stand in the way of this PR. But if you were motivated to work on getting the event system started... :)

**Comment by wmvanvliet** [comment]
(3) sounds like the way to go if we want to add even more capabilities to `Brain`. The file is too large and complicated as it is already. This event system sounds like a good way to achieve some of the todo items in this PR. Notably, it would be nice if the field patterns can still be plotted with our time viewer, but without a FreeSurfer brain mesh in the center (like xfit can). This is clearly out of scope of the `Brain` object.

**Comment by larsoner** [comment]
>  it would be nice if the field patterns can still be plotted with our time viewer, but without a FreeSurfer brain mesh in the center (like xfit can). 

Agreed. I think an event system could make it much easier to provide xfit-like interactive dipole fitting for example...

Should we start building an event system to allow this sort of stuff (maybe over the next month or so?), then see if we can get the equivalent functionality of this PR, or would you rather get some version of this PR in as is? I don't want to make perfect the enemy of good here, what you have is already cool and usable!

**Comment by wmvanvliet** [comment]
See https://github.com/mne-tools/mne-python/issues/11678

**Comment by wmvanvliet** [comment]
Closing for now. I'll re-implement this when the [ui-event system](https://github.com/mne-tools/mne-python/issues/11678) is operational.

**Pull request closed without merging**
