### PR TITLE
ENH: migrate to new amazon bucket

### PR DESCRIPTION
**Pull request by dengemann**
Let's see if it flies.

### CODE REVIEW

**Comment by dengemann** [comment]
We should probably look into making travis and circle ci get the data directly from AWS to avoid unnecessary costs.

**Comment by dengemann** [comment]
https://docs.travis-ci.com/user/deployment/s3

**Comment by dengemann** [comment]
same for circle ci https://circleci.com/docs/continuous-deployment-with-aws-codedeploy and appveyor
https://www.appveyor.com/docs/deployment/amazon-s3

**Comment by agramfort** [comment]
merge when it's up and running

**Comment by dengemann** [comment]
I would say let's try to also use the within AWS deployment. It should save money.

**Comment by kingjr** [comment]
have you thought of using a dropbox server? That's S3 based, and it'd be free.

**Comment by dengemann** [comment]
> have you thought of using a dropbox server

you mean a dropbox account? Something does not make feel that good about this idea.

**Comment by kingjr** [comment]
I agree it feels less pro than aws. I'm just saying in case aws becomes too expensive, (but I don't know anything about your budget). Dropbox has an app interface with encryption keys and a python sdk.

The janelia people are also developing [this](http://datasets.codeneuro.org/), and I heard some of them saying that they're trying to make a free platform to host neural data. But I don't think it's ready yet.

**Comment by dengemann** [comment]
Looks cool! Let's have a look at this. Currently I don't see an issue here as we have funding for this. Eric's free tier has expired and we need a quick solution to avoid private costs for him. On the mid term we need something community funded.

**Comment by Eric89GXL** [comment]
Dup of #2885...?

**Comment by jasmainak** [comment]
Cool, I was suggesting this to @jaeilepp today because Copy is closing their servers on 1st May. Timely PR :)

**Comment by Eric89GXL** [comment]
@jasmainak yeah there is actually a PR already to move that repo over, too, it's part of #2587 :) In fact the versions that are up on AWS of the Brainstorm data might not even work without #2587, someone would need to check before merging this version. IMO it's easier to stick with #2885 and #2587 separately...

**Comment by jasmainak** [comment]
How is the Amazon dataset different from the one on the Copy server?

**Comment by Eric89GXL** [comment]
IIRC works with the PR in progress to use the native format (CTF?) and also
adds the annotations mat file. The changes in that PR probably give some
indication

**Comment by jasmainak** [comment]
Ah right, so the examples would have to be updated as well ...

**Comment by Eric89GXL** [comment]
I think so, but looking at the PR it still uses FIF. But we should probably do all the checking as part of #2587. It should go in for 0.12 and thus meet the May deadline.

**Pull request closed without merging**
