### PR TITLE
MRG, DOC: Clearer MNE links

### PR DESCRIPTION
**Pull request by larsoner**
A variant of what I think is the behavior requested by @agramfort in #7174.

### CODE REVIEW

**Comment by larsoner** [comment]
@drammock @agramfort feel free to look:

https://17429-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/intro/plot_10_overview.html

**Comment by agramfort** [comment]
I like it better but please share your collective opinions

**Comment by larsoner** [comment]
I'm fine with it

**Comment by drammock** [comment]
Personally I think that looks better, but weird things are still happening. In [the preprocessing section](https://17429-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/intro/plot_10_overview.html#preprocessing) we are getting bolding/linking on variable called `ica` (shouldn't happen in my opinion). Earlier in the same page we are not getting bolding/linking on variable `raw` (desired behavior in my opinion).  I can't tell if those are going to get fixed by sphinx-gallery/sphinx-gallery#584 or not (but it looks like not?).

To state my vision more comprehensively than before, here is what I would like to be able to format separately:

1. functions, class constructors, and methods within MNE
2. functions, class constructors, and methods from other modules (numpy, etc)
3. functions, class constructors, and methods in the standard library
4. variable names of MNE objects
5. variable names of objects defined by other modules
6. variable names of standard library objects

Personally for MNE docs I think ideally (1) should be linked and bolded, (2) should be linked but with no special formatting, and 3-6 should be neither linked nor formatted.  If it's hard to separate 2&3 or 5&6, or if it's hard to suppress linking, leaving 2-6 unformatted would still in my opinion make things look a lot better.

**Comment by drammock** [comment]
(that said, this is an improvement over how it was before, so +1 for merge on this particular PR's changes)

**Comment by larsoner** [comment]
>  In the preprocessing section we are getting bolding/linking on variable called ica (shouldn't happen in my opinion). Earlier in the same page we are not getting bolding/linking on variable raw (desired behavior in my opinion).

These are both instances of MNE classes so for consistency I'm not sure why you in principle would want them highlighted differently.

As for why `raw` is not highlighted if we delete it then it won't get highlighted, which is a global var limitation that would require quite a bit of SG refactoring to deal with.

> To state my vision more comprehensively than before, here is what I would like to be able to format separately:

I think in principle you should be able to do this now with CSS selectors. Do you want to give it a shot?

Personally what I do is get a single build with `PATTERN=overview make html_dev-pattern` done, then modify the `doc/_build/html/static/style.css` file, reloading the page in chrome / making changes in chrome and porting them back, then once I'm happy copy the `doc/_build/html/_static/style.css` over to `doc/_static/style.css`. It prevents ever needing to `make html*` to go through style iterations and makes it pretty quick.

**Comment by drammock** [comment]
> > In the preprocessing section we are getting bolding/linking on variable called ica (shouldn't happen in my opinion). Earlier in the same page we are not getting bolding/linking on variable raw (desired behavior in my opinion).
> 
> These are both instances of MNE classes so for consistency I'm not sure why you in principle would want them highlighted differently.

I guess I wasn't clear.  I don't want them different.  I want both of them to be not bold and not linked.  Currently `raw` is correct and `ica` is incorrect (in my opinion).

> As for why `raw` is not highlighted if we delete it then it won't get highlighted, which is a global var limitation that would require quite a bit of SG refactoring to deal with.

so calling `del raw` is the reason that `raw` doesn't get linked/formatted?  To me that is even stronger reason to not highlight/link *any* variable names.

> > To state my vision more comprehensively than before, here is what I would like to be able to format separately:
> 
> I think in principle you should be able to do this now with CSS selectors. Do you want to give it a shot?

Sure, I'll push to this PR if that's OK?

**Comment by larsoner** [comment]
Yes feel free to push

**Comment by drammock** [comment]
actually I don't think this will be possible with CSS selectors.  The generated `a` tag for the `ica` variable name is indistinguishable from the generated `a` tag for the `mne.preprocessing.ICA` class constructor (same href, same title, same CSS class), and the `span` tags for variable names and for namespace components are both `span class='n'` so I can't select based on that either.  I think this will require changes to SG :(

**Comment by larsoner** [comment]
Yes it's a SG bug that `ica` gets only the `sphx-glr-backref-module-mne-preprocessing` class, it should also get the `sphx-glr-backref-type-class` and `sphx-glr-backref-instance` classes. Feel free to open a SG issue, we are currently working on fixing these things anyway.

**Comment by larsoner** [comment]
Opening an issue now. Feel free to merge this in the meantime if you want @drammock in case it takes us a while to get the SG fixes in

**Pull request merged**
