### PR TITLE
FIX: fixes 3305

### PR DESCRIPTION
**Pull request by clamus**
Correct the SNR computation in the simulation module

### CODE REVIEW

**Comment by agramfort** [comment]
thx @clamus 

can you eventually update a test?

please also update what's new page.

**Comment by clamus** [comment]
At the moment, simulation/evoked.py does't test the SNR. Should I include something that checks if the theoretical SNR is close to the the empirical one?

**Comment by agramfort** [comment]
Yes it would be great






On Tue, Jun 14, 2016 at 10:05 PM +0200, "Camilo Lamus" <notifications@github.com> wrote:












At the moment, simulation/evoked.py does't test the SNR. Should I include something that checks if the theoretical SNR is close to the the empirical one?

**Comment by Eric89GXL** [comment]
AppVeyor failure is unrelated. Is this ready to go from your end @clamus?

**Comment by clamus** [comment]
Yep, this is ready.

**Comment by agramfort** [comment]
thx @clamus

**Pull request merged**
