### PR TITLE
Fix Circle CI

### PR DESCRIPTION
**Pull request by teonbrooks**

### CODE REVIEW

**Comment by larsoner** [comment]
You need to touch the example to get it to run. Maybe we should do that and restart CircleCI a few times. Did you look at the CircleCI log from the failure I linked to in my other comment? It had some weird messages

**Comment by larsoner** [comment]
I'm going to disable it for now

https://circleci.com/gh/mne-tools/mne-python/12458?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

**Comment by larsoner** [comment]
I'll close this one, open new PR to rename back to `plot_lslclient_rt.py` when you are ready

**Comment by jasmainak** [comment]
The error log seems to tell me that there is some issue with pylsl and not just a random error ... I think users might hit it as well

**Pull request closed without merging**
