### PR TITLE
[MAINT, MRG] Move over tutorials

### PR DESCRIPTION
**Pull request by alexrockhill**
Fixes two items in https://github.com/mne-tools/mne-gui-addons/pull/7

### CODE REVIEW

**Comment by alexrockhill** [comment]
Hmm the failures are unrelated (OpenMEEG errors) but the links don't show up https://output.circle-artifacts.com/output/job/e7d5fa52-7811-47ff-9b77-0c15c89d0cd8/artifacts/0/dev/auto_tutorials/clinical/index.html

I checked the link addresses and they look okay so I'm not sure why that is, do you have a second to look @larsoner ?

**Comment by alexrockhill** [comment]
Is there no way to make it look like the other examples?

**Comment by larsoner** [comment]
I'm not sure we want to -- eventually you'll presumably have more examples over at mne-gui-addons, and we don't want to also have to add them here

**Comment by larsoner** [comment]
To me it's brittle/code dup to add both places but if you want to maintain it you can do it in RST. See how SG adds galleries and you can add the equivalent RST/HTML to the README here

**Comment by alexrockhill** [comment]
Hmmm, I gave this a look but I couldn't figure out how to make it look like the other examples without hooking into the sphinx-gallery commands. Are you thinking of how to do it with just the rst?

**Comment by larsoner** [comment]
Just trying to make it look similar somehow. Looking at one of the generated `index.rst` like `doc/auto_examples/io/index.rst` I see this pattern for the thumbnail containers:

```
.. _sphx_glr_auto_examples_io:

Input/Output
------------

blah blah

.. raw:: html

    <div class="sphx-glr-thumbnails">


.. START INDIVIDUAL THUMBNAIL

.. raw:: html

    <div class="sphx-glr-thumbcontainer" tooltip="Parse averaging information defined in Elekta Vectorview/TRIUX DACQ (data acquisition). Extract...">

.. only:: html

  .. image:: /auto_examples/io/images/thumb/sphx_glr_elekta_epochs_thumb.png
    :alt:

  :ref:`sphx_glr_auto_examples_io_elekta_epochs.py`

.. raw:: html

      <div class="sphx-glr-thumbnail-title">Getting averaging info from .fif files</div>
    </div>

.. END INDIVIDUAL THUMNAIL


.. raw:: html

    </div>
```

So I think if you were to add something like this at the bottom of README.txt it would work to make it look similar:
```
.. raw:: html

    <div class="sphx-glr-thumbnails">

.. raw:: html

    <div class="sphx-glr-thumbcontainer" tooltip="TODO_TOOLTIP">

.. only:: html

  .. image:: TODO_MNE_GUI_EXTERNAL_IMAGE_LINK
    :alt:

  :ref:`TODO_MNE_GUI_INTERSPHINX_REF`

.. raw:: html

      <div class="sphx-glr-thumbnail-title">TODO_TITLE</div>
    </div>

.. repeat as necessary, then close the parent div:

.. raw:: html

    </div>
```
Then these should show up above the ones that SG adds

**Comment by alexrockhill** [comment]
Awesome, thanks, I can do that

**Comment by alexrockhill** [comment]
That looks pretty good but it might be worth writing a function that hooks into SG so that things are handled more naturally. It didn't generate a redirect based on the xref also so I had to hardcode in the onclick event. I think it might be useful more broadly to decrease the documentation size in `mne-python` and put it in other, specialized repositories but keep one documentation so that people can find the specialized packages they're looking for.

image

**Comment by alexrockhill** [comment]
I think this is good to go for now once the circle CI builds (unrelated failure), then we can follow up with that aforementioned function if it seems important and time allows.

**Review by larsoner — APPROVED** [review]
Pushed a fix for the linking problem (it was a CSS issue) and added subheadings:

Screenshot from 2023-04-27 15-47-13

Will merge now!

**Pull request merged**
