### PR TITLE
FIX missing Axes3D import in viz._3d._plot_mpl_stc

### LINKED ISSUE #8810: 'matplotlib' backend for stc.plot is broken
#### Describe the bug

Missing

```python
from mpl_toolkits.mplot3d import Axes3
```

in `mne.viz._3d._plot_mpl_stc`

#### Steps to reproduce

Generic to any example

```python
data_path = somato.data_path()
subject = '01'
task = 'somato'
...
stc_mne = apply_inverse(evoked, inv, lambda2, method='MNE', pick_ori="normal",
                        return_residual=False, verbose=True)

brain = stc_mne.plot(subjects_dir=subjects_dir, hemi='rh', surface='inflated',
                     smoothing_steps='nearest', view_layout='vertical',
                     backend='matplotlib')
```

#### Expected results

A static plot using the `matplotlib` backend showing a 3D rendering of a surface.

#### Actual results

```python
Using control points [6.56993144e-11 7.80732925e-11 1.82440323e-10]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/miniconda3/envs/hnn_dev/lib/python3.7/site-packages/matplotlib/projections/__init__.py in get_projection_class(projection)
     57     try:
---> 58         return projection_registry.get_projection_class(projection)
     59     except KeyError:

~/miniconda3/envs/hnn_dev/lib/python3.7/site-packages/matplotlib/projections/__init__.py in get_projection_class(self, name)
     24         """
---> 25         return self._all_projection_types[name]
     26 

KeyError: '3d'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
~/src/git/hnn-core/examples/plot_simulate_somato.py in <module>
----> 1 stc_mne.plot(backend='matplotlib')

~/src/git/mne-python/mne/source_estimate.py in plot(self, subject, surface, hemi, colormap, time_label, smoothing_steps, transparent, alpha, time_viewer, subjects_dir, figure, views, colorbar, clim, cortex, size, background, foreground, initial_time, time_unit, backend, spacing, title, show_traces, src, volume_options, view_layout, add_data_kwargs, brain_kwargs, verbose)
    662             src=src, volume_options=volume_options, view_layout=view_layout,
    663             add_data_kwargs=add_data_kwargs, brain_kwargs=brain_kwargs,
--> 664             verbose=verbose)
    665         return brain
    666 

<decorator-gen-142> in plot_source_estimates(stc, subject, surface, hemi, colormap, time_label, smoothing_steps, transparent, alpha, time_viewer, subjects_dir, figure, views, colorbar, clim, cortex, size, background, foreground, initial_time, time_unit, backend, spacing, title, show_traces, src, volume_options, view_layout, add_data_kwargs, brain_kwargs, verbose)

~/src/git/mne-python/mne/viz/_3d.py in plot_source_estimates(stc, subject, surface, hemi, colormap, time_label, smoothing_steps, transparent, alpha, time_viewer, subjects_dir, figure, views, colorbar, clim, cortex, size, background, foreground, initial_time, time_unit, backend, spacing, title, show_traces, src, volume_options, view_layout, add_data_kwargs, brain_kwargs, verbose)
   1826         transparent=transparent)
   1827     if plot_mpl:
-> 1828         return _plot_mpl_stc(stc, spacing=spacing, **kwargs)
   1829     return _plot_stc(
   1830         stc, overlay_alpha=alpha, brain_alpha=alpha, vector_alpha=alpha,

~/src/git/mne-python/mne/viz/_3d.py in _plot_mpl_stc(***failed resolving arguments***)
   1524     time_label, times = _handle_time(time_label, time_unit, stc.times)
   1525     fig = plt.figure(figsize=(6, 6)) if figure is None else figure
-> 1526     ax = fig.gca(projection='3d')
   1527     hemi_idx = 0 if hemi == 'lh' else 1
   1528     surf = op.join(subjects_dir, subject, 'surf', '%s.%s' % (hemi, surface))

~/miniconda3/envs/hnn_dev/lib/python3.7/site-packages/matplotlib/figure.py in gca(self, **kwargs)
   1930 
   1931         # no axes found, so create one which spans the figure
-> 1932         return self.add_subplot(1, 1, 1, **kwargs)
   1933 
   1934     def sca(self, a):

~/miniconda3/envs/hnn_dev/lib/python3.7/site-packages/matplotlib/figure.py in add_subplot(self, *args, **kwargs)
   1394         else:
   1395             projection_class, kwargs, key = \
-> 1396                 self._process_projection_requirements(*args, **kwargs)
   1397 
   1398             # try to find the axes with this key in the stack

~/miniconda3/envs/hnn_dev/lib/python3.7/site-packages/matplotlib/figure.py in _process_projection_requirements(self, polar, projection, *args, **kwargs)
   1118 
   1119         if isinstance(projection, str) or projection is None:
-> 1120             projection_class = projections.get_projection_class(projection)
   1121         elif hasattr(projection, '_as_mpl_axes'):
   1122             projection_class, extra_kwargs = projection._as_mpl_axes()

~/miniconda3/envs/hnn_dev/lib/python3.7/site-packages/matplotlib/projections/__init__.py in get_projection_class(projection)
     58         return projection_registry.get_projection_class(projection)
     59     except KeyError:
---> 60         raise ValueError("Unknown projection %r" % projection)
     61 
     62 

ValueError: Unknown projection '3d'
```

#### Additional information

PR will follow...

### PR DESCRIPTION
**Pull request by cjayb**
#### Reference issue
Fixes #8810 .

#### What does this implement/fix?

Added the missing `from mpl_toolkits.mplot3d import Axes3`

#### Additional information

Note that I've also modified the same import in `plot_head_positions`:

```python
from mpl_toolkits.mplot3d import axes3d  # was this
from mpl_toolkits.mplot3d import Axes3  # surely should be this?
```

I found this while searching for the actual bug, and [remembered reading this](https://stackoverflow.com/questions/11529043/axes3d-vs-axes3d-matplotlib) recently.

### CODE REVIEW

**Comment by jasmainak** [comment]
how come this was not caught by any of the tests?

**Comment by agramfort** [comment]
was not caught because both axes3d and Axes3D are valid imports. Yet only Axes3D is what you want.

**Review by agramfort — APPROVED** [review]
we should also maybe backport this.

I know it was working before so we should see when this was changed / broken.

**Comment by larsoner** [comment]
@cjayb can you push a commit to update `doc/changes/latest.inc` in the bug section? Otherwise LGTM +1 for merge!

**Comment by cjayb** [comment]
The `Axes3D` is very sinister: its import needed to set up 3D backend functionality, but there's no code that actually calls it. Hence the flake8-related ignore comments too.

FYI we [were hoping](https://github.com/jonescompneurolab/hnn-core/pull/253) to bypass the need to add `pyvista` to `hnn_core` dependencies, yet have a 'pretty picture' in one of the examples. Given that the `mpl` backend lacks any faculties to add glyphs, we're likely to just comment out the 3d as optional. All we really want is to illustrate a point on the wm surface...

**Comment by larsoner** [comment]
@cjayb looks like something went wrong. Sorry if I messed things up by pushing a commit to update `latest.inc`. If you want I can take your wording and force-push a fix...

**Comment by cjayb** [comment]
Not sure what happened, go ahead and force-push, I’m offline!

**Comment by larsoner** [comment]
Thanks @cjayb !

**Pull request merged**
