### PR TITLE
WIP,FIX: pyvista 3d backend

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR fixes issues found in https://github.com/mne-tools/mne-python/pull/10166#issuecomment-1003691825

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
It's not ready for merge just now. I need to investigate why `_to_rgba` was necessary considering that the opacity was given as a separate parameter.

**Comment by GuillaumeFavelier** [comment]
For short, except particular cases (*i.e.* custom colormaps), `_to_rgb(alpha=True)` should not be necessary and `_to_rgb(alpha=False)` with the separate `opacity` parameter will work just fine.

This is now ready to merge from my side @agramfort, @larsoner 

---

I noticed 2 unrelated failures:

```
================================== FAILURES ===================================
______________________________ test_yule_walker _______________________________
C:\hostedtoolcache\windows\Python\3.9.9\x64\lib\site-packages\statsmodels\compat\pandas.py:61: in <module>
    from pandas import NumericIndex
E   ImportError: cannot import name 'NumericIndex' from 'pandas' (C:\hostedtoolcache\windows\Python\3.9.9\x64\lib\site-packages\pandas\__init__.py)

During handling of the above exception, another exception occurred:
mne\time_frequency\tests\test_ar.py:21: in test_yule_walker
    from statsmodels.regression.linear_model import yule_walker as sm_yw
C:\hostedtoolcache\windows\Python\3.9.9\x64\lib\site-packages\statsmodels\regression\__init__.py:1: in <module>
    from .linear_model import yule_walker
C:\hostedtoolcache\windows\Python\3.9.9\x64\lib\site-packages\statsmodels\regression\linear_model.py:35: in <module>
    from statsmodels.compat.pandas import Appender
C:\hostedtoolcache\windows\Python\3.9.9\x64\lib\site-packages\statsmodels\compat\pandas.py:65: in <module>
    from pandas import Int64Index as NumericIndex
<frozen importlib._bootstrap>:1055: in _handle_fromlist
    ???
C:\hostedtoolcache\windows\Python\3.9.9\x64\lib\site-packages\pandas\__init__.py:198: in __getattr__
    warnings.warn(
E   FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
```

**Comment by agramfort** [comment]
ok let's merge this one and look at pandas issue in what's next. It seems that statsmodels breaks with recent pandas. I think we need to look at cached installs or maybe min some dependency in test for now

**Comment by larsoner** [comment]
I would just add `pandas.Int64Index is deprecated` to the ignores for testing. Will open a PR for this

**Pull request merged**
