### PR TITLE
ENH: Include more realistic simulations to example for simulating raw data using subject anatomy

### PR DESCRIPTION
**Pull request by ikojcic**
The changes included in this PR are proposed in the discussion
of PR #6256 and #6261.

This PR changes the simulation of source time courses in the example for
simulating raw data using subject anatomy. Initially, sine wave was used for
source time courses and it was the same for each of the 4 simulation conditions.
In this PR, a new function is added which enables to generate source activity for
evoked responses, parametrized by latency and duration. Stcs are simulated for
a single condition at the time.

### CODE REVIEW

**Comment by ikojcic** [comment]
Do you think it might be good to also visualize:
- simulated stcs, e.g. with plot_sparse_source_estimates(src, stc_data, ...)
(I know that here simulated stcs are not sparse but the plots look nice.)
- evoked responses e.g. for 1 condition with something like:
evoked_al = epochs['auditory/left'].average()
evoked_al.plot(time_unit='s')

**Comment by agramfort** [comment]
@ikojcic I just pushed a couple of commits here.

**Comment by agramfort** [comment]
here is the rendered example: https://13359-1301584-gh.circle-artifacts.com/0/dev/auto_examples/simulation/plot_simulated_raw_data_using_subject_anatomy.html

I am bit puzzled to see how low is the noise with this simulation though.
Maybe it's because we assume iid noise ... if you have a suggestion let me know.

**Comment by agramfort** [comment]
thx @ikojcic

**Comment by ikojcic** [comment]
Sorry for the late response, for now I don’t have any useful ideas for the noise... I’ll let you know if I do, I can always make the changes with a new PR. Thank you for the modifications!

**Pull request merged**
