### PR TITLE
MRG: Update docstyle

### PR DESCRIPTION
**Pull request by Eric89GXL**
Can't continue until the skipping-option PR https://github.com/PyCQA/pydocstyle/pull/203 gets merged because `pydocstyle` (formerly pep257) parses .py files instead of loading modules, so our auto-generated docstrings raise false alarms.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
The `pydocstyle` folks have been pretty nonresponsive, I'll reopen if they start responding

**Comment by Eric89GXL** [comment]
The requisite `pydocstyle` PRs finally got merged, so I went through and made our docstrings (mostly) compliant. Ready for review/merge from my end

**Comment by jaeilepp** [comment]
Needs a rebase. Otherwise LGTM.

**Comment by Eric89GXL** [comment]
Rebased. @agramfort okay to merge once the CIs come back happy?

**Comment by agramfort** [comment]
thx @Eric89GXL

**Pull request merged**
