### PR TITLE
read_raw_FOO inconsistencies

### PR DESCRIPTION
**Pull request by massich**
During #6521 we found the following:

- `read_raw_brainvision(vhdr_fname=fname` rather than `read_raw_brainvision(input_fname=fname`
- nicolet, eeglab initialize locations to `nan` rather than `0`
- `test_egi.mff`, `scan41_short.cnt` has location information

So far this PR reveals them, we can choose to fix them all, some or none.

### CODE REVIEW

**Comment by sappelhoff** [comment]
I guess the BrainVision special case could be because we have three brainvision files: `.eeg, .vmrk, .vhdr` and to make it obvious that it's the header file (`.vhdr`) that people should point to it's called `vhdr_fname`?

but this could also be described in the docstring, so I think I would prefer the consistency (i.e., change the current way)

**Comment by massich** [comment]
I that if we check how people call it most of the calls are:
```py
read_raw_brainvision(filename)
```

I don't really see the point on having a different signature. To me, it could be called `input_fname` and error if it's not `.vhdr` file. Which is exactly what is tested here:

https://github.com/mne-tools/mne-python/blob/3f4ce3cd2cf522e7a826f352f65ed8440158c232/mne/io/brainvision/tests/test_brainvision.py#L328

But if it is the case that `.eeg, .vmrk, .vhdr` are a pack then it might be cool to be able to pass any of the 3 and get the proper result. (ofcourse a warning sayng xxx.eeg, we found xxx.vmrk we are using this instead). Something similar can be done in #6272

**Comment by sappelhoff** [comment]
> But if it is the case that .eeg, .vmrk, .vhdr are a pack then it might be cool to be able to pass any of the 3 and get the proper result.

yes, sounds good. `.vhdr` and `.vmrk` also point to the other files, see:

https://github.com/mne-tools/mne-python/blob/3f4ce3cd2cf522e7a826f352f65ed8440158c232/mne/io/brainvision/tests/data/test.vhdr#L6-L7

https://github.com/mne-tools/mne-python/blob/3f4ce3cd2cf522e7a826f352f65ed8440158c232/mne/io/brainvision/tests/data/test.vmrk#L5

`.eeg` is binary with no file pointers. But usually (as you already said), the triplet is being kept in the same directory with identical filesnames (and only extensions different) anyhow!

**Comment by agramfort** [comment]
for read_raw_brainvision and it's a way to show that the input_fname needed is the one ending with .vhdr
I don't think there is any reason to change this.

for nan or 0 I agree that we need to be consistent how we populate loc when no position is present. THis for me would be a bug fix.

> test_egi.mff, scan41_short.cnt has location information

I don't get the question

**Comment by massich** [comment]
> I don't get the question 

These are two examples of eeg files with location information. I was just logging. But the question would be what to do when set_montage and the montage-channels is not a supper set of raw-channels

**Comment by agramfort** [comment]
we need to make a decision here. Do we enforce the montage to be super set of the EEG channels or shall we set the locs only for the channels we provide without error.

**Comment by agramfort** [comment]
> But if it is the case that .eeg, .vmrk, .vhdr are a pack then it might be cool to be able to pass any of the 3 and get the proper result.

I would say no. Just tell users they need to pass the .vhdr file

**Comment by larsoner** [comment]
My vote would be to at least warn if it's a subset. If we want to be even safer, `set_montage(..., allow_subset=False)` by default which raises an error to be safe, and people can do `allow_subset=True` if they know what they are doing and want to only operate on a subset of the channels marked as EEG.

**Comment by agramfort** [comment]
that would fly but we need to make sure we don't break backward
compatibility

>

**Comment by larsoner** [comment]
We can maintain it with a standard deprecation cycle `allow_subset=None` meaning "'warn' in 0.19, False in 0.20, set explicitly to True, 'warn', or False to avoid deprecation warning"

**Comment by massich** [comment]
To sum up:
- parameter name we said is fine,
- the 0 nan thing is already exposed and documented in #6521 
- the sub/super set behaviour would be defined somwhere else.

So, closing

**Pull request closed without merging**
