### PR TITLE
FIX: set_3d_view

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR updates the plotter in the `set_3d_view` routine.

Closes https://github.com/mne-tools/mne-python/issues/8562

### CODE REVIEW

**Comment by agramfort** [comment]
this bug was in the last release? if so we need to document the fix in what's new

**Comment by GuillaumeFavelier** [comment]
It's fixed now @rob-luke :

From https://23798-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/source-modeling/plot_dipole_orientations.html#sphx-glr-auto-tutorials-source-modeling-plot-dipole-orientations-py:

image

From https://23798-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/preprocessing/plot_70_fnirs_processing.html#sphx-glr-auto-tutorials-preprocessing-plot-70-fnirs-processing-py:

image

> document the fix in what's new

Will do

**Review by rob-luke — APPROVED** [review]
I checked a few docs and they look good now

**Comment by agramfort** [comment]
thanks @GuillaumeFavelier for the quick fix !

**Pull request merged**
