### PR TITLE
[MRG] Enable anti-aliasing in plot_raw

### LINKED ISSUE #4434: Anti-aliasing in plots
I've noticed that most plots in MNE use the MPL default of `antialiasing=True` except for `plot_raw`, which specifically disables antialiasing. I'd argue that anti-aliasing makes for a much nicer look (for example `plot_pds` is a really nice representation of the spectrum for all channels), so I'd enable it also in `plot_raw`. What is the reason that this was disabled? With the current behavior, lines appear rather thick on some platforms, which doesn't appear to be the case if antialiasing is turned on.

### PR DESCRIPTION
**Pull request by cbrnr**
Fix #4434

### CODE REVIEW

**Comment by agramfort** [comment]
+1 for MRG

**Comment by cbrnr** [comment]
Should we add a whats_new entry just in case?

**Comment by Eric89GXL** [comment]
> Should we add a whats_new entry just in case?

Sure, why not

**Comment by agramfort** [comment]
it should be done with Epochs plotter too before we forget.

**Comment by Eric89GXL** [comment]
@cbrnr can you do that in this PR, too?

**Comment by cbrnr** [comment]
Sure. What about [line 1040 in `viz/_3d.py`](https://github.com/mne-tools/mne-python/blob/master/mne/viz/_3d.py#L1040)?

**Comment by agramfort** [comment]
try to see the impact

**Comment by cbrnr** [comment]
@agramfort this requires mayavi which currently doesn't work in Python 3. I don't have the time to set up a Python 2 env just to test this, so I suggest that we leave this setting as it is (unless someone else can check the plot with and without antialiasing and let me know if this can also be set to `True`).

**Comment by agramfort** [comment]
it does **not** require mayavi. it's in the function:

def _smooth_plot(this_time, params):
"""Smooth source estimate data and plot with mpl."""

that is meant to work with matplotlib

also mayavi works on python 3. With conda I do:

conda install pyqt=4.11.4 qt=4.8.7
conda install -c satra vtk
pip install mayavi

and it should work assuming you use a mac.

**Comment by cbrnr** [comment]
OK, I'll try that. All tests using `_smooth_plot` have the `@require_mayavi` decorator, which is the easiest way for me to produce a plot with this function.

**Comment by agramfort** [comment]
that's bad not to be able to test without mayavi. This should be fixed.

**Comment by cbrnr** [comment]
```
~ $ conda install pyqt=4.11.4 qt=4.8.7
Fetching package metadata .........
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - pyqt 4.11.4* -> python 2.7* -> openssl 1.0.1*
  - python 3.6*
```

Let's not worry about this in this PR. I suggest to open a new issue where we can discuss setting `antialiased=True` also for this type of plot.

**Comment by agramfort** [comment]
ok thx @cbrnr

**Pull request merged**
