### PR TITLE
FIX: Fix gamma_map

### LINKED ISSUE #2702: BUG: Instability of gamma_map tests
We have had problems in the past with `gamma_map` tests being sensitive to changes in packages (e.g., Anaconda updates) and they cropped up again recently. Specifically there are now two skipped checks in `test_gamma_map.py` that should be fixed at some point.

### PR DESCRIPTION
**Pull request by Eric89GXL**
@agramfort I think this should make the test more robust (and restores a broken one!). Let me know if you think it's too lenient.

Closes #2702.

### CODE REVIEW

**Comment by agramfort** [comment]
fine with me but travis is not happy yet

**Comment by Eric89GXL** [comment]
Yeah, seems like the code is broken worse than I expected :(

**Comment by Eric89GXL** [comment]
@agramfort unfortunately I think you'll need to take over. The STCs on my system have a handful of verts per hemi (e.g., `(4, 30)` for left and right hemi), but on the failed builds they have e.g. `(3956, 3972)`.

**Comment by Eric89GXL** [comment]
...and I can't reproduce locally with my Anaconda setup :(

**Comment by Eric89GXL** [comment]
It appears as though the issue has been magically fixed.

**Pull request closed without merging**
