### PR TITLE
fix HTML repr table rendering

### LINKED ISSUE #12775: HTML repr tables have really bad text contrast ratios
as seen in the [Eyetracking tutorial:](https://mne.tools/stable/auto_tutorials/preprocessing/90_eyetracking_data.html)

Screenshot 2024-08-05 at 9 06 49 AM

_Originally posted by @scott-huberty in https://github.com/mne-tools/mne-python/issues/12750#issuecomment-2269424078_

### PR DESCRIPTION
**Pull request by drammock**
closes #12775 

WIP because I haven't addressed appearance in notebooks or IDEs yet. But in the meantime at least y'all can see how it looks in the built docs, and offer feedback.

### CODE REVIEW

**Comment by drammock** [comment]
here's what the repr HTML tables look like on built docs:

https://output.circle-artifacts.com/output/job/df0a833c-b387-4034-a9e4-f3d59d80ef3f/artifacts/0/html/auto_tutorials/raw/20_event_arrays.html#sphx-glr-auto-tutorials-raw-20-event-arrays-py

The buttons for showing bad channels are a bit wonky; I'll have to work on that. Pushing commits now that make it look ok in Jupyter notebook. I tried tackling VSCode interactive pane too... but the whole notebook gets hidden in an `iframe` and I can't seem to access the individual DOM elements in the notebook output cells via the built-in developer tools pane... maybe @hoechenberger can point me in the right direction (or just push some commits).

**Comment by larsoner** [comment]
@drammock I marked for 1.8, this is probably a blocker right?

**Comment by drammock** [comment]
> @drammock I marked for 1.8, this is probably a blocker right?

could also just backport it afterwards I guess?  I will try to finish today but can't promise it.

**Comment by larsoner** [comment]
Yeah backporting seems okay!

**Comment by drammock** [comment]
OK here are some screenshots:

### Sphinx

built-docs-dark

built-docs

### Jupyter

juypter-dark

jupyter-light

### VSCode

vscode-dark

vscode-light

**Comment by hoechenberger** [comment]
Aren't the carets in Jupyter and VS Code swapped between "opened" and "collapsed" state?

**Comment by hoechenberger** [comment]
just want to add, i think this is a great job, @drammock 
I'm currently in a hiking trip in the mountains with limited internet access (and only through my phone), so cannot really test or provide thorough feedback until next week or so

**Comment by drammock** [comment]
> Aren't the carets in Jupyter and VS Code swapped between "opened" and "collapsed" state?

oops yes, good catch.

**Comment by drammock** [comment]
@hoechenberger @larsoner this one is ready!

**Comment by larsoner** [comment]
I looked at the examples and reports and they look great, thanks @drammock !

**Pull request merged**
