### PR TITLE
MRG, BUG: Fix Xdawn check

### LINKED ISSUE #8493: test_xdawn_regularization fails on Fedora 34 (rawhide)
Hey all!

the test: `test_dawn::test_xdawn_regularization` is currently failing in Fedora 34, with no reason per se. The test works fine on Fedora 33.

#### Describe the bug

The build logs are below:

1. [Fedora 33](https://major.fedorapeople.org/python-mne/f33_build.log)
2. [Fedora 34 (failing)](https://major.fedorapeople.org/python-mne/f34_build.log)
 
Failure:

```
mne/preprocessing/tests/test_xdawn.py:203: in test_xdawn_regularization
    xd.fit(epochs)
E   Failed: DID NOT RAISE <class 'ValueError'>
```
There's a bunch of log statements as well:

```
----------------------------- Captured stdout call -----------------------------
Computing rank from data with rank='full'
    MEG: rank 39 from info
    Created an SSP operator (subspace dimension = 3)
Reducing data rank from 39 -> 39
Estimating covariance using OAS
Done.
Computing rank from data with rank='full'
    MEG: rank 39 from info
    Created an SSP operator (subspace dimension = 3)
Reducing data rank from 39 -> 39
Estimating covariance using OAS
Done.
Computing rank from data with rank='full'
    MEG: rank 39 from info
    Created an SSP operator (subspace dimension = 3)
Reducing data rank from 39 -> 39
Estimating covariance using OAS
Done.
Computing rank from data with rank='full'
    MEG: rank 39 from info
    Created an SSP operator (subspace dimension = 3)
Reducing data rank from 39 -> 39
Estimating covariance using SHRINKAGE
Done.
Computing rank from data with rank='full'
    MEG: rank 39 from info
    Created an SSP operator (subspace dimension = 3)
Reducing data rank from 39 -> 39
Estimating covariance using SHRINKAGE
Done.
Computing rank from data with rank='full'
    MEG: rank 39 from info
    Created an SSP operator (subspace dimension = 3)
Reducing data rank from 39 -> 39
Estimating covariance using SHRINKAGE
Done.
Computing rank from data with rank='full'
    MEG: rank 39 from info
    Created an SSP operator (subspace dimension = 3)
Reducing data rank from 39 -> 39
Estimating covariance using SHRINKAGE
Done.
Computing rank from data with rank='full'
    MEG: rank 39 from info
    Created an SSP operator (subspace dimension = 3)
Reducing data rank from 39 -> 39
Estimating covariance using LEDOIT_WOLF
Done.
Computing rank from data with rank='full'
    MEG: rank 39 from info
    Created an SSP operator (subspace dimension = 3)
Reducing data rank from 39 -> 39
Estimating covariance using LEDOIT_WOLF
Done.
Computing rank from data with rank='full'
    MEG: rank 39 from info
    Created an SSP operator (subspace dimension = 3)
Reducing data rank from 39 -> 39
Estimating covariance using OAS
Done.
Computing rank from data with rank='full'
    MEG: rank 39 from info
    Created an SSP operator (subspace dimension = 3)
Reducing data rank from 39 -> 39
Estimating covariance using OAS
Done.
Computing rank from data with rank='full'
    MEG: rank 39 from info
    Created an SSP operator (subspace dimension = 3)
Reducing data rank from 39 -> 39
Estimating covariance using SHRINKAGE
Done.
Computing rank from data with rank='full'
    MEG: rank 39 from info
    Created an SSP operator (subspace dimension = 3)
Reducing data rank from 39 -> 39
Estimating covariance using SHRINKAGE
Done.
Computing rank from data with rank='full'
    MEG: rank 39 from info
    Created an SSP operator (subspace dimension = 3)
Reducing data rank from 39 -> 39
Estimating covariance using SHRINKAGE
Done.
Computing rank from data with rank='full'
    MEG: rank 39 from info
    Created an SSP operator (subspace dimension = 3)
Reducing data rank from 39 -> 39
Estimating covariance using DIAGONAL_FIXED
    MAG regularization : 0.1
    GRAD regularization : 0.1
Done.
Computing rank from data with rank='full'
    MEG: rank 39 from info
    Created an SSP operator (subspace dimension = 3)
Reducing data rank from 39 -> 39
Estimating covariance using DIAGONAL_FIXED
    MAG regularization : 0.1
    GRAD regularization : 0.1
Done.
Computing rank from data with rank='full'
    MEG: rank 39 from info
    Created an SSP operator (subspace dimension = 3)
Reducing data rank from 39 -> 39
Estimating covariance using DIAGONAL_FIXED
    MAG regularization : 0.1
    GRAD regularization : 0.1
Done.
Computing rank from data with rank='full'
    MEG: rank 39 from info
    Created an SSP operator (subspace dimension = 3)
Reducing data rank from 39 -> 39
Estimating covariance using EMPIRICAL
Done.
Computing rank from data with rank='full'
    MEG: rank 39 from info
    Created an SSP operator (subspace dimension = 3)
Reducing data rank from 39 -> 39
Estimating covariance using EMPIRICAL
Done.
Computing rank from data with rank='full'
    MEG: rank 39 from info
    Created an SSP operator (subspace dimension = 3)
Reducing data rank from 39 -> 39
Estimating covariance using EMPIRICAL
Done.
```

#### Steps to reproduce

Run the test in a Fedora 34 environment

#### Expected results

The test should not fail. It should throw a ValueError

#### Additional information

Since Fedora 34 is the bleeding edge, and is not stable, it is likely that it might get fixed in a later release. It is also possible it is due to some internal library (probably sklearn) and their compatibility with F34. I will be using this tracker to keep an eye on it, and will update this ticket regularly.

### PR DESCRIPTION
**Pull request by larsoner**
Closes #8493

### CODE REVIEW

**Comment by larsoner** [comment]
@Aniket-Pradhan can you try this branch? If everything works, we can merge and backport then release a 0.21.2 so you can use that with Fedora

**Comment by larsoner** [comment]
Okay looking at the results I think this is not the right fix. I'm going to change it just to have the fix from recent CI PRs

**Comment by Aniket-Pradhan** [comment]
> @Aniket-Pradhan can you try this branch? If everything works, we can merge and backport then release a 0.21.2 so you can use that with Fedora

Sure, I can test this branch in some time.

Although, before releasing 0.21.2 I was wondering if I could bring up some more issues I was getting for Fedora 33. I shall create a new issue ticket for that, I guess

**Comment by larsoner** [comment]
New issue or comment here, either way is fine. I'll probably just push commits to this PR to get everything working

**Comment by Aniket-Pradhan** [comment]
So, the `xdawn` test is now working fine, for both F33 and F34.

Although a lot of tests are failing for F33 which are noted below. The whole build log can be found [here](https://kojipkgs.fedoraproject.org//work/tasks/611/55250611/build.log).

I tried to run these tests on my local installation, and they worked fine, but they are failing on the VM, so probably I am missing something. I am not sure what am I missing, a dependency, or probably the VM is using a version of a library that is incompatible with the tests.

The test logs:

```
____________________________ test_interpolation_meg ____________________________
mne/channels/tests/test_interpolation.py:197: in test_interpolation_meg
    assert np.corrcoef(data1, data2)[0, 1] > thresh
E   assert 0.6998407074799566 > 0.7
----------------------------- Captured stdout call -----------------------------
Opening raw data file /builddir/build/BUILD/mne-python-0.21.1/mne/channels/tests/../../io/tests/data/test_raw.fif...
    Read a total of 3 projection items:
        PCA-v1 (1 x 102)  idle
        PCA-v2 (1 x 102)  idle
        PCA-v3 (1 x 102)  idle
    Range : 25800 ... 40199 =     42.956 ...    66.930 secs
Ready.
Not setting metadata
Not setting metadata
7 matching events found
Applying baseline correction (mode: mean)
Created an SSP operator (subspace dimension = 3)
3 projection items activated
Loading data for 7 events and 421 original time points ...
0 bad epochs dropped
Reading 0 ... 60  =      0.000 ...     0.100 secs...
Interpolating bad channels
    Automatic origin fit: head of radius 91.0 mm
    Computing dot products for 98 MEG channels...
    Computing cross products for 98 → 1 MEG channel...
    Preparing the mapping matrix...
    Truncating at 74/98 components to omit less than 0.0001 (9e-05)
Creating RawArray with float64 data, n_channels=100, n_times=421
    Range : 0 ... 420 =      0.000 ...     0.699 secs
Ready.
Interpolating bad channels
    Automatic origin fit: head of radius 91.0 mm
    Computing dot products for 99 MEG channels...
    Computing cross products for 99 → 1 MEG channel...
    Preparing the mapping matrix...
    Truncating at 74/99 components to omit less than 0.0001 (9.8e-05)
Interpolating bad channels
    Automatic origin fit: head of radius 91.0 mm
    Computing dot products for 99 MEG channels...
    Computing cross products for 99 → 1 MEG channel...
    Preparing the mapping matrix...
    Truncating at 74/99 components to omit less than 0.0001 (9.8e-05)
_______________________________ test_find_layout _______________________________
mne/channels/tests/test_layout.py:255: in test_find_layout
    raw_kit = read_raw_kit(fname_kit_157)
mne/io/kit/kit.py:903: in read_raw_kit
    return RawKIT(input_fname=input_fname, mrk=mrk, elp=elp, hsp=hsp,
<decorator-gen-211>:24: in __init__
    ???
mne/io/kit/kit.py:134: in __init__
    info, kit_info = get_kit_info(
<decorator-gen-213>:24: in get_kit_info
    ???
mne/io/kit/kit.py:495: in get_kit_info
    dirs.extend(_read_dir(fid) for _ in range(dirs[0]['count'] - 1))
mne/io/kit/kit.py:495: in <genexpr>
    dirs.extend(_read_dir(fid) for _ in range(dirs[0]['count'] - 1))
mne/io/kit/kit.py:459: in _read_dir
    size=np.fromfile(fid, np.int32, 1)[0],
E   IndexError: index 0 is out of bounds for axis 0 with size 0
----------------------------- Captured stdout call -----------------------------
    Read a total of 3 projection items:
        PCA-v1 (1 x 102)  idle
        PCA-v2 (1 x 102)  idle
        PCA-v3 (1 x 102)  idle
    Read 5 compensation matrices
Extracting SQD Parameters from /builddir/build/BUILD/mne-python-0.21.1/mne/channels/tests/../../io/kit/tests/data/test.sqd...
Creating Raw.info structure...
_____________________________ test_edf_data_broken _____________________________
mne/io/edf/tests/test_edf.py:130: in test_edf_data_broken
    raw = _test_raw_reader(read_raw_edf, input_fname=edf_path,
mne/io/tests/test_raw.py:189: in _test_raw_reader
    assert_array_less(data, maxval)
E   AssertionError: 
E   Arrays are not less-ordered
E   
E   Mismatched elements: 12283 / 417792 (2.94%)
E   Max absolute difference: 0.05090099
E   Max relative difference: 5.09009855
E    x: array([[0.001702, 0.000423, 0.000769, ..., 0.002524, 0.001299, 0.000917],
E          [0.002138, 0.000244, 0.000334, ..., 0.001169, 0.000199, 0.000183],
E          [0.004641, 0.000301, 0.000377, ..., 0.002903, 0.001678, 0.001296],...
E    y: array(0.01)
____________________________ test_parse_annotation _____________________________
mne/io/edf/tests/test_edf.py:197: in test_parse_annotation
    assert_equal(np.column_stack((onset, duration, description)),
E   AssertionError: 
E   Arrays are not equal
E   
E   (shapes (3, 3), (6, 3) mismatch)
E    x: array([['1.0', '4402.0', '0onhtni'],
E          ['1.0', '4402.0', 'g\x00\x00\x00\x001+08.0\x152525.A'],
E          ['1.0', '4402.0', 'npae']], dtype='>U32')
E    y: array([['180.0', '0.0', 'Lights off'],
E          ['180.0', '0.0', 'Close door'],
E          ['180.0', '0.0', 'Lights off'],...
___________________ test_find_events_backward_compatibility ____________________
mne/io/edf/tests/test_edf.py:212: in test_find_events_backward_compatibility
    event_id.pop('start')
E   KeyError: 'start'
----------------------------- Captured stdout call -----------------------------
Extracting EDF parameters from /builddir/build/BUILD/mne-python-0.21.1/mne/io/edf/tests/data/test.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 3071  =      0.000 ...     5.998 secs...
_______________________________ test_read_annot ________________________________
mne/io/edf/tests/test_edf.py:292: in test_read_annot
    _assert_annotations_equal(annotation, EXPECTED_ANNOTATIONS)
mne/io/edf/tests/test_edf.py:251: in _assert_annotations_equal
    assert_array_equal(a.onset, b.onset)
E   AssertionError: 
E   Arrays are not equal
E   
E   (shapes (3,), (6,) mismatch)
E    x: array([1., 1., 1.])
E    y: array([   3.14,  180.  ,  180.  ,  180.  ,  180.  , 1800.2 ])
_________________________________ test_io_egi __________________________________
mne/io/egi/tests/test_egi.py:143: in test_io_egi
    raw = read_raw_egi(egi_fname, include=None)
<decorator-gen-182>:24: in read_raw_egi
    ???
mne/io/egi/egi.py:153: in read_raw_egi
    return RawEGI(input_fname, eog, misc, include, exclude, preload,
<decorator-gen-183>:24: in __init__
    ???
mne/io/egi/egi.py:170: in __init__
    egi_info = _read_header(fid)
mne/io/egi/egi.py:52: in _read_header
    raise RuntimeError('Floating point precision is undefined.')
E   RuntimeError: Floating point precision is undefined.
----------------------------- Captured stdout call -----------------------------
Reading EGI header from /builddir/build/BUILD/mne-python-0.21.1/mne/io/egi/tests/data/test_egi.raw...
_________________________________ test_io_mrk __________________________________
mne/io/kit/tests/test_coreg.py:26: in test_io_mrk
    pts = read_mrk(mrk_fname)
mne/io/kit/coreg.py:40: in read_mrk
    mrk_count = unpack('i', fid.read(KIT.INT))[0]
E   struct.error: unpack requires a buffer of 4 bytes
_________________________________ test_epochs __________________________________
mne/io/kit/tests/test_kit.py:205: in test_epochs
    raw = read_raw_kit(sqd_path, stim=None)
mne/io/kit/kit.py:903: in read_raw_kit
    return RawKIT(input_fname=input_fname, mrk=mrk, elp=elp, hsp=hsp,
<decorator-gen-211>:24: in __init__
    ???
mne/io/kit/kit.py:134: in __init__
    info, kit_info = get_kit_info(
<decorator-gen-213>:24: in get_kit_info
    ???
mne/io/kit/kit.py:495: in get_kit_info
    dirs.extend(_read_dir(fid) for _ in range(dirs[0]['count'] - 1))
mne/io/kit/kit.py:495: in <genexpr>
    dirs.extend(_read_dir(fid) for _ in range(dirs[0]['count'] - 1))
mne/io/kit/kit.py:459: in _read_dir
    size=np.fromfile(fid, np.int32, 1)[0],
E   IndexError: index 0 is out of bounds for axis 0 with size 0
----------------------------- Captured stdout call -----------------------------
Extracting SQD Parameters from /builddir/build/BUILD/mne-python-0.21.1/mne/io/kit/tests/data/test.sqd...
Creating Raw.info structure...
_______________________________ test_raw_events ________________________________
mne/io/kit/tests/test_kit.py:222: in test_raw_events
    raw = read_raw_kit(sqd_path)
mne/io/kit/kit.py:903: in read_raw_kit
    return RawKIT(input_fname=input_fname, mrk=mrk, elp=elp, hsp=hsp,
<decorator-gen-211>:24: in __init__
    ???
mne/io/kit/kit.py:134: in __init__
    info, kit_info = get_kit_info(
<decorator-gen-213>:24: in get_kit_info
    ???
mne/io/kit/kit.py:495: in get_kit_info
    dirs.extend(_read_dir(fid) for _ in range(dirs[0]['count'] - 1))
mne/io/kit/kit.py:495: in <genexpr>
    dirs.extend(_read_dir(fid) for _ in range(dirs[0]['count'] - 1))
mne/io/kit/kit.py:459: in _read_dir
    size=np.fromfile(fid, np.int32, 1)[0],
E   IndexError: index 0 is out of bounds for axis 0 with size 0
----------------------------- Captured stdout call -----------------------------
Extracting SQD Parameters from /builddir/build/BUILD/mne-python-0.21.1/mne/io/kit/tests/data/test.sqd...
Creating Raw.info structure...
_________________________________ test_ch_loc __________________________________
mne/io/kit/tests/test_kit.py:246: in test_ch_loc
    raw_py = read_raw_kit(sqd_path, mrk_path, elp_txt_path, hsp_txt_path,
mne/io/kit/kit.py:903: in read_raw_kit
    return RawKIT(input_fname=input_fname, mrk=mrk, elp=elp, hsp=hsp,
<decorator-gen-211>:24: in __init__
    ???
mne/io/kit/kit.py:134: in __init__
    info, kit_info = get_kit_info(
<decorator-gen-213>:24: in get_kit_info
    ???
mne/io/kit/kit.py:495: in get_kit_info
    dirs.extend(_read_dir(fid) for _ in range(dirs[0]['count'] - 1))
mne/io/kit/kit.py:495: in <genexpr>
    dirs.extend(_read_dir(fid) for _ in range(dirs[0]['count'] - 1))
mne/io/kit/kit.py:459: in _read_dir
    size=np.fromfile(fid, np.int32, 1)[0],
E   IndexError: index 0 is out of bounds for axis 0 with size 0
----------------------------- Captured stdout call -----------------------------
Extracting SQD Parameters from /builddir/build/BUILD/mne-python-0.21.1/mne/io/kit/tests/data/test.sqd...
Creating Raw.info structure...
_________________________________ test_hsp_elp _________________________________
mne/io/kit/tests/test_kit.py:275: in test_hsp_elp
    raw_txt = read_raw_kit(sqd_path, mrk_path, elp_txt_path, hsp_txt_path)
mne/io/kit/kit.py:903: in read_raw_kit
    return RawKIT(input_fname=input_fname, mrk=mrk, elp=elp, hsp=hsp,
<decorator-gen-211>:24: in __init__
    ???
mne/io/kit/kit.py:134: in __init__
    info, kit_info = get_kit_info(
<decorator-gen-213>:24: in get_kit_info
    ???
mne/io/kit/kit.py:495: in get_kit_info
    dirs.extend(_read_dir(fid) for _ in range(dirs[0]['count'] - 1))
mne/io/kit/kit.py:495: in <genexpr>
    dirs.extend(_read_dir(fid) for _ in range(dirs[0]['count'] - 1))
mne/io/kit/kit.py:459: in _read_dir
    size=np.fromfile(fid, np.int32, 1)[0],
E   IndexError: index 0 is out of bounds for axis 0 with size 0
----------------------------- Captured stdout call -----------------------------
Extracting SQD Parameters from /builddir/build/BUILD/mne-python-0.21.1/mne/io/kit/tests/data/test.sqd...
Creating Raw.info structure...
________________________________ test_decimate _________________________________
mne/io/kit/tests/test_kit.py:308: in test_decimate
    raw = read_raw_kit(sqd_path, mrk_path, elp_txt_path, sphere_hsp_path)
mne/io/kit/kit.py:903: in read_raw_kit
    return RawKIT(input_fname=input_fname, mrk=mrk, elp=elp, hsp=hsp,
<decorator-gen-211>:24: in __init__
    ???
mne/io/kit/kit.py:134: in __init__
    info, kit_info = get_kit_info(
<decorator-gen-213>:24: in get_kit_info
    ???
mne/io/kit/kit.py:495: in get_kit_info
    dirs.extend(_read_dir(fid) for _ in range(dirs[0]['count'] - 1))
mne/io/kit/kit.py:495: in <genexpr>
    dirs.extend(_read_dir(fid) for _ in range(dirs[0]['count'] - 1))
mne/io/kit/kit.py:459: in _read_dir
    size=np.fromfile(fid, np.int32, 1)[0],
E   IndexError: index 0 is out of bounds for axis 0 with size 0
----------------------------- Captured stdout call -----------------------------
Extracting SQD Parameters from /builddir/build/BUILD/mne-python-0.21.1/mne/io/kit/tests/data/test.sqd...
Creating Raw.info structure...
________________________________ test_pick_refs ________________________________
mne/io/tests/test_pick.py:99: in test_pick_refs
    raw_kit = read_raw_kit(sqd_path, mrk_path, elp_path, hsp_path)
mne/io/kit/kit.py:903: in read_raw_kit
    return RawKIT(input_fname=input_fname, mrk=mrk, elp=elp, hsp=hsp,
<decorator-gen-211>:24: in __init__
    ???
mne/io/kit/kit.py:134: in __init__
    info, kit_info = get_kit_info(
<decorator-gen-213>:24: in get_kit_info
    ???
mne/io/kit/kit.py:495: in get_kit_info
    dirs.extend(_read_dir(fid) for _ in range(dirs[0]['count'] - 1))
mne/io/kit/kit.py:495: in <genexpr>
    dirs.extend(_read_dir(fid) for _ in range(dirs[0]['count'] - 1))
mne/io/kit/kit.py:459: in _read_dir
    size=np.fromfile(fid, np.int32, 1)[0],
E   IndexError: index 0 is out of bounds for axis 0 with size 0
----------------------------- Captured stdout call -----------------------------
Extracting SQD Parameters from /builddir/build/BUILD/mne-python-0.21.1/mne/io/tests/../kit/tests/data/test.sqd...
Creating Raw.info structure...
_______________________ test_read_raw_supported[fname3] ________________________
mne/io/tests/test_read_raw.py:35: in test_read_raw_supported
    read_raw(fname)
mne/io/_read_raw.py:82: in read_raw
    return readers[ext](fname, preload=preload, verbose=verbose, **kwargs)
mne/io/kit/kit.py:903: in read_raw_kit
    return RawKIT(input_fname=input_fname, mrk=mrk, elp=elp, hsp=hsp,
<decorator-gen-211>:24: in __init__
    ???
mne/io/kit/kit.py:134: in __init__
    info, kit_info = get_kit_info(
<decorator-gen-213>:24: in get_kit_info
    ???
mne/io/kit/kit.py:495: in get_kit_info
    dirs.extend(_read_dir(fid) for _ in range(dirs[0]['count'] - 1))
mne/io/kit/kit.py:495: in <genexpr>
    dirs.extend(_read_dir(fid) for _ in range(dirs[0]['count'] - 1))
mne/io/kit/kit.py:459: in _read_dir
    size=np.fromfile(fid, np.int32, 1)[0],
E   IndexError: index 0 is out of bounds for axis 0 with size 0
----------------------------- Captured stdout call -----------------------------
Extracting SQD Parameters from /builddir/build/BUILD/mne-python-0.21.1/mne/io/kit/tests/data/test.sqd...
Creating Raw.info structure...
______________________________ test_other_systems ______________________________
mne/preprocessing/tests/test_maxwell.py:235: in test_other_systems
    raw_kit = read_raw_kit(sqd_path, mrk_path, elp_path, hsp_path)
mne/io/kit/kit.py:903: in read_raw_kit
    return RawKIT(input_fname=input_fname, mrk=mrk, elp=elp, hsp=hsp,
<decorator-gen-211>:24: in __init__
    ???
mne/io/kit/kit.py:134: in __init__
    info, kit_info = get_kit_info(
<decorator-gen-213>:24: in get_kit_info
    ???
mne/io/kit/kit.py:495: in get_kit_info
    dirs.extend(_read_dir(fid) for _ in range(dirs[0]['count'] - 1))
mne/io/kit/kit.py:495: in <genexpr>
    dirs.extend(_read_dir(fid) for _ in range(dirs[0]['count'] - 1))
mne/io/kit/kit.py:459: in _read_dir
    size=np.fromfile(fid, np.int32, 1)[0],
E   IndexError: index 0 is out of bounds for axis 0 with size 0
----------------------------- Captured stdout call -----------------------------
Extracting SQD Parameters from /builddir/build/BUILD/mne-python-0.21.1/mne/preprocessing/tests/../../io/kit/tests/data/test.sqd...
Creating Raw.info structure...
___________________________ test_plot_ica_components ___________________________
mne/viz/tests/test_ica.py:91: in test_plot_ica_components
    _fake_click(fig, fig.axes[1], (0., 0.), xform='data')
mne/viz/utils.py:1442: in _fake_click
    func(guiEvent=None)
/usr/lib64/python3.9/site-packages/matplotlib/backend_bases.py:1854: in button_press_event
    self.callbacks.process(s, mouseevent)
/usr/lib64/python3.9/site-packages/matplotlib/cbook/__init__.py:224: in process
    func(*args, **kwargs)
mne/viz/topomap.py:1231: in onclick_topo
    ica.plot_properties(inst, picks=ic, show=True,
mne/preprocessing/ica.py:1746: in plot_properties
    return plot_ica_properties(self, inst, picks=picks, axes=axes,
mne/viz/ica.py:475: in plot_ica_properties
    fig = _plot_ica_properties(
mne/viz/ica.py:193: in _plot_ica_properties
    kde_ /= kde_.max()
E   RuntimeWarning: invalid value encountered in true_divide
----------------------------- Captured stdout call -----------------------------
Opening raw data file /builddir/build/BUILD/mne-python-0.21.1/mne/viz/tests/../../io/tests/data/test_raw.fif...
    Read a total of 3 projection items:
        PCA-v1 (1 x 102)  idle
        PCA-v2 (1 x 102)  idle
        PCA-v3 (1 x 102)  idle
    Range : 25800 ... 40199 =     42.956 ...    66.930 secs
Ready.
    366 x 366 full covariance (kind = 1) found.
    Read a total of 4 projection items:
        PCA-v1 (1 x 102) active
        PCA-v2 (1 x 102) active
        PCA-v3 (1 x 102) active
        Average EEG reference (1 x 60) active
Fitting ICA to data using 9 channels (please be patient, this may take a while)
    Created an SSP operator (subspace dimension = 3)
Computing rank from covariance with rank=None
    Using tolerance 1e-15 (2.2e-16 eps * 9 dim * 0.51  max singular value)
    Estimated rank (mag + grad): 6
    MEG: rank 6 computed from 9 data channels with 3 projectors
    Setting small MEG eigenvalues to zero (without PCA)
    Created the whitener using a noise covariance matrix with rank 6 (3 small eigenvalues omitted)
Selecting by number: 2 components
Fitting ICA took 0.1s.
    Using multitaper spectrum estimation with 7 DPSS windows
Not setting metadata
Not setting metadata
11 matching events found
No baseline correction applied
0 projection items activated
0 bad epochs dropped
___________________________ test_plot_ica_properties ___________________________
mne/viz/tests/test_ica.py:135: in test_plot_ica_properties
    ica.plot_properties(raw, picks=0, **topoargs)
mne/preprocessing/ica.py:1746: in plot_properties
    return plot_ica_properties(self, inst, picks=picks, axes=axes,
mne/viz/ica.py:475: in plot_ica_properties
    fig = _plot_ica_properties(
mne/viz/ica.py:193: in _plot_ica_properties
    kde_ /= kde_.max()
E   RuntimeWarning: invalid value encountered in true_divide
----------------------------- Captured stdout call -----------------------------
Opening raw data file /builddir/build/BUILD/mne-python-0.21.1/mne/viz/tests/../../io/tests/data/test_raw.fif...
    Read a total of 3 projection items:
        PCA-v1 (1 x 102)  idle
        PCA-v2 (1 x 102)  idle
        PCA-v3 (1 x 102)  idle
    Range : 25800 ... 40199 =     42.956 ...    66.930 secs
Ready.
Reading 0 ... 14399  =      0.000 ...    23.974 secs...
0 projection items deactivated
Not setting metadata
Not setting metadata
2 matching events found
Applying baseline correction (mode: mean)
0 projection items activated
Loading data for 2 events and 181 original time points ...
0 bad epochs dropped
    366 x 366 full covariance (kind = 1) found.
    Read a total of 4 projection items:
        PCA-v1 (1 x 102) active
        PCA-v2 (1 x 102) active
        PCA-v3 (1 x 102) active
        Average EEG reference (1 x 60) active
Fitting ICA to data using 6 channels (please be patient, this may take a while)
    Created an SSP operator (subspace dimension = 2)
Computing rank from covariance with rank=None
    Using tolerance 6e-16 (2.2e-16 eps * 6 dim * 0.45  max singular value)
    Estimated rank (mag + grad): 4
    MEG: rank 4 computed from 6 data channels with 0 projectors
    Setting small MEG eigenvalues to zero (without PCA)
    Created the whitener using a noise covariance matrix with rank 4 (2 small eigenvalues omitted)
Selecting by number: 2 components
Fitting ICA took 0.0s.
    Using multitaper spectrum estimation with 7 DPSS windows
Not setting metadata
Not setting metadata
11 matching events found
No baseline correction applied
0 projection items activated
0 bad epochs dropped
```

**Comment by larsoner** [comment]
> mne/channels/tests/test_interpolation.py:197: in test_interpolation_meg

Pushing a fix for this now

> mne/channels/tests/test_layout.py:255: in test_find_layout
> mne/io/edf/tests/test_edf.py:130: in test_edf_data_broken
> mne/io/edf/tests/test_edf.py:212: in test_find_events_backward_compatibility
> ...

A lot of these seem to be likely due to your removal of `mne/io/tests/data` files. Maybe restore them for now to get things to pass, then at the end remove them and you can see which tests you need to disable?

> mne/viz/tests/test_ica.py:135: in test_plot_ica_properties

Pushing a fix for the invalid divides now, too

**Comment by Aniket-Pradhan** [comment]
Thanks a lot for pushing in the fixes. :D

I am not sure what files are you talking about. The following files are present in the tar and the `mne/io/tests/data` directory.

```
process_raw.sh               test_chpi_raw_sss.fif  test-eve.fif.gz         test_raw-annot.fif
sample-audvis-raw-trans.txt  test.cov               test-eve-old-style.eve  test_raw-eve.fif
small-src.fif.gz             test-cov.fif           test_ica.lout           test_raw.fif
test-1-eve.fif               test-cov.fif.gz        test_keepmean.cov       test_raw.fif.gz
test.ave                     test_ctf_comp_raw.fif  test-km-cov.fif         test_raw.lout
test-ave-2.log               test_ctf_raw.fif       test-lh.label           test-rh.label
test-ave.fif                 test_empty_room.cov    test-mpr-eve.eve        test_withbads_raw.fif
test-ave.fif.gz              test_erm-cov.fif       test-nf-ave.fif         test_wrong_bads.txt
test-ave.log                 test-eve-1.eve         test-no-reject.ave
test_bads.txt                test-eve.eve           test-proj.fif
test_chpi_raw_hp.txt         test-eve.fif           test-proj.fif.gz
```

**Comment by larsoner** [comment]
> > A lot of these seem to be likely due to your removal of mne/io/tests/data files

> I am not sure what files are you talking about. The following files are present in the tar and the mne/io/tests/data directory.

It looked at first like the errors were due to only some but not all of the files in `mne/io/tests/data` being present. I thought that you did some removal of `mne/io/tests/data` directory during the packaging process, but it looks like *we* actually do that when creating the source tarball. So you're not testing from the source tarball but rather from the `git checkout`'ed version or something? I'm not very familiar with how the packaging process works and what source you use for the code (e.g., directly from `git`, or after `python setup.py sdist` output which would remove the `mne/io/tests/data` directory), or what diffs you apply to our code before running the tests. If you can outline these steps perhaps I can help more?

> Also, these tests pass for Fedora 34, but are currently failing for Fedora 33. Seems very weird to me ￼

This part is weird. What NumPy version is used in Fedora 33? For 0.21 we require NumPy >= 1.13.3, SciPy >= 1.0.0 so maybe these aren't satisfied?

**Comment by larsoner** [comment]
I'll merge this once CIs are happy so that we can push out 0.21.2 tomorrow. @Aniket-Pradhan I think the remaining question is what NumPy version is used in Fedora 33? For 0.21 we require NumPy >= 1.13.3, SciPy >= 1.0.0 so maybe these aren't satisfied by it. But in a tiny bit of searching I saw something about trying to use Python 3.9 in Fedora 33 -- maybe NumPy is bleeding edge and actually has some bugs in that build?

**Comment by Aniket-Pradhan** [comment]
Hey, sorry I got caught up in some other work.

So, I am pretty sure it is some issue with the deps, and not with mne. Although I am yet to figure out what actually is causing the problem, since Fedora 34 is the bleeding edge and generally should be the one causing problems :stuck_out_tongue: 

I'll have to sit one day figuring out which dep is it, and will have to see how I can fix that. Although, thanks for helping me around with the other tests. I'll get back if I find something interesting. :smile:

**Comment by larsoner** [comment]
0.21.2 is out

https://pypi.org/project/mne/0.21.2/

**Comment by Aniket-Pradhan** [comment]
Hey @larsoner 

Sorry, had some school tests midway, and hence was busy with them. I just tested the branch [mne-python:maint/0.21](https://github.com/mne-tools/mne-python/tree/maint/0.21) and it builds great! I'm guessing the dep causing the issue has been fixed.

I just had one small request, if you could tag the release on GitHub too. This is because most of the tests and data are not present in the PyPI release.

**Comment by larsoner** [comment]
https://github.com/mne-tools/mne-python/releases/tag/v0.21.2

**Pull request merged**
