### PR TITLE
MRG, MAINT: Reduce memory

### PR DESCRIPTION
**Pull request by larsoner**
There was a failure on CircleCI for `plot_visualize_epochs.py`. This PR fixes it.

WIP because I'm running it with https://github.com/sphinx-gallery/sphinx-gallery/pull/523 which will show the memory usage of all examples. Maybe there are others we should fix.

### CODE REVIEW

**Comment by larsoner** [comment]
The other offenders who use > 1.5 GB memory on master are both more memory efficient and faster (before/after images):

### plot_40_visualize_raw

master

PR

### plot_time_frequency_global_field_power.py

master

PR

### plot_source_power_spectrum_opm.py

(this one is worse locally than when SG builds it because SG closes the figures for each block)

master

PR

**Comment by larsoner** [comment]
@drammock feel free to review and merge if you're happy

**Comment by drammock** [comment]
I made a small PR into your branch with tweaks, otherwise LGTM.

**Comment by larsoner** [comment]
Great thanks, I'll merge once CircleCI comes back happy to get `master` green again

**Pull request merged**
