### PR TITLE
WIP, BUG: Make plot_evoked() not plot GFP for single channel

### LINKED ISSUE #8772: plot_evoked(gfp=True) with single-channel data behaves incorrectly
#### Problem
Plotting the GFP of data with only a single sensor via `plot_evoked(gfp=True)` produces a GFP, although the GFP – describing the spatial standard deviation – should not exist.

#### Steps to reproduce
```python
import os
import mne
sample_data_folder = mne.datasets.sample.data_path()
sample_data_raw_file = os.path.join(sample_data_folder, 'MEG', 'sample',
                                    'sample_audvis_raw.fif')
raw = mne.io.read_raw_fif(sample_data_raw_file, verbose=False)
events = mne.find_events(raw, stim_channel='STI 014')
event_dict = {'auditory/left': 1, 'auditory/right': 2, 'visual/left': 3,
              'visual/right': 4}
epochs = mne.Epochs(raw, events, tmin=-0.3, tmax=0.7, event_id=event_dict,
                    preload=True)
evoked = epochs['auditory/left'].average()

evoked.pick('EEG 001').plot(gfp=True)
```

#### Expected results
- either no GFP trace, or
- a GFP constantly at zero, or
- a warning, or
- an error message

#### Actual results
GFP is displayed as the absolute value of the sensor signal.
Screen Shot 2021-01-22 at 16 27 48

#### Additional information
Using `master`.

### PR DESCRIPTION
**Pull request by hoechenberger**
Fixes #8772

### CODE REVIEW

**Review by drammock — APPROVED** [review]
changes look reasonable. +1 for merge when CIs are happy

**Comment by hoechenberger** [comment]
Please do not merge yet, I figured there's actually a bug in how we calculate GFP.

**Review by agramfort — APPROVED** [review]

**Comment by agramfort** [comment]
@cbrnr merge if heppy

**Comment by cbrnr** [comment]
Thanks @hoechenberger!

**Comment by hoechenberger** [comment]
Oh noes this wasn't supposed to be merged… can we revert?

**Comment by cbrnr** [comment]
Can you open a new PR to revert? Sorry about that, I thought you'd addressed the issue (the PR was not a draft and @agramfort said OK to merge).

**Comment by hoechenberger** [comment]
Super weird, 
Screen Shot 2021-01-23 at 12 58 39

Was this simply reset once @agramfort submitted his review?

**Comment by cbrnr** [comment]
Hmmm, must've been otherwise it wouldn't have let me merge... Very strange!

**Comment by agramfort** [comment]
It's my fault.... Sorry and thanks for reverting.

**Pull request merged**
