### PR TITLE
Add mastodon link

### PR DESCRIPTION
**Pull request by drammock**
cc @cbrnr

### CODE REVIEW

**Comment by drammock** [comment]
https://output.circle-artifacts.com/output/job/4fac4c92-3241-4dfb-9dad-3e7dd75eb178/artifacts/0/dev/index.html

Failed CI is a windows permissions error on test_search_light (plus someone cancelled the compat/old job?)

**Comment by larsoner** [comment]
Thanks @drammock ! Now we just need some content :smile:

**Comment by cbrnr** [comment]
I just checked our Mastodon profile, and we don't get the green checkmark if I link to https://mne.tools/. However, I do get it when I link to https://mne.tools/stable/index.html, which I'd like to avoid (after all, this URL is what people see as our official homepage). @drammock do you know why this is the case (some redirection?) and if it can be fixed?

**Comment by drammock** [comment]
Yeah Probably mastodon's script doesn't follow redirects. Does it work to just specify /stable (without the index.html)? That seems an ok compromise to me.

**Comment by cbrnr** [comment]
Yes, adding /stable works!

**Pull request merged**
