### PR TITLE
[FIX] Fix channel-picking in _calculate_head_pos_ctf

### PR DESCRIPTION
**Pull request by jeythekey**
This PR consists of exactly one character of code, which had to be removed from the matching pattern in order to match CTF headloc channels of data loaded with the `clean_names` option set to `True`. See comment in #4088.

### CODE REVIEW

**Comment by larsoner** [comment]
Thanks @jeythekey

**Comment by jeythekey** [comment]
Welcome. I guess no whats_new.rst needed for that?

**Comment by larsoner** [comment]
Yes as it's a private function. If enough people use it successfully we should make it public.

**Comment by jeythekey** [comment]
Yes, I would definitely vote for making it at least semi-public in the meantime (e.g. only mention it in the docstring somehwere). It took me a long journey to find this functionality (because it is nowhere clearly documented, where exactly the headloc-data comes from and you have no clue if you are not using an Electra system).

**Comment by larsoner** [comment]
We could make it public but say that it's currently experimental status. We could do the same with `_calculate_chpi_positions`. But really before that we should see how much those can be deduplicated.

**Pull request merged**
