### PR TITLE
MAINT: Ignore dep temporarily

### PR DESCRIPTION
**Pull request by larsoner**
Let's get things green, then go back and fix (in case it's not trivial)

### CODE REVIEW

**Comment by larsoner** [comment]
Opened https://github.com/matplotlib/matplotlib/issues/23699 about the notebook issue, which I'll hopefully be able to track down better tomorrow

**Comment by larsoner** [comment]
(We should still merge this PR if it's the only failure because it's a *lot* easier to tell that it's the only failure without all the mpl-deprecation-related failures in there)

**Review by agramfort — APPROVED** [review]

**Review by drammock — APPROVED** [review]

**Comment by drammock** [comment]
there's still one failure:

https://github.com/mne-tools/mne-python/runs/7942941522?check_suite_focus=true#step:13:3650

3 days ago `ListedColormap` lost its `_resample` method and gained a (public) `resampled` method.

**Comment by larsoner** [comment]
The third arg of `getattr` will be evaluated and fail so we probably need `hasattr` here

**Comment by larsoner** [comment]
Getting this in so our error rate is at least lower!

**Pull request merged**
