### PR TITLE
MAINT: Only do nightly full builds

### PR DESCRIPTION
**Pull request by larsoner**
Now that we are paying for CircleCI builds, it would be nice to cut down our usage a bit. One way to do this is to only build `dev` and `maint/0.24` nightly, and only if they have changed. So this PR:

1. Makes it so that each build creates a `_build/html/_version.txt` that contains the SHA of the commit.
2. It quits on non-PR builds if it sees that it's not a scheduled build, unless there is a `[circle deploy]` in the commit line (hopefully we will only rarely need this, but it could come in handy around release time)
3. If it is a scheduled build, compares https://mne.tools/stable/_version.txt or https://mne.tools/dev/_version.txt (I put dummy ones in there manually for now) to the current commit number, and quits if the version numbers match.
4. Gets rid of "interactive_test", we don't really use it, and when we need something like it, it's probably easy enough to SSH in and venv manually now.
5. Fixes a [failure](https://app.circleci.com/pipelines/github/mne-tools/mne-python/11690/workflows/489499a3-3a5d-4e2a-93e7-07d8ae8773d8/jobs/39099) due to `pick_channels` deprecation

For now I have the schedule actually set to every hour in order to allow me to debug more easily. Once it this is merged, I'll push directly to `main` to make it work, then reset to `"0 0 * * *"` to make it nightly rather than hourly. Then I'll backport to `maint/0.24`, and hopefully things will work smoothly from there!

### CODE REVIEW

**Comment by drammock** [comment]
should we close #10006 after this is merged?

**Comment by larsoner** [comment]
> should we close #10006 after this is merged?

I went ahead and closed it already since it's technically fixed even without this PR. This PR should just help keep our bills smaller :)

**Comment by larsoner** [comment]
... when I merge this, I'm going to tag it with `[circle deploy]` just to see if it gets recognized properly, then cancel the build. Then on the hour, hopefully the schedule kicks in and starts a build for us! (Hopefully the current changes-only PR run will return before the turn of the hour so that we don't have to wait...)

**Comment by larsoner** [comment]
It timed out after 3h during the artifact uploading stage (argh!). Slowest ones:
```
computation time summary:
    - ../tutorials/clinical/30_ecog.py:                                       261.95 sec    513.9 MB
    - ../tutorials/intro/70_report.py:                                        229.07 sec    363.0 MB
    - ../tutorials/preprocessing/40_artifact_correction_ica.py:               187.72 sec    649.4 MB
    - ../examples/inverse/mixed_norm_inverse.py:                              162.41 sec    394.9 MB
    - ../tutorials/clinical/10_ieeg_localize.py:                              153.59 sec    917.8 MB
    - ../tutorials/inverse/40_mne_fixed_free.py:                              140.15 sec    508.7 MB
    - ../examples/time_frequency/source_power_spectrum_opm.py:                119.01 sec    617.0 MB
    - ../tutorials/forward/30_forward.py:                                     114.05 sec    571.3 MB
    - ../tutorials/inverse/60_visualize_stc.py:                               111.43 sec    552.7 MB
    - ../tutorials/clinical/20_seeg.py:                                       108.13 sec    365.9 MB
    - ../examples/inverse/covariance_whitening_dspm.py:                       102.94 sec    877.8 MB
    - ../tutorials/inverse/50_beamformer_lcmv.py:                             102.33 sec    827.8 MB
    - ../tutorials/preprocessing/30_filtering_resampling.py:                  100.92 sec    820.9 MB
```
I'll probably make a PR to try to reduce these. For now I also tried setting the resource class to `large`, but it would be better if we didn't have to make that switch.

**Comment by larsoner** [comment]
Even with the `large` machine class we still timed out. So I think we'll need to get it to build in < 3h to make things work. I think it's probably worth doing this anyway, 3h is a long time to build the docs. It seems like not too long ago it only took ~1.5h, perhaps we need to be more careful about how long examples and tutorials take going forward.

**Pull request merged**
