### PR TITLE
Enh single channel annotation

### PR DESCRIPTION
**Pull request by nmarkowitz**
Thanks for contributing a pull request! Please make sure you have read the
[contribution guidelines](https://mne.tools/dev/development/contributing.html)
before submitting.

Please be aware that we are a loose team of volunteers so patience is
necessary. Assistance handling other issues is very welcome. We value
all user contributions, no matter how minor they are. If we are slow to
review, either the pull request needs some benchmarking, tinkering,
convincing, etc. or more likely the reviewers are simply busy. In either
case, we ask for your understanding during the review process.

Again, thanks for contributing!

#### Reference issue

#8946 

#### What does this implement/fix?

Allows `BrowserBase` to directly toggle channel specific annotations

#### Additional information

Required to be pulled for mne-qt-browser pull request to work

https://github.com/mne-tools/mne-qt-browser/pull/255

### CODE REVIEW

**Comment by drammock** [comment]
is this ready for review? if not please mark as "draft"

**Comment by nmarkowitz** [comment]
> is this ready for review? if not please mark as "draft"

This is ready for review. I confirmed it works

**Comment by nmarkowitz** [comment]
How can I tell why checks are failing? Clicking details doesn't show any information

**Comment by larsoner** [comment]
@nmarkowitz I pushed a tiny commit to add a changelog entry and am marking for merge-when-green, thanks!

**Pull request merged**
