### PR TITLE
FIX: FFT memory

### LINKED ISSUE #2967: Memory consumption / scipy fft
``time_frequency/plot_epochs_spectra.py`` consumes over 2GB of memory. I tracked it down to  https://github.com/mne-tools/mne-python/blob/master/mne/time_frequency/multitaper.py#L440
Then I tried breaking it to parts so that one signal at a time is transformed. That reduced the memory consumption, but I noticed that the results are less smooth. Here are plots from ``plot_epochs_spectra.py``
On master:
figure_1-4
One signal at a time:
figure_1-1

Any idea what's going on?

### PR DESCRIPTION
**Pull request by Eric89GXL**
@jaeilepp see the minor fix, just needed to set the dims properly.

We could fix `dpss` so that it's always 2D at some point, too.

Closes #2967.

### CODE REVIEW

**Comment by agramfort** [comment]
LGTM. what fraction % of memory do we gain?

**Comment by Eric89GXL** [comment]
From @jaeilepp in the other PR:

> Reduces memory consumption. In plot_epochs_spectra.py from over 2GB to ~1.2GB.

**Comment by Eric89GXL** [comment]
I'll go ahead and merge if the CIs are happy, I suspect this might get CircleCI working again. It's been timing out on `master` builds, and @jaeilepp tracked down that our examples have been using too much memory. So this helps a bit with #2864.

**Comment by Eric89GXL** [comment]
Go Circle go...

**Comment by jaeilepp** [comment]
> Reduces memory consumption. In plot_epochs_spectra.py from over 2GB to ~1.2GB.

It actually ended up being something like 200MB. The solution earlier didn't include the imaginary part.
The circle succeeded once, so it must be right on the verge of succeeding.

**Comment by Eric89GXL** [comment]
We might be able to save a lot of memory by using `rfft`, which excludes the redundant coefficients

**Comment by agramfort** [comment]
>
> We might be able to save a lot of memory by using rfft, which excludes
> the redundant coefficients
>
+1

**Pull request merged**
