### PR TITLE
[RELEASE][DOC] Archive 0.16 and add 0.17 to navigation bar

### PR DESCRIPTION
**Pull request by massich**
This PR requires https://github.com/mne-tools/mne-tools.github.io/pull/13

### CODE REVIEW

**Comment by larsoner** [comment]
Might as well bump the version numbers in `.circle.yml` at the same time

**Comment by larsoner** [comment]
Oh wait, you haven't bumped the version number to 0.17 yet, nevermind :)

**Comment by massich** [comment]
No I haven't but maybe I can do it here and I can use this as PR example

**Comment by massich** [comment]
What have I done wrong? 
In this artifact https://10250-1301584-gh.circle-artifacts.com/0/html/index.html it appears to be the dev version but it should not

image

**Comment by larsoner** [comment]
(In other words, as long as you continue to follow the release instructions, it should all work out in the end. There are times/commits for which things are incorrect, like they will be now, because we let CircleCI push website changes, which takes a while, and there are steps in between that we must take.)

**Pull request merged**
