### PR TITLE
MRG, BUG: Fix warnings in examples

### PR DESCRIPTION
**Pull request by larsoner**
Fixes the failures here:

https://circleci.com/gh/mne-tools/mne-python/13597?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

### CODE REVIEW

**Comment by drammock** [comment]
heh. I was just starting on the fix for the sensors tutorial.  But your fix is inconsistent with the text that comes right before that code...  it specifically is supposed to illustrate that you can plot into an existing set of axes :(

**Comment by larsoner** [comment]
Fixed

**Comment by drammock** [comment]
thanks. It's not as pretty now, but apparently the `aspect=equal` setting was buggy so I guess this is better.

**Comment by larsoner** [comment]
Yeah once mpl officially allows setting the aspect again we can set it back

**Comment by larsoner** [comment]
Let's get this in so the master build is green before the transoceanic folks wake up :)

**Pull request merged**
