### PR TITLE
ENH: collapsible group box

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR adds support for collapsible group boxes for the `notebook` 3d backend. Here is an example with coreg:

main | PR
--|--
image | image

*I know the main render view still appears stretched, there might be way to fix its size somehow*

It's an item of #8833

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
And in video:

https://user-images.githubusercontent.com/18143289/152566076-9115d8d3-ba8f-44b5-b2c6-e1151c5b25c8.mp4

**Comment by larsoner** [comment]
> I know the main render view still appears stretched, there might be way to fix its size somehow

In the end it's just an image display, right? It seems like there must be a way in ipyvtklink (or whatever it depends on) to make the image's aspect ratio be respected rather than having it get stretched. It seems like some CSS like `object-fit` [might be enough to do it](https://web.dev/aspect-ratio/#object-fit)

**Comment by larsoner** [comment]
...I would try adding this property directly in Chrome's inspect mode to see if it works, and if so, then dig into which library would need to have this option added, then add it and make an upstream PR... and for now if we can add our own CSS inline or in a little cell header (seems like it should be possible?) then we can add it ourselves, too -- that way people don't have to upgrade `ipyvtklink` or whatever to get the benefit.

**Comment by GuillaumeFavelier** [comment]
Thank you for the great suggestions @larsoner !

According to [ipywidgets' doc](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Styling.html#Controlling-the-display-of-an-Image-inside-a-container), using `object_fit='contain'` should preserve the aspect ratio:

> 'contain': Fit the image in its content box while preserving the aspect ratio. If any of the container is not covered by the image, the background of the container is displayed. The content box is the size of the container if the container is smaller than the image, or the size of the image if the container is larger.

I made a comparative table to showcase the different options with collapsed groupbox or not:

object_fit\collapsed | True | False
--|--|--
'contain' | image | image
'cover' | image | image
'fill' | image | image
'none' | image | image

**Comment by GuillaumeFavelier** [comment]
No need for an upstream change, the `object_fit` property of the `ipyvtklink` viewer is directly accessible (*c.f.* 6f44268ffd5a84547ed5a830dce869264decc1cb)

**Comment by GuillaumeFavelier** [comment]
I chose `object_fit='contain'` because although `cover` also preserves the aspect ratio of the image, it will crop it if needed (visible in the table above):

> 'cover': Fill the content box completely while preserving the aspect ratio of the image, cropping the image if necessary.

https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Styling.html#Controlling-the-display-of-an-Image-inside-a-container

**Comment by GuillaumeFavelier** [comment]
What do you think @agramfort, @larsoner?

**Comment by agramfort** [comment]
I am interested in a live demo :)

**Comment by larsoner** [comment]
Contain is the right choice I think

**Comment by GuillaumeFavelier** [comment]
During a video call with @agramfort, we discovered a bug related to picking which is introduced in this PR. I have to debug before merge.

**Comment by larsoner** [comment]
> During a video call with @agramfort, we discovered a bug related to picking which is introduced in this PR. I have to debug before merge.

My guess is that it's an `ipyvtklink` bug where they assume that the click in the box containing the image is in the corresponding part of the stretched image regardless of the `object_fit` mode. So probably an upstream fix is necessary?

**Comment by GuillaumeFavelier** [comment]
> My guess is that it's an ipyvtklink bug where they assume that the click in the box containing the image is in the corresponding part of the stretched image regardless of the object_fit mode.

Hm... Assuming that the picking with the `Pick()` function in itself is alright, it could be related to the coordinates returned by `GetEventPosition()` which in turn could use an obsolete "window" size. 

I'll check the size returned by the viewer both in `main` and in here.

>  So probably an upstream fix is necessary?

Well, yes, if I cannot pinpoint the bug or find no way to fix it.

**Comment by GuillaumeFavelier** [comment]
I will share what I have learned:

`ipyvtklink` relies on `ipyevents` to get the [mouse event locations](https://github.com/mwcraig/ipyevents/blob/main/docs/events.ipynb). Then it does [a little bit of offset computation](https://github.com/Kitware/ipyvtklink/blob/master/ipyvtklink/viewer.py#L249-L254) to adjust the given coordinates from the canvas size (which depends on the notebook) to the render window size (which is fixed by the Renderer at init).

What happens when all the group boxes are folded is that the main 3d viewer in the middle is the widget with the highest height value, defining how stretched the container widget (`HBox`) is. At this point, the values given by `ipyevents` for `boundingRectHeight` and `boundingRectTop` used for offset calculation are correct because the image and its bounding box have the same size.

So the issue with `object_fit='contain'` arises when the group boxes are unfolded, the bouding box of the image is stretched with the accordion whereas the image is not (that's the point, we want to keep the aspect ratio). And now, the sizes sent by `ipyevents` will not match anymore.

It is possible to mitigate by using `object_position='top'`, this fixes the value of `boundingRectTop` but  `boundingRectHeight` is still incorrect so all the accordions must be folded.

I thought of 2 solutions to deal with this:

1. Prevent the image's container to stretch. 
2. adjust the event position given by the picker

I did not manage to make `1.` work by playing around with `layout` but it's possible that I missed something and `2.` is very hacky because I did not find any convenient way to get the *real size* of the canvas once it is displayed.

**Comment by larsoner** [comment]
This sounds like an upstream ipyvtklink bug, I would open an issue there and see if people have ideas

**Comment by GuillaumeFavelier** [comment]
Meanwhile, 5014f41601b75148779881888354d8676a2497e5 is the kind of hack I have to use to make it work with `2.`

**Comment by GuillaumeFavelier** [comment]
@larsoner I opened https://github.com/Kitware/ipyvtklink/issues/35

**Comment by larsoner** [comment]
For now I would say get rid of `object_fit` in this PR, and let's see if `ipyvtklink` can make an upstream fix soon. 

@GuillaumeFavelier could you see if you can change their computation in the "a little bit of offset computation" code to fix the bug at their end? It might move things forword (much) faster than waiting for them to fix it.

**Comment by GuillaumeFavelier** [comment]
> could you see if you can change their computation in the "a little bit of offset computation" code to fix the bug at their end?

I'll see what I can do but I think it might be better to handle it with `ipyevents` directly.

I updated #8833 with:

>  add support for `object_fit='contain'` and `object_position='top'` (*ipywidgets*)

**Comment by GuillaumeFavelier** [comment]
This is ready to merge from my end @agramfort, @larsoner

**Comment by larsoner** [comment]
> I'll see what I can do but I think it might be better to handle it with ipyevents directly.

Could be, want to open an issue with them, too? They should know if it's in scope for them or not

**Comment by larsoner** [comment]
(if it's a fairly trivial fix, sometimes I open a PR-as-issue to just fix the problem, and ask if they think it's acceptable)

**Comment by larsoner** [comment]
Thanks @GuillaumeFavelier ! On to the next blocker for 1.0, if any?

**Pull request merged**
