### PR TITLE
don't call subplots_adjust when user provided axes

### PR DESCRIPTION
**Pull request by drammock**

### CODE REVIEW

**Review by larsoner — APPROVED** [review]

**Comment by larsoner** [comment]
Can we simplify the example somehow now and remove the `subplots_adjust` call from it?

**Comment by drammock** [comment]
> Can we simplify the example somehow now and remove the `subplots_adjust` call from it?

looking into it now, in fact.

**Comment by drammock** [comment]
turns out we still need `subplots_adjust` because of the axis labels, but now we only need to specify `bottom`.  I also delayed introducing the axis labels until the final cell, so we avoid `subplots_adjust` in the 2 earlier cells.

**Review by larsoner — APPROVED** [review]

**Comment by larsoner** [comment]
Thanks @drammock

**Pull request merged**
