### PR TITLE
Doc string clarification

### PR DESCRIPTION
**Pull request by kambysese**

### CODE REVIEW

**Comment by Eric89GXL** [comment]
LGTM. I'm thinking of potentially trying to deprecate this function actually, as it's likely not going to work that well for movement compensation in Python.

**Comment by jasmainak** [comment]
Thanks @kambysese

**Comment by kambysese** [comment]
Welcome @jasmainak 
@Eric89GXL can you explain a bit more. I'm interested in implications on evoked movement compensation method.

**Comment by Eric89GXL** [comment]
I plan on replacing the function with something more consistently named like `read_head_quats` or so. Then you can use that to read head positions appropriate for evoked movecomp

**Pull request merged**
