### PR TITLE
MRG: Inter-hemisphere Euclidean distance connectivity

### LINKED ISSUE #2286: ENH: allow for spatial connectivity between two hemispheres
In volumetric source spaces you can get bi-lateral ROIs, blobs, and  connected clusters, not that easily with Freesurfer surfaces. However, it's an unphysiological prior to not allow bihemispheric connections in permutation clustering tests. With @banilo and @yuval-harpaz we were wondering about ways to connect medial vertices across hemispheres, maybe based on a minimum distance criterion. As an intermediate step it would be cool to support FS xhemi registrations to support mapping vertices between hemispheres. Input and ideas are welcome.

cc @Eric89GXL @mainakjas @agramfort

### PR DESCRIPTION
**Pull request by Eric89GXL**
@dengemann can you see if it makes sense for your use case? I went with naming that was more consistent with the existing spatial distance functions than what we talked about. But it should be pretty straightforward to combine connectivity matrices.

Closes #2286.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
@dengemann still interested in this?

**Comment by dengemann** [comment]
@Eric89GXL yes absolutely.

**Comment by dengemann** [comment]
I need to play with it to give feedback ...

**Comment by Eric89GXL** [comment]
What do you mean by play with it? Test it with data? It seems like if 1) the API fits with mne-python, 2) the function does what it says it will do, and 3) that can be confirmed by reading and running the tests, that should be good enough for the first draft. Then if we need more functions on top e.g. to combine different connectivity matrices (if `+` doesn't do it), then we could do it in another PR. Or are there other things you wanted to do in addition?

**Comment by dengemann** [comment]
The API is to me very low level. In order to see how well it works I need to analyze some data and see what different values in meters give in terms of connectivity. From reading the code I cannot really get an intuition for it.

**Comment by Eric89GXL** [comment]
> The API is to me very low level.

I think it's at the same level as the rest of our connectivity code, which does connectivity based on distances, just using a different measure (geodesic instead of Euclidean distance)...?

> In order to see how well it works I need to analyze some data and see what different values in meters give in terms of connectivity.

Okay -- but how will this comparison/testing inform this PR? Are you thinking it might change something about how the calculation actually gets done? I imagine you might need to tweak what the distance limit is, but I'm not sure how it would come to influence the algorithm itself.

**Comment by Eric89GXL** [comment]
@dengemann any thoughts on this one, too? Never heard back on the above questions...

**Comment by dengemann** [comment]
> @dengemann any thoughts on this one, too? Never heard back on the above questions...

we can merge it I will play with it soon during my next burst of source space group analyses

**Comment by dengemann** [comment]
Thanks a lot Eric!

**Pull request merged**
