### PR TITLE
MRG: Use info to get NIRS metadata, not raw

### PR DESCRIPTION
**Pull request by HanBnrd**
#### Reference issue
Addresses https://github.com/mne-tools/mne-python/pull/9141#discussion_r610730226.

#### What does this implement/fix?
Use the info field to get NIRS frequencies and chromophores, not the raw structure.

#### Additional information
Extension of @rob-luke's work with #9280.
This should enable usage in functions that only have access to info, like set_montage.

### CODE REVIEW

**Review by agramfort — APPROVED** [review]

**Comment by rob-luke** [comment]
Fantastic, thanks @HanBnrd

**Review by rob-luke — APPROVED** [review]

**Comment by rob-luke** [comment]
Not sure if I am allowed to merge PR?, so I just hit approve. So I will leave to @larsoner or @drammock.

**Review by larsoner — APPROVED** [review]
Feel free to click the green button using squash+merge @rob-luke . If you don't have permission let me know and I'll grant it

**Comment by rob-luke** [comment]
Thanks @larsoner, I will hit the button from now on if there is already another approval and its fnirs related

**Pull request merged**
