### PR TITLE
MAINT: Test against installed package

### PR DESCRIPTION
**Pull request by larsoner**
Hopefully shows problem from https://github.com/mne-tools/mne-bids-pipeline/pull/825 and https://github.com/mne-tools/mne-bids/pull/1206

cc @hoechenberger @drammock @sappelhoff

### CODE REVIEW

**Comment by hoechenberger** [comment]
@larsoner 
I think it's worthwhile considering switching to a `src/` layout to further reduce the chances of erroneously using `mne` in the CWD instead of the installed version. Thoughts?

**Comment by drammock** [comment]
> > I think it's worthwhile considering switching to a `src/` layout to further reduce the chances of erroneously using `mne` in the CWD instead of the installed version.
> It sounds like a pretty big change and a departure from how most scientific python projects (numpy/scipy/pandas etc., but there are exceptions like matplotlib) are organized AFAIK. I'd rather move slower than faster here.

I'm actually less swayed by the "what does numpy do" heuristic here, perhaps because there are exceptions (pydata-sphinx-theme is another one).  For me the relevant question is "is it likely to *continue* causing problems for us?" We've hit two big-ish and annoying problems, and now have fixes for both of them. The biggest cost may be that changing from `mne/` to `src/` will require our devs to update their muscle memory for actions that some of them make tens or hundreds of times per day.  So I don't want to incur that cost unless we can foresee future problems.  Might be worth asking for opinions on the scientific python discord or discourse?

**Review by drammock — APPROVED** [review]

**Comment by hoechenberger** [comment]
@larsoner Are you sure this is actually testing what we want here?

I'd much rather ship our tests with the sdist, `rm -rf` the checked-out repository, and run the tests from `site-packages/mne` just to be absolutely sure… No?

**Comment by larsoner** [comment]
See also https://github.com/mne-tools/mne-python/issues/4926, feel free to reopen if you see a good path forward

**Pull request closed without merging**
