### PR TITLE
MRG, ENH: Better support for str-like objects

### LINKED ISSUE #6657: read_* functions should support pathlib objects
#### Describe the problem
This currently throws an error:
```python

import pathlib
import mne

data_dir = pathlib.Path('/Users/hoechenberger/Projects/TaLa/'
                        'Data/EEG/Preprocessed')

data_file = data_dir / 'TaLa_460_preped-epo.fif'
data = mne.read_epochs(data_file)
```

Generates:
```python
Reading File-like PosixPath('/Users/hoechenberger/Projects/TaLa/Data/EEG/Preprocessed/TaLa_460_preped-epo.fif') ...
Traceback (most recent call last):
  File "/Users/hoechenberger/Library/Preferences/PyCharm2019.2/scratches/scratch_45.py", line 8, in <module>
    data = mne.read_epochs(data_file)
  File "</Users/hoechenberger/Development/mne-python/mne/externals/decorator.py:decorator-gen-179>", line 2, in read_epochs
  File "/Users/hoechenberger/Development/mne-python/mne/utils/_logging.py", line 89, in wrapper
    return function(*args, **kwargs)
  File "/Users/hoechenberger/Development/mne-python/mne/epochs.py", line 2347, in read_epochs
    return EpochsFIF(fname, proj, preload, verbose)
  File "</Users/hoechenberger/Development/mne-python/mne/externals/decorator.py:decorator-gen-180>", line 2, in __init__
  File "/Users/hoechenberger/Development/mne-python/mne/utils/_logging.py", line 89, in wrapper
    return function(*args, **kwargs)
  File "/Users/hoechenberger/Development/mne-python/mne/epochs.py", line 2413, in __init__
    fid, tree, _ = fiff_open(fname, preload=preload)
  File "</Users/hoechenberger/Development/mne-python/mne/externals/decorator.py:decorator-gen-6>", line 2, in fiff_open
  File "/Users/hoechenberger/Development/mne-python/mne/utils/_logging.py", line 89, in wrapper
    return function(*args, **kwargs)
  File "/Users/hoechenberger/Development/mne-python/mne/io/open.py", line 119, in fiff_open
    fid = _fiff_get_fid(fname)
  File "/Users/hoechenberger/Development/mne-python/mne/io/open.py", line 50, in _fiff_get_fid
    fid.seek(0)
  File "/Users/hoechenberger/Development/mne-python/mne/io/open.py", line 33, in seek
    return self.fid.seek(offset, whence)
AttributeError: 'PosixPath' object has no attribute 'seek'
```

#### Describe your solution
My current workaround: convert the `PosixPath` object to a string:
```python
data = mne.read_epochs(str(data_file))
```

#### Describe possible alternatives
Ideally, there would be "built-in" `pathlib` support in MNE.

### PR DESCRIPTION
**Pull request by larsoner**
Closes #6657. cc @hoechenberger

### CODE REVIEW

**Comment by agramfort** [comment]
this only does the job for read_raw_fif ? not all read_xxx functions right?

**Comment by larsoner** [comment]
Only FIF format. The others probably don't support `file-like` objects anyway, so might already have built-in `str-like` support for when we do e.g. `open(fname, 'rb')` on them.

**Comment by agramfort** [comment]
alright ! I had not realized. thx

**Comment by massich** [comment]
does this mean that we don't need to keep casting the pytest tempdir??

**Comment by massich** [comment]
Now I'm confused. The snipped of #6657 is exactly the same use case than pytest tempdir, isn't it?

**Comment by larsoner** [comment]
probably, we might be able to get of the `str` casts, I did not check

**Pull request merged**
