### PR TITLE
DOC: Avoid talking about set_montage in EEG ERP example

### PR DESCRIPTION
**Pull request by massich**

### CODE REVIEW

**Comment by massich** [comment]
maybe instead of what I did it should point to `_reading-dig-montages`. WDYT @drammock? Feel free to push and merge.

**Comment by drammock** [comment]
rendering: 
https://13944-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/evoked/plot_eeg_erp.html

**Comment by drammock** [comment]
@massich I haven't been closely following the montage debates so I don't know what's best here, but I pushed a minimal change to get CIs happy.

**Comment by massich** [comment]
@drammock that's great. Thanks a lot !!!

**Pull request merged**
