### PR TITLE
[MRG] ENH: better sel channels visibility

### PR DESCRIPTION
**Pull request by mmagnuski**
Currently doing `epochs.plot_sensors(kind='select')` and lasso-selecting some channels leads to selected channels not being clearly distinguishable:

I've added changes to edgecolors with lasso selection to make the channels more visible:

## TODOs:
- [x] test?
- [x] what's new

### CODE REVIEW

**Comment by larsoner** [comment]
Looks reasonable to me

**Comment by agramfort** [comment]
> Looks reasonable to me
+1

**Comment by mmagnuski** [comment]
Circle failures seem unrelated.

**Comment by mmagnuski** [comment]
Seems that `nipy.org` is unavailable and that makes the docs building fail.

**Comment by agramfort** [comment]
Thx @mmagnuski

**Comment by mmagnuski** [comment]
Thanks @larsoner and @agramfort :rocket:

**Pull request merged**
