### PR TITLE
Drop unit kwarg from `read_custom_montage()`

### LINKED ISSUE #7320: read_custom_montage() silently ignores unit kwarg when loading Theta-phi montages (and possibly others)
#### Describe the bug
`read_custom_montage()` accepts a `unit` kwarg …
https://github.com/mne-tools/mne-python/blob/d2a5660db534c2d67af514b3d89b08abb67aa696/mne/channels/montage.py#L956-L957

… but doesn't pass the `unit` kwarg down to `_read_theta_phi_in_degrees()`:
https://github.com/mne-tools/mne-python/blob/d2a5660db534c2d67af514b3d89b08abb67aa696/mne/channels/montage.py#L1039-L1044

This is understandable, since `_read_theta_phi_in_degrees()` currently doesn't _accept_ a `unit` kwarg!
https://github.com/mne-tools/mne-python/blob/d2a5660db534c2d67af514b3d89b08abb67aa696/mne/channels/_standard_montage_utils.py#L238-L239

The result is a montage built on the assumption that head size was specified in meters, regardless of the `unit` kwarg the user passes.

#### Steps to reproduce
```python
import pathlib
import mne


base_dir = pathlib.Path('/Users/hoechenberger/Projects/TaDe')
montage_file = base_dir / 'actiCHamp_64Ch_Theta-phi_in_deg_including_fid.txt'

head_sizes = (0.085, 85)
units = ('m', 'mm')

for head_size, unit in zip(head_sizes, units):
    m = mne.channels.read_custom_montage(montage_file,
                                         head_size=head_size,
                                         unit=unit)
    print(f'Specfiied head size: {head_size} {unit}')
    print(f'Resulting LPA loc:\n{m.dig[0]}\n')
```
(I can upload the files if need be, but I think the example is pretty straightforward)

#### Expected results
Both function calls should yield identical channel locations.

#### Actual results
The channel locations differ, as the head size is always assumed to have been specified in meters:
```
Specfiied head size: 0.085 m
Resulting LPA loc:
<DigPoint |        LPA : (-78.8, -0.0, -31.8) mm   : unknown frame>

Specfiied head size: 85 mm
Resulting LPA loc:
<DigPoint |        LPA : (-78810.6, -0.0, -31841.6) mm : unknown frame>
```

#### Additional information
Since the `unit` kwarg isn't processed correctly, it's also not sanity-checked for invalid values. So one could pass anything, without creating an error message:

```python
mne.channels.read_custom_montage(montage_file, unit='hello world!')
```
Output:
```
<DigMontage | 0 extras (headshape), 0 HPIs, 3 fiducials, 65 channels>
```

A number of other montage-reading functions may be affected too, as they also seem to be assuming the head size is always specified in meters:

- `_read_elc`
- `_read_csd`
- `_read_sfp`
- `_read_elp_besa`

### PR DESCRIPTION
**Pull request by hoechenberger**
#### Reference issue
Fixes #7320

#### What does this implement/fix?
<strike>Improves the docstring of `read_custom_montage()` to make it clearer that `head_size` has to be specified in meters (and meters only), and that the `unit` kwarg only refers to the montage, not the head.

Also drops the `unit` arg from `_read_eeglab_location()`, as it was unused inside the function.

Currently, the only use of the `unit` kwarg is in the BrainVision reader; but even there, we simply check it the passed value is `auto` or `mm`, and then don't do _anything_ with that info:
https://github.com/mne-tools/mne-python/blob/2b9a707f1600af9f120df20b15e55d6c6ce18c62/mne/channels/_standard_montage_utils.py#L303-L318

Therefore I would almost say we should, at this time, entirely _drop_ the `unit` kwarg from `read_custom_montage()`: none of the readers we invoke needs / uses it! WDYT?</strike>

Removes the `unit` kwarg from `read_custom_montage()` completely.

### CODE REVIEW

**Comment by agramfort** [comment]
I see that `unit` is not even used in `def _read_brainvision(fname, head_size, unit):` so it's actually useless ... I would suggest to simply remove the parameter as a bug fix.

**Comment by agramfort** [comment]
@hoechenberger can you add an entry in "bug" section in latest.inc ?

**Comment by hoechenberger** [comment]
@agramfort I've added it to the API section in the changelog, as apparently the `unit` kwarg was already present in mne-python 0.19, so this is a backward-incompatible API change without a deprecation cycle … is it even legal to do that? ;)

**Comment by agramfort** [comment]
I can live with api change as I don’t expect anyone to have used this parameter that had no effect

**Comment by hoechenberger** [comment]
> I can live with api change as I don’t expect anyone to have used this parameter that had no effect

Well, I did ;)
nn7jo

thanks for your help and the clarifications, @agramfort

**Comment by hoechenberger** [comment]
@agramfort I you're happy with the code, this PR should be good to merge

**Comment by larsoner** [comment]
Thanks @hoechenberger

**Pull request merged**
