### PR TITLE
backport new environment file and install instructions

### PR DESCRIPTION
**Pull request by drammock**
@larsoner not sure if I did the cherry-pick correctly; the diff ended up including some changes that weren't from #7971 ... but I *think* that's actually what we want in this case?

### CODE REVIEW

**Comment by larsoner** [comment]
Technically we don't want to bump Travis on `maint/0.20` to 3.6 because 0.20 still supports 3.5. But it probably does not matter much since we're releasing 0.21 in about two months, so if it's enough to make the CIs happy then I guess it's fine.

**Comment by drammock** [comment]
hmm, circle failures are all related to _dict stuff.  I guess I need to cherry-pick the ignore-nitpicky lines in `doc/conf.py`?

**Comment by larsoner** [comment]
Yep, that should do it

**Comment by drammock** [comment]
@larsoner Circle is happy, and I've reverted all the changes except for the changes to the docs, and the `nitpicky` ignores in `conf.py`.  Note that I had to add a *new* nitpick ignore to make Circle happy.  Is this OK to merge then, to get the stable docs in sync with the current state of `environment.yml`?

**Comment by larsoner** [comment]
Thanks @drammock

**Pull request merged**
