### PR TITLE
MRG, DOC: Link to funding

### PR DESCRIPTION
**Pull request by larsoner**
Also fixes a warning-as-error bug on `main`, a build bug due to `mne-connectivity` release, plus adds URLs for funding sources that I could find.

### CODE REVIEW

**Comment by larsoner** [comment]
conda-forge failures are noted / fixed in https://github.com/conda-forge/pyvista-feedstock/pull/51, hopefully it lands very quickly so we don't have to work around it...

**Comment by larsoner** [comment]
Much more blue here: https://33885-1301584-gh.circle-artifacts.com/0/dev/funding.html

Should be good to merge if you're happy @drammock

**Comment by drammock** [comment]
you are OK with the ghActions failures (`module not found: transforms3d`)?

**Review by drammock — APPROVED** [review]

**Comment by drammock** [comment]
(never mind, I just missed the earlier comment about conda-forge / pyvista)

**Pull request merged**
