### PR TITLE
[MRG] FIX: save-load split FIF round trip

### LINKED ISSUE #5856: save-load FIF round trip fails due to Annotations
```py
import os.path as op
import numpy as np
from numpy.testing import (assert_array_almost_equal, assert_array_equal,
                           assert_allclose)

from mne.datasets import testing
from mne.io import read_raw_fif
from mne.utils import _TempDir
from mne.annotations import Annotations

testing_path = testing.data_path(download=False)
data_dir = op.join(testing_path, 'MEG', 'sample')
fif_fname = op.join(data_dir, 'sample_audvis_trunc_raw.fif')
tmpdir = _TempDir()


raw_1 = read_raw_fif(fif_fname, preload=True)
raw_1.set_annotations(Annotations(np.arange(20), np.ones((20,)), 'test'))
split_fname = op.join(tmpdir, 'split_raw.fif')
raw_1.save(split_fname, buffer_size_sec=1.0, split_size='10MB')
raw_2 = read_raw_fif(split_fname)

print(raw_1.annotations)
print(raw_2.annotations)

assert_array_almost_equal(raw_1.annotations.onset, raw_2.annotations.onset)
```

I get two extra annotations at the end of the file that I've no idea where are they coming from.

```
<Annotations  |  20 segments : test (20), orig_time : 2002-12-03 19:01:10.720100>
<Annotations  |  22 segments : test (22), orig_time : 2002-12-03 19:01:10.720100>
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
~/code/mne-python/test_xx.py in <module>
     24 print(raw_2.annotations)
     25 
---> 26 assert_array_almost_equal(raw_1.annotations.onset, raw_2.annotations.onset)
     27 

~/miniconda3/envs/mne/lib/python3.6/site-packages/numpy/testing/_private/utils.py in assert_array_almost_equal(x, y, decimal, err_msg, verbose)
    971     assert_array_compare(compare, x, y, err_msg=err_msg, verbose=verbose,
    972              header=('Arrays are not almost equal to %d decimals' % decimal),
--> 973              precision=decimal)
    974 
    975 

~/miniconda3/envs/mne/lib/python3.6/site-packages/numpy/testing/_private/utils.py in assert_array_compare(comparison, x, y, err_msg, verbose, header, precision, equal_nan, equal_inf)
    738                                 verbose=verbose, header=header,
    739                                 names=('x', 'y'), precision=precision)
--> 740             raise AssertionError(msg)
    741 
    742         flagged = bool_(False)

AssertionError: 
Arrays are not almost equal to 6 decimals

(shapes (20,), (22,) mismatch)
 x: array([42.955971, 43.955971, 44.955971, 45.955971, 46.955971, 47.955971,
       48.955971, 49.955971, 50.955971, 51.955971, 52.955971, 53.955971,
       54.955971, 55.955971, 56.955971, 57.955971, 58.955971, 59.955971,
       60.955971, 61.955971])
 y: array([42.955971, 43.955971, 44.955971, 45.955971, 46.955971, 47.955971,
       48.955971, 49.955971, 50.955971, 51.955971, 52.955971, 53.955971,
       54.955971, 55.955971, 56.955971, 57.955971, 58.955971, 59.955971,
       60.955971, 61.955971, 62.958802, 62.958802])
```

### PR DESCRIPTION
**Pull request by massich**
split save and reload a FIF file fails due to Annotations

Fixes #5856

### CODE REVIEW

**Comment by larsoner** [comment]
It would be great if this could also fix #5908

**Comment by larsoner** [comment]
@massich it would be good to release soon, this should go in if at all possible so this is a high priority!

**Comment by massich** [comment]
The current status solves #5856 and does not break any other tests.

The following snipped fails in master and passes in the PR.

```py
import os.path as op
import numpy as np
from numpy.testing import assert_array_equal, assert_allclose

from mne.datasets import testing
from mne.io import read_raw_fif
from mne.utils import _TempDir
from mne.annotations import Annotations

testing_path = testing.data_path(download=False)
data_dir = op.join(testing_path, 'MEG', 'sample')
fif_fname = op.join(data_dir, 'sample_audvis_trunc_raw.fif')
tempdir = _TempDir()

raw_1 = read_raw_fif(fif_fname, preload=True)
annot = Annotations(np.arange(20), np.ones((20,)), 'test')
raw_1.set_annotations(annot)
split_fname = op.join(tempdir, 'split_raw.fif')
raw_1.save(split_fname, buffer_size_sec=1.0, split_size='10MB')
raw_2 = read_raw_fif(split_fname)
assert_allclose(raw_2.buffer_size_sec, 1., atol=1e-2)  # samp rate
assert_allclose(raw_1.annotations.onset, raw_2.annotations.onset)
assert_allclose(raw_1.annotations.duration, raw_2.annotations.duration,
                rtol=0.001 / raw_2.info['sfreq'])
assert_array_equal(raw_1.annotations.description,
                    raw_2.annotations.description)
```

**Comment by larsoner** [comment]
Probably worth an entry in `whats_new.rst` BUG section, otherwise +1 for merge, thanks @massich

**Comment by larsoner** [comment]
> The following snipped fails in master and passes in the PR.

This is effectively captured by one of the modifications to the test files now, right? If not, please do add it because it's an important non-regression test.

**Comment by massich** [comment]
@larsoner yes it is.

**Comment by larsoner** [comment]
Thanks @massich !

**Pull request merged**
