### PR TITLE
DOC: Update commands

### LINKED ISSUE #5650: Unable to add source for libXp6 package
@agramfort Instructions for resolving the missing libXp.so.6 package issue were helpfully added to the MNE-C documentation: http://mne-tools.github.io/dev/install_mne_c.html#troubleshooting. Unfortunately, with my Ubuntu 18.04 setup, the following error pops up when attempting the first command:

 `W: GPG error: http://security.ubuntu.com/ubuntu precise-security InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 40976EAF437D05B5`

`E: The repository 'http://security.ubuntu.com/ubuntu precise-security InRelease' is not signed.`

`N: Updating from such a repository can't be done securely, and is therefore disabled by default.`

`N: See apt-secure(8) manpage for repository creation and user configuration details.`

Attached is the full traceback. 
libxp6error

### PR DESCRIPTION
**Pull request by larsoner**
Closes #5650

### CODE REVIEW

**Comment by larsoner** [comment]
I stopped Travis and AppVeyor since they don't do anything with `.rst` files

**Comment by larsoner** [comment]
(other than spell check I guess, but I just checked that locally)

**Comment by larsoner** [comment]
https://9942-1301584-gh.circle-artifacts.com/0/html/install_mne_c.html#troubleshooting

**Comment by massich** [comment]
Thx! merging

**Pull request merged**
