### PR TITLE
ENH use mkl fft if available

### PR DESCRIPTION
**Pull request by mainakjas**
closes https://github.com/mne-tools/mne-python/issues/1889

and save me lots of time :)

### CODE REVIEW

**Comment by Eric89GXL** [comment]
Looks reasonable, but there are many places we use `fft`s. We should probably do `from mne.fixes import fftn, ifftn` or so, and just do the triaging there once. WDYT?

**Comment by agramfort** [comment]
+1 this should be in fixes to be used everywhere.

how much speed gain did you observe?

**Comment by Eric89GXL** [comment]
Also, we should update the docs to say how to speed these up, e.g. what package you need to install in anaconda. It could go in the same area that talks about using CUDA.

**Comment by mainakjas** [comment]
weird, actually it doesn't seem to help.

`%timeit tfr_morlet(epochs, freqs=freqs, n_cycles=n_cycles, use_fft=True, return_itc=False, decim=32, n_jobs=1)`

on my data on `master` branch is 25.8 s per loop but on this branch, it is 31.2 s per loop

**Comment by mainakjas** [comment]
weird, actually it doesn't seem to help.

`%timeit tfr_morlet(epochs, freqs=freqs, n_cycles=n_cycles, use_fft=True, return_itc=False, decim=32, n_jobs=1)`

on my data on `master` branch is 25.8 s per loop but on this branch, it is 31.2 s per loop

**Comment by agramfort** [comment]
let me know when you played with num threads

```
In [1]: import mkl

In [2]: mkl.set_num_threads?
Type:        builtin_function_or_method
String form: <built-in function set_num_threads>
Docstring:
set_num_threads(n)

Set the number of threads MKL should use.  This is only a hint, and no
guaranteed is made this number of threads will actually be used.
This function takes precedence over the environment variable
MKL_NUM_THREADS.

In [3]: mkl.set_num_threads(1)
```

**Comment by Eric89GXL** [comment]
If people are using morlet transforms heavily I could look at implementing them in CUDA. (Or @mainakjas you could!) I think it should speed it up since it's related to FIR filtering.

**Comment by mainakjas** [comment]
@agramfort here are the stats:

```
single thread: 1 loops, best of 3: 32.8 s per loop
two threads: 1 loops, best of 3: 30.7 s per loop
three threads: 1 loops, best of 3: 30.2 s per loop
four threads: 1 loops, best of 3: 30.6 s per loop
```

without mkl it is around 25 s. So, it appears that there is some overhead to using mkl which is not offset by using more threads.

@Eric89GXL : sure, I can implement a CUDA version. How much speed up are we talking about with CUDA? I just figured that I could use the `n_jobs` option (`n_jobs=4`) and it seems to take only 7.3 s compared to approx. 30 s with or without mkl.

**Comment by dengemann** [comment]
> without mkl it is around 25 s. So, it appears that there is some overhead to using mkl which is not offset by using more thread

maybe the single trial data are just too small to make a difference ...
MKL really kicks in for more heavy computations.

**Comment by agramfort** [comment]
can you try on filtering raw data?

I am really surprised if we don't gain anything.

**Comment by Eric89GXL** [comment]
It is interesting that it hurts for epochs, we'll see on raw.

BTW I don't remember my formal test results but I think CUDA is about an
order of magnitude faster then fftpack (and also faster than fftw) with
n_jobs=6 on raw data, so I suspect either way we might be able to get CUDA
to win for morlets.

**Comment by agramfort** [comment]
can anaconda facilitate cuda setup?

**Comment by jona-sassenhagen** [comment]
I'd love to see either implemented for multitapers.

**Comment by Eric89GXL** [comment]
I suppose CUDA could speed up multitaper as well, because you could upload the tapers once, and for each window it could do the N multitaper calculations and then send the result back. The overhead with CUDA is mostly with memory transfers -- that would just be one chunk of data in, result out, so it should be fast.

@agramfort no I don't think so, PyCUDA probably needs to be compiled against the CUDA version one has installed, which could be anything from 5.0 to 6.5 nowadays. On Ubuntu you can just do `sudo apt-get install pycuda`, but not every OS can be so civilized :)

**Comment by Eric89GXL** [comment]
FYI you pushed this branch to upstream instead of origin, please move it to your fork and delete

**Comment by mainakjas** [comment]
darn, I am sorry. I'll delete ASAP

**Pull request closed without merging**
