### PR TITLE
[WIP] SourceMorph (GSoC 2018)

### PR DESCRIPTION
**Pull request by TommyClausner**
This PR is about updating the SourceMorph class to morph (Vol)SourceEstimate + tutorials and examples.

To do:
- [x] discuss ``compute_morph_matrix``
- [ ] hope for checks
- [ ] convince people to merge :)

### CODE REVIEW

**Comment by TommyClausner** [comment]
Hey again regarding depreciation: we deprecated ``morph_precomputed`` and ``morph_data`` but agreed for some reason to not depreciate ``compute_morph_matrix`` 

if I remember correctly because it would be too much pain (because it's used overall) 

could we deprecate it nevertheless and I fix all issues that might occur? The ``morph_mat`` can e.g. also be accessed from ``SoureMorph.params``

**Comment by larsoner** [comment]
> Hey again regarding deprecation: we deprecated morph_precomputed and morph_data but agreed for some reason to not deprecate compute_morph_matrix

Can you look through the various issues and PRs to figure out what we settled on? I don't remember the details. But to me it does not make much sense to deprecate just `morph_precomputed` without also deprecating `compute_morph_matrix`. The latter is typically only used with the former.

I think at this point I'm okay with deprecating `compute_morph_matrix`, too. Maybe tell people in the docstring of `compute_morph_matrix` the equivalent one-liner that they can use, probably something like:
```
morph_mat = SourceMorph(...).params['morph_mat']
```

**Comment by agramfort** [comment]
@TommyClausner please have a look at @larsoner 's comments and i'll do another pass.

If there is a question to discuss API wise besides compute_morph_matrix?
compute_morph_matrix and morph_data are used in plot_morph_data.py
To fully see the API transitioned this example should be updated.
Once done does it make the code as simple / fast?

**Comment by TommyClausner** [comment]
Hey @larsoner yes it's indeed a bit of a pity, but maybe you're right... 

The thing is just, that I'm not quite sure about your definition of "refinement" because often so far it happened that I produced version A, was asked to make version B and after another round version A* 

I guess this is mostly because you (mne) didn't commit fully to throw away previous API - if you would, we could rebuild it from scratch (and hopefully better) and include some temporary wrappers for the deprecation cycle - thoughts?

but of course I finish it for now including all suggested ;)

@agramfort compute_morph_matrix and morph_data are sometimes "abused" to do some things in e.g. testing files or examples or in labels or etc. - so I'll deprecate it now and fix all those things...
I guess it makes the code not "as simple" because difference is (in that particular example):
```
moprh_mat = mne.compute_morph_matrix(**stuff)
```
vs
```
moprh_mat = mne.SourceMorph(**stuff).params['morph_mat']
```
Comp time wise it should be equal to the pre-computation pipeline you had before (I use those functions)

**Comment by TommyClausner** [comment]
Thanks @massich !

**Comment by TommyClausner** [comment]
Yes, @larsoner sounds like a plan ! Thanks for pointing towards the important issues!

regarding 2 and 3) : doable, but bit annoying, since for vol it has way more parameters... so guess some dictionary in the back might be needed for this type at least I guess, ... but dk... 

Also it was @agramfort 's explicit wish to put the computation in ``__init__`` and make each **kwarg an attribute... So I guess that's between you guys then :D

But in general, yes I'll proceed as you suggested!

**Comment by TommyClausner** [comment]
btw: also: how would you like me to "submit" the stuff actually? atm I'm just trying to integrate the version I have now (including suggestions) and abuse the PR for testing, but how do I submit it finally?

**Comment by larsoner** [comment]
> why can I not delete compute_morph_matrix from python_reference.rst?

You'll have to be more specific as to what you mean. You should be able to delete it from `python_reference.rst`, use the `@deprecated` decorator on it, and wrap any calls currently in tests with `with pytest.deprecated_call` context manager and tests should pass.

> how would you like me to "submit" the stuff actually

This is good enough -- let's get things green here. Once that's done I can push a `morph` branch and we can open a new PR to it rather than `master`, which should also come back green and we can merge it there.

**Comment by TommyClausner** [comment]
Hey @larsoner  thanks! Thing is: I decorated it with deprecated but it doesn't let me delete it from the .rst anyway...

**Comment by TommyClausner** [comment]
nope...

**Comment by larsoner** [comment]
> but it doesn't let me delete it from the .rst anyway...

Again I'm not sure what this means. Do you get a doc build error? Does some test not pass?

Luckily I happened to be on GitHub to see what you actually did. You had some conflict when you did it. This means you need to rebase (preferably) or merge with `upstream/master`. But since you have a ton of commits (and a number that switch back and forth between states) this might be difficult. So for now you can leave it in so it is not a bottleneck and we can fix it later. I assume there are more important issues to work out still...?

**Comment by TommyClausner** [comment]
well actually I guess I'm done in the sense that I implemented the suggestions and e.g. did not delete the sparse part, so that you have it there when you refine it... In general it passes all my tests and all random examples I tried that e.g. use compute_morph_matrix I changed and they work as well...

**Comment by larsoner** [comment]
Let me know when the CIs are happy, or ping me if you are unsure how to make them happy

**Comment by TommyClausner** [comment]
all right ;)
just as a note - Google says I have to submit until tomorrow 18:00 - does this mean accepted by you?

**Comment by larsoner** [comment]
Hmmm... not sure. But to be safe I've pushed a `sourcemorph` branch. Let's see if CIs come back happy and either way close this and open a PR to that branch. Hopefully it's green but even if it's not we'll accept it there so there is no ambiguity :)

**Comment by TommyClausner** [comment]
All right thanks a lot!! I'll wait for them to complete here (to not waste time waiting ;) ) - and after correcting close here and PR there... :)

**Comment by TommyClausner** [comment]
That's indeed a little bit strange, since the volume that is created internally to apply the morph is the size of the reference MRI... For that reason I assume you have a really long time series(?) Maybe you could try down-sampling your time dimension(?)

On the other hand @larsoner and @agramfort - what do you think? Would a sparse make a significant difference here / should it be considered?

**Comment by larsoner** [comment]
> Any ideas? If the mri_shape is huge could a sparse matrix be used as an alternative?

I don't know enough about the nonlinear warp to know if this is possible. But to start we could loop through time chunks like you suggest.

**Comment by TommyClausner** [comment]
hm... as far as I can see, the bottleneck would be ``dipy.align.reslice.reslice`` - if that function takes sparse matrices, then it should work. 

Because the memory issue happens, where stc.data gets extrapolated to full MRI-resolution. For this a 4-D volume is created of zeros and filled. If the t-dim is too huge you get the error there (np.zeros) I assume. Afterwards the full-res series goes into ``dipy.align.reslice.reslice`` - so again:

if supported by dipy, one could make the result volume of ``_interpolate_data`` a sparse matrix (working internally completely with sparse then) and re-slice it as is (given dipy supports sparse) - but other than that I could indeed only think of looping :/

**Comment by agramfort** [comment]
@TommyClausner @WilliamCollishaw @larsoner this commit https://github.com/mne-tools/mne-python/pull/5466/commits/40da488de52b495fed0c4fa2c1d9c21dad6db40c should fix the memory issue. It's now in https://github.com/mne-tools/mne-python/pull/5466

**Pull request closed without merging**
