### PR TITLE
MRG, FIX: BTi reading bugs

### LINKED ISSUE #6032: 4D/BTi import error if pdf/config channel orders to not match
#### Describe the bug
If the order of channels is different in the config and header (pdf) files, than the current match algorithm will report that they do not match even if all channels are present in both. 

#### Steps and/or code to reproduce
You need to have a config and header file with channels in a different order. If you do, then all you need to do is:

raw = mne.io.read_raw_bti(filename) 

#### Expected results
import the file

#### Actual results
throws a runtime exception

#### Additional information
Platform:      Darwin-18.2.0-x86_64-i386-64bit
Python:        3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37)  [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
Executable:    /Users/joshbear/bin/anaconda3/envs/mne/bin/python
CPU:           i386: 8 cores
Memory:        16.0 GB

mne:           0.17.0
numpy:         1.14.2 {blas=mkl_rt, lapack=mkl_rt}
scipy:         1.1.0
matplotlib:    2.2.2 {backend=MacOSX}

sklearn:       0.19.1
nibabel:       2.2.1
mayavi:        4.5.1.dev0 {qt_api=pyqt5, PyQt5=5.10.1}
cupy:          Not found
pandas:        0.23.0
dipy:          Not found

### LINKED ISSUE #6048: 4D/BTi import error reading channel data
#### Describe the bug
Program fails to read a 4D data file, probably due to bad interpretation of 4D data file header

#### Steps and/or code to reproduce
 import mne
fname = 'c,rfDC,fbp3-75n,o'
raw = mne.io.read_raw_bti(fname)
 
#### Expected results
read in the raw data
 
#### Actual results
crashes 
/usr/local/lib/python3.5/dist-packages/mne-0.17.1-py3.5.egg/mne/io/bti/bti.py in _read_channel(fid)
    660                 'index': read_int32(fid),
    661                 'checksum': read_int32(fid),
--> 662                 'off_flag': read_str(fid, 16),
    663                 'offset': read_float(fid)})
    664
with UnicodeDecodeError: 'ascii' codec can't decode byte 0xa4 in position 4: ordinal not in range(128)
 
#### Additional information
Platform:      Linux-4.9.0-8-amd64-x86_64-with-debian-9.8
Python:        3.5.3 (default, Sep 27 2018, 17:25:39)  [GCC 6.3.0 20170516]
Executable:    /usr/bin/python3
CPU:           : 4 cores
Memory:        15.7 GB

mne:           0.17.1
numpy:         1.12.1 {lapack=lapack, blas=blas}
scipy:         0.18.1
matplotlib:    2.0.0 {backend=TkAgg}

sklearn:       0.18
nibabel:       2.1.0
mayavi:        Not found
cupy:          Not found
pandas:        0.19.2
dipy:          Not found

#### Proposed fix:
4D/BTi's $STAGE/map/src/include/dftk_channel_ref.h has
struct dftk_channel_ref_data
{ [...]
    int32_t         checksum;
    char            off_flag[4];
    float           offset;
    char            reserved[24];
};
and in mne/io/bti/bti.py 'off_flag' and fid.seek() should be adjusted:
def _read_channel(fid):
    [...]
                'checksum': read_int32(fid),
                'off_flag': read_str(fid, 4),
                'offset': read_float(fid)})
    fid.seek(24, 1)

### PR DESCRIPTION
**Pull request by larsoner**
@joshbear @ebeich can you 1) see if this works on your data and 2) check that you're happy with the name and URL I put in `whats_new.rst` (based on 2 minutes of Google investigation)? I just cherry-picked your commits and updated `whats_new.rst`. It would be nice to have some test data for these use cases but might be overkill for this corner case.

Closes #6048.
Closes #6033.
Closes #6032.

### CODE REVIEW

**Comment by agramfort** [comment]
@jdammers maybe has an opinion here?

**Comment by joshbear** [comment]
Sorry for my tardiness on this. I actually ran into another concern that these fixes allowed the importing of the data but did not properly classify channels (for example, I think one of the MEG channels is imported as ECG, etc.). It's almost certainly related to the same problem of what we are using to index the channels as the correct information is all there. I believe Brainstorm sorts the channels correctly, so I'm sure it will be relatively easy fix. I just haven't had a chance to dig into my problematic sample again yet. It will probably be a few weeks before I can do some of these tests.

**Comment by larsoner** [comment]
Okay, moving to the 0.19 release then (we can backport for a 0.18.1 release)

**Comment by jdammers** [comment]
I will discuss the problem with Eberhard and we will come back to you soon.

**Comment by massich** [comment]
@joshbear @ebeich could you also update `.mailmap`? thx

**Comment by larsoner** [comment]
@jdammers any chance to look in the next week so that we can get this into 0.19?

**Comment by jdammers** [comment]
@larsoner sorry for this delay we had a busy summer! It turned out that this is something for @ebeich to solve. He will come back next week from holidays, but I am not sure how far he came and if he could fix the problem already. Hopefully @ebeich can comment on this next week.

**Comment by larsoner** [comment]
Okay, I'll remove the 0.19 milestone so it gets into 0.20 (and maybe we can backport to 0.19)

**Comment by ebeich** [comment]
Dear Eric,

   for me things look okay now. I've included a small 4D sample data set
for testing, which should also make bad channel assignments visible,

Best regards,
   Eberhard

--
Dr. Eberhard Eich
Institute of Neuroscience and Medicine - 4
Medical Imaging Physics
Forschungszentrum Juelich GmbH
52425 Juelich
Germany

Tel: +49 2461 61-8976
Fax: +49 2461 61-2820
email: e.eich@fz-juelich.de
http://www.fz-juelich.de/inm


------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
Forschungszentrum Juelich GmbH
52425 Juelich
Sitz der Gesellschaft: Juelich
Eingetragen im Handelsregister des Amtsgerichts Dueren Nr. HR B 3498
Vorsitzender des Aufsichtsrats: MinDir Volker Rieke
Geschaeftsfuehrung: Prof. Dr.-Ing. Wolfgang Marquardt (Vorsitzender),
Karsten Beneke (stellv. Vorsitzender), Prof. Dr.-Ing. Harald Bolt,
Prof. Dr. Sebastian M. Schmidt
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------

**Comment by larsoner** [comment]
@ebeich if you attached the dataset to the email it didn't make it through (probably because the email was to a GitHub email address that just posts comments). Can you share it on DropBox or some other service? If not you can email it to me separately

**Comment by agramfort** [comment]
let's merge when green then. thx @larsoner @ebeich

**Comment by ebeich** [comment]
Here is a link to my demo-/test-dataset:
   https://www.dropbox.com/s/zddhzudjl8ywjen/4Dsim.zip?dl=0
md5: fc0dab69bd560c315d7d60c3cae997a7 4Dsim.zip

Best regards,
   Eberhard


------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
Forschungszentrum Juelich GmbH
52425 Juelich
Sitz der Gesellschaft: Juelich
Eingetragen im Handelsregister des Amtsgerichts Dueren Nr. HR B 3498
Vorsitzender des Aufsichtsrats: MinDir Volker Rieke
Geschaeftsfuehrung: Prof. Dr.-Ing. Wolfgang Marquardt (Vorsitzender),
Karsten Beneke (stellv. Vorsitzender), Prof. Dr.-Ing. Harald Bolt,
Prof. Dr. Sebastian M. Schmidt
------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------

**Pull request merged**
