### PR TITLE
BUG: Fix coordinate frame

### LINKED ISSUE #9250: BUG: EGI coords read but not transformed
Doing:
```
mne.viz.plot_alignment(mne.io.read_raw_egi('test_egi.mff').info, show_axes=True, dig=True, eeg=True, coord_frame='head')
```
gets sensor positions plus LPA/Nasion/RPA (good), but not transformed to the head coordinate frame (bad):

Screenshot from 2021-04-05 14-48-36

### PR DESCRIPTION
**Pull request by larsoner**
@christianbrodbeck see https://github.com/mne-tools/mne-python/issues/9250, this PR fixes the behavior in `main`:

```
>>> mne.viz.plot_alignment(mne.io.read_raw_egi(mne.datasets.testing.data_path() + '/EGI/test_egi.mff').info, show_axes=True, dig=True, eeg=True, coord_frame='head')
```
Screenshot from 2021-04-05 14-48-36

To properly transform to the head coordinate frame (this PR):

Screenshot from 2021-04-05 15-20-57

No need for latest.inc update because this was added within-cycle in #8789

Closes  #9250

### CODE REVIEW

**Review by agramfort — APPROVED** [review]
+1 for MRG provided @christianbrodbeck confirms it fixes the pb and we have a what's new entry.

thx heaps @larsoner !

**Review by hoechenberger — APPROVED** [review]

**Comment by larsoner** [comment]
> +1 for MRG provided @christianbrodbeck confirms it fixes the pb and we have a what's new entry.

Quoting above:

> No need for latest.inc update because this was added within-cycle in #8789

**Comment by agramfort** [comment]
ok then. Let's just make CIs green :)

**Comment by larsoner** [comment]
Failure was just a timeout but it actually passed:
```
= 2908 passed, 53 skipped, 220 deselected, 3 xfailed, 2 xpassed, 2 warnings in 2721.60s (0:45:21) =
```
so I'll go ahead and merge

**Pull request merged**
