### PR TITLE
Fix load_data

### LINKED ISSUE #2507: load_data problem with BrainVision
Because the brainvision module wasn't modified for the new  `_read_segment`, and `_read_segment_file` methods, it errors with withe `raw.load_data` method.

To reproduce the error:

```python
from mne.io.brainvision.tests import test_brainvision
from mne.io import read_raw_brainvision


raw = read_raw_brainvision(test_brainvision.vhdr_path, preload=False)
raw.load_data()
```

### PR DESCRIPTION
**Pull request by teonlamont**
closes #2507

Since brainvision files are stored across multiple files, one solution to the `load_data` method is to just override the helper function that normally refers to `_read_segment_file`.

### CODE REVIEW

**Comment by agramfort** [comment]
LGTM

@Eric89GXL merge if happy.

**Comment by Eric89GXL** [comment]
A few points:

- Why did you override `_preload_data`? You should only need to override `_read_segment_file` to get the correct behavior based on how the super `_BaseRaw` class works. Your description actually suggests you meant to override `_read_segment_file`, but in the code it's not what you did (instead overriding `_preload_data`) so I'm extra confused. It looks like `brainvision` currently overrides `_read_segment` instead of `_read_segment_file`, which is incorrect, so this probably needs to be refactored.

- For reference, see `_BaseRaw` class:
  https://github.com/mne-tools/mne-python/blob/master/mne/io/base.py#L219

- For examples, see how it's done for EDF:

  https://github.com/mne-tools/mne-python/blob/master/mne/io/edf/edf.py#L97

  And for FIF:

  https://github.com/mne-tools/mne-python/blob/master/mne/io/fiff/raw.py#L137

- Please add the `_test_concat` test for `brainvision`, it should be in there. `git grep` it and you'll see what I mean.

**Comment by Eric89GXL** [comment]
Ahh, I see now that you say that you override the function that *refers to* `_read_segment_file`. So that makes sense as far as how it relates to the changes you made, but it's not really the right/consistent behavior.

**Comment by teonlamont** [comment]
so what would you suggest. I figured that the `_read_segment_file` was really put in place for the FIF files seeing how they are the only ones I know of who split the files. If using the `_BaseRaw._read_segment` and replacing the `._read_segment_file` is more ideal, that would require, as you mention, a refactoring of the methods. In the past, it used to be only overwriting the `_read_segment` was necessary for the io modules.

**Comment by Eric89GXL** [comment]
`read_segment_file` is meant to be used by all classes, see how it is done for EDF and FIF above, and now that I notice also KIT, too:

https://github.com/mne-tools/mne-python/blob/master/mne/io/kit/kit.py#L208

Somehow I missed BrainVision doing it this different way during refactoring. So it should be changed to use the same mechanisms. It is more DRY and consistent with KIT/EDF/FIF reading. I can do it if you don't have time.

**Comment by Eric89GXL** [comment]
FYI I think at one point I refactored `_read_segment` into `_read_segment_file` because it made things a lot more DRY, since all those classes had repeated bits of code in them, and no longer do. If you look at the BrainVision `_read_segment` function, you'll see a lot of overlap with the now refactored `_BaseRaw._read_segment` file, which is not good (and was the point of the refactoring in the first place).

**Comment by Eric89GXL** [comment]
In other words, I think (as proposed in https://github.com/mne-tools/mne-python/issues/2507) you should only have to provide a correct `_read_segment_file` function (in addition to `__init__`) in your `RawBrainVision` class, and everything else like preloading should work as expected.

**Comment by Eric89GXL** [comment]
Also, the documentation here is meant to strongly suggest this as the proper solution:

https://github.com/mne-tools/mne-python/blob/master/mne/io/base.py#L219

If it is not clear that subclasses need to provide this method for non-preloaded data, please update the documentation in way that will make it clearer for the next person who wants to add/modify a format.

**Comment by teonlamont** [comment]
@Eric89GXL ah, that's good to know. I guess the issue arose because the `load_data` method was accessible to all the `Raw` objects, we probably should have given an overwrite with a `NotImplementedError`. 

unfortunately I am drowning with things this week so I would be unable to refactor (dissertation proposal on Friday, eek!). I can close this pr if you would like to take over.

**Comment by Eric89GXL** [comment]
Sure, I should have time to do it this week

**Comment by Eric89GXL** [comment]
@teonlamont any reason why an event channel isn't always added to the data? It seems to complicate the code a bit to have it be conditional. The conditional is also a bit weird -- I could have recorded a file with events "on" but had no events. I'd expect the converted file to have an events channel, but have that channel be all zeros, but that's not what currently happens. Do you think it's okay just to always add an event channel?

**Comment by teonlamont** [comment]
I think it would be fine to always add an event channel. I don't remember having added the conditional part but removing it would help simplify the code.

**Pull request closed without merging**
