### PR TITLE
[MRG] add grants that funded mne

### PR DESCRIPTION
**Pull request by agramfort**
let me know if I miss some

### CODE REVIEW

**Comment by kingjr** [comment]
show off ;)

**Comment by agramfort** [comment]
can you give me the text to add?

**Comment by dengemann** [comment]
That one I pasted. The grants don't have public numbers. Just truncate it
left and right.

**Comment by agramfort** [comment]
ok pushed

**Comment by Eric89GXL** [comment]
LGTM, feel free to merge once you're done

**Pull request merged**
