### PR TITLE
MRG: Fix dataset check [ci skip]

### LINKED ISSUE #5624: `has_dataset` in mne.datasets.uitls crashes
#### Describe the bug
This is not working:

https://github.com/mne-tools/mne-python/blob/9df12aa57dce2a75ba619c90abc6a6547dde9997/tutorials/plot_brainstorm_phantom_ctf.py#L45

#### Steps and/or code to reproduce
Please provide a code snippet or [minimal working example (MWE)](https://en.wikipedia.org/wiki/Minimal_Working_Example)
to replicate your problem.

This MWE should be self-contained, which means that other MNE-Python contributors
should be able to copy and paste the provided snippet and replicate the bug.
If possible, use MNE-Python testing examples to reproduce the error. Otherwise,
provide a small and anonymized portion of your data required to reproduce the bug.

If the code is too long, feel free to put it in a [public gist](https://gist.github.com) and link
it in the issue.

Example:

```Python
from mne.datasets.utils import has_dataset
has_dataset('brainstorm')
```

#### Expected results
A boolean describing if the dataset is either present or not.

#### Actual results
```sh
AttributeError: 'dict' object has no attribute 'split'
```

#### Additional information
```py
In [5]: mne.sys_info()
Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.
Platform:      Linux-4.15.0-34-generic-x86_64-with-debian-buster-sid
Python:        3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51)  [GCC 7.2.0]
Executable:    /home/sik/miniconda3/envs/mne/bin/python
CPU:           x86_64: 4 cores
Memory:        31.3 GB

mne:           0.17.dev0
numpy:         1.15.0 {blas=mkl_rt, lapack=mkl_rt}
scipy:         1.1.0
matplotlib:    2.2.2 {backend=Qt5Agg}

sklearn:       0.19.2
nibabel:       2.3.0
mayavi:        4.6.2.dev0 {qt_api=pyqt5}
cupy:          Not found
pandas:        0.23.3
dipy:          Not found
```

### PR DESCRIPTION
**Pull request by larsoner**
Closes #5624.

Probably not perfect but it seems to work for the ones I have on my system. You can see locally with:
```
pytest -s mne/datatsets
```
It should print the "have" status for a bunch of datasets.

### CODE REVIEW

**Comment by larsoner** [comment]
@massich feel free to merge if you are happy

**Comment by massich** [comment]
Sure. but my idea was to let this one to a first-time contributor.

**Comment by agramfort** [comment]
@massich please merge. We're in release mode so we have to go fast.

**Comment by massich** [comment]
It works on my machine.

**Comment by larsoner** [comment]
> but my idea was to let this one to a first-time contributor.

Yes it would have been nice, but it turns out the changes were actually a bit less straightforward.

**Comment by massich** [comment]
that's fine, and if it was needed. it makes total sense.

**Pull request merged**
