### PR TITLE
Backport: Fix backend='pyvista' in stc.plot() (#8395)

### PR DESCRIPTION
**Pull request by hoechenberger**

### CODE REVIEW

**Comment by hoechenberger** [comment]
I'm not sure why the notebook test fails… @GuillaumeFavelier mind having a look?

**Comment by hoechenberger** [comment]
@agramfort One test failed, yet you merged this PR – was this intentional or an accident?

**Comment by agramfort** [comment]
yes it's intentional. I did not think the issue was related. Was it?

>

**Comment by GuillaumeFavelier** [comment]
Yes. But it's just a small thing. On `maint/0.21.0` the attribute name is `_notebook` (with an underscore) instead of just `notebook`

**Comment by hoechenberger** [comment]
@GuillaumeFavelier 
> Yes. But it's just a small thing. On `maint/0.21.0` the attribute name is `_notebook` (with an underscore) instead of just `notebook`

But this PR didn't touch any of these… I don't get it. But you seem to be understanding what's going on :) I'd appreciate if you could file a follow-up PR if something is broken now? Or we can have a quick chat / call and you tell me what I need to fix :) 
btw check your Slack! ;)

**Comment by agramfort** [comment]
oups my bad....

>

**Comment by GuillaumeFavelier** [comment]
> But this PR didn't touch any of these…

The tests use the name :sweat_smile: 

I will open a PR that reverts to the old name and we backport it too. What do you say?

**Comment by hoechenberger** [comment]
> I will open a PR that reverts to the old name and we backport it too. What do you say?

perfect :)

**Pull request merged**
