### PR TITLE
WIP: Add text above orientation slider

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR updates the orientation slider of `_TimeViewer` and adds a `vtkTextActor` above the slider.

**Known issues**

For now, the text does not scale with the window size

Fullscreen | Resized
--------------|----------
2020-01-15_1920x1080 | 2020-01-15_1920x1080

It's an item of #7162

### CODE REVIEW

**Comment by larsoner** [comment]
BTW @GuillaumeFavelier I wonder if we should try to take the opposite approach by keeping our controls some fixed size. For example:
```
            scalar_bar.SetUnconstrainedFontSize(True)
            scalar_bar.GetLabelTextProperty().SetFontSize(14)
```
Makes the labels always the same size, which is kind of nice. If we could make our controls always on the right with some fixed width, this is more like how most GUIs display -- you scale up the window, the controls do not also scale up.

The time slider scaling to fill the width and colorbar scaling to fill the height are probably okay. But if we fix those, too, it might not be so bad.

Just some more ideas for someday. But I would say let's tackle this after the multi-view and linked-plotter ideas.

**Comment by GuillaumeFavelier** [comment]
> Just some more ideas for someday. But I would say let's tackle this after the multi-view and linked-plotter ideas.

I'm tempted to try those ideas in this PR actually.

**Comment by larsoner** [comment]
Over in #7219 it looks like you are doing some coordinate gymnastics anyway, might not be a bad time to figure out how to get some controls to always be some fixed width, fixed height, and fixed distance from the screen edge regardless of screen size.

Even the time slider and colorbar could in principle be made some fixed size. Though the time slider does become more usable the larger it gets, so maybe that one should grow. I'll let you think on it :)

**Comment by mmagnuski** [comment]
Just a thought: I think extending the sliders a bit (for example up to some max length) might be helpful in bigger windows - it gives the user more precision in selecting time and color limits (but still allows for all the sliders to fit in a smaller window).

**Comment by larsoner** [comment]
@GuillaumeFavelier do we still need this? The current behavior seems okay, this seems more like a "nice to have someday maybe" option

**Comment by GuillaumeFavelier** [comment]
The priority is really low and this is not so trivial to achieve. We can delay it further and focus on the [layout](https://github.com/mne-tools/mne-python/pull/7211#issuecomment-574801566) itself.

Either way, I agree with you this 'nice to have'.

**Comment by larsoner** [comment]
Okay let's close for now and reopen when someone is motivated

**Comment by GuillaumeFavelier** [comment]
I could find this `SetUnconstrainedFontSize()` function only for `vtkScalarBarActor`, not any other. It seems to be what we want though:

> Set/Get whether the font size of title and labels is unconstrained.
>
> Default is off. When it is constrained, the size of the scalar bar will constrained the font size. When it is not, the size of the font will always be respected.

Reference: https://vtk.org/doc/nightly/html/classvtkScalarBarActor.html#a668d039964548cca8f2b6c1a4e664689

**Pull request closed without merging**
