### PR TITLE
Clean up badges

### LINKED ISSUE #11551: Consider removing some badges
Currently, we have two rows of badges at the top of our README.rst:

Screenshot 2023-03-14 at 09 26 24

Do we really need the first row? This only shows build results from various workflows, which is not that interesting for users. Developers can look in other places (PRs) to check if our workflows are passing or not. I think removing the first row would make the document less crowded and more pleasant to view. WDYT?

### PR DESCRIPTION
**Pull request by cbrnr**
Fixes #11551. I've removed all CI badges, kept Codecov, and added a badge for our Discourse forum.

### CODE REVIEW

**Comment by cbrnr** [comment]
The Discourse badge is labeled "forum" right now, but I'm open to suggestions for better labels ("Discourse", "Community", ...). We should also probably capitalize the first letter just like in most other badges (except for "codecov", which we should also change to "Codecov").

**Comment by cbrnr** [comment]
Looks good I think: https://github.com/mne-tools/mne-python/blob/bd4a10a32c5ccbf0200e0dd6a5a99dc5374087b8/README.rst

**Review by larsoner — APPROVED** [review]
> The Discourse badge is labeled "Community" right now

Works for me!

> Although I still think Coverage doesn't really belong there anymore.

I think one big advantage that MNE has is that it is well covered by tests, so I like keeping this as a bit of advertisement

@drammock feel free to merge if you're also happy

**Comment by drammock** [comment]
> one big advantage that MNE has is that it is well covered by tests

agreed. IMO this is actually useful to programmerly folks who are unfamiliar with our project

**Pull request merged**
