### PR TITLE
DOC : Adds copy button to code blocks

### LINKED ISSUE #8957: Add "copy" button to code blocks
Code blocks, at least in the tutorials, should come with a "copy" button, allowing users to conveniently copy code snippets to the clipboard.

Not sure if this is something that needs to be addressed upstream?

### PR DESCRIPTION
**Pull request by ramkpari**
#### Reference issue
Fixes #8957 .

#### What does this implement/fix?
Adds a copy button to all code blocks using sphinx-copybutton. 

#### Additional information
Updated the requirements_doc.txt to reflect addition of sphinx-copybutton.

### CODE REVIEW

**Comment by rob-luke** [comment]
https://25918-1301584-gh.circle-artifacts.com/0/dev/auto_tutorials/preprocessing/plot_55_setting_eeg_reference.html#sphx-glr-auto-tutorials-preprocessing-plot-55-setting-eeg-reference-py

I can see a copy box!

**Review by rob-luke — APPROVED** [review]

**Review by agramfort — APPROVED** [review]
+1 for MRG if CIs are happy. Not the case as it is

**Comment by larsoner** [comment]
No need for the other CIs on this one I think, thanks @ramkpari !

**Comment by hoechenberger** [comment]
Awesome!

**Pull request merged**
