### PR TITLE
WIP: Set physical range to digital range for stim channels

### LINKED ISSUE #5159: Can't read events from BDF file
Hi all,

When i import my data from the BDF format ([test.zip](https://github.com/mne-tools/mne-python/files/1941601/test.zip)) i can't read the event list. The events are present in the data as i can read them using EEGLAB.

i loaded the code using:
`raw = mne.io.read_raw_edf(bdf_file, stim_channel="Status")`
i have tried
`raw.find_edf_events()`
as well as
`mne.find_events(raw)`

both functions return an empty array.

when i use `raw.plot()` the stimulus channell appears to be completely flat.
i looked at the stim channel value for each sample:
`data = raw.to_data_frame()`
`print(data["STI 014"])`
the value at every sample is 41009.0 ( i have no idea where that comes from)

Not sure where i am doing something wrong (I'm pretty new to MNE-Python and EEG-Data processing in general) and i hope you can help me with this.

best,
Ole

### PR DESCRIPTION
**Pull request by cbrnr**
Fixes #5159. This is a long shot, let's see if other things break.

### CODE REVIEW

**Comment by cbrnr** [comment]
I ran the EDF tests locally, and `test_edf_stim_channel` fails in line 267 (`assert_array_equal(true_data[-1], edf_data[-1])`). However, I'm not sure if the text file (`true_data`) actually contains the true data, because even in `master` the data of the regular channels are not identical in the two arrays (but the stim channels match).

**Comment by cbrnr** [comment]
Forget my comment about the data not being equal, I just saw that you have to multiply them by `1e-6`.

**Comment by cbrnr** [comment]
In the test file from #5159, the stim channel gets scaled so that `data[stim_channel_idx].min()` is `41009.076118414174` and `data[stim_channel_idx].max()` is `41009.16551108155`. Then the array is converted to an `int` array in [lines 318-319](https://github.com/mne-tools/mne-python/blob/master/mne/io/edf/edf.py#L318-L319), which is why all values are identical to `41009`. 

Does anyone have a suggestion what we could do in such a situation?

In addition, I have no idea what the bitwise and with `2**17 - 1` does...

**Comment by cbrnr** [comment]
I can scale the stim channel up if the difference between max and min is less than 1. This actually seems to work and doesn't require tinkering with the physical/digital min and max. All EDF-related tests pass on my local machine.

**Comment by larsoner** [comment]
Determining data scaling based on the contents of the data is dangerous. For one example, your code here will break if the `max` and `min` of the data are the same (though this can be fixed with a conditional). For another, consider if one file has only trigger value `1`, another has only a value of `100`, and a third file has both `1` and `100`. These will be messed up, right?

The information to scale properly is not located anywhere in the file itself?

**Comment by cbrnr** [comment]
The information is in the file header, but for whatever reason even the stim channel gets rescaled. This results in values that differ only in the fifth decimal place, so converting that to `int` yields identical values.

**Comment by cbrnr** [comment]
Regarding your points, if the minimum equals the maximum there are no events we can extract. Also, I'm only rescaling if the difference between max and min is less than 1, so your example would not be a problem. My thinking was that there must be something wrong if the stim channel values differ by less than 1.

**Comment by larsoner** [comment]
> Also, I'm only rescaling if the difference between max and min is less than 1, so your example would not be a problem.

I guess I'm really getting at "do we have a way to know that this will this always work for people"? Can a file reasonably have values at that point in the code with a peak-to-peak of 0.9999? Of 1.00001? If both of these are possible, do these depend on the actual triggers that were used during acquisition? If so, then this code will not work robustly.

However, if we are guaranteed that exclusively 1) values are encoded as `float-like` between 0 and 1 *or* 2) values are encoded as integers, then some variant of what you have (triaging based on peak-to-peak) will probably work. If we do not have this guarantee, then I don't think it will. Agreed?

And if the answers to these questions are "we don't know", then I think we're taking a risk implementing another EDF fix that might fix one thing and break another. Perhaps instead we shouldn't do any `int` casting, and instead warn if the data are not already `int`-like until we can figure out what the right thing is to do based on the EDF trigger format / specs.

**Comment by cbrnr** [comment]
Absolutely, this is definitely a bad hack almost guaranteed to break other files. The problem is that this is an ordinary data channel, so it is not standardized at all. As long as there is some way to derive events via differentiation (i.e. at time instants when values change), everything is possible. This is not the dedicated annotation channel labeled "EDF Annotations", which we already parse separately.

Converting to `int` seems like a bad idea in this case. Also, I am still clueless why it is then and-masked with `2**17 - 1`. Biosig can parse this channel correctly as events. Maybe something you could help us out @holgern?

**Comment by cbrnr** [comment]
> Do they not limit their events to be integer values? Then nothing magical should need to be done.
> Or you mean they don't have this weird scaling issue, and do have integer values (or at least nicer floats)?

I don't know, I think they also have integer event codes. Biosig seems to treat this channel differently, maybe based on the channel label (it is called "Status").

**Comment by cbrnr** [comment]
Yes, I can confirm that BioSig treats channels labeled "Status" in a BDF file as event channels, which means that they don't show up as data channels at all. There is even a dedicated function `bdf2biosig_events` that converts a BDF Status channel to events (using one of various modes).

How do we want to proceed? It might be a good idea to mimic what BioSig does, i.e. treat "Status" channels differently (given that the `stim_channel` argument is set to `'auto'` or to a specific channel label/index).

**Comment by agramfort** [comment]
sounds fair to me

**Comment by cbrnr** [comment]
I'm now scaling only data channels after processing the stim channel. This seems like the right thing to do, and it does work with the test file by @ElBibulo. Here, we now get exactly the values he was expecting (1, 2, 3, and 4).

However, this means that event values might change for other files, such as in `test_edf_stim_channel`, which expects values 0 and 100, but the reader now produces 98304 and 32767. I'm not sure how to proceed.

Either we interpret a channel as a data channel - then we apply the necessary scaling. Or we interpret it as a stim channel, then the scaling should not matter because we're converting the channel to `int` anyway. But we can't extract events from a scaled data channel (in general), which like in this example file has values that differ in the fifth decimal place due to scaling (and we are converting stim channels to `int`).

I have no idea why this channel gets scaled like that, but that's what's in the header. EDF does not restrict scaling of stim channels to 1. In fact, EDF doesn't even define stim channels.

Ideas?

**Comment by larsoner** [comment]
Should we scale EDF but don't scale BDF Status channel?

**Comment by larsoner** [comment]
> If you want to define a channel as a stim channel, you shouldn't expect to get any specific values 

I'm surprised by this. Is this some peculiarity of EDF/BDF? With the systems I'm used to, you know exactly what trigger values are stamped during recording, and should expect that stim channels will accurately reflect them.

Maybe we should look at what values `pyedflib` or other libraries give for these files. It's possible they know something about the formats that we don't.

**Comment by cbrnr** [comment]
Biosig doesn't find any events in `test_edf_stim_channel.edf`. Instead, it interprets the last channels as a normal data channel, and the values are what we expect (0 and 100) because a data channel gets scaled according to the header settings.

In the case of `test.bdf` that started this discussion, Biosig recognizes the channel labeled "Status" as an event channel. The values of the events are coincidentally mapped to 1-4, which in this case is what we expected. But I think this is because events that are not recognized by Biosig are always mapped to numbers starting at 1.

We have a Biosemi amp, and sometimes there is an offset of some power of 2 value that I need to subtract before I get the expected values. And yes, this is a peculiarity of file formats that store events in a data channel. A much better option is a dedicated event channel, such as in GDF or EDF+, where events are really treated as events.

**Comment by larsoner** [comment]
> We have a Biosemi amp, and sometimes there is an offset of some power of 2 value that I need to subtract before I get the expected values.

FYI `mask` and `mask_type='not_and'` in `find_events` will do this sort of thing for you. Basically it means that there is some bit that is always "on" in your data. Bit-masking is a little bit safer than subtraction because it also works if the bit turns on and off (instead of always staying on).

> And yes, this is a peculiarity of file formats that store events in a data channel. A much better option is a dedicated event channel, such as in GDF or EDF+, where events are really treated as events.

I'm not clear on what makes events stored in a "data channel" vs events stored in a dedicated "event channel". In Neuromag (and it sounds like Biosemi), the TTL pulses are encoded converted to integers and stored some channel (or multiple channels), but this channel (or these channels) are no different from other channels in terms of how data are stored, scaled, etc. They just receive a different `type` in the meas info, and are useful because they contain integers.

Thus if the file is written correctly (with correct scaling factors, etc. based on how the data are stored internally), nothing special needs to be done.

> Biosig doesn't find any events in test_edf_stim_channel.edf. Instead, it interprets the last channels as a normal data channel, and the values are what we expect (0 and 100) because a data channel gets scaled according to the header settings.

This is what we try to do -- and seems like the correct thing to do -- in MNE as well, at least according to my interpretation above. In this sense, instead of "doesn't find any events" I would say "does not do anything special to the channels to deal with events", as the events are still there and encoded properly / in the standard way.

There are other formats that have events stored using discrete markers (e.g., Brainvision, maybe also GDF and EDF+?). In MNE we do some work to convert these to the integer-values-in-a-data-channel representation so that `find_events` will usually work. But I don't think that's what we're talking about here.

From what I can tell, the problem is that some files put in bad scaling values so that the channel that is supposed to encode integers related to TTL pulses during the experiment do not write the scale factors correctly, so we end up with non-integer values in the channel.

If this is true, and we know that the BDF "Status" channel always (or hopefully almost always) has this property that the scale factors don't make sense, then it seems like the right fix to treat the "Status" channel in a special way.

**Comment by cbrnr** [comment]
> FYI `mask` and `mask_type='not_and'` in `find_events` will do this sort of thing for you. Basically it means that there is some bit that is always "on" in your data. Bit-masking is a little bit safer than subtraction because it also works if the bit turns on and off (instead of always staying on).

Yes, by subtraction I really meant I am applying some mask until I get the desired values.

I prefer to treat events and data channels as different entities. I don't really like the concept of trying to coerce discrete markers into a continuous stim channel. Why do we have to invent a new channel when all we need are the events? This can lead to inconsistencies as we have seen in the output of `mne.find_events` and `edf.find_edf_events`. But some systems, including Biosemi, only work with events in a regular data channel, so we can't get around this problem.

You are right that if the scaling values in the file header are correct, we should get the expected integer values that we recorded. And you are also correct that in this BDF file, the scaling values are apparently bad, which leads to float values. But there is nothing in the specs that tells us that the scalings are bad. This is what I was trying to do by setting the scaling to 1 if I get floats, but we agreed that this was a pretty unstable solution.

We already have the argument `stim_channel` for the user to specify which channel should be interpreted as a stim channel. If we set `stim_channel=None`, we do nothing special. If we set it to `'auto'`, we can take the last channel (or I can add code that chooses channel "Status" if it exists in BDF files). But then what do we do with this stim channel? Do we scale it as per the information in the header, which doesn't work if the scaling is wrong? Other toolboxes such as Biosig seem to derive event information from the stim channel in its unscaled form.

**Comment by larsoner** [comment]
> I prefer to treat events and data channels as different entities. I don't really like the concept of trying to coerce discrete markers into a continuous stim channel. Why do we have to invent a new channel when all we need are the events? This can lead to inconsistencies as we have seen in the output of mne.find_events and edf.find_edf_events. But some systems, including Biosemi, only work with events in a regular data channel, so we can't get around this problem.

I would agree if I were starting a package and file formats from scratch. But this is how we currently do things in MNE-Python, and how we write files (in the FIF format spec). We can have a bigger conversation about the refactoring necessary to move away from this elsewhere, but it's out of scope for fixing this issue. So for here it seems most productive to stick with the concept, flawed though it may be, that we should try to shoehorn each format into a FIFF/Biosemi/EDF-like encoding of events as integers in a channel.

> But then what do we do with this stim channel? Do we scale it as per the information in the header, which doesn't work if the scaling is wrong? Other toolboxes such as Biosig seem to derive event information from the stim channel in its unscaled form.

How about we add an argument `stim_scaling='auto' (default) | True | False`. `'auto'` means `True` (use header values just like for all other channels) for anything other than `"Status"` channel in a BDF file. False means "do not scale". It seems like this would make all of our test files "just work" and for unknown cases we will inevitably hit, we have given people the option to scale or not.

**Comment by cbrnr** [comment]
Agreed, we should focus on fixing this issue. I don't really have the time anyway to completely refactor how events are represented ATM.

I like your idea of introducing a new argument! This seems like a great solution! I'll push an update to this PR ASAP.

**Comment by larsoner** [comment]
In the code where you implement it, could you put in a mention of `gh-5160` in a comment? Future @cbrnr and @larsoner will probably appreciate it when looking at the spaghetti code we are making :)

**Comment by cbrnr** [comment]
Sure, will do :smile:!

**Comment by teonbrooks** [comment]
five years later (https://github.com/mne-tools/mne-python/pull/832) I am still haunted by the EDF format 👻
to echo @larsoner, the TTL pulse into the data channel used to be (and still is) a convention for reporting out event markers in the data. I agree that annotations or integer values are the best but a lot of setups still rely on this method. 

we should still have a suite of irregular edf files. we should make sure to check against them

**Comment by cbrnr** [comment]
@teonbrooks file formats are a nightmare! I'm sure someone will come back to me in five years regarding either this or some other "feature" I've added to our readers... 😵 

@larsoner, are you OK with adding the new argument `stim_scaling` to `BaseRaw._read_segment_file` and the overridden method in `RawEDF`? If yes, I'll also add it to `read_raw_edf` and `RawEDF.__init__`, and the best position for the new argument would be right after `stim_channel`. Or do you want me to add it at the end right before the `verbose` argument?

**Comment by cbrnr** [comment]
I don't know, I feel a bit uncomfortable changing such a widely used class. We could also just implement this behavior (scale stim channels for EDF, don't scale for BDF) by default and fix it when the next file breaks.

**Comment by agramfort** [comment]
> @teonbrooks <https://github.com/teonbrooks> file formats are a nightmare!

well FIF is complicated but files are a lot more consistent and unambiguous
to read.

**Comment by cbrnr** [comment]
Looks good so far, ready to merge when all Travis jobs are happy!

**Comment by larsoner** [comment]
So no need for a new parameter now?

Instead of triaging during this indexing operation, would it be cleaner for BDF stim channel to ensure that the scale factors are set properly to not scale the data?

**Comment by cbrnr** [comment]
> So no need for a new parameter now?

This would involve changing a method in the base class (at least its signature), but I don't think this is a good idea since this seems to be a BDF-related peculiarity.

> Instead of triaging during this indexing operation, would it be cleaner for BDF stim channel to ensure that the scale factors are set properly to not scale the data?

You mean setting `cal` and `gains` to `1` and `offsets` to `0` for the stim channel? I'm not sure if this is cleaner, the way it's done now ensures that the original scaling values from the file header are at least accessible.

**Comment by larsoner** [comment]
> This would involve changing a method in the base class (at least its signature

It shouldn't involve any change in `BaseRaw` if that's what you mean. Each reader can put arbitrary data in `_raw_extras` and use it whenever they need to.-

> You mean setting cal and gains to 1 and offsets to 0 for the stim channel? I'm not sure if this is cleaner, the way it's done now ensures that the original scaling values from the file header are at least accessible.

The idea is that for BDF we can/should probably think of these values as being incorrect, as they scale things incorrectly. In that sense, it makes sense to correct the problem by changing the errant scale factors rather than introducing a conditional about what scale factors to apply during the reading phase. But it probably doesn't make too much difference.

**Comment by cbrnr** [comment]
> It shouldn't involve any change in `BaseRaw` if that's what you mean. Each reader can put arbitrary data in `_raw_extras` and use it whenever they need to.

You're right, this would have been necessary only if we'd added a new argument to `_read_segment_file` - then I think we'd had to add that to the super method as well, right? Since a new argument is not necessary, this issue has been resolved for me.

> The idea is that for BDF we can/should probably think of these values as being incorrect, as they scale things incorrectly. In that sense, it makes sense to correct the problem by changing the errant scale factors rather than introducing a conditional about what scale factors to apply during the reading phase. But it probably doesn't make too much difference.

Right, I can do it either way, the result will be identical. But I wouldn't correct the scale factors in the `_raw_extras` dict, because people might want to apply the (possibly errant) scale factors for whatever reasons. So in the `if subtype == 'bdf'` I would then set `cal`, `offsets`, and `gains` to 1 and 0, respectively, so this would merely be an internal implementation detail.

**Comment by cbrnr** [comment]
@larsoner @agramfort do you want me to change anything? Otherwise I think this could be merged (and I'd also backport it to 0.16).

**Comment by agramfort** [comment]
is it bug fix ? or API change? it seems more an API change so I would not backport.

can we add a test for this?

**Comment by cbrnr** [comment]
This is a bug fix, I didn't change the API. I'll add a test, the best thing would be to add the problematic BDF file. I have to find/create a small file, because I guess we don't want to add another 15MB just for this test.

**Comment by larsoner** [comment]
@cbrnr do you have time to make this tiny file?

**Comment by cbrnr** [comment]
I found a bug related to reading with `preload=False`, this is fixed (and I've added a test). I've also cropped the BDF file from @ElBibulo (it contains only 3 data and 1 stim channel, and is only 20 seconds long). @ElBibulo could you please give us permission to use your file (heavily cropped, see the Files changed tab)?

If @ElBibulo agrees and CIs are happy, this is ready to be merged.

**Comment by agramfort** [comment]
can we avoid putting a new binary file in the repo and put the file in mne-testing if we have permission?

**Comment by cbrnr** [comment]
Yes, I can certainly do that.

**Comment by cbrnr** [comment]
@agramfort but note that the file is only 61kB. I know that we want to move all test files out of the main repo, but currently this means that I have to download the whole test data repo, which is almost 1GB. See also #4926.

**Comment by agramfort** [comment]
or fair enough. 61kB is really small.

ok for you @larsoner 

@cbrnr can you see why travis complains?

**Comment by larsoner** [comment]
I put it in `mne-testing-data`, PR forthcoming to this branch to bump to 0.49

**Comment by cbrnr** [comment]
Let's just make sure we get permission to use this file. And let's discuss how to proceed in the future in #4926.

**Comment by larsoner** [comment]
(for some reason I could not make a PR to your branch)

> Let's just make sure we get permission to use this file. And let's discuss how to proceed in the future

Sure but in the meantime I don't want to add more files to `mne-python`. Until we make this decision I think they should live in `mne-testing-data`. It sounded like your opposition to doing this here was mostly that it involved downloading a lot of data on your machine, which you no longer have to deal with because I did it instead. (You can mirror the changes locally just by copying the file over to the right place.)

**Comment by cbrnr** [comment]
Thanks @larsoner. Yes, downloading the whole repo is really unwieldy. Thanks for solving this for this issue, but the problem remains in general. Now I can't run the test without the huge download.

**Comment by agramfort** [comment]
it's not so huge... and it's a git repo with incremental updates. Also this
tells me that you don't have the testing data on your system to run the
tests locally?

**Comment by larsoner** [comment]
> Now I can't run the test without the huge download.

See my comment above as:

> You can mirror the changes locally just by copying the file over to the right place.

In other words, move the file that you had in `io/edf/tests/data` to `MNE-testing-data/BDF/`.

For devs who needs latest updates often and doing the 1GB download with `python -c "import mne; mne.datasets.testing.data_path(force_update=True, verbose=True)` in the background is untenable, you can also incrementally update locally by downloading files from commits rather than updating everything. It is manual work but shouldn't take more than a minute or two.

**Comment by cbrnr** [comment]
@agramfort yes, basically because every time I tried downloading the repo from GitHub it was super slow. So yes, I don't run all tests locally 😺 (thanks Travis!).

@larsoner I see - manually moving a file to a different folder is tenable for running specific tests. Re your latest comment, the problem was getting a complete checkout once. Updating should be straightforward afterwards.

All in all, it is OK, but any improvement to make this process easier would be highly welcome.

**Comment by cbrnr** [comment]
OK, ready to merge. Ideally, we should get permission to use this data set, but it seems like @ElBibulo isn't responding anymore. In any case, the data is heavily cropped, and already in the other repo.

**Comment by ElBibulo** [comment]
Sorry i missed your first request. Of course you can use the data :)

**Comment by cbrnr** [comment]
Great, thanks @ElBibulo!

**Comment by cbrnr** [comment]
@larsoner please feel free to merge, I'm all set.

**Comment by larsoner** [comment]
Thanks @cbrnr

**Pull request merged**
