### PR TITLE
MRG: Use VTK8 and Qt 5.9+

### PR DESCRIPTION
**Pull request by larsoner**
Let's see how the CIs like this.

### CODE REVIEW

**Comment by larsoner** [comment]
Green!?!

@cjayb can you see if this works on your computer to get VTK8?

Ready for review/merge from my end.

**Comment by cjayb** [comment]
Unfortunately not, mayavi wheels fail:

[environment_vtk8_mayavi_error.txt](https://github.com/mne-tools/mne-python/files/1805658/environment_vtk8_mayavi_error.txt)

On a hunch, I moved pyqt from conda (`pyqt=5`) to pip (`pyqt5`), and it compiled. `mne coreg` starts ok (#4971), though still some weirdness remains (two display opts windows, greying wonky but basically functional)

**Comment by larsoner** [comment]
@cjayb maybe you need to update conda? It built fine on OSX on Travis.

**Comment by larsoner** [comment]
Okay this is ready for review/merge from my end.

@agramfort this would be a good candidate to get a better working OSX env, especially since it properly supports HiDPI.

**Comment by cjayb** [comment]
I'm not sure I'm reading it right, but I think Travis is running on a Darwin16-instance, whereas my High Sierra-mac reports Darwin17 and clang 9.0.0 (vs. 8.x). I'm guessing this is why I still can't get the `env` in this PR to build:

[cjayb_env5012.log](https://github.com/mne-tools/mne-python/files/1809756/cjayb_env5012.log)

This would by far be the first High Sierra-related troubles various sw have. My hunch is that `pyqt` 5.10 solves this for `mayavi`, but it's not on `conda-forge` yet, hence having to get it off `pip` (as `PyQt5`). 

FYI Looks like [`pyface`](https://github.com/enthought/pyface/issues/293)/[`traitsui`](https://github.com/enthought/traitsui/pull/433) are working towards releases against Qt5, so `pip`-installable dependencies perhaps on the horizon (pinned git commits give me the creeps).

**Comment by larsoner** [comment]
The weird thing is that AFAIK I am using a fully up-to-date OSX + dev tools. It's weird you have the problem and I don't.

I would say we should wait for a release of those libraries, but sometimes releases can get delayed for months.

**Comment by agramfort** [comment]
agreed !

time to transition to python 3 for real !

**Comment by christianbrodbeck** [comment]
Wouldn't it be worth at least mentioning that `conda install mne` gives a fully functional 2.7 install, without compiling for half an hour or so (which this env did when I installed it the first time)?

**Comment by larsoner** [comment]
I think we should offer only one way of installing for simplicity for both users and our support overhead. There is a note at the top now saying that there are multiple ways of installing.

Regarding the 2.7 env alternative specifically, there are a few things that would prevent me from recommending it:

1. 2.7 reaches EOL for updates for NumPy in just 9 months
2. the 2.7 env last I checked held back to Qt4, which helds back MPL to 1.5
3. it also held back NumPy and SciPy (not sure if it does anymore, though)
4. CircleCI's 2.7-based env has bugs with Mayavi/VTK text rendering, see [how CircleCI renders for the last few months or so](https://7291-1301584-gh.circle-artifacts.com/0/tmp/circle-artifacts.bA2s3jk/html/auto_tutorials/plot_mne_dspm_source_localization.html)

Once a 3+ Qt5 env (with proper OSX HiDPI) is supported out of the box with Anaconda, I'd be happy to switch, though. I agree it's not optimal to have to force people to use an `environment.yml`, but so far it seems to offer the best experience.

**Comment by christianbrodbeck** [comment]
I agree that long term goal is to switch, but would favor using stable releases as long as development versions have issues like the sudden crash with the duplicating mayavi toolbar...

> the 2.7 env last I checked held back to Qt4, which holds back MPL to 1.5

With `$ conda create -n mne27 -c conda-forge mne` I get matplotlib 2.2

By the way with the env from this PR, `mne coreg` from your `coreg2` branch does not even launch anymore, don't know if I did something wrong with the install? After `mne coreg` I get 

screen shot 2018-03-23 at 12 56 11 pm

and in the terminal

```
(mne) Christians-Mini ~/Code$ mne coreg
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:178: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  out = np.fromstring(fid.read(tag_size), dtype=dtype)
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:363: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  version=int(np.fromstring(fid.read(4), dtype=">i4")),
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:364: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  machid=np.fromstring(fid.read(8), dtype=">i4"),
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:365: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  secs=int(np.fromstring(fid.read(4), dtype=">i4")),
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:366: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  usecs=int(np.fromstring(fid.read(4), dtype=">i4")))
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:178: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  out = np.fromstring(fid.read(tag_size), dtype=dtype)
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:178: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  out = np.fromstring(fid.read(tag_size), dtype=dtype)
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:178: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  out = np.fromstring(fid.read(tag_size), dtype=dtype)
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:178: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  out = np.fromstring(fid.read(tag_size), dtype=dtype)
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:178: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  out = np.fromstring(fid.read(tag_size), dtype=dtype)
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:178: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  out = np.fromstring(fid.read(tag_size), dtype=dtype)
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:178: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  out = np.fromstring(fid.read(tag_size), dtype=dtype)
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:178: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  out = np.fromstring(fid.read(tag_size), dtype=dtype)
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:178: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  out = np.fromstring(fid.read(tag_size), dtype=dtype)
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:178: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  out = np.fromstring(fid.read(tag_size), dtype=dtype)
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:244: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  ndim = int(np.fromstring(fid.read(4), dtype='>i4'))
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:246: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  dims = np.fromstring(fid.read(4 * ndim), dtype='>i4')[::-1]
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:263: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  data = np.fromstring(read_big(fid, 4 * dims.prod()), dtype='>f4')
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:244: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  ndim = int(np.fromstring(fid.read(4), dtype='>i4'))
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:246: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  dims = np.fromstring(fid.read(4 * ndim), dtype='>i4')[::-1]
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:263: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  data = np.fromstring(read_big(fid, 4 * dims.prod()), dtype='>f4')
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:244: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  ndim = int(np.fromstring(fid.read(4), dtype='>i4'))
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:246: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  dims = np.fromstring(fid.read(4 * ndim), dtype='>i4')[::-1]
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:259: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  data = np.fromstring(read_big(fid, 4 * dims.prod()), dtype='>i4')
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:178: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  out = np.fromstring(fid.read(tag_size), dtype=dtype)
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:363: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  version=int(np.fromstring(fid.read(4), dtype=">i4")),
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:364: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  machid=np.fromstring(fid.read(8), dtype=">i4"),
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:365: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  secs=int(np.fromstring(fid.read(4), dtype=">i4")),
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:366: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  usecs=int(np.fromstring(fid.read(4), dtype=">i4")))
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:178: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  out = np.fromstring(fid.read(tag_size), dtype=dtype)
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:178: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  out = np.fromstring(fid.read(tag_size), dtype=dtype)
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:178: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  out = np.fromstring(fid.read(tag_size), dtype=dtype)
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:372: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  kind=int(np.fromstring(fid.read(4), dtype=">i4")),
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:373: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  ident=int(np.fromstring(fid.read(4), dtype=">i4")),
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:374: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  r=np.fromstring(fid.read(12), dtype=">f4"),
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:372: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  kind=int(np.fromstring(fid.read(4), dtype=">i4")),
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:373: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  ident=int(np.fromstring(fid.read(4), dtype=">i4")),
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:374: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  r=np.fromstring(fid.read(12), dtype=">f4"),
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:372: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  kind=int(np.fromstring(fid.read(4), dtype=">i4")),
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:373: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  ident=int(np.fromstring(fid.read(4), dtype=">i4")),
//anaconda/envs/mne/lib/python3.6/site-packages/mne/io/tag.py:374: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  r=np.fromstring(fid.read(12), dtype=">f4"),
QWidgetWindow(0x7ff02f737a30, name="QMainWindowClassWindow") ( QScreen(0x7ff02c41c1c0, name="SMS27A850") ): Attempt to set a screen on a child window.
QWidgetWindow(0x7ff02f737a30, name="QMainWindowClassWindow") ( QScreen(0x7ff02c41c1c0, name="SMS27A850") ): Attempt to set a screen on a child window.
QWidgetWindow(0x7ff02f737a30, name="QMainWindowClassWindow") ( QScreen(0x7ff02c41c1c0, name="SMS27A850") ): Attempt to set a screen on a child window.
QWidgetWindow(0x7ff02df9e5d0, name="_ToolBarClassWindow") ( QScreen(0x7ff02c41c1c0, name="SMS27A850") ): Attempt to set a screen on a child window.
QWidgetWindow(0x7ff02f737a30, name="QMainWindowClassWindow") ( QScreen(0x7ff02c41c1c0, name="SMS27A850") ): Attempt to set a screen on a child window.
QWidgetWindow(0x7ff02df9e5d0, name="_ToolBarClassWindow") ( QScreen(0x7ff02c41c1c0, name="SMS27A850") ): Attempt to set a screen on a child window.
QWidgetWindow(0x7ff02f70afd0, name="_GroupSplitterClassWindow") ( QScreen(0x7ff02c41c1c0, name="SMS27A850") ): Attempt to set a screen on a child window.
```

The installation output was this: 

```
(mayavi45) Christians-Mini ~/Downloads$ conda env create -f environment.yml
Using Anaconda API: https://api.anaconda.org
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.4.11
  latest version: 4.5.0

Please update conda by running

    $ conda update -n base conda



Downloading and Extracting Packages
qtpy 1.4.0: ################################################################################################################################################################# | 100% 
pylint 1.8.3: ############################################################################################################################################################### | 100% 
numpy 1.14.2: ############################################################################################################################################################### | 100% 
matplotlib 2.2.2: ########################################################################################################################################################### | 100% 
intel-openmp 2018.0.0: ###################################################################################################################################################### | 100% 
jupyter_client 5.2.3: ####################################################################################################################################################### | 100% 
notebook 5.4.1: ############################################################################################################################################################# | 100% 
astroid 1.6.2: ############################################################################################################################################################## | 100% 
jedi 0.11.1: ################################################################################################################################################################ | 100% 
mkl 2018.0.2: ############################################################################################################################################################### | 100% 
spyder 3.2.8: ############################################################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Collecting git+https://github.com/enthought/traits.git@a99b3f64d50c5f7f28ffc01bf69419b061f9e976 (from -r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 3))
  Cloning https://github.com/enthought/traits.git (to a99b3f64d50c5f7f28ffc01bf69419b061f9e976) to /private/var/folders/85/kmfd5l4s0z3c8kcpvpj24vq80000gn/T/pip-gb11hd97-build
  Could not find a tag or branch 'a99b3f64d50c5f7f28ffc01bf69419b061f9e976', assuming commit.
Collecting git+https://github.com/enthought/pyface.git@6a0cac149d56293482bb828a7d98122667c773be (from -r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 4))
  Cloning https://github.com/enthought/pyface.git (to 6a0cac149d56293482bb828a7d98122667c773be) to /private/var/folders/85/kmfd5l4s0z3c8kcpvpj24vq80000gn/T/pip-s1_4p2nm-build
  Could not find a tag or branch '6a0cac149d56293482bb828a7d98122667c773be', assuming commit.
Collecting git+https://github.com/enthought/traitsui.git@e366ad3886d3c39bedb96e83bab447d31c4ab725 (from -r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 5))
  Cloning https://github.com/enthought/traitsui.git (to e366ad3886d3c39bedb96e83bab447d31c4ab725) to /private/var/folders/85/kmfd5l4s0z3c8kcpvpj24vq80000gn/T/pip-anwx2l0h-build
  Could not find a tag or branch 'e366ad3886d3c39bedb96e83bab447d31c4ab725', assuming commit.
Collecting git+https://github.com/enthought/mayavi.git (from -r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 6))
  Cloning https://github.com/enthought/mayavi.git to /private/var/folders/85/kmfd5l4s0z3c8kcpvpj24vq80000gn/T/pip-ox0n7l0e-build
Collecting git+https://github.com/nipy/PySurfer.git (from -r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 7))
  Cloning https://github.com/nipy/PySurfer.git to /private/var/folders/85/kmfd5l4s0z3c8kcpvpj24vq80000gn/T/pip-cgg1b_xu-build
Collecting git+https://github.com/sphinx-gallery/sphinx-gallery.git (from -r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 16))
  Cloning https://github.com/sphinx-gallery/sphinx-gallery.git to /private/var/folders/85/kmfd5l4s0z3c8kcpvpj24vq80000gn/T/pip-o5vg5s44-build
Collecting mne (from -r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 1))
Collecting vtk>=8 (from -r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 2))
  Using cached vtk-8.1.0-cp36-cp36m-macosx_10_6_x86_64.whl
Collecting nitime (from -r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 8))
Collecting nibabel (from -r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 9))
Collecting nilearn (from -r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 10))
  Downloading nilearn-0.4.1.tar.gz (894kB)
    100% |████████████████████████████████| 901kB 1.1MB/s 
Collecting neo (from -r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 11))
Collecting pytest-sugar (from -r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 12))
Collecting pytest-faulthandler (from -r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 13))
  Using cached pytest_faulthandler-1.4.1-py2.py3-none-any.whl
Collecting pydocstyle (from -r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 14))
  Using cached pydocstyle-2.1.1-py3-none-any.whl
Collecting sphinx_bootstrap_theme (from -r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 15))
Collecting apptools (from mayavi==4.5.1.dev0->-r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 6))
Requirement already satisfied: scipy in /anaconda/envs/mne/lib/python3.6/site-packages (from nitime->-r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 8))
Requirement already satisfied: numpy in /anaconda/envs/mne/lib/python3.6/site-packages (from nitime->-r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 8))
Requirement already satisfied: matplotlib in /anaconda/envs/mne/lib/python3.6/site-packages (from nitime->-r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 8))
Collecting quantities>=0.9.0 (from neo->-r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 11))
Requirement already satisfied: pytest>=2.9 in /anaconda/envs/mne/lib/python3.6/site-packages (from pytest-sugar->-r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 12))
Collecting termcolor>=1.1.0 (from pytest-sugar->-r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 12))
Requirement already satisfied: snowballstemmer in /anaconda/envs/mne/lib/python3.6/site-packages (from pydocstyle->-r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 14))
Requirement already satisfied: six in /anaconda/envs/mne/lib/python3.6/site-packages (from pydocstyle->-r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 14))
Requirement already satisfied: setuptools in /anaconda/envs/mne/lib/python3.6/site-packages (from sphinx_bootstrap_theme->-r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 15))
Collecting configobj (from apptools->mayavi==4.5.1.dev0->-r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 6))
Requirement already satisfied: cycler>=0.10 in /anaconda/envs/mne/lib/python3.6/site-packages (from matplotlib->nitime->-r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 8))
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /anaconda/envs/mne/lib/python3.6/site-packages (from matplotlib->nitime->-r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 8))
Requirement already satisfied: python-dateutil>=2.1 in /anaconda/envs/mne/lib/python3.6/site-packages (from matplotlib->nitime->-r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 8))
Requirement already satisfied: pytz in /anaconda/envs/mne/lib/python3.6/site-packages (from matplotlib->nitime->-r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 8))
Requirement already satisfied: kiwisolver>=1.0.1 in /anaconda/envs/mne/lib/python3.6/site-packages (from matplotlib->nitime->-r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 8))
Requirement already satisfied: py>=1.5.0 in /anaconda/envs/mne/lib/python3.6/site-packages (from pytest>=2.9->pytest-sugar->-r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 12))
Requirement already satisfied: attrs>=17.2.0 in /anaconda/envs/mne/lib/python3.6/site-packages (from pytest>=2.9->pytest-sugar->-r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 12))
Requirement already satisfied: pluggy<0.7,>=0.5 in /anaconda/envs/mne/lib/python3.6/site-packages (from pytest>=2.9->pytest-sugar->-r /Users/christian/Downloads/condaenv.jNxuss.requirements.txt (line 12))
Building wheels for collected packages: nilearn
  Running setup.py bdist_wheel for nilearn ... done
  Stored in directory: /Users/christian/Library/Caches/pip/wheels/86/03/b5/34b6d9f4019b690fe7e28fd04ecfe2e4e255a2d8891e8f9fb7
Successfully built nilearn
Installing collected packages: mne, vtk, nitime, nibabel, nilearn, quantities, neo, termcolor, pytest-sugar, pytest-faulthandler, pydocstyle, sphinx-bootstrap-theme, traits, pyface, traitsui, configobj, apptools, mayavi, pysurfer, sphinx-gallery
  Running setup.py install for traits ... done
  Running setup.py install for pyface ... done
  Running setup.py install for traitsui ... done
  Running setup.py install for mayavi ... done
  Running setup.py install for pysurfer ... done
  Running setup.py install for sphinx-gallery ... done
Successfully installed apptools-4.4.0 configobj-5.0.6 mayavi-4.5.1.dev0 mne-0.15.2 neo-0.5.2 nibabel-2.2.1 nilearn-0.4.1 nitime-0.7 pydocstyle-2.1.1 pyface-5.2.0.dev344 pysurfer-0.9.dev0 pytest-faulthandler-1.4.1 pytest-sugar-0.9.1 quantities-0.12.1 sphinx-bootstrap-theme-0.6.4 sphinx-gallery-0.1.13 termcolor-1.1.0 traits-4.7.0.dev73 traitsui-5.2.0.dev403 vtk-8.1.0
#
# To activate this environment, use
#
#     $ conda activate mne
#
# To deactivate an active environment, use
#
#     $ conda deactivate

```

**Comment by christianbrodbeck** [comment]
There is another small weirdnesses though, I can't select anything in a file dialog until I switch to a different App and back.

**Comment by christianbrodbeck** [comment]
> A year or two ago, I would have agreed that switching to Py3k could rightly be considered a long-term goal. Today, however, it feels more like a near-term / immediate goal. 

Okay yes, completely agree :) I would have wanted to switch years ago if it were not for the dependencies. 

> The env installs mne from pip so you probably need to ensure you're actually using the dev version

Yeah I noticed that shortly afterwards (and edited the above post), so even though strange I assume since the env will only go public with 0.16 it should not be an issue. 

The issue with the save dialog is on the dev version though. 

So yeah I see the tradeoffs, I guess I would just lean slightly more on the side of a stable user experience...

**Comment by larsoner** [comment]
> I can't select anything in a file dialog until I switch to a different App and back.
> The issue with the save dialog is on the dev version though.

Argh. Can you see if it's possible to come up with a TraitsUI MWE that replicates this behavior? It's probably a Qt5 problem. I vaguely recall seeing a command-line warning about not having a parent, and even on Linux I think it fails to appear in the foreground (probably from not being properly parented).

I can work on the MWE for the Mayavi bar crash.

Then all users will surely have a stable experience. :)

**Comment by larsoner** [comment]
> Argh. Can you see if it's possible to come up with a TraitsUI MWE that replicates this behavior? 

Actually don't bother. I think I have fixed it by explicitly setting the parent in the `CoregFrameHandler` over in #4971, can you check? All dialogs pop up in front for me now on OSX.

**Comment by christianbrodbeck** [comment]
> Can you see if it's possible to come up with a TraitsUI MWE that replicates this behavior?

Hm it's not easy, a simple `File` trait does not have the error. However `pip install pyqt5` fixes it!

**Comment by larsoner** [comment]
> However pip install pyqt5 fixes it!

Yeah this is what I've effectively added to this `environment.yml`.

**Comment by larsoner** [comment]
@christianbrodbeck are you happy with this version, then?

If so then this is good to go. The Travis failure should be fixed in #5045, but we should probably wait until that's in and rebase this one just to be safe.

**Comment by larsoner** [comment]
Marking as WIP because #4685 should probably go in first

**Comment by larsoner** [comment]
After this PR, Travis, AppVeyor, and CircleCI all now use the same `environment.yml`, which uses a HiDPI-compatible VTK with PyQt5. Hooray!

https://7430-1301584-gh.circle-artifacts.com/0/HTML/html/index.html

@massich @agramfort okay for you to merge once the CIs come back happy?

**Comment by christianbrodbeck** [comment]
It seems to mostly work for the GUIs, the only small issue that I noticed is that the status text ("n points omitted") does not update immediately, but only after switching applications.

**Comment by agramfort** [comment]
GUI works on  my mac too :)

**Comment by larsoner** [comment]
Pinning `qt5` to 5.9.2 to avoid AppVeyor from hanging, see https://github.com/enthought/mayavi/issues/624

**Comment by larsoner** [comment]
Lookin' good:

https://7458-1301584-gh.circle-artifacts.com/0/html/index.html

I'll merge if the remaining CIs come back happy

**Comment by agramfort** [comment]
ok

**Comment by christianbrodbeck** [comment]
Potential issue with Mayavi – for me `brain.set_surf` does not work on this env (for example, starting with http://martinos.org/mne/stable/auto_examples/inverse/plot_dics_source_power.html#sphx-glr-auto-examples-inverse-plot-dics-source-power-py and then calling `brain.set_surf('sphere')`).

**Comment by christianbrodbeck** [comment]
It works on the Python 2.7 `conda-forge` env, (otherwise it would probably not have been merged into PySurfer :) why do you think it ought not to work?

**Comment by larsoner** [comment]
I don't see anywhere that `brain._geo_mesh.coords` actually gets changed. See:

https://github.com/nipy/PySurfer/pull/232

Which fixes it

**Comment by larsoner** [comment]
In any case I think we're safe to fix remaining PySurfer bugs in PySurfer and/or Mayavi

**Comment by mingwandroid** [comment]
@larsoner, you said:

> Once a 3+ Qt5 env (with proper OSX HiDPI) is supported out of the box with Anaconda

Qt 5.9.4 is available now, and it should support OSX HiDPI (but actually so did Qt 5.6 provided you set the right values in Info.plist correctly, see RStudio for an example of how to do that).

**Comment by larsoner** [comment]
Perhaps for matplotlib but for Mayavi (3D viz) I think you also need VTK >=
8 and a sufficiently updated (unreleased AFAIK)
pyface/traits/traitsui/mayavi stack.

>

**Comment by mingwandroid** [comment]
We have VTK 8.1 on the Anaconda Defaults `main` channel, but yes, I hear we need Mayavi (I know what it is, thanks!) 4.5.1.

**Comment by larsoner** [comment]
>  I hear we need Mayavi (I know what it is, thanks!) 4.5.1.

Yep, it's not just this, though -- you also need sufficiently updated Traits/TraitsUI/pyface to handle Qt5. Last I knew they hadn't been released unfortunately.

**Pull request merged**
