### PR TITLE
MRG: Add pip requirements.txt and Travis runs

### PR DESCRIPTION
**Pull request by larsoner**
Let's see how it goes on Linux and OSX.

Eventually we might want to do AppVeyor, too, but this will be more work.

### CODE REVIEW

**Comment by larsoner** [comment]
This PR now does a few things to speed up tests:

1. Speeds up DICS and LCMV tests by subselecting/decimating channels
2. Speeds up CTF reading quite a bit by using NumPy structured arrays
3. Removes old/unused code for FTP file grabbing because we no longer use it (and hopefully never will need to in the future)

Hopefully this will fix the Travis timeouts that I have seen. If not, I'll keep cutting time. It seems like for some reason some tests take *much* longer on the pip/OpenBLAS builds compared to the conda/MKL ones.

**Comment by agramfort** [comment]
we don't test with python 2 anymore?

**Comment by larsoner** [comment]
I can put it back somewhere, but I don't want to add more entries because it will take too long

**Comment by larsoner** [comment]
Oh actually there is still/already a 2.7 run. I just got rid of `environment2.yml` because I don't think we should advertise its use in 0.17, since it will be the last release to support 2.7 anyway.

**Comment by larsoner** [comment]
(and also to make room for another pair of 3.6 runs, this time based on `pip` instead of `conda`. It's currently three more instead of two more because it has been timing out, but this is just temporary so I can identify the tests that are too slow and make them faster)

**Comment by larsoner** [comment]
Okay there are a few really slow tests, here are all the ones over 30 sec from the three splits:
```
204.83s call     mne/io/fiff/tests/test_raw_fiff.py::test_compensation_raw
182.81s call     mne/io/tests/test_compensator.py::test_compensation
89.40s call     mne/inverse_sparse/tests/test_gamma_map.py::test_gamma_map
86.14s call     mne/inverse_sparse/tests/test_gamma_map.py::test_gamma_map_vol_sphere
79.36s call     mne/inverse_sparse/tests/test_mxne_inverse.py::test_mxne_inverse
69.57s call     mne/inverse_sparse/tests/test_mxne_inverse.py::test_mxne_vol_sphere
51.49s call     mne/io/tests/test_compensator.py::test_compensation_mne
41.33s call     mne/forward/tests/test_make_forward.py::test_make_forward_solution_kit
41.00s call     mne/forward/tests/test_make_forward.py::test_make_forward_solution
36.86s call     mne/io/fiff/tests/test_raw_fiff.py::test_compensation_raw_mne
36.19s call     mne/beamformer/tests/test_lcmv.py::test_lcmv_vector
33.68s call     mne/channels/tests/test_interpolation.py::test_interpolation
---
227.65s call     mne/tests/test_cov.py::test_compute_covariance_auto_reg
152.58s call     mne/tests/test_cov.py::test_auto_low_rank
77.81s call     mne/tests/test_epochs.py::test_read_write_epochs
59.68s call     mne/tests/test_epochs.py::test_reject
49.51s call     mne/tests/test_cov.py::test_rank
37.57s call     mne/tests/test_bem.py::test_bem_solution
36.83s call     mne/tests/test_source_space.py::test_setup_source_space
---
96.60s call     mne/preprocessing/tests/test_maxwell.py::test_movement_compensation
89.98s call     mne/minimum_norm/tests/test_inverse.py::test_localization_bias
58.32s call     mne/preprocessing/tests/test_ica.py::test_ica_additional[fastica]
51.93s call     mne/preprocessing/tests/test_maxwell.py::test_other_systems
51.41s call     mne/preprocessing/tests/test_maxwell.py::test_spatiotemporal_only
46.42s call     mne/preprocessing/tests/test_maxwell.py::test_shielding_factor
45.81s call     mne/preprocessing/tests/test_ica.py::test_ica_ctf
43.02s call     mne/preprocessing/tests/test_maxwell.py::test_spatiotemporal
41.92s call     mne/viz/tests/test_3d.py::test_plot_dipole_mri_orthoview
40.03s call     mne/preprocessing/tests/test_ica.py::test_ica_eeg
35.94s call     mne/minimum_norm/tests/test_inverse.py::test_make_inverse_operator_vector
33.09s call     mne/preprocessing/tests/test_maxwell.py::test_cross_talk
32.37s call     mne/minimum_norm/tests/test_inverse.py::test_make_inverse_operator_fixed
30.49s call     mne/viz/tests/test_evoked.py::test_plot_evoked
```
I'm going to see if I can speed at least a few more of these up, then recombine the `pip` runs into two instead of three, then this should be ready for merge.

**Comment by larsoner** [comment]
Okay pushed one more little commit to deal with what I think is a numerical precision problem with OpenBLAS. Ready for review/merge from my end.

FYI the key to speeding things up was `OPENBLAS_NUM_THREADS=1`, it's 2-3x faster here. @agramfort (and @massich ?) at one point you mentioned OpenBLAS was unusable because it was slow for some operations in something you were working on. I think in C you can set this on the fly to 1 and then back to N_CPU (or whatever), in case it's what caused the slowdown for you. Here it was the `linalg.inv` call, which is either `dgetrf` or `dgetri` being slow. And [here](https://github.com/xianyi/OpenBLAS/issues/731) is a related bug report.

**Comment by larsoner** [comment]
FYI now the slow tests (> 20 sec on `conda` or `pip` envs) are:
```
58.06s call     mne/inverse_sparse/tests/test_mxne_inverse.py::test_mxne_inverse
53.03s call     mne/inverse_sparse/tests/test_mxne_optim.py::test_dgapl21l1
46.42s call     mne/forward/tests/test_make_forward.py::test_make_forward_solution_kit
35.50s call     mne/forward/tests/test_make_forward.py::test_make_forward_solution
28.35s call     mne/channels/tests/test_interpolation.py::test_interpolation
25.94s call     mne/tests/test_source_space.py::test_setup_source_space
25.78s call     mne/viz/tests/test_evoked.py::test_plot_evoked
25.69s call     mne/tests/test_source_space.py::test_read_volume_from_src
24.47s call     mne/tests/test_coreg.py::test_scale_mri_xfm
23.08s call     mne/io/fiff/tests/test_raw_fiff.py::test_io_raw
22.96s call     mne/preprocessing/tests/test_ica.py::test_ica_additional[picard]
22.91s call     mne/inverse_sparse/tests/test_mxne_inverse.py::test_mxne_vol_sphere
21.11s call     mne/decoding/tests/test_search_light.py::test_search_light
21.07s call     mne/preprocessing/tests/test_ica.py::test_ica_additional[fastica]
21.05s call     mne/viz/tests/test_3d.py::test_plot_dipole_mri_orthoview
21.02s call     mne/tests/test_epochs.py::test_read_write_epochs
21.02s call     mne/io/artemis123/tests/test_artemis123.py::test_data
20.69s call     mne/tests/test_coreg.py::test_scale_mri
20.17s call     mne/io/bti/tests/test_bti.py::test_raw
```

**Comment by agramfort** [comment]
thx @larsoner !

**Pull request merged**
