### PR TITLE
DOC: Improve the docstrings of multitaper private functions

### PR DESCRIPTION
**Pull request by ruuskas**
I'm relatively new to time-frequency analysis and was struggling while trying to understand the `mne.time_frequency_multitaper` module, especially in the context of MNE-Connectivity. To make understanding the module easier, I propose some minor changes to the docstrings of the private functions.

Most importantly, the return value of `_mt_spectra` was previously documented as follows.
```
Returns
-------
x_mt : array, shape=(..., n_tapers, n_times)
        The tapered spectra
freqs : array
        The frequency points in Hz of the spectra
```
Here, the shape of `x_mt` should be `(..., n_tapers, n_freqs)` as it contains the result of `rfft`.

### CODE REVIEW

**Comment by ruuskas** [comment]
Hi @drammock. Thanks for the comment. Should be fixed now. 

Probably most users won't be digging in the source code that much, but I think this will make things a tiny tiny bit easier to understand for new developers and maintainers.

**Comment by larsoner** [comment]
@ruuskas can you add an entry in `docs/chages/latest.inc` with `:newcontrib:` and your name in `doc/changes/names.inc` so that we can give you proper credit? You can just have an entry saying that you fixed bugs with code documentation or so, no need to link to any methods/functions (they won't work since they're private)

**Comment by ruuskas** [comment]
> @ruuskas can you add an entry in `docs/chages/latest.inc` with `:newcontrib:` and your name in `doc/changes/names.inc` so that we can give you proper credit? You can just have an entry saying that you fixed bugs with code documentation or so, no need to link to any methods/functions (they won't work since they're private)

Done.

**Comment by larsoner** [comment]
Fixed a Sphinx / RST bug and marking for auto-merge, thanks in advance @ruuskas !

**Comment by ruuskas** [comment]
It looks like the CIs are not happy about some unrelated things.

**Comment by larsoner** [comment]
Thanks @ruuskas !

**Pull request merged**
