### PR TITLE
try to fix circle [skip travis]

### PR DESCRIPTION
**Pull request by drammock**
see if this makes the circle build failures go away. (not optimistic...)

### CODE REVIEW

**Comment by larsoner** [comment]
An additional idea would be to upgrade the image to `circleci/python:3.7-buster`

**Comment by drammock** [comment]
What I don't get is why we're seeing this now...  our image isn't using pip 19.3 so I don't get why the recent release would matter.

**Comment by larsoner** [comment]
Okay buster did not work. Next I'd do `pip install --upgrade "pip<19.3"`. It will tell us for sure 19.3 is the problem, and also get things green again while we figure out why

**Comment by drammock** [comment]
OK, removing `pip` from the install line `pip install --user --upgrade --progress-bar off {pip} numpy vtk` seems to have worked

**Comment by larsoner** [comment]
Feel free to open a pypa/pip issue if you feel up to it. Maybe they'll immediately know the problem. In the meantime +1 for merge once CircleCI comes back happy

**Comment by drammock** [comment]
crossref pypa/pip#7205

**Pull request merged**
