### PR TITLE
MRG, ENH: Reduce memory usage of Welch PSD

### PR DESCRIPTION
**Pull request by larsoner**
This:
```
# -*- coding: utf-8 -*-
import os
import mne
sample_data_folder = mne.datasets.sample.data_path()
sample_data_raw_file = os.path.join(sample_data_folder, 'MEG', 'sample',
                                    'sample_audvis_raw.fif')
raw = mne.io.read_raw_fif(sample_data_raw_file)
raw.plot_psd()
data_path = mne.datasets.brainstorm.bst_raw.data_path()
raw_path = (data_path + '/MEG/bst_raw/' +
            'subj001_somatosensory_20111109_01_AUX-f.ds')
raw = mne.io.read_raw_ctf(raw_path).load_data()
raw.plot_psd()
```
Goes from this on `master`:

Screenshot from 2020-07-10 13-02-49

To this:

Screenshot from 2020-07-10 13-03-17

@agramfort feel free to try it on https://github.com/mne-tools/mne-study-template/pull/155

### CODE REVIEW

**Comment by hoechenberger** [comment]
@larsoner This does indeed fix our issue with the study template!

**Comment by larsoner** [comment]
I think you reintroduced a codestyle error I had fixed in `master`

**Comment by larsoner** [comment]
Ahh never mind, guess the "for ext in exts" is okay

**Comment by hoechenberger** [comment]
Thanks @larsoner!

**Pull request merged**
