### PR TITLE
MRG: fix annot->events chunk size

### LINKED ISSUE #6258: `mne.events_from_annotations` returns events that barely overlap with annotation
I noticed that `mne.events_from_annotations` sometimes returns events that barely even overlap with an actual annotation when `chunk_duration` is used. I think this might have been the actual reason behind the issue https://github.com/mne-tools/mne-python/issues/5684#issuecomment-438211200.

The issue seems to arise when an annotation has a duration that is only slightly over `chunk_duration`. A first event will cover almost the entire annotation, but a second annotation will be created that might start within the annotation, but will barely overlap with it. Because of that, in some rare cases, the second event is identical to the next annotation - causing `mne.Epochs` to throw an error due to duplicate events.

#### Steps and/or code to reproduce

```Python
import mne
import numpy as np


# Create fake data with annotations
data = np.random.randn(2, 16000)
info = mne.create_info(
    ch_names=['EEG1', 'EEG2'], ch_types=['eeg', 'eeg'], sfreq=256)
raw = mne.io.RawArray(data, info)

onset = [0, 30]
duration = [30.1, 30]
description = ['0', '0']
annots = mne.Annotations(onset, duration, description)
raw = raw.set_annotations(annots)

# Extract epochs
events, event_ids = mne.events_from_annotations(raw, chunk_duration=30)
epochs = mne.Epochs(
    raw, events, tmin=0, tmax=30, baseline=None, on_missing='warning')
```

#### Expected results
I would have expected `events` to contain two events only: one for the first annotation [0, 30.1] and one for the second [30, 60]. An option would be to have an argument that lets the user decide whether events need to completely overlap with the annotation to be returned.

#### Actual results

`events` is:
```
array([[   0,    0,    1],
       [7680,    0,    1],
       [7680,    0,    1]])
```

Because of the duplicate row, `mne.Epochs` returns `RuntimeError: Event time samples were not unique`.

#### Additional information
```
Platform:      Linux-4.17.13-041713-generic-x86_64-with-debian-buster-sid
Python:        3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51)  [GCC 7.2.0]
Executable:    /home/hubert/miniconda3/envs/dl-eeg/bin/python
CPU:           x86_64: 4 cores
Memory:        15.6 GB

mne:           0.18.dev0
numpy:         1.16.0 {blas=openblas, lapack=openblas}
scipy:         1.1.0
matplotlib:    2.2.3 {backend=TkAgg}

sklearn:       0.20.2
nibabel:       Not found
mayavi:        4.6.2 {qt_api=pyqt5, PyQt5=5.11.3}
cupy:          Not found
pandas:        0.23.4
dipy:          Not found
```

### PR DESCRIPTION
**Pull request by mmagnuski**
Closes #6258

Could also allow additional argument - `min_chunk_duration` (a bit shorter than `chunk_duration` by default for example 85%).
But in its current shape it seems to be simple enough. I could add warnings if some annotations cannot generate events due to chunk_size being too long.

- [x] add test
- [x] add warning when some annotations do not contribute any events?
- [x] decide whether to expose control over min chunk duration

### CODE REVIEW

**Comment by mmagnuski** [comment]
The CI failure is irrelevant: `RuntimeError: URL could not be parsed properly (total size 27905 != file size 1)` in `test_constants`.

**Comment by mmagnuski** [comment]
@massich @agramfort any thoughts?

**Comment by agramfort** [comment]
looks ok to me.

@hubertjb can you confirm it fixes your pb?

**Comment by mmagnuski** [comment]
@agramfort - do you think we should warn when some annotations do not produce any events due to the `chunk_size` requirement?

**Comment by jona-sassenhagen** [comment]
>@agramfort - do you think we should warn when some annotations do not produce any events due to the chunk_size requirement?

I would think so, right? What speaks against?

**Comment by agramfort** [comment]
I think the docstring is pretty explicit. It makes events from annotations
whose duration is larger than chunk_size.
Clarify even more the docstring if you feel it's needed.

>

**Comment by mmagnuski** [comment]
Ok, changed the docs a bit to make it clearer.

**Comment by mmagnuski** [comment]
Thanks all! 🚀

**Pull request merged**
