### PR TITLE
[ENH, MRG] Add `node_height` keyword argument

### PR DESCRIPTION
**Pull request by alexrockhill**
It would be nice if you could control the node heights, I have smaller subplots and they are too small for my figure. It looks like the code is duplicated in `mne-connectivity`... any thought on how that would be refactored ideally? All in `mne-python` might be easiest... I can work a bit on that since I'm pushing to mess up the duplication.

### CODE REVIEW

**Comment by alexrockhill** [comment]
Ok, my opinion would be to add the circle plotting back to `mne-python` but maybe call it something more general like `plot_circle` and have a connectivity argument. The use case that I'm running into wanting to change these things so that I can make my plots is not connectivity or electrode relations--it's linking high-level features to their anatomical locations. I think a circle plot would be useful fo that kind of thing.

**Comment by alexrockhill** [comment]
Well maybe that would be difficult to do both labels and connectivity in a nice API. There is a lot of super-useful high-level code that plots labels around a circle and connects them and it would be nice to abstract that outside of connectivity but I will just leave this be for now, maybe we can talk about it soon.

**Comment by alexrockhill** [comment]
It also needs to be fixed that the keyword arguments for `plot_channel_labels_circle` reference `plot_connectivity_circle` with no intersphinx. I would add the reference from MNE-connectivity but the keyword arguments don't actually go there, they go to the internal `_plot_connectivity_circle` so I think this should really be exposed if we're going to keep `plot_channel_labels_circle`.

**Comment by alexrockhill** [comment]
So there is an issue with the `axis` type being cartesian which makes it so that axis has to be removed and replaced. Now that I'm writing this, I'm realizing we should just require the axis to be `polar`. I'll change that now.

https://stackoverflow.com/questions/33942233/how-do-i-change-matplotlibs-subplot-projection-of-an-existing-axis

**Comment by agramfort** [comment]
@alexrockhill can you share a picture to see how it looks now compared to before?

**Comment by alexrockhill** [comment]
feature_labels

**Comment by alexrockhill** [comment]
You can do something like that. I just shared the whole figure because it shows how you can change the heights and the labels fit but then why you would want to change the heights as in the case in the figure.

**Comment by agramfort** [comment]
that's pretty neat !

feel free to merge if you're happy with it

**Pull request merged**
