### PR TITLE
BUG: don't assume that channel info contains particular keys

### LINKED ISSUE #11039: read_raw_eeglab stopped working in MNE 1.1
I just updated to MNE 1.1 and I found I can no longer run read_raw_eeglab. It spits out an error message, instead of loading my file. Here's what spits out:

```
raw = mne.io.read_raw_eeglab(rawfile,preload=True)
Traceback (most recent call last):

  File "/var/folders/6l/0_b631dn2q7d_wfw636xsp7w0000gq/T/ipykernel_1591/1431119611.py", line 1, in <module>
    raw = mne.io.read_raw_eeglab(rawfile,preload=True)

  File "/Users/ivy/miniconda3/lib/python3.7/site-packages/mne/io/eeglab/eeglab.py", line 263, in read_raw_eeglab
    eog=eog, verbose=verbose, uint16_codec=uint16_codec)

  File "<decorator-gen-399>", line 12, in __init__

  File "/Users/ivy/miniconda3/lib/python3.7/site-packages/mne/io/eeglab/eeglab.py", line 368, in __init__
    info, eeg_montage, _ = _get_info(eeg, eog=eog)

  File "/Users/ivy/miniconda3/lib/python3.7/site-packages/mne/io/eeglab/eeglab.py", line 185, in _get_info
    _get_montage_information(eeg, has_pos)

  File "/Users/ivy/miniconda3/lib/python3.7/site-packages/mne/io/eeglab/eeglab.py", line 154, in _get_montage_information
    elif d['description'] == 'Nasion':

KeyError: 'description'
```

The problem is with the function _get_montage_information, specifically the set of code:

```python
    lpa, rpa, nasion = None, None, None
    if (hasattr(eeg, "chaninfo") and
            "nodatchans" in eeg.chaninfo and
            len(eeg.chaninfo['nodatchans'])):
        for item in list(zip(*eeg.chaninfo['nodatchans'].values())):
            d = dict(zip(eeg.chaninfo['nodatchans'].keys(), item))
            if d["type"] != 'FID':
                continue
            elif d['description'] == 'Nasion':
                nasion = np.array([d["X"], d["Y"], d["Z"]])
            elif d['description'] == 'Right periauricular point':
                rpa = np.array([d["X"], d["Y"], d["Z"]])
            elif d['description'] == 'Left periauricular point':
                lpa = np.array([d["X"], d["Y"], d["Z"]])
```

To investigate, I ran this code:

```python
for item in list(zip(*eeg.chaninfo['nodatchans'].values())):
    d = dict(zip(eeg.chaninfo['nodatchans'].keys(), item))
    print(d)
    print('')
```

And got:
```
{'labels': 'FidNz', 'Y': -0.0, 'X': 11.331284, 'Z': -1.4538770000000003, 'sph_theta': -0.0, 'sph_phi': -7.311471770814621, 'sph_radius': 11.424174167955643, 'theta': 0, 'radius': 0.5406192876156368, 'type': 'FID', 'ref': array([], dtype='<U1'), 'urchan': 1, 'datachan': 0}

{'labels': 'FidT9', 'Y': 7.519939000000001, 'X': 1.4731859999999999, 'Z': -2.59104, 'sph_theta': 78.91590242180789, 'sph_phi': -18.68186885137234, 'sph_radius': 8.089082014414059, 'theta': -78.91590242180789, 'radius': 0.6037881602854018, 'type': 'FID', 'ref': array([], dtype='<U1'), 'urchan': 2, 'datachan': 0}

{'labels': 'FidT10', 'Y': -7.519939000000001, 'X': 1.4731859999999999, 'Z': -2.59104, 'sph_theta': -78.91590242180789, 'sph_phi': -18.68186885137234, 'sph_radius': 8.089082014414059, 'theta': 78.91590242180789, 'radius': 0.6037881602854018, 'type': 'FID', 'ref': array([], dtype='<U1'), 'urchan': 3, 'datachan': 0}

{'labels': 'Cz', 'Y': 0, 'X': 6.285744013660221e-16, 'Z': 10.265399, 'sph_theta': 0, 'sph_phi': 90, 'sph_radius': 10.265399, 'theta': -0.0, 'radius': 0, 'type': array([], dtype='<U1'), 'ref': array([], dtype='<U1'), 'urchan': 68, 'datachan': 0}
```

As you can see, no 'description', so the code fails when you try to run `d['description']`.

This might be a problem very specific to me; someone in my lab wrote a matlab script to convert the data we get from the eeg cap into a .set file, and perhaps their code isn't quite right.

### PR DESCRIPTION
**Pull request by smathot**
#### What does this implement/fix?

Load a specific `.set` file broke in the latest release of MNE. The reason is a regression introduced along with 5e60e475ef8019af73cc81e184a10bde524c681f, which assumes that certain fields exist, thus resulting in a crash when they don't. It's possible that my `.set` is non-standard, I'm not familiar enough with the format to be able to say that, but this PR seems safe enough in any case.

closes #11039

### CODE REVIEW

**Comment by drammock** [comment]
was just discussing this yesterday (with @larsoner and @agramfort).  We thought it best to treat the unidentified fiducials as regular headshape points (rather than ignoring them entirely) and add a warning that this was being done.

**Comment by smathot** [comment]
I don't understand everything in that sentence :wink: But sure, as long as it doesn't crash any solution is fine with me. I'll take a look at #11039, which had escaped my attention. Do you want to close this PR?

**Comment by drammock** [comment]
Sorry, I dashed off my reply in a hurry. No need to close this PR, it's 90% of the way there. What I meant was: the fields in question are fiducials ("fids"), AKA cardinal anatomical landmarks. "Headshape points" are other digitized points located elsewhere on the scalp or face. Together they are all used to coregister electrode locations with an MRI image. If the fiducials are present in an EEGLAB file, but their description is empty (so we don't know for certain which is left/right ear (LPA/RPA) and which is nose (NAS), then instead of simply discarding the information, we can/should treat them as regular (unlabelled) headshape points.

However, looking at the `_get_montage_information` function that you've edited here, I don't see headshape points being handled at all (which makes sense in retrospect; those aren't used when creating the montage).  So perhaps your proposed changes are enough after all.  I'll let @larsoner and/or @agramfort decide whether it makes sense to do the "fids as headshape points" change here, or in a different PR.

(side note: it seems like it ought to be possible to simply infer from the XYZ values which of the fids is which. @agramfort / @larsoner WDYT about, e.g., inferring that RPA is the fid point with the highest X value, NAS is the one with the highest Y value, and LPA is the other one?)

**Comment by larsoner** [comment]
>  inferring that RPA is the fid point with the highest X value, NAS is the one with the highest Y value, and LPA is the other one? Can we safely assume the pts are in head coord frame?

Unfortunately it's unsafe because we can't assume the points are near the head coordinate frame. They probably usually are, but sometimes might be quite far from it

> I'll let @larsoner and/or @agramfort decide whether it makes sense to do the "fids as headshape points" change here, or in a different PR.

I think it would be nice to fix it here. Feel free to give it a shot if you're up for it @smathot , or I can push some commits if you want help

**Review by larsoner — APPROVED** [review]
I just pushed a small commit to update `latest.inc`, `names.inc`, and add a test that fails on `main` but passes on this PR (following TDD). Will merge once green, thanks for the quick fix @smathot !

**Comment by drammock** [comment]
@smathot just to close the loop: @larsoner, @agramfort and I discussed in person and realized that past behavior before #10521 was to ignore these points, so we'll continue to ignore them now (i.e., not try to treat as headshape points). Hence no further changes needed here.

**Comment by smathot** [comment]
Thanks for handling this so quickly! :partying_face:

**Pull request merged**
