### PR TITLE
DOC: evoked.plot_ plot lim docs

### PR DESCRIPTION
**Pull request by jona-sassenhagen**
Fix docstring for evoked plotting lims. Alternative to #2823

(Sorry if this isn't the proper way ...)

@jasmainak @teonlamont

### CODE REVIEW

**Comment by agramfort** [comment]
maybe mention the unit of uV after scaling for EEG?

**Comment by jona-sassenhagen** [comment]
E.g.
```
ylim for plots (after scaling has been applied). e.g. ylim = dict(eeg=[-20, 20]) to plot EEG data with plot limits from -20 to 20 uV (assuming default scaling of 1e6 for EEG)
```
?

Could also be argued this belongs in the `scalings` param.

**Comment by jona-sassenhagen** [comment]
I'm not sure, but the line after is possibly wrong:
```
Valid keys are eeg, mag, grad, misc.
```
I don't have seeg data, but I think that would also be an acceptable key? @choldgraf ?

**Comment by choldgraf** [comment]
I am always for supporting seeg and ecog :)  aren't those planned to be added as "official" channel types?

**Comment by jona-sassenhagen** [comment]
No idea - but the code checks for `seeg`, but not for `misc`, in line 187:
```channel_types = ['eeg', 'grad', 'mag', 'seeg']```

**Comment by jona-sassenhagen** [comment]
Maybe just merge as-is and fix seeg/channel type stuff later.

**Comment by choldgraf** [comment]
Yeah, I assume that adding support for seeg/ecog (or maybe just a single channel type called ieeg?) is going to take a fair amount of looking through code to see when it's appropriate to treat differently.

**Comment by agramfort** [comment]
On Wed, Jan 27, 2016 at 6:05 PM, jona-sassenhagen <notifications@github.com>
wrote:

> Could also be argued this belongs in the scalings param.
>

ok point taken.

LGTM then

**Comment by jona-sassenhagen** [comment]
@jasmainak can you merge if you and Travis are happy?

**Comment by agramfort** [comment]
thx @jona-sassenhagen

**Comment by jasmainak** [comment]
Thanks @jona-sassenhagen for taking care of it!

**Pull request merged**
