### PR TITLE
MRG+1: Fix re-raising of errors

### PR DESCRIPTION
**Pull request by Eric89GXL**
FYI when using this pattern:
```
try:
    ...
except Exception as exp:
    ...
    raise exp
```
it gives a better traceback just to do at the end:
```
    raise
```
because then the proper/full traceback is given, instead of a traceback pointing only to the `raise exp` line (i.e., better than what we see in https://github.com/mne-tools/mne-python/issues/3945).

I already pushed https://github.com/mne-tools/mne-python/commit/f1fb89636a7086f2ecbe32e5da58b509cc770605 directly to master without realizing there were other occurrences in our code.

### CODE REVIEW

**Comment by christianbrodbeck** [comment]
Good to know, thanks! PR looks good to me.

**Comment by Eric89GXL** [comment]
@christianbrodbeck FYI we usually set title to `MRG+N` when giving approval nowadays. I'll do it for you here :)

**Comment by christianbrodbeck** [comment]
Thanks :)

**Comment by agramfort** [comment]
LGTM

merge when travis is happy

**Comment by Eric89GXL** [comment]
I killed Travis -- all builds passed except OSX that hadn't started yet after hours of waiting.

**Pull request merged**
